Repository idaholab/moose, pull requests merged in 2018-02, with the labels that each got.

#10741 broken break unbroken
  modules/porous_flow/src/auxkernels/PorousFlowPropertyAux.C
Labels: PR: Failed but allowed

#10730 Adding API for setting output dimension
  framework/include/outputs/Exodus.h
  framework/src/outputs/Exodus.C
Labels: PR: Failed but allowed

#10754 Continue explicitly enabling OpenMP.
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed

#10753 Skip heat conduction recover test in PBS mode
  modules/heat_conduction/test/tests/recover/tests
Labels: PR: Failed but allowed

#10749 Extend ReferenceResidualProblem to work with generalized plane strain
  docs/content/documentation/systems/AuxScalarKernels/tensor_mechanics/GeneralizedPlaneStrainReferenceResidual.md
  modules/combined/test/tests/generalized_plane_strain_tm_contact/gold/out_of_plane_pressure_out.e
  modules/combined/test/tests/generalized_plane_strain_tm_contact/out_of_plane_pressure.i
  modules/combined/test/tests/generalized_plane_strain_tm_contact/tests
  modules/contact/src/ReferenceResidualProblem.C
  modules/tensor_mechanics/include/auxkernels/GeneralizedPlaneStrainReferenceResidual.h
  modules/tensor_mechanics/include/userobjects/GeneralizedPlaneStrainUserObject.h
  modules/tensor_mechanics/src/auxkernels/GeneralizedPlaneStrainReferenceResidual.C
  modules/tensor_mechanics/src/base/TensorMechanicsApp.C
  modules/tensor_mechanics/src/userobjects/GeneralizedPlaneStrainUserObject.C
Labels: PR: Ready to Merge

#10735 Fixing parser bugs
  framework/contrib/hit/parse.cc
  framework/contrib/hit/parse.h
  framework/src/parser/Parser.C
  modules/navier_stokes/test/tests/ins/jeffery_hamel/wedge_dirichlet.i
  test/tests/controls/time_periods/error/control.i
  test/tests/time_steppers/iteration_adaptive/adapt_tstep_grow_dtfunc.i
  test/tests/time_steppers/iteration_adaptive/adapt_tstep_grow_dtfunc_restart.i
  unit/include/BrineFluidPropertiesTest.h
  unit/include/CO2FluidPropertiesTest.h
  unit/include/ColumnMajorMatrixTest.h
  unit/include/DependencyResolverTest.h
  unit/include/EBSDAccessFunctorsTest.h
  unit/include/EBSDMeshErrorTest.h
  unit/include/IdealGasFluidPropertiesPTTest.h
  unit/include/IdealGasFluidPropertiesTest.h
  unit/include/IsotropicElasticityTensorTest.h
  unit/include/LineSegmentTest.h
  unit/include/MethaneFluidPropertiesTest.h
  unit/include/NaClFluidPropertiesTest.h
  unit/include/ParsedFunctionTest.h
  unit/include/PorousFlowBrineCO2Test.h
  unit/include/PorousFlowFluidStateFlashTest.h
  unit/include/PorousFlowWaterNCGTest.h
  unit/include/RankTwoTensorTest.h
  unit/include/SimpleFluidPropertiesTest.h
  unit/include/SodiumPropertiesTest.h
  unit/include/StiffenedGasFluidPropertiesTest.h
  unit/include/TabulatedFluidPropertiesTest.h
  unit/include/Water97FluidPropertiesTest.h
  unit/include/gtest_include.h
  unit/src/BrentsMethodTest.C
  unit/src/HitTests.C
  unit/src/MinimalApp.C
Labels: PR: Ready to Merge

#10803 Quick temporary implementation of requirements per test spec file
  docs/content/documentation/sqa/moose_srs.md
  python/MooseDocs/extensions/sqa.py
  python/TestHarness/testers/Tester.py
  test/tests/markers/box_marker/tests
Labels: PR: Ready to Merge

#10815 Fixup compiler warnings
  framework/include/utils/MooseUtils.h
  framework/src/base/Assembly.C
  framework/src/base/MooseVariableConstMonomial.C
  framework/src/geomsearch/GeometricSearchData.C
  framework/src/meshmodifiers/ElementDeleterBase.C
  framework/src/parser/Parser.C
Labels: PR: Ready to Merge

#10725 Change the steady state detection parameter names
  docs/content/documentation/systems/Executioner/framework/Transient.md
  framework/include/executioners/Transient.h
  framework/src/executioners/Transient.C
  modules/navier_stokes/test/tests/ins/mms/supg/supg_pspg_adv_dominated_mms.i
  modules/tensor_mechanics/test/tests/cp_user_object/crysp.i
  modules/tensor_mechanics/test/tests/cp_user_object/crysp_exception.i
  modules/tensor_mechanics/test/tests/cp_user_object/crysp_fileread.i
  modules/tensor_mechanics/test/tests/cp_user_object/crysp_linesearch.i
  modules/tensor_mechanics/test/tests/cp_user_object/crysp_save_euler.i
  modules/tensor_mechanics/test/tests/cp_user_object/crysp_substep.i
  modules/tensor_mechanics/test/tests/cp_user_object/crysp_user_object.i
  modules/tensor_mechanics/test/tests/elem_prop_read_user_object/prop_elem_read.i
  modules/tensor_mechanics/test/tests/elem_prop_read_user_object/prop_grain_read.i
  modules/tensor_mechanics/test/tests/elem_prop_read_user_object/prop_grain_read_3d.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic/finite_strain_elastic_eigen_sol.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic/finite_strain_elastic_new_test.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic/finite_strain_fake_plastic.i
  test/tests/executioners/executioner/steady_state_check_test.i
  test/tests/postprocessors/relative_solution_difference_norm/test.i
  test/tests/time_integrators/abort/abort.i
  test/tests/time_integrators/aee/aee.i
Labels: PR: Failed but allowed, PR: Ready to Merge

#10793 Output variable residuals on non-linear as intended
  framework/src/outputs/VariableResidualNormsDebugOutput.C
  test/tests/outputs/debug/tests
Labels: PR: Ready to Merge

#10771 Rename FaceFaceConstraint
  framework/include/constraints/ConstraintWarehouse.h
  framework/include/constraints/EqualGradientConstraint.h
  framework/include/constraints/EqualValueConstraint.h
  framework/include/constraints/FaceFaceConstraint.h
  framework/include/constraints/MortarConstraint.h
  framework/src/base/NonlinearSystemBase.C
  framework/src/constraints/ConstraintWarehouse.C
  framework/src/constraints/EqualGradientConstraint.C
  framework/src/constraints/EqualValueConstraint.C
  framework/src/constraints/FaceFaceConstraint.C
  framework/src/constraints/MortarConstraint.C
  modules/heat_conduction/include/constraints/GapConductanceConstraint.h
  modules/heat_conduction/src/constraints/GapConductanceConstraint.C
Labels: PR: Ready to Merge

#10824 Fixed bug related to displaced_problem in reinitNeighborPhys
  framework/src/base/FEProblemBase.C
Labels: PR: Ready to Merge

#10855 Loosen tolerances to pass 64 bit dof tests
  test/tests/kernels/vector_fe/tests
Labels: PR: Failed but allowed, PR: Ready to Merge

#10859 Prescribed directions for smeared cracking
  modules/tensor_mechanics/include/materials/ComputeSmearedCrackingStress.h
  modules/tensor_mechanics/src/materials/ComputeSmearedCrackingStress.C
  modules/tensor_mechanics/test/tests/smeared_cracking/cracking_function.cmp
  modules/tensor_mechanics/test/tests/smeared_cracking/cracking_rotation.cmp
  modules/tensor_mechanics/test/tests/smeared_cracking/cracking_rotation.i
  modules/tensor_mechanics/test/tests/smeared_cracking/gold/cracking_plane_stress_out.e
  modules/tensor_mechanics/test/tests/smeared_cracking/tests
Labels: PR: Failed but allowed

#10876 Loosen absolute exodiff tolerance for parallel sweeps
  test/tests/kernels/vector_fe/tests
Labels: PR: Ready to Merge

#10884 Fix transfer in step 10 of darcy tutorial
  tutorials/darcy_thermo_mech/step10_multiapps/problems/step10.i
  tutorials/darcy_thermo_mech/step10_multiapps/problems/step10_micro.i
Labels: PR: Ready to Merge

#10875 Overhaul the restartable interface
  framework/include/base/MooseApp.h
  framework/include/base/SubProblem.h
  framework/include/controls/Control.h
  framework/include/restart/DataIO.h
  framework/include/restart/Restartable.h
  framework/include/restart/RestartableData.h
  framework/include/restart/RestartableDataIO.h
  framework/src/auxkernels/AuxKernel.C
  framework/src/base/FEProblemBase.C
  framework/src/base/MooseApp.C
  framework/src/base/SubProblem.C
  framework/src/bcs/BoundaryCondition.C
  framework/src/constraints/Constraint.C
  framework/src/controls/Control.C
  framework/src/dampers/Damper.C
  framework/src/dgkernels/DGKernel.C
  framework/src/dirackernels/DiracKernel.C
  framework/src/executioners/Executioner.C
  framework/src/functions/Function.C
  framework/src/geomsearch/NearestNodeLocator.C
  framework/src/geomsearch/PenetrationLocator.C
  framework/src/ics/InitialCondition.C
  framework/src/indicators/Indicator.C
  framework/src/interfacekernels/InterfaceKernel.C
  framework/src/kernels/KernelBase.C
  framework/src/markers/Marker.C
  framework/src/materials/Material.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshmodifiers/MeshModifier.C
  framework/src/multiapps/MultiApp.C
  framework/src/nodalkernels/NodalKernel.C
  framework/src/outputs/Checkpoint.C
  framework/src/outputs/Output.C
  framework/src/partitioner/MoosePartitioner.C
  framework/src/postprocessors/PostprocessorData.C
  framework/src/preconditioners/MoosePreconditioner.C
  framework/src/predictors/Predictor.C
  framework/src/restart/Restartable.C
  framework/src/restart/RestartableDataIO.C
  framework/src/splits/Split.C
  framework/src/timeintegrators/TimeIntegrator.C
  framework/src/timesteppers/TimeStepper.C
  framework/src/transfers/Transfer.C
  framework/src/userobject/UserObject.C
  framework/src/vectorpostprocessors/VectorPostprocessorData.C
  modules/functional_expansion_tools/include/coefficients/MutableCoefficientsInterface.h
  modules/functional_expansion_tools/include/functions/MutableCoefficientsFunctionInterface.h
  modules/functional_expansion_tools/include/userobject/FXIntegralBaseUserObject.h
  modules/functional_expansion_tools/src/coefficients/MutableCoefficientsInterface.C
  modules/functional_expansion_tools/src/functions/FunctionSeries.C
  modules/functional_expansion_tools/src/functions/MutableCoefficientsFunctionInterface.C
Labels: PR: Failed but allowed

#10879 Added PiecewiseBase class for generalization of Piecewise functions
  framework/include/functions/Piecewise.h
  framework/include/functions/PiecewiseBase.h
  framework/include/timesteppers/IterationAdaptiveDT.h
  framework/src/functions/Piecewise.C
  framework/src/functions/PiecewiseBase.C
  framework/src/timesteppers/IterationAdaptiveDT.C
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed

#10849 add mesh splitting tests
  test/include/userobjects/SplitTester.h
  test/src/base/MooseTestApp.C
  test/src/userobjects/SplitTester.C
  test/tests/mesh/splitting/gold/simple_diffusion_out.e
  test/tests/mesh/splitting/simple_diffusion.i
  test/tests/mesh/splitting/tests
Labels: PR: Failed but allowed

#10840 Shorten up a few longer tests and create a little doco.
  docs/content/documentation/systems/ICs/phase_field/MultiSmoothCircleIC.md
  modules/phase_field/include/ics/MultiSmoothCircleIC.h
  modules/phase_field/test/tests/MultiSmoothCircleIC/gold/multismoothcircleIC_normal_test_out.e
  modules/phase_field/test/tests/MultiSmoothCircleIC/gold/multismoothcircleIC_test_out.e
  modules/phase_field/test/tests/MultiSmoothCircleIC/latticesmoothcircleIC_normal_test.i
  modules/phase_field/test/tests/MultiSmoothCircleIC/multismoothcircleIC_normal_test.i
  modules/phase_field/test/tests/MultiSmoothCircleIC/multismoothcircleIC_test.i
  test/tests/bcs/periodic/gold/level1.e
  test/tests/bcs/periodic/gold/level1.e-s005
  test/tests/bcs/periodic/gold/level1.e-s010
  test/tests/bcs/periodic/gold/periodic_level_1_test_out.e
  test/tests/bcs/periodic/gold/periodic_level_1_test_out.e-s004
  test/tests/bcs/periodic/gold/periodic_level_1_test_out.e-s007
  test/tests/bcs/periodic/periodic_level_1_test.i
  test/tests/bcs/periodic/tests
  test/tests/multiapps/picard_sub_cycling/gold/picard_master_out.e
  test/tests/multiapps/picard_sub_cycling/picard_master.i
  test/tests/multiapps/picard_sub_cycling/picard_sub.i
Labels: PR: Failed but allowed, PR: Ready to Merge

#10892 Get rid of warnings on older compilers
  framework/include/mesh/AnnularMesh.h
  framework/include/mesh/GeneratedMesh.h
  framework/include/utils/MooseEnumItem.h
  modules/phase_field/include/postprocessors/FeatureFloodCount.h
  modules/phase_field/include/utils/PolycrystalICTools.h
Labels: PR: Ready to Merge
