Repository idaholab/moose, pull requests merged in 2018-03, with the labels that each got.

#10481 Mesh-based cutter class with growth capability
  docs/content/documentation/systems/UserObjects/xfem/MeshCut3DUserObject.md
  modules/xfem/include/base/XFEMFuncs.h
  modules/xfem/include/userobjects/GeometricCutUserObject.h
  modules/xfem/include/userobjects/MeshCut3DUserObject.h
  modules/xfem/src/base/XFEMApp.C
  modules/xfem/src/base/XFEMFuncs.C
  modules/xfem/src/userobjects/MeshCut3DUserObject.C
  modules/xfem/test/tests/solid_mechanics_basic/edge_crack_3d_mesh.i
  modules/xfem/test/tests/solid_mechanics_basic/gold/edge_crack_3d_mesh_out.e
  modules/xfem/test/tests/solid_mechanics_basic/gold/mesh_grow.e
  modules/xfem/test/tests/solid_mechanics_basic/mesh_edge_crack.xda
  modules/xfem/test/tests/solid_mechanics_basic/mesh_grow.i
  modules/xfem/test/tests/solid_mechanics_basic/mesh_grow.xda
  modules/xfem/test/tests/solid_mechanics_basic/tests
Labels: PR: Failed but allowed

#10962 Exclusively used new fluid property interfaces in modules
  modules/fluid_properties/src/auxkernels/SpecificEnthalpyAux.C
  modules/fluid_properties/src/auxkernels/StagnationPressureAux.C
  modules/fluid_properties/src/auxkernels/StagnationTemperatureAux.C
  modules/fluid_properties/src/materials/FluidPropertiesMaterial.C
  modules/fluid_properties/src/userobjects/TwoPhaseFluidProperties.C
  modules/fluid_properties/test/include/kernels/InternalEnergyFromVolumeEnthalpyDerivativesTestKernel.h
  modules/fluid_properties/test/src/base/FluidPropertiesTestApp.C
  modules/fluid_properties/test/src/kernels/InternalEnergyFromVolumeEnthalpyDerivativesTestKernel.C
  modules/fluid_properties/test/src/kernels/SoundSpeedFromVolumeEnthalpyDerivativesTestKernel.C
  modules/fluid_properties/test/src/kernels/SoundSpeedFromVolumeInternalEnergyDerivativesTestKernel.C
  modules/fluid_properties/test/tests/ideal_gas/e_from_v_h_derivatives.i
  modules/fluid_properties/test/tests/ideal_gas/tests
  modules/fluid_properties/test/tests/stiffened_gas/e_from_v_h_derivatives.i
  modules/fluid_properties/test/tests/stiffened_gas/tests
  modules/navier_stokes/src/auxkernels/NSMachAux.C
  modules/navier_stokes/src/auxkernels/NSPressureAux.C
  modules/navier_stokes/src/auxkernels/NSTemperatureAux.C
  modules/navier_stokes/src/bcs/NSWeakStagnationBaseBC.C
  modules/navier_stokes/src/ics/NSInitialCondition.C
  modules/navier_stokes/src/materials/NavierStokesMaterial.C
Labels: PR: Failed but allowed

#10963 Fluid property interfaces changes, Part 2
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
Labels: PR: Failed but allowed

#10971 Added missing ideal gas interfaces
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  unit/include/IdealGasFluidPropertiesTest.h
  unit/include/SinglePhaseFluidPropertiesUtils.h
  unit/include/StiffenedGasFluidPropertiesTest.h
  unit/src/IdealGasFluidPropertiesTest.C
  unit/src/StiffenedGasFluidPropertiesTest.C
Labels: PR: Failed but allowed

#10970 Get_Repo_Revision.py: about twice as fast, more work to do
  examples/ex01_inputfile/Makefile
  examples/ex02_kernel/Makefile
  examples/ex03_coupling/Makefile
  examples/ex04_bcs/Makefile
  examples/ex05_amr/Makefile
  examples/ex06_transient/Makefile
  examples/ex07_ics/Makefile
  examples/ex08_materials/Makefile
  examples/ex09_stateful_materials/Makefile
  examples/ex10_aux/Makefile
  examples/ex11_prec/Makefile
  examples/ex12_pbp/Makefile
  examples/ex13_functions/Makefile
  examples/ex14_pps/Makefile
  examples/ex15_actions/Makefile
  examples/ex16_timestepper/Makefile
  examples/ex17_dirac/Makefile
  examples/ex18_scalar_kernel/Makefile
  examples/ex19_dampers/Makefile
  examples/ex20_user_objects/Makefile
  examples/ex21_debugging/Makefile
  framework/app.mk
  framework/scripts/get_repo_revision.py
  modules/Makefile
  modules/chemical_reactions/Makefile
  modules/combined/Makefile
  modules/contact/Makefile
  modules/fluid_properties/Makefile
  modules/functional_expansion_tools/Makefile
  modules/functional_expansion_tools/unit/Makefile
  modules/heat_conduction/Makefile
  modules/level_set/Makefile
  modules/misc/Makefile
  modules/module_loader/Makefile
  modules/modules.mk
  modules/navier_stokes/Makefile
  modules/phase_field/Makefile
  modules/porous_flow/Makefile
  modules/rdg/Makefile
  modules/richards/Makefile
  modules/solid_mechanics/Makefile
  modules/stochastic_tools/Makefile
  modules/tensor_mechanics/Makefile
  modules/water_steam_eos/Makefile
  modules/xfem/Makefile
  stork/Makefile.app
  stork/Makefile.module
  test/Makefile
  tutorials/darcy_thermo_mech/step01_diffusion/Makefile
  tutorials/darcy_thermo_mech/step01_diffusion/unit/Makefile
Labels: PR: Failed but allowed

#10980 Adding surface tension property
  modules/fluid_properties/include/userobjects/LiquidFluidPropertiesInterface.h
Labels: PR: Failed but allowed

#10984 Fixing my own brain damage
  framework/scripts/get_repo_revision.py
Labels: PR: Failed but allowed

#10978 Allow mesh adaptivity with interface kernels
  framework/include/base/FEProblemBase.h
  framework/src/base/ComputeResidualThread.C
  framework/src/base/FEProblemBase.C
  test/tests/dgkernels/adaptivity/adaptivity.i
  test/tests/dgkernels/adaptivity/gold/adaptivity_out.e
  test/tests/dgkernels/adaptivity/gold/adaptivity_out.e-s002
  test/tests/dgkernels/adaptivity/tests
  test/tests/interfacekernels/adaptivity/adaptivity.i
  test/tests/interfacekernels/adaptivity/gold/adaptivity_out.e
  test/tests/interfacekernels/adaptivity/gold/adaptivity_out.e-s002
  test/tests/interfacekernels/adaptivity/tests
Labels: PR: Failed but allowed, PR: Ready to Merge

#10986 Fix inheritance of CoupledBEKinetic
  modules/chemical_reactions/include/kernels/CoupledBEKinetic.h
  modules/chemical_reactions/src/kernels/CoupledBEKinetic.C
  modules/chemical_reactions/test/tests/solid_kinetics/gold/2species_out.e
Labels: PR: Failed but allowed

#11012 Move viscosity derivative calculation from PorousFlow to FluidProperties
  modules/fluid_properties/include/userobjects/BrineFluidProperties.h
  modules/fluid_properties/include/userobjects/CO2FluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/MethaneFluidProperties.h
  modules/fluid_properties/include/userobjects/MultiComponentFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/NaClFluidProperties.h
  modules/fluid_properties/include/userobjects/SimpleFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/TabulatedFluidProperties.h
  modules/fluid_properties/include/userobjects/Water97FluidProperties.h
  modules/fluid_properties/src/userobjects/BrineFluidProperties.C
  modules/fluid_properties/src/userobjects/CO2FluidProperties.C
  modules/fluid_properties/src/userobjects/IdealGasFluidPropertiesPT.C
  modules/fluid_properties/src/userobjects/MethaneFluidProperties.C
  modules/fluid_properties/src/userobjects/NaClFluidProperties.C
  modules/fluid_properties/src/userobjects/SimpleFluidProperties.C
  modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
  modules/fluid_properties/src/userobjects/Water97FluidProperties.C
  modules/porous_flow/src/materials/PorousFlowBrine.C
  modules/porous_flow/src/materials/PorousFlowSingleComponentFluid.C
  modules/porous_flow/src/userobjects/PorousFlowBrineCO2.C
  modules/porous_flow/src/userobjects/PorousFlowWaterNCG.C
Labels: PR: Failed but allowed

#11028 Move MathUtils
  framework/include/utils/MathUtils.h
  framework/src/utils/MathUtils.C
Labels: PR: Failed but allowed

#11030 Fix MooseDocs executable and links
  framework/doc/content/index.md
  modules/chemical_reactions/doc/moosedocs.py
  modules/combined/doc/config.yml
  modules/combined/doc/moosedocs.py
  modules/contact/doc/moosedocs.py
  modules/doc/moosedocs.py
  modules/fluid_properties/doc/moosedocs.py
  modules/functional_expansion_tools/doc/moosedocs.py
  modules/heat_conduction/doc/moosedocs.py
  modules/level_set/doc/moosedocs.py
  modules/misc/doc/moosedocs.py
  modules/navier_stokes/doc/moosedocs.py
  modules/phase_field/doc/moosedocs.py
  modules/porous_flow/doc/moosedocs.py
  modules/rdg/doc/moosedocs.py
  modules/richards/doc/moosedocs.py
  modules/solid_mechanics/doc/moosedocs.py
  modules/stochastic_tools/doc/moosedocs.py
  modules/tensor_mechanics/doc/moosedocs.py
  modules/water_steam_eos/doc/moosedocs.py
  modules/xfem/doc/moosedocs.py
  test/doc/moosedocs.py
Labels: PR: Failed but allowed

#11008 Adding Eshelby Tensor material in the DomainIntegralAction class.
  modules/solid_mechanics/src/postprocessors/InteractionIntegralSM.C
  modules/solid_mechanics/test/tests/domain_integral_thermal/interaction_integral_2d.i
  modules/solid_mechanics/test/tests/domain_integral_thermal/interaction_integral_2d_rot.i
  modules/tensor_mechanics/doc/content/documentation/systems/Materials/EshelbyTensor.md
  modules/tensor_mechanics/src/actions/DomainIntegralAction.C
  modules/tensor_mechanics/src/postprocessors/InteractionIntegral.C
  modules/tensor_mechanics/test/tests/domain_integral_thermal/interaction_integral_2d.i
  modules/tensor_mechanics/test/tests/domain_integral_thermal/interaction_integral_2d_rot.i
  modules/tensor_mechanics/test/tests/domain_integral_thermal/j_integral_2d.i
  modules/tensor_mechanics/test/tests/domain_integral_thermal/j_integral_2d_ctefunc.i
  modules/tensor_mechanics/test/tests/domain_integral_thermal/j_integral_2d_inst_ctefunc.i
  modules/tensor_mechanics/test/tests/domain_integral_thermal/j_integral_2d_mean_ctefunc.i
  modules/tensor_mechanics/test/tests/interaction_integral_benchmark/input.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_2d.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_2d_mouth_dir.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_2d_points.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_2d_small_strain.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_2d_topo_q_func.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_3d.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_3d_as_2d.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_3d_as_2d_topo_q_func.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_3d_mouth_dir.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_3d_mouth_dir_end_dir_vec.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_3d_points.i
  modules/tensor_mechanics/test/tests/j_integral/j_integral_3d_topo_q_func.i
  modules/tensor_mechanics/test/tests/j_integral_vtest/j_int_surfbreak_ellip_crack_sym_mm.i
  modules/tensor_mechanics/test/tests/j_integral_vtest/j_int_surfbreak_ellip_crack_sym_mm_cfp.i
  modules/tensor_mechanics/test/tests/j_integral_vtest/j_int_surfbreak_ellip_crack_sym_mm_cfp_cm.i
  modules/tensor_mechanics/test/tests/j_integral_vtest/j_int_surfbreak_ellip_crack_sym_mm_cm.i
  modules/tensor_mechanics/test/tests/t_stress/t_stress_crack_infinite_plate_2d.i
  modules/tensor_mechanics/test/tests/t_stress/t_stress_ellip_crack_3d.i
Labels: PR: Failed but allowed

#11022 Use paramError where applicable
  framework/include/actions/Action.h
  modules/phase_field/include/ics/PolycrystalRandomIC.h
  modules/phase_field/include/kernels/CahnHilliardBase.h
  modules/phase_field/src/action/BicrystalBoundingBoxICAction.C
  modules/phase_field/src/action/BicrystalCircleGrainICAction.C
  modules/phase_field/src/action/ConservedAction.C
  modules/phase_field/src/action/DisplacementGradientsAction.C
  modules/phase_field/src/action/MatVecRealGradAuxKernelAction.C
  modules/phase_field/src/action/MaterialVectorAuxKernelAction.C
  modules/phase_field/src/action/MaterialVectorGradAuxKernelAction.C
  modules/phase_field/src/action/MortarPeriodicAction.C
  modules/phase_field/src/action/PolycrystalRandomICAction.C
  modules/phase_field/src/auxkernels/CrossTermGradientFreeEnergy.C
  modules/phase_field/src/ics/BimodalInverseSuperellipsoidsIC.C
  modules/phase_field/src/ics/PolycrystalRandomIC.C
  modules/phase_field/src/ics/Tricrystal2CircleGrainsIC.C
  modules/phase_field/src/ics/TricrystalTripleJunctionIC.C
  modules/phase_field/src/kernels/ACGrGrMulti.C
  modules/phase_field/src/kernels/ACInterface.C
  modules/phase_field/src/kernels/ACMultiInterface.C
  modules/phase_field/src/kernels/ACSwitching.C
  modules/phase_field/src/kernels/CoupledSwitchingTimeDerivative.C
  modules/phase_field/src/kernels/GradientComponent.C
  modules/phase_field/src/kernels/KKSMultiACBulkBase.C
  modules/phase_field/src/kernels/KKSMultiACBulkC.C
  modules/phase_field/src/kernels/KKSMultiPhaseConcentration.C
  modules/phase_field/src/kernels/SwitchingFunctionPenalty.C
  modules/phase_field/src/materials/AsymmetricCrossTermBarrierFunctionMaterial.C
  modules/phase_field/src/materials/CrossTermBarrierFunctionBase.C
  modules/phase_field/src/materials/CrossTermBarrierFunctionMaterial.C
  modules/phase_field/src/materials/DeformedGrainMaterial.C
  modules/phase_field/src/materials/DerivativeMultiPhaseMaterial.C
  modules/phase_field/src/materials/GBAnisotropyBase.C
  modules/phase_field/src/materials/PFParamsPolyFreeEnergy.C
  modules/phase_field/src/mesh/EBSDMesh.C
Labels: PR: Failed but allowed

#11080 Support syntax alias in MooseDocs
  framework/doc/content/bib/macro_test_abbrev.bib
  framework/doc/content/bib/template_example.bib
  framework/doc/content/documentation/systems/Transfers/MultiAppVectorPostprocessorTransfer.md
  framework/doc/globals.yml
  modules/chemical_reactions/doc/content/bib/chemical_reactions.bib
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/documentation/systems/Modules/index.md
  modules/functional_expansion_tools/doc/content/bib/functional_expansion_tools.bib
  modules/level_set/doc/content/bib/level_set.bib
  modules/phase_field/doc/content/bib/phase_field.bib
  modules/porous_flow/doc/content/bib/porous_flow.bib
  modules/rdg/doc/content/bib/rdg.bib
  modules/stochastic_tools/doc/content/bib/stochastic_tools.bib
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  python/MooseDocs/base/lexers.py
  python/MooseDocs/base/readers.py
  python/MooseDocs/base/renderers.py
  python/MooseDocs/commands/build.py
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/panoptic.py
  python/MooseDocs/test/base/test_lexers.py
  python/MooseDocs/test/tree/test_build_page_tree.py
  python/MooseDocs/test/tree/test_syntax_tree.py
  python/MooseDocs/tree/app_syntax.py
  python/MooseDocs/tree/build_page_tree.py
  python/MooseDocs/tree/syntax.py
Labels: PR: Ready to Merge

#11017 Relative paths for submodules
  .gitmodules
Labels: PR: Failed but allowed

#11093 Improvements to SQA system
  framework/doc/acronyms.yml
  framework/doc/content/bib/sqa.bib
  framework/doc/content/css/moose.css
  framework/doc/content/documentation/sqa/index.md
  framework/doc/content/documentation/sqa/moose_rtm.md
  framework/doc/content/documentation/sqa/moose_sdd.md
  framework/doc/content/documentation/sqa/moose_srs.md
  framework/doc/content/getting_started/installation/centos_pre_req.md
  framework/doc/content/getting_started/installation/fedora_pre_req.md
  framework/doc/content/getting_started/installation/mint_pre_req.md
  framework/doc/content/getting_started/installation/opensuse_pre_req.md
  framework/doc/content/utilities/MooseDocs/extensions/acronym.md
  framework/doc/content/utilities/MooseDocs/specification.md
  framework/doc/templates/sqa/system_design_description.md.template
  framework/doc/templates/sqa/system_requirement_specification.md.template
  framework/doc/templates/sqa/system_requirements_traceability_matrix.md.template
  modules/chemical_reactions/doc/config.yml
  modules/combined/doc/config.yml
  modules/combined/doc/content/documentation/sqa/moose_rtm.md
  modules/combined/doc/content/documentation/sqa/moose_sdd.md
  modules/combined/doc/content/documentation/sqa/moose_srs.md
  modules/contact/doc/config.yml
  modules/fluid_properties/doc/config.yml
  modules/functional_expansion_tools/doc/config.yml
  modules/heat_conduction/doc/config.yml
  modules/level_set/doc/config.yml
  modules/misc/doc/config.yml
  modules/navier_stokes/doc/config.yml
  modules/phase_field/doc/config.yml
  modules/porous_flow/doc/config.yml
  modules/rdg/doc/config.yml
  modules/stochastic_tools/doc/config.yml
  modules/tensor_mechanics/doc/config.yml
  modules/water_steam_eos/doc/config.yml
  modules/xfem/doc/config.yml
  python/MooseDocs/__init__.py
  python/MooseDocs/commands/profiler.py
  python/MooseDocs/common/__init__.py
  python/MooseDocs/common/build_class_database.py
  python/MooseDocs/common/get_requirements.py
  python/MooseDocs/common/load_config.py
  python/MooseDocs/extensions/acronym.py
  python/MooseDocs/extensions/alert.py
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/autolink.py
  python/MooseDocs/extensions/command.py
  python/MooseDocs/extensions/floats.py
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/extensions/table.py
  python/MooseDocs/main.py
  python/mooseutils/__init__.py
  python/mooseutils/mooseutils.py
  test/doc/config.yml
  test/tests/adaptivity/initial_marker/tests
  test/tests/dgkernels/adaptivity/tests
  test/tests/interfacekernels/2d_interface/tests
  test/tests/interfacekernels/adaptivity/tests
  test/tests/markers/box_marker/tests
Labels: PR: Ready to Merge

#11037 Nonconstant thermal expansion for ideal gas EOS
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
  unit/src/IdealGasFluidPropertiesTest.C
Labels: PR: Failed but allowed

#11124 MooseDocs SDD Cross-Reference
  framework/doc/content/css/moose.css
  modules/combined/doc/config.yml
  modules/combined/doc/content/documentation/sqa/index.md
  modules/combined/doc/content/documentation/sqa/moose_rtm.md
  modules/combined/doc/content/documentation/sqa/moose_sdd.md
  modules/combined/doc/content/documentation/sqa/moose_srs.md
  python/MooseDocs/common/get_requirements.py
  python/MooseDocs/common/load_config.py
  python/MooseDocs/extensions/sqa.py
Labels: PR: Ready to Merge

#11107 PorousFlow equilibrium constants are now AuxVariables
  modules/porous_flow/doc/content/documentation/systems/Materials/PorousFlowAqueousPreDisChemistry.md
  modules/porous_flow/doc/content/documentation/systems/Materials/PorousFlowMassFractionAqueousEquilibriumChemistry.md
  modules/porous_flow/examples/tutorial/07.i
  modules/porous_flow/examples/tutorial/gold/07_out.e
  modules/porous_flow/include/materials/PorousFlowAqueousPreDisChemistry.h
  modules/porous_flow/include/materials/PorousFlowMassFractionAqueousEquilibriumChemistry.h
  modules/porous_flow/src/materials/PorousFlowAqueousPreDisChemistry.C
  modules/porous_flow/src/materials/PorousFlowMassFractionAqueousEquilibriumChemistry.C
  modules/porous_flow/test/tests/chemistry/2species_equilibrium.i
  modules/porous_flow/test/tests/chemistry/2species_equilibrium_2phase.i
  modules/porous_flow/test/tests/chemistry/2species_predis.i
  modules/porous_flow/test/tests/chemistry/dissolution.i
  modules/porous_flow/test/tests/chemistry/dissolution_limited.i
  modules/porous_flow/test/tests/chemistry/dissolution_limited_2phase.i
  modules/porous_flow/test/tests/chemistry/except1.i
  modules/porous_flow/test/tests/chemistry/except10.i
  modules/porous_flow/test/tests/chemistry/except11.i
  modules/porous_flow/test/tests/chemistry/except12.i
  modules/porous_flow/test/tests/chemistry/except13.i
  modules/porous_flow/test/tests/chemistry/except14.i
  modules/porous_flow/test/tests/chemistry/except15.i
  modules/porous_flow/test/tests/chemistry/except16.i
  modules/porous_flow/test/tests/chemistry/except17.i
  modules/porous_flow/test/tests/chemistry/except18.i
  modules/porous_flow/test/tests/chemistry/except19.i
  modules/porous_flow/test/tests/chemistry/except2.i
  modules/porous_flow/test/tests/chemistry/except20.i
  modules/porous_flow/test/tests/chemistry/except3.i
  modules/porous_flow/test/tests/chemistry/except5.i
  modules/porous_flow/test/tests/chemistry/except6.i
  modules/porous_flow/test/tests/chemistry/except7.i
  modules/porous_flow/test/tests/chemistry/except8.i
  modules/porous_flow/test/tests/chemistry/except9.i
  modules/porous_flow/test/tests/chemistry/gold/2species_equilibrium_2phase_out.e
  modules/porous_flow/test/tests/chemistry/gold/2species_equilibrium_out.e
  modules/porous_flow/test/tests/chemistry/gold/2species_predis_out.e
  modules/porous_flow/test/tests/chemistry/precipitation.i
  modules/porous_flow/test/tests/chemistry/precipitation_2phase.i
  modules/porous_flow/test/tests/chemistry/precipitation_porosity_change.i
  modules/porous_flow/test/tests/jacobian/chem01.i
  modules/porous_flow/test/tests/jacobian/chem02.i
  modules/porous_flow/test/tests/jacobian/chem03.i
  modules/porous_flow/test/tests/jacobian/chem04.i
  modules/porous_flow/test/tests/jacobian/chem05.i
  modules/porous_flow/test/tests/jacobian/chem06.i
  modules/porous_flow/test/tests/jacobian/chem07.i
  modules/porous_flow/test/tests/jacobian/chem08.i
  modules/porous_flow/test/tests/jacobian/chem09.i
  modules/porous_flow/test/tests/jacobian/chem10.i
  modules/porous_flow/test/tests/jacobian/chem11.i
  modules/porous_flow/test/tests/jacobian/chem12.i
  modules/porous_flow/test/tests/jacobian/chem13.i
  modules/porous_flow/test/tests/jacobian/chem14.i
  modules/porous_flow/test/tests/jacobian/chem15.i
Labels: PR: Failed but allowed

#11125 dolomite example added to PorousFlow tutorial
  framework/doc/content/media/porous_flow/tut13_conc.png
  framework/doc/content/media/porous_flow/tut13_dolo.png
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_00.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_01.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_02.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_03.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_04.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_05.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_06.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_07.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_08.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_09.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_10.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_11.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_12.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_13.md
  modules/porous_flow/examples/tutorial/13.i
  modules/porous_flow/examples/tutorial/gold/13_out.e
  modules/porous_flow/examples/tutorial/tests
Labels: PR: Failed but allowed

#11127 Revert "dolomite example added to PorousFlow tutorial"
  framework/doc/content/media/porous_flow/tut13_conc.png
  framework/doc/content/media/porous_flow/tut13_dolo.png
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_00.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_01.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_02.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_03.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_04.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_05.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_06.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_07.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_08.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_09.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_10.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_11.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_12.md
  modules/porous_flow/doc/content/documentation/modules/porous_flow/tutorial_13.md
  modules/porous_flow/examples/tutorial/13.i
  modules/porous_flow/examples/tutorial/gold/13_out.e
  modules/porous_flow/examples/tutorial/tests
Labels: PR: Failed but allowed

#11126 Add better error message when an error is enouncter in get_repo_revision
  framework/scripts/get_repo_revision.py
Labels: PR: Failed but allowed

#11134 Makefile optimization
  framework/app.mk
  framework/build.mk
  framework/moose.mk
Labels: PR: Ready to Merge

#11131 Using alpha_vapor instead of alpha_liquid
  modules/fluid_properties/include/userobjects/HEMFluidProperties.h
Labels: PR: Failed but allowed

#11145 fix duplicate action registrations
  framework/src/base/Moose.C
Labels: PR: Failed but allowed

#11123 Refactor the writing of result files
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/schedulers/Scheduler.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/test_WriteResults.py
  python/TestHarness/tests/tests
  python/TestHarness/util.py
Labels: PR: Failed but allowed

#11146 Converting regression tests into unit tests
  modules/fluid_properties/test/include/kernels/EntropyFromEnthalpyPressureDerivativesTestKernel.h
  modules/fluid_properties/test/include/kernels/FluidPropertyDerivativesTestKernel.h
  modules/fluid_properties/test/include/kernels/InternalEnergyFromVolumeEnthalpyDerivativesTestKernel.h
  modules/fluid_properties/test/include/kernels/SoundSpeedFromVolumeInternalEnergyDerivativesTestKernel.h
  modules/fluid_properties/test/src/kernels/EntropyFromEnthalpyPressureDerivativesTestKernel.C
  modules/fluid_properties/test/src/kernels/FluidPropertyDerivativesTestKernel.C
  modules/fluid_properties/test/src/kernels/InternalEnergyFromVolumeEnthalpyDerivativesTestKernel.C
  modules/fluid_properties/test/src/kernels/SoundSpeedFromVolumeInternalEnergyDerivativesTestKernel.C
  modules/fluid_properties/test/tests/ideal_gas/c_from_v_e_derivatives.i
  modules/fluid_properties/test/tests/ideal_gas/e_from_v_h_derivatives.i
  modules/fluid_properties/test/tests/ideal_gas/s_from_h_p_derivatives.i
  modules/fluid_properties/test/tests/ideal_gas/tests
  modules/fluid_properties/test/tests/stiffened_gas/c_from_v_e_derivatives.i
  modules/fluid_properties/test/tests/stiffened_gas/e_from_v_h_derivatives.i
  modules/fluid_properties/test/tests/stiffened_gas/s_from_h_p_derivatives.i
  modules/fluid_properties/test/tests/stiffened_gas/tests
  unit/src/IdealGasFluidPropertiesTest.C
  unit/src/StiffenedGasFluidPropertiesTest.C
Labels: PR: Failed but allowed

#11147 Don't try to touch non-existent files (submodule case)
  framework/scripts/get_repo_revision.py
Labels: PR: Failed but allowed

#11158 Updates to MooseDocs for application support
  framework/doc/content/css/moose_presentation.css
  modules/tensor_mechanics/doc/content/documentation/systems/BCs/CavityPressure/CavityPressureAction.md
  modules/tensor_mechanics/doc/content/documentation/systems/BCs/CavityPressure/cavity_pressure.md
  python/MooseDocs/extensions/include.py
Labels: PR: Ready to Merge

#11157 Fix test_WriteResults collision with Diff test
  python/TestHarness/tests/test_WriteResults.py
  python/TestHarness/tests/tests
Labels: PR: Failed but allowed
