Repository idaholab/moose, pull requests merged in 2018-08, with the labels that each got.

#11794 Concentric circle
  framework/doc/content/source/mesh/ConcentricCircleMesh.md
  framework/include/mesh/ConcentricCircleMesh.h
  framework/src/mesh/ConcentricCircleMesh.C
  modules/tensor_mechanics/examples/coal_mining/coal_mining.tex
  test/tests/mesh/concentric_circle_mesh/concentric_circle_mesh.i
  test/tests/mesh/concentric_circle_mesh/gold/concentric_circle_mesh_out.e
  test/tests/mesh/concentric_circle_mesh/tests
Labels: PR: Ready for Review/Merge

#11928 Allow multiple defaulted coupled values
  framework/doc/content/framework_development/interfaces/Coupleable.md
  framework/include/interfaces/Coupleable.h
  framework/include/utils/InputParameters.h
  framework/src/interfaces/Coupleable.C
  framework/src/parser/Parser.C
  framework/src/utils/InputParameters.C
  test/include/kernels/OptionallyVectorCoupledForce.h
  test/src/kernels/OptionallyVectorCoupledForce.C
  test/tests/variables/optionally_coupled/gold/two_coupled_default_1.e
  test/tests/variables/optionally_coupled/gold/two_coupled_default_2.e
  test/tests/variables/optionally_coupled/optionally_coupled_twovar.i
  test/tests/variables/optionally_coupled/tests
Labels: PR: Failed but allowed

#11966 Add missing performance graph and final execution in eigen executioners
  framework/include/executioners/EigenExecutionerBase.h
  framework/src/executioners/EigenExecutionerBase.C
Labels: PR: Failed but allowed

#11828 EqualValueEmbededConstraint -- new type of constraint
  framework/doc/content/source/constraints/EqualValueEmbeddedConstraint.md
  framework/include/constraints/ConstraintWarehouse.h
  framework/include/constraints/EqualValueEmbeddedConstraint.h
  framework/include/constraints/NodeElemConstraint.h
  framework/include/variables/MooseVariableFE.h
  framework/src/constraints/ConstraintWarehouse.C
  framework/src/constraints/EqualValueEmbeddedConstraint.C
  framework/src/constraints/NodeElemConstraint.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/RankTwoTensor.C
  test/tests/constraints/equal_value_embedded_constraint/embedded_constraint.i
  test/tests/constraints/equal_value_embedded_constraint/gold/1D_2D.e
  test/tests/constraints/equal_value_embedded_constraint/gold/1D_2D_kinematic_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/1D_2D_penalty_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/1D_3D.e
  test/tests/constraints/equal_value_embedded_constraint/gold/1D_3D_kinematic_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/1D_3D_penalty_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/2D_2D.e
  test/tests/constraints/equal_value_embedded_constraint/gold/2D_2D_kinematic_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/2D_2D_penalty_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/2D_3D.e
  test/tests/constraints/equal_value_embedded_constraint/gold/2D_3D_kinematic_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/2D_3D_penalty_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/3D_3D.e
  test/tests/constraints/equal_value_embedded_constraint/gold/3D_3D_kinematic_out.e
  test/tests/constraints/equal_value_embedded_constraint/gold/3D_3D_penalty_out.e
  test/tests/constraints/equal_value_embedded_constraint/tests
Labels: PR: Ready for Review/Merge

#11964 Fix some deprecated calls/parameters
  framework/src/kernels/NodalEqualValueConstraint.C
  framework/src/transfers/MultiAppVectorPostprocessorTransfer.C
  framework/src/vectorpostprocessors/LineValueSampler.C
  test/tests/misc/check_error/check_syntax_error.i
  test/tests/misc/check_error/check_syntax_ok.i
  test/tests/misc/check_error/tests
  test/tests/mortar/1d/1d.i
Labels: PR: Failed but allowed

#11961 Run threaded general user objects when not using pthreads
  modules/fluid_properties/test/tests/auxkernels/tests
  modules/fluid_properties/test/tests/brine/tests
  modules/fluid_properties/test/tests/co2/tests
  modules/fluid_properties/test/tests/ideal_gas/tests
  modules/fluid_properties/test/tests/methane/tests
  modules/fluid_properties/test/tests/stiffened_gas/tests
  modules/fluid_properties/test/tests/tabulated/tests
  modules/fluid_properties/test/tests/two_phase_fluid_properties_independent/tests
  modules/fluid_properties/test/tests/water/tests
  modules/navier_stokes/test/tests/bump/tests
  modules/porous_flow/examples/coal_mining/tests
  modules/porous_flow/examples/flow_through_fractured_media/tests
  modules/porous_flow/examples/tutorial/tests
  modules/porous_flow/test/tests/actions/tests
  modules/porous_flow/test/tests/aux_kernels/tests
  modules/porous_flow/test/tests/basic_advection/tests
  modules/porous_flow/test/tests/broadbridge_white/tests
  modules/porous_flow/test/tests/buckley_leverett/tests
  modules/porous_flow/test/tests/capillary_pressure/tests
  modules/porous_flow/test/tests/chemistry/tests
  modules/porous_flow/test/tests/density/tests
  modules/porous_flow/test/tests/desorption/tests
  modules/porous_flow/test/tests/dirackernels/tests
  modules/porous_flow/test/tests/dispersion/tests
  modules/porous_flow/test/tests/energy_conservation/tests
  modules/porous_flow/test/tests/fluids/tests
  modules/porous_flow/test/tests/fluidstate/tests
  modules/porous_flow/test/tests/functions/tests
  modules/porous_flow/test/tests/gravity/tests
  modules/porous_flow/test/tests/heat_advection/tests
  modules/porous_flow/test/tests/heat_conduction/tests
  modules/porous_flow/test/tests/heterogeneous_materials/tests
  modules/porous_flow/test/tests/jacobian/tests
  modules/porous_flow/test/tests/mass_conservation/tests
  modules/porous_flow/test/tests/newton_cooling/tests
  modules/porous_flow/test/tests/numerical_diffusion/tests
  modules/porous_flow/test/tests/plastic_heating/tests
  modules/porous_flow/test/tests/poro_elasticity/tests
  modules/porous_flow/test/tests/poroperm/tests
  modules/porous_flow/test/tests/pressure_pulse/tests
  modules/porous_flow/test/tests/radioactive_decay/tests
  modules/porous_flow/test/tests/relperm/tests
  modules/porous_flow/test/tests/rogers_stallybrass_clements/tests
  modules/porous_flow/test/tests/sinks/tests
  modules/porous_flow/test/tests/thermal_conductivity/tests
  modules/porous_flow/test/tests/thm_rehbinder/tests
  python/TestHarness/TestHarness.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/test_ExtraInfo.py
  python/TestHarness/util.py
  test/tests/test_harness/extra_info
  test/tests/userobjects/threaded_general_user_object/tests
Labels: PR: Failed but allowed

#11969 PorousFlow DiracKernel doco improved
  framework/doc/content/media/porous_flow/bh02_error.png
  framework/doc/content/media/porous_flow/bh02_flow.png
  framework/doc/content/media/porous_flow/bh03_error.png
  framework/doc/content/media/porous_flow/bh03_flow.png
  framework/doc/content/media/porous_flow/bh04_error.png
  framework/doc/content/media/porous_flow/bh04_flow.png
  framework/doc/content/media/porous_flow/bh05_error.png
  framework/doc/content/media/porous_flow/bh05_flow.png
  framework/doc/content/media/porous_flow/bh07.png
  framework/doc/content/media/porous_flow/bh07_mesh.png
  framework/doc/content/media/porous_flow/injection_production_P.png
  framework/doc/content/media/porous_flow/injection_production_T.png
  modules/porous_flow/doc/content/modules/porous_flow/index.md
  modules/porous_flow/doc/content/modules/porous_flow/sinks.md
  modules/porous_flow/doc/content/source/dirackernels/PorousFlowPeacemanBorehole.md
  modules/porous_flow/doc/content/source/dirackernels/PorousFlowPolyLineSink.md
  modules/porous_flow/doc/content/source/dirackernels/PorousFlowSquarePulsePointSource.md
  modules/porous_flow/doc/content/source/postprocessors/PorousFlowPlotQuantity.md
  modules/porous_flow/doc/content/source/userobjects/PorousFlowSumQuantity.md
  modules/porous_flow/test/tests/dirackernels/bh02.i
  modules/porous_flow/test/tests/dirackernels/bh03.i
  modules/porous_flow/test/tests/dirackernels/bh04.i
  modules/porous_flow/test/tests/dirackernels/bh05.i
  modules/porous_flow/test/tests/dirackernels/bh07.i
  modules/porous_flow/test/tests/dirackernels/dirackernels.py
  modules/porous_flow/test/tests/dirackernels/gold/injection_production_out.e
  modules/porous_flow/test/tests/dirackernels/injection.bh
  modules/porous_flow/test/tests/dirackernels/injection_production.i
  modules/porous_flow/test/tests/dirackernels/pls02.i
  modules/porous_flow/test/tests/dirackernels/production.bh
  modules/porous_flow/test/tests/dirackernels/tests
Labels: PR: Failed but allowed

#11976 Guard existence of user objects only on thread 0
  modules/fluid_properties/src/userobjects/TwoPhaseFluidProperties.C
Labels: PR: Failed but allowed

#11895 GrainTracker Optimizations / New Timers
  modules/phase_field/include/postprocessors/FeatureFloodCount.h
  modules/phase_field/include/postprocessors/GrainTracker.h
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
  modules/phase_field/src/postprocessors/GrainTracker.C
  modules/phase_field/test/tests/grain_tracker_test/grain_tracker_remapping_test.i
  modules/phase_field/test/tests/grain_tracker_test/grain_tracker_volume.i
  modules/phase_field/test/tests/grain_tracker_test/tests
Labels: PR: Failed but allowed

#11830 New kernels to increase model flexibility
  modules/phase_field/doc/content/source/kernels/ACBarrierFunction.md
  modules/phase_field/doc/content/source/kernels/ACKappaFunction.md
  modules/phase_field/include/kernels/ACBarrierFunction.h
  modules/phase_field/include/kernels/ACGrGrMulti.h
  modules/phase_field/include/kernels/ACKappaFunction.h
  modules/phase_field/src/kernels/ACBarrierFunction.C
  modules/phase_field/src/kernels/ACGrGrMulti.C
  modules/phase_field/src/kernels/ACKappaFunction.C
  modules/phase_field/test/tests/phase_field_kernels/gold/nonuniform_barrier_coefficient_out.e
  modules/phase_field/test/tests/phase_field_kernels/nonuniform_barrier_coefficient.i
  modules/phase_field/test/tests/phase_field_kernels/tests
Labels: PR: Ready for Review/Merge

#11975 Report proper distance to users
  modules/phase_field/src/postprocessors/GrainTracker.C
Labels: PR: Failed but allowed

#11972 Add back screen print-outs showing actions
  framework/src/actions/ActionWarehouse.C
  test/tests/actions/debug_block/debug_print_actions_test.i
  test/tests/actions/debug_block/tests
Labels: PR: Failed but allowed

#11979 give threaded general user objects their own subclass
  framework/include/userobject/ThreadedGeneralUserObject.h
  framework/src/problems/FEProblemBase.C
  framework/src/userobject/GeneralUserObject.C
  framework/src/userobject/ThreadedGeneralUserObject.C
  modules/fluid_properties/include/userobjects/FluidProperties.h
  modules/fluid_properties/src/userobjects/FluidProperties.C
  test/include/userobjects/PrimeProductUserObject.h
  test/src/userobjects/PrimeProductUserObject.C
  test/tests/userobjects/threaded_general_user_object/test.i
Labels: PR: Auto Merge, PR: Failed but allowed, PR: Ready for Review/Merge

#11982 Fix preprocessor macro check for threaded general user objects
  framework/include/userobject/ThreadedGeneralUserObject.h
  framework/src/userobject/GeneralUserObject.C
  framework/src/userobject/ThreadedGeneralUserObject.C
Labels: PR: Auto Merge, PR: Failed but allowed

#11938 Implemented ScalarDamageBase
  modules/tensor_mechanics/doc/content/source/materials/CombinedScalarDamage.md
  modules/tensor_mechanics/include/materials/CombinedScalarDamage.h
  modules/tensor_mechanics/include/materials/ScalarDamageBase.h
  modules/tensor_mechanics/include/materials/ScalarMaterialDamage.h
  modules/tensor_mechanics/src/materials/CombinedScalarDamage.C
  modules/tensor_mechanics/src/materials/ScalarDamageBase.C
  modules/tensor_mechanics/src/materials/ScalarMaterialDamage.C
  modules/tensor_mechanics/test/tests/scalar_material_damage/combined_scalar_damage.i
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/combined_scalar_damage_mult_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/combined_scalar_damage_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/tests
Labels: PR: Failed but allowed

#11980 Aug 2018 MOOSEletter
  modules/combined/doc/content/newsletter/2018_08_09.md
  modules/combined/doc/content/newsletter/2018_08_17.md
  modules/combined/doc/content/newsletter/index.md
Labels: PR: Auto Merge

#12009 O(n) algrogithm for Polycrystal IC merging
  modules/phase_field/include/postprocessors/FeatureFloodCount.h
  modules/phase_field/include/userobjects/PolycrystalUserObjectBase.h
  modules/phase_field/src/userobjects/PolycrystalUserObjectBase.C
Labels: PR: Ready for Review/Merge

#11984 Proper API degradation for non-specialized cases
  framework/doc/content/source/mesh/MooseMesh.md
  framework/src/mesh/MooseMesh.C
  test/include/auxkernels/PeriodicDistanceAux.h
  test/src/auxkernels/PeriodicDistanceAux.C
  test/tests/bcs/periodic/gold/trapezoid_non_periodic_out.e
  test/tests/bcs/periodic/tests
  test/tests/bcs/periodic/trapezoid_non_periodic.i
Labels: PR: Ready for Review/Merge

#12051 Add testing for Aux variables in nemesis format
  framework/doc/content/syntax/Mesh/index.md
  test/tests/mesh/nemesis/gold/out.e.4.0
  test/tests/mesh/nemesis/gold/out.e.4.1
  test/tests/mesh/nemesis/gold/out.e.4.2
  test/tests/mesh/nemesis/gold/out.e.4.3
  test/tests/mesh/nemesis/nemesis_test.i
  test/tests/mesh/nemesis/tests
Labels: PR: Ready for Review/Merge
