Repository idaholab/moose, pull requests merged in 2018-09, with the labels that each got.

#12054 Add capability to group variables for ReferenceResidualProblem
  modules/combined/test/tests/reference_residual/2squares.e
  modules/combined/test/tests/reference_residual/gold/group_variables_out.e
  modules/combined/test/tests/reference_residual/group_variables.i
  modules/combined/test/tests/reference_residual/tests
  modules/contact/doc/content/source/ReferenceResidualProblem.md
  modules/contact/include/ReferenceResidualProblem.h
  modules/contact/src/ReferenceResidualProblem.C
Labels: PR: Ready for Review/Merge

#12076 Allow rz_coord_axis = X for GapHeatTransfer
  modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_zr_test.i
  modules/combined/test/tests/gap_heat_transfer_htonly/gold/gap_heat_transfer_htonly_zr_test_out.e
  modules/combined/test/tests/gap_heat_transfer_htonly/simple_2D.e
  modules/combined/test/tests/gap_heat_transfer_htonly/tests
  modules/heat_conduction/include/materials/GapConductance.h
  modules/heat_conduction/src/bcs/GapHeatTransfer.C
  modules/heat_conduction/src/materials/GapConductance.C
Labels: PR: Ready for Review/Merge

#12056 Merging the (e,v) and (p,T) branch in fluid_properties
  modules/fluid_properties/doc/content/modules/fluid_properties/index.md
  modules/fluid_properties/include/userobjects/CO2FluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/MethaneFluidProperties.h
  modules/fluid_properties/include/userobjects/NaClFluidProperties.h
  modules/fluid_properties/include/userobjects/SimpleFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/TabulatedFluidProperties.h
  modules/fluid_properties/include/userobjects/Water97FluidProperties.h
  modules/fluid_properties/src/materials/FluidPropertiesMaterialPT.C
  modules/fluid_properties/src/userobjects/BrineFluidProperties.C
  modules/fluid_properties/src/userobjects/CO2FluidProperties.C
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  modules/fluid_properties/src/userobjects/IdealGasFluidPropertiesPT.C
  modules/fluid_properties/src/userobjects/MethaneFluidProperties.C
  modules/fluid_properties/src/userobjects/NaClFluidProperties.C
  modules/fluid_properties/src/userobjects/SimpleFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidPropertiesPT.C
  modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
  modules/fluid_properties/src/userobjects/Water97FluidProperties.C
  modules/fluid_properties/test/include/utils/SinglePhaseFluidPropertiesPTTestUtils.h
  modules/porous_flow/src/materials/PorousFlowSingleComponentFluid.C
  modules/porous_flow/src/userobjects/PorousFlowBrineCO2.C
  modules/porous_flow/src/userobjects/PorousFlowWaterNCG.C
  unit/src/CO2FluidPropertiesTest.C
  unit/src/IdealGasFluidPropertiesPTTest.C
  unit/src/MethaneFluidPropertiesTest.C
  unit/src/NaClFluidPropertiesTest.C
  unit/src/PorousFlowBrineCO2Test.C
  unit/src/PorousFlowWaterNCGTest.C
  unit/src/SimpleFluidPropertiesTest.C
  unit/src/TabulatedFluidPropertiesTest.C
  unit/src/Water97FluidPropertiesTest.C
Labels: PR: Failed but allowed

#12073 Get deprecation tests passing with --error-deprecated
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_file.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_gravity.i
  python/TestHarness/testers/RunApp.py
  test/tests/misc/check_error/tests
  test/tests/misc/deprecation/tests
Labels: PR: Failed but allowed

#12086 Add SQA requirements
  framework/doc/content/source/functions/VectorPostprocessorFunction.md
  framework/doc/content/source/kernels/MassEigenKernel.md
  framework/src/auxkernels/PenetrationAux.C
  framework/src/functions/PiecewiseMultilinear.C
  scripts/sqa_check.py
  test/tests/executioners/adapt_and_modify/tests
  test/tests/executioners/arbitrary_execute_flag/tests
  test/tests/executioners/eigen_executioners/tests
  test/tests/executioners/executioner/tests
  test/tests/executioners/nullspace/tests
  test/tests/executioners/pp_binding/tests
  test/tests/executioners/time_period/tests
  test/tests/executioners/transient_sync_time/tests
  test/tests/fixedbugs/i8575/tests
  test/tests/functions/constant_function/tests
  test/tests/functions/default_function/tests
  test/tests/functions/function_file_format/tests
  test/tests/functions/function_ic/tests
  test/tests/functions/function_setup/tests
  test/tests/functions/generic_function_material/tests
  test/tests/functions/image_function/tests
  test/tests/functions/linear_combination_function/tests
  test/tests/functions/parsed/tests
  test/tests/functions/piecewise_constant/tests
  test/tests/functions/piecewise_multilinear/tests
  test/tests/functions/pps_function/tests
  test/tests/functions/solution_function/tests
  test/tests/functions/vector_postprocessor_function/tests
  test/tests/geomsearch/1d_line_sampler/tests
  test/tests/geomsearch/1d_penetration_locator/tests
  test/tests/geomsearch/2d_interior_boundary_penetration_locator/tests
  test/tests/geomsearch/2d_moving_penetration/tests
  test/tests/geomsearch/2d_penetration_locator/tests
  test/tests/geomsearch/3d_moving_penetration/tests
  test/tests/geomsearch/3d_penetration_locator/tests
  test/tests/geomsearch/fake_block_to_boundary/tests
  test/tests/geomsearch/nearest_node_locator/tests
  test/tests/geomsearch/patch_update_strategy/tests
  test/tests/geomsearch/penetration_locator/tests
  test/tests/geomsearch/quadrature_nearest_node_locator/tests
  test/tests/geomsearch/quadrature_penetration_locator/tests
  test/tests/outputs/displacement/displaced_eq_transient_test.i
  test/tests/outputs/displacement/displacement_test.i
  test/tests/outputs/displacement/displacement_transient_test.i
  test/tests/outputs/displacement/gold/displaced_eq_transient_test_out_displaced.e-s011
  test/tests/outputs/displacement/gold/displacement_transient_test_out_displaced.e-s011
  test/tests/outputs/displacement/gold/out_displaced.e-s002
  test/tests/outputs/displacement/square.e
  test/tests/outputs/displacement/tests
  test/tests/vectorpostprocessors/1d_line_sampler/1d_line_sampler.i
  test/tests/vectorpostprocessors/1d_line_sampler/gold/1d_line_sampler_out_my_vpp_0001.csv
  test/tests/vectorpostprocessors/1d_line_sampler/tests
Labels: PR: Ready for Review/Merge

#12077 Sept. 2018 MOOSEletter
  modules/combined/doc/content/newsletter/2018_09_07.md
  modules/combined/doc/content/newsletter/index.md
Labels: PR: Auto Merge

#11750 Add preliminary capability of modeling moving interface problems using XFEM
  modules/xfem/doc/content/source/auxkernels/LineSegmentLevelSetAux.md
  modules/xfem/doc/content/source/constraints/XFEMEqualValueAtInterface.md
  modules/xfem/doc/content/source/materials/LevelSetBiMaterialRankFour.md
  modules/xfem/doc/content/source/materials/LevelSetBiMaterialRankTwo.md
  modules/xfem/doc/content/source/materials/LevelSetBiMaterialReal.md
  modules/xfem/doc/content/source/materials/LevelSetBiMaterialStress.md
  modules/xfem/doc/content/source/userobjects/MovingLineSegmentCutSetUserObject.md
  modules/xfem/doc/content/source/userobjects/PointValueAtXFEMInterface.md
  modules/xfem/doc/content/source/userobjects/XFEMPhaseTransitionMovingInterfaceVelocity.md
  modules/xfem/include/auxkernels/LineSegmentLevelSetAux.h
  modules/xfem/include/constraints/XFEMEqualValueAtInterface.h
  modules/xfem/include/materials/LevelSetBiMaterialBase.h
  modules/xfem/include/materials/LevelSetBiMaterialRankFour.h
  modules/xfem/include/materials/LevelSetBiMaterialRankTwo.h
  modules/xfem/include/materials/LevelSetBiMaterialReal.h
  modules/xfem/include/materials/LevelSetBiMaterialStress.h
  modules/xfem/include/userobjects/GeometricCut2DUserObject.h
  modules/xfem/include/userobjects/LineSegmentCutSetUserObject.h
  modules/xfem/include/userobjects/MovingLineSegmentCutSetUserObject.h
  modules/xfem/include/userobjects/PointValueAtXFEMInterface.h
  modules/xfem/include/userobjects/XFEMMovingInterfaceVelocityBase.h
  modules/xfem/include/userobjects/XFEMPhaseTransitionMovingInterfaceVelocity.h
  modules/xfem/src/auxkernels/LineSegmentLevelSetAux.C
  modules/xfem/src/constraints/XFEMEqualValueAtInterface.C
  modules/xfem/src/materials/LevelSetBiMaterialBase.C
  modules/xfem/src/materials/LevelSetBiMaterialRankFour.C
  modules/xfem/src/materials/LevelSetBiMaterialRankTwo.C
  modules/xfem/src/materials/LevelSetBiMaterialReal.C
  modules/xfem/src/materials/LevelSetBiMaterialStress.C
  modules/xfem/src/userobjects/MovingLineSegmentCutSetUserObject.C
  modules/xfem/src/userobjects/PointValueAtXFEMInterface.C
  modules/xfem/src/userobjects/XFEMMovingInterfaceVelocityBase.C
  modules/xfem/src/userobjects/XFEMPhaseTransitionMovingInterfaceVelocity.C
  modules/xfem/test/tests/bimaterials/glued_bimaterials_2d.i
  modules/xfem/test/tests/bimaterials/inclusion_bimaterials_2d.i
  modules/xfem/test/tests/moving_interface/gold/moving_diffusion_out.e
  modules/xfem/test/tests/moving_interface/gold/moving_diffusion_out.e-s002
  modules/xfem/test/tests/moving_interface/gold/moving_level_set_out.e
  modules/xfem/test/tests/moving_interface/gold/moving_level_set_out.e-s002
  modules/xfem/test/tests/moving_interface/gold/moving_level_set_out.e-s003
  modules/xfem/test/tests/moving_interface/gold/phase_transition_out.e
  modules/xfem/test/tests/moving_interface/gold/phase_transition_out.e-s002
  modules/xfem/test/tests/moving_interface/gold/phase_transition_out.e-s003
  modules/xfem/test/tests/moving_interface/gold/phase_transition_out.e-s004
  modules/xfem/test/tests/moving_interface/moving_bimaterial.i
  modules/xfem/test/tests/moving_interface/moving_diffusion.i
  modules/xfem/test/tests/moving_interface/moving_level_set.i
  modules/xfem/test/tests/moving_interface/phase_transition.i
  modules/xfem/test/tests/moving_interface/tests
  modules/xfem/test/tests/single_var_constraint_2d/equal_value.i
  modules/xfem/test/tests/single_var_constraint_2d/gold/equal_value_out.e
  modules/xfem/test/tests/single_var_constraint_2d/tests
Labels: PR: Ready for Review/Merge

#12135 Add ElementQualityAux
  framework/doc/content/media/framework/auxkernels/element_quality.png
  framework/doc/content/source/auxkernels/ElementQualityAux.md
  framework/include/auxkernels/ElementQualityAux.h
  framework/src/auxkernels/ElementQualityAux.C
  test/tests/auxkernels/element_quality_aux/element_quality_aux.i
  test/tests/auxkernels/element_quality_aux/gold/element_quality_aux_out.e
  test/tests/auxkernels/element_quality_aux/mesh.e
  test/tests/auxkernels/element_quality_aux/tests
Labels: PR: Ready for Review/Merge

#12141 Moose docs fixes
  framework/doc/content/css/moose.css
  framework/doc/content/source/mesh/GeneratedMesh.md
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/sqa.py
Labels: PR: Auto Merge

#12031 Add SharedPool
  framework/include/utils/SharedPool.h
  unit/src/SharedPoolTest.C
Labels: PR: Ready for Review/Merge

#12137 Suppressions
  python/TestHarness/TestHarness.py
  python/TestHarness/suppressions/errors.supp
  python/TestHarness/testers/RunApp.py
  python/TestHarness/testers/Tester.py
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12130 Additional Nucleation System capabilities and expanded documentation
  framework/doc/content/source/bcs/PenaltyDirichletBC.md
  framework/doc/content/source/bcs/SinDirichletBC.md
  framework/doc/content/source/bcs/SinNeumannBC.md
  framework/doc/content/source/materials/DerivativeParsedMaterial.md
  framework/doc/content/syntax/Kernels/index.md
  modules/phase_field/doc/content/modules/phase_field/Nucleation/DiscreteNucleation.md
  modules/phase_field/doc/content/source/auxkernels/DiscreteNucleationAux.md
  modules/phase_field/doc/content/source/kernels/CoupledSusceptibilityTimeDerivative.md
  modules/phase_field/doc/content/source/kernels/DiscreteNucleationForce.md
  modules/phase_field/doc/content/source/kernels/HHPFCRFF.md
  modules/phase_field/doc/content/source/kernels/KKSMultiACBulkF.md
  modules/phase_field/doc/content/source/kernels/KKSMultiPhaseConcentration.md
  modules/phase_field/doc/content/source/kernels/KKSPhaseChemicalPotential.md
  modules/phase_field/doc/content/source/kernels/SusceptibilityTimeDerivative.md
  modules/phase_field/doc/content/source/materials/BarrierFunctionMaterial.md
  modules/phase_field/doc/content/source/materials/CrossTermBarrierFunctionMaterial.md
  modules/phase_field/doc/content/source/materials/DerivativeTwoPhaseMaterial.md
  modules/phase_field/doc/content/source/materials/DiscreteNucleation.md
  modules/phase_field/doc/content/source/materials/ElasticEnergyMaterial.md
  modules/phase_field/doc/content/source/materials/GasFreeEnergyBase.md
  modules/phase_field/doc/content/source/materials/IdealGasFreeEnergy.md
  modules/phase_field/doc/content/source/materials/MixedSwitchingFunctionMaterial.md
  modules/phase_field/doc/content/source/materials/MultiBarrierFunctionMaterial.md
  modules/phase_field/doc/content/source/materials/VanDerWaalsFreeEnergy.md
  modules/phase_field/doc/content/source/postprocessors/DiscreteNucleationData.md
  modules/phase_field/include/auxkernels/DiscreteNucleationAux.h
  modules/phase_field/include/kernels/DiscreteNucleationForce.h
  modules/phase_field/include/postprocessors/DiscreteNucleationData.h
  modules/phase_field/src/auxkernels/DiscreteNucleationAux.C
  modules/phase_field/src/kernels/DiscreteNucleationForce.C
  modules/phase_field/src/postprocessors/DiscreteNucleationData.C
  modules/phase_field/test/tests/Nucleation/auxkernel.i
  modules/phase_field/test/tests/Nucleation/data.i
  modules/phase_field/test/tests/Nucleation/force.i
  modules/phase_field/test/tests/Nucleation/gold/auxkernel_out.e
  modules/phase_field/test/tests/Nucleation/gold/data_out.csv
  modules/phase_field/test/tests/Nucleation/gold/force_out.e
  modules/phase_field/test/tests/Nucleation/tests
  modules/rdg/doc/content/modules/rdg/index.md
  modules/tensor_mechanics/doc/content/source/kernels/InertialTorque.md
Labels: PR: Ready for Review/Merge

#12150 Add hyperbolic tangent profile to smooth circle initial conditions
  modules/phase_field/doc/content/media/tanh_interface.gpl
  modules/phase_field/doc/content/media/tanh_interface.png
  modules/phase_field/doc/content/source/ics/SmoothCircleIC.md
  modules/phase_field/doc/hidden.yml
  modules/phase_field/include/ics/SmoothCircleBaseIC.h
  modules/phase_field/src/ics/RndSmoothCircleIC.C
  modules/phase_field/src/ics/SmoothCircleBaseIC.C
  modules/phase_field/test/tests/new_initial_conditions/SmoothCircleIC_tanh.i
  modules/phase_field/test/tests/new_initial_conditions/gold/SmoothCircleIC_tanh_out.e
  modules/phase_field/test/tests/new_initial_conditions/tests
Labels: PR: Ready for Review/Merge

#11877 SmoothMesh
  framework/doc/content/media/mesh_modifiers/smooth.apng
  framework/doc/content/media/mesh_modifiers/smooth.gif
  framework/doc/content/source/meshmodifiers/SmoothMesh.md
  framework/include/meshmodifiers/SmoothMesh.h
  framework/src/meshmodifiers/SmoothMesh.C
  test/tests/mesh_modifiers/smooth_mesh/concentric_circle_mesh_in.e
  test/tests/mesh_modifiers/smooth_mesh/gold/mesh_smoother_out.e
  test/tests/mesh_modifiers/smooth_mesh/mesh_smoother.i
  test/tests/mesh_modifiers/smooth_mesh/tests
Labels: PR: Ready for Review/Merge

#12146 Remove deprecated legacy_return_mapping option
  modules/solid_mechanics/src/materials/CLSHPlasticModel.C
  modules/solid_mechanics/src/materials/ElasticModel.C
  modules/solid_mechanics/src/materials/IsotropicPlasticity.C
  modules/solid_mechanics/src/materials/PowerLawCreepModel.C
  modules/solid_mechanics/src/materials/ReturnMappingModel.C
  modules/solid_mechanics/src/materials/SolidModel.C
  modules/solid_mechanics/test/tests/combined_creep_plasticity/combined_creep_plasticity_sm2.i
  modules/tensor_mechanics/include/materials/SingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/src/materials/SingleVariableReturnMappingSolution.C
Labels: PR: Failed but allowed

#12173 Add mobile menu to website
  python/MooseDocs/base/renderers.py
Labels: PR: Failed but allowed

#12176 Error if supplied path is incorrect
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed

#12184 Make contact_us.md reference more unique
  framework/doc/content/application_usage/tracked_apps.md
Labels: PR: Auto Merge

#12182 Improve app type retrevial for MooseDocs
  framework/src/base/MooseApp.C
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/listing.py
Labels: PR: Auto Merge

#12204 Fix coupling test for BCs
  framework/include/materials/DerivativeMaterialInterface.h
Labels: PR: Auto Merge

#12199 Optimize assembly by removing coupling matrix queries
  framework/include/base/Assembly.h
  framework/src/base/Assembly.C
Labels: PR: Ready for Review/Merge

#12212 follow up to register func consolidation
  examples/ex01_inputfile/include/base/ExampleApp.h
  examples/ex01_inputfile/src/base/ExampleApp.C
  examples/ex02_kernel/include/base/ExampleApp.h
  examples/ex02_kernel/src/base/ExampleApp.C
  examples/ex03_coupling/include/base/ExampleApp.h
  examples/ex03_coupling/src/base/ExampleApp.C
  examples/ex04_bcs/include/base/ExampleApp.h
  examples/ex04_bcs/src/base/ExampleApp.C
  examples/ex05_amr/include/base/ExampleApp.h
  examples/ex05_amr/src/base/ExampleApp.C
  examples/ex06_transient/include/base/ExampleApp.h
  examples/ex06_transient/src/base/ExampleApp.C
  examples/ex07_ics/include/base/ExampleApp.h
  examples/ex07_ics/src/base/ExampleApp.C
  examples/ex08_materials/include/base/ExampleApp.h
  examples/ex08_materials/src/base/ExampleApp.C
  examples/ex09_stateful_materials/include/base/ExampleApp.h
  examples/ex09_stateful_materials/src/base/ExampleApp.C
  examples/ex10_aux/include/base/ExampleApp.h
  examples/ex10_aux/src/base/ExampleApp.C
  examples/ex11_prec/include/base/ExampleApp.h
  examples/ex11_prec/src/base/ExampleApp.C
  examples/ex12_pbp/include/base/ExampleApp.h
  examples/ex12_pbp/src/base/ExampleApp.C
  examples/ex13_functions/include/base/ExampleApp.h
  examples/ex13_functions/src/base/ExampleApp.C
  examples/ex14_pps/include/base/ExampleApp.h
  examples/ex14_pps/src/base/ExampleApp.C
  examples/ex15_actions/include/base/ExampleApp.h
  examples/ex15_actions/src/base/ExampleApp.C
  examples/ex16_timestepper/include/base/ExampleApp.h
  examples/ex16_timestepper/src/base/ExampleApp.C
  examples/ex17_dirac/include/base/ExampleApp.h
  examples/ex17_dirac/src/base/ExampleApp.C
  examples/ex18_scalar_kernel/include/base/ExampleApp.h
  examples/ex18_scalar_kernel/src/base/ExampleApp.C
  examples/ex19_dampers/include/base/ExampleApp.h
  examples/ex19_dampers/src/base/ExampleApp.C
  examples/ex20_user_objects/include/base/ExampleApp.h
  examples/ex20_user_objects/src/base/ExampleApp.C
  examples/ex21_debugging/include/base/ExampleApp.h
  examples/ex21_debugging/src/base/ExampleApp.C
  modules/chemical_reactions/test/src/base/ChemicalReactionsTestApp.C
  stork/include/base/StorkApp.h
  stork/src/base/StorkApp.C.app
  stork/test/include/base/StorkTestApp.h
  stork/test/src/base/StorkTestApp.C
Labels: PR: Ready for Review/Merge
