Repository idaholab/moose, pull requests merged in 2018-06, with the labels that each got.

#11678 Mark a few coefficents as controllable
  framework/include/timesteppers/IterationAdaptiveDT.h
  framework/src/timesteppers/IterationAdaptiveDT.C
Labels: PR: Auto Merge

#10259 Remove water_steam_eos module
  modules/combined/doc/config.yml
  modules/combined/doc/content/documentation/modules/index.md
  modules/combined/src/base/CombinedApp.C
  modules/combined/test/src/base/CombinedTestApp.C
  modules/functional_expansion_tools/unit/Makefile
  modules/module_loader/src/ModulesApp.C
  modules/modules.mk
  modules/water_steam_eos/Makefile
  modules/water_steam_eos/doc/config.yml
  modules/water_steam_eos/doc/content/documentation/modules/water_steam_eos/index.md
  modules/water_steam_eos/doc/doxygen/Doxyfile
  modules/water_steam_eos/doc/doxygen/background_navigation.png
  modules/water_steam_eos/doc/doxygen/blank.html
  modules/water_steam_eos/doc/doxygen/doxygen.css
  modules/water_steam_eos/doc/doxygen/moose_doxy_header.html
  modules/water_steam_eos/doc/doxygen/tabs.css
  modules/water_steam_eos/doc/moosedocs.py
  modules/water_steam_eos/include/Water_Steam_EOS.h
  modules/water_steam_eos/include/base/WaterSteamEOSApp.h
  modules/water_steam_eos/run_tests
  modules/water_steam_eos/src/IAPWS97.f90
  modules/water_steam_eos/src/VISS_noderiv1.f90
  modules/water_steam_eos/src/base/WaterSteamEOSApp.C
  modules/water_steam_eos/src/main.C
  modules/water_steam_eos/src/wateos_noderiv1.f90
  modules/water_steam_eos/src/water_steam_functions.f90
  modules/water_steam_eos/src/water_steam_phase_prop.f90
  modules/water_steam_eos/test/include/base/WaterSteamEOSTestApp.h
  modules/water_steam_eos/test/src/base/WaterSteamEOSTestApp.C
  modules/water_steam_eos/test/tests/kernels/simple_diffusion/gold/simple_diffusion_out.e
  modules/water_steam_eos/test/tests/kernels/simple_diffusion/simple_diffusion.i
  modules/water_steam_eos/test/tests/kernels/simple_diffusion/tests
  modules/water_steam_eos/testroot
  modules/water_steam_eos/water_steam_eos.mk
Labels: PR: Failed but allowed

#11670 Moved _line_search and _bracket_solution to protected
  modules/tensor_mechanics/include/materials/SingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/src/materials/SingleVariableReturnMappingSolution.C
Labels: PR: Failed but allowed

#11694 fix incorrect line number calculation in hit
  framework/contrib/hit/lex.cc
  framework/contrib/hit/lex.h
  unit/src/HitTests.C
Labels: PR: Auto Merge

#11728 Provide tick marks when data range is zero
  python/chigger/misc/ColorBar.py
  python/chigger/tests/colorbar/gold/zero_range.png
  python/chigger/tests/colorbar/tests
  python/chigger/tests/colorbar/zero_range.py
  python/chigger/tests/input/zero_variable.e
  python/chigger/tests/range/gold/none_0.png
  python/chigger/utils/AxisOptions.py
  python/peacock/tests/exodus_tab/gold/TestGoldDiffPlugin_testDiff.png
Labels: PR: Auto Merge

#11729 Fix spelling mistake causing config to cross streams
  python/MooseDocs/extensions/config.py
Labels: PR: Auto Merge

#11714 Modify jacobian calculation for global strain scalar kernel
  modules/tensor_mechanics/include/userobjects/GlobalStrainUserObject.h
  modules/tensor_mechanics/src/userobjects/GlobalStrainUserObject.C
Labels: PR: Failed but allowed

#11692 MaterialTimeStepPostprocessor can now use number of elements changed
  modules/tensor_mechanics/doc/content/documentation/systems/Postprocessors/MaterialTimeStepPostprocessor.md
  modules/tensor_mechanics/include/postprocessors/MaterialTimeStepPostprocessor.h
  modules/tensor_mechanics/src/postprocessors/MaterialTimeStepPostprocessor.C
  modules/tensor_mechanics/test/tests/material_limit_time_step/damage/elements_changed_timestep_limit.i
  modules/tensor_mechanics/test/tests/material_limit_time_step/damage/gold/elements_changed_timestep_limit_out.e
  modules/tensor_mechanics/test/tests/material_limit_time_step/damage/gold/mixed_timestep_limit_out.e
  modules/tensor_mechanics/test/tests/material_limit_time_step/damage/tests
Labels: PR: Ready for Review/Merge

#11753 Update appsyntax extension to build combined parameter table for SynaxNode objects
  framework/doc/content/documentation/systems/Variables/index.md
  python/MooseDocs/extensions/appsyntax.py
Labels: PR: Ready for Review/Merge
