Repository idaholab/moose, pull requests merged in 2018-10, with the labels that each got.

#12223 Adding more SQA documentation for contact verification tests.
  modules/combined/test/tests/contact_verification/patch_tests/brick_1/tests
  modules/combined/test/tests/contact_verification/patch_tests/brick_2/tests
  modules/combined/test/tests/contact_verification/patch_tests/brick_3/tests
  modules/combined/test/tests/contact_verification/patch_tests/brick_4/tests
  modules/combined/test/tests/contact_verification/patch_tests/cyl_1/tests
  modules/combined/test/tests/contact_verification/patch_tests/cyl_2/tests
  modules/combined/test/tests/contact_verification/patch_tests/cyl_3/tests
  modules/combined/test/tests/contact_verification/patch_tests/cyl_4/tests
  modules/combined/test/tests/contact_verification/patch_tests/ring_1/tests
  modules/combined/test/tests/contact_verification/patch_tests/ring_2/tests
  modules/combined/test/tests/contact_verification/patch_tests/ring_3/tests
  modules/combined/test/tests/contact_verification/patch_tests/ring_4/tests
Labels: PR: Failed but allowed

#12215 Update GlobalStrain documentation
  modules/combined/examples/periodic_strain/tests
  modules/tensor_mechanics/doc/content/syntax/Modules/TensorMechanics/GlobalStrain/index.md
  modules/tensor_mechanics/test/tests/global_strain/global_strain_direction.i
  modules/tensor_mechanics/test/tests/global_strain/tests
Labels: PR: Failed but allowed

#12221 Remove deprecated object
  modules/phase_field/doc/content/source/kernels/CHCpldPFCTrad.md
  modules/phase_field/doc/hidden.yml
  modules/phase_field/include/kernels/CHCpldPFCTrad.h
  modules/phase_field/src/kernels/CHCpldPFCTrad.C
Labels: PR: Failed but allowed

#12250 Disabled pthreads for NaNInterface tests
  modules/fluid_properties/test/tests/interfaces/nan_interface/tests
Labels: PR: Auto Merge

#12258 Disabled pthreads for RDG tests
  modules/rdg/test/tests/advection_1d/tests
Labels: PR: Auto Merge

#12259 Call plt.savefig() instead of plt.show() in git_commit_history.py
  scripts/git_commit_history.py
Labels: PR: Auto Merge

#12277 Add missing return type
  modules/combined/doc/content/newsletter/2018_10_04.md
Labels: PR: Auto Merge

#12272 MaterialOutputAction Refactor
  framework/include/actions/MaterialOutputAction.h
  framework/include/actions/SetupDebugAction.h
  framework/src/actions/CommonOutputAction.C
  framework/src/actions/MaterialOutputAction.C
  framework/src/actions/SetupDebugAction.C
  framework/src/base/Moose.C
  framework/src/base/MooseApp.C
Labels: PR: Ready for Review/Merge

#12282 Restrict test so that it doesn't run with 64-bit indices
  test/tests/relationship_managers/evaluable/tests
Labels: PR: Auto Merge

#12283 SystemBase.C cleanup
  framework/src/systems/SystemBase.C
Labels: PR: Ready for Review/Merge

#12301 Release MooseArrays introduced by automatic differentiation
  framework/src/interfaces/Coupleable.C
  framework/src/problems/FEProblemBase.C
Labels: PR: Auto Merge

#12295 Add initial from file option for Polycrystalline Variables
  modules/phase_field/src/action/PolycrystalVariablesAction.C
  modules/phase_field/test/tests/new_initial_conditions/PolycrystalVariables_initial_from_file.i
  modules/phase_field/test/tests/new_initial_conditions/gold/PolycrystalVariables_initial_from_file_out.e
  modules/phase_field/test/tests/new_initial_conditions/prepare_mesh.i
  modules/phase_field/test/tests/new_initial_conditions/tests
Labels: PR: Ready for Review/Merge

#12353 Add ability to compare subset of columns
  python/TestHarness/CSVDiffer.py
  python/TestHarness/testers/CSVDiff.py
  python/TestHarness/tests/test_CSVDiffer.py
Labels: PR: Ready for Review/Merge

#12378 Add a PRE_DISPLACE exec flag to MOOSE
  framework/include/base/Moose.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/src/auxkernels/AuxKernel.C
  framework/src/base/Moose.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
  modules/phase_field/src/postprocessors/GrainTracker.C
  modules/tensor_mechanics/src/auxkernels/GlobalDisplacementAux.C
Labels: PR: Ready for Review/Merge

#12379 Mark multistage TimeIntegrators as being "experimental".
  framework/src/timeintegrators/AStableDirk4.C
  framework/src/timeintegrators/ExplicitRK2.C
  framework/src/timeintegrators/ExplicitTVDRK2.C
  framework/src/timeintegrators/ImplicitMidpoint.C
  framework/src/timeintegrators/LStableDirk2.C
  framework/src/timeintegrators/LStableDirk3.C
  framework/src/timeintegrators/LStableDirk4.C
Labels: PR: Ready for Review/Merge

#12399 don't run adaptivity+meshmodifiers when using pre-split mesh
  framework/include/base/Adaptivity.h
  framework/src/actions/AdaptivityAction.C
  framework/src/actions/SetupMeshCompleteAction.C
  test/tests/postprocessors/num_elems/gold/num_elems_split_out.csv
  test/tests/postprocessors/num_nodes/gold/num_nodes_split_out.csv
Labels: PR: Failed but allowed

#12398 Regolding random5 test due to random displacements in the solution
  modules/tensor_mechanics/test/tests/capped_mohr_coulomb/gold/random5.e
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12400 Don't update the test results when using --failed-tests
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12402 Extend NormalizationAux to be able to shift value
  framework/include/auxkernels/NormalizationAux.h
  framework/src/auxkernels/NormalizationAux.C
  test/tests/auxkernels/normalization_aux/gold/normalization_aux_out.e
  test/tests/auxkernels/normalization_aux/gold/normalization_aux_shift.e
  test/tests/auxkernels/normalization_aux/normalization_aux.i
  test/tests/auxkernels/normalization_aux/tests
Labels: PR: Failed but allowed

#12348 Numerical diffusion doco of PorousFlow includes RDG comparison
  framework/doc/content/media/porous_flow/framework_dt.png
  framework/doc/content/media/porous_flow/framework_eles.png
  framework/doc/content/media/porous_flow/numerical_diffusion_summary_100_100.png
  framework/doc/content/media/porous_flow/numerical_diffusion_summary_100_1000.png
  framework/doc/content/media/porous_flow/rdgP0P1_dt.png
  framework/doc/content/media/porous_flow/rdgP0P1_eles.png
  framework/doc/content/media/porous_flow/rdgP0_dt.png
  framework/doc/content/media/porous_flow/rdgP0_eles.png
  modules/porous_flow/Makefile
  modules/porous_flow/doc/config.yml
  modules/porous_flow/doc/content/modules/porous_flow/numerical_diffusion.md
  modules/porous_flow/src/base/PorousFlowApp.C
  modules/porous_flow/test/tests/numerical_diffusion/framework.i
  modules/porous_flow/test/tests/numerical_diffusion/gold/framework_out_tracer_0011.csv
  modules/porous_flow/test/tests/numerical_diffusion/tests
  modules/rdg/include/userobjects/AEFVFreeOutflowBoundaryFlux.h
  modules/rdg/include/userobjects/AEFVUpwindInternalSideFlux.h
  modules/rdg/src/userobjects/AEFVFreeOutflowBoundaryFlux.C
  modules/rdg/src/userobjects/AEFVUpwindInternalSideFlux.C
  modules/rdg/test/tests/advection_1d/gold/rdgP0_out_tracer_0011.csv
  modules/rdg/test/tests/advection_1d/rdgP0.i
  modules/rdg/test/tests/advection_1d/tests
  unit/Makefile
Labels: PR: Do Not Merge, PR: Failed but allowed

#12406 Change array size of ADReal.
  framework/include/utils/MooseTypes.h
Labels: PR: Failed but allowed
