Repository idaholab/moose, pull requests merged in 2018-12, with the labels that each got.

#12566 Fix combination of volumetric_locking_correction and use_finite_deform_jacobian
  modules/tensor_mechanics/src/kernels/StressDivergenceTensors.C
Labels: PR: Failed but allowed

#12564 Improve example 5 and adaptivity pages
  examples/ex05_amr/ex05.i
  examples/ex06_transient/ex06.i
  examples/ex06_transient/src/kernels/ExampleTimeDerivative.C
  framework/doc/content/syntax/Adaptivity/index.md
  framework/doc/content/syntax/Executioner/Adaptivity/index.md
  modules/doc/content/examples/ex01_inputfile.md
  modules/doc/content/examples/ex05_amr.md
  modules/doc/content/examples/ex06_transient.md
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#12575 Additional diagnostics
  scripts/diagnostics.sh
Labels: PR: Ready for Review/Merge

#12602 Minor changes for MOOSEDocs and chigger
  python/MooseDocs/extensions/include.py
  python/MooseDocs/tree/pages.py
  python/chigger/utils/__init__.py
Labels: PR: Auto Merge

#12481 Rename block parameter in LayeredBase
  framework/include/userobject/LayeredBase.h
  framework/src/userobject/LayeredBase.C
  framework/src/userobject/LayeredSideIntegral.C
  test/tests/userobjects/layered_average/block_restricted_num_layers.i
  test/tests/userobjects/layered_average/gold/layered_average_bounding_block_out.e
  test/tests/userobjects/layered_average/layered_average_bounding_block.e
  test/tests/userobjects/layered_average/layered_average_bounding_block.i
  test/tests/userobjects/layered_average/tests
  test/tests/userobjects/layered_side_integral/tests
Labels: PR: Failed but allowed

#12614 Move operator*(const Scalar & scalar) into header for RankFourTensor
  framework/include/utils/RankFourTensor.h
  framework/src/utils/RankFourTensor.C
Labels: PR: Auto Merge, PR: Failed but allowed

#12592 Update moose-environment package
  framework/doc/packages_config.yml
  package_version
Labels: PR: Ready for Review/Merge

#12604 Dec 2018 MOOSEletter
  modules/doc/content/newsletter/2018_12.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#12620 Added matrix time tag to ODETimeKernel
  framework/src/kernels/ODETimeKernel.C
  test/tests/time_integrators/actually_explicit_euler_verification/ee-ode.i
  test/tests/time_integrators/actually_explicit_euler_verification/gold/ee-ode_out.csv
  test/tests/time_integrators/actually_explicit_euler_verification/tests
Labels: PR: Failed but allowed
