Repository idaholab/moose, pull requests merged in 2018-05, with the labels that each got.

#11356 Documenting a few InitialCondition classes.
  framework/doc/content/documentation/systems/ICs/BoundingBoxIC.md
  framework/doc/content/documentation/systems/ICs/ConstantIC.md
  framework/doc/content/documentation/systems/ICs/FunctionIC.md
  framework/doc/content/documentation/systems/ICs/RandomIC.md
  framework/include/ics/BoundingBoxIC.h
  framework/include/ics/ConstantIC.h
  framework/include/ics/FunctionIC.h
  framework/src/ics/BoundingBoxIC.C
  framework/src/ics/ConstantIC.C
  framework/src/ics/FunctionIC.C
  framework/src/ics/RandomIC.C
  modules/phase_field/doc/content/documentation/systems/ICs/MultiBoundingBoxIC.md
  modules/phase_field/include/ics/MultiBoundingBoxIC.h
  modules/phase_field/src/ics/MultiBoundingBoxIC.C
Labels: PR: Ready to Merge

#11382 Added fractional option to MaxIncrement damper
  framework/include/dampers/MaxIncrement.h
  framework/src/dampers/MaxIncrement.C
  test/tests/dampers/max_increment/max_increment_damper_test.i
  test/tests/dampers/max_increment/tests
Labels: PR: [TODO] Please address comments

#11400 Test Chorin code in Navier Stokes module
  modules/navier_stokes/include/kernels/INSChorinPredictor.h
  modules/navier_stokes/src/kernels/INSChorinPredictor.C
  modules/navier_stokes/test/tests/ins/lid_driven/gold/lid_driven_chorin_out.e
  modules/navier_stokes/test/tests/ins/lid_driven/lid_driven_chorin.i
  modules/navier_stokes/test/tests/ins/lid_driven/tests
Labels: PR: Ready to Merge

#11405 Fix issue with VTKWindowPlugin highlighting
  python/peacock/ExodusViewer/plugins/VTKWindowPlugin.py
  python/peacock/tests/input_tab/InputFileEditorWithMesh/gold/meshrender_highlight_dup.png
  python/peacock/tests/input_tab/InputFileEditorWithMesh/test_InputFileEditorWithMesh.py
Labels: PR: Ready to Merge

#11274 Vpp visualization
  framework/doc/content/documentation/systems/AuxKernels/VectorPostprocessorVisualizationAux.md
  framework/doc/content/documentation/systems/VectorPostprocessors/WorkBalance.md
  framework/include/auxkernels/VectorPostprocessorVisualizationAux.h
  framework/include/vectorpostprocessors/WorkBalance.h
  framework/src/auxkernels/VectorPostprocessorVisualizationAux.C
  framework/src/problems/FEProblemBase.C
  framework/src/vectorpostprocessors/WorkBalance.C
  test/tests/auxkernels/vector_postprocessor_visualization/gold/vector_postprocessor_visualization_out.e
  test/tests/auxkernels/vector_postprocessor_visualization/tests
  test/tests/auxkernels/vector_postprocessor_visualization/vector_postprocessor_visualization.i
Labels: PR: Ready to Merge

#11363 Control system re-factor
  framework/doc/content/documentation/systems/Controls/index.md
  framework/include/controls/Control.h
  framework/include/controls/ControllableItem.h
  framework/include/controls/ControllableParameter.h
  framework/include/controls/RealFunctionControl.h
  framework/include/materials/GenericConstantMaterial.h
  framework/include/utils/InputParameterWarehouse.h
  framework/src/base/MooseObject.C
  framework/src/controls/Control.C
  framework/src/controls/ControllableItem.C
  framework/src/controls/ControllableParameter.C
  framework/src/materials/GenericConstantMaterial.C
  framework/src/outputs/ControlOutput.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/InputParameterWarehouse.C
  framework/src/utils/InputParameters.C
  modules/stochastic_tools/include/controls/SamplerReceiver.h
  modules/stochastic_tools/include/transfers/SamplerTransfer.h
  modules/stochastic_tools/src/controls/SamplerReceiver.C
  modules/stochastic_tools/src/transfers/SamplerTransfer.C
  modules/stochastic_tools/test/tests/transfers/errors/tests
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/errors/tests
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/gold/master_out_sub0.csv
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/gold/master_out_sub1.csv
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/gold/master_out_sub2.csv
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/gold/master_out_sub3.csv
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/gold/master_out_sub4.csv
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/gold/sub_out.csv
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/master.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/master_not_enough_data.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/master_size_mismatch.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/sub.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/tests
  test/src/controls/TestControl.C
  test/tests/controls/error/tests
  unit/src/ControllableItemTest.C
  unit/src/ControllableParameterTest.C
  unit/src/InputParameterWarehouseTest.C
  unit/src/InputParametersTest.C
Labels: PR: Failed but allowed, PR: Ready to Merge

#10951 Custom line search for mechanical contact
  framework/doc/content/bib/moose.bib
  framework/doc/content/documentation/systems/LineSearches/index.md
  framework/include/linesearches/LineSearch.h
  framework/include/problems/DumpObjectsProblem.h
  framework/include/problems/FEProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/utils/MooseTypes.h
  framework/include/utils/MooseUtils.h
  framework/include/utils/PetscSupport.h
  framework/src/executioners/Executioner.C
  framework/src/linesearches/LineSearch.C
  framework/src/problems/FEProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/Conversion.C
  framework/src/utils/PetscSupport.C
  modules/combined/test/tests/contact_verification/patch_tests/single_pnt_2d/gold/single_point_2d_contact_line_search_out.csv
  modules/combined/test/tests/contact_verification/patch_tests/single_pnt_2d/single_point_2d_contact_line_search.i
  modules/combined/test/tests/contact_verification/patch_tests/single_pnt_2d/tests
  modules/combined/test/tests/sliding_block/in_and_out/constraint/frictionless_penalty_contact_line_search.i
  modules/combined/test/tests/sliding_block/in_and_out/constraint/gold/frictionless_penalty_contact_line_search_exodus.e
  modules/combined/test/tests/sliding_block/in_and_out/constraint/tests
  modules/contact/doc/content/documentation/systems/LineSearches/ContactLineSearch.md
  modules/contact/include/ContactLineSearchBase.h
  modules/contact/include/MechanicalContactConstraint.h
  modules/contact/include/PetscContactLineSearch.h
  modules/contact/src/ContactAction.C
  modules/contact/src/ContactLineSearchBase.C
  modules/contact/src/MechanicalContactConstraint.C
  modules/contact/src/PetscContactLineSearch.C
Labels: PR: Failed but allowed

#11457 Fix AnalyzeJacobian race conditions
  modules/tensor_mechanics/test/tests/creep_tangent_operator/tests
  python/TestHarness/testers/AnalyzeJacobian.py
  python/TestHarness/tests/test_Duplicate.py
  test/tests/test_harness/duplicate_outputs_analyzejacobian
  test/tests/test_harness/duplicate_outputs_ok
Labels: PR: Failed but allowed

#11431 Allow for python3 to be the default python in python unit tests.
  python/TestHarness/testers/PythonUnitTest.py
Labels: PR: Failed but allowed

#11455 Disallow use_displaced_mesh on markers
  framework/src/markers/Marker.C
  test/tests/markers/expected_error/displaced_error.i
  test/tests/markers/expected_error/tests
Labels: PR: Failed but allowed

#11308 Voce hardening
  modules/tensor_mechanics/doc/content/documentation/systems/UserObjects/CrystalPlasticityStateVarRateComponentVoce.md
  modules/tensor_mechanics/include/userobjects/CrystalPlasticityStateVarRateComponentVoce.h
  modules/tensor_mechanics/src/userobjects/CrystalPlasticityStateVarRateComponentVoce.C
  modules/tensor_mechanics/test/tests/cp_user_object/crysp_user_object_Voce_BCC.i
  modules/tensor_mechanics/test/tests/cp_user_object/gold/crysp_user_object_Voce_BCC_out.e
  modules/tensor_mechanics/test/tests/cp_user_object/gold/crysp_user_object_Voce_BCC_out.e~HEAD
  modules/tensor_mechanics/test/tests/cp_user_object/gold/crysp_user_object_Voce_BCC_out.e~HEAD_0
  modules/tensor_mechanics/test/tests/cp_user_object/input_slip_sys_bcc12.txt
  modules/tensor_mechanics/test/tests/cp_user_object/input_slip_sys_bcc24.txt
  modules/tensor_mechanics/test/tests/cp_user_object/input_slip_sys_bcc48.txt
  modules/tensor_mechanics/test/tests/cp_user_object/tests
Labels: PR: Failed but allowed, PR: Ready to Merge

#11438 GridPartitioner
  framework/doc/content/documentation/systems/Mesh/Partitioner/GridPartitioner.md
  framework/include/partitioner/GridPartitioner.h
  framework/src/partitioner/GridPartitioner.C
  test/tests/partitioners/grid_partitioner/gold/grid_partitioner_out.e
  test/tests/partitioners/grid_partitioner/grid_partitioner.i
  test/tests/partitioners/grid_partitioner/tests
Labels: PR: Ready to Merge

#11358 Implementing strain periodicity
  framework/include/utils/RankTwoTensor.h
  framework/src/utils/RankTwoTensor.C
  modules/combined/examples/periodic_strain/global_strain_pfm.i
  modules/combined/examples/periodic_strain/global_strain_pfm_3D.i
  modules/combined/examples/periodic_strain/tests
  modules/tensor_mechanics/doc/content/documentation/systems/AuxKernels/GlobalDisplacementAux.md
  modules/tensor_mechanics/doc/content/documentation/systems/Materials/ComputeGlobalStrain.md
  modules/tensor_mechanics/doc/content/documentation/systems/ScalarKernels/GlobalStrain.md
  modules/tensor_mechanics/doc/content/documentation/systems/UserObjects/GlobalStrainUserObject.md
  modules/tensor_mechanics/include/auxkernels/GlobalDisplacementAux.h
  modules/tensor_mechanics/include/materials/ComputeGlobalStrain.h
  modules/tensor_mechanics/include/materials/ComputeStrainBase.h
  modules/tensor_mechanics/include/scalarkernels/GlobalStrain.h
  modules/tensor_mechanics/include/userobjects/GlobalStrainUserObject.h
  modules/tensor_mechanics/src/auxkernels/GlobalDisplacementAux.C
  modules/tensor_mechanics/src/materials/ComputeFiniteStrain.C
  modules/tensor_mechanics/src/materials/ComputeGlobalStrain.C
  modules/tensor_mechanics/src/materials/ComputeSmallStrain.C
  modules/tensor_mechanics/src/materials/ComputeStrainBase.C
  modules/tensor_mechanics/src/scalarkernels/GlobalStrain.C
  modules/tensor_mechanics/src/userobjects/GlobalStrainUserObject.C
  modules/tensor_mechanics/test/tests/global_strain/global_strain.i
  modules/tensor_mechanics/test/tests/global_strain/global_strain_hydrostat.i
  modules/tensor_mechanics/test/tests/global_strain/global_strain_shear.i
  modules/tensor_mechanics/test/tests/global_strain/global_strain_uniaxial.i
  modules/tensor_mechanics/test/tests/global_strain/gold/global_strain_hydrostat_out.e
  modules/tensor_mechanics/test/tests/global_strain/gold/global_strain_out.e
  modules/tensor_mechanics/test/tests/global_strain/gold/global_strain_shear_out.e
  modules/tensor_mechanics/test/tests/global_strain/gold/global_strain_uniaxial_out.e
  modules/tensor_mechanics/test/tests/global_strain/tests
Labels: PR: Ready to Merge

#11483 Fix invalid race condition check
  modules/solid_mechanics/test/tests/j_integral_vtest/tests
  modules/tensor_mechanics/test/tests/j_integral_vtest/tests
  python/TestHarness/JobDAG.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/testers/AnalyzeJacobian.py
  python/TestHarness/tests/test_Duplicate.py
  python/TestHarness/tests/tests
  test/tests/mesh/adapt/tests
  test/tests/test_harness/duplicate_outputs_prereqs
  test/tests/test_harness/multiple_duplicate_outputs
Labels: PR: Auto Merge

#11498 Add --recover unittest
  python/TestHarness/tests/test_Recover.py
  python/TestHarness/tests/tests
Labels: PR: Auto Merge

#11502 Improve assignment of processor_id for new XFEM nodes
  modules/xfem/src/base/XFEM.C
  modules/xfem/test/tests/bimaterials/glued_bimaterials_2d.i
  modules/xfem/test/tests/bimaterials/gold/glued_bimaterials_2d_out.e
  modules/xfem/test/tests/bimaterials/gold/inclusion_bimaterials_2d_out.e
  modules/xfem/test/tests/bimaterials/inclusion_bimaterials_2d.i
Labels: PR: Auto Merge, PR: Failed but allowed

#11510 Remove incorrect padding
  framework/doc/content/css/moose.css
Labels: PR: Auto Merge

#11508 Set libmesh_static in framework/build.mk
  framework/build.mk
Labels: PR: Auto Merge, PR: Failed but allowed

#11518 Fix run_test when in test dir
  python/TestHarness/TestHarness.py
Labels: PR: Auto Merge

#11526 Close Aux System
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystemBase.C
  test/include/materials/ExceptionMaterial.h
  test/src/materials/ExceptionMaterial.C
  test/tests/materials/material/exception_material.i
  test/tests/materials/material/gold/exception_material_out.e
  test/tests/materials/material/tests
Labels: PR: Auto Merge

#11536 Swap petsc private ops for public functions in PetscContactLineSearch
  modules/contact/src/PetscContactLineSearch.C
Labels: PR: Auto Merge

#11539 Document passing in debugger commands
  framework/doc/content/documentation/application_development/debugging.md
Labels: PR: Auto Merge

#11387 Add an action to generate kernels for grand potential model
  modules/phase_field/doc/content/bib/phase_field.bib
  modules/phase_field/doc/content/documentation/systems/Modules/PhaseField/GrandPotential/GrandPotentialKernelAction.md
  modules/phase_field/doc/content/documentation/systems/Modules/PhaseField/GrandPotential/index.md
  modules/phase_field/include/action/GrandPotentialKernelAction.h
  modules/phase_field/src/action/GrandPotentialKernelAction.C
  modules/phase_field/src/base/PhaseFieldApp.C
  modules/phase_field/test/tests/actions/gold/gpm_kernel_out.e
  modules/phase_field/test/tests/actions/gpm_kernel.i
  modules/phase_field/test/tests/actions/tests
Labels: PR: Ready for Review/Merge

#11557 fix hit python bindings build for certain environments.
  framework/contrib/hit/Makefile
  framework/moose.mk
Labels: PR: Auto Merge

#11505 DistributedGeneratedMesh
  framework/doc/content/documentation/systems/Mesh/DistributedGeneratedMesh.md
  framework/include/mesh/DistributedGeneratedMesh.h
  framework/src/mesh/DistributedGeneratedMesh.C
  modules/phase_field/doc/content/documentation/systems/Mesh/MortarPeriodicMesh.md
  test/tests/mesh/distributed_generated_mesh/distributed_generated_mesh.i
  test/tests/mesh/distributed_generated_mesh/gold/d1.e
  test/tests/mesh/distributed_generated_mesh/gold/d2.e
  test/tests/mesh/distributed_generated_mesh/gold/d3.e
  test/tests/mesh/distributed_generated_mesh/tests
  test/tests/mesh/distributed_generated_mesh_bias/distributed_generated_mesh_bias.i
  test/tests/mesh/distributed_generated_mesh_bias/gold/bias.e
  test/tests/mesh/distributed_generated_mesh_bias/tests
Labels: PR: Ready for Review/Merge

#11569 Fix 64-bit build issues.
  framework/src/mesh/DistributedGeneratedMesh.C
Labels: PR: Auto Merge

#11503 initial_stress input parameter removed from TensorMechanics
  modules/tensor_mechanics/include/materials/ComputeFiniteStrainElasticStress.h
  modules/tensor_mechanics/include/materials/ComputeMultiPlasticityStress.h
  modules/tensor_mechanics/include/materials/ComputeStressBase.h
  modules/tensor_mechanics/src/materials/ComputeCosseratLinearElasticStress.C
  modules/tensor_mechanics/src/materials/ComputeFiniteStrainElasticStress.C
  modules/tensor_mechanics/src/materials/ComputeLinearElasticStress.C
  modules/tensor_mechanics/src/materials/ComputeMultiPlasticityStress.C
  modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
  modules/tensor_mechanics/src/materials/ComputeSmearedCrackingStress.C
  modules/tensor_mechanics/src/materials/ComputeStressBase.C
Labels: PR: Failed but allowed

#11581 Increase unit test coverage in fluid properties module
  modules/fluid_properties/include/userobjects/BrineFluidProperties.h
  modules/fluid_properties/include/userobjects/MultiComponentFluidPropertiesPT.h
  modules/fluid_properties/src/userobjects/BrineFluidProperties.C
  modules/fluid_properties/src/userobjects/CO2FluidProperties.C
  modules/fluid_properties/src/userobjects/MethaneFluidProperties.C
  unit/include/TabulatedFluidPropertiesTest.h
  unit/src/BrineFluidPropertiesTest.C
  unit/src/CO2FluidPropertiesTest.C
  unit/src/MethaneFluidPropertiesTest.C
  unit/src/TabulatedFluidPropertiesTest.C
  unit/src/Water97FluidPropertiesTest.C
Labels: PR: Failed but allowed

#11428 VPP parallel consistency
  framework/doc/content/documentation/systems/VectorPostprocessors/index.md
  framework/include/auxkernels/AuxKernel.h
  framework/include/auxkernels/VectorPostprocessorVisualizationAux.h
  framework/include/problems/FEProblemBase.h
  framework/include/userobject/GeneralUserObject.h
  framework/include/utils/MooseTypes.h
  framework/include/vectorpostprocessors/VectorPostprocessor.h
  framework/include/vectorpostprocessors/VectorPostprocessorData.h
  framework/include/vectorpostprocessors/VectorPostprocessorInterface.h
  framework/src/auxkernels/AuxKernel.C
  framework/src/auxkernels/VectorPostprocessorVisualizationAux.C
  framework/src/kernels/ScalarKernel.C
  framework/src/problems/FEProblemBase.C
  framework/src/userobject/GeneralUserObject.C
  framework/src/vectorpostprocessors/CSVReader.C
  framework/src/vectorpostprocessors/ConstantVectorPostprocessor.C
  framework/src/vectorpostprocessors/ElementVariablesDifferenceMax.C
  framework/src/vectorpostprocessors/SamplerBase.C
  framework/src/vectorpostprocessors/VectorOfPostprocessors.C
  framework/src/vectorpostprocessors/VectorPostprocessor.C
  framework/src/vectorpostprocessors/VectorPostprocessorData.C
  framework/src/vectorpostprocessors/VectorPostprocessorInterface.C
  test/src/auxkernels/VectorPostprocessorAux.C
  test/src/scalarkernels/VectorPostprocessorScalarKernel.C
  test/tests/auxkernels/vectorpostprocessor/vectorpostprocessor.i
  test/tests/kernels/scalarkernel_vectorpostprocessor/scalarkernel_vectorpostprocessor.i
  test/tests/vectorpostprocessors/parallel_consistency/gold/broadcast_out.e
  test/tests/vectorpostprocessors/parallel_consistency/gold/constant_vector_postprocessor_out_constant_0001.csv
  test/tests/vectorpostprocessors/parallel_consistency/gold/parallel_consistency_out.e
  test/tests/vectorpostprocessors/parallel_consistency/parallel_consistency.i
  test/tests/vectorpostprocessors/parallel_consistency/tests
Labels: PR: Ready for Review/Merge

#11590 Give MooseMesh::clone() non-pure-virtual-error error implementation.
  framework/include/mesh/AnnularMesh.h
  framework/include/mesh/DistributedGeneratedMesh.h
  framework/include/mesh/FileMesh.h
  framework/include/mesh/GeneratedMesh.h
  framework/include/mesh/ImageMesh.h
  framework/include/mesh/MooseMesh.h
  framework/include/mesh/PatternedMesh.h
  framework/include/mesh/StitchedMesh.h
  framework/include/mesh/TiledMesh.h
  framework/src/mesh/AnnularMesh.C
  framework/src/mesh/DistributedGeneratedMesh.C
  framework/src/mesh/FileMesh.C
  framework/src/mesh/GeneratedMesh.C
  framework/src/mesh/ImageMesh.C
  framework/src/mesh/MooseMesh.C
  framework/src/mesh/PatternedMesh.C
  framework/src/mesh/StitchedMesh.C
  framework/src/mesh/TiledMesh.C
Labels: PR: Ready for Review/Merge

#11607 Fixed ElementValueSampler test in parallel
  test/tests/vectorpostprocessors/element_value_sampler/element_value_sampler.i
  test/tests/vectorpostprocessors/element_value_sampler/gold/element_value_sampler_element_value_sampler_0000.csv
Labels: PR: Auto Merge

#11537 Improve TensorMechanics documentation.
  modules/contact/doc/content/documentation/systems/Problem/ReferenceResidualProblem.md
  modules/tensor_mechanics/doc/content/documentation/systems/AuxScalarKernels/GeneralizedPlaneStrainReferenceResidual.md
  modules/tensor_mechanics/doc/content/documentation/systems/Modules/TensorMechanics/GeneralizedPlaneStrain/GeneralizedPlaneStrainAction.md
  modules/tensor_mechanics/doc/content/documentation/systems/Postprocessors/CavityPressurePostprocessor.md
  modules/tensor_mechanics/doc/content/documentation/systems/UserObjects/GeneralizedPlaneStrainUserObject.md
  modules/tensor_mechanics/include/postprocessors/CavityPressurePostprocessor.h
  modules/tensor_mechanics/include/userobjects/CavityPressureUserObject.h
  modules/tensor_mechanics/src/actions/CavityPressurePPAction.C
  modules/tensor_mechanics/src/postprocessors/CavityPressurePostprocessor.C
  modules/tensor_mechanics/src/userobjects/CavityPressureUserObject.C
  modules/tensor_mechanics/src/userobjects/GeneralizedPlaneStrainUserObject.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#11566 Adding Pressure BC for multi-app runs
  modules/tensor_mechanics/doc/content/documentation/systems/BCs/CoupledPressure/CoupledPressureAction.md
  modules/tensor_mechanics/doc/content/documentation/systems/BCs/CoupledPressure/index.md
  modules/tensor_mechanics/doc/content/documentation/systems/BCs/CoupledPressureBC.md
  modules/tensor_mechanics/include/actions/CoupledPressureAction.h
  modules/tensor_mechanics/include/bcs/CoupledPressureBC.h
  modules/tensor_mechanics/src/actions/CoupledPressureAction.C
  modules/tensor_mechanics/src/base/TensorMechanicsApp.C
  modules/tensor_mechanics/src/bcs/CoupledPressureBC.C
  modules/tensor_mechanics/test/tests/coupled_pressure/coupled_pressure_test.exodiff
  modules/tensor_mechanics/test/tests/coupled_pressure/coupled_pressure_test.i
  modules/tensor_mechanics/test/tests/coupled_pressure/gold/coupled_pressure_test_out.e
  modules/tensor_mechanics/test/tests/coupled_pressure/pressure_test.e
  modules/tensor_mechanics/test/tests/coupled_pressure/tests
Labels: PR: Failed but allowed

#11604 Docs for TM Axisymmetric1D strains
  modules/tensor_mechanics/doc/content/documentation/modules/tensor_mechanics/common/supplementalAxisymmetricRZStrain.md
  modules/tensor_mechanics/doc/content/documentation/systems/Kernels/StressDivergenceRZTensors.md
  modules/tensor_mechanics/doc/content/documentation/systems/Materials/ComputeAxisymmetric1DFiniteStrain.md
  modules/tensor_mechanics/doc/content/documentation/systems/Materials/ComputeAxisymmetric1DIncrementalStrain.md
  modules/tensor_mechanics/doc/content/documentation/systems/Materials/ComputeAxisymmetric1DSmallStrain.md
  modules/tensor_mechanics/doc/content/documentation/systems/Materials/ComputeAxisymmetricRZFiniteStrain.md
  modules/tensor_mechanics/doc/content/documentation/systems/Materials/ComputeAxisymmetricRZIncrementalStrain.md
  modules/tensor_mechanics/doc/hidden.yml
  modules/tensor_mechanics/src/materials/Compute1DFiniteStrain.C
  modules/tensor_mechanics/test/tests/1D_axisymmetric/axisymm_gps_finite.i
  modules/tensor_mechanics/test/tests/1D_axisymmetric/axisymm_gps_incremental.i
  modules/tensor_mechanics/test/tests/1D_axisymmetric/axisymm_gps_small.i
Labels: PR: Ready for Review/Merge

#11587 Make interface kernels work with boundary restricted stateful materials
  framework/doc/content/documentation/systems/InterfaceKernels/index.md
  framework/src/loops/ComputeJacobianThread.C
  framework/src/loops/ComputeMaterialsObjectThread.C
  framework/src/loops/ComputeResidualThread.C
  framework/src/systems/NonlinearSystemBase.C
  test/include/interfacekernels/InterfaceDiffusion.h
  test/src/interfacekernels/InterfaceDiffusion.C
  test/tests/interfacekernels/1d_interface/coupled_value_coupled_flux.i
  test/tests/interfacekernels/1d_interface/tests
Labels: PR: Ready for Review/Merge

#11613 Fix peacock InputTree test.
  python/peacock/tests/input_tab/InputTree/test_InputTree.py
Labels: PR: Auto Merge
