Repository idaholab/moose, pull requests merged in 2019-01, with the labels that each got.

#12611 Fix regex in MOOSEDocs package extension
  python/MooseDocs/extensions/package.py
Labels: PR: Failed but allowed

#12623 Fix hang with segfault TestHarness and PBS
  scripts/are_queued_jobs_finished.py
Labels: PR: Failed but allowed

#12643 Inactive Initial MultiApp
  framework/include/warehouses/MooseObjectWarehouse.h
  framework/include/warehouses/MooseObjectWarehouseBase.h
  framework/src/problems/FEProblemBase.C
  test/tests/multiapps/initial_intactive/gold/master_out_sub0.e
  test/tests/multiapps/initial_intactive/master.i
  test/tests/multiapps/initial_intactive/sub.i
  test/tests/multiapps/initial_intactive/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#12653 Fix typo in are_queued_jobs_finished.py
  scripts/are_queued_jobs_finished.py
Labels: PR: Auto Merge

#12613 Windows 10 update instructions
  modules/doc/content/getting_started/installation/centos_pre_req.md
  modules/doc/content/getting_started/installation/fedora_pre_req.md
  modules/doc/content/getting_started/installation/mint_pre_req.md
  modules/doc/content/getting_started/installation/opensuse_pre_req.md
  modules/doc/content/getting_started/installation/ubuntu_pre_req.md
  modules/doc/content/getting_started/installation/windows10.md
Labels: PR: Ready for Review/Merge

#12661 Loosened test tolerances and added tests for diffusion in Misc
  modules/combined/test/tests/coef_diffusion/coef_diffusion_test.i
  modules/combined/test/tests/coef_diffusion/func_diffusion_test.i
  modules/combined/test/tests/coef_diffusion/gold/out.e
  modules/combined/test/tests/coef_diffusion/square.e
  modules/combined/test/tests/coef_diffusion/tests
  modules/heat_conduction/test/tests/heat_source_bar/tests
  modules/heat_conduction/test/tests/verify_against_analytical/tests
  modules/misc/doc/content/source/kernels/CoefDiffusion.md
  modules/misc/test/tests/kernels/diffusion/1D_transient.i
  modules/misc/test/tests/kernels/diffusion/2d_steady_state_final_prob.i
  modules/misc/test/tests/kernels/diffusion/ad_1D_transient.i
  modules/misc/test/tests/kernels/diffusion/ad_2d_steady_state_final_prob.i
  modules/misc/test/tests/kernels/diffusion/gold/1D_transient_out.e
  modules/misc/test/tests/kernels/diffusion/gold/2d_steady_state_final_prob_out.e
  modules/misc/test/tests/kernels/diffusion/gold/ad_1D_transient_out.e
  modules/misc/test/tests/kernels/diffusion/gold/ad_2d_steady_state_final_prob_out.e
  modules/misc/test/tests/kernels/diffusion/tests
  modules/misc/test/tests/kernels/simple_diffusion/gold/simple_diffusion_out.e
  modules/misc/test/tests/kernels/simple_diffusion/simple_diffusion.i
  modules/misc/test/tests/kernels/simple_diffusion/tests
  modules/misc/test/tests/kernels/thermo_diffusion/tests
Labels: PR: Ready for Review/Merge

#12665 Shrink down test a bit due to timeouts
  modules/phase_field/test/tests/rigidbodymotion/update_orientation_verify.i
Labels: PR: Ready for Review/Merge

#12660 Add memory units to documentation
  framework/doc/content/source/postprocessors/MemoryUsage.md
  framework/doc/content/source/vectorpostprocessors/VectorMemoryUsage.md
  framework/include/postprocessors/MemoryUsage.h
  framework/include/utils/MemoryUtils.h
  framework/include/vectorpostprocessors/VectorMemoryUsage.h
  framework/src/postprocessors/MemoryUsage.C
  framework/src/utils/MemoryUtils.C
  framework/src/vectorpostprocessors/VectorMemoryUsage.C
  test/tests/postprocessors/memory_usage/vector_memory_usage.i
Labels: PR: Ready for Review/Merge

#12669 Fix new test harness race condition
  modules/heat_conduction/test/tests/heat_source_bar/tests
Labels: PR: Auto Merge

#12668 Sort the source page list
  modules/doc/content/help.menu.md
  modules/doc/content/help/a-to-z.md
  python/MooseDocs/extensions/content.py
  python/MooseDocs/test/gold/html/extensions/content.html
  python/MooseDocs/test/gold/json/extensions/content.json
  python/MooseDocs/test/gold/latex/extensions/content.tex
  python/MooseDocs/test/gold/materialize/extensions/content.html
Labels: PR: Auto Merge, PR: Failed but allowed

#12663 Brace expressions in HIT
  framework/contrib/hit/Makefile
  framework/contrib/hit/braceexpr.cc
  framework/contrib/hit/braceexpr.h
  framework/contrib/hit/hit.h
  framework/contrib/hit/lex.cc
  framework/contrib/hit/main.cc
  framework/contrib/hit/parse.cc
  framework/include/parser/Parser.h
  framework/moose.mk
  framework/src/parser/Parser.C
  modules/doc/content/application_usage/index.md
  modules/doc/content/application_usage/input_syntax.md
  unit/src/HitTests.C
Labels: PR: Ready for Review/Merge

#12683 Exodiff-like summary output
  python/csvdiff/csvdiff.py
Labels: PR: Do Not Merge

#12690 Loosen tolerances in some periodic bc tests
  modules/phase_field/test/tests/MultiSmoothCircleIC/tests
  modules/phase_field/test/tests/TotalFreeEnergy/tests
  modules/phase_field/test/tests/grain_tracker_test/tests
Labels: PR: Auto Merge

#12699 Improve MooseApp::restore() API
  framework/include/base/MooseApp.h
  framework/src/base/MooseApp.C
  framework/src/multiapps/MultiApp.C
Labels: PR: Ready for Review/Merge

#12689 Some DualNumber related header clean-up
  framework/include/kernels/ADKernel.h
  framework/include/materials/ADMaterial.h
  framework/include/restart/DataIO.h
  framework/include/utils/ColumnMajorMatrix.h
  framework/include/utils/MooseUtils.h
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankTwoTensor.h
  framework/src/utils/ColumnMajorMatrix.C
  framework/src/utils/MooseADWrapper.C
  framework/src/utils/RankFourTensor.C
  framework/src/utils/RankTwoTensor.C
  modules/tensor_mechanics/src/utils/ElasticityTensorTools.C
Labels: PR: Failed but allowed

#12716 Remove support for Intel Compilers
  modules/doc/content/application_development/debugging.md
  modules/doc/content/examples/ex21_debugging.md
  modules/doc/content/getting_started/installation/manual_gcc.md
  modules/doc/content/getting_started/minimum_requirements.md
  modules/doc/content/getting_started/petsc_default.md
  modules/doc/content/sqa/moose_srs.md
Labels: PR: Auto Merge, PR: Failed but allowed

#12681 Documentation update for finite strains and closed loop loading
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/Strains.md
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/closed_loop_large_deform_cycle_loading.png
  modules/tensor_mechanics/doc/content/source/materials/ComputeFiniteStrain.md
Labels: PR: Ready for Review/Merge

#12725 Remove deprecated option from CSVDiff
  python/TestHarness/testers/CSVDiff.py
Labels: PR: Failed but allowed

#12729 BEWARE: next/devel sync problem. Not pthreads in PorousFlow tests
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/tests
  modules/porous_flow/test/tests/heat_advection/tests
Labels: PR: Failed but allowed

#12727 parser,mesh-generators: several small fixes and tweaks
  framework/include/meshgenerators/MeshExtruderGenerator.h
  framework/src/meshgenerators/MeshExtruderGenerator.C
  framework/src/meshgenerators/StackGenerator.C
  framework/src/meshgenerators/StitchedMeshGenerator.C
  framework/src/parser/Parser.C
Labels: PR: Failed but allowed

#12721 Automatic dual/non-dual types
  framework/include/interfaces/Coupleable.h
  framework/include/materials/MaterialData.h
  framework/include/problems/FEProblemBase.h
  framework/include/restart/DataIO.h
  framework/include/utils/ColumnMajorMatrix.h
  framework/include/utils/DualReal.h
  framework/include/utils/MooseADWrapper.h
  framework/include/utils/MooseTypes.h
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankTwoTensor.h
  framework/include/variables/MooseVariableFE.h
  framework/src/kernels/ADKernel.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/ColumnMajorMatrix.C
  framework/src/utils/MooseADWrapper.C
  framework/src/utils/RankFourTensor.C
  framework/src/utils/RankTwoTensor.C
  modules/tensor_mechanics/include/kernels/ADStressDivergenceTensors.h
  modules/tensor_mechanics/include/materials/ADComputeIncrementalSmallStrain.h
  modules/tensor_mechanics/include/materials/ADComputeIncrementalStrainBase.h
  modules/tensor_mechanics/include/materials/ADComputeStrainBase.h
  modules/tensor_mechanics/include/materials/ADComputeStressBase.h
  modules/tensor_mechanics/src/materials/ADComputeFiniteStrainElasticStress.C
  modules/tensor_mechanics/src/materials/ADComputeIncrementalSmallStrain.C
  modules/tensor_mechanics/src/materials/ADComputeIncrementalStrainBase.C
  modules/tensor_mechanics/src/materials/ADComputeSmallStrain.C
Labels: PR: Auto Merge, PR: Failed but allowed

#12726 Add AuxKernel to output volumetric heating from Joule heating
  modules/combined/test/tests/joule_heating_heat/gold/jouleheating_heat_out.e
  modules/combined/test/tests/joule_heating_heat/jouleheating_heat.i
  modules/combined/test/tests/joule_heating_heat/tests
  modules/heat_conduction/doc/content/source/auxkernels/JouleHeatingHeatGeneratedAux.md
  modules/heat_conduction/include/auxkernels/JouleHeatingHeatGeneratedAux.h
  modules/heat_conduction/src/auxkernels/JouleHeatingHeatGeneratedAux.C
Labels: PR: Failed but allowed

#12749 Expand ParsedFunction doc
  framework/doc/content/source/functions/MooseParsedFunction.md
  framework/src/functions/MooseParsedFunctionBase.C
Labels: C: Documentation

#12748 Add radiusSearch to KDTree
  framework/include/utils/KDTree.h
  framework/src/utils/KDTree.C
  unit/src/KDTreeTest.C
Labels: PR: Failed but allowed

#12751 Create FINAL and LATEST symlinks for VPP files
  framework/include/outputs/CSV.h
  framework/include/utils/MooseUtils.h
  framework/src/outputs/CSV.C
  framework/src/utils/MooseUtils.C
  test/tests/outputs/csv_final_and_latest/final.i
  test/tests/outputs/csv_final_and_latest/gold/final_out_line_sample_FINAL.csv
  test/tests/outputs/csv_final_and_latest/gold/latest_out_line_sample_LATEST.csv
  test/tests/outputs/csv_final_and_latest/latest.i
  test/tests/outputs/csv_final_and_latest/tests
Labels: PR: Failed but allowed

#12706 Create ComputeSurfaceTensionKKS material
  modules/combined/test/tests/surface_tension_KKS/gold/surface_tension_KKS_out.e
  modules/combined/test/tests/surface_tension_KKS/surface_tension_KKS.i
  modules/combined/test/tests/surface_tension_KKS/tests
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/source/materials/ComputeSurfaceTensionKKS.md
  modules/tensor_mechanics/include/materials/ComputeSurfaceTensionKKS.h
  modules/tensor_mechanics/src/materials/ComputeSurfaceTensionKKS.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12754 Fixes to VPP latest and final symlinks
  framework/src/outputs/CSV.C
  python/mooseutils/VectorPostprocessorReader.py
  test/tests/outputs/csv_final_and_latest/final.i
  test/tests/outputs/csv_final_and_latest/latest.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12760 Fix parameter validation bug
  framework/src/utils/FunctionParserUtils.C
Labels: PR: Failed but allowed

#12765 Passed CLI args to PETSc configure script
  scripts/update_and_rebuild_petsc.sh
Labels: PR: Auto Merge, PR: Failed but allowed

#12753 MeshGenerator updates
  framework/include/meshgenerators/PatternedMeshGenerator.h
  framework/src/meshgenerators/MeshExtruderGenerator.C
  framework/src/meshgenerators/PatternedMeshGenerator.C
  framework/src/meshgenerators/StackGenerator.C
  test/tests/meshgenerators/patterned_mesh_generator/patterned_mesh_generator.i
Labels: PR: Failed but allowed

#12740 Add the ability to execute transfers on final
  framework/include/utils/MooseUtils.h
  framework/include/utils/MultiMooseEnum.h
  framework/src/executioners/Transient.C
  framework/src/outputs/Exodus.C
  framework/src/utils/MooseUtils.C
  test/tests/postprocessors/execute_on_final/execute_on_final.i
  test/tests/postprocessors/execute_on_final/gold/execute_on_final_on_final.csv
  test/tests/postprocessors/execute_on_final/gold/execute_on_final_out.csv
  test/tests/postprocessors/execute_on_final/tests
  test/tests/transfers/transfer_on_final/gold/master_final.e
  test/tests/transfers/transfer_on_final/gold/master_out.e
  test/tests/transfers/transfer_on_final/gold/master_out_sub0.e
  test/tests/transfers/transfer_on_final/master.i
  test/tests/transfers/transfer_on_final/sub.i
  test/tests/transfers/transfer_on_final/tests
Labels: PR: Failed but allowed

#12710 Fix csvdiff script
  modules/doc/content/python/CSVDiff.md
  modules/doc/content/python/TestHarness.md
  modules/doc/content/python/index.md
  python/TestHarness/testers/CSVDiff.py
  python/TestHarness/tests/test_CSVDiffer.py
  python/TestHarness/tests/test_CSVDiffs.py
  scripts/csvdiff.py
  test/tests/test_harness/csvdiff_comparison.i
  test/tests/test_harness/csvdiff_comparison_floor.cmp
  test/tests/test_harness/csvdiff_comparison_floor.i
  test/tests/test_harness/csvdiff_comparison_global_floor.cmp
  test/tests/test_harness/csvdiff_comparison_global_floor.i
  test/tests/test_harness/csvdiff_comparison_global_relative.cmp
  test/tests/test_harness/csvdiff_comparison_global_relative.i
  test/tests/test_harness/csvdiff_comparison_not_logic.cmp
  test/tests/test_harness/csvdiff_comparison_not_logic.i
  test/tests/test_harness/csvdiff_comparison_relative.cmp
  test/tests/test_harness/csvdiff_comparison_relative.i
  test/tests/test_harness/csvdiff_comparison_removed_field.cmp
  test/tests/test_harness/csvdiff_comparison_removed_field.i
  test/tests/test_harness/csvdiff_missing_comparison_file
  test/tests/test_harness/csvdiff_missing_field_comparison.i
  test/tests/test_harness/csvdiff_spec_override_global_floor.i
  test/tests/test_harness/csvdiff_spec_override_global_relative.i
  test/tests/test_harness/csvdiff_spec_override_specific_floor.i
  test/tests/test_harness/csvdiff_spec_override_specific_relative.i
  test/tests/test_harness/csvdiff_tests
  test/tests/test_harness/gold/csvdiff_comparison_floor_out.csv
  test/tests/test_harness/gold/csvdiff_comparison_global_floor_out.csv
  test/tests/test_harness/gold/csvdiff_comparison_global_relative_out.csv
  test/tests/test_harness/gold/csvdiff_comparison_not_logic_out.csv
  test/tests/test_harness/gold/csvdiff_comparison_out.csv
  test/tests/test_harness/gold/csvdiff_comparison_relative_out.csv
  test/tests/test_harness/gold/csvdiff_comparison_removed_field_out.csv
  test/tests/test_harness/gold/csvdiff_spec_override_global_floor_out.csv
  test/tests/test_harness/gold/csvdiff_spec_override_global_relative_out.csv
  test/tests/test_harness/gold/csvdiff_spec_override_specific_floor_out.csv
  test/tests/test_harness/gold/csvdiff_spec_override_specific_relative_out.csv
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#12756 Multiapp start time
  framework/include/multiapps/FullSolveMultiApp.h
  framework/include/multiapps/MultiApp.h
  framework/include/multiapps/TransientMultiApp.h
  framework/src/multiapps/MultiApp.C
  framework/src/multiapps/TransientMultiApp.C
  framework/src/problems/FEProblemBase.C
  modules/level_set/include/multiapps/LevelSetReinitializationMultiApp.h
  test/tests/multiapps/check_error/tests
  test/tests/multiapps/move_and_reset/gold/multilevel_master_out_sub0_sub0.e-s002
  test/tests/multiapps/reset/gold/multilevel_master_out_sub0_sub0.e-s002
  test/tests/multiapps/time_offset/gold/master_out_sub_app0.e
  test/tests/multiapps/time_offset/master.i
  test/tests/multiapps/time_offset/sub.i
  test/tests/multiapps/time_offset/tests
Labels: PR: Ready for Review/Merge

#12784 fix peacock for vtk8
  python/chigger/RenderWindow.py
  python/chigger/vtk_scripts/cylinder_color.py
  python/chigger/vtk_scripts/plane_rotate_extrude.py
  python/peacock/peacock
Labels: PR: Ready for Review/Merge

#12798 Adjusting test so that it passes robustly in parallel
  test/tests/transfers/multiapp_interpolation_transfer/fromrestrictedsub_master.i
  test/tests/transfers/multiapp_interpolation_transfer/gold/fromrestrictedsub_master_out.e
Labels: PR: Ready for Review/Merge
