Repository idaholab/moose, pull requests merged in 2019-03, with the labels that each got.

#12986 PorousFlow DiracKernels mention strain_at_nearest_qp
  modules/porous_flow/doc/content/modules/porous_flow/sinks.md
  modules/porous_flow/src/dirackernels/PorousFlowPeacemanBorehole.C
  modules/porous_flow/src/dirackernels/PorousFlowPolyLineSink.C
  modules/porous_flow/test/tests/dirackernels/strain_at_nearest_qp.bh
  modules/porous_flow/test/tests/dirackernels/strain_at_nearest_qp.i
  modules/porous_flow/test/tests/dirackernels/tests
Labels: PR: Failed but allowed

#12807 Gcc 8 fixes
  framework/contrib/tinydir/include/tinydir.h
  framework/src/postprocessors/FindValueOnLine.C
  framework/src/systems/NonlinearSystem.C
  framework/src/vectorpostprocessors/SphericalAverage.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12949 Less Leaky MooseArray Experiment
  framework/include/utils/MooseArray.h
  framework/src/outputs/Exodus.C
  framework/src/outputs/Nemesis.C
  framework/src/outputs/TableOutput.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12993 Update tutorial's examples to use registerAll
  tutorials/darcy_thermo_mech/step01_diffusion/include/base/DarcyThermoMechApp.h
  tutorials/darcy_thermo_mech/step01_diffusion/src/base/DarcyThermoMechApp.C
Labels: PR: Auto Merge

#12957 Create a simple solve object to wrap FEProblem solve
  framework/include/executioners/Executioner.h
  framework/include/executioners/FEProblemSolve.h
  framework/include/executioners/PicardSolve.h
  framework/include/executioners/SolveObject.h
  framework/src/executioners/Executioner.C
  framework/src/executioners/FEProblemSolve.C
  framework/src/executioners/PicardSolve.C
  framework/src/executioners/SolveObject.C
  framework/src/executioners/Steady.C
  framework/src/executioners/Transient.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13001 Add porosity and permeability to PorousFlowPropertyAux
  modules/porous_flow/doc/content/source/auxkernels/PorousFlowPropertyAux.md
  modules/porous_flow/examples/coal_mining/coarse_with_fluid.i
  modules/porous_flow/examples/coal_mining/fine_with_fluid.i
  modules/porous_flow/examples/tutorial/07.i
  modules/porous_flow/examples/tutorial/11.i
  modules/porous_flow/examples/tutorial/11_2D.i
  modules/porous_flow/include/auxkernels/PorousFlowPropertyAux.h
  modules/porous_flow/src/auxkernels/PorousFlowPropertyAux.C
  modules/porous_flow/src/utils/PorousFlowDependencies.C
  modules/porous_flow/test/tests/chemistry/except19.i
  modules/porous_flow/test/tests/chemistry/except20.i
  modules/porous_flow/test/tests/chemistry/except22.i
  modules/porous_flow/test/tests/chemistry/precipitation_porosity_change.i
  modules/porous_flow/test/tests/energy_conservation/heat04.i
  modules/porous_flow/test/tests/energy_conservation/heat04_action.i
  modules/porous_flow/test/tests/energy_conservation/heat04_action_KT.i
  modules/porous_flow/test/tests/energy_conservation/heat04_fullysat_action.i
  modules/porous_flow/test/tests/heterogeneous_materials/constant_poroperm.i
  modules/porous_flow/test/tests/heterogeneous_materials/constant_poroperm2.i
  modules/porous_flow/test/tests/heterogeneous_materials/vol_expansion_poroperm.i
  modules/porous_flow/test/tests/poro_elasticity/pp_generation.i
  modules/porous_flow/test/tests/poro_elasticity/pp_generation_action.i
  modules/porous_flow/test/tests/poro_elasticity/pp_generation_fullysat_action.i
  modules/porous_flow/test/tests/poro_elasticity/vol_expansion_poroperm.i
  modules/porous_flow/test/tests/poroperm/PermFromPoro01.i
  modules/porous_flow/test/tests/poroperm/PermFromPoro02.i
  modules/porous_flow/test/tests/poroperm/PermFromPoro03.i
  modules/porous_flow/test/tests/poroperm/PermFromPoro04.i
  modules/porous_flow/test/tests/poroperm/PermFromPoro05.i
  modules/porous_flow/test/tests/poroperm/PermTensorFromVar01.i
  modules/porous_flow/test/tests/poroperm/PermTensorFromVar02.i
  modules/porous_flow/test/tests/poroperm/PermTensorFromVar03.i
  modules/porous_flow/test/tests/poroperm/except1.i
  modules/porous_flow/test/tests/poroperm/except2.i
  modules/porous_flow/test/tests/poroperm/poro_hm.i
  modules/porous_flow/test/tests/poroperm/poro_thm.i
  modules/porous_flow/test/tests/poroperm/poro_tm.i
Labels: PR: Failed but allowed

#12999 Better formatting in ReferenceResidualProblem
  framework/src/outputs/Console.C
  modules/contact/src/ReferenceResidualProblem.C
Labels: PR: Failed but allowed

#13005 Small interface improvement in ActionWarehouse::getActionListByName
  framework/include/actions/ActionWarehouse.h
  framework/src/actions/ActionWarehouse.C
  framework/src/actions/CheckOutputAction.C
Labels: PR: Auto Merge, PR: Failed but allowed

#12997 MOOSEDocs Fixes
  python/MooseDocs/extensions/media.py
  python/MooseDocs/extensions/package.py
  python/MooseDocs/test/gold/html/extensions/config.html
  python/MooseDocs/test/gold/html/extensions/media.html
  python/MooseDocs/test/gold/json/extensions/config.json
  python/MooseDocs/test/gold/json/extensions/media.json
  python/MooseDocs/test/gold/latex/extensions/config.tex
  python/MooseDocs/test/gold/latex/extensions/media.tex
  python/MooseDocs/test/gold/materialize/extensions/config.html
  python/MooseDocs/test/gold/materialize/extensions/media.html
Labels: PR: Failed but allowed

#13019 Add vector time derivative
  framework/doc/content/source/kernels/ADVectorTimeDerivative.md
  framework/include/kernels/ADVectorTimeDerivative.h
  framework/src/kernels/ADVectorTimeDerivative.C
  test/tests/kernels/ad_transient_diffusion/ad_transient_vector_diffusion.i
  test/tests/kernels/ad_transient_diffusion/gold/ad_transient_vector_diffusion_out.e
  test/tests/kernels/ad_transient_diffusion/tests
Labels: PR: Failed but allowed

#13024 Adding API for getting info about phase change
  modules/fluid_properties/include/userobjects/TwoPhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/TwoPhaseFluidPropertiesIndependent.h
Labels: PR: Failed but allowed

#13013 Make PorousFlow2PhasePS consistent with PorousFlow2PhasePP
  modules/porous_flow/include/materials/PorousFlow2PhasePS.h
  modules/porous_flow/src/materials/PorousFlow2PhasePS.C
  modules/porous_flow/src/userobjects/PorousFlowCapillaryPressure.C
  modules/porous_flow/test/tests/aux_kernels/gold/properties_out.e
  modules/porous_flow/test/tests/capillary_pressure/gold/brooks_corey1_out_vpp_0001.csv
  modules/porous_flow/test/tests/capillary_pressure/gold/brooks_corey2_out_vpp_0001.csv
  modules/porous_flow/test/tests/capillary_pressure/gold/vangenuchten1_out_vpp_0001.csv
  modules/porous_flow/test/tests/capillary_pressure/gold/vangenuchten2_out_vpp_0001.csv
  modules/porous_flow/test/tests/capillary_pressure/gold/vangenuchten3_out_vpp_0001.csv
  modules/porous_flow/test/tests/dirackernels/gold/theis3.csv
  modules/porous_flow/test/tests/gravity/gold/grav02e.e
  modules/porous_flow/test/tests/gravity/gold/grav02f.e
  modules/porous_flow/test/tests/gravity/gold/grav02g.e
  modules/porous_flow/test/tests/pressure_pulse/gold/pressure_pulse_1d_2phasePSVG2_pp_0011.csv
  modules/porous_flow/test/tests/pressure_pulse/gold/pressure_pulse_1d_2phasePSVG_pp_0011.csv
  modules/porous_flow/test/tests/pressure_pulse/gold/pressure_pulse_1d_2phasePS_KT_pp_0011.csv
  modules/porous_flow/test/tests/pressure_pulse/gold/pressure_pulse_1d_2phasePS_pp_0011.csv
Labels: PR: Failed but allowed

#13031 Added fluid properties interrogator
  modules/fluid_properties/doc/content/modules/fluid_properties/index.md
  modules/fluid_properties/doc/content/source/actions/AddFluidPropertiesInterrogatorAction.md
  modules/fluid_properties/doc/content/source/userobjects/FluidPropertiesInterrogator.md
  modules/fluid_properties/doc/content/syntax/FluidPropertiesInterrogator/index.md
  modules/fluid_properties/fp_interrogator/fp_interrogator.i
  modules/fluid_properties/include/actions/AddFluidPropertiesInterrogatorAction.h
  modules/fluid_properties/include/userobjects/FluidPropertiesInterrogator.h
  modules/fluid_properties/include/userobjects/TwoPhaseNCGFluidProperties.h
  modules/fluid_properties/src/actions/AddFluidPropertiesInterrogatorAction.C
  modules/fluid_properties/src/base/FluidPropertiesApp.C
  modules/fluid_properties/src/userobjects/FluidPropertiesInterrogator.C
  modules/fluid_properties/test/include/userobjects/TestTwoPhaseFluidProperties.h
  modules/fluid_properties/test/include/userobjects/TestTwoPhaseNCGFluidProperties.h
  modules/fluid_properties/test/src/userobjects/TestTwoPhaseFluidProperties.C
  modules/fluid_properties/test/src/userobjects/TestTwoPhaseNCGFluidProperties.C
  modules/fluid_properties/test/tests/fp_interrogator/1ph.p_T.i
  modules/fluid_properties/test/tests/fp_interrogator/1ph.rho_e.i
  modules/fluid_properties/test/tests/fp_interrogator/1ph.rho_p.i
  modules/fluid_properties/test/tests/fp_interrogator/1ph.rho_rhou_rhoE.i
  modules/fluid_properties/test/tests/fp_interrogator/2ph.T.i
  modules/fluid_properties/test/tests/fp_interrogator/2ph.p.i
  modules/fluid_properties/test/tests/fp_interrogator/2ph.p_T.i
  modules/fluid_properties/test/tests/fp_interrogator/2ph_ncg_p_T.i
  modules/fluid_properties/test/tests/fp_interrogator/err.no_params.i
  modules/fluid_properties/test/tests/fp_interrogator/err.wrong_fp_type.i
  modules/fluid_properties/test/tests/fp_interrogator/tests
  modules/fluid_properties/test/tests/fp_interrogator/vapor_mixture_rho_e.i
Labels: PR: Failed but allowed

#13037 Disabled pthreads for fluid properties interrogator tests
  modules/fluid_properties/test/tests/fp_interrogator/tests
Labels: PR: Failed but allowed

#13032 Add turn_off_exodus_output option to the PetscJacobianTester
  modules/heat_conduction/test/tests/recover/tests
  modules/heat_conduction/test/tests/verify_against_analytical/tests
  modules/misc/test/tests/kernels/diffusion/tests
  python/TestHarness/testers/PetscJacobianTester.py
  test/tests/kernels/diffusion_with_hanging_node/tests
  test/tests/materials/ad_material/tests
Labels: PR: Failed but allowed

#13038 Don't compare small error for ad_heat_source_bar test
  modules/heat_conduction/test/tests/heat_source_bar/ad_heat_source_bar.cmp
  modules/heat_conduction/test/tests/heat_source_bar/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#13026 Template RankThreeTensor for AD
  framework/include/restart/DataIO.h
  framework/include/utils/MooseADWrapper.h
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankThreeTensor.h
  framework/include/utils/RankTwoTensor.h
  framework/src/restart/DataIO.C
  framework/src/utils/MooseADWrapper.C
  framework/src/utils/RankThreeTensor.C
  modules/phase_field/include/kernels/ACInterfaceStress.h
  modules/phase_field/src/kernels/ACInterfaceStress.C
  unit/src/RankThreeTensorTest.C
Labels: PR: Failed but allowed

#13045 Attempt to reinstante 2 tests
  modules/porous_flow/test/tests/jacobian/tests
Labels: PR: Failed but allowed

#12914 Add Feature Request Template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: PR: Failed but allowed

#12913 Add Bug Report Template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: PR: Failed but allowed

#13057 Create a generalized stabilization ADKernel
  framework/include/kernels/ADKernelSUPG.h
  framework/include/kernels/ADKernelStabilized.h
  framework/src/kernels/ADKernelSUPG.C
  framework/src/kernels/ADKernelStabilized.C
Labels: PR: Failed but allowed

#13052 Include header_symlinks
  framework/scripts/build_coverage.py
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13055 Allow users to turn off header symlinking
  framework/app.mk
  framework/moose.mk
  modules/doc/content/application_development/build_system.md
Labels: PR: Failed but allowed

#13039 Remove a few deprecated tasks
  framework/src/base/Moose.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13068 Final removal of old thermal contact actions
  modules/heat_conduction/doc/content/source/actions/ThermalContactAuxVarsAction.md
  modules/heat_conduction/include/actions/ThermalContactAuxVarsAction.h
  modules/heat_conduction/src/actions/ThermalContactAuxVarsAction.C
Labels: PR: Failed but allowed

#12943 PorousFlow Kuzmin-Turek vector instead of map
  modules/porous_flow/include/userobjects/AdvectiveFluxCalculatorBase.h
  modules/porous_flow/include/userobjects/AdvectiveFluxCalculatorConstantVelocity.h
  modules/porous_flow/include/userobjects/PorousFlowAdvectiveFluxCalculatorBase.h
  modules/porous_flow/include/utils/PorousFlowConnectedNodes.h
  modules/porous_flow/src/kernels/FluxLimitedTVDAdvection.C
  modules/porous_flow/src/kernels/PorousFlowFluxLimitedTVDAdvection.C
  modules/porous_flow/src/userobjects/AdvectiveFluxCalculatorBase.C
  modules/porous_flow/src/userobjects/AdvectiveFluxCalculatorConstantVelocity.C
  modules/porous_flow/src/userobjects/PorousFlowAdvectiveFluxCalculatorBase.C
  modules/porous_flow/src/utils/PorousFlowConnectedNodes.C
  unit/include/PorousFlowConnectedNodesTest.h
  unit/src/PorousFlowConnectedNodesTest.C
Labels: PR: Failed but allowed

#13072 Example of restart in PorousFlow
  modules/porous_flow/doc/content/media/porous_flow/gas_injection.png
  modules/porous_flow/doc/content/media/porous_flow/gas_injection_refined.png
  modules/porous_flow/doc/content/media/porous_flow/hydrostatic_pressure.png
  modules/porous_flow/doc/content/modules/porous_flow/index.md
  modules/porous_flow/doc/content/modules/porous_flow/restart.md
  modules/porous_flow/examples/restart/gas_injection.i
  modules/porous_flow/examples/restart/gas_injection_new_mesh.i
  modules/porous_flow/examples/restart/gold/gravityeq_out.e
  modules/porous_flow/examples/restart/gravityeq.i
  modules/porous_flow/examples/restart/tests
Labels: PR: Failed but allowed

#13075 Output Correct Grain Indices for Multi-phase or Porous EBSD Datasets
  modules/phase_field/include/auxkernels/EBSDReaderAvgDataAux.h
  modules/phase_field/include/auxkernels/EulerAngleProvider2RGBAux.h
  modules/phase_field/include/userobjects/EBSDReader.h
  modules/phase_field/src/action/EulerAngle2RGBAction.C
  modules/phase_field/src/auxkernels/EBSDReaderAvgDataAux.C
  modules/phase_field/src/auxkernels/EulerAngleProvider2RGBAux.C
  modules/phase_field/src/userobjects/PolycrystalEBSD.C
  modules/phase_field/test/tests/reconstruction/euler2rgb_no_grain_region.i
Labels: PR: Failed but allowed

#13062 March newsletter
  modules/doc/content/newsletter/2019_03.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#13082 Add missing issue number in porous flow example
  modules/porous_flow/examples/restart/tests
Labels: PR: Failed but allowed

#13085 allow submodule tests to run with run_tests
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed

#13086 explicitly invoke python2 in stork run_tests files
  stork/run_tests.app
  stork/run_tests.module
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13083 Make libmesh build scripts more flexible
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed

#13074 Fix compile error in GCC 8.x series
  framework/include/utils/MooseTypes.h
  framework/src/vectorpostprocessors/SpatialAverageBase.C
  modules/doc/content/framework_development/code_standards.md
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
Labels: PR: Ready for Review/Merge

#13107 PorousFlowConnectedNodes sizeSequential method added
  modules/porous_flow/include/utils/PorousFlowConnectedNodes.h
  modules/porous_flow/src/utils/PorousFlowConnectedNodes.C
  unit/src/PorousFlowConnectedNodesTest.C
Labels: PR: Failed but allowed

#13111 Fix ADHeatConductionTimeDerivative to take AD material properties
  modules/heat_conduction/include/kernels/ADHeatConductionTimeDerivative.h
Labels: PR: Auto Merge, PR: Failed but allowed

#13112 Support setting Scalar IC from file
  framework/src/systems/SystemBase.C
  test/tests/kernels/ode/coupled_ode_td_auxvar_ic_from_mesh.i
  test/tests/kernels/ode/coupled_ode_td_var_ic_from_mesh.i
  test/tests/kernels/ode/gold/coupled_ode_td_auxvar_ic_from_mesh_out.csv
  test/tests/kernels/ode/gold/coupled_ode_td_var_ic_from_mesh_out.csv
  test/tests/kernels/ode/tests
Labels: PR: Ready for Review/Merge

#13117 Fix PorousFlowAddMaterialAction and PorousFlowAddMaterialJoiner
  modules/porous_flow/include/actions/PorousFlowAddMaterialJoiner.h
  modules/porous_flow/src/actions/PorousFlowAddMaterialAction.C
  modules/porous_flow/src/actions/PorousFlowAddMaterialJoiner.C
  modules/porous_flow/test/tests/actions/block_restricted_materials.i
  modules/porous_flow/test/tests/actions/gold/block_restricted_materials_out.e
  modules/porous_flow/test/tests/actions/tests
  modules/porous_flow/test/tests/gravity/gold/grav01d.csv
  modules/porous_flow/test/tests/gravity/grav01d.i
  modules/porous_flow/test/tests/gravity/tests
Labels: PR: Failed but allowed

#13126 Enumerate syntactic sugar!
  framework/include/utils/Enumerate.h
  framework/include/utils/JvarMapInterface.h
  unit/src/EnumerateTest.C
Labels: PR: Auto Merge

#13135 Made value param required in Gravity and ADGravity
  modules/tensor_mechanics/src/kernels/ADGravity.C
  modules/tensor_mechanics/src/kernels/Gravity.C
Labels: PR: Ready for Review/Merge

#13133 Fix another GCC 8_x issue
  modules/porous_flow/src/kernels/PorousFlowDarcyBase.C
Labels: PR: Ready for Review/Merge

#13136 Fix problem with partial app syntax lists
  modules/chemical_reactions/doc/content/modules/chemical_reactions/index.md
  modules/contact/doc/content/modules/contact/index.md
  modules/functional_expansion_tools/doc/content/modules/functional_expansion_tools/index.md
  modules/heat_conduction/doc/content/modules/heat_conduction/index.md
  modules/level_set/doc/content/modules/level_set/index.md
  modules/misc/doc/content/modules/misc/index.md
  modules/navier_stokes/doc/content/modules/navier_stokes/index.md
  modules/phase_field/doc/content/modules/phase_field/systems.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/index.md
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/systems.md
  modules/xfem/doc/content/modules/xfem/index.md
  python/MooseDocs/extensions/appsyntax.py
Labels: PR: Ready for Review/Merge

#12918 Add ComputeExtraStressVDWGas material
  modules/combined/test/tests/surface_tension_KKS/gold/surface_tension_VDWgas_out.e
  modules/combined/test/tests/surface_tension_KKS/surface_tension_VDWgas.i
  modules/combined/test/tests/surface_tension_KKS/tests
  modules/tensor_mechanics/doc/content/source/materials/ComputeExtraStressVDWGas.md
  modules/tensor_mechanics/include/materials/ComputeExtraStressVDWGas.h
  modules/tensor_mechanics/src/materials/ComputeExtraStressVDWGas.C
Labels: PR: Failed but allowed

#13119 Add smoothing to ConcentricCircleMeshGenerator
  framework/doc/content/source/meshgenerators/ConcentricCircleMeshGenerator.md
  framework/include/meshgenerators/ConcentricCircleMeshGenerator.h
  framework/src/meshgenerators/ConcentricCircleMeshGenerator.C
  test/tests/meshgenerators/concentric_circle_mesh_generator/concentric_circle_mesh2.i
  test/tests/meshgenerators/concentric_circle_mesh_generator/concentric_circle_mesh_generator.i
  test/tests/meshgenerators/concentric_circle_mesh_generator/gold/concentric_circle_mesh2_out.e
  test/tests/meshgenerators/concentric_circle_mesh_generator/gold/concentric_circle_mesh_generator_in.e
Labels: PR: Ready for Review/Merge

#13132 PorousFlow uses saturation not effective saturation
  modules/porous_flow/doc/content/modules/porous_flow/capillary_pressure.md
  modules/porous_flow/doc/content/source/materials/PorousFlow1PhaseP.md
  modules/porous_flow/doc/content/source/materials/PorousFlow2PhasePP.md
  modules/porous_flow/include/userobjects/PorousFlowCapillaryPressure.h
  modules/porous_flow/src/materials/PorousFlow1PhaseP.C
  modules/porous_flow/src/materials/PorousFlow2PhasePP.C
  modules/porous_flow/src/userobjects/PorousFlowCapillaryPressure.C
  modules/porous_flow/test/tests/actions/addmaterials.i
  modules/porous_flow/test/tests/actions/addmaterials2.i
  modules/porous_flow/test/tests/jacobian/basic_advection2.i
  modules/porous_flow/test/tests/jacobian/basic_advection3.i
  modules/porous_flow/test/tests/jacobian/basic_advection4.i
  modules/porous_flow/test/tests/jacobian/basic_advection6.i
  modules/porous_flow/test/tests/jacobian/eff_stress02.i
  modules/porous_flow/test/tests/jacobian/eff_stress04.i
  modules/porous_flow/test/tests/jacobian/fflux07.i
Labels: PR: Ready for Review/Merge

#13143 Remove beginIndex() usage
  framework/include/actions/ActionWarehouse.h
  framework/include/userobject/NearestPointBase.h
  framework/include/utils/MooseTypes.h
  framework/src/base/Assembly.C
  framework/src/controls/TimePeriod.C
  framework/src/interfaces/TaggingInterface.C
  framework/src/kernels/NodalScalarKernel.C
  framework/src/materials/DerivativeParsedMaterialHelper.C
  framework/src/materials/ParsedMaterialHelper.C
  framework/src/mesh/PatternedMesh.C
  framework/src/mesh/StitchedMesh.C
  framework/src/meshgenerators/BreakBoundaryOnSubdomainGenerator.C
  framework/src/meshgenerators/LowerDBlockFromSidesetGenerator.C
  framework/src/meshgenerators/PatternedMeshGenerator.C
  framework/src/meshgenerators/StackGenerator.C
  framework/src/meshgenerators/StitchedMeshGenerator.C
  framework/src/meshmodifiers/BreakBoundaryOnSubdomain.C
  framework/src/meshmodifiers/LowerDBlockFromSideset.C
  framework/src/restart/DataIO.C
  framework/src/samplers/Sampler.C
  framework/src/transfers/MultiAppScalarToAuxScalarTransfer.C
  framework/src/utils/BicubicInterpolation.C
  framework/src/utils/FormattedTable.C
  framework/src/vectorpostprocessors/LeastSquaresFit.C
  framework/src/vectorpostprocessors/LeastSquaresFitHistory.C
  framework/src/vectorpostprocessors/PointSamplerBase.C
  framework/src/vectorpostprocessors/SamplerBase.C
  modules/chemical_reactions/src/actions/AddPrimarySpeciesAction.C
  modules/chemical_reactions/src/actions/AddSecondarySpeciesAction.C
  modules/chemical_reactions/src/kernels/CoupledBEKinetic.C
  modules/phase_field/src/kernels/MultiGrainRigidBodyMotion.C
  modules/phase_field/src/materials/DeformedGrainMaterial.C
  modules/phase_field/src/postprocessors/AverageGrainVolume.C
  modules/phase_field/src/postprocessors/FauxGrainTracker.C
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
  modules/phase_field/src/userobjects/PolycrystalVoronoi.C
  modules/phase_field/src/vectorpostprocessors/FeatureVolumeVectorPostprocessor.C
  modules/stochastic_tools/src/samplers/MonteCarloSampler.C
  modules/stochastic_tools/src/samplers/SobolSampler.C
  modules/stochastic_tools/src/transfers/SamplerTransfer.C
  modules/stochastic_tools/src/vectorpostprocessors/SamplerData.C
  modules/stochastic_tools/src/vectorpostprocessors/StochasticResults.C
  modules/tensor_mechanics/src/auxkernels/AccumulateAux.C
  modules/tensor_mechanics/src/materials/ComputeInterfaceStress.C
  modules/xfem/src/userobjects/PointValueAtXFEMInterface.C
  test/src/actions/TestGetActionsAction.C
  test/src/vectorpostprocessors/ChannelGradientVectorPostprocessor.C
Labels: PR: Ready for Review/Merge

#13153 Remove no longer needed ADCoupledTimeTest
  test/include/kernels/ADCoupledTimeTest.h
  test/src/kernels/ADCoupledTimeTest.C
  test/tests/kernels/ad_coupled_value/ad_aux_coupled_time_value.i
Labels: PR: Auto Merge

#12902 Boundary restrictable InterfaceUserObject (and postprocessor) family
  framework/doc/content/source/auxkernels/InterfaceValueUserObjectAux.md
  framework/doc/content/source/postprocessors/InterfaceAverageVariableValuePostprocessor.md
  framework/doc/content/source/postprocessors/InterfaceIntegralVariableValuePostprocessor.md
  framework/doc/content/source/userobject/InterfaceQpValueUserObject.md
  framework/doc/content/source/utils/InterfaceValueTools.md
  framework/include/auxkernels/InterfaceValueUserObjectAux.h
  framework/include/base/Attributes.h
  framework/include/loops/ComputeUserObjectsThread.h
  framework/include/postprocessors/InterfaceAverageVariableValuePostprocessor.h
  framework/include/postprocessors/InterfaceIntegralPostprocessor.h
  framework/include/postprocessors/InterfaceIntegralVariableValuePostprocessor.h
  framework/include/postprocessors/InterfacePostprocessor.h
  framework/include/problems/FEProblemBase.h
  framework/include/userobject/InterfaceQpValueUserObject.h
  framework/include/userobject/InterfaceUserObject.h
  framework/include/userobject/InterfaceValueUserObject.h
  framework/include/utils/InterfaceValueTools.h
  framework/src/auxkernels/InterfaceValueUserObjectAux.C
  framework/src/base/Attributes.C
  framework/src/loops/ComputeUserObjectsThread.C
  framework/src/postprocessors/InterfaceAverageVariableValuePostprocessor.C
  framework/src/postprocessors/InterfaceIntegralPostprocessor.C
  framework/src/postprocessors/InterfaceIntegralVariableValuePostprocessor.C
  framework/src/postprocessors/InterfacePostprocessor.C
  framework/src/problems/FEProblemBase.C
  framework/src/userobject/InterfaceQpValueUserObject.C
  framework/src/userobject/InterfaceUserObject.C
  framework/src/userobject/InterfaceValueUserObject.C
  framework/src/utils/InterfaceValueTools.C
  test/tests/postprocessors/interface_value/gold/interface_average_variable_value_postprocessor_out.e
  test/tests/postprocessors/interface_value/gold/interface_integral_variable_value_postprocessor_out.e
  test/tests/postprocessors/interface_value/interface_average_variable_value_postprocessor.i
  test/tests/postprocessors/interface_value/interface_integral_variable_value_postprocessor.i
  test/tests/postprocessors/interface_value/tests
  test/tests/userobjects/interface_user_object/gold/interface_value_user_object_QP_out.e
  test/tests/userobjects/interface_user_object/interface_value_user_object_QP.i
  test/tests/userobjects/interface_user_object/tests
Labels: PR: Auto Merge
