Repository idaholab/moose, pull requests merged in 2019-10, with the labels that each got.

#14094 Adds ability to use Google CSE
  framework/doc/content/css/moose.css
  modules/doc/config.yml
  python/MooseDocs/base/renderers.py
  python/MooseDocs/commands/build.py
  python/MooseDocs/extensions/navigation.py
  python/MooseDocs/test/gold/materialize/extensions/alert.html
  python/MooseDocs/test/gold/materialize/extensions/amendments.html
  python/MooseDocs/test/gold/materialize/extensions/appsyntax.html
  python/MooseDocs/test/gold/materialize/extensions/bibtex.html
  python/MooseDocs/test/gold/materialize/extensions/common.html
  python/MooseDocs/test/gold/materialize/extensions/config.html
  python/MooseDocs/test/gold/materialize/extensions/core.html
  python/MooseDocs/test/gold/materialize/extensions/devel.html
  python/MooseDocs/test/gold/materialize/extensions/example.template.html
  python/MooseDocs/test/gold/materialize/extensions/first.html
  python/MooseDocs/test/gold/materialize/extensions/folder/folder.html
  python/MooseDocs/test/gold/materialize/extensions/folder/index.html
  python/MooseDocs/test/gold/materialize/extensions/gallery.html
  python/MooseDocs/test/gold/materialize/extensions/graph.html
  python/MooseDocs/test/gold/materialize/extensions/include.html
  python/MooseDocs/test/gold/materialize/extensions/katex.html
  python/MooseDocs/test/gold/materialize/extensions/katex_include.html
  python/MooseDocs/test/gold/materialize/extensions/layout.html
  python/MooseDocs/test/gold/materialize/extensions/listing.html
  python/MooseDocs/test/gold/materialize/extensions/listing_include.html
  python/MooseDocs/test/gold/materialize/extensions/materialicon.html
  python/MooseDocs/test/gold/materialize/extensions/media.html
  python/MooseDocs/test/gold/materialize/extensions/navigation.html
  python/MooseDocs/test/gold/materialize/extensions/package.html
  python/MooseDocs/test/gold/materialize/extensions/preamble.html
  python/MooseDocs/test/gold/materialize/extensions/second.html
  python/MooseDocs/test/gold/materialize/extensions/style.html
  python/MooseDocs/test/gold/materialize/extensions/table.html
  python/MooseDocs/test/gold/materialize/extensions/template.html
  python/MooseDocs/test/gold/materialize/index.html
  python/MooseDocs/test/gold/materialize/mega.menu.html
Labels: PR: Ready for Review/Merge

#13982 KKS system cleanup
  modules/combined/examples/phase_field-mechanics/kks_mechanics_KHS.i
  modules/combined/examples/phase_field-mechanics/kks_mechanics_VTS.i
  modules/combined/test/tests/surface_tension_KKS/surface_tension_KKS.i
  modules/combined/test/tests/surface_tension_KKS/surface_tension_VDWgas.i
  modules/phase_field/examples/kim-kim-suzuki/kks_example_dirichlet.i
  modules/phase_field/examples/kim-kim-suzuki/kks_example_noflux.i
  modules/phase_field/examples/kim-kim-suzuki/kks_example_ternary.i
  modules/phase_field/include/kernels/KKSACBulkBase.h
  modules/phase_field/include/kernels/KKSACBulkC.h
  modules/phase_field/include/kernels/KKSACBulkF.h
  modules/phase_field/include/kernels/KKSMultiPhaseConcentration.h
  modules/phase_field/include/kernels/KKSPhaseChemicalPotential.h
  modules/phase_field/include/kernels/KKSSplitCHCRes.h
  modules/phase_field/include/kernels/SwitchingFunctionConstraintEta.h
  modules/phase_field/include/kernels/SwitchingFunctionConstraintLagrange.h
  modules/phase_field/src/kernels/KKSACBulkBase.C
  modules/phase_field/src/kernels/KKSACBulkC.C
  modules/phase_field/src/kernels/KKSACBulkF.C
  modules/phase_field/src/kernels/KKSMultiPhaseConcentration.C
  modules/phase_field/src/kernels/KKSPhaseChemicalPotential.C
  modules/phase_field/src/kernels/KKSSplitCHCRes.C
  modules/phase_field/src/kernels/SwitchingFunctionConstraintEta.C
  modules/phase_field/src/kernels/SwitchingFunctionConstraintLagrange.C
  modules/phase_field/src/materials/SwitchingFunction3PhaseMaterial.C
  modules/phase_field/test/tests/KKS_system/kks_example.i
  modules/phase_field/test/tests/KKS_system/kks_example_offset.i
  modules/phase_field/test/tests/KKS_system/kks_example_split.i
Labels: PR: Ready for Review/Merge

#14060 Mesh Generator Directed Acyclic Graph Cleanup
  framework/doc/content/syntax/Mesh/index.md
  framework/include/base/MooseApp.h
  framework/include/utils/DependencyResolver.h
  framework/src/actions/SetupMeshAction.C
  framework/src/base/MooseApp.C
  framework/src/base/MooseObject.C
  framework/src/mesh/MeshGeneratorMesh.C
  modules/porous_flow/examples/tidal/atm_tides_open_hole.i
  test/tests/meshgenerators/final_generator/final_ambigious.i
  test/tests/meshgenerators/final_generator/final_linear.i
  test/tests/meshgenerators/final_generator/final_multi_trees.i
  test/tests/meshgenerators/final_generator/gold/final_first_in.e
  test/tests/meshgenerators/final_generator/gold/final_generator_in.e
  test/tests/meshgenerators/final_generator/gold/final_linear_in.e
  test/tests/meshgenerators/final_generator/gold/final_second_in.e
  test/tests/meshgenerators/final_generator/tests
  unit/src/DependencyResolverTest.C
Labels: PR: Ready for Review/Merge

#13920 Implement radiative exchange between gray surfaces using view factors
  modules/heat_conduction/doc/content/bib/heat_conduction.bib
  modules/heat_conduction/doc/content/modules/heat_conduction/index.md
  modules/heat_conduction/doc/content/source/bcs/GrayLambertNeumannBC.md
  modules/heat_conduction/doc/content/source/postprocessors/GrayLambertSurfaceRadiationPP.md
  modules/heat_conduction/doc/content/source/userobjects/GrayLambertSurfaceRadiation.md
  modules/heat_conduction/include/bcs/GrayLambertNeumannBC.h
  modules/heat_conduction/include/postprocessors/GrayLambertSurfaceRadiationPP.h
  modules/heat_conduction/include/userobjects/GrayLambertSurfaceRadiation.h
  modules/heat_conduction/src/bcs/GrayLambertNeumannBC.C
  modules/heat_conduction/src/postprocessors/GrayLambertSurfaceRadiationPP.C
  modules/heat_conduction/src/userobjects/GrayLambertSurfaceRadiation.C
  modules/heat_conduction/test/tests/gray_lambert_radiator/coupled_heat_conduction.i
  modules/heat_conduction/test/tests/gray_lambert_radiator/gold/coupled_heat_conduction_out.e
  modules/heat_conduction/test/tests/gray_lambert_radiator/gold/gray_lambert_cavity_out.csv
  modules/heat_conduction/test/tests/gray_lambert_radiator/gray_lambert_cavity.i
  modules/heat_conduction/test/tests/gray_lambert_radiator/tests
Labels: PR: Ready for Review/Merge

#14088 Improvements to PatchSidesetGenerator
  modules/heat_conduction/src/meshgenerators/PatchSidesetGenerator.C
  modules/heat_conduction/test/tests/generate_radiation_patch/tests
Labels: PR: Failed but allowed

#14121 Fix min compile error
  modules/heat_conduction/src/userobjects/GrayLambertSurfaceRadiation.C
Labels: PR: Auto Merge

#14117 fix line numbering for exploded HIT syntax
  framework/contrib/hit/parse.cc
  unit/src/HitTests.C
Labels: PR: Ready for Review/Merge

#14123 Nodal kernel scaling
  framework/doc/content/source/nodalkernels/ReactionNodalKernel.md
  framework/include/nodalkernels/ReactionNodalKernel.h
  framework/src/nodalkernels/NodalKernel.C
  framework/src/nodalkernels/ReactionNodalKernel.C
  framework/src/nodalkernels/TimeNodalKernel.C
  framework/src/systems/NonlinearSystemBase.C
  test/include/nodalkernels/CoefTimeDerivativeNodalKernel.h
  test/src/nodalkernels/CoefTimeDerivativeNodalKernel.C
  test/tests/nodalkernels/scaling/gold/scaling_out.e
  test/tests/nodalkernels/scaling/scaling.i
  test/tests/nodalkernels/scaling/tests
Labels: PR: Ready for Review/Merge

#14131 Catalina warning
  framework/doc/content/css/alert_moose.css
  framework/doc/content/css/moose.css
  modules/doc/content/getting_started/index.md
Labels: PR: Auto Merge

#14114 Included time step size in steady-state tolerance
  framework/doc/content/source/executioners/Transient.md
  framework/include/executioners/Transient.h
  framework/src/executioners/Transient.C
  modules/porous_flow/examples/reservoir_model/regular_grid.i
  modules/porous_flow/examples/restart/gravityeq.i
  test/tests/postprocessors/relative_solution_difference_norm/test.i
  test/tests/time_integrators/aee/aee.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14133 Nodal variable bounding using NodalKernels
  framework/doc/content/source/nodalkernels/CoupledForceNodalKernel.md
  framework/doc/content/source/nodalkernels/LowerBoundNodalKernel.md
  framework/doc/content/source/nodalkernels/UpperBoundNodalKernel.md
  framework/doc/content/source/postprocessors/GreaterThanLessThanPostprocessor.md
  framework/doc/content/source/postprocessors/LMActiveSetSize.md
  framework/include/nodalkernels/CoupledForceNodalKernel.h
  framework/include/nodalkernels/LowerBoundNodalKernel.h
  framework/include/nodalkernels/UpperBoundNodalKernel.h
  framework/include/postprocessors/GreaterThanLessThanPostprocessor.h
  framework/src/nodalkernels/CoupledForceNodalKernel.C
  framework/src/nodalkernels/LowerBoundNodalKernel.C
  framework/src/nodalkernels/NodalKernel.C
  framework/src/nodalkernels/UpperBoundNodalKernel.C
  framework/src/postprocessors/GreaterThanLessThanPostprocessor.C
  test/tests/nodalkernels/constraint_enforcement/gold/interpolated-ncp-lm-nodal-enforcement-nodal-forces_out.e
  test/tests/nodalkernels/constraint_enforcement/gold/lower-bound_out.e
  test/tests/nodalkernels/constraint_enforcement/gold/upper-and-lower-bound_out.e
  test/tests/nodalkernels/constraint_enforcement/gold/upper-bound_out.e
  test/tests/nodalkernels/constraint_enforcement/lower-bound.i
  test/tests/nodalkernels/constraint_enforcement/tests
  test/tests/nodalkernels/constraint_enforcement/upper-and-lower-bound.i
  test/tests/nodalkernels/constraint_enforcement/upper-bound.i
Labels: PR: Auto Merge

#14160 retrieve file_base from correct params object
  framework/src/base/MooseApp.C
Labels: PR: Ready for Review/Merge

#13822 Remove linear checker
  framework/include/problems/FEProblemBase.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/PetscSupport.C
Labels: PR: Ready for Review/Merge

#14098 LAROMANCE update
  modules/tensor_mechanics/doc/content/source/materials/ADLAROMANCEStressUpdateBase.md
  modules/tensor_mechanics/doc/content/source/userobjects/SS316LAROMData.md
  modules/tensor_mechanics/include/materials/ADLAROMANCEStressUpdateBase.h
  modules/tensor_mechanics/include/userobjects/LAROMData.h
  modules/tensor_mechanics/include/userobjects/SS316LAROMData.h
  modules/tensor_mechanics/src/materials/ADLAROMANCEStressUpdateBase.C
  modules/tensor_mechanics/src/materials/ADRadialReturnStressUpdate.C
  modules/tensor_mechanics/src/userobjects/LAROMData.C
  modules/tensor_mechanics/test/include/materials/SS316HLAROMANCEStressUpdateTest.h
  modules/tensor_mechanics/test/src/materials/SS316HLAROMANCEStressUpdateTest.C
  modules/tensor_mechanics/test/tests/rom_stress_update/2drz.i
  modules/tensor_mechanics/test/tests/rom_stress_update/3d.i
  modules/tensor_mechanics/test/tests/rom_stress_update/tests
  modules/tensor_mechanics/test/tests/rom_stress_update/verification.i
Labels: PR: Ready for Review/Merge

#14181 Make conservative transfers work with L2_LAGRANGE
  framework/src/transfers/MultiAppFieldTransfer.C
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_conservative_out.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_conservative_out_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/master_L2_Lagrange_conservative.i
  test/tests/transfers/multiapp_high_order_variable_transfer/sub_L2_Lagrange_conservative.i
  test/tests/transfers/multiapp_high_order_variable_transfer/tests
Labels: PR: Do Not Merge

#14175 Change eigen tagged kernels to use negative sign
  framework/include/problems/EigenProblem.h
  framework/src/problems/EigenProblem.C
  framework/src/systems/NonlinearEigenSystem.C
  framework/src/utils/SlepcSupport.C
  test/include/kernels/PMassKernel.h
  test/src/kernels/PMassKernel.C
  test/tests/problems/eigen_problem/ane.i
  test/tests/problems/eigen_problem/gipm.i
  test/tests/problems/eigen_problem/ne.i
  test/tests/problems/eigen_problem/ne_coupled.i
  test/tests/problems/eigen_problem/ne_deficient_b.i
  test/tests/problems/eigen_problem/tests
Labels: PR: Ready for Review/Merge

#14178 Add IntegratedBC support to eigenvalue systems
  framework/src/systems/NonlinearEigenSystem.C
  test/tests/problems/eigen_problem/gipm_ibc.i
  test/tests/problems/eigen_problem/gold/gipm_ibc_out_eigenvalues_0001.csv
  test/tests/problems/eigen_problem/tests
Labels: PR: Ready for Review/Merge

#13839 Petsc option database, and Picard iteration using Eigen executioner
  framework/include/problems/EigenProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/systems/NonlinearEigenSystem.h
  framework/src/executioners/Eigenvalue.C
  framework/src/problems/EigenProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearEigenSystem.C
  framework/src/utils/PetscSupport.C
  test/tests/problems/eigen_problem/gold/ne_coupled_picard_out_eigenvalues_0001.csv
  test/tests/problems/eigen_problem/gold/ne_coupled_picard_subT_out_sub0_eigenvalues_0001.csv
  test/tests/problems/eigen_problem/ne_coupled_picard.i
  test/tests/problems/eigen_problem/ne_coupled_picard_sub.i
  test/tests/problems/eigen_problem/ne_coupled_picard_subT.i
  test/tests/problems/eigen_problem/ne_coupled_picard_subT_sub.i
  test/tests/problems/eigen_problem/tests
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#14066 Use SMP full by default with solve_type=LINEAR
  framework/doc/content/syntax/Executioner/index.md
  framework/src/actions/CreateExecutionerAction.C
  test/tests/executioners/solve_type_linear/gold/linear_with_full_smp_out.e
  test/tests/executioners/solve_type_linear/linear_with_full_smp.i
  test/tests/executioners/solve_type_linear/tests
Labels: PR: Failed but allowed

#14183 Error out on invalid vals in ParsedFunction
  framework/src/functions/MooseParsedFunctionWrapper.C
  test/tests/functions/parsed/tests
  test/tests/functions/parsed/vals_error.i
Labels: PR: Ready for Review/Merge

#14208 Removed deprecated parameters in IdealGasFluidProperties
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  unit/include/IdealGasFluidPropertiesTest.h
  unit/src/IdealGasFluidPropertiesTest.C
Labels: PR: Auto Merge, PR: Failed but allowed

#14216 Fixups for 14124
  framework/src/problems/FEProblemBase.C
  test/tests/materials/interface_material/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14223 Switch to use GridPartitioner for relationship manager tests
  test/tests/relationship_managers/geometric_neighbors/gold/geometric_edge_neighbors_3D_out.e
  test/tests/relationship_managers/geometric_neighbors/gold/geometric_edge_neighbors_out.e
  test/tests/relationship_managers/geometric_neighbors/tests
Labels: PR: Failed but allowed

#14228 Update GeneralizedPlaneStrain to use TaggingInterface API
  modules/tensor_mechanics/src/scalarkernels/GeneralizedPlaneStrain.C
Labels: PR: Failed but allowed

#14204 Update auto-scaling to use new DiagonalMatrix
  framework/include/systems/NonlinearSystem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/MooseTypes.C
  test/tests/kernels/simple_transient_diffusion/tests
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#14234 Diagonal matrix fixups
  modules/tensor_mechanics/test/tests/rom_stress_update/gold/verification_1e-5_out.e
  modules/tensor_mechanics/test/tests/rom_stress_update/tests
  modules/tensor_mechanics/test/tests/rom_stress_update/verification-heavy.cmp
  modules/tensor_mechanics/test/tests/rom_stress_update/verification.i
Labels: PR: Failed but allowed

#14251 Revert #14234
  modules/tensor_mechanics/test/tests/rom_stress_update/gold/verification_1e-5_out.e
  modules/tensor_mechanics/test/tests/rom_stress_update/tests
  modules/tensor_mechanics/test/tests/rom_stress_update/verification-heavy.cmp
  modules/tensor_mechanics/test/tests/rom_stress_update/verification.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14254 Remove whitespaces in the CSV keys
  python/mooseutils/csvdiff.py
Labels: PR: Failed but allowed

#14239 Moved ccache page from old wiki to moosedocs
  modules/doc/content/help/development/ccache.md
  modules/doc/content/help/development/index.md
Labels: PR: Failed but allowed

#14265 Mortar with tensor mechanics test shortening
  modules/combined/test/tests/mortar_tm/2d/ad_frictionless_fir/finite.i
  modules/combined/test/tests/mortar_tm/2d/ad_frictionless_fir/finite_rr.i
  modules/combined/test/tests/mortar_tm/2d/ad_frictionless_fir/small.i
  modules/combined/test/tests/mortar_tm/2d/ad_frictionless_sec/finite.i
  modules/combined/test/tests/mortar_tm/2d/ad_frictionless_sec/finite_rr.i
  modules/combined/test/tests/mortar_tm/2d/ad_frictionless_sec/small.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_first/finite.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_first/finite_noaction.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_first/finite_rr.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_first/gold/small.csv
  modules/combined/test/tests/mortar_tm/2d/frictionless_first/small.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_second/finite.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_second/finite_noaction.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_second/finite_rr.i
  modules/combined/test/tests/mortar_tm/2d/frictionless_second/gold/small.csv
  modules/combined/test/tests/mortar_tm/2d/frictionless_second/small.i
  modules/combined/test/tests/mortar_tm/2drz/ad_frictionless_first/finite.i
  modules/combined/test/tests/mortar_tm/2drz/ad_frictionless_first/finite_rr.i
  modules/combined/test/tests/mortar_tm/2drz/ad_frictionless_first/small.i
  modules/combined/test/tests/mortar_tm/2drz/ad_frictionless_second/finite.i
  modules/combined/test/tests/mortar_tm/2drz/ad_frictionless_second/finite_rr.i
  modules/combined/test/tests/mortar_tm/2drz/ad_frictionless_second/small.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_first/finite.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_first/finite_noaction.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_first/finite_rr.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_first/gold/finite.csv
  modules/combined/test/tests/mortar_tm/2drz/frictionless_first/gold/small.csv
  modules/combined/test/tests/mortar_tm/2drz/frictionless_first/gold/soft_stiff.csv
  modules/combined/test/tests/mortar_tm/2drz/frictionless_first/small.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_second/finite.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_second/finite_noaction.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_second/finite_rr.i
  modules/combined/test/tests/mortar_tm/2drz/frictionless_second/gold/finite.csv
  modules/combined/test/tests/mortar_tm/2drz/frictionless_second/gold/small.csv
  modules/combined/test/tests/mortar_tm/2drz/frictionless_second/gold/soft_stiff.csv
  modules/combined/test/tests/mortar_tm/2drz/frictionless_second/small.i
Labels: PR: Failed but allowed

#14224 Moved tests
  modules/combined/test/tests/1D_axisymmetric/tests
  modules/combined/test/tests/accumulate_aux/tests
  modules/combined/test/tests/beam_eigenstrain_transfer/tests
  modules/combined/test/tests/elasticitytensor/tests
  modules/combined/test/tests/generalized_plane_strain_tm_contact/generalized_plane_strain_tm_contact.i
  modules/combined/test/tests/heat_conduction_ortho/tests
  modules/combined/test/tests/joule_heating/gold/jouleheating_out.e
  modules/combined/test/tests/joule_heating/jouleheating.i
  modules/combined/test/tests/joule_heating/tests
  modules/combined/test/tests/joule_heating_heat/gold/jouleheating_heat_out.e
  modules/combined/test/tests/joule_heating_heat/jouleheating_heat.i
  modules/combined/test/tests/joule_heating_heat/tests
  modules/combined/test/tests/misc/coupled_directional_mesh_height_interpolation/tests
  modules/heat_conduction/test/tests/heat_conduction_ortho/gold/heat_conduction_ortho_out.e
  modules/heat_conduction/test/tests/heat_conduction_ortho/heat_conduction_ortho.e
  modules/heat_conduction/test/tests/heat_conduction_ortho/heat_conduction_ortho.i
  modules/heat_conduction/test/tests/heat_conduction_ortho/tests
  modules/heat_conduction/test/tests/transient_heat/cube.e
  modules/heat_conduction/test/tests/transient_heat/gold/transient_heat_out.e
  modules/heat_conduction/test/tests/transient_heat/tests
  modules/heat_conduction/test/tests/transient_heat/transient_heat.i
  modules/misc/test/tests/coupled_directional_mesh_height_interpolation/coupled_directional_mesh_height_interpolation.i
  modules/misc/test/tests/coupled_directional_mesh_height_interpolation/gold/coupled_directional_mesh_height_interpolation_out.e
  modules/misc/test/tests/coupled_directional_mesh_height_interpolation/tests
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/VisualizingTensors.md
  modules/tensor_mechanics/doc/content/source/materials/CompositeElasticityTensor.md
  modules/tensor_mechanics/test/tests/1D_axisymmetric/axisymmetric_gps_finite.i
  modules/tensor_mechanics/test/tests/1D_axisymmetric/axisymmetric_gps_incremental.i
  modules/tensor_mechanics/test/tests/1D_axisymmetric/axisymmetric_gps_small.i
  modules/tensor_mechanics/test/tests/1D_axisymmetric/gold/axisymmetric_gps_finite_out.e
  modules/tensor_mechanics/test/tests/1D_axisymmetric/gold/axisymmetric_gps_incremental_out.e
  modules/tensor_mechanics/test/tests/1D_axisymmetric/gold/axisymmetric_gps_small_out.e
  modules/tensor_mechanics/test/tests/1D_axisymmetric/lines.e
  modules/tensor_mechanics/test/tests/1D_axisymmetric/tests
  modules/tensor_mechanics/test/tests/accumulate_aux/accumulate_aux.i
  modules/tensor_mechanics/test/tests/accumulate_aux/gold/accumulate_aux_out.e
  modules/tensor_mechanics/test/tests/accumulate_aux/square.e
  modules/tensor_mechanics/test/tests/accumulate_aux/square.jou
  modules/tensor_mechanics/test/tests/accumulate_aux/tests
  modules/tensor_mechanics/test/tests/elasticitytensor/composite.i
  modules/tensor_mechanics/test/tests/elasticitytensor/gold/composite_out.e
  modules/tensor_mechanics/test/tests/elasticitytensor/tests
  modules/tensor_mechanics/test/tests/finite_strain_tensor_mechanics_tests/elastic_rotation.i
  modules/tensor_mechanics/test/tests/finite_strain_tensor_mechanics_tests/finite_strain_patch.i
  modules/tensor_mechanics/test/tests/finite_strain_tensor_mechanics_tests/gold/elastic_rotation_out.e
  modules/tensor_mechanics/test/tests/finite_strain_tensor_mechanics_tests/gold/finite_strain_patch_out.e
  modules/tensor_mechanics/test/tests/finite_strain_tensor_mechanics_tests/patch_mesh.e
  modules/tensor_mechanics/test/tests/finite_strain_tensor_mechanics_tests/rotation_test.e
  modules/tensor_mechanics/test/tests/finite_strain_tensor_mechanics_tests/tests
Labels: PR: Failed but allowed

#14243 Add GetPostprocessorValueOld into AD Materials
  framework/include/materials/ADMaterial.h
Labels: PR: Auto Merge
