Repository idaholab/moose, pull requests merged in 2019-08, with the labels that each got.

#13838 Post-check algebraic and coupling ghosting enhancements
  framework/doc/content/source/postprocessors/NumRelationshipManagers.md
  framework/doc/content/source/relationshipmanagers/RelationshipManager.md
  framework/include/actions/Action.h
  framework/include/postprocessors/NumRelationshipManagers.h
  framework/include/relationshipmanagers/RelationshipManager.h
  framework/include/utils/MooseTypes.h
  framework/include/utils/TimedPrint.h
  framework/src/actions/Action.C
  framework/src/actions/CouplingFunctorCheckAction.C
  framework/src/actions/CreateDisplacedProblemAction.C
  framework/src/bcs/BoundaryCondition.C
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/kernels/KernelBase.C
  framework/src/postprocessors/NumRelationshipManagers.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/relationshipmanagers/ElementSideNeighborLayers.C
  framework/src/relationshipmanagers/RelationshipManager.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/systems/DisplacedSystem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/Conversion.C
  modules/doc/content/application_development/relationship_managers.md
  test/include/actions/AddDGDiffusion.h
  test/src/actions/AddDGDiffusion.C
  test/src/base/MooseTestApp.C
  test/tests/dgkernels/2d_diffusion_dg/gold/no_functor_additions_distributed.e
  test/tests/dgkernels/2d_diffusion_dg/gold/no_functor_additions_out.e
  test/tests/dgkernels/2d_diffusion_dg/gold/no_mallocs_with_action_distributed.e
  test/tests/dgkernels/2d_diffusion_dg/gold/no_mallocs_with_action_out.e
  test/tests/dgkernels/2d_diffusion_dg/gold/no_mallocs_with_action_parallel.e
  test/tests/dgkernels/2d_diffusion_dg/gold/no_mallocs_with_action_parallel_distributed.e
  test/tests/dgkernels/2d_diffusion_dg/no_functor_additions.i
  test/tests/dgkernels/2d_diffusion_dg/no_mallocs_with_action.i
  test/tests/dgkernels/2d_diffusion_dg/tests
  test/tests/misc/max_var_n_dofs_per_elem/max_var_n_dofs_per_elem.i
Labels: PR: Ready for Review/Merge

#13845 Added a flag to skip checkExceptionAndStopSolve
  framework/include/problems/FEProblemBase.h
  framework/src/executioners/FEProblemSolve.C
  framework/src/problems/FEProblemBase.C
  test/tests/misc/exception/2d_diffusion_skip_exception.i
  test/tests/misc/exception/gold/2d_diffusion_skip_exception_out.e
  test/tests/misc/exception/tests
Labels: PR: Ready for Review/Merge

#13877 Continue support of old-style stub pages
  python/MooseDocs/commands/check.py
Labels: PR: Auto Merge

#13849 Nest mesh generators
  framework/include/actions/SetupMeshAction.h
  framework/include/base/MooseApp.h
  framework/src/actions/SetupMeshAction.C
  framework/src/base/Moose.C
  framework/src/base/MooseApp.C
  framework/src/meshmodifiers/AddAllSideSetsByNormals.C
  framework/src/meshmodifiers/AddExtraNodeset.C
  framework/src/meshmodifiers/AddSideSetsFromBoundingBox.C
  framework/src/meshmodifiers/AssignElementSubdomainID.C
  framework/src/meshmodifiers/AssignSubdomainID.C
  framework/src/meshmodifiers/BlockDeleter.C
  framework/src/meshmodifiers/BoundingBoxNodeSet.C
  framework/src/meshmodifiers/BreakBoundaryOnSubdomain.C
  framework/src/meshmodifiers/BreakMeshByBlock.C
  framework/src/meshmodifiers/ImageSubdomain.C
  framework/src/meshmodifiers/LowerDBlockFromSideset.C
  framework/src/meshmodifiers/MeshExtruder.C
  framework/src/meshmodifiers/MeshSideSet.C
  framework/src/meshmodifiers/OrientedSubdomainBoundingBox.C
  framework/src/meshmodifiers/ParsedAddSideset.C
  framework/src/meshmodifiers/ParsedSubdomainMeshModifier.C
  framework/src/meshmodifiers/RenameBlock.C
  framework/src/meshmodifiers/SideSetsAroundSubdomain.C
  framework/src/meshmodifiers/SideSetsBetweenSubdomains.C
  framework/src/meshmodifiers/SideSetsFromNormals.C
  framework/src/meshmodifiers/SideSetsFromPoints.C
  framework/src/meshmodifiers/SmoothMesh.C
  framework/src/meshmodifiers/SubdomainBoundingBox.C
  framework/src/meshmodifiers/Transform.C
  test/tests/mesh/mesh_only/output_dimension_override.i
  test/tests/meshgenerators/plane_deletion/plane_deletion.i
Labels: PR: Ready for Review/Merge

#13894 Skip bbox uo transfer
  framework/include/transfers/MultiAppUserObjectTransfer.h
  framework/src/transfers/MultiAppUserObjectTransfer.C
  test/tests/transfers/multiapp_userobject_transfer/gold/two_pipe_master_out.e
  test/tests/transfers/multiapp_userobject_transfer/tests
  test/tests/transfers/multiapp_userobject_transfer/two_pipe.e
  test/tests/transfers/multiapp_userobject_transfer/two_pipe_master.i
  test/tests/transfers/multiapp_userobject_transfer/two_pipe_sub.i
Labels: PR: Ready for Review/Merge

#13887 ComputeJacobianBlocksThread: add face contributions
  framework/include/loops/ComputeJacobianBlocksThread.h
  framework/src/loops/ComputeJacobianBlocksThread.C
  test/tests/preconditioners/pbp/gold/pbp_dg_test_out.e
  test/tests/preconditioners/pbp/pbp_dg_test.i
  test/tests/preconditioners/pbp/pbp_test.i
  test/tests/preconditioners/pbp/tests
Labels: PR: Ready for Review/Merge

#13911 string -> std::string
  framework/src/utils/MooseUtils.C
Labels: PR: Auto Merge

#13900 Updates to the MOOSE SRS and SDD documents
  framework/doc/acronyms.yml
  framework/doc/content/media/sqa/code_platform.png
  framework/doc/content/media/sqa/usage_diagram_uml.svg
  framework/doc/content/sqa/framework_sdd.md
  framework/doc/content/sqa/framework_srs.md
  framework/doc/content/templates/sqa/sdd.md.template
Labels: PR: Ready for Review/Merge

#13837 Add clone_master_mesh parameter for MultiApps
  framework/include/base/MooseApp.h
  framework/src/actions/AddMeshGeneratorAction.C
  framework/src/actions/AddMeshModifierAction.C
  framework/src/actions/SetupMeshAction.C
  framework/src/base/MooseApp.C
  framework/src/multiapps/MultiApp.C
  test/tests/multiapps/picard/picard_master.i
Labels: PR: Failed but allowed

#13926 Remove clang-format v8 feature
  .clang-format
Labels: PR: Auto Merge, PR: Failed but allowed

#13928 Fixing up incorrect branch names for contributing pages
  modules/doc/content/framework_development/contributing.md
  modules/doc/content/framework_development/patch_to_code.md
Labels: PR: Auto Merge, PR: Failed but allowed

#13929 Adopt new framework add*Variable APIs
  modules/contact/src/ContactPenetrationVarAction.C
  modules/contact/src/ContactPressureVarAction.C
  modules/contact/src/NodalAreaVarAction.C
  modules/heat_conduction/src/actions/ThermalContactAction.C
  modules/navier_stokes/src/actions/AddNavierStokesVariablesAction.C
Labels: PR: Ready for Review/Merge

#13936 Manually --enable-glibcxx-debugging in libmesh
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Ready for Review/Merge

#13937 templated some mathutils, and used raw_value for some outputs
  framework/include/utils/MathUtils.h
  framework/src/utils/MathUtils.C
  modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C
  modules/tensor_mechanics/src/materials/ADSingleVariableReturnMappingSolution.C
Labels: PR: Ready for Review/Merge

#13938 parallel test failure fixup
  modules/tensor_mechanics/test/tests/ad_linear_elasticity/extra_stresses.i
  modules/tensor_mechanics/test/tests/ad_linear_elasticity/gold/extra_stresses_out.e
  modules/tensor_mechanics/test/tests/ad_linear_elasticity/linear_elastic_material.i
  modules/tensor_mechanics/test/tests/ad_linear_elasticity/tensor.i
Labels: PR: Auto Merge

#13939 Updated PETSc URL since PETSc has been moved to gitlab
  .gitmodules
Labels: PR: Auto Merge

#13934 Add Dockerfile and Jenkinsfile to Repo
  docker_ci/Dockerfile
  docker_ci/Jenkinsfile
  scripts/update_and_rebuild_petsc.sh
Labels: PR: Ready for Review/Merge

#13941 Separate peacock tests to avoid timeout
  python/peacock/tests/input_tab/InputTree/tests
Labels: PR: Ready for Review/Merge

#13946 Set appropriate default for parameters for moose variables
  framework/src/variables/MooseVariableConstMonomial.C
  framework/src/variables/MooseVariableScalar.C
Labels: PR: Auto Merge

#13889 Handle block restricted elemental variables
  python/chigger/base/ColorMap.py
  python/chigger/exodus/ExodusSource.py
  python/chigger/tests/exodus/blocks/gold/partial.png
  python/chigger/tests/exodus/blocks/partial.py
  python/chigger/tests/exodus/blocks/tests
  python/chigger/tests/input/block_vars.i
  python/chigger/tests/input/block_vars_out.e
  python/chigger/vtk_scripts/elem_block.py
Labels: PR: Auto Merge

#13944 Miscellaneous geometric stuff
  framework/doc/content/media/geomsearch/nearest_node_diagram.jpg
  framework/doc/content/media/geomsearch/penetration_diagram.jpg
  framework/doc/content/source/geomsearch/GeometricSearchData.md
  framework/doc/content/source/geomsearch/NearestNodeLocator.md
  framework/doc/content/source/geomsearch/PenetrationLocator.md
  framework/doc/content/source/systems/NonlinearSystem.md
  framework/doc/content/sqa/what_is_a_requirement.md
  framework/include/mesh/MooseMesh.h
  framework/src/geomsearch/GeometricSearchData.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/LowerDBlockFromSidesetGenerator.C
  framework/src/problems/DisplacedProblem.C
  modules/contact/include/MechanicalContactConstraint.h
  modules/contact/src/MechanicalContactConstraint.C
  test/include/materials/QuadratureLocatorTestMaterial.h
  test/src/materials/QuadratureLocatorTestMaterial.C
  test/tests/geomsearch/quadrature_locator_plus_constraint/nodal_normals_test_offset_nonmatching_gap.e
  test/tests/geomsearch/quadrature_locator_plus_constraint/quadrature_locator_plus_constraint.i
  test/tests/geomsearch/quadrature_locator_plus_constraint/tests
Labels: PR: Ready for Review/Merge

#13990 Fix memory leak created in stateful property + recover fix
  framework/include/materials/MaterialPropertyStorage.h
  framework/src/materials/MaterialPropertyStorage.C
Labels: PR: Ready for Review/Merge
