Repository idaholab/moose, pull requests merged in 2019-02, with the labels that each got.

#12813 Don't calculate equilibrium mass fractions uneccesarily
  modules/porous_flow/include/userobjects/PorousFlowBrineCO2.h
  modules/porous_flow/src/userobjects/PorousFlowBrineCO2.C
Labels: PR: Failed but allowed

#12817 'mu_from_p_T' and 'k_from_p_T' interface added to IdealGasFluidProperties and StiffenedGasFluidProperties
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
  unit/src/IdealGasFluidPropertiesTest.C
  unit/src/StiffenedGasFluidPropertiesTest.C
Labels: PR: Failed but allowed

#12811 Make sure PorousFlow actions add all versions of materials as needed
  modules/porous_flow/include/actions/PorousFlowActionBase.h
  modules/porous_flow/include/actions/PorousFlowBasicTHM.h
  modules/porous_flow/include/actions/PorousFlowFullySaturated.h
  modules/porous_flow/include/actions/PorousFlowSinglePhaseBase.h
  modules/porous_flow/include/actions/PorousFlowUnsaturated.h
  modules/porous_flow/src/actions/PorousFlowActionBase.C
  modules/porous_flow/src/actions/PorousFlowAddMaterialAction.C
  modules/porous_flow/src/actions/PorousFlowBasicTHM.C
  modules/porous_flow/src/actions/PorousFlowFullySaturated.C
  modules/porous_flow/src/actions/PorousFlowSinglePhaseBase.C
  modules/porous_flow/src/actions/PorousFlowUnsaturated.C
  modules/porous_flow/src/utils/PorousFlowDependencies.C
  modules/porous_flow/test/tests/actions/basicthm_h.i
  modules/porous_flow/test/tests/actions/basicthm_hm.i
  modules/porous_flow/test/tests/actions/basicthm_th.i
  modules/porous_flow/test/tests/actions/basicthm_thm.i
  modules/porous_flow/test/tests/actions/gold/basicthm_h_out.e
  modules/porous_flow/test/tests/actions/gold/basicthm_hm_out.e
  modules/porous_flow/test/tests/actions/gold/basicthm_th_out.e
  modules/porous_flow/test/tests/actions/gold/basicthm_thm_out.e
  modules/porous_flow/test/tests/actions/tests
  modules/porous_flow/test/tests/dispersion/diff01_action.i
Labels: PR: Failed but allowed

#12819 Clarify how PorousFlowPiecewiseLinearSink can specify BCs
  modules/porous_flow/doc/content/media/porous_flow/piecewiselinear_g_function.png
  modules/porous_flow/doc/content/modules/porous_flow/boundaries.md
  modules/porous_flow/test/tests/sinks/PorousFlowPiecewiseLinearSink_BC_eg1.i
  modules/porous_flow/test/tests/sinks/gold/PorousFlowPiecewiseLinearSink_BC_eg1_out.csv
  modules/porous_flow/test/tests/sinks/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12801 Add Green-Lagrange strain calculator
  framework/src/kernels/ADKernel.C
  modules/tensor_mechanics/doc/content/source/materials/ADComputeGreenLagrangeStrain.md
  modules/tensor_mechanics/examples/hyper_elastic_test.i
  modules/tensor_mechanics/include/materials/ADComputeGreenLagrangeStrain.h
  modules/tensor_mechanics/src/materials/ADComputeGreenLagrangeStrain.C
  modules/tensor_mechanics/test/tests/ad_finite_elastic/gold/green-lagrange_out.e
  modules/tensor_mechanics/test/tests/ad_finite_elastic/green-lagrange.i
  modules/tensor_mechanics/test/tests/ad_finite_elastic/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12820 stdVector() on MooseArray can be marked const
  framework/include/utils/MooseArray.h
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12834 Update to Hertz contact regression tests
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_kin_check2.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_kin_check_cont_press_0035.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_kin_check_x_disp_0035.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_kin_check_y_disp_0035.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_kin_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_pen_check2.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_pen_check_cont_press_0035.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_pen_check_x_disp_0035.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_pen_check_y_disp_0035.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_frictionless_pen_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_kin_check2.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_kin_check_cont_press_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_kin_check_x_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_kin_check_y_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_kin_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_pen_check2.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_pen_check_cont_press_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_pen_check_x_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_pen_check_y_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_glued_pen_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_2_aug_check2.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_2_aug_check_cont_press_0030.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_2_aug_check_x_disp_0030.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_2_aug_check_y_disp_0030.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_2_aug_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_pen_check2.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_pen_check_cont_press_0020.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_pen_check_x_disp_0020.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_pen_check_y_disp_0020.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_0_pen_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_1_0_pen_check2.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_1_0_pen_check_cont_press_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_1_0_pen_check_x_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_1_0_pen_check_y_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/gold/hertz_cyl_half_1deg_mu_1_0_pen_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/hertz_cyl_half_1deg_template1.i
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/hertz_cyl_half_1deg_template3.i
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_kin_check.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_kin_check_cont_press_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_kin_check_x_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_kin_check_y_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_kin_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_pen_check.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_pen_check_cont_press_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_pen_check_x_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_pen_check_y_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_frictionless_pen_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_kin_check.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_kin_check_cont_press_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_kin_check_x_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_kin_check_y_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_kin_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_pen_check.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_pen_check_cont_press_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_pen_check_x_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_pen_check_y_disp_0010.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/gold/hertz_cyl_qsym_1deg_glued_pen_out.csv
  modules/combined/test/tests/contact_verification/hertz_cyl/quart_symm_q8/hertz_cyl_qsym_1deg_template1.i
Labels: PR: Failed but allowed

#12789 Added maximum shear and stress intensity output quantities
  modules/tensor_mechanics/doc/content/source/auxkernels/RankTwoScalarAux.md
  modules/tensor_mechanics/include/utils/RankTwoScalarTools.h
  modules/tensor_mechanics/src/utils/RankTwoScalarTools.C
  modules/tensor_mechanics/test/tests/elastic_patch/elastic_patch.i
  modules/tensor_mechanics/test/tests/elastic_patch/gold/elastic_patch_out.e
  modules/tensor_mechanics/test/tests/elastic_patch/gold/elastic_patch_small_out.e
Labels: PR: Failed but allowed

#12836 Add ADTimeDerivative
  framework/doc/content/source/kernels/ADTimeDerivative.md
  framework/include/kernels/ADTimeDerivative.h
  framework/src/kernels/ADTimeDerivative.C
  framework/src/variables/MooseVariableFE.C
  test/tests/kernels/ad_transient_diffusion/ad_transient_diffusion.i
  test/tests/kernels/ad_transient_diffusion/gold/ad_transient_diffusion_out.e
  test/tests/kernels/ad_transient_diffusion/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#12810 Pre-calculate and cache Jacobian in PorousFlowAdvectiveFluxCalculator
  modules/porous_flow/include/userobjects/PorousFlowAdvectiveFluxCalculatorBase.h
  modules/porous_flow/src/kernels/PorousFlowFluxLimitedTVDAdvection.C
  modules/porous_flow/src/userobjects/PorousFlowAdvectiveFluxCalculatorBase.C
Labels: PR: Failed but allowed

#12845 Add package installation commands
  modules/doc/content/getting_started/installation/centos_pre_req.md
  modules/doc/content/getting_started/installation/fedora_pre_req.md
  modules/doc/content/getting_started/installation/mint_pre_req.md
  modules/doc/content/getting_started/installation/opensuse_pre_req.md
  modules/doc/content/getting_started/installation/ubuntu_pre_req.md
Labels: PR: Failed but allowed

#12841 Specific heat derivatives to Fluid Properties module
  modules/fluid_properties/include/userobjects/HelmholtzFluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/NaClFluidProperties.h
  modules/fluid_properties/include/userobjects/SimpleFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/include/userobjects/TabulatedFluidProperties.h
  modules/fluid_properties/include/userobjects/Water97FluidProperties.h
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  modules/fluid_properties/src/userobjects/SimpleFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
  unit/src/IdealGasFluidPropertiesTest.C
  unit/src/SimpleFluidPropertiesTest.C
  unit/src/StiffenedGasFluidPropertiesTest.C
Labels: PR: Failed but allowed

#12829 Speed up BrineFluidProperties
  modules/fluid_properties/doc/content/source/userobjects/BrineFluidProperties.md
  modules/fluid_properties/include/userobjects/TabulatedFluidProperties.h
  modules/fluid_properties/src/userobjects/BrineFluidProperties.C
  modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
  modules/fluid_properties/test/tests/brine/brine_tabulated.i
  modules/fluid_properties/test/tests/brine/tests
  modules/porous_flow/doc/content/modules/porous_flow/brineco2.md
  modules/porous_flow/examples/co2_intercomparison/1Dradial/1Dradial.i
  modules/porous_flow/test/tests/fluidstate/gold/theis_brineco2_csvout.csv
  modules/porous_flow/test/tests/fluidstate/theis_brineco2.i
Labels: PR: Failed but allowed

#12827 Remove const_cast in FiniteStrainUObasedCP
  modules/tensor_mechanics/doc/content/source/materials/FiniteStrainUObasedCP.md
  modules/tensor_mechanics/doc/content/source/userobjects/CrystalPlasticitySlipRateGSS.md
  modules/tensor_mechanics/doc/content/source/userobjects/CrystalPlasticitySlipResistanceGSS.md
  modules/tensor_mechanics/doc/content/source/userobjects/CrystalPlasticityStateVarRateComponentGSS.md
  modules/tensor_mechanics/doc/content/source/userobjects/CrystalPlasticityStateVariable.md
  modules/tensor_mechanics/include/materials/FiniteStrainUObasedCP.h
  modules/tensor_mechanics/include/userobjects/CrystalPlasticityStateVariable.h
  modules/tensor_mechanics/src/materials/FiniteStrainUObasedCP.C
  modules/tensor_mechanics/src/userobjects/CrystalPlasticityStateVariable.C
Labels: PR: Failed but allowed

#12808 Fix mesh generators with displaced mesh
  framework/include/base/MooseApp.h
  framework/src/base/MooseApp.C
  framework/src/meshgenerators/AnnularMeshGenerator.C
  test/tests/meshgenerators/displaced_mesh/displaced_mesh.i
  test/tests/meshgenerators/displaced_mesh/gold/displaced_mesh_in.e
  test/tests/meshgenerators/displaced_mesh/tests
Labels: PR: Failed but allowed

#12860 Floating point formatting in csvdiff reports
  python/mooseutils/csvdiff.py
Labels: PR: Failed but allowed

#12864 Update fluid properties method names
  modules/fluid_properties/include/userobjects/CO2FluidProperties.h
  modules/fluid_properties/include/userobjects/HelmholtzFluidProperties.h
  modules/fluid_properties/include/userobjects/HydrogenFluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/MethaneFluidProperties.h
  modules/fluid_properties/include/userobjects/NaClFluidProperties.h
  modules/fluid_properties/include/userobjects/NitrogenFluidProperties.h
  modules/fluid_properties/include/userobjects/SimpleFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/TabulatedFluidProperties.h
  modules/fluid_properties/include/userobjects/Water97FluidProperties.h
  modules/fluid_properties/src/userobjects/CO2FluidProperties.C
  modules/fluid_properties/src/userobjects/HelmholtzFluidProperties.C
  modules/fluid_properties/src/userobjects/HydrogenFluidProperties.C
  modules/fluid_properties/src/userobjects/IdealGasFluidPropertiesPT.C
  modules/fluid_properties/src/userobjects/MethaneFluidProperties.C
  modules/fluid_properties/src/userobjects/NaClFluidProperties.C
  modules/fluid_properties/src/userobjects/NitrogenFluidProperties.C
  modules/fluid_properties/src/userobjects/SimpleFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
  modules/fluid_properties/src/userobjects/Water97FluidProperties.C
  modules/fluid_properties/test/include/utils/SinglePhaseFluidPropertiesPTTestUtils.h
  modules/porous_flow/src/materials/PorousFlowSingleComponentFluid.C
  modules/porous_flow/src/userobjects/PorousFlowBrineCO2.C
  modules/porous_flow/src/userobjects/PorousFlowWaterNCG.C
  unit/include/Water97FluidPropertiesTest.h
  unit/src/CO2FluidPropertiesTest.C
  unit/src/HydrogenFluidPropertiesTest.C
  unit/src/IdealGasFluidPropertiesPTTest.C
  unit/src/MethaneFluidPropertiesTest.C
  unit/src/NaClFluidPropertiesTest.C
  unit/src/NitrogenFluidPropertiesTest.C
  unit/src/SimpleFluidPropertiesTest.C
  unit/src/TabulatedFluidPropertiesTest.C
  unit/src/Water97FluidPropertiesTest.C
Labels: PR: Failed but allowed

#12866 Make FileMeshGenerator work with distributed mesh
  framework/src/meshgenerators/FileMeshGenerator.C
  test/tests/meshgenerators/sideset_around_subdomain_generator/tests
  test/tests/meshgenerators/sidesets_between_subdomains_generator/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12856 Remove deprecated input parameter in PorousFlow actions
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/except01.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/except02.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/except03.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/except04.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/except05.i
  modules/porous_flow/test/tests/gravity/grav01c_action.i
  modules/porous_flow/test/tests/thm_rehbinder/fixed_outer.i
  modules/porous_flow/test/tests/thm_rehbinder/fixed_outer_rz.i
  modules/porous_flow/test/tests/thm_rehbinder/free_outer.i
Labels: PR: Failed but allowed

#12842 Adds adCoupledVectorValue and adCoupledVectorGradient
  framework/include/interfaces/Coupleable.h
  framework/src/interfaces/Coupleable.C
  test/include/kernels/ADCoupledVectorConvection.h
  test/src/kernels/ADCoupledVectorConvection.C
  test/tests/kernels/ad_vector_couple/ad_grad_vector_couple.i
  test/tests/kernels/ad_vector_couple/ad_vector_couple.i
  test/tests/kernels/ad_vector_couple/ad_vector_couple_default.i
  test/tests/kernels/ad_vector_couple/gold/ad_grad_vector_couple_out.e
  test/tests/kernels/ad_vector_couple/gold/ad_vector_couple_default_out.e
  test/tests/kernels/ad_vector_couple/gold/ad_vector_couple_out.e
  test/tests/kernels/ad_vector_couple/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12648 Added ADHeatConductionTimeDerivative
  modules/heat_conduction/doc/content/source/kernels/ADHeatConductionTimeDerivative.md
  modules/heat_conduction/include/kernels/ADHeatConductionTimeDerivative.h
  modules/heat_conduction/src/kernels/ADHeatConduction.C
  modules/heat_conduction/src/kernels/ADHeatConductionTimeDerivative.C
  modules/heat_conduction/test/tests/ad_heat_conduction/test.i
  modules/heat_conduction/test/tests/ad_heat_conduction/tests
  modules/heat_conduction/test/tests/verify_against_analytical/ad_1D_transient.i
Labels: PR: Failed but allowed

#12869 Update MOOSEDocs sqa testing to use test specs from MOOSEDocs
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/test/gold/html/extensions/sqa.html
  python/MooseDocs/test/gold/latex/extensions/sqa.tex
  python/MooseDocs/test/gold/materialize/extensions/sqa.html
  python/MooseDocs/test/html.yml
  python/MooseDocs/test/json.yml
  python/MooseDocs/test/latex.yml
  python/MooseDocs/test/materialize.yml
Labels: PR: Failed but allowed

#12861 Adding a virtual function for derivatives of beta_from_p_T (SinglePhaseFluidProperties)
  modules/fluid_properties/include/userobjects/SimpleFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/src/userobjects/SimpleFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
Labels: PR: Failed but allowed

#12876 Fix leak
  framework/src/interfaces/Coupleable.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12875 Fixup element generator so it works with distributed mesh
  framework/src/meshgenerators/ElementGenerator.C
  test/tests/meshgenerators/block_deletion_generator/tests
  test/tests/meshgenerators/element_generator/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12872 Make ExternalPetscSolverApp compile with PETSc-3.6.x
  modules/external_petsc_solver/src/petscsolver/PETScDiffusionFDM.C
Labels: PR: Failed but allowed

#12878 Removing old deprecated and used code
  framework/include/utils/LinearInterpolation.h
  framework/include/utils/PolynomialFit.h
  framework/include/utils/SplineInterpolation.h
  framework/src/utils/LinearInterpolation.C
  framework/src/utils/PolynomialFit.C
  framework/src/utils/SplineInterpolation.C
  test/include/materials/LinearInterpolationMaterial.h
  test/src/materials/LinearInterpolationMaterial.C
  test/tests/utils/linear_interp_mat/linear_interp_mat_test.i
  test/tests/utils/linear_interp_mat/tests
Labels: PR: Failed but allowed

#12883 Add capillary pressure output to PorousFlowProperyAux
  modules/porous_flow/doc/content/source/auxkernels/PorousFlowPropertyAux.md
  modules/porous_flow/include/auxkernels/PorousFlowPropertyAux.h
  modules/porous_flow/src/auxkernels/PorousFlowPropertyAux.C
  modules/porous_flow/test/tests/aux_kernels/gold/properties_out.e
  modules/porous_flow/test/tests/aux_kernels/properties.i
Labels: PR: Failed but allowed

#12880 Allow LAGRANGE_VEC simulations to be performed in 1D
  framework/include/bcs/VectorIntegratedBC.h
  framework/include/kernels/ADKernel.h
  framework/include/kernels/VectorKernel.h
  framework/src/base/Assembly.C
  framework/src/bcs/VectorIntegratedBC.C
  framework/src/kernels/VectorKernel.C
  test/include/kernels/VectorFEWave.h
  test/src/kernels/VectorFEWave.C
  test/tests/kernels/vector_fe/gold/lagrange_vec_1d_out.e
  test/tests/kernels/vector_fe/lagrange_vec_1d.i
  test/tests/kernels/vector_fe/tests
Labels: PR: Failed but allowed

#12886 Fix logic for creating links in MOOSEDocs content extension
  python/MooseDocs/extensions/content.py
  python/MooseDocs/test/gold/latex/extensions/content.tex
  python/MooseDocs/test/gold/materialize/extensions/content.html
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12891 1D, 2D, 3D cartesian mesh generator tests
  framework/doc/content/source/meshgenerators/CartesianMeshGenerator.md
  test/tests/meshgenerators/cartesian_mesh_generator/cartesian_mesh_1D.i
  test/tests/meshgenerators/cartesian_mesh_generator/cartesian_mesh_2D.i
  test/tests/meshgenerators/cartesian_mesh_generator/cartesian_mesh_3D.i
  test/tests/meshgenerators/cartesian_mesh_generator/gold/cartesian_mesh_1D_in.e
  test/tests/meshgenerators/cartesian_mesh_generator/gold/cartesian_mesh_2D_in.e
  test/tests/meshgenerators/cartesian_mesh_generator/gold/cartesian_mesh_3D_in.e
  test/tests/meshgenerators/cartesian_mesh_generator/tests
Labels: PR: Failed but allowed

#12897 Update PetscSupport.C to support PETSc-master
  framework/src/utils/PetscSupport.C
Labels: PR: Failed but allowed

#12771 Support Exodus/output_dimension when using --mesh-only
  framework/include/base/MooseApp.h
  framework/include/mesh/AnnularMesh.h
  framework/include/mesh/DistributedGeneratedMesh.h
  framework/include/mesh/GeneratedMesh.h
  framework/include/mesh/MooseMesh.h
  framework/include/outputs/Exodus.h
  framework/include/outputs/OversampleOutput.h
  framework/include/parser/Syntax.h
  framework/include/utils/DependencyResolver.h
  framework/src/actions/MeshOnlyAction.C
  framework/src/base/MooseApp.C
  framework/src/mesh/AnnularMesh.C
  framework/src/mesh/DistributedGeneratedMesh.C
  framework/src/mesh/GeneratedMesh.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshmodifiers/MeshExtruder.C
  framework/src/outputs/Exodus.C
  framework/src/outputs/OversampleOutput.C
  framework/src/parser/Syntax.C
  test/tests/mesh/distributed_generated_mesh/gold/d1.e
  test/tests/mesh/mesh_only/gold/output_dimension.e
  test/tests/mesh/mesh_only/output_dimension_override.i
  test/tests/mesh/mesh_only/tests
  unit/src/DependencyResolverTest.C
Labels: PR: Failed but allowed

#12887 Actually construct default vector values
  framework/src/interfaces/Coupleable.C
  framework/src/utils/InputParameters.C
  test/include/kernels/EFieldAdvection.h
  test/src/kernels/EFieldAdvection.C
  test/tests/kernels/ad_vector_couple/gold/ad_vector_couple_default_out.e
  test/tests/kernels/ad_vector_couple/tests
  test/tests/kernels/vector_fe/coupled_scalar_default_vector_value.i
  test/tests/kernels/vector_fe/gold/coupled_scalar_default_vector_value_alt_out.e
  test/tests/kernels/vector_fe/gold/coupled_scalar_default_vector_value_out.e
  test/tests/kernels/vector_fe/tests
Labels: PR: Failed but allowed

#12888 Increase test coverage
  framework/doc/content/source/userobject/PerflogDumper.md
  framework/include/markers/QuadraturePointMarker.h
  framework/include/markers/ValueRangeMarker.h
  framework/include/markers/ValueThresholdMarker.h
  framework/include/userobject/PerflogDumper.h
  framework/include/userobject/UserObject.h
  framework/src/markers/QuadraturePointMarker.C
  framework/src/markers/ValueRangeMarker.C
  framework/src/markers/ValueThresholdMarker.C
  framework/src/meshgenerators/AllSideSetsByNormalsGenerator.C
  framework/src/userobject/PerflogDumper.C
  framework/src/userobject/UserObject.C
  test/src/markers/QPointMarker.C
  test/tests/markers/q_point_marker/q_point_marker.i
  test/tests/meshgenerators/add_all_side_sets_generators/gold/less_simple_in.e
  test/tests/meshgenerators/add_all_side_sets_generators/gold/simple_in.e
  test/tests/meshgenerators/add_all_side_sets_generators/less_simple.i
  test/tests/meshgenerators/add_all_side_sets_generators/reactor.e
  test/tests/meshgenerators/add_all_side_sets_generators/simple.i
  test/tests/meshgenerators/add_all_side_sets_generators/tests
  test/tests/meshgenerators/add_all_side_sets_generators/twoblocks.e
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.0
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.1
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.2
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.3
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.0
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.1
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.2
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.3
  test/tests/outputs/nemesis/nemesis_elemental.i
  test/tests/outputs/nemesis/nemesis_scalar.i
  test/tests/outputs/nemesis/tests
  test/tests/outputs/output_on/tests
  test/tests/parser/hit_dump/tests
  unit/src/MathUtilsTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12774 Generate warning when volumetric locking is used with second order el…
  modules/combined/test/tests/contact_verification/hertz_cyl/half_symm_q8/tests
  modules/combined/test/tests/contact_verification/patch_tests/brick_3/brick3_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/brick_3/brick3_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/brick_3/brick3_template2.i
  modules/combined/test/tests/contact_verification/patch_tests/brick_4/brick4_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/brick_4/brick4_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/brick_4/brick4_template2.i
  modules/combined/test/tests/contact_verification/patch_tests/brick_4/tests
  modules/combined/test/tests/contact_verification/patch_tests/cyl_3/cyl3_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/cyl_3/cyl3_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/cyl_3/cyl3_template2.i
  modules/combined/test/tests/contact_verification/patch_tests/cyl_4/cyl4_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/cyl_4/cyl4_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/cyl_4/cyl4_template2.i
  modules/combined/test/tests/contact_verification/patch_tests/plane_3/plane3_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/plane_3/plane3_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/plane_3/plane3_template2.i
  modules/combined/test/tests/contact_verification/patch_tests/plane_4/plane4_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/plane_4/plane4_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/plane_4/plane4_template2.i
  modules/combined/test/tests/contact_verification/patch_tests/ring_3/ring3_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/ring_3/ring3_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/ring_3/ring3_template2.i
  modules/combined/test/tests/contact_verification/patch_tests/ring_4/ring4_mu_0_2_pen.i
  modules/combined/test/tests/contact_verification/patch_tests/ring_4/ring4_template1.i
  modules/combined/test/tests/contact_verification/patch_tests/ring_4/ring4_template2.i
  modules/combined/test/tests/gravity/gold/gravity_hex20_out.e
  modules/combined/test/tests/gravity/gold/gravity_qp_select_out.e
  modules/combined/test/tests/gravity/gold/gravity_rz_quad8_out.e
  modules/combined/test/tests/gravity/gravity_hex20.i
  modules/combined/test/tests/gravity/gravity_hex20_sm.i
  modules/combined/test/tests/gravity/gravity_qp_select.i
  modules/combined/test/tests/gravity/gravity_qp_select_sm.i
  modules/combined/test/tests/gravity/gravity_rz_quad8.i
  modules/combined/test/tests/gravity/gravity_rz_quad8_sm.i
  modules/combined/test/tests/internal_volume/hex20.i
  modules/combined/test/tests/internal_volume/rz_quad8.i
  modules/combined/test/tests/nodal_area/gold/nodal_area_Hex20_3_out.e
  modules/combined/test/tests/nodal_area/nodal_area_Hex20.i
  modules/combined/test/tests/nodal_area/nodal_area_Hex20_3.i
  modules/combined/test/tests/nodal_area/nodal_area_Hex20_3_sm.i
  modules/combined/test/tests/nodal_area/nodal_area_Hex27.i
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/media/tensor_mechanics/cook_problem.png
  modules/tensor_mechanics/doc/content/media/tensor_mechanics/cook_results.png
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/VolumetricLocking.md
  modules/tensor_mechanics/src/kernels/StressDivergenceTensors.C
  modules/tensor_mechanics/src/materials/ComputeStrainBase.C
  modules/tensor_mechanics/test/tests/2D_geometries/tests
  modules/tensor_mechanics/test/tests/elastic_patch/tests
  modules/tensor_mechanics/test/tests/isotropic_elasticity_tensor/tests
  modules/tensor_mechanics/test/tests/volumetric_locking_verification/42_node.i
  modules/tensor_mechanics/test/tests/volumetric_locking_verification/42_node_side.e
  modules/tensor_mechanics/test/tests/volumetric_locking_verification/gold/42_node_no_vol_lock_out.e
  modules/tensor_mechanics/test/tests/volumetric_locking_verification/gold/42_node_out.e
  modules/tensor_mechanics/test/tests/volumetric_locking_verification/tests
Labels: PR: Failed but allowed

#12912 Loosen jacobian tolerances
  test/tests/kernels/jxw_grad_test_dep_on_displacements/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12911 add const qualifiers in GenericFunctionMaterial.h
  framework/include/materials/GenericFunctionMaterial.h
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12885 Implement vaporPressure() in TabulatedFluidProperties
  modules/fluid_properties/include/userobjects/TabulatedFluidProperties.h
  modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
  unit/src/TabulatedFluidPropertiesTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12906 Compute time dependent values for CONST, MONOMIALS on neighbor elements
  framework/doc/content/source/variables/MooseVariableConstantMonomial.md
  framework/src/variables/MooseVariableConstMonomial.C
  test/include/materials/CoupledValuesMaterial.h
  test/src/materials/CoupledValuesMaterial.C
  test/tests/variables/time_derivatives_neighbor/gold/test_out.e
  test/tests/variables/time_derivatives_neighbor/test.i
  test/tests/variables/time_derivatives_neighbor/tests
Labels: PR: Failed but allowed

#12904 Remove unused class
  framework/doc/content/source/multiapps/AutoPositionsMultiApp.md
  framework/include/multiapps/AutoPositionsMultiApp.h
  framework/src/multiapps/AutoPositionsMultiApp.C
  test/tests/multiapps/auto_positions/auto_positions.i
  test/tests/multiapps/auto_positions/gold/auto_positions_out.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos00.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos01.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos02.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos03.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos04.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos05.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos06.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos07.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos08.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos09.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos10.e
  test/tests/multiapps/auto_positions/gold/auto_positions_out_auto_pos11.e
  test/tests/multiapps/auto_positions/sub.i
  test/tests/multiapps/auto_positions/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12917 Various doco related fixes
  python/MooseDocs/commands/verify.py
  python/MooseDocs/extensions/bibtex.py
  python/MooseDocs/test/gold/html/extensions/bibtex.html
  python/MooseDocs/test/gold/json/extensions/bibtex.json
  python/MooseDocs/test/gold/materialize/extensions/bibtex.html
  python/mooseutils/__init__.py
  python/mooseutils/sqa_check.py
  scripts/sqa_check.py
  scripts/tests/test_sqa_check.py
Labels: PR: Failed but allowed

#12899 fluidproperties: add AD support to SinglePhase objects
  framework/include/base/Registry.h
  modules/fluid_properties/include/userobjects/CO2FluidProperties.h
  modules/fluid_properties/include/userobjects/HelmholtzFluidProperties.h
  modules/fluid_properties/include/userobjects/HydrogenFluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/NaClFluidProperties.h
  modules/fluid_properties/include/userobjects/NitrogenFluidProperties.h
  modules/fluid_properties/include/userobjects/SimpleFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/include/userobjects/TabulatedFluidProperties.h
  modules/fluid_properties/include/userobjects/Water97FluidProperties.h
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  unit/include/ADFluidPropsTest.h
  unit/src/ADFluidPropsTest.C
Labels: PR: Failed but allowed

#12922 fix bug from #12899
  framework/include/base/Registry.h
Labels: PR: Ready for Review/Merge

#12924 Skipping test that fails on HPC
  modules/combined/test/tests/contact_verification/patch_tests/ring_3/tests
Labels: PR: Ready for Review/Merge

#12921 Ensure that adCoupledValue called on an aux variable doesn't destroy the Jacobian
  framework/include/variables/MooseVariableFE.h
  framework/src/variables/MooseVariableFE.C
  test/tests/kernels/ad_coupled_value/ad_aux_coupled_value.i
  test/tests/kernels/ad_coupled_value/ad_coupled_value.i
  test/tests/kernels/ad_coupled_value/gold/ad_aux_coupled_value_out.e
  test/tests/kernels/ad_coupled_value/tests
Labels: PR: Failed but allowed

#12928 Dont warn when using adCoupledValue with aux.
  framework/include/variables/MooseVariableFE.h
  test/tests/kernels/ad_coupled_value/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12929 Changes to tests to pass --recover testing
  modules/porous_flow/test/tests/broadbridge_white/gold/rd03.e
  modules/porous_flow/test/tests/broadbridge_white/rd03.i
  modules/porous_flow/test/tests/buckley_leverett/bl01.i
  modules/porous_flow/test/tests/buckley_leverett/gold/bl01.e
  modules/porous_flow/test/tests/dirackernels/bh07.i
  modules/porous_flow/test/tests/dirackernels/tests
  modules/porous_flow/test/tests/dirackernels/theis1.i
  modules/porous_flow/test/tests/dirackernels/theis2.i
  modules/porous_flow/test/tests/dispersion/diff01.i
  modules/porous_flow/test/tests/dispersion/diff01_action.i
  modules/porous_flow/test/tests/dispersion/disp01.i
  modules/porous_flow/test/tests/dispersion/disp01_heavy.i
  modules/porous_flow/test/tests/flux_limited_TVD_advection/fltvd_1D.i
  modules/porous_flow/test/tests/flux_limited_TVD_advection/fltvd_1D_adaptivity.i
  modules/porous_flow/test/tests/flux_limited_TVD_advection/fltvd_2D.i
  modules/porous_flow/test/tests/flux_limited_TVD_advection/fltvd_2D_angle.i
  modules/porous_flow/test/tests/flux_limited_TVD_advection/fltvd_2D_blocks.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/pffltvd_1D.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/pffltvd_1D_adaptivity.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/pffltvd_2D.i
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/pffltvd_2D_angle.i
  modules/porous_flow/test/tests/gravity/grav02a.i
  modules/porous_flow/test/tests/gravity/grav02d.i
  modules/porous_flow/test/tests/numerical_diffusion/fltvd.i
  modules/porous_flow/test/tests/numerical_diffusion/fltvd_no_antidiffusion.i
  modules/porous_flow/test/tests/numerical_diffusion/framework.i
  modules/porous_flow/test/tests/numerical_diffusion/fully_saturated_action.i
  modules/porous_flow/test/tests/numerical_diffusion/no_action.i
  modules/porous_flow/test/tests/numerical_diffusion/pffltvd.i
  modules/porous_flow/test/tests/numerical_diffusion/pffltvd_action.i
  modules/porous_flow/test/tests/pressure_pulse/pressure_pulse_1d_2phasePS.i
  modules/porous_flow/test/tests/pressure_pulse/pressure_pulse_1d_2phasePSVG.i
  modules/porous_flow/test/tests/pressure_pulse/pressure_pulse_1d_2phasePSVG2.i
  modules/porous_flow/test/tests/pressure_pulse/pressure_pulse_1d_2phasePS_KT.i
  modules/porous_flow/test/tests/rogers_stallybrass_clements/gold/rsc01.e
  modules/porous_flow/test/tests/rogers_stallybrass_clements/gold/rsc02.e
  modules/porous_flow/test/tests/rogers_stallybrass_clements/rsc01.i
  modules/porous_flow/test/tests/rogers_stallybrass_clements/rsc02.i
  modules/porous_flow/test/tests/sinks/gold/s10_back.e
  modules/porous_flow/test/tests/sinks/gold/s10_bottom.e
  modules/porous_flow/test/tests/sinks/gold/s10_front.e
  modules/porous_flow/test/tests/sinks/gold/s10_left.e
  modules/porous_flow/test/tests/sinks/gold/s10_right.e
  modules/porous_flow/test/tests/sinks/gold/s10_top.e
  modules/porous_flow/test/tests/sinks/injection_production_eg.i
  modules/porous_flow/test/tests/sinks/s10.i
  modules/porous_flow/test/tests/sinks/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12889 Make displaced mesh an actual copy of the undisplaced
  framework/src/actions/PartitionerAction.C
  framework/src/actions/SetupMeshAction.C
  framework/src/base/MooseApp.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12932 Remove output_dimension from modules tests
  modules/combined/test/tests/gap_heat_transfer_htonly/cyl2D_xz.i
  modules/combined/test/tests/gap_heat_transfer_htonly/cyl2D_yz.i
  modules/combined/test/tests/gap_heat_transfer_htonly/planar_xz.i
  modules/combined/test/tests/gap_heat_transfer_htonly/planar_yz.i
  modules/tensor_mechanics/test/tests/2D_different_planes/gps_xz.i
  modules/tensor_mechanics/test/tests/2D_different_planes/gps_yz.i
  modules/tensor_mechanics/test/tests/2D_different_planes/planestrain_xz.i
  modules/tensor_mechanics/test/tests/2D_different_planes/planestrain_yz.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#12930 Remove one unnecessary mesh adaptation
  framework/include/executioners/Transient.h
  framework/src/executioners/Transient.C
  framework/src/multiapps/TransientMultiApp.C
  framework/src/timesteppers/TimeStepper.C
  test/include/timesteppers/TimeSequenceStepperFailTest.h
  test/src/timesteppers/TimeSequenceStepperFailTest.C
  test/tests/outputs/system_info/tests
Labels: PR: Failed but allowed

#12847 Added verification tests for XFEM moving interface capability
  modules/xfem/test/include/kernels/TestMatTimeDerivative.h
  modules/xfem/test/src/kernels/TestMatTimeDerivative.C
  modules/xfem/test/tests/moving_interface/verification/1D_rz_homog1mat.i
  modules/xfem/test/tests/moving_interface/verification/1D_rz_lsdep1mat.i
  modules/xfem/test/tests/moving_interface/verification/1D_xy_homog1mat.i
  modules/xfem/test/tests/moving_interface/verification/1D_xy_lsdep1mat.i
  modules/xfem/test/tests/moving_interface/verification/2D_rz_homog1mat.i
  modules/xfem/test/tests/moving_interface/verification/2D_rz_lsdep1mat.i
  modules/xfem/test/tests/moving_interface/verification/2D_xy_homog1mat.i
  modules/xfem/test/tests/moving_interface/verification/2D_xy_lsdep1mat.i
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_homog1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_homog1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_homog1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_homog1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_homog1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_lsdep1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_lsdep1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_lsdep1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_lsdep1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/1D_rz_lsdep1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_homog1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_homog1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_homog1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_homog1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_homog1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_lsdep1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_lsdep1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_lsdep1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_lsdep1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/1D_xy_lsdep1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_homog1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_homog1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_homog1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_homog1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_homog1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_lsdep1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_lsdep1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_lsdep1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_lsdep1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/2D_rz_lsdep1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_homog1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_homog1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_homog1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_homog1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_homog1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_lsdep1mat_out.e
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_lsdep1mat_out.e-s002
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_lsdep1mat_out.e-s003
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_lsdep1mat_out.e-s004
  modules/xfem/test/tests/moving_interface/verification/gold/2D_xy_lsdep1mat_out.e-s005
  modules/xfem/test/tests/moving_interface/verification/tests
Labels: PR: Failed but allowed

#12942 Set default for code block heights
  framework/doc/content/css/moose.css
  python/MooseDocs/extensions/core.py
  python/MooseDocs/test/gold/html/extensions/alert.html
  python/MooseDocs/test/gold/html/extensions/appsyntax.html
  python/MooseDocs/test/gold/html/extensions/autolink.html
  python/MooseDocs/test/gold/html/extensions/core.html
  python/MooseDocs/test/gold/html/extensions/devel.html
  python/MooseDocs/test/gold/html/extensions/listing.html
  python/MooseDocs/test/gold/html/extensions/listing_include.html
  python/MooseDocs/test/gold/html/extensions/package.html
  python/MooseDocs/test/gold/html/extensions/sqa.html
  python/MooseDocs/test/gold/materialize/extensions/alert.html
  python/MooseDocs/test/gold/materialize/extensions/appsyntax.html
  python/MooseDocs/test/gold/materialize/extensions/autolink.html
  python/MooseDocs/test/gold/materialize/extensions/core.html
  python/MooseDocs/test/gold/materialize/extensions/devel.html
  python/MooseDocs/test/gold/materialize/extensions/example.template.html
  python/MooseDocs/test/gold/materialize/extensions/listing.html
  python/MooseDocs/test/gold/materialize/extensions/listing_include.html
  python/MooseDocs/test/gold/materialize/extensions/package.html
  python/MooseDocs/test/gold/materialize/extensions/sqa.html
  python/MooseDocs/test/gold/materialize/extensions/template.html
Labels: PR: Auto Merge, PR: Failed but allowed

#12955 Free the comm in MemoryUsageReporter
  framework/src/postprocessors/MemoryUsageReporter.C
Labels: PR: Auto Merge

#12963 Add dashes to update_and_rebuild_petsc.sh script
  scripts/update_and_rebuild_petsc.sh
Labels: PR: Failed but allowed

#12967 AD BrineFluidProperties
  modules/fluid_properties/include/userobjects/BrineFluidProperties.h
  modules/fluid_properties/include/userobjects/FluidProperties.h
  modules/fluid_properties/include/userobjects/MultiComponentFluidProperties.h
  modules/fluid_properties/include/userobjects/MultiComponentFluidPropertiesPT.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/src/userobjects/BrineFluidProperties.C
  modules/fluid_properties/src/userobjects/FluidProperties.C
  modules/fluid_properties/src/userobjects/MultiComponentFluidProperties.C
  modules/fluid_properties/src/userobjects/MultiComponentFluidPropertiesPT.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/test/include/materials/MultiComponentFluidPropertiesMaterialPT.h
  modules/fluid_properties/test/src/materials/MultiComponentFluidPropertiesMaterialPT.C
  modules/porous_flow/src/materials/PorousFlowBrine.C
  modules/porous_flow/src/userobjects/PorousFlowBrineCO2.C
  unit/src/BrineFluidPropertiesTest.C
  unit/src/PorousFlowBrineCO2Test.C
Labels: PR: Failed but allowed

#12965 Move _elasticity_tensor from ComputeStressBase to derived classes
  modules/tensor_mechanics/include/materials/ADComputeFiniteStrainElasticStress.h
  modules/tensor_mechanics/include/materials/ADComputeLinearElasticStress.h
  modules/tensor_mechanics/include/materials/ADComputeStressBase.h
  modules/tensor_mechanics/include/materials/ComputeCosseratLinearElasticStress.h
  modules/tensor_mechanics/include/materials/ComputeFiniteStrainElasticStress.h
  modules/tensor_mechanics/include/materials/ComputeLinearElasticStress.h
  modules/tensor_mechanics/include/materials/ComputeMultiPlasticityStress.h
  modules/tensor_mechanics/include/materials/ComputeMultipleInelasticStress.h
  modules/tensor_mechanics/include/materials/ComputePFFractureStressBase.h
  modules/tensor_mechanics/include/materials/ComputeStrainIncrementBasedStress.h
  modules/tensor_mechanics/include/materials/ComputeStressBase.h
  modules/tensor_mechanics/include/materials/FiniteStrainCrystalPlasticity.h
  modules/tensor_mechanics/include/materials/FiniteStrainHyperElasticViscoPlastic.h
  modules/tensor_mechanics/include/materials/FiniteStrainPlasticMaterial.h
  modules/tensor_mechanics/include/materials/FiniteStrainUObasedCP.h
  modules/tensor_mechanics/src/materials/ADComputeFiniteStrainElasticStress.C
  modules/tensor_mechanics/src/materials/ADComputeLinearElasticStress.C
  modules/tensor_mechanics/src/materials/ADComputeStressBase.C
  modules/tensor_mechanics/src/materials/ComputeCosseratLinearElasticStress.C
  modules/tensor_mechanics/src/materials/ComputeFiniteStrainElasticStress.C
  modules/tensor_mechanics/src/materials/ComputeLinearElasticStress.C
  modules/tensor_mechanics/src/materials/ComputeMultiPlasticityStress.C
  modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
  modules/tensor_mechanics/src/materials/ComputePFFractureStressBase.C
  modules/tensor_mechanics/src/materials/ComputeStrainIncrementBasedStress.C
  modules/tensor_mechanics/src/materials/ComputeStressBase.C
  modules/tensor_mechanics/src/materials/FiniteStrainCrystalPlasticity.C
  modules/tensor_mechanics/src/materials/FiniteStrainHyperElasticViscoPlastic.C
  modules/tensor_mechanics/src/materials/FiniteStrainPlasticMaterial.C
  modules/tensor_mechanics/src/materials/FiniteStrainUObasedCP.C
Labels: PR: Failed but allowed
