Repository idaholab/moose, pull requests merged in 2019-12, with the labels that each got.

#14395 Move convective heat flux side integral from Pronghorn
  modules/heat_conduction/doc/content/source/postprocessors/ConvectiveHeatTransferSideIntegral.md
  modules/heat_conduction/include/postprocessors/ConvectiveHeatTransferSideIntegral.h
  modules/heat_conduction/src/postprocessors/ConvectiveHeatTransferSideIntegral.C
  modules/heat_conduction/test/tests/postprocessors/convective_ht_side_integral.i
  modules/heat_conduction/test/tests/postprocessors/gold/convective_ht_side_integral_out.csv
  modules/heat_conduction/test/tests/postprocessors/tests
Labels: PR: Failed but allowed

#14466 fix material property AD bugs
  framework/include/materials/MaterialProperty.h
  framework/include/utils/MooseADWrapper.h
  framework/src/utils/MooseADWrapper.C
Labels: PR: Auto Merge, PR: Failed but allowed

#14400 Allowing MultiAppCopyTransfer to handle multiple variables and array variables as input
  framework/include/transfers/MultiAppConservativeTransfer.h
  framework/include/transfers/MultiAppCopyTransfer.h
  framework/include/transfers/MultiAppFieldTransfer.h
  framework/include/transfers/MultiAppInterpolationTransfer.h
  framework/include/transfers/MultiAppMeshFunctionTransfer.h
  framework/include/transfers/MultiAppNearestNodeTransfer.h
  framework/include/transfers/MultiAppProjectionTransfer.h
  framework/include/transfers/MultiAppUserObjectTransfer.h
  framework/src/transfers/MultiAppConservativeTransfer.C
  framework/src/transfers/MultiAppCopyTransfer.C
  framework/src/transfers/MultiAppFieldTransfer.C
  framework/src/transfers/MultiAppInterpolationTransfer.C
  framework/src/transfers/MultiAppMeshFunctionTransfer.C
  framework/src/transfers/MultiAppNearestNodeTransfer.C
  framework/src/transfers/MultiAppProjectionTransfer.C
  framework/src/transfers/MultiAppTransfer.C
  framework/src/transfers/MultiAppUserObjectTransfer.C
  test/tests/transfers/multiapp_copy_transfer/array_variable_transfer/gold/master_out.e
  test/tests/transfers/multiapp_copy_transfer/array_variable_transfer/gold/master_out_sub0.e
  test/tests/transfers/multiapp_copy_transfer/array_variable_transfer/master.i
  test/tests/transfers/multiapp_copy_transfer/array_variable_transfer/sub.i
  test/tests/transfers/multiapp_copy_transfer/array_variable_transfer/tests
  test/tests/transfers/multiapp_copy_transfer/aux_to_aux/tests
  test/tests/transfers/multiapp_copy_transfer/multivariable_copy/gold/master_out.e
  test/tests/transfers/multiapp_copy_transfer/multivariable_copy/gold/master_out_sub0.e
  test/tests/transfers/multiapp_copy_transfer/multivariable_copy/master.i
  test/tests/transfers/multiapp_copy_transfer/multivariable_copy/sub.i
  test/tests/transfers/multiapp_copy_transfer/multivariable_copy/tests
Labels: PR: Failed but allowed

#14461 File base cleanup
  framework/include/base/MooseApp.h
  framework/include/outputs/FileOutput.h
  framework/src/base/MooseApp.C
  framework/src/multiapps/MultiApp.C
  framework/src/outputs/FileOutput.C
  framework/src/problems/FEProblemBase.C
  modules/fluid_properties/src/actions/AddFluidPropertiesInterrogatorAction.C
  modules/level_set/test/tests/transfers/markers/single_level/gold/master_out_sub0.e
  modules/level_set/test/tests/transfers/markers/single_level/gold/master_out_sub0_out.e
  modules/level_set/test/tests/transfers/markers/single_level/tests
  test/tests/multiapps/loose_couple_time_adapt/gold/begin_dummy0.e
  test/tests/multiapps/loose_couple_time_adapt/gold/end_dummy0.e
  test/tests/multiapps/loose_couple_time_adapt/tests
  test/tests/multiapps/multilevel/tests
  test/tests/multiapps/picard_multilevel/gold/picard_master_out_extra_sub10.e
  test/tests/multiapps/picard_multilevel/gold/picard_master_out_extra_sub10_sub20.e
  test/tests/multiapps/picard_multilevel/tests
  test/tests/restart/restart_subapp_not_master/two_step_solve_sub_restart.i
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_diff_out_diff_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_interpolation_out_interpolation_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_nearest_node_out_nearest_node_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/tests
  test/tests/transfers/multiapp_projection_transfer/gold/tosub_master_out_sub0_out.e
  test/tests/transfers/multiapp_projection_transfer/gold/tosub_master_out_sub1_out.e
  test/tests/transfers/multiapp_projection_transfer/tests
  test/tests/transfers/transfer_on_final/gold/master_out_sub0_final.e
  test/tests/transfers/transfer_on_final/tests
Labels: PR: Failed but allowed

#14478 Warn about empty TM master actions
  modules/tensor_mechanics/include/actions/CommonTensorMechanicsAction.h
  modules/tensor_mechanics/src/actions/CommonTensorMechanicsAction.C
  modules/tensor_mechanics/test/tests/action/no_block.i
  modules/tensor_mechanics/test/tests/action/tests
Labels: PR: Failed but allowed

#14154 Add PETSc SNES divergence tolerance support
  framework/include/problems/FEProblemBase.h
  framework/include/problems/ReferenceResidualProblem.h
  framework/src/executioners/FEProblemSolve.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/ReferenceResidualProblem.C
  framework/src/utils/PetscSupport.C
  modules/contact/include/problems/AugmentedLagrangianContactProblem.h
  modules/contact/src/problems/AugmentedLagrangianContactProblem.C
  test/tests/executioners/nl_divergence_tolerance/gold/nl_divergence_tolerance_out.e
  test/tests/executioners/nl_divergence_tolerance/nl_divergence_tolerance.i
  test/tests/executioners/nl_divergence_tolerance/tests
Labels: PR: Failed but allowed

#14477 Remove old SQA tools
  framework/doc/sqa/DOEbwlogo.pdf
  framework/doc/sqa/INLreport.cls
  framework/doc/sqa/Makefile
  framework/doc/sqa/README
  framework/doc/sqa/SoftwareRequirements.tex
  framework/doc/sqa/inl-left_black.pdf
  scripts/traceability_matrix.py
Labels: PR: Failed but allowed

#14483 Fix typos (outputing/outputting)
  framework/doc/content/source/outputs/Exodus.md
  framework/doc/content/source/utils/PerfGraph.md
  framework/doc/content/syntax/Mesh/index.md
  framework/include/outputs/Checkpoint.h
  framework/include/outputs/Exodus.h
  framework/include/outputs/GMVOutput.h
  framework/include/outputs/Nemesis.h
  framework/include/outputs/Tecplot.h
  framework/include/outputs/XDA.h
  framework/include/utils/PetscSupport.h
  framework/src/outputs/Output.C
  framework/src/outputs/OversampleOutput.C
  modules/phase_field/examples/rigidbodymotion/AC_CH_advection_constforce_rect.i
Labels: PR: Failed but allowed

#14481 Added SmoothMultiBoundingBoxBaseIC and two new ICs that inherit from …
  modules/phase_field/doc/content/media/phase_field/isolated_bounding_box.png
  modules/phase_field/doc/content/media/phase_field/nested_bounding_box.png
  modules/phase_field/doc/content/source/ics/IsolatedBoundingBoxIC.md
  modules/phase_field/doc/content/source/ics/NestedBoundingBoxIC.md
  modules/phase_field/include/ics/IsolatedBoundingBoxIC.h
  modules/phase_field/include/ics/NestedBoundingBoxIC.h
  modules/phase_field/include/ics/SmoothMultiBoundingBoxBaseIC.h
  modules/phase_field/src/ics/IsolatedBoundingBoxIC.C
  modules/phase_field/src/ics/NestedBoundingBoxIC.C
  modules/phase_field/src/ics/SmoothMultiBoundingBoxBaseIC.C
  modules/phase_field/test/tests/initial_conditions/IsolatedBoundingBoxIC_2D.i
  modules/phase_field/test/tests/initial_conditions/IsolatedBoundingBoxIC_2D_Overlapping.i
  modules/phase_field/test/tests/initial_conditions/IsolatedBoundingBoxIC_3D.i
  modules/phase_field/test/tests/initial_conditions/NestedBoundingBoxIC_2D.i
  modules/phase_field/test/tests/initial_conditions/NestedBoundingBoxIC_3D.i
  modules/phase_field/test/tests/initial_conditions/gold/IsolatedBoundingBoxIC_2D_Overlapping_out.e
  modules/phase_field/test/tests/initial_conditions/gold/IsolatedBoundingBoxIC_2D_out.e
  modules/phase_field/test/tests/initial_conditions/gold/IsolatedBoundingBoxIC_3D_out.e
  modules/phase_field/test/tests/initial_conditions/gold/NestedBoundingBoxIC_2D_out.e
  modules/phase_field/test/tests/initial_conditions/gold/NestedBoundingBoxIC_3D_out.e
  modules/phase_field/test/tests/initial_conditions/tests
Labels: PR: Failed but allowed

#14496 Skip tensor rotations for isotropic plasticity models
  modules/tensor_mechanics/include/materials/CappedDruckerPragerStressUpdate.h
  modules/tensor_mechanics/include/materials/CappedMohrCoulombStressUpdate.h
  modules/tensor_mechanics/include/materials/ComputeMultipleInelasticStress.h
  modules/tensor_mechanics/include/materials/RadialReturnStressUpdate.h
  modules/tensor_mechanics/include/materials/StressUpdateBase.h
  modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
Labels: PR: Failed but allowed

#14497 Remove an extraneous file
  modules/tensor_mechanics/test/tests/1D_axisymmetric/asdf.i
Labels: PR: Failed but allowed

#14479 Create logic that handles changes in ThreadPool._state between 3.7 and 3.8
  python/TestHarness/schedulers/Scheduler.py
Labels: PR: Failed but allowed

#14494 Fix a bug in clone_master_mesh plus uniform refinement
  framework/src/actions/SetupMeshCompleteAction.C
  test/tests/multiapps/picard/gold/picard_master_out_sub0.e
  test/tests/multiapps/picard/picard_master.i
  test/tests/multiapps/picard/tests
Labels: PR: Failed but allowed

#14424 Rename few input parameters in our old eigen
  framework/include/executioners/InversePowerMethod.h
  framework/include/executioners/NonlinearEigen.h
  framework/src/executioners/EigenExecutionerBase.C
  framework/src/executioners/FEProblemSolve.C
  framework/src/executioners/InversePowerMethod.C
  framework/src/executioners/NonlinearEigen.C
  test/tests/executioners/eigen_executioners/ane.i
  test/tests/executioners/eigen_executioners/ne.i
  test/tests/executioners/eigen_executioners/ne_coupled.i
  test/tests/executioners/eigen_executioners/ne_deficient_b.i
  test/tests/executioners/eigen_executioners/ne_mat.i
Labels: PR: Auto Merge, PR: Failed but allowed, PR: Ready for Review/Merge

#14509 Fix import error for anytree
  python/moosetree/tests/test_Node.py
Labels: PR: Auto Merge

#14467 Improve error message in DependencyResolver during insert
  framework/include/utils/DependencyResolver.h
Labels: PR: Ready for Review/Merge

#14469 set initial conditions and aux kernel values consistently
  framework/doc/content/syntax/ICs/index.md
  framework/include/ics/InitialConditionTempl.h
  framework/include/variables/MooseVariableData.h
  framework/include/variables/MooseVariableFE.h
  framework/src/ics/InitialConditionTempl.C
  framework/src/loops/ComputeInitialConditionThread.C
  framework/src/variables/MooseVariableData.C
  framework/src/variables/MooseVariableFE.C
  modules/heat_conduction/test/tests/gray_lambert_radiator/coupled_heat_conduction.i
  modules/heat_conduction/test/tests/meshed_gap_thermal_contact/gold/meshed_gap_thermal_contact_constant_conductance_quadrature_out.e
  modules/heat_conduction/test/tests/meshed_gap_thermal_contact/meshed_annulus_thermal_contact.i
  modules/heat_conduction/test/tests/meshed_gap_thermal_contact/meshed_gap_thermal_contact.i
  modules/heat_conduction/test/tests/meshed_gap_thermal_contact/meshed_gap_thermal_contact_constant_conductance.i
  test/tests/kernels/ad_transient_diffusion/ad_transient_vector_diffusion.i
  test/tests/kernels/ad_transient_diffusion/tests
  test/tests/kernels/transient_vector_diffusion/tests
  test/tests/kernels/transient_vector_diffusion/transient_vector_diffusion.i
  test/tests/mesh/named_entities/gold/named_entities_test_out.e
  test/tests/mesh/named_entities/gold/named_entities_test_xda_out.e
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14219 Enable cohesive zone modelling
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/index.md
  modules/tensor_mechanics/doc/content/source/actions/CohesiveZoneMasterAction.md
  modules/tensor_mechanics/doc/content/source/interfacekernels/CZMInterfaceKernel.md
  modules/tensor_mechanics/doc/content/source/materials/czm/SalehaniIrani3DCTraction.md
  modules/tensor_mechanics/doc/content/syntax/Modules/TensorMechanics/CohesiveZoneMaster/index.md
  modules/tensor_mechanics/include/actions/CohesiveZoneMasterAction.h
  modules/tensor_mechanics/include/interfacekernels/CZMInterfaceKernel.h
  modules/tensor_mechanics/include/materials/czm/CZMMaterialBase.h
  modules/tensor_mechanics/include/materials/czm/SalehaniIrani3DCTraction.h
  modules/tensor_mechanics/src/actions/CohesiveZoneMasterAction.C
  modules/tensor_mechanics/src/base/TensorMechanicsApp.C
  modules/tensor_mechanics/src/interfacekernels/CZMInterfaceKernel.C
  modules/tensor_mechanics/src/materials/czm/CZMMaterialBase.C
  modules/tensor_mechanics/src/materials/czm/SalehaniIrani3DCTraction.C
  modules/tensor_mechanics/test/tests/czm/czm_3DC_3D_base_input.i
  modules/tensor_mechanics/test/tests/czm/gold/czm_3DC_load_complex_out.e
  modules/tensor_mechanics/test/tests/czm/gold/czm_3DC_load_only_normal_1D_out.e
  modules/tensor_mechanics/test/tests/czm/gold/czm_3DC_load_only_normal_2D_out.e
  modules/tensor_mechanics/test/tests/czm/gold/czm_3DC_load_only_normal_3D_out.e
  modules/tensor_mechanics/test/tests/czm/gold/czm_3DC_load_shear_y_out.e
  modules/tensor_mechanics/test/tests/czm/gold/czm_3DC_load_shear_z_out.e
  modules/tensor_mechanics/test/tests/czm/tests
Labels: PR: Failed but allowed

#14520 Remove deprecated parameter
  modules/tensor_mechanics/test/tests/material_limit_time_step/creep/nafems_test5a_lim.i
Labels: PR: Auto Merge

#14288 Add tests for reading ABAQUS input file
  test/tests/mesh/abaqus_input/gold/testcube_elem_id_in.e
  test/tests/mesh/abaqus_input/gold/testcube_elset_name_in.e
  test/tests/mesh/abaqus_input/gold/testcube_elset_name_ws_in.e
  test/tests/mesh/abaqus_input/testcube_elem_id.i
  test/tests/mesh/abaqus_input/testcube_elem_id_in.inp
  test/tests/mesh/abaqus_input/testcube_elset_name.i
  test/tests/mesh/abaqus_input/testcube_elset_name_in.inp
  test/tests/mesh/abaqus_input/testcube_elset_name_ws.i
  test/tests/mesh/abaqus_input/testcube_elset_name_ws_in.inp
  test/tests/mesh/abaqus_input/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14524 Remove potential race condition from Sampler tests
  test/tests/samplers/base/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#14415 RANFS for contact
  framework/include/constraints/NodeFaceConstraint.h
  framework/include/executioners/FEProblemSolve.h
  framework/include/geomsearch/GeometricSearchData.h
  framework/include/linesearches/LineSearch.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/include/utils/MooseTypes.h
  framework/src/constraints/NodeFaceConstraint.C
  framework/src/executioners/FEProblemSolve.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/Conversion.C
  framework/src/utils/PetscSupport.C
  modules/contact/doc/content/modules/contact/index.md
  modules/contact/doc/content/source/constraints/RANFSNormalMechanicalContact.md
  modules/contact/include/constraints/MechanicalContactConstraint.h
  modules/contact/include/constraints/RANFSNormalMechanicalContact.h
  modules/contact/include/linesearches/PetscProjectSolutionOntoBounds.h
  modules/contact/src/constraints/MechanicalContactConstraint.C
  modules/contact/src/constraints/RANFSNormalMechanicalContact.C
  modules/contact/src/linesearches/PetscProjectSolutionOntoBounds.C
  modules/contact/test/include/constraints/RANFSTieNode.h
  modules/contact/test/src/constraints/RANFSTieNode.C
  modules/contact/test/tests/bouncing-block-contact/bouncing-block-ranfs.cmp
  modules/contact/test/tests/bouncing-block-contact/bouncing-block-ranfs.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-nodal-reduced-active-set.i
  modules/contact/test/tests/bouncing-block-contact/gold/bouncing-block-coarse.e
  modules/contact/test/tests/bouncing-block-contact/gold/bouncing-block-ranfs_exo.e
  modules/contact/test/tests/bouncing-block-contact/gold/ranfs-dont-project-amg.e
  modules/contact/test/tests/bouncing-block-contact/gold/ranfs-dont-project-svd.e
  modules/contact/test/tests/bouncing-block-contact/gold/ranfs-project-amg.e
  modules/contact/test/tests/bouncing-block-contact/gold/ranfs-project-svd.e
  modules/contact/test/tests/bouncing-block-contact/gold/tied-nodes_exo.e
  modules/contact/test/tests/bouncing-block-contact/long-bottom-block-no-lower-d-coarse.e
  modules/contact/test/tests/bouncing-block-contact/long-bottom-block-no-lower-d-coarse.jou
  modules/contact/test/tests/bouncing-block-contact/long-bottom-block-no-lower-d.e
  modules/contact/test/tests/bouncing-block-contact/long-bottom-block-no-lower-d.jou
  modules/contact/test/tests/bouncing-block-contact/long-bottom-block-symmetric-single-element.e
  modules/contact/test/tests/bouncing-block-contact/long-bottom-block-symmetric-single-element.jou
  modules/contact/test/tests/bouncing-block-contact/square-blocks-no-offset.e
  modules/contact/test/tests/bouncing-block-contact/square-blocks-no-offset.jou
  modules/contact/test/tests/bouncing-block-contact/tests
  modules/contact/test/tests/bouncing-block-contact/tied-nodes.i
Labels: PR: Ready for Review/Merge

#14522 Finish up the RTM for the framework
  framework/doc/content/sqa/assumptions_and_dependencies.md
  framework/doc/content/sqa/framework_rtm.md
  framework/doc/content/sqa/framework_srs.md
  framework/doc/content/sqa/minimum_requirements.md
  framework/doc/content/sqa/system_purpose.md
  framework/doc/content/sqa/system_scope.md
  framework/doc/content/templates/sqa/rtm.md.template
  modules/doc/content/getting_started/installation/centos.md
  modules/doc/content/getting_started/installation/fedora.md
  modules/doc/content/getting_started/installation/macos_catalina.md
  modules/doc/content/getting_started/installation/macos_mojave.md
  modules/doc/content/getting_started/installation/macos_other.md
  modules/doc/content/getting_started/installation/manual_installation_gcc.md
  modules/doc/content/getting_started/installation/manual_installation_llvm.md
  modules/doc/content/getting_started/installation/mint.md
  modules/doc/content/getting_started/installation/opensuse.md
  modules/doc/content/getting_started/installation/ubuntu.md
Labels: PR: Ready for Review/Merge

#14528 Fix cohesive zone model parallel tests
  modules/tensor_mechanics/test/tests/czm/tests
Labels: PR: Failed but allowed

#14529 Attempt at fixing failing heavy tests
  modules/combined/test/tests/sliding_block/in_and_out/constraint/frictionless_kinematic_out.cmp
  modules/combined/test/tests/sliding_block/in_and_out/constraint/frictionless_lm.i
  modules/combined/test/tests/sliding_block/in_and_out/constraint/gold/frictionless_lm_out.e
  modules/combined/test/tests/sliding_block/in_and_out/constraint/sm/frictional_lm_sm.i
  modules/combined/test/tests/sliding_block/in_and_out/constraint/sm/frictionless_lm_sm.i
  modules/combined/test/tests/sliding_block/in_and_out/constraint/sm/gold/frictional_lm_sm_out.e
  modules/combined/test/tests/sliding_block/in_and_out/constraint/sm/gold/frictionless_lm_sm_out.e
  modules/combined/test/tests/sliding_block/in_and_out/constraint/sm/sliding_elastic_blocks_2d.e
  modules/combined/test/tests/sliding_block/in_and_out/constraint/sm/tests
  modules/combined/test/tests/sliding_block/in_and_out/constraint/tests
  modules/combined/test/tests/sliding_block/in_and_out/dirac/sm/tests
  modules/combined/test/tests/sliding_block/in_and_out/dirac/tests
  modules/combined/test/tests/sliding_block/sliding/constraint/sm/sliding_elastic_blocks_2d.e
  modules/combined/test/tests/sliding_block/sliding/constraint/sm/tests
  modules/combined/test/tests/sliding_block/sliding/constraint/tests
  modules/combined/test/tests/sliding_block/sliding/dirac/frictional_02_penalty.i
  modules/combined/test/tests/sliding_block/sliding/dirac/gold/frictional_02_penalty_out.e
  modules/combined/test/tests/sliding_block/sliding/dirac/sm/frictional_02_penalty_sm.i
  modules/combined/test/tests/sliding_block/sliding/dirac/sm/gold/frictional_02_penalty_sm_exodus.e
  modules/combined/test/tests/sliding_block/sliding/dirac/sm/tests
  modules/combined/test/tests/sliding_block/sliding/dirac/tests
Labels: PR: Failed but allowed

#14530 Add ability to format/add/remove nodes and parameters from python hit
  framework/contrib/hit/chit.pxd
  framework/contrib/hit/hit.pyx
  framework/contrib/hit/hit3.cpp
  framework/contrib/hit/parse.cc
  framework/contrib/hit/parse.h
  python/mooseutils/hit_load.py
  python/mooseutils/tests/test_hit_load.py
Labels: PR: Failed but allowed

#14535 Feature 14532
  docker_ci/Jenkinsfile
Labels: PR: Failed but allowed

#14516 Add conda instructions
  modules/doc/content/getting_started/installation/conda.md
  modules/doc/content/getting_started/installation/remove_moose_environment.md
  modules/doc/content/getting_started/installation/test_moose.md
Labels: PR: Failed but allowed

#14523 Side set heat transfer model
  framework/include/dgkernels/DGKernelBase.h
  framework/src/dgkernels/DGKernelBase.C
  modules/heat_conduction/doc/content/source/interfacekernels/SideSetHeatTransferKernel.md
  modules/heat_conduction/doc/content/source/materials/SideSetHeatTransferMaterial.md
  modules/heat_conduction/include/interfacekernels/SideSetHeatTransferKernel.h
  modules/heat_conduction/include/materials/SideSetHeatTransferMaterial.h
  modules/heat_conduction/src/interfacekernels/SideSetHeatTransferKernel.C
  modules/heat_conduction/src/materials/SideSetHeatTransferMaterial.C
  modules/heat_conduction/test/tests/sideset_heat_transfer/cfem_gap.i
  modules/heat_conduction/test/tests/sideset_heat_transfer/gap_thermal_1D.i
  modules/heat_conduction/test/tests/sideset_heat_transfer/gap_thermal_ktemp_1D.i
  modules/heat_conduction/test/tests/sideset_heat_transfer/gold/cfem_gap_out.e
  modules/heat_conduction/test/tests/sideset_heat_transfer/gold/gap_thermal_1D_Tbulk_var.e
  modules/heat_conduction/test/tests/sideset_heat_transfer/gold/gap_thermal_1D_out.e
  modules/heat_conduction/test/tests/sideset_heat_transfer/gold/gap_thermal_ktemp_1D_out.e
  modules/heat_conduction/test/tests/sideset_heat_transfer/tests
Labels: PR: Failed but allowed

#14542 Add MONOMIAL_VEC support to MOOSE
  framework/include/auxkernels/VectorVariableComponentAux.h
  framework/include/base/Assembly.h
  framework/src/actions/AddAuxVariableAction.C
  framework/src/actions/AddVariableAction.C
  framework/src/auxkernels/VectorVariableComponentAux.C
  framework/src/base/Assembly.C
  framework/src/outputs/AdvancedOutput.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/systems/SystemBase.C
  framework/src/utils/Conversion.C
  framework/src/variables/MooseVariableBase.C
  framework/src/variables/MooseVariableData.C
  tutorials/darcy_thermo_mech/step04_velocity_aux/include/auxkernels/DarcyVelocity.h
  tutorials/darcy_thermo_mech/step04_velocity_aux/problems/step4.i
  tutorials/darcy_thermo_mech/step04_velocity_aux/src/auxkernels/DarcyVelocity.C
  tutorials/darcy_thermo_mech/step04_velocity_aux/tests/auxkernels/velocity_aux/tests
  tutorials/darcy_thermo_mech/step04_velocity_aux/tests/auxkernels/velocity_aux/velocity_aux.cmp
  tutorials/darcy_thermo_mech/step04_velocity_aux/tests/auxkernels/velocity_aux/velocity_aux.i
  tutorials/darcy_thermo_mech/step05_heat_conduction/tests/auxkernels/velocity_aux/velocity_aux.cmp
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/problems/step6a_coupled.i
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/problems/step6b_transient_inflow.i
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/tests/auxkernels/velocity_aux/velocity_aux.cmp
  tutorials/darcy_thermo_mech/step07_adaptivity/problems/step7a_coarse.i
  tutorials/darcy_thermo_mech/step07_adaptivity/problems/step7b_fine.i
  tutorials/darcy_thermo_mech/step07_adaptivity/problems/step7c_adapt.i
  tutorials/darcy_thermo_mech/step07_adaptivity/problems/step7d_adapt_blocks.i
  tutorials/darcy_thermo_mech/step07_adaptivity/tests/auxkernels/velocity_aux/velocity_aux.cmp
  tutorials/darcy_thermo_mech/step08_postprocessors/problems/step8.i
  tutorials/darcy_thermo_mech/step08_postprocessors/tests/auxkernels/velocity_aux/velocity_aux.cmp
  tutorials/darcy_thermo_mech/step09_mechanics/problems/step9.i
  tutorials/darcy_thermo_mech/step09_mechanics/tests/auxkernels/velocity_aux/velocity_aux.cmp
  tutorials/darcy_thermo_mech/step10_multiapps/problems/step10.i
  tutorials/darcy_thermo_mech/step10_multiapps/tests/auxkernels/velocity_aux/velocity_aux.cmp
  tutorials/darcy_thermo_mech/step11_action/src/actions/SetupDarcySimulation.C
  tutorials/darcy_thermo_mech/step11_action/tests/auxkernels/velocity_aux/velocity_aux.cmp
Labels: PR: Failed but allowed

#14404 Fix for hanging parallel solve due to exception
  framework/include/loops/ThreadedElementLoopBase.h
  framework/src/loops/ComputeJacobianForScalingThread.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/AuxiliarySystem.C
  modules/combined/test/include/materials/ADPowerLawCreepExceptionTest.h
  modules/combined/test/include/materials/PowerLawCreepExceptionTest.h
  modules/combined/test/src/materials/ADPowerLawCreepExceptionTest.C
  modules/combined/test/src/materials/PowerLawCreepExceptionTest.C
  modules/combined/test/tests/exception/ad.i
  modules/combined/test/tests/exception/mesh.e
  modules/combined/test/tests/exception/mesh.jou
  modules/combined/test/tests/exception/nonad.i
  modules/combined/test/tests/exception/tests
  modules/tensor_mechanics/src/materials/ADPowerLawCreepStressUpdate.C
  test/tests/materials/material/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#14526 Vectors of mixed PPs and Reals
  framework/include/interfaces/PostprocessorInterface.h
  framework/include/postprocessors/LinearCombinationPostprocessor.h
  framework/include/userobject/GeneralUserObject.h
  framework/include/utils/InputParameters.h
  framework/src/interfaces/PostprocessorInterface.C
  framework/src/parser/Parser.C
  framework/src/postprocessors/LinearCombinationPostprocessor.C
  framework/src/userobject/GeneralUserObject.C
  framework/src/utils/InputParameters.C
  test/tests/postprocessors/linear_combination/gold/linear_combination_defaulted_pps.csv
  test/tests/postprocessors/linear_combination/tests
Labels: PR: Failed but allowed

#14485 Plane stress improvements
  modules/tensor_mechanics/doc/content/source/kernels/StressDivergenceTensors.md
  modules/tensor_mechanics/doc/content/source/kernels/WeakPlaneStress.md
  modules/tensor_mechanics/doc/content/source/materials/ComputePlaneFiniteStrain.md
  modules/tensor_mechanics/doc/content/source/materials/ComputePlaneIncrementalStrain.md
  modules/tensor_mechanics/doc/content/source/materials/ComputePlaneSmallStrain.md
  modules/tensor_mechanics/doc/content/syntax/Modules/TensorMechanics/Master/index.md
  modules/tensor_mechanics/include/actions/TensorMechanicsAction.h
  modules/tensor_mechanics/include/kernels/StressDivergenceTensors.h
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
  modules/tensor_mechanics/src/kernels/StressDivergenceTensors.C
  modules/tensor_mechanics/test/tests/plane_stress/3D_finite_tension_pull.i
  modules/tensor_mechanics/test/tests/plane_stress/gold/3D_finite_tension_pull_out.csv
  modules/tensor_mechanics/test/tests/plane_stress/gold/weak_plane_stress_finite_out.e
  modules/tensor_mechanics/test/tests/plane_stress/gold/weak_plane_stress_finite_tension_pull_out.csv
  modules/tensor_mechanics/test/tests/plane_stress/gold/weak_plane_stress_small_out.e
  modules/tensor_mechanics/test/tests/plane_stress/tests
  modules/tensor_mechanics/test/tests/plane_stress/weak_plane_stress_elastic_jacobian.i
  modules/tensor_mechanics/test/tests/plane_stress/weak_plane_stress_finite.i
  modules/tensor_mechanics/test/tests/plane_stress/weak_plane_stress_finite_tension_pull.i
  modules/tensor_mechanics/test/tests/plane_stress/weak_plane_stress_incremental.i
  modules/tensor_mechanics/test/tests/plane_stress/weak_plane_stress_small.i
Labels: PR: Failed but allowed

#14221 Refactor PiecewiseBase add coarsened tabulated linear function
  framework/doc/content/source/functions/CoarsenedPiecewiseLinear.md
  framework/doc/content/source/vectorpostprocessors/PiecewiseFunctionTabulate.md
  framework/include/functions/CoarsenedPiecewiseLinear.h
  framework/include/functions/Piecewise.h
  framework/include/functions/PiecewiseBase.h
  framework/include/functions/PiecewiseConstant.h
  framework/include/functions/PiecewiseLinear.h
  framework/include/functions/PiecewiseLinearBase.h
  framework/include/utils/PointReduction.h
  framework/include/vectorpostprocessors/PiecewiseFunctionTabulate.h
  framework/src/functions/CoarsenedPiecewiseLinear.C
  framework/src/functions/Piecewise.C
  framework/src/functions/PiecewiseBase.C
  framework/src/functions/PiecewiseConstant.C
  framework/src/functions/PiecewiseLinear.C
  framework/src/functions/PiecewiseLinearBase.C
  framework/src/timesteppers/FunctionDT.C
  framework/src/utils/PointReduction.C
  framework/src/vectorpostprocessors/PiecewiseFunctionTabulate.C
  test/tests/functions/coarsened_piecewise_linear/coarsened_piecewise_linear.i
  test/tests/functions/coarsened_piecewise_linear/generate_data.py
  test/tests/functions/coarsened_piecewise_linear/gold/coarsened_piecewise_linear_vpp_F_0000.csv
  test/tests/functions/coarsened_piecewise_linear/tests
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed
