Repository idaholab/moose, pull requests merged in 2019-04, with the labels that each got.

#13159 Fix the Jacobian for SoretDiffusion
  modules/phase_field/src/kernels/SoretDiffusion.C
Labels: PR: Auto Merge

#13172 Adds the derivatives of surface tension sigma.
  modules/fluid_properties/include/userobjects/TwoPhaseFluidProperties.h
  modules/fluid_properties/src/userobjects/TwoPhaseFluidProperties.C
  modules/fluid_properties/test/include/utils/SinglePhaseFluidPropertiesTestUtils.h
Labels: PR: Auto Merge

#13120 Add full-solve type sampler multi-app
  framework/include/samplers/Sampler.h
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/monte_carlo.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/index.md
  modules/stochastic_tools/doc/content/source/multiapps/SamplerFullSolveMultiApp.md
  modules/stochastic_tools/doc/content/source/multiapps/SamplerMultiApp.md
  modules/stochastic_tools/doc/content/source/multiapps/SamplerTransientMultiApp.md
  modules/stochastic_tools/include/multiapps/SamplerFullSolveMultiApp.h
  modules/stochastic_tools/include/multiapps/SamplerTransientMultiApp.h
  modules/stochastic_tools/include/transfers/SamplerPostprocessorTransfer.h
  modules/stochastic_tools/include/transfers/SamplerTransfer.h
  modules/stochastic_tools/include/vectorpostprocessors/StochasticResults.h
  modules/stochastic_tools/src/multiapps/SamplerFullSolveMultiApp.C
  modules/stochastic_tools/src/multiapps/SamplerTransientMultiApp.C
  modules/stochastic_tools/src/transfers/SamplerPostprocessorTransfer.C
  modules/stochastic_tools/src/transfers/SamplerTransfer.C
  modules/stochastic_tools/src/vectorpostprocessors/StochasticResults.C
  modules/stochastic_tools/test/tests/multiapps/sampler_multiapp/master_full_solve.i
  modules/stochastic_tools/test/tests/multiapps/sampler_multiapp/master_transient.i
  modules/stochastic_tools/test/tests/multiapps/sampler_multiapp/sub.i
  modules/stochastic_tools/test/tests/multiapps/sampler_multiapp/tests
  modules/stochastic_tools/test/tests/transfers/errors/master_missing_control.i
  modules/stochastic_tools/test/tests/transfers/errors/master_num_parameters_wrong.i
  modules/stochastic_tools/test/tests/transfers/errors/master_wrong_control.i
  modules/stochastic_tools/test/tests/transfers/errors/tests
  modules/stochastic_tools/test/tests/transfers/monte_carlo.i
  modules/stochastic_tools/test/tests/transfers/sampler_postprocessor/errors/require_stochastic_results.i
  modules/stochastic_tools/test/tests/transfers/sampler_postprocessor/errors/tests
  modules/stochastic_tools/test/tests/transfers/sampler_postprocessor/master.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/errors/master_missing_control.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/errors/master_num_parameters_wrong.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/errors/master_wrong_control.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/errors/tests
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/monte_carlo.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/sobol.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/master.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/master_not_enough_data.i
  modules/stochastic_tools/test/tests/transfers/sampler_transfer_vector/master_size_mismatch.i
  modules/stochastic_tools/test/tests/transfers/sobol.i
Labels: PR: Auto Merge, PR: Failed but allowed

#13183 Added post-processor for querying BoundaryFlux objects
  modules/rdg/doc/content/source/postprocessors/BoundaryFluxPostprocessor.md
  modules/rdg/include/postprocessors/BoundaryFluxPostprocessor.h
  modules/rdg/src/postprocessors/BoundaryFluxPostprocessor.C
  modules/rdg/test/include/userobjects/TestBoundaryFlux.h
  modules/rdg/test/src/userobjects/TestBoundaryFlux.C
  modules/rdg/test/tests/postprocessors/boundary_flux_postprocessor/boundary_flux_postprocessor.i
  modules/rdg/test/tests/postprocessors/boundary_flux_postprocessor/gold/boundary_flux_postprocessor_out.csv
  modules/rdg/test/tests/postprocessors/boundary_flux_postprocessor/tests
Labels: PR: Auto Merge

#13201 Ghosting fixes
  framework/include/actions/Action.h
  framework/include/actions/MooseObjectAction.h
  framework/src/actions/Action.C
  framework/src/actions/CreateDisplacedProblemAction.C
  framework/src/actions/MooseObjectAction.C
  framework/src/dgkernels/ADDGKernel.C
  framework/src/dgkernels/DGKernel.C
  framework/src/dgkernels/DGKernelBase.C
Labels: PR: Failed but allowed

#13205 Delete remote elements if its needed
  framework/include/mesh/MooseMesh.h
  framework/src/actions/Action.C
  framework/src/actions/AddRelationshipManager.C
  framework/src/actions/CreateDisplacedProblemAction.C
  framework/src/actions/SetupMeshCompleteAction.C
  framework/src/base/Moose.C
  framework/src/mesh/MooseMesh.C
Labels: PR: Failed but allowed

#13206 Ghost uo improvements
  framework/doc/content/source/actions/DisplayGhostingAction.md
  framework/doc/content/source/auxkernels/GhostingAux.md
  framework/doc/content/source/userobject/GhostingUserObject.md
  framework/include/actions/DisplayGhostingAction.h
  framework/include/auxkernels/AuxKernel.h
  framework/include/auxkernels/AuxScalarKernel.h
  framework/include/auxkernels/GhostingAux.h
  framework/include/userobject/GhostingUserObject.h
  framework/src/actions/DisplayGhostingAction.C
  framework/src/auxkernels/GhostingAux.C
  framework/src/base/Moose.C
  framework/src/outputs/ConsoleUtils.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/userobject/GhostingUserObject.C
  modules/phase_field/include/auxkernels/FeatureFloodCountAux.h
  test/tests/auxkernels/ghosting_aux/ghosting_aux.i
  test/tests/auxkernels/ghosting_aux/gold/ghosting_aux_out.e
  test/tests/auxkernels/ghosting_aux/gold/ghosting_aux_with_local_out.e
  test/tests/auxkernels/ghosting_aux/gold/no_ghosting_out.e
  test/tests/auxkernels/ghosting_aux/no_ghosting.i
  test/tests/auxkernels/ghosting_aux/tests
  test/tests/relationship_managers/two_rm/gold/two_rm_dist_out.e
  test/tests/relationship_managers/two_rm/gold/two_rm_out.e
  test/tests/relationship_managers/two_rm/tests
  test/tests/relationship_managers/two_rm/two_rm.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13213 Update peacock test for changes to input file
  python/peacock/tests/input_tab/InputTree/test_InputTree.py
Labels: PR: Auto Merge

#13176 Some cleanups in MooseVariableFE for ArrayKernel
  framework/include/variables/MooseVariableBase.h
  framework/include/variables/MooseVariableFE.h
  framework/include/variables/MooseVariableFEBase.h
  framework/include/variables/MooseVariableScalar.h
  framework/src/variables/MooseVariableFE.C
  framework/src/variables/MooseVariableScalar.C
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
Labels: PR: Auto Merge, PR: Failed but allowed, PR: Ready for Review/Merge

#13215 Fixing error with minimum compiler version
  modules/phase_field/src/kernels/ADACInterface.C
Labels: PR: Failed but allowed

#13209 Consistent tensor rank in example 3 equations
  modules/doc/content/examples/ex03_coupling.md
Labels: PR: Failed but allowed

#13220 Support offscreen matplotlib plots in mms module
  python/mms/__init__.py
Labels: PR: Failed but allowed

#13222 disallow empty field values for HIT
  framework/contrib/hit/lex.cc
  framework/contrib/hit/parse.cc
  framework/src/outputs/formatters/InputFileFormatter.C
  framework/src/outputs/formatters/JsonInputFileFormatter.C
  modules/functional_expansion_tools/test/tests/standard_use/tests
  test/tests/mesh/no_mesh_block/tests
  test/tests/misc/app_name/tests
  test/tests/multiapps/time_offset/tests
  unit/src/HitTests.C
Labels: PR: Failed but allowed

#13229 Minor fixes of comparisons, efficiency for ReplicatedMesh
  framework/include/relationshipmanagers/ElementSideNeighborLayers.h
  framework/include/relationshipmanagers/RelationshipManager.h
  framework/src/base/MooseApp.C
  framework/src/relationshipmanagers/ElementPointNeighborLayers.C
  framework/src/relationshipmanagers/ElementSideNeighborLayers.C
  framework/src/relationshipmanagers/MooseGhostPointNeighbors.C
  modules/phase_field/src/postprocessors/GrainTracker.C
  modules/phase_field/src/userobjects/PolycrystalUserObjectBase.C
  test/tests/auxkernels/ghosting_aux/gold/no_ghosting_out.e
  test/tests/relationship_managers/two_rm/gold/two_rm_out.e
Labels: PR: Ready for Review/Merge

#13241 We don't use this function anymore
  python/mooseutils/__init__.py
  python/mooseutils/mooseutils.py
  python/mooseutils/tests/test_check_file_size.py
  python/mooseutils/tests/tests
Labels: PR: Auto Merge

#13238 Allow more than one registerMooseObjectRenamed in an application
  framework/include/base/Registry.h
Labels: PR: Ready for Review/Merge

#13246 Cleanup FEProblemBase a bit
  framework/src/problems/FEProblemBase.C
Labels: PR: Auto Merge

#13248 Add doco for explaining a requirement
  modules/doc/content/bib/sqa.bib
  modules/doc/content/python/MooseDocs/generate.md
  modules/doc/content/sqa/index.md
  modules/doc/content/sqa/what_is_a_requirement.md
Labels: PR: Auto Merge

#13234 Fixed tests for petsc-3.9.{0,1,2,3}
  modules/combined/test/tests/thermal_elastic/tests
  modules/heat_conduction/test/tests/ad_heat_conduction/tests
  modules/heat_conduction/test/tests/heat_source_bar/tests
  modules/heat_conduction/test/tests/verify_against_analytical/tests
  modules/misc/test/tests/kernels/diffusion/tests
  modules/misc/test/tests/kernels/thermo_diffusion/tests
  modules/navier_stokes/test/tests/ins/jacobian_test/tests
  modules/phase_field/test/tests/phase_field_kernels/tests
  modules/tensor_mechanics/test/tests/ad_action/tests
  modules/tensor_mechanics/test/tests/ad_linear_elasticity/tests
  modules/tensor_mechanics/test/tests/ad_plastic/tests
  modules/tensor_mechanics/test/tests/creep_tangent_operator/tests
  modules/tensor_mechanics/test/tests/gravity/tests
  python/TestHarness/testers/PetscJacobianTester.py
  test/tests/dgkernels/jacobian_testing/tests
  test/tests/interfacekernels/1d_interface/tests
  test/tests/interfacekernels/2d_interface/tests
  test/tests/misc/jacobian/tests
  test/tests/preconditioners/fdp/tests
Labels: PR: Failed but allowed

#13259 Some minor cleanups during working on array kernel
  framework/include/interfaces/Coupleable.h
  framework/include/utils/MooseTypes.h
  framework/include/variables/MooseVariableFE.h
  framework/src/interfaces/Coupleable.C
Labels: PR: Auto Merge

#13257 Create AuxVectorKernel
  examples/ex02_kernel/ex02.i
  examples/ex10_aux/ex10.i
  framework/doc/content/js/init.js
  framework/doc/content/source/auxkernels/VectorFunctionAux.md
  framework/doc/content/syntax/AuxKernels/index.md
  framework/doc/content/syntax/AuxVariables/index.md
  framework/doc/content/syntax/Variables/index.md
  framework/doc/hidden.yml
  framework/include/auxkernels/AuxKernel.h
  framework/include/auxkernels/VectorFunctionAux.h
  framework/include/loops/ComputeElemAuxBcsThread.h
  framework/include/loops/ComputeElemAuxVarsThread.h
  framework/include/loops/ComputeNodalAuxBcsThread.h
  framework/include/loops/ComputeNodalAuxVarsThread.h
  framework/include/systems/AuxiliarySystem.h
  framework/include/variables/MooseVariableFE.h
  framework/include/variables/MooseVariableFEBase.h
  framework/src/actions/AddAuxVariableAction.C
  framework/src/auxkernels/AuxKernel.C
  framework/src/auxkernels/VectorFunctionAux.C
  framework/src/base/Moose.C
  framework/src/loops/ComputeElemAuxBcsThread.C
  framework/src/loops/ComputeElemAuxVarsThread.C
  framework/src/loops/ComputeIndicatorThread.C
  framework/src/loops/ComputeMarkerThread.C
  framework/src/loops/ComputeNodalAuxBcsThread.C
  framework/src/loops/ComputeNodalAuxVarsThread.C
  framework/src/loops/ComputeNodalKernelBCJacobiansThread.C
  framework/src/loops/ComputeNodalKernelBcsThread.C
  framework/src/loops/ComputeNodalKernelJacobiansThread.C
  framework/src/loops/ComputeNodalKernelsThread.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/systems/SystemBase.C
  framework/src/variables/MooseVariableFE.C
  modules/doc/content/examples/ex02_kernel.md
  modules/doc/content/tutorials/darcy_thermo_mech/index.md
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/navigation.py
  python/MooseDocs/test/gold/html/extensions/appsyntax.html
  python/MooseDocs/test/gold/latex/extensions/appsyntax.tex
  python/MooseDocs/test/gold/materialize/extensions/appsyntax.html
  python/MooseDocs/test/gold/materialize/extensions/autolink.html
  python/MooseDocs/test/gold/materialize/extensions/bibtex.html
  python/MooseDocs/test/gold/materialize/extensions/content.html
  python/MooseDocs/test/gold/materialize/extensions/core.html
  python/MooseDocs/test/gold/materialize/extensions/devel.html
  python/MooseDocs/test/gold/materialize/extensions/example.template.html
  python/MooseDocs/test/gold/materialize/extensions/katex.html
  python/MooseDocs/test/gold/materialize/extensions/listing.html
  python/MooseDocs/test/gold/materialize/extensions/media.html
  python/MooseDocs/test/gold/materialize/extensions/table.html
  python/MooseDocs/test/gold/materialize/extensions/template.html
  python/MooseDocs/test/gold/materialize/mega.menu.html
  test/tests/auxkernels/vector_function_aux/gold/vector_function_aux_out.e
  test/tests/auxkernels/vector_function_aux/tests
  test/tests/auxkernels/vector_function_aux/vector_function_aux.i
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/problems/step6c_decoupled.i
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/problems/tests
Labels: PR: Ready for Review/Merge

#13269 Small patch for enabling Picard iteration for the old eigen executioner
  framework/src/executioners/PicardSolve.C
Labels: PR: Auto Merge

#13273 Fix PETSc/SLEPc version logic
  python/TestHarness/testers/Tester.py
  python/TestHarness/util.py
Labels: PR: Auto Merge, PR: Failed but allowed

#13287 Remove deprecated incremental_form parameter for eigenstrain models
  modules/tensor_mechanics/src/materials/ComputeEigenstrainBase.C
Labels: PR: Ready for Review/Merge

#13147 Updating package version
  modules/doc/content/getting_started/installation/bash_profile.md
  modules/doc/content/getting_started/installation/centos.md
  modules/doc/content/getting_started/installation/fedora.md
  modules/doc/content/getting_started/installation/install_moose.md
  modules/doc/content/getting_started/installation/mint.md
  modules/doc/content/getting_started/installation/opensuse.md
  modules/doc/content/getting_started/installation/post_package_install.md
  modules/doc/content/getting_started/installation/ubuntu.md
  package_version
Labels: PR: Failed but allowed

#13299 Add support for known functions to be included in MMS evaluation
  modules/doc/content/python/mms.md
  python/mms/ConvergencePlot.py
  python/mms/evaluate.py
  python/mms/runner.py
  python/mms/test/test_mms.py
  python/mooseutils/mooseutils.py
Labels: PR: Auto Merge

#13291 Removing IsParamValid usage after intialization in dynamic inertial force computations
  modules/tensor_mechanics/include/kernels/InertialForce.h
  modules/tensor_mechanics/include/kernels/InertialForceBeam.h
  modules/tensor_mechanics/include/materials/ComputeIncrementalBeamStrain.h
  modules/tensor_mechanics/include/nodalkernels/NodalGravity.h
  modules/tensor_mechanics/include/nodalkernels/NodalRotationalInertia.h
  modules/tensor_mechanics/include/nodalkernels/NodalTranslationalInertia.h
  modules/tensor_mechanics/src/kernels/InertialForce.C
  modules/tensor_mechanics/src/kernels/InertialForceBeam.C
  modules/tensor_mechanics/src/materials/ComputeIncrementalBeamStrain.C
  modules/tensor_mechanics/src/nodalkernels/NodalGravity.C
  modules/tensor_mechanics/src/nodalkernels/NodalRotationalInertia.C
  modules/tensor_mechanics/src/nodalkernels/NodalTranslationalInertia.C
Labels: PR: Ready for Review/Merge

#13315 Fix SLEPc include guard in the .C file
  framework/include/utils/SlepcSupport.h
  framework/src/utils/SlepcSupport.C
Labels: PR: Auto Merge, PR: Failed but allowed

#13321 `get_repo_revision.py` generates `#pragma once`
  framework/scripts/get_repo_revision.py
Labels: PR: Failed but allowed

#13319 Misc fracture_flow test now passes in parallel
  modules/misc/test/tests/fracture_flow/gold/single_out.e
  modules/misc/test/tests/fracture_flow/gold/single_quick_out.e
  modules/misc/test/tests/fracture_flow/single.i
  modules/misc/test/tests/fracture_flow/single_quick.i
  modules/misc/test/tests/fracture_flow/tests
  modules/porous_flow/doc/content/modules/porous_flow/flow_through_fractured_media.md
Labels: PR: Failed but allowed

#13324 Sort status results by exit_code
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/util.py
Labels: PR: Failed but allowed
