Repository idaholab/moose, pull requests merged in 2019-06, with the labels that each got.

#13512 fix compile time warning
  framework/src/utils/RankTwoTensor.C
Labels: PR: Failed but allowed

#13510 Resolve issues with polynomial order truncation in LeastSquaresFit
  framework/doc/content/source/vectorpostprocessors/LeastSquaresFit.md
  framework/doc/content/source/vectorpostprocessors/LeastSquaresFitHistory.md
  framework/include/vectorpostprocessors/LeastSquaresFit.h
  framework/include/vectorpostprocessors/LeastSquaresFitHistory.h
  framework/src/utils/PolynomialFit.C
  framework/src/vectorpostprocessors/LeastSquaresFit.C
  framework/src/vectorpostprocessors/LeastSquaresFitHistory.C
  test/tests/vectorpostprocessors/least_squares_fit/fit_data_0.csv
  test/tests/vectorpostprocessors/least_squares_fit/fit_data_1.csv
  test/tests/vectorpostprocessors/least_squares_fit/fit_data_2.csv
  test/tests/vectorpostprocessors/least_squares_fit/gold/csv0_least_squares_fit_coeffs_0000.csv
  test/tests/vectorpostprocessors/least_squares_fit/gold/csv1_least_squares_fit_coeffs_0000.csv
  test/tests/vectorpostprocessors/least_squares_fit/gold/csv2_least_squares_fit_coeffs_0000.csv
  test/tests/vectorpostprocessors/least_squares_fit/least_squares_fit_csv_data.i
  test/tests/vectorpostprocessors/least_squares_fit/tests
Labels: PR: Failed but allowed

#13479 Test creating a heterogeneous material using values from a mesh
  modules/porous_flow/test/tests/heterogeneous_materials/constant_poroperm3.i
  modules/porous_flow/test/tests/heterogeneous_materials/tests
Labels: PR: Failed but allowed

#13503 Add CoupledVarNeumannBC
  framework/doc/content/source/bcs/CoupledVarNeumannBC.md
  framework/include/bcs/CoupledVarNeumannBC.h
  framework/src/bcs/CoupledVarNeumannBC.C
  test/tests/bcs/coupled_var_neumann/coupled_var_neumann.i
  test/tests/bcs/coupled_var_neumann/gold/coupled_var_neumann_out.e
  test/tests/bcs/coupled_var_neumann/tests
Labels: PR: Failed but allowed

#13477 MultiParameterPlasticityStressUpdate now works with DiracKernels
  modules/porous_flow/test/tests/dirackernels/gold/injection_with_plasticity_out.e
  modules/porous_flow/test/tests/dirackernels/injection_with_plasticity.i
  modules/porous_flow/test/tests/dirackernels/tests
  modules/porous_flow/test/tests/dirackernels/two_nodes.bh
  modules/tensor_mechanics/src/materials/MultiParameterPlasticityStressUpdate.C
Labels: PR: Failed but allowed

#13514 abs_zero set so test succeeds in paralel
  modules/porous_flow/test/tests/dirackernels/gold/injection_with_plasticity_out.e
  modules/porous_flow/test/tests/dirackernels/injection_with_plasticity.i
  modules/porous_flow/test/tests/dirackernels/tests
Labels: PR: Auto Merge

#13501 New test for reference residual and perf graph to demonstrate usage
  modules/combined/test/tests/reference_residual/gold/reference_residual_perfgraph_out.csv
  modules/combined/test/tests/reference_residual/reference_residual_perfgraph.i
  modules/combined/test/tests/reference_residual/tests
Labels: PR: Failed but allowed

#13465 Restart tests reorg
  framework/doc/content/source/kernels/BodyForce.md
  framework/doc/content/syntax/ICs/index.md
  test/tests/ics/from_exodus_solution/elem_part1.i
  test/tests/ics/from_exodus_solution/elem_part2.i
  test/tests/ics/from_exodus_solution/gold/elem_part1_out.e
  test/tests/ics/from_exodus_solution/gold/elem_part2_out.e
  test/tests/ics/from_exodus_solution/gold/out_nodal_part1.e
  test/tests/ics/from_exodus_solution/gold/out_nodal_var_restart.e
  test/tests/ics/from_exodus_solution/nodal_part1.i
  test/tests/ics/from_exodus_solution/nodal_part2.i
  test/tests/ics/from_exodus_solution/tests
  test/tests/restart/restart/tests
  test/tests/restart/restart_add_variable/add_variable_restart.i
  test/tests/restart/restart_add_variable/gold/add_variable_restart_out.e
  test/tests/restart/restart_add_variable/gold/transient_with_stateful_out.e
  test/tests/restart/restart_add_variable/tests
  test/tests/restart/restart_add_variable/transient_with_stateful.i
  test/tests/restart/restart_refined_mesh/README
  test/tests/restart/restart_refined_mesh/bad1.i
  test/tests/restart/restart_refined_mesh/bad2.i
  test/tests/restart/restart_steady_from_transient/gold/steady_from_transient_restart_out.e
  test/tests/restart/restart_steady_from_transient/gold/transient_out.e
  test/tests/restart/restart_steady_from_transient/steady_from_transient_restart.i
  test/tests/restart/restart_steady_from_transient/tests
  test/tests/restart/restart_steady_from_transient/transient.i
  test/tests/restart/restart_transient_from_steady/gold/restart_from_steady_out.e
  test/tests/restart/restart_transient_from_steady/gold/steady_out.e
  test/tests/restart/restart_transient_from_steady/restart_from_steady.i
  test/tests/restart/restart_transient_from_steady/steady.i
  test/tests/restart/restart_transient_from_steady/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13485 Add ADMatReaction
  modules/heat_conduction/include/kernels/ADHeatConduction.h
  modules/phase_field/doc/content/source/kernels/ADMatReaction.md
  modules/phase_field/include/kernels/ADMatReaction.h
  modules/phase_field/src/kernels/ADMatReaction.C
  modules/phase_field/test/include/materials/ADTestDerivativeFunction.h
  modules/phase_field/test/src/materials/ADTestDerivativeFunction.C
  modules/phase_field/test/tests/automatic_differentiation/admatreaction.i
  modules/phase_field/test/tests/automatic_differentiation/gold/admatreaction_out.e
  modules/phase_field/test/tests/automatic_differentiation/tests
Labels: PR: Failed but allowed

#13517 Made changes to sqa.py to improve V&V report.
  modules/doc/content/sqa/verification/parsed_function_verification.md
  python/MooseDocs/common/get_requirements.py
  python/MooseDocs/extensions/sqa.py
  test/tests/functions/parsed/tests
Labels: C: Documentation, P: minor, PR: Auto Merge, PR: Failed but allowed

#13433 Avoid accumlation of supplied command line arguments
  framework/include/parser/CommandLine.h
  framework/include/parser/Parser.h
  framework/src/multiapps/MultiApp.C
  framework/src/parser/CommandLine.C
  unit/src/CommandLine.C
Labels: PR: Auto Merge

#13519 Fix logic bug in missing design file check
  python/MooseDocs/extensions/sqa.py
Labels: PR: Failed but allowed

#13506 June 2019 News
  modules/doc/content/newsletter/2019_06.md
  modules/doc/content/newsletter/2019_07.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#13416 Create tools for unit testing MOOSEDocs extensions
  modules/doc/moosedocs.py
  python/MooseDocs/base/readers.py
  python/MooseDocs/base/renderers.py
  python/MooseDocs/test/__init__.py
  python/MooseDocs/test/gold/html/extensions/sqa.html
  python/MooseDocs/test/gold/latex/extensions/package.tex
  python/MooseDocs/test/gold/latex/extensions/sqa.tex
  python/MooseDocs/test/gold/materialize/extensions/sqa.html
  python/MooseDocs/test/unit/test_core.py
  python/MooseDocs/test/unit/tests
  python/MooseDocs/tree/html.py
  python/MooseDocs/tree/pages.py
Labels: PR: Ready for Review/Merge

#13538 Add missing explicit instantiation
  framework/src/utils/DenseMatrixDualReal.C
Labels: PR: Auto Merge

#13543 Fixing up SQA commit
  test/tests/mesh/periodic_node_map/tests
Labels: PR: Auto Merge

#13557 Fix possible race condition
  modules/Makefile
Labels: PR: Ready for Review/Merge

#13558 Update the RankMap to use the new Communicator split_by_type
  framework/src/utils/RankMap.C
Labels: PR: Ready for Review/Merge

#13535 Created the robust race conditions checker.
  python/TestHarness/FileChecker.py
  python/TestHarness/JobDAG.py
  python/TestHarness/RaceChecker.py
  python/TestHarness/StatusSystem.py
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/schedulers/Scheduler.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/test_RaceConditions.py
  python/TestHarness/tests/tests
  python/TestHarness/util.py
  python/contrib/dag/__init__.py
  test/tests/controls/time_periods/dampers/tests
  test/tests/interfacekernels/1d_interface/tests
  test/tests/kernels/jxw_grad_test_dep_on_displacements/tests
  test/tests/misc/check_error/tests
  test/tests/mortar/continuity-2d-non-conforming/tests
  test/tests/mortar/displaced-gap-conductance-2d-non-conforming/tests
  test/tests/mortar/gap-conductance-2d-non-conforming/tests
  test/tests/multiapps/picard/tests
  test/tests/outputs/console/tests
  test/tests/test_harness/output_clobber_different_extensions
  test/tests/test_harness/output_clobber_many
  test/tests/test_harness/output_clobber_simple
  test/tests/test_harness/output_clobber_skips
  test/tests/test_harness/output_csv_and_exodus.i
  test/tests/time_integrators/actually_explicit_euler/diverged.i
  test/tests/transfers/multiapp_copy_transfer/errors/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13563 Add interval parameter to adaptivity
  framework/src/actions/SetAdaptivityOptionsAction.C
  test/tests/adaptivity/interval/adapt_interval.i
  test/tests/adaptivity/interval/gold/adapt_interval_out.e
  test/tests/adaptivity/interval/gold/adapt_interval_out.e-s003
  test/tests/adaptivity/interval/tests
Labels: PR: Failed but allowed

#13536 Removes GeneralVaporMixtureFluidProperties class
  modules/fluid_properties/doc/content/documentation/systems/Modules/FluidProperties/GeneralVaporMixtureFluidProperties.md
  modules/fluid_properties/doc/content/source/userobjects/GeneralVaporMixtureFluidProperties.md
  modules/fluid_properties/include/userobjects/GeneralVaporMixtureFluidProperties.h
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/src/userobjects/GeneralVaporMixtureFluidProperties.C
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  modules/fluid_properties/test/src/userobjects/TestTwoPhaseNCGFluidProperties.C
  modules/fluid_properties/test/tests/fp_interrogator/tests
  modules/fluid_properties/test/tests/fp_interrogator/vapor_mixture_rho_e.i
  unit/include/GeneralVaporMixtureFluidPropertiesTest.h
  unit/src/GeneralVaporMixtureFluidPropertiesTest.C
Labels: PR: Auto Merge, PR: Failed but allowed

#13568 Remove deprecated objects
  modules/stochastic_tools/include/state_sim/StateProcessor.h
  modules/stochastic_tools/src/state_sim/StateProcessor.C
Labels: PR: Auto Merge, PR: Failed but allowed

#13566 Add html style comments to comment extension and improve testing
  python/MooseDocs/commands/build.py
  python/MooseDocs/common/load_config.py
  python/MooseDocs/extensions/comment.py
  python/MooseDocs/test/gold/html/extensions/sqa.html
  python/MooseDocs/test/gold/latex/extensions/acronym.tex
  python/MooseDocs/test/gold/latex/extensions/package.tex
  python/MooseDocs/test/gold/latex/extensions/sqa.tex
  python/MooseDocs/test/gold/materialize/extensions/sqa.html
  python/MooseDocs/test/unit/test_comment.py
  python/MooseDocs/test/unit/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#13572 Cache property name and return by reference
  framework/include/utils/FunctionMaterialPropertyDescriptor.h
  framework/src/utils/FunctionMaterialPropertyDescriptor.C
Labels: PR: Failed but allowed

#13571 Improving the templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: PR: Failed but allowed

#13547 Automatic scaling
  examples/ex01_inputfile/src/base/ExampleApp.C
  examples/ex15_actions/src/base/ExampleApp.C
  framework/include/base/MooseApp.h
  framework/include/loops/ComputeJacobianForScalingThread.h
  framework/include/loops/ThreadedElementLoopBase.h
  framework/include/problems/FEProblemBase.h
  framework/include/systems/NonlinearSystem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/include/systems/SystemBase.h
  framework/src/base/Assembly.C
  framework/src/base/MooseApp.C
  framework/src/executioners/Executioner.C
  framework/src/executioners/FEProblemSolve.C
  framework/src/loops/ComputeJacobianForScalingThread.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  modules/chemical_reactions/src/base/ChemicalReactionsApp.C
  modules/combined/src/base/CombinedApp.C
  modules/contact/src/base/ContactApp.C
  modules/doc/content/application_usage/failed_solves.md
  modules/functional_expansion_tools/src/base/FunctionalExpansionToolsApp.C
  modules/level_set/src/base/LevelSetApp.C
  modules/navier_stokes/src/base/NavierStokesApp.C
  modules/phase_field/src/base/PhaseFieldApp.C
  modules/porous_flow/src/base/PorousFlowApp.C
  modules/rdg/src/base/RdgApp.C
  modules/richards/src/base/RichardsApp.C
  modules/solid_mechanics/src/base/SolidMechanicsApp.C
  modules/tensor_mechanics/src/base/TensorMechanicsApp.C
  modules/xfem/src/base/XFEMApp.C
  test/src/base/MooseTestApp.C
  test/tests/kernels/bad_scaling_scalar_kernels/gold/ill_conditioned_field_scalar_system_out.e
  test/tests/kernels/bad_scaling_scalar_kernels/ill_conditioned_field_scalar_system.i
  test/tests/kernels/bad_scaling_scalar_kernels/tests
  test/tests/kernels/simple_transient_diffusion/gold/ill_conditioned_simple_diffusion_out.e
  test/tests/kernels/simple_transient_diffusion/gold/transient.e
  test/tests/kernels/simple_transient_diffusion/ill_conditioned_simple_diffusion.i
  test/tests/kernels/simple_transient_diffusion/tests
  tutorials/darcy_thermo_mech/step01_diffusion/src/base/DarcyThermoMechApp.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13553 Create PorousFlowHeatMassTransfer Kernel
  modules/porous_flow/doc/content/source/kernels/PorousFlowHeatMassTransfer.md
  modules/porous_flow/include/kernels/PorousFlowHeatMassTransfer.h
  modules/porous_flow/src/kernels/PorousFlowHeatMassTransfer.C
  modules/porous_flow/test/tests/heat_mass_transfer/gold/variable_transfer_0D_out.csv
  modules/porous_flow/test/tests/heat_mass_transfer/gold/variable_transfer_variable_0D_out.csv
  modules/porous_flow/test/tests/heat_mass_transfer/tests
  modules/porous_flow/test/tests/heat_mass_transfer/variable_transfer_0D.i
  modules/porous_flow/test/tests/heat_mass_transfer/variable_transfer_variable_0D.i
Labels: PR: Failed but allowed

#13577 Add missing using declarations
  modules/tensor_mechanics/include/materials/ADIsotropicPlasticityStressUpdate.h
Labels: PR: Failed but allowed

#13586 Fix broken package links
  modules/doc/content/getting_started/installation/centos_pre_req.md
  modules/doc/content/getting_started/installation/fedora_pre_req.md
  modules/doc/content/getting_started/installation/mac_pre_req.md
  modules/doc/content/getting_started/installation/manual_gcc.md
  modules/doc/content/getting_started/installation/manual_llvm.md
  modules/doc/content/getting_started/installation/manual_mpich_gcc.md
  modules/doc/content/getting_started/installation/manual_mpich_llvm.md
  modules/doc/content/getting_started/installation/manual_petsc.md
  modules/doc/content/getting_started/installation/mint_pre_req.md
  modules/doc/content/getting_started/installation/opensuse_pre_req.md
  modules/doc/content/getting_started/installation/ubuntu_pre_req.md
  modules/doc/content/getting_started/minimum_requirements.md
  modules/doc/content/python/MooseDocs/extensions/package.md
Labels: PR: Auto Merge

#13367 Add special treatment for piecewise linear funcs.
  framework/include/timesteppers/IterationAdaptiveDT.h
  framework/src/timesteppers/IterationAdaptiveDT.C
  modules/combined/test/tests/adaptive_timestepping/gold/adapt_tstep_function_change_out.e
  modules/combined/test/tests/adaptive_timestepping/gold/adapt_tstep_function_change_restart2_out.e
  test/tests/time_steppers/iteration_adaptive/gold/piecewise_linear_out.csv
  test/tests/time_steppers/iteration_adaptive/gold/piecewise_linear_out.e
  test/tests/time_steppers/iteration_adaptive/piecewise_linear.i
  test/tests/time_steppers/iteration_adaptive/tests
Labels: PR: Failed but allowed

#13604 TimedPrint patch for Valgrind and min compiler failures
  framework/include/utils/StreamArguments.h
  framework/include/utils/TimedPrint.h
  framework/src/outputs/Console.C
  framework/src/systems/NonlinearSystemBase.C
Labels: PR: Auto Merge, PR: Failed but allowed, PR: Ready for Review/Merge

#13597 Better error missing side sets and node sets
  framework/doc/content/source/mesh/MooseMesh.md
  framework/src/interfaces/BoundaryRestrictable.C
  test/tests/mesh/node_list_from_side_list/tests
  test/tests/mesh/side_list_from_node_list/gold/side_list_from_node_list_out.e
  test/tests/mesh/side_list_from_node_list/mesh_journal.jou
  test/tests/mesh/side_list_from_node_list/side_list_from_node_list.i
  test/tests/mesh/side_list_from_node_list/square_nodesets_only.e
  test/tests/mesh/side_list_from_node_list/tests
  test/tests/restrictable/undefined_ids/tests
Labels: PR: Ready for Review/Merge

#13606 Keep bib entries in the correct order.
  python/MooseDocs/extensions/bibtex.py
Labels: PR: Auto Merge

#13602 Added base_name parameter to Density material class. Made all module base_name patterns constant.
  modules/heat_conduction/include/materials/ElectricalConductivity.h
  modules/heat_conduction/include/materials/SemiconductorLinearConductivity.h
  modules/misc/include/materials/Density.h
  modules/misc/src/materials/Density.C
  modules/phase_field/include/action/PolycrystalElasticDrivingForceAction.h
  modules/phase_field/include/kernels/ACInterfaceStress.h
  modules/phase_field/include/kernels/GrainRigidBodyMotionBase.h
  modules/phase_field/include/materials/ElasticEnergyMaterial.h
  modules/phase_field/include/materials/ForceDensityMaterial.h
  modules/phase_field/include/materials/GrainAdvectionVelocity.h
  modules/tensor_mechanics/include/auxkernels/ElasticEnergyAux.h
  modules/tensor_mechanics/include/kernels/GeneralizedPlaneStrainOffDiag.h
  modules/tensor_mechanics/include/kernels/PhaseFieldFractureMechanicsOffDiag.h
  modules/tensor_mechanics/include/kernels/PlasticHeatEnergy.h
  modules/tensor_mechanics/include/kernels/StressDivergenceTensors.h
  modules/tensor_mechanics/include/kernels/StressDivergenceTensorsTruss.h
  modules/tensor_mechanics/include/kernels/WeakPlaneStress.h
  modules/tensor_mechanics/include/materials/ADComputeEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ADComputeElasticityTensorBase.h
  modules/tensor_mechanics/include/materials/ADComputeStrainBase.h
  modules/tensor_mechanics/include/materials/ComputeEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ComputeElasticityTensorBase.h
  modules/tensor_mechanics/include/materials/ComputeExtraStressBase.h
  modules/tensor_mechanics/include/materials/ComputeGlobalStrain.h
  modules/tensor_mechanics/include/materials/ComputePlasticHeatEnergy.h
  modules/tensor_mechanics/include/materials/ComputeStrainBase.h
  modules/tensor_mechanics/include/materials/EshelbyTensor.h
  modules/tensor_mechanics/include/materials/MultiPhaseStressMaterial.h
  modules/tensor_mechanics/include/materials/StrainEnergyDensity.h
  modules/tensor_mechanics/include/materials/ThermalFractureIntegral.h
  modules/tensor_mechanics/include/materials/TwoPhaseStressMaterial.h
  modules/tensor_mechanics/include/userobjects/GeneralizedPlaneStrainUserObject.h
  modules/tensor_mechanics/include/userobjects/GlobalStrainUserObject.h
  modules/tensor_mechanics/include/userobjects/HEVPFlowRateUOBase.h
  modules/xfem/include/kernels/CrackTipEnrichmentStressDivergenceTensors.h
  modules/xfem/include/materials/LevelSetBiMaterialBase.h
Labels: PR: Auto Merge

#13612 Fix parallel test failure
  modules/phase_field/test/tests/GrandPotentialPFM/GrandPotentialAnisotropyAntitrap.i
  modules/phase_field/test/tests/GrandPotentialPFM/gold/GrandPotentialAnisotropyAntitrap_out.e
Labels: PR: Auto Merge

#13613 Introduce UserObjectInterface API to AD objects
  framework/include/bcs/ADIntegratedBC.h
  framework/include/bcs/ADNodalBC.h
  framework/include/constraints/Constraint.h
  framework/include/dgkernels/ADDGKernel.h
  framework/include/kernels/ADKernel.h
  framework/include/userobject/UserObjectInterface.h
Labels: PR: Auto Merge

#13545 Convert DynamicStressDivergenceTensors to AD
  framework/include/materials/MaterialPropertyInterface.h
  modules/tensor_mechanics/doc/content/source/kernels/ADDynamicStressDivergenceTensors.md
  modules/tensor_mechanics/include/kernels/ADDynamicStressDivergenceTensors.h
  modules/tensor_mechanics/src/actions/DynamicTensorMechanicsAction.C
  modules/tensor_mechanics/src/kernels/ADDynamicStressDivergenceTensors.C
  modules/tensor_mechanics/src/materials/ADComputeFiniteStrainElasticStress.C
  modules/tensor_mechanics/test/tests/dynamics/wave_1D/tests
  modules/tensor_mechanics/test/tests/dynamics/wave_1D/wave_rayleigh_hht_AD.i
Labels: PR: Auto Merge

#13621 Drop all double colon rules
  framework/app.mk
  framework/build.mk
  framework/moose.mk
Labels: PR: Auto Merge, PR: Failed but allowed

#13526 Inelastic damage
  modules/tensor_mechanics/doc/content/source/materials/ComputeMultipleInelasticStress.md
  modules/tensor_mechanics/include/materials/ComputeMultipleInelasticStress.h
  modules/tensor_mechanics/include/materials/DamageBase.h
  modules/tensor_mechanics/include/materials/ScalarDamageBase.h
  modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
  modules/tensor_mechanics/src/materials/ScalarDamageBase.C
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/scalar_material_damage_creep_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/scalar_material_damage_creep.i
  modules/tensor_mechanics/test/tests/scalar_material_damage/tests
Labels: PR: Failed but allowed

#13585 MultiAppMeshFunctionTransfer support L2 Lagrange variable
  framework/include/transfers/MultiAppNearestNodeTransfer.h
  framework/src/transfers/MultiAppInterpolationTransfer.C
  framework/src/transfers/MultiAppMeshFunctionTransfer.C
  framework/src/transfers/MultiAppNearestNodeTransfer.C
  framework/src/transfers/MultiAppUserObjectTransfer.C
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_diff_out.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_interpolation_out.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_nearest_node_out.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_out.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_out_diff_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_out_nearest_node_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_out_nterpolation_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_out_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_userobject_out.e
  test/tests/transfers/multiapp_high_order_variable_transfer/gold/master_L2_Lagrange_userobject_out_sub0.e
  test/tests/transfers/multiapp_high_order_variable_transfer/master_L2_Lagrange.i
  test/tests/transfers/multiapp_high_order_variable_transfer/master_L2_Lagrange_userobject.i
  test/tests/transfers/multiapp_high_order_variable_transfer/sub_L2_Lagrange.i
  test/tests/transfers/multiapp_high_order_variable_transfer/tests
Labels: PR: Ready for Review/Merge

#13626 Add initial from file for GrainGrowth action
  modules/phase_field/src/action/GrainGrowthAction.C
  modules/phase_field/test/tests/new_initial_conditions/GrainGrowth_initial_from_file.i
  modules/phase_field/test/tests/new_initial_conditions/gold/GrainGrowth_initial_from_file_out.e
  modules/phase_field/test/tests/new_initial_conditions/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13579 Fix recover and pedantic behavior
  python/TestHarness/FileChecker.py
  python/TestHarness/JobDAG.py
  python/TestHarness/RaceChecker.py
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/contrib/dag/__init__.py
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13640 More SQA Reqs
  framework/doc/content/source/interfacekernels/BlockRestrictable.md
  framework/doc/content/source/interfacekernels/BoundaryRestrictable.md
  framework/doc/content/source/problems/FEProblem.md
  framework/doc/content/source/problems/FEProblemBase.md
  framework/doc/content/source/systems/AuxiliarySystem.md
  framework/doc/content/source/systems/NonlinearSystem.md
  framework/doc/content/syntax/ICs/index.md
  framework/doc/hidden.yml
  framework/src/problems/FEProblem.C
  test/tests/ics/boundary_ic/tests
  test/tests/ics/check_error/tests
  test/tests/ics/component_ic/tests
  test/tests/ics/constant_ic/tests
  test/tests/ics/data_struct_ic/tests
  test/tests/ics/dependency/tests
  test/tests/ics/function_ic/tests
  test/tests/ics/function_scalar_ic/tests
  test/tests/ics/hermite_ic/tests
  test/tests/ics/lagrange_ic/tests
  test/tests/ics/zero_ic/tests
  test/tests/problems/custom_fe_problem/tests
  test/tests/problems/mixed_coord/tests
  test/tests/problems/no_kernel_coverage_check/tests
  test/tests/problems/no_material_coverage_check/tests
  test/tests/problems/no_solve/tests
  test/tests/quadrature/order/tests
Labels: PR: Failed but allowed

#13645 Patches for 13622
  framework/src/systems/NonlinearEigenSystem.C
  modules/phase_field/src/kernels/ADGrainGrowth.C
  modules/phase_field/src/kernels/ADGrainGrowthBase.C
  tutorials/darcy_thermo_mech/step02_darcy_pressure/src/kernels/DarcyPressure.C
  tutorials/darcy_thermo_mech/step03_darcy_material/src/kernels/DarcyPressure.C
  tutorials/darcy_thermo_mech/step05_heat_conduction/src/bcs/HeatConductionOutflow.C
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/src/bcs/HeatConductionOutflow.C
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/src/kernels/DarcyAdvection.C
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/src/materials/PackedColumn.C
  tutorials/darcy_thermo_mech/step09_mechanics/src/materials/PackedColumn.C
  tutorials/darcy_thermo_mech/step10_multiapps/src/materials/PackedColumn.C
Labels: PR: Failed but allowed

#13651 SQA tags in tensor_mechanics/auxkernels. #13634
  modules/tensor_mechanics/test/tests/auxkernels/tests
Labels: PR: Failed but allowed

#13643 Do not leak memory when Assembly::createQRules is called multiple times
  framework/src/base/Assembly.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13649 Extension of StiffenedGasFluidProperties with NaNInterface
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
Labels: PR: Failed but allowed
