Repository idaholab/moose, pull requests merged in 2019-05, with the labels that each got.

#13330 Added pi and e to ${fparse ..} in input file parser
  framework/include/parser/Parser.h
  unit/src/HitTests.C
Labels: PR: Failed but allowed

#13312 Intermittent Failure object
  test/include/userobjects/IntermittentFailureUO.h
  test/src/userobjects/IntermittentFailureUO.C
  test/tests/misc/intermittent_failure/intermittent_failure.i
  test/tests/misc/intermittent_failure/tests
Labels: PR: Ready for Review/Merge

#13343 Simplify Makefiles for modules
  framework/app.mk
  framework/src/base/MooseApp.C
  modules/chemical_reactions/Makefile
  modules/contact/Makefile
  modules/external_petsc_solver/Makefile
  modules/fluid_properties/Makefile
  modules/functional_expansion_tools/Makefile
  modules/heat_conduction/Makefile
  modules/level_set/Makefile
  modules/misc/Makefile
  modules/modules.mk
  modules/navier_stokes/Makefile
  modules/phase_field/Makefile
  modules/porous_flow/Makefile
  modules/rdg/Makefile
  modules/richards/Makefile
  modules/solid_mechanics/Makefile
  modules/stochastic_tools/Makefile
  modules/tensor_mechanics/Makefile
  modules/xfem/Makefile
  stork/Makefile.app
  stork/Makefile.module
Labels: PR: Auto Merge

#13353 Don't run a few slower tests in some configs
  modules/xfem/test/tests/crack_tip_enrichment/tests
  test/tests/misc/intermittent_failure/tests
Labels: PR: Ready for Review/Merge

#13355 Fix a few more headers
  framework/include/controls/ConditionalEnableControl.h
  framework/include/controls/ConditionalFunctionEnableControl.h
  framework/include/ics/VectorFunctionIC.h
  modules/navier_stokes/include/bcs/AdvectionBC.h
  modules/xfem/test/tests/crack_tip_enrichment/tests
Labels: PR: Auto Merge

#13358 UserObjects can be retrieved in scalar initial conditions
  framework/doc/content/source/ics/InitialCondition.md
  framework/doc/content/source/ics/ScalarInitialCondition.md
  framework/doc/content/source/userobject/UserObjectInterface.md
  framework/include/ics/ScalarInitialCondition.h
  framework/include/ics/ScalarInitialConditionWarehouse.h
  framework/include/problems/FEProblemBase.h
  framework/src/ics/ScalarInitialCondition.C
  framework/src/ics/ScalarInitialConditionWarehouse.C
  framework/src/problems/FEProblemBase.C
  test/include/ics/ScalarUOIC.h
  test/src/ics/ScalarUOIC.C
  test/tests/ics/depend_on_uo/gold/scalar_ic_from_uo_out.csv
  test/tests/ics/depend_on_uo/scalar_ic_from_uo.i
  test/tests/ics/depend_on_uo/tests
Labels: PR: Failed but allowed

#13362 Working towards fixing phase_field parallel tests
  modules/phase_field/src/userobjects/PolycrystalUserObjectBase.C
  modules/phase_field/test/tests/grain_tracker_test/tests
Labels: PR: Failed but allowed

#13337 May News
  framework/doc/content/source/auxkernels/VectorFunctionAux.md
  modules/doc/content/newsletter/2019_04.md
  modules/doc/content/newsletter/2019_05.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#13376 Enable DenseMatrix<DualReal>
  framework/include/utils/DenseMatrix.h
  framework/src/utils/DenseMatrixDualReal.C
  unit/src/DenseMatrixDualRealTest.C
Labels: PR: Auto Merge

#13378 Fix for using "execute_on = final" for the Console object
  framework/doc/content/source/outputs/Console.md
  framework/doc/hidden.yml
  framework/src/outputs/Console.C
  test/tests/outputs/console/tests
Labels: PR: Ready for Review/Merge

#13371 AD wrapper types
  framework/include/restart/DataIO.h
  framework/include/utils/MooseADWrapper.h
  framework/src/restart/DataIO.C
  framework/src/utils/MooseADWrapper.C
  modules/fluid_properties/include/userobjects/IdealGasFluidProperties.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/include/utils/DimensionlessFlowNumbers.h
  modules/fluid_properties/src/userobjects/IdealGasFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
  modules/fluid_properties/src/utils/DimensionlessFlowNumbers.C
  unit/src/ADTypesTest.C
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#13385 Old compilers cant handle scoping for specialization declaration
  framework/include/utils/DenseMatrix.h
Labels: PR: Auto Merge

#13364 Getting tensor mechanics ready for parallel
  modules/tensor_mechanics/examples/coal_mining/cosserat_mc_wp_sticky.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_dyn_variable_action.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_file.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_gravity.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_inertia_damping.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_inertia_damping_action.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_added_mass_inertia_damping_ti.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_rayleigh_hht.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_rayleigh_hht_action.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_euler_small_rayleigh_hht_ti.i
  modules/tensor_mechanics/test/tests/beam/dynamic/dyn_timoshenko_small.i
  modules/tensor_mechanics/test/tests/beam/dynamic/tests
  modules/tensor_mechanics/test/tests/beam/static/euler_small_strain_y.i
  modules/tensor_mechanics/test/tests/beam/static/euler_small_strain_y_action.i
  modules/tensor_mechanics/test/tests/beam/static/euler_small_strain_z.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/tests
  modules/tensor_mechanics/test/tests/isotropicSD_plasticity/isotropicSD.i
  modules/tensor_mechanics/test/tests/isotropicSD_plasticity/powerRuleHardening.i
  modules/tensor_mechanics/test/tests/mohr_coulomb/gold/uni_axial2_planar.e
  modules/tensor_mechanics/test/tests/mohr_coulomb/gold/uni_axial3_planar.e
  modules/tensor_mechanics/test/tests/mohr_coulomb/uni_axial2_planar.i
  modules/tensor_mechanics/test/tests/mohr_coulomb/uni_axial3_planar.i
  modules/tensor_mechanics/test/tests/orthotropic_plasticity/orthotropic.i
  modules/tensor_mechanics/test/tests/orthotropic_plasticity/powerRuleHardening.i
  modules/tensor_mechanics/test/tests/plane_stress/weak_plane_stress_incremental.i
  modules/tensor_mechanics/test/tests/plane_stress/weak_plane_stress_small.i
  modules/tensor_mechanics/test/tests/torque_reaction/torque_reaction_tm.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13395 Fixing #pragma once
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  unit/include/PorousFlowWaterVaporTest.h
  unit/src/DelimitedFileReaderTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13392 Mortar deuce fixups
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/constraints/MortarConstraint.C
  modules/combined/test/tests/sliding_block/in_and_out/constraint/frictionless_penalty.i
  modules/tensor_mechanics/test/tests/beam/dynamic/tests
  test/tests/mortar/displaced-gap-conductance-2d-non-conforming/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#13393 Catch problems with text type
  python/MooseDocs/base/lexers.py
  python/MooseDocs/common/get_content.py
  python/MooseDocs/test/unit/common/test_get_pages.py
Labels: PR: Failed but allowed

#13386 Improve sqa stats script and add links to source page headings
  modules/doc/config.yml
  python/MooseDocs/extensions/content.py
  python/mooseutils/__init__.py
  python/mooseutils/compute_requirement_stats.py
  scripts/sqa_stats.py
Labels: PR: Failed but allowed

#13398 Use tee to capture summary report
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13391 PorousFlow tests work in parallel
  modules/porous_flow/examples/flow_through_fractured_media/coarse.i
  modules/porous_flow/examples/flow_through_fractured_media/diffusion.i
  modules/porous_flow/examples/flow_through_fractured_media/fine_steady.i
  modules/porous_flow/examples/flow_through_fractured_media/gold/coarse_csv_xmass_0011.csv
  modules/porous_flow/examples/flow_through_fractured_media/gold/diffusion_out.e
  modules/porous_flow/examples/flow_through_fractured_media/gold/fine_steady_out.e
  modules/porous_flow/examples/flow_through_fractured_media/tests
  modules/porous_flow/examples/tutorial/01.i
  modules/porous_flow/examples/tutorial/04.i
  modules/porous_flow/examples/tutorial/06.i
  modules/porous_flow/examples/tutorial/06_KT.i
  modules/porous_flow/examples/tutorial/08_KT.i
  modules/porous_flow/examples/tutorial/gold/01_out.e
  modules/porous_flow/examples/tutorial/gold/04_out.e
  modules/porous_flow/examples/tutorial/gold/06_KT_out.e
  modules/porous_flow/examples/tutorial/gold/06_out.e
  modules/porous_flow/examples/tutorial/gold/08_KT_out.e
  modules/porous_flow/test/tests/actions/basicthm_h.i
  modules/porous_flow/test/tests/actions/basicthm_hm.i
  modules/porous_flow/test/tests/actions/basicthm_th.i
  modules/porous_flow/test/tests/actions/basicthm_thm.i
  modules/porous_flow/test/tests/actions/gold/basicthm_h_out.e
  modules/porous_flow/test/tests/actions/gold/basicthm_hm_out.e
  modules/porous_flow/test/tests/actions/gold/basicthm_th_out.e
  modules/porous_flow/test/tests/actions/gold/basicthm_thm_out.e
  modules/porous_flow/test/tests/energy_conservation/tests
  modules/porous_flow/test/tests/gravity/fully_saturated_grav01a.i
  modules/porous_flow/test/tests/gravity/fully_saturated_grav01b.i
  modules/porous_flow/test/tests/gravity/fully_saturated_grav01c.i
  modules/porous_flow/test/tests/gravity/grav01a.i
  modules/porous_flow/test/tests/gravity/grav01b.i
  modules/porous_flow/test/tests/gravity/grav01c.i
  modules/porous_flow/test/tests/gravity/grav01c_action.i
  modules/porous_flow/test/tests/gravity/grav01d.i
  modules/porous_flow/test/tests/gravity/grav02a.i
  modules/porous_flow/test/tests/gravity/grav02b.i
  modules/porous_flow/test/tests/gravity/tests
  modules/porous_flow/test/tests/heat_advection/heat_advection_1d_fully_saturated_action.i
  modules/porous_flow/test/tests/heat_conduction/no_fluid.i
  modules/porous_flow/test/tests/heat_conduction/two_phase.i
  modules/porous_flow/test/tests/jacobian/tests
  modules/porous_flow/test/tests/newton_cooling/nc08.i
  modules/porous_flow/test/tests/numerical_diffusion/fully_saturated_action_KT.i
  modules/porous_flow/test/tests/numerical_diffusion/pffltvd_action.i
  modules/porous_flow/test/tests/poro_elasticity/terzaghi.i
  modules/porous_flow/test/tests/poro_elasticity/terzaghi_basicthm.i
  modules/porous_flow/test/tests/poro_elasticity/terzaghi_constM.i
  modules/porous_flow/test/tests/poro_elasticity/terzaghi_fully_saturated_volume.i
  modules/porous_flow/test/tests/pressure_pulse/pressure_pulse_1d_MD.i
  modules/porous_flow/test/tests/sinks/gold/s09_mf_0010.csv
  modules/porous_flow/test/tests/sinks/gold/s09_mf_0050.csv
  modules/porous_flow/test/tests/sinks/gold/s09_mf_0100.csv
  modules/porous_flow/test/tests/sinks/s09.i
  modules/porous_flow/test/tests/sinks/s09_fully_saturated.i
  modules/porous_flow/test/tests/sinks/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13379 Newsletter: PorousFlow KT announcement
  modules/doc/content/newsletter/2019_06.md
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13387 Flibe fluid properties. Refs #13383
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/source/userobjects/FlibeFluidProperties.md
  modules/fluid_properties/include/userobjects/FlibeFluidProperties.h
  modules/fluid_properties/src/userobjects/FlibeFluidProperties.C
  unit/include/FlibeFluidPropertiesTest.h
  unit/src/FlibeFluidPropertiesTest.C
Labels: PR: Auto Merge, PR: Failed but allowed

#13407 Helium fluid properties
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/source/userobjects/HeliumFluidProperties.md
  modules/fluid_properties/include/userobjects/HeliumFluidProperties.h
  modules/fluid_properties/src/userobjects/HeliumFluidProperties.C
  unit/include/HeliumFluidPropertiesTest.h
  unit/src/HeliumFluidPropertiesTest.C
Labels: PR: Failed but allowed

#13419 Added post-processor to compute element integral of function
  framework/doc/content/source/postprocessors/FunctionElementIntegral.md
  framework/include/postprocessors/FunctionElementIntegral.h
  framework/src/postprocessors/FunctionElementIntegral.C
  test/tests/postprocessors/function_element_integral/function_element_integral.i
  test/tests/postprocessors/function_element_integral/gold/function_element_integral_out.csv
  test/tests/postprocessors/function_element_integral/tests
Labels: PR: Failed but allowed

#13409 Fix incorrect type
  framework/src/samplers/Sampler.C
Labels: PR: Failed but allowed

#13427 Limit parallel testing for adaptive cycles test
  test/tests/mesh/adapt/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13288 Fancy Extruder
  framework/doc/content/source/meshgenerators/FancyExtruderGenerator.md
  framework/include/meshgenerators/FancyExtruderGenerator.h
  framework/src/meshgenerators/FancyExtruderGenerator.C
  test/tests/meshgenerators/fancy_extruder_generator/gen_extrude.i
  test/tests/meshgenerators/fancy_extruder_generator/gold/gen_extrude_in.e
  test/tests/meshgenerators/fancy_extruder_generator/tests
Labels: PR: Ready for Review/Merge

#13066 Add PlaneDeletionGenerator
  framework/doc/content/media/meshgenerators/plane_deletion_after.png
  framework/doc/content/media/meshgenerators/plane_deletion_before.png
  framework/doc/content/source/meshgenerators/PlaneDeletionGenerator.md
  framework/include/meshgenerators/PlaneDeletionGenerator.h
  framework/src/meshgenerators/PlaneDeletionGenerator.C
  test/tests/meshgenerators/plane_deletion/gold/plane_deletion_in.e
  test/tests/meshgenerators/plane_deletion/plane_deletion.i
  test/tests/meshgenerators/plane_deletion/tests
Labels: PR: Ready for Review/Merge

#12630 Add RankMap
  framework/doc/content/media/auxkernels/hardware_id_aux.png
  framework/doc/content/media/vectorpostprocessors/work_balance_hardware_id.png
  framework/doc/content/source/auxkernels/HardwareIDAux.md
  framework/doc/content/source/vectorpostprocessors/WorkBalance.md
  framework/include/auxkernels/HardwareIDAux.h
  framework/include/base/MooseApp.h
  framework/include/postprocessors/MemoryUsageReporter.h
  framework/include/utils/RankMap.h
  framework/include/vectorpostprocessors/WorkBalance.h
  framework/src/auxkernels/HardwareIDAux.C
  framework/src/base/MooseApp.C
  framework/src/postprocessors/MemoryUsageReporter.C
  framework/src/utils/RankMap.C
  framework/src/vectorpostprocessors/WorkBalance.C
  test/tests/auxkernels/hardware_id_aux/gold/hardware_id_aux_out.e
  test/tests/auxkernels/hardware_id_aux/hardware_id_aux.i
  test/tests/auxkernels/hardware_id_aux/tests
  test/tests/vectorpostprocessors/work_balance/gold/distributed_all_wb_0000.csv
  test/tests/vectorpostprocessors/work_balance/gold/distributed_aux_wb_0000.csv
  test/tests/vectorpostprocessors/work_balance/gold/distributed_nl_wb_0000.csv
  test/tests/vectorpostprocessors/work_balance/gold/work_balance_out_all_wb_0000.csv
  test/tests/vectorpostprocessors/work_balance/gold/work_balance_out_aux_wb_0000.csv
  test/tests/vectorpostprocessors/work_balance/gold/work_balance_out_nl_wb_0000.csv
Labels: PR: Ready for Review/Merge

#13402 PorousFlow Actions add RelationshipManagers
  modules/porous_flow/examples/tutorial/06_KT.i
  modules/porous_flow/examples/tutorial/08_KT.i
  modules/porous_flow/include/actions/PorousFlowActionBase.h
  modules/porous_flow/src/actions/PorousFlowActionBase.C
  modules/porous_flow/test/tests/heat_advection/heat_advection_1d_fully_saturated_action.i
  modules/porous_flow/test/tests/numerical_diffusion/fully_saturated_action_KT.i
  modules/porous_flow/test/tests/numerical_diffusion/pffltvd_action.i
Labels: PR: Failed but allowed

#13431 Enable AD for constant monomials
  framework/include/variables/MooseVariableData.h
  framework/src/variables/MooseVariableConstMonomial.C
  test/include/dgkernels/ADDGConvection.h
  test/src/dgkernels/ADDGConvection.C
  test/tests/dgkernels/ad_dg_convection/ad_dg_convection.i
  test/tests/dgkernels/ad_dg_convection/gold/ad_dg_convection_out.e
  test/tests/dgkernels/ad_dg_convection/tests
Labels: PR: Failed but allowed

#13422 PorousFlow KuzminTurek issues memory-wastage warning
  modules/porous_flow/include/userobjects/AdvectiveFluxCalculatorBase.h
  modules/porous_flow/src/userobjects/AdvectiveFluxCalculatorBase.C
  modules/porous_flow/test/tests/flux_limited_TVD_pflow/tests
Labels: PR: Failed but allowed

#13423 CombinerGenerator
  framework/doc/content/media/meshgenerators/combiner.png
  framework/doc/content/media/meshgenerators/combiner_multi.png
  framework/doc/content/media/meshgenerators/combiner_multi_translate.png
  framework/doc/content/source/meshgenerators/CombinerGenerator.md
  framework/include/meshgenerators/CombinerGenerator.h
  framework/src/meshgenerators/CombinerGenerator.C
  test/tests/meshgenerators/combiner_generator/combiner_generator.i
  test/tests/meshgenerators/combiner_generator/combiner_multi_input.i
  test/tests/meshgenerators/combiner_generator/combiner_multi_input_translate.i
  test/tests/meshgenerators/combiner_generator/gold/combiner_generator_in.e
  test/tests/meshgenerators/combiner_generator/gold/combiner_multi_input_in.e
  test/tests/meshgenerators/combiner_generator/gold/combiner_multi_input_translate_in.e
  test/tests/meshgenerators/combiner_generator/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#13399 Display when GhostingFunctors are active
  framework/include/actions/ActionWarehouse.h
  framework/src/base/MooseApp.C
  test/tests/relationship_managers/default_ghosting/default_ghosting.i
  test/tests/relationship_managers/default_ghosting/tests
Labels: PR: Failed but allowed

#13410 Update moose-environment package
  framework/doc/packages_config.yml
  modules/doc/content/getting_started/installation/bash_profile.md
  modules/doc/content/getting_started/installation/centos.md
  modules/doc/content/getting_started/installation/fedora.md
  modules/doc/content/getting_started/installation/mint.md
  modules/doc/content/getting_started/installation/opensuse.md
  modules/doc/content/getting_started/installation/post_package_install.md
  modules/doc/content/getting_started/installation/ubuntu.md
  package_version
Labels: PR: Failed but allowed

#13430 Adds T_from_h_p to SinglePhaseFluidProperties
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
Labels: PR: Failed but allowed

#13441 Enable LinearInterpolation for AD
  framework/include/utils/LinearInterpolation.h
  framework/src/utils/LinearInterpolation.C
  modules/solid_mechanics/include/materials/IsotropicTempDepHardening.h
  modules/tensor_mechanics/include/materials/TemperatureDependentHardeningStressUpdate.h
  test/include/materials/LinearInterpolationMaterial.h
  unit/src/LinearInterpolationTest.C
Labels: PR: Failed but allowed

#13317 AD robustness tests
  modules/combined/test/tests/ad_power_law_creep/gold/power_law_creep_out.e
  modules/combined/test/tests/ad_power_law_creep/gold/power_law_creep_restart2_tm_out.e
  modules/combined/test/tests/ad_power_law_creep/gold/power_law_creep_smallstrain_out.e
  modules/combined/test/tests/ad_power_law_creep/power_law_creep.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_restart1.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_restart2.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_simple.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_smallstrain.i
  modules/combined/test/tests/ad_power_law_creep/tests
  modules/combined/test/tests/power_law_creep/gold/power_law_creep_test_out.e
  modules/combined/test/tests/power_law_creep/gold/power_law_creep_test_tm_out.e
  modules/tensor_mechanics/include/materials/ADPowerLawCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/ADRadialReturnStressUpdate.h
  modules/tensor_mechanics/include/materials/ADSingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/include/materials/SingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/src/kernels/ADStressDivergenceTensors.C
  modules/tensor_mechanics/src/materials/ADPowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/ADRadialReturnStressUpdate.C
  modules/tensor_mechanics/src/materials/ADSingleVariableReturnMappingSolution.C
  modules/tensor_mechanics/src/materials/PowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/SingleVariableReturnMappingSolution.C
  test/tests/kernels/ad_jacobians/test.i
  test/tests/kernels/ad_jacobians/tests
Labels: PR: Failed but allowed

#13447 Revert changes in MultiAppDTKInterpolationTransfer for Trilinos
  framework/include/transfers/MultiAppDTKInterpolationTransfer.h
  framework/src/transfers/MultiAppDTKInterpolationTransfer.C
Labels: PR: Failed but allowed

#13451 Drop changes on finalize in postprocessor and user object
  framework/include/postprocessors/ElementIntegralPostprocessor.h
  framework/include/postprocessors/SideIntegralPostprocessor.h
  framework/include/userobject/ElementIntegralUserObject.h
  framework/include/userobject/SideIntegralUserObject.h
  framework/src/postprocessors/ElementIntegralPostprocessor.C
  framework/src/postprocessors/SideIntegralPostprocessor.C
  framework/src/userobject/ElementIntegralUserObject.C
  framework/src/userobject/NearestPointIntegralVariablePostprocessor.C
  framework/src/userobject/SideIntegralUserObject.C
  test/tests/transfers/multiapp_conservative_transfer/gold/master_conservative_transfer_out.e
  test/tests/transfers/multiapp_conservative_transfer/gold/master_conservative_transfer_out_sub0.e
  test/tests/transfers/multiapp_conservative_transfer/master_conservative_transfer.i
Labels: PR: Auto Merge, PR: Failed but allowed

#13456 Template fuzzy compares
  framework/include/utils/MooseUtils.h
  framework/src/utils/MooseUtils.C
Labels: PR: Auto Merge, PR: Failed but allowed

#13457 Prevent hidden-virtual warning
  framework/include/utils/JvarMapInterface.h
Labels: PR: Failed but allowed

#13458 Fix for clamp bug in power law creep
  framework/include/utils/MathUtils.h
  modules/tensor_mechanics/src/materials/ADSingleVariableReturnMappingSolution.C
  modules/tensor_mechanics/src/materials/SingleVariableReturnMappingSolution.C
Labels: PR: Auto Merge

#13445 Working on SQA for check_error tests
  modules/doc/content/framework_development/index.md
  modules/doc/content/framework_development/sanity_checking.md
  test/tests/misc/check_error/nan_test.i
  test/tests/misc/check_error/nan_test_transient.i
  test/tests/misc/check_error/tests
Labels: PR: Auto Merge, PR: Failed but allowed, PR: Ready for Review/Merge

#13452 Disable volumetric_locking_correction for face materials
  framework/include/materials/ADMaterial.h
  modules/tensor_mechanics/include/materials/ADComputeFiniteStrain.h
  modules/tensor_mechanics/include/materials/ComputeFiniteStrain.h
  modules/tensor_mechanics/include/materials/ComputeStrainBase.h
  modules/tensor_mechanics/src/materials/ADComputeFiniteStrain.C
  modules/tensor_mechanics/src/materials/ADComputeStrainBase.C
  modules/tensor_mechanics/src/materials/ComputeFiniteStrain.C
  modules/tensor_mechanics/src/materials/ComputeStrainBase.C
Labels: PR: Failed but allowed, PR: Requires App Patch(es)

#13462 fix overzealous assert
  framework/src/variables/MooseVariableData.C
Labels: PR: Auto Merge

#13359 Vector interface kernel
  framework/include/interfacekernels/InterfaceKernel.h
  framework/include/interfacekernels/InterfaceKernelBase.h
  framework/include/loops/ComputeJacobianThread.h
  framework/include/loops/ComputeResidualThread.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/base/Moose.C
  framework/src/interfacekernels/InterfaceKernel.C
  framework/src/interfacekernels/InterfaceKernelBase.C
  framework/src/loops/ComputeFullJacobianThread.C
  framework/src/loops/ComputeJacobianThread.C
  framework/src/loops/ComputeResidualThread.C
  framework/src/systems/NonlinearSystemBase.C
  test/include/interfacekernels/VectorPenaltyInterfaceDiffusion.h
  test/src/interfacekernels/VectorPenaltyInterfaceDiffusion.C
  test/tests/interfacekernels/2d_interface/gold/vector_2d_out.e
  test/tests/interfacekernels/2d_interface/tests
  test/tests/interfacekernels/2d_interface/vector_2d.i
  test/tests/interfacekernels/3d_interface/gold/vector_3d_out.e
  test/tests/interfacekernels/3d_interface/tests
  test/tests/interfacekernels/3d_interface/vector_3d.i
Labels: PR: Failed but allowed

#13470 add missing fluid properties funcs for pronghorn AD
  modules/fluid_properties/include/userobjects/FlibeFluidProperties.h
  modules/fluid_properties/include/userobjects/FlinakFluidProperties.h
  modules/fluid_properties/src/userobjects/FlibeFluidProperties.C
  modules/fluid_properties/src/userobjects/FlinakFluidProperties.C
Labels: PR: Auto Merge, PR: Failed but allowed

#13483 Support older Python namedtuple
  python/TestHarness/StatusSystem.py
Labels: PR: Failed but allowed

#13500 RDG ElementLoopUserObject sets current subdomain
  modules/rdg/include/userobjects/ElementLoopUserObject.h
  modules/rdg/src/userobjects/ElementLoopUserObject.C
Labels: PR: Failed but allowed

#13487 Adding a unit test
  framework/include/utils/InputParameterWarehouse.h
  unit/src/InputParameterWarehouseTest.C
Labels: PR: Auto Merge, PR: Failed but allowed

#13382 Diffuse interface support for more IC's and IC user objects
  framework/include/ics/BoundingBoxIC.h
  framework/src/ics/BoundingBoxIC.C
  modules/phase_field/include/userobjects/PolycrystalCircles.h
  modules/phase_field/include/userobjects/PolycrystalVoronoi.h
  modules/phase_field/src/ics/PolycrystalVoronoiVoidIC.C
  modules/phase_field/src/ics/SmoothCircleBaseIC.C
  modules/phase_field/src/userobjects/PolycrystalCircles.C
  modules/phase_field/src/userobjects/PolycrystalVoronoi.C
  modules/phase_field/test/tests/DeformedGrain/DeformedGrain.i
  modules/phase_field/test/tests/MultiPhase/switchingfunctionmultiphasematerial.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_moregrains.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_notperiodic.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_periodic.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_periodic_fromfile.i
  modules/phase_field/test/tests/initial_conditions/gold/polycrystalcircles_fromfile_out.e
  modules/phase_field/test/tests/initial_conditions/gold/polycrystalcircles_fromvector_out.e
  modules/phase_field/test/tests/initial_conditions/polycrystalcircles_fromfile.i
  modules/phase_field/test/tests/initial_conditions/polycrystalcircles_fromvector.i
  modules/phase_field/test/tests/new_initial_conditions/gold/SmoothCircleIC_tanh_out.e
  test/tests/ics/bounding_box_ic/bounding_box_ic_diffuse_test.i
  test/tests/ics/bounding_box_ic/gold/bounding_box_ic_diffuse_test_out.e
  test/tests/ics/bounding_box_ic/tests
Labels: PR: Failed but allowed

#13405 added AD compatible spectral decomposition for ranktwotensor
  framework/include/utils/RankTwoTensor.h
  framework/src/utils/RankTwoTensor.C
  unit/src/RankTwoEigenRoutinesTest.C
  unit/src/RankTwoTensorTest.C
Labels: PR: Failed but allowed
