Repository idaholab/moose, pull requests merged in 2020-11, with the labels that each got.

#16034 Add FV support for Dirac Kernels
  framework/include/dirackernels/DiracKernel.h
  framework/src/dirackernels/DiracKernel.C
  test/tests/dirackernels/constant_point_source/1d_point_source_fv.i
  test/tests/dirackernels/constant_point_source/gold/1d_fv_out.e
  test/tests/dirackernels/constant_point_source/tests
Labels: PR: Failed but allowed

#16041 Add Agent Labeling
  docker_ci/Jenkinsfile
Labels: PR: Failed but allowed

#15982 Add Gtest and pip3 installs for Consul/Nomad to Docker Image Build
  docker_ci/apt_installs.sh
  docker_ci/install_packages.sh
  docker_ci/yum_installs.sh
Labels: PR: Failed but allowed

#15812 Add some relationship manager and action doc
  framework/doc/content/source/actions/Action.md
  framework/doc/content/source/relationshipmanagers/RelationshipManager.md
Labels: PR: Ready for Review/Merge

#16048 More paranoid initialization of RMs
  framework/include/base/MooseApp.h
  framework/src/base/MooseApp.C
Labels: PR: Failed but allowed

#16047 Provide application level option for controlling new nonzero behavior
  framework/doc/content/source/base/MooseApp.md
  framework/include/base/MooseApp.h
  framework/src/problems/FEProblemBase.C
  modules/navier_stokes/include/base/NavierStokesApp.h
  modules/navier_stokes/test/include/base/NavierStokesTestApp.h
  modules/navier_stokes/test/include/kernels/MallocKernel.h
  modules/navier_stokes/test/src/base/NavierStokesTestApp.C
  modules/navier_stokes/test/src/kernels/MallocKernel.C
  modules/navier_stokes/test/tests/ins/nonzero-malloc/test.i
  modules/navier_stokes/test/tests/ins/nonzero-malloc/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16053 Convert boussinesq benchmarks to heavy tests
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/tests
Labels: PR: Failed but allowed

#16059 Fix FV Dirac Kernel test for different element numberings
  test/tests/dirackernels/constant_point_source/1d_point_source_fv.i
Labels: PR: Failed but allowed

#16038 Remove dark/light movie; update contributing page
  .github/CONTRIBUTING.md
  framework/doc/content/js/init.js
  modules/doc/content/framework_development/contributing.md
  modules/doc/content/index.md
  python/MooseDocs/extensions/katex.py
  python/MooseDocs/extensions/media.py
  python/MooseDocs/test/extensions/test_media.py
  python/MooseDocs/test/gold/html/extensions/devel.html
  python/MooseDocs/test/gold/html/extensions/katex.html
  python/MooseDocs/test/gold/html/extensions/katex_include.html
  python/MooseDocs/test/gold/html/extensions/table.html
  python/MooseDocs/test/gold/materialize/extensions/devel.html
  python/MooseDocs/test/gold/materialize/extensions/katex.html
  python/MooseDocs/test/gold/materialize/extensions/katex_include.html
  python/MooseDocs/test/gold/materialize/extensions/table.html
  python/MooseDocs/test/tree/test_html.py
  python/MooseDocs/tree/html.py
Labels: PR: Failed but allowed

#16054 Revert change to MooseApp start_time
  framework/src/base/MooseApp.C
  framework/src/executioners/Transient.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16022 PorousFlow hysteresis order
  modules/porous_flow/doc/content/media/porous_flow/hysteretic_order.png
  modules/porous_flow/doc/content/source/auxkernels/PorousFlowPropertyAux.md
  modules/porous_flow/doc/content/source/materials/PorousFlowHysteresisOrder.md
  modules/porous_flow/include/auxkernels/PorousFlowPropertyAux.h
  modules/porous_flow/include/materials/PorousFlowHysteresisOrder.h
  modules/porous_flow/include/utils/PorousFlowConstants.h
  modules/porous_flow/src/auxkernels/PorousFlowPropertyAux.C
  modules/porous_flow/src/materials/PorousFlowHysteresisOrder.C
  modules/porous_flow/src/utils/PorousFlowDependencies.C
  modules/porous_flow/test/tests/hysteresis/except01.i
  modules/porous_flow/test/tests/hysteresis/except02.i
  modules/porous_flow/test/tests/hysteresis/except03.i
  modules/porous_flow/test/tests/hysteresis/except04.i
  modules/porous_flow/test/tests/hysteresis/except05.i
  modules/porous_flow/test/tests/hysteresis/except06.i
  modules/porous_flow/test/tests/hysteresis/except07.i
  modules/porous_flow/test/tests/hysteresis/except08.i
  modules/porous_flow/test/tests/hysteresis/except09.i
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_01_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_02_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_03_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_04_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_05_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_06_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_07_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_08_csv.csv
  modules/porous_flow/test/tests/hysteresis/gold/hys_order_09_csv.csv
  modules/porous_flow/test/tests/hysteresis/hys_order_01.i
  modules/porous_flow/test/tests/hysteresis/hys_order_02.i
  modules/porous_flow/test/tests/hysteresis/hys_order_03.i
  modules/porous_flow/test/tests/hysteresis/hys_order_04.i
  modules/porous_flow/test/tests/hysteresis/hys_order_05.i
  modules/porous_flow/test/tests/hysteresis/hys_order_06.i
  modules/porous_flow/test/tests/hysteresis/hys_order_07.i
  modules/porous_flow/test/tests/hysteresis/hys_order_08.i
  modules/porous_flow/test/tests/hysteresis/hys_order_09.i
  modules/porous_flow/test/tests/hysteresis/tests
Labels: PR: Failed but allowed

#16090 Make mortar convergence study tests heavy
  test/tests/mortar/convergence-studies/gap-conductance/tests
  test/tests/mortar/convergence-studies/solution-continuity/tests
Labels: PR: Failed but allowed

#16095 update credit for soil desiccation simulation
  modules/doc/content/gallery.md
Labels: PR: Failed but allowed

#16082 Hysteretic utils added to PorousFlow
  modules/porous_flow/include/utils/PorousFlowVanGenuchten.h
  modules/porous_flow/src/utils/PorousFlowVanGenuchten.C
  modules/porous_flow/unit/src/PorousFlowVanGenuchtenTest.C
Labels: PR: Failed but allowed

#16103 Simplify GenericType
  framework/include/utils/MooseTypes.h
  modules/tensor_mechanics/include/materials/StrainEnergyRateDensity.h
Labels: PR: Failed but allowed

#16105 Fixed PR "Eigensolver Performance Improvement #15791"
  framework/include/problems/EigenProblem.h
  framework/include/utils/SlepcSupport.h
  framework/src/executioners/Eigenvalue.C
  framework/src/problems/EigenProblem.C
  framework/src/utils/SlepcSupport.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16068 Remove duplicate requirements
  modules/doc/sqa_reports.yml
  python/moosesqa/check_requirements.py
  python/moosesqa/test/test_check_requirements.py
  python/moosesqa/test/tests
  test/doc/sqa_reports.yml
  test/tests/auxkernels/ghosting_aux/tests
  test/tests/constraints/equal_value_embedded_constraint/tests
  test/tests/dgkernels/2d_diffusion_dg/tests
  test/tests/executioners/fixed_point/tests
  test/tests/interfacekernels/2d_interface/tests
  test/tests/kernels/ad_2d_diffusion/tests
  test/tests/kernels/ad_mat_diffusion/tests
  test/tests/kernels/ad_transient_diffusion/tests
  test/tests/kernels/array_kernels/tests
  test/tests/kernels/material_derivatives/tests
  test/tests/kernels/vector_fe/tests
  test/tests/materials/piecewise_linear_interpolation_material/tests
  test/tests/mesh/face_info/tests
  test/tests/mesh/mesh_generation/tests
  test/tests/mesh/splitting/tests
  test/tests/mesh_modifiers/sidesets_around_subdomain/tests
  test/tests/mesh_modifiers/sidesets_between_subdomains/tests
  test/tests/meshgenerators/break_mesh_by_block_generator/tests
  test/tests/meshgenerators/cartesian_mesh_generator/tests
  test/tests/meshgenerators/dmg_displaced_mesh/tests
  test/tests/meshgenerators/generated_mesh_generator/tests
  test/tests/meshgenerators/mesh_side_set_generator/tests
  test/tests/meshgenerators/stack_generator/tests
  test/tests/meshgenerators/stitched_mesh_generator/tests
  test/tests/meshgenerators/tiled_mesh_generator/tests
  test/tests/meshgenerators/transform_generator/tests
  test/tests/outputs/console/tests
  test/tests/outputs/perf_graph/multi_app/tests
  test/tests/postprocessors/num_iterations/tests
  test/tests/problems/eigen_problem/arraykernels/tests
  test/tests/problems/no_material_dependency_check/tests
  test/tests/relationship_managers/two_rm/tests
  test/tests/restart/restart_diffusion/tests
  test/tests/restart/restart_transient_from_steady/tests
  test/tests/userobjects/layered_average/tests
  test/tests/variables/optionally_coupled/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16122 Skip spatial_4_threads in geochemistry
  modules/doc/sqa_reports.yml
  modules/geochemistry/test/tests/spatial_reactor/tests
Labels: PR: Failed but allowed

#16136 Fix warnings in geochemistry
  modules/geochemistry/include/utils/GeochemicalSystem.h
  modules/geochemistry/src/utils/PertinentGeochemicalSystem.C
Labels: PR: Failed but allowed

#16126 Do not throw exception from pybtex for duplicate entries
  python/MooseDocs/extensions/bibtex.py
Labels: PR: Failed but allowed

#16071 Nov. 2020 news
  modules/doc/content/newsletter/2020_09.md
  modules/doc/content/newsletter/2020_10.md
  modules/doc/content/newsletter/2020_11.md
  modules/doc/content/newsletter/2020_12.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#16020 Added ability to use old temperature for thermal expansion
  modules/tensor_mechanics/include/materials/ADComputeThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/src/materials/ADComputeDilatationThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ADComputeThermalExpansionEigenstrain.C
  modules/tensor_mechanics/src/materials/ADComputeThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/test/tests/thermal_expansion/ad_constant_expansion_coeff_old.i
  modules/tensor_mechanics/test/tests/thermal_expansion/gold/ad_constant_expansion_coeff_old_out.e
  modules/tensor_mechanics/test/tests/thermal_expansion/tests
Labels: PR: Failed but allowed

#16148 Remove solution localization in eigenvalue system
  framework/src/utils/SlepcSupport.C
Labels: PR: Failed but allowed

#15969 Fix a coord_sys issue in GapConductance model at recover mode
  modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_rspherical.i
  modules/heat_conduction/src/materials/GapConductance.C
Labels: PR: Auto Merge, PR: Failed but allowed

#15776 Support LAGRANGE_VEC in Coupleable interface for nodal objects
  framework/doc/content/source/auxkernels/VectorVariableMagnitudeAux.md
  framework/include/auxkernels/VectorVariableMagnitudeAux.h
  framework/src/auxkernels/VectorVariableMagnitudeAux.C
  framework/src/interfaces/Coupleable.C
  framework/src/variables/MooseVariableData.C
  test/tests/auxkernels/vector_variable_nodal/gold/vector_variable_nodal_out.e
  test/tests/auxkernels/vector_variable_nodal/tests
  test/tests/auxkernels/vector_variable_nodal/vector_variable_nodal.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16056 Create object for to transfer VPP data between main/sub apps
  framework/doc/content/source/reporters/ConstantReporter.md
  framework/doc/content/source/transfers/MultiAppReporterTransfer.md
  framework/doc/content/source/transfers/MultiAppVectorPostprocessorTransfer.md
  framework/include/postprocessors/Receiver.h
  framework/include/reporters/ConstantReporter.h
  framework/include/reporters/ReporterContext.h
  framework/include/reporters/ReporterData.h
  framework/include/transfers/MultiAppReporterTransfer.h
  framework/include/transfers/MultiAppReporterTransferBase.h
  framework/include/utils/JsonSyntaxTree.h
  framework/src/outputs/JSONOutput.C
  framework/src/outputs/JsonIO.C
  framework/src/parser/Parser.C
  framework/src/postprocessors/Receiver.C
  framework/src/reporters/ConstantReporter.C
  framework/src/reporters/ReporterData.C
  framework/src/transfers/MultiAppReporterTransfer.C
  framework/src/transfers/MultiAppReporterTransferBase.C
  python/TestHarness/testers/RunException.py
  test/tests/reporters/constant_reporter/constant_reporter.i
  test/tests/reporters/constant_reporter/gold/constant_reporter_out.json
  test/tests/reporters/constant_reporter/tests
  test/tests/transfers/reporter_transfer/gold/main_out.json
  test/tests/transfers/reporter_transfer/gold/main_out2_sub0_to_sub_vpp_0001.csv
  test/tests/transfers/reporter_transfer/gold/main_out2_sub1_to_sub_vpp_0001.csv
  test/tests/transfers/reporter_transfer/gold/main_out_sub0_out.json
  test/tests/transfers/reporter_transfer/gold/main_out_sub0_to_sub_vpp_0001.csv
  test/tests/transfers/reporter_transfer/gold/main_out_sub1_to_sub_vpp_0001.csv
  test/tests/transfers/reporter_transfer/gold/main_out_to_main_vpp_0001.csv
  test/tests/transfers/reporter_transfer/main.i
  test/tests/transfers/reporter_transfer/sub0.i
  test/tests/transfers/reporter_transfer/sub1.i
  test/tests/transfers/reporter_transfer/tests
Labels: PR: Failed but allowed

#15746 Improve bound checking laromance
  modules/tensor_mechanics/include/materials/ADLAROMANCEStressUpdateBase.h
  modules/tensor_mechanics/src/materials/ADLAROMANCEStressUpdateBase.C
  modules/tensor_mechanics/test/include/materials/SS316HLAROMANCEStressUpdateTest.h
Labels: PR: Auto Merge

#16115 Enable multiple objects, postprocs, transfers for FV variables
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/src/postprocessors/ElementIntegralArrayVariablePostprocessor.C
  framework/src/postprocessors/ElementVariablePostprocessor.C
  framework/src/postprocessors/ElementalVariableValue.C
  framework/src/postprocessors/InterfaceIntegralVariableValuePostprocessor.C
  framework/src/postprocessors/SideIntegralVariablePostprocessor.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/transfers/MultiAppVariableValueSamplePostprocessorTransfer.C
  framework/src/transfers/MultiAppVariableValueSampleTransfer.C
  framework/src/userobject/ElementIntegralVariableUserObject.C
  framework/src/userobject/SideIntegralVariableUserObject.C
  framework/src/vectorpostprocessors/PointSamplerBase.C
  modules/phase_field/src/postprocessors/PFCElementEnergyIntegral.C
  test/tests/postprocessors/element_integral_var_pps/gold/pps_old_value_fv_out.e
  test/tests/postprocessors/element_integral_var_pps/pps_old_value_fv.i
  test/tests/postprocessors/element_integral_var_pps/tests
  test/tests/postprocessors/element_variable_value/elemental_variable_value_fv.i
  test/tests/postprocessors/element_variable_value/gold/elemental_variable_value_fv_out.csv
  test/tests/postprocessors/element_variable_value/tests
  test/tests/postprocessors/interface_value/gold/InterfaceAverageVariableValuePostprocessor_fe.e
  test/tests/postprocessors/interface_value/gold/InterfaceAverageVariableValuePostprocessor_fv.e
  test/tests/postprocessors/interface_value/gold/InterfaceIntegralVariableValuePostprocessor_fe.e
  test/tests/postprocessors/interface_value/gold/InterfaceIntegralVariableValuePostprocessor_fv.e
  test/tests/postprocessors/interface_value/gold/interface_integral_variable_value_postprocessor_out.e
  test/tests/postprocessors/interface_value/interface_fe_variable_value_postprocessor.i
  test/tests/postprocessors/interface_value/interface_fv_variable_value_postprocessor.i
  test/tests/postprocessors/interface_value/tests
  test/tests/postprocessors/side_integral/gold/fv_out.e
  test/tests/postprocessors/side_integral/side_integral_fv_test.i
  test/tests/postprocessors/side_integral/tests
  test/tests/transfers/multiapp_variable_value_sample_transfer/gold/master_fv_out_pp_sub0.e
  test/tests/transfers/multiapp_variable_value_sample_transfer/gold/master_fv_out_pp_sub1.e
  test/tests/transfers/multiapp_variable_value_sample_transfer/gold/master_fv_out_sub0.e
  test/tests/transfers/multiapp_variable_value_sample_transfer/gold/master_fv_out_sub1.e
  test/tests/transfers/multiapp_variable_value_sample_transfer/master_fv.i
  test/tests/transfers/multiapp_variable_value_sample_transfer/tests
  test/tests/userobjects/layered_integral/gold/fv_out.e
  test/tests/userobjects/layered_integral/layered_integral_fv_test.i
  test/tests/userobjects/layered_integral/tests
  test/tests/userobjects/layered_side_integral/gold/fv_out.e
  test/tests/userobjects/layered_side_integral/layered_side_integral_fv_test.i
  test/tests/userobjects/layered_side_integral/tests
  test/tests/vectorpostprocessors/point_value_sampler/gold/point_value_sampler_fv_out_point_sample_0001.csv
  test/tests/vectorpostprocessors/point_value_sampler/point_value_sampler_fv.i
  test/tests/vectorpostprocessors/point_value_sampler/tests
Labels: PR: Failed but allowed

#16229 Optimize memory usage in Assemly::init()
  framework/include/base/Assembly.h
  framework/src/base/Assembly.C
Labels: PR: Ready for Review/Merge

#16182 Allow user access to physical locations of mortar qpoints
  framework/include/base/Assembly.h
  framework/include/constraints/MortarConstraintBase.h
  framework/src/base/Assembly.C
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/constraints/MortarConstraintBase.C
  framework/src/problems/FEProblemBase.C
  test/include/constraints/SpatiallyVaryingSource.h
  test/src/constraints/SpatiallyVaryingSource.C
  test/tests/mortar/mortar-q-points/gold/test_out.e
  test/tests/mortar/mortar-q-points/nodal_normals_test_offset_nonmatching_gap.e
  test/tests/mortar/mortar-q-points/nodal_normals_test_offset_nonmatching_gap_fine.jou
  test/tests/mortar/mortar-q-points/test.i
  test/tests/mortar/mortar-q-points/tests
Labels: PR: Ready for Review/Merge

#16224 Heap profiling
  framework/app.mk
  framework/build.mk
  framework/include/base/MooseApp.h
  framework/moose.mk
  framework/src/base/MooseApp.C
  modules/doc/content/application_development/profiling.md
Labels: PR: Ready for Review/Merge

#16254 Remove duplicate requirement and improve contributing page
  modules/doc/content/framework_development/contributing.md
  modules/doc/sqa_reports.yml
  test/tests/scaling/remove-singularity/tests
Labels: PR: Auto Merge

#16245 Fix deprecated required coupled variable
  framework/doc/content/source/utils/InputParameters.md
  framework/src/utils/InputParameters.C
  modules/contact/examples/2d_indenter/indenter_rz_fine.i
Labels: PR: Ready for Review/Merge

#16218 Make split mesh work with mesh meta data without re-run mesh generators
  framework/doc/content/source/meshgenerators/FileMeshGenerator.md
  framework/doc/content/syntax/Mesh/index.md
  framework/doc/content/syntax/Mesh/splitting.md
  framework/include/base/MooseApp.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/src/actions/ExecuteMeshGenerators.C
  framework/src/actions/SetupMeshAction.C
  framework/src/actions/SetupRecoverFileBaseAction.C
  framework/src/actions/SplitMeshAction.C
  framework/src/base/MooseApp.C
  framework/src/mesh/FileMesh.C
  framework/src/meshgenerators/FileMeshGenerator.C
  framework/src/outputs/Checkpoint.C
  test/tests/meshgenerators/file_mesh_generator/2d_diffusion_test.i
  test/tests/meshgenerators/file_mesh_generator/gold/2d_diffusion_test_out.e
  test/tests/meshgenerators/file_mesh_generator/tests
  test/tests/meshgenerators/meta_data_store/mesh_meta_data_store.i
  test/tests/meshgenerators/meta_data_store/tests
  test/tests/restart/restart_steady_from_transient/steady_from_transient_restart.i
Labels: PR: Failed but allowed

#16261 PorousFlow: hysteretic capillary-pressure materials for 2-phase systems
  modules/porous_flow/doc/content/media/porous_flow/hys_2phasePP_1.png
  modules/porous_flow/doc/content/media/porous_flow/hys_2phasePS_2.png
  modules/porous_flow/doc/content/modules/porous_flow/hysteresis.md
  modules/porous_flow/doc/content/modules/porous_flow/multiphase.md
  modules/porous_flow/doc/content/source/materials/PorousFlow2PhaseHysPP.md
  modules/porous_flow/doc/content/source/materials/PorousFlow2PhaseHysPS.md
  modules/porous_flow/include/materials/PorousFlow2PhaseHysPP.h
  modules/porous_flow/include/materials/PorousFlow2PhaseHysPS.h
  modules/porous_flow/src/materials/PorousFlow2PhaseHysPP.C
  modules/porous_flow/src/materials/PorousFlow2PhaseHysPS.C
  modules/porous_flow/test/tests/hysteresis/2phasePP.i
  modules/porous_flow/test/tests/hysteresis/2phasePP_2.i
  modules/porous_flow/test/tests/hysteresis/2phasePP_jac.i
  modules/porous_flow/test/tests/hysteresis/2phasePS.i
  modules/porous_flow/test/tests/hysteresis/2phasePS_2.i
  modules/porous_flow/test/tests/hysteresis/2phasePS_jac.i
  modules/porous_flow/test/tests/hysteresis/except14.i
  modules/porous_flow/test/tests/hysteresis/except15.i
  modules/porous_flow/test/tests/hysteresis/gold/2phasePP_2_out.csv
  modules/porous_flow/test/tests/hysteresis/gold/2phasePP_out.csv
  modules/porous_flow/test/tests/hysteresis/gold/2phasePS_2_out.csv
  modules/porous_flow/test/tests/hysteresis/gold/2phasePS_out.csv
  modules/porous_flow/test/tests/hysteresis/hys.py
  modules/porous_flow/test/tests/hysteresis/tests
Labels: PR: Failed but allowed

#16133 Geochemistry: use static to fix threading problem
  modules/geochemistry/include/userobjects/GeochemistrySpatialReactor.h
  modules/geochemistry/src/userobjects/GeochemistrySpatialReactor.C
  modules/geochemistry/test/tests/spatial_reactor/tests
Labels: PR: Failed but allowed

#16300 Geochemistry: change tests files for SQA
  modules/geochemistry/test/tests/equilibrium_models/tests
  modules/geochemistry/test/tests/geochemistry_quantity_aux/tests
  modules/geochemistry/test/tests/interrogate_reactions/tests
  modules/geochemistry/test/tests/kernels/tests
  modules/geochemistry/test/tests/kinetics/tests
  modules/geochemistry/test/tests/nodal_void_volume/tests
  modules/geochemistry/test/tests/postprocessors/tests
  modules/geochemistry/test/tests/redox_disequilibrium/tests
  modules/geochemistry/test/tests/solubilities_and_activities/tests
  modules/geochemistry/test/tests/sorption_and_surface_complexation/tests
  modules/geochemistry/test/tests/spatial_reactor/tests
  modules/geochemistry/test/tests/time_dependent_reactions/tests
Labels: PR: Failed but allowed

#16024 Enable finite strain elastic anisotropic material
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankFourTensorImplementation.h
  modules/tensor_mechanics/doc/content/source/materials/ComputeElasticityTensor.md
  modules/tensor_mechanics/include/materials/ADComputeFiniteStrainElasticStress.h
  modules/tensor_mechanics/include/materials/ComputeFiniteStrainElasticStress.h
  modules/tensor_mechanics/src/materials/ADComputeFiniteStrainElasticStress.C
  modules/tensor_mechanics/src/materials/ComputeFiniteStrainElasticStress.C
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/3d_bar_orthotropic.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/3d_bar_orthotropic_90deg_rotation.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/3d_bar_orthotropic_90deg_rotation_ad.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/3d_bar_orthotropic_full_rotation.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/3d_bar_orthotropic_full_rotation_ad.i
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/gold/3d_bar_orthotropic_90deg_rotation_ad_out.e
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/gold/3d_bar_orthotropic_90deg_rotation_out.e
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/gold/3d_bar_orthotropic_full_rotation_ad_out.e
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/gold/3d_bar_orthotropic_full_rotation_out.e
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/gold/3d_bar_orthotropic_out.e
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/ortho.cmp
  modules/tensor_mechanics/test/tests/finite_strain_elastic_anisotropy/tests
  unit/src/RankFourTensorTest.C
Labels: PR: Failed but allowed

#16306 moosedocs mod dict fix 16304
  python/MooseDocs/tree/tokens.py
Labels: PR: Failed but allowed

#15758 Add Smagorinsky large eddy simulation kernel to Navier Stokes module
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/source/auxkernels/INSQCriterionAux.md
  modules/navier_stokes/doc/content/source/kernels/INSADSmagorinskyEddyViscosity.md
  modules/navier_stokes/include/auxkernels/INSQCriterionAux.h
  modules/navier_stokes/include/kernels/INSADSmagorinskyEddyViscosity.h
  modules/navier_stokes/src/auxkernels/INSQCriterionAux.C
  modules/navier_stokes/src/kernels/INSADSmagorinskyEddyViscosity.C
  modules/navier_stokes/test/tests/ins/lid_driven/ad_lid_driven_les.i
  modules/navier_stokes/test/tests/ins/lid_driven/gold/ad_lid_driven_les_out.e
  modules/navier_stokes/test/tests/ins/lid_driven/tests
Labels: PR: Failed but allowed

#16269 Dont duplicate NodalKernel computation on interfaces
  framework/src/loops/ComputeNodalKernelsThread.C
  test/tests/nodalkernels/multiple-subdomains/gold/test_out.e
  test/tests/nodalkernels/multiple-subdomains/test.i
  test/tests/nodalkernels/multiple-subdomains/tests
Labels: PR: Failed but allowed

#16313 PorousFlow: JOSS bibliography update
  modules/porous_flow/paper.bib
Labels: PR: Failed but allowed

#16309 Geochemistry: copyright in all C and h files
  modules/geochemistry/src/userobjects/GeochemistrySpatialReactor.C
  modules/geochemistry/src/userobjects/GeochemistryTimeDependentReactor.C
  modules/geochemistry/src/userobjects/GeochemistryTimeIndependentReactor.C
Labels: PR: Failed but allowed

#15743 Enthalpy injection dirac kernel
  modules/porous_flow/doc/content/modules/porous_flow/sinks.md
  modules/porous_flow/doc/content/source/dirackernels/PorousFlowPointEnthalpySourceFromPostprocessor.md
  modules/porous_flow/include/dirackernels/PorousFlowPointEnthalpySourceFromPostprocessor.h
  modules/porous_flow/src/dirackernels/PorousFlowPointEnthalpySourceFromPostprocessor.C
  modules/porous_flow/test/tests/dirackernels/gold/hfrompps.csv
  modules/porous_flow/test/tests/dirackernels/hfrompps.i
  modules/porous_flow/test/tests/dirackernels/tests
  modules/porous_flow/test/tests/jacobian/hfrompps.i
  modules/porous_flow/test/tests/jacobian/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16292 Improve regex for inline links
  framework/doc/content/source/kernels/Kernel.md
  python/MooseDocs/extensions/core.py
  python/MooseDocs/test/extensions/test_core.py
Labels: PR: Failed but allowed

#16299 PorousFlow: utils for hysteretic relative permeabilities added
  modules/porous_flow/include/utils/PorousFlowCubic.h
  modules/porous_flow/include/utils/PorousFlowVanGenuchten.h
  modules/porous_flow/src/utils/PorousFlowCubic.C
  modules/porous_flow/src/utils/PorousFlowVanGenuchten.C
  modules/porous_flow/test/tests/hysteresis/hys.py
  modules/porous_flow/unit/src/PorousFlowCubicTest.C
  modules/porous_flow/unit/src/PorousFlowVanGenuchtenTest.C
Labels: PR: Failed but allowed

#16317 Add a control parameter to allow profiler to be started only on selected processors
  framework/src/base/MooseApp.C
  modules/doc/content/application_development/profiling.md
Labels: PR: Failed but allowed
