Repository idaholab/moose, pull requests merged in 2020-06, with the labels that each got.

#15357 Fix prereq and working_directory
  python/TestHarness/JobDAG.py
  python/TestHarness/tests/test_WorkingDirectory.py
  test/tests/test_harness/sub_directory_dependency/gold/sub_good_exodiff_out.e
  test/tests/test_harness/sub_directory_dependency/sub_good.i
  test/tests/test_harness/working_directory
Labels: PR: Ready for Review/Merge

#15304 DARK MODE
  framework/doc/content/css/alert_moose.css
  framework/doc/content/css/moose.css
  modules/doc/content/getting_started/installation/windows10.md
  modules/doc/content/getting_started/installation/wsl.md
  modules/doc/content/help/faq/build_issues.md
  modules/doc/content/help/faq/catalina_caveats.md
  modules/doc/content/help/faq/conda_issues.md
  modules/doc/content/help/faq/failing_tests.md
  modules/doc/content/help/faq/index.md
  modules/doc/content/help/troubleshooting.md
  modules/doc/content/python/MooseDocs/extensions/style.md
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15195 Add hasADMaterialProperty* APIs
  framework/include/materials/MaterialPropertyInterface.h
  test/src/kernels/ADMatDiffusionTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15378 Fix JIT include paths
  framework/moose.mk
Labels: PR: Auto Merge, PR: Failed but allowed

#15377 Properly scope console timed print
  framework/src/problems/FEProblemBase.C
Labels: PR: Ready for Review/Merge

#15387 suppress valgrind memory leak from boost math
  python/TestHarness/suppressions/errors.supp
Labels: PR: Failed but allowed

#15383 Hit format stdin
  framework/contrib/hit/main.cc
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15385 int -> PetscBLASInt
  framework/include/utils/RankTwoTensorImplementation.h
  framework/src/problems/EigenProblem.C
  framework/src/utils/ColumnMajorMatrix.C
  framework/src/utils/MatrixTools.C
  modules/solid_mechanics/src/materials/RateDepSmearCrackModel.C
  modules/tensor_mechanics/src/materials/MultiParameterPlasticityStressUpdate.C
  modules/tensor_mechanics/src/utils/MultiPlasticityLinearSystem.C
  modules/xfem/src/base/XFEMCutElem2D.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15398 Added triple-point temperature interface to TwoPhaseFluidProperties
  modules/fluid_properties/include/userobjects/StiffenedGasTwoPhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/TwoPhaseFluidProperties.h
  modules/fluid_properties/src/userobjects/StiffenedGasTwoPhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/TwoPhaseFluidProperties.C
  modules/fluid_properties/unit/include/StiffenedGasTwoPhaseFluidPropertiesTest.h
  modules/fluid_properties/unit/src/StiffenedGasTwoPhaseFluidPropertiesTest.C
Labels: PR: Failed but allowed

#15302 Code verification problems for 1D heat conduction in each coordinate system
  modules/heat_conduction/test/tests/code_verification/cartesian_test_no1.i
  modules/heat_conduction/test/tests/code_verification/cartesian_test_no2.i
  modules/heat_conduction/test/tests/code_verification/cartesian_test_no3.i
  modules/heat_conduction/test/tests/code_verification/cartesian_test_no4.i
  modules/heat_conduction/test/tests/code_verification/cartesian_test_no5.i
  modules/heat_conduction/test/tests/code_verification/cylindrical_test_no1.i
  modules/heat_conduction/test/tests/code_verification/cylindrical_test_no2.i
  modules/heat_conduction/test/tests/code_verification/cylindrical_test_no3.i
  modules/heat_conduction/test/tests/code_verification/cylindrical_test_no4.i
  modules/heat_conduction/test/tests/code_verification/cylindrical_test_no5.i
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no1_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no2_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no2_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no3_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no3_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no4_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no5_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cartesian_test_no5_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no1_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no1_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no2_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no2_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no3_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no3_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no4_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no4_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no5_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/cylindrical_test_no5_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no1_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no1_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no2_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no2_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no3_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no3_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no4_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no4_second_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no5_first_order.csv
  modules/heat_conduction/test/tests/code_verification/gold/spherical_test_no5_second_order.csv
  modules/heat_conduction/test/tests/code_verification/mes_spatial.py
  modules/heat_conduction/test/tests/code_verification/spherical_test_no1.i
  modules/heat_conduction/test/tests/code_verification/spherical_test_no2.i
  modules/heat_conduction/test/tests/code_verification/spherical_test_no3.i
  modules/heat_conduction/test/tests/code_verification/spherical_test_no4.i
  modules/heat_conduction/test/tests/code_verification/spherical_test_no5.i
  modules/heat_conduction/test/tests/code_verification/tests
Labels: PR: Failed but allowed

#15395 Removing deprecated parameter
  modules/heat_conduction/include/bcs/ConvectiveFluxFunction.h
  modules/heat_conduction/src/bcs/ConvectiveFluxFunction.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15381 Add linear extroplation to LinearInterpolation
  framework/include/materials/ADPiecewiseLinearInterpolationMaterial.h
  framework/include/materials/PiecewiseLinearInterpolationMaterial.h
  framework/include/utils/LinearInterpolation.h
  framework/src/materials/ADPiecewiseLinearInterpolationMaterial.C
  framework/src/materials/PiecewiseLinearInterpolationMaterial.C
  framework/src/utils/LinearInterpolation.C
  test/tests/materials/ad_piecewise_linear_interpolation_material/tests
  test/tests/materials/piecewise_linear_interpolation_material/tests
Labels: PR: Failed but allowed

#15401 Eliminate console race condition in adaptMesh
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed

#15413 Fix Install Miniconda link
  modules/doc/content/getting_started/installation/remove_moose_environment.md
Labels: PR: Failed but allowed

#15403 Allow to control 'solve' parameter
  framework/doc/content/source/controls/BoolFunctionControl.md
  framework/include/controls/BoolFunctionControl.h
  framework/include/problems/FEProblemBase.h
  framework/src/controls/BoolFunctionControl.C
  framework/src/problems/FEProblemBase.C
  test/tests/controls/bool_function_control/bool_function_control.i
  test/tests/controls/bool_function_control/gold/bool_function_control_out.csv
  test/tests/controls/bool_function_control/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15431 Made average and extreme material property PPs AD-compatible
  framework/include/postprocessors/ElementAverageMaterialProperty.h
  framework/include/postprocessors/ElementExtremeMaterialProperty.h
  framework/src/postprocessors/ElementAverageMaterialProperty.C
  framework/src/postprocessors/ElementExtremeMaterialProperty.C
  test/tests/postprocessors/element_average_material_property/tests
  test/tests/postprocessors/element_extreme_material_property/tests
Labels: PR: Failed but allowed

#15430 Removed the slepc link
  scripts/update_and_rebuild_petsc.sh
Labels: PR: Failed but allowed

#15427 Adding scale_factor to CoupledConvectiveHeatFluxBC
  modules/heat_conduction/doc/content/source/bcs/CoupledConvectiveHeatFluxBC.md
  modules/heat_conduction/include/bcs/CoupledConvectiveHeatFluxBC.h
  modules/heat_conduction/src/bcs/CoupledConvectiveHeatFluxBC.C
  modules/heat_conduction/test/tests/heat_conduction/coupled_convective_heat_flux/gold/on_off_out.e
  modules/heat_conduction/test/tests/heat_conduction/coupled_convective_heat_flux/on_off.i
  modules/heat_conduction/test/tests/heat_conduction/coupled_convective_heat_flux/tests
Labels: PR: Failed but allowed

#15432 Remove the legacy code of eigenvalue solver
  framework/include/utils/MooseTypes.h
  framework/src/problems/EigenProblem.C
  framework/src/utils/Conversion.C
  framework/src/utils/SlepcSupport.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15435 Adding PostprocessorSpatialUserObject
  framework/doc/content/source/userobject/PostprocessorSpatialUserObject.md
  framework/include/userobject/PostprocessorSpatialUserObject.h
  framework/src/userobject/PostprocessorSpatialUserObject.C
  test/tests/userobjects/postprocessor_spatial_user_object/gold/master_out.e
  test/tests/userobjects/postprocessor_spatial_user_object/master.i
  test/tests/userobjects/postprocessor_spatial_user_object/slave.i
  test/tests/userobjects/postprocessor_spatial_user_object/tests
Labels: PR: Failed but allowed

#15443 Simplify Conda Install, Create Offline Install
  modules/doc/content/getting_started/index.md
  modules/doc/content/getting_started/installation/conda.md
  modules/doc/content/getting_started/installation/install_conda_moose.md
  modules/doc/content/getting_started/installation/install_miniconda.md
  modules/doc/content/getting_started/installation/offline_installation.md
  modules/doc/content/help/development/ccache.md
  modules/doc/content/help/faq/conda_issues.md
Labels: PR: Failed but allowed

#15453 Restrict test to max_parallel = 2
  test/tests/userobjects/postprocessor_spatial_user_object/tests
Labels: PR: Failed but allowed

#15451 remove mention of the moose-envoronment package
  modules/doc/content/getting_started/installation/bash_profile.md
  modules/doc/content/getting_started/installation/catalina_profile.md
  modules/doc/content/getting_started/installation/centos.md
  modules/doc/content/getting_started/installation/centos_pre_req.md
  modules/doc/content/getting_started/installation/deprecated_instructions.md
  modules/doc/content/getting_started/installation/fedora.md
  modules/doc/content/getting_started/installation/fedora_pre_req.md
  modules/doc/content/getting_started/installation/install_redistributable_deb.md
  modules/doc/content/getting_started/installation/install_redistributable_rpm.md
  modules/doc/content/getting_started/installation/macos_bash_profile.md
  modules/doc/content/getting_started/installation/macos_catalina.md
  modules/doc/content/getting_started/installation/macos_catalina_pre_req.md
  modules/doc/content/getting_started/installation/macos_mojave.md
  modules/doc/content/getting_started/installation/macos_mojave_pre_req.md
  modules/doc/content/getting_started/installation/macos_other.md
  modules/doc/content/getting_started/installation/macos_other_pre_req.md
  modules/doc/content/getting_started/installation/manual_environment.md
  modules/doc/content/getting_started/installation/mint.md
  modules/doc/content/getting_started/installation/mint_pre_req.md
  modules/doc/content/getting_started/installation/offline_installation.md
  modules/doc/content/getting_started/installation/opensuse.md
  modules/doc/content/getting_started/installation/opensuse_pre_req.md
  modules/doc/content/getting_started/installation/post_linux_install.md
  modules/doc/content/getting_started/installation/ubuntu.md
  modules/doc/content/getting_started/installation/ubuntu_pre_req.md
Labels: PR: Failed but allowed

#14982 Geochemistry equilibrium constant interpolators
  framework/include/utils/LeastSquaresFitBase.h
  framework/src/utils/LeastSquaresFitBase.C
  modules/geochemistry/database/moose_geochemdb.json
  modules/geochemistry/include/utils/EquilibriumConstantInterpolator.h
  modules/geochemistry/include/utils/GeochemicalDatabaseReader.h
  modules/geochemistry/python/database_converter.py
  modules/geochemistry/python/dbclass.py
  modules/geochemistry/python/readers/eq36_reader.py
  modules/geochemistry/python/readers/gwb_reader.py
  modules/geochemistry/python/readers/reader_utils.py
  modules/geochemistry/python/tests/test_eq36reader.py
  modules/geochemistry/python/tests/test_gwbreader.py
  modules/geochemistry/python/tests/test_readerutils.py
  modules/geochemistry/python/tests/tests
  modules/geochemistry/src/utils/EquilibriumConstantInterpolator.C
  modules/geochemistry/src/utils/GeochemicalDatabaseReader.C
  modules/geochemistry/unit/database/moose_testdb.json
  modules/geochemistry/unit/src/EquilibriumConstantInterpolatorTest.C
  modules/geochemistry/unit/src/GeochemicalDatabaseReaderTest.C
Labels: PR: Failed but allowed

#15322 Change coefficient in piecewise interpolation functions and materials to pp
  framework/include/functions/PiecewiseBase.h
  framework/include/materials/PiecewiseLinearInterpolationMaterial.h
  framework/src/functions/PiecewiseBase.C
  framework/src/materials/PiecewiseLinearInterpolationMaterial.C
  test/tests/controls/control_piecewise/controlled_piecewise.i
  test/tests/controls/control_piecewise/gold/controlled_piecewise_out.e
  test/tests/controls/control_piecewise/tests
Labels: PR: Failed but allowed

#15447 Add --enable-nodeconstraint in update_and_rebuild_libmesh.sh
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed

#15463 Update Conda and MOOSE repository
  modules/doc/content/getting_started/installation/install_conda_moose.md
  modules/doc/content/getting_started/installation/install_miniconda.md
  modules/doc/content/getting_started/installation/update_moose.md
Labels: PR: Failed but allowed

#15465 Small number of cores for partition
  framework/include/meshgenerators/DistributedRectilinearMeshGenerator.h
  framework/include/partitioner/PetscExternalPartitioner.h
  framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C
  framework/src/partitioner/PetscExternalPartitioner.C
  test/tests/meshgenerators/distributed_rectilinear_mesh_generator/gold/drmg_3d_scomm_out.e
  test/tests/meshgenerators/distributed_rectilinear_mesh_generator/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15469 Enhance subdomain bounding box generator
  framework/doc/content/source/meshgenerators/SubdomainBoundingBoxGenerator.md
  framework/include/meshgenerators/SubdomainBoundingBoxGenerator.h
  framework/src/meshgenerators/SubdomainBoundingBoxGenerator.C
  test/tests/meshgenerators/subdomain_bounding_box_generator/gold/subdomain_bounding_box_generator_restricted_in.e
  test/tests/meshgenerators/subdomain_bounding_box_generator/subdomain_bounding_box_generator_restricted.i
  test/tests/meshgenerators/subdomain_bounding_box_generator/tests
Labels: PR: Failed but allowed

#15456 Update docs, fix unity build
  framework/contrib/pcre/include/config.h
  framework/moose.mk
  modules/doc/content/getting_started/installation/msys2.md
Labels: PR: Do Not Merge, PR: Failed but allowed

#15466 AD DerivativeParsedMaterial
  framework/src/materials/DerivativeParsedMaterial.C
  framework/src/materials/DerivativeParsedMaterialHelper.C
  test/tests/materials/derivative_material_interface/ad_derivative_parsed_material.i
  test/tests/materials/derivative_material_interface/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15449 Add (vector)postprocessors and snip markers to dump problem
  framework/include/problems/DumpObjectsProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/samplers/Sampler.h
  framework/src/problems/DumpObjectsProblem.C
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15389 Avoid use of libmesh_deprecated() APIs
  framework/src/base/Assembly.C
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/mesh/AnnularMesh.C
  framework/src/mesh/ConcentricCircleMesh.C
  framework/src/mesh/FileMesh.C
  framework/src/mesh/MooseMesh.C
  framework/src/mesh/RinglebMesh.C
  framework/src/mesh/SpiralAnnularMesh.C
  framework/src/mesh/TiledMesh.C
  framework/src/meshgenerators/AllSideSetsByNormalsGenerator.C
  framework/src/meshgenerators/AnnularMeshGenerator.C
  framework/src/meshgenerators/ConcentricCircleMeshGenerator.C
  framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C
  framework/src/meshgenerators/ElementDeletionGeneratorBase.C
  framework/src/meshgenerators/FancyExtruderGenerator.C
  framework/src/meshgenerators/FileMeshGenerator.C
  framework/src/meshgenerators/PatchMeshGenerator.C
  framework/src/meshgenerators/RinglebMeshGenerator.C
  framework/src/meshgenerators/SideSetsFromNormalsGenerator.C
  framework/src/meshgenerators/SpiralAnnularMeshGenerator.C
  framework/src/meshmodifiers/ParsedAddSideset.C
  framework/src/userobject/SolutionUserObject.C
  modules/external_petsc_solver/src/mesh/PETScDMDAMesh.C
  modules/heat_conduction/src/meshgenerators/PatchSidesetGenerator.C
  modules/peridynamics/src/mesh/PeridynamicsMesh.C
  modules/phase_field/include/postprocessors/FeatureFloodCount.h
  modules/phase_field/src/meshgenerators/SphereSurfaceMeshGenerator.C
  modules/xfem/src/base/XFEM.C
Labels: PR: Failed but allowed

#15480 Add compile error message
  framework/src/utils/ADFParser.C
Labels: PR: Failed but allowed

#15323 PorousFlow JOSS improvements to documentation
  modules/porous_flow/doc/content/bib/porous_flow.bib
  modules/porous_flow/doc/content/modules/porous_flow/getting_started_with_pf.md
  modules/porous_flow/doc/content/modules/porous_flow/index.md
  modules/porous_flow/doc/content/modules/porous_flow/lava_lamp.md
  modules/porous_flow/examples/lava_lamp/1phase_convection.i
  modules/porous_flow/examples/lava_lamp/2phase_convection.i
  modules/porous_flow/paper.md
Labels: PR: Failed but allowed

#15459 Move crack definition test to tensor mechanics
  modules/tensor_mechanics/test/tests/crack_loop/crack_loop.e
  modules/tensor_mechanics/test/tests/crack_loop/crack_loop.i
  modules/tensor_mechanics/test/tests/crack_loop/tests
Labels: PR: Failed but allowed

#15405 refactor fourth order tensor fill methods for efficiency
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankFourTensorImplementation.h
  unit/src/RankFourTensorTest.C
Labels: PR: Failed but allowed

#15364 Verify user's conda libmesh version before building.
  framework/moose.mk
  scripts/verify_conda_libmesh.py
Labels: PR: Failed but allowed

#15423 Mark materials as constant on subdomain
  framework/include/materials/GenericConstantRankTwoTensor.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialData.h
  framework/src/materials/GenericConstant2DArray.C
  framework/src/materials/GenericConstantArray.C
  framework/src/materials/GenericConstantMaterial.C
  framework/src/materials/GenericConstantRankTwoTensor.C
  framework/src/materials/Material.C
  framework/src/materials/MaterialBase.C
  modules/combined/test/tests/ad_power_law_creep/power_law_creep.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_restart1.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_restart2.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_simple.i
  modules/combined/test/tests/ad_power_law_creep/power_law_creep_smallstrain.i
  modules/contact/test/tests/sliding_block/in_and_out/frictional_02_penalty.i
  modules/contact/test/tests/sliding_block/in_and_out/frictional_04_penalty.i
  modules/contact/test/tests/sliding_block/in_and_out/frictional_lm.i
  modules/contact/test/tests/sliding_block/in_and_out/frictionless_kinematic.i
  modules/contact/test/tests/sliding_block/in_and_out/frictionless_lm.i
  modules/contact/test/tests/sliding_block/in_and_out/frictionless_penalty.i
  modules/contact/test/tests/sliding_block/in_and_out/frictionless_penalty_contact_line_search.i
  modules/contact/test/tests/tan-pen-and-scaling/bouncing-block-tan-pen.i
  modules/phase_field/include/materials/ConstantAnisotropicMobility.h
  modules/phase_field/src/materials/ConstantAnisotropicMobility.C
  modules/tensor_mechanics/include/materials/ComputeElasticityTensorCP.h
  modules/tensor_mechanics/include/materials/ComputeGlobalStrain.h
  modules/tensor_mechanics/src/materials/ComputeGlobalStrain.C
  test/include/materials/SubdomainConstantMaterial.h
  test/src/materials/IncrementMaterial.C
  test/src/materials/SubdomainConstantMaterial.C
Labels: PR: Failed but allowed

#15493 shorten names of tests in distributed_rectilinear_mesh_generator
  test/tests/meshgenerators/distributed_rectilinear_mesh_generator/tests
Labels: PR: Failed but allowed

#15496 Generalize MaterialAuxBase
  framework/doc/content/source/auxkernels/VectorMaterialRealVectorValueAux.md
  framework/include/auxkernels/MaterialAuxBase.h
  framework/include/auxkernels/VectorMaterialRealVectorValueAux.h
  framework/src/auxkernels/VectorMaterialRealVectorValueAux.C
  test/include/materials/VectorCoupledValuesMaterial.h
  test/src/materials/VectorCoupledValuesMaterial.C
  test/tests/auxkernels/vector_material_real_vector_value/gold/test_out.e
  test/tests/auxkernels/vector_material_real_vector_value/test.i
  test/tests/auxkernels/vector_material_real_vector_value/tests
Labels: PR: Failed but allowed

#15488 Add `unique_test_id` parameter to TestHarness.
  python/TestHarness/testers/Tester.py
  test/tests/mesh/unique_ids/tests
Labels: PR: Failed but allowed

#15438 Add AD to XFEM BiMaterials
  modules/xfem/doc/content/source/materials/LevelSetBiMaterialRankFour.md
  modules/xfem/include/materials/LevelSetBiMaterialBase.h
  modules/xfem/include/materials/LevelSetBiMaterialRankFour.h
  modules/xfem/include/materials/LevelSetBiMaterialRankTwo.h
  modules/xfem/include/materials/LevelSetBiMaterialReal.h
  modules/xfem/src/materials/LevelSetBiMaterialBase.C
  modules/xfem/src/materials/LevelSetBiMaterialRankFour.C
  modules/xfem/src/materials/LevelSetBiMaterialRankTwo.C
  modules/xfem/src/materials/LevelSetBiMaterialReal.C
  modules/xfem/test/tests/bimaterials/glued_ad_bimaterials_2d.i
  modules/xfem/test/tests/bimaterials/inclusion_ad_bimaterials_2d.i
  modules/xfem/test/tests/bimaterials/tests
  modules/xfem/test/tests/moving_interface/ad_phase_transition.i
  modules/xfem/test/tests/moving_interface/moving_ad_bimaterial.i
  modules/xfem/test/tests/moving_interface/moving_ad_diffusion.i
  modules/xfem/test/tests/moving_interface/tests
Labels: PR: Failed but allowed

#15118 Generalize split method to work with elements of any size
  modules/xfem/include/efa/EFAElement.h
  modules/xfem/include/efa/EFAElement2D.h
  modules/xfem/include/efa/EFAElement3D.h
  modules/xfem/src/efa/EFAElement2D.C
  modules/xfem/src/efa/EFAElement3D.C
  modules/xfem/src/efa/EFAFragment2D.C
  modules/xfem/test/tests/corner_nodes_cut/gold/corner_edge_cut_out.e
  modules/xfem/test/tests/corner_nodes_cut/gold/corner_node_cut_out.e
  modules/xfem/test/tests/corner_nodes_cut/gold/corner_node_cut_twice_out.e
  modules/xfem/test/tests/second_order_elements/gold/square_branch_tri6_2d_out.e
  modules/xfem/test/tests/second_order_elements/gold/square_branch_tri6_2d_out.e-s002
  modules/xfem/test/tests/second_order_elements/gold/square_branch_tri6_2d_out.e-s003
  modules/xfem/test/tests/solid_mechanics_basic/gold/square_branch_tri_2d_out.e
  modules/xfem/test/tests/solid_mechanics_basic/gold/square_branch_tri_2d_out.e-s002
  modules/xfem/test/tests/solid_mechanics_basic/gold/square_branch_tri_2d_out.e-s003
  modules/xfem/test/tests/solid_mechanics_basic/tests
  unit/src/ElementFragmentAlgorithmTest.C
Labels: PR: Failed but allowed

#15470 Allow block-specific custom volume quadrature rules
  framework/include/actions/SetupQuadratureAction.h
  framework/include/base/Assembly.h
  framework/include/loops/MaxQpsThread.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/src/actions/SetupQuadratureAction.C
  framework/src/base/Assembly.C
  framework/src/loops/MaxQpsThread.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  test/include/materials/QuadratureOrderBumper.h
  test/src/materials/QuadratureOrderBumper.C
  test/tests/quadrature/order/block-order.i
  test/tests/quadrature/order/code-order-bump.i
  test/tests/quadrature/order/gold/block-order_out.csv
  test/tests/quadrature/order/gold/code-order-bump_out.csv
  test/tests/quadrature/order/tests
Labels: PR: Failed but allowed

#15512 Remove training announcement and add webinar recording info
  modules/doc/content/upcoming_training.md
Labels: PR: Failed but allowed

#15485 ghostGhostedBoundaries
  framework/include/mesh/MooseMesh.h
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C
  test/include/userobjects/CheckGhostedBoundaries.h
  test/src/userobjects/CheckGhostedBoundaries.C
  test/tests/bcs/dmg_periodic/dmg_periodic_bc.i
  test/tests/bcs/dmg_periodic/gold/dmg_periodic_bc_out.e
  test/tests/bcs/dmg_periodic/gold/dmg_periodic_bc_out_1d.e
  test/tests/bcs/dmg_periodic/gold/dmg_periodic_bc_out_3d.e
  test/tests/bcs/dmg_periodic/gold/dmg_periodic_bc_out_one_step.e
  test/tests/bcs/dmg_periodic/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15366 Create outline option
  framework/doc/content/css/content_moose.css
  python/MooseDocs/base/executioners.py
  python/MooseDocs/extensions/__init__.py
  python/MooseDocs/extensions/autolink.py
  python/MooseDocs/extensions/content.py
  python/MooseDocs/extensions/core.py
  python/MooseDocs/extensions/heading.py
  python/MooseDocs/test/content/extensions/acronym.md
  python/MooseDocs/test/content/extensions/content.md
  python/MooseDocs/test/content/extensions/core.md
  python/MooseDocs/test/extensions/test_autolink.py
  python/MooseDocs/test/extensions/test_content.py
  python/MooseDocs/test/gold/html/extensions/core.html
  python/MooseDocs/test/gold/latex/extensions/core.tex
  python/MooseDocs/test/gold/materialize/extensions/alert.html
  python/MooseDocs/test/gold/materialize/extensions/amendments.html
  python/MooseDocs/test/gold/materialize/extensions/bibtex.html
  python/MooseDocs/test/gold/materialize/extensions/common.html
  python/MooseDocs/test/gold/materialize/extensions/config.html
  python/MooseDocs/test/gold/materialize/extensions/core.html
  python/MooseDocs/test/gold/materialize/extensions/devel.html
  python/MooseDocs/test/gold/materialize/extensions/example.template.html
  python/MooseDocs/test/gold/materialize/extensions/first.html
  python/MooseDocs/test/gold/materialize/extensions/folder/folder.html
  python/MooseDocs/test/gold/materialize/extensions/folder/index.html
  python/MooseDocs/test/gold/materialize/extensions/gallery.html
  python/MooseDocs/test/gold/materialize/extensions/graph.html
  python/MooseDocs/test/gold/materialize/extensions/include.html
  python/MooseDocs/test/gold/materialize/extensions/katex.html
  python/MooseDocs/test/gold/materialize/extensions/katex_include.html
  python/MooseDocs/test/gold/materialize/extensions/layout.html
  python/MooseDocs/test/gold/materialize/extensions/listing.html
  python/MooseDocs/test/gold/materialize/extensions/listing_include.html
  python/MooseDocs/test/gold/materialize/extensions/materialicon.html
  python/MooseDocs/test/gold/materialize/extensions/media.html
  python/MooseDocs/test/gold/materialize/extensions/navigation.html
  python/MooseDocs/test/gold/materialize/extensions/package.html
  python/MooseDocs/test/gold/materialize/extensions/preamble.html
  python/MooseDocs/test/gold/materialize/extensions/second.html
  python/MooseDocs/test/gold/materialize/extensions/style.html
  python/MooseDocs/test/gold/materialize/extensions/table.html
  python/MooseDocs/test/gold/materialize/extensions/template.html
  python/MooseDocs/test/gold/materialize/index.html
  python/MooseDocs/test/gold/materialize/mega.menu.html
  python/MooseDocs/test/materialize.yml
Labels: PR: Failed but allowed

#15516 Taging warehouse caching fix
  framework/include/warehouses/MooseObjectTagWarehouse.h
  test/tests/tag/controls-tagging.i
  test/tests/tag/gold/controls-tagging_out.e
  test/tests/tag/tests
Labels: PR: Failed but allowed
