Repository idaholab/moose, pull requests merged in 2020-10, with the labels that each got.

#15708 Aug 2020 news
  modules/doc/content/newsletter/2020_08.md
  modules/doc/content/newsletter/2020_09.md
  modules/doc/content/newsletter/2020_10.md
  modules/doc/content/newsletter/2020_11.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15866 Add a default divergence tolerance value
  framework/src/executioners/FEProblemSolve.C
Labels: PR: Auto Merge, PR: Failed but allowed

#15834 Put Piecewise class back in
  framework/include/functions/PiecewiseBase.h
  framework/include/functions/PiecewiseConstant.h
  framework/include/functions/PiecewiseLinearBase.h
  framework/include/functions/PiecewiseTabularBase.h
  framework/src/functions/PiecewiseBase.C
  framework/src/functions/PiecewiseConstant.C
  framework/src/functions/PiecewiseLinearBase.C
  framework/src/functions/PiecewiseTabularBase.C
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15800 Issue15799
  framework/doc/content/source/transfers/MultiAppPostprocessorTransfer.md
  framework/include/transfers/MultiAppPostprocessorTransfer.h
  framework/src/transfers/MultiAppPostprocessorTransfer.C
  test/tests/transfers/multiapp_postprocessor_transfer/from_one_sub_master.i
  test/tests/transfers/multiapp_postprocessor_transfer/gold/from_one_sub_master_out.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/from_one_sub_master_out.e
  test/tests/transfers/multiapp_postprocessor_transfer/gold/from_one_sub_master_out_sub0.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/from_one_sub_master_out_sub0.e
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_from_multiapp_out.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_from_multiapp_out.e
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_from_multiapp_out_sub0.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_from_multiapp_out_sub0.e
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_from_multiapp_out_sub1.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_from_multiapp_out_sub1.e
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_out.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_out.e
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_out_pp_sub0.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_out_pp_sub0.e
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_out_pp_sub1.csv
  test/tests/transfers/multiapp_postprocessor_transfer/gold/master_out_pp_sub1.e
  test/tests/transfers/multiapp_postprocessor_transfer/master.i
  test/tests/transfers/multiapp_postprocessor_transfer/master_from_multiapp.i
  test/tests/transfers/multiapp_postprocessor_transfer/sub.i
  test/tests/transfers/multiapp_postprocessor_transfer/sub0.i
  test/tests/transfers/multiapp_postprocessor_transfer/sub1.i
  test/tests/transfers/multiapp_postprocessor_transfer/tests
Labels: PR: Ready for Review/Merge

#15847 Allow using boundary names in radiative transfer action
  modules/heat_conduction/include/actions/RadiationTransferAction.h
  modules/heat_conduction/include/meshgenerators/PatchSidesetGenerator.h
  modules/heat_conduction/src/actions/RadiationTransferAction.C
  modules/heat_conduction/src/meshgenerators/PatchSidesetGenerator.C
  modules/heat_conduction/test/tests/generate_radiation_patch/generate_radiation_patch.i
  modules/heat_conduction/test/tests/radiation_transfer_action/gold/radiative_transfer_action_out_bnd_names.e
  modules/heat_conduction/test/tests/radiation_transfer_action/radiative_transfer_action.i
  modules/heat_conduction/test/tests/radiation_transfer_action/radiative_transfer_action_external_boundary.i
  modules/heat_conduction/test/tests/radiation_transfer_action/radiative_transfer_no_action.i
  modules/heat_conduction/test/tests/radiation_transfer_action/tests
Labels: PR: Failed but allowed

#15882 Use idaholab as our Conda channel
  conda/README.md
  modules/doc/content/getting_started/installation/install_miniconda.md
  modules/doc/content/help/faq/conda_issues.md
Labels: PR: Failed but allowed

#15865 Add user dev to MOOSE Docker image
  docker_ci/Dockerfile
Labels: PR: Failed but allowed

#15724 Allow SamplerData to output in distributed mode
  modules/stochastic_tools/src/vectorpostprocessors/SamplerData.C
  modules/stochastic_tools/test/tests/samplers/monte_carlo/gold/monte_carlo_uniform_distributed_out_data_0000.csv.0
  modules/stochastic_tools/test/tests/samplers/monte_carlo/gold/monte_carlo_uniform_distributed_out_data_0000.csv.1
  modules/stochastic_tools/test/tests/samplers/monte_carlo/gold/monte_carlo_uniform_distributed_out_data_0001.csv.0
  modules/stochastic_tools/test/tests/samplers/monte_carlo/gold/monte_carlo_uniform_distributed_out_data_0001.csv.1
  modules/stochastic_tools/test/tests/samplers/monte_carlo/tests
Labels: PR: Failed but allowed

#15878 Removed `./` and `../` HIT syntax in `stork/`
  stork/test/tests/kernels/simple_diffusion/simple_diffusion.i
  stork/test/tests/kernels/simple_diffusion/tests
Labels: PR: Failed but allowed

#15888 Disable tests due to unstable MooseDocs executioner (refs #15887)
  python/MooseDocs/test/tests
Labels: PR: Failed but allowed

#15897 Fix location of conf_vars.mk
  framework/build.mk
Labels: PR: Failed but allowed

#15863 prevent negative porosity
  modules/tensor_mechanics/src/materials/ADComputeMultiplePorousInelasticStress.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15902 Rename MooseMesh data member in RelationshipManager
  framework/include/relationshipmanagers/RelationshipManager.h
  framework/src/relationshipmanagers/RelationshipManager.C
Labels: PR: Failed but allowed

#15905 Update copyright
  COPYRIGHT
Labels: PR: Failed but allowed

#15901 Add API for creating specific libMesh mesh type
  framework/doc/content/source/meshgenerators/MeshGenerator.md
  framework/include/mesh/MooseMesh.h
  framework/src/mesh/MooseMesh.C
Labels: PR: Failed but allowed

#15898 Restore sub-sub-apps when needed, even if the sub-app does not need restored
  framework/include/multiapps/FullSolveMultiApp.h
  framework/include/multiapps/MultiApp.h
  framework/src/multiapps/FullSolveMultiApp.C
  framework/src/multiapps/MultiApp.C
  framework/src/problems/FEProblemBase.C
  framework/src/transfers/MultiAppConservativeTransfer.C
  test/include/postprocessors/TestPostprocessor.h
  test/src/postprocessors/TestPostprocessor.C
  test/tests/multiapps/picard_multilevel/gold/picard_master_out_extra_sub10.e
  test/tests/multiapps/picard_multilevel/gold/picard_master_out_sub10.e
  test/tests/multiapps/picard_multilevel/picard_sub.i
  test/tests/multiapps/picard_multilevel/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15830 Add grid partitioning option for PatchSidesetGenerator
  framework/include/mesh/MooseMesh.h
  framework/include/utils/MooseEnum.h
  framework/src/mesh/MooseMesh.C
  framework/src/utils/MooseEnum.C
  modules/heat_conduction/include/meshgenerators/PatchSidesetGenerator.h
  modules/heat_conduction/src/meshgenerators/PatchSidesetGenerator.C
  modules/heat_conduction/test/tests/generate_radiation_patch/generate_radiation_patch_grid.i
  modules/heat_conduction/test/tests/generate_radiation_patch/generate_radiation_patch_grid_2D.i
  modules/heat_conduction/test/tests/generate_radiation_patch/gold/generate_radiation_patch_grid.e
  modules/heat_conduction/test/tests/generate_radiation_patch/gold/generate_radiation_patch_grid_2D_in.e
  modules/heat_conduction/test/tests/generate_radiation_patch/gold/generate_radiation_patch_grid_2D_overpart.e
  modules/heat_conduction/test/tests/generate_radiation_patch/tests
  unit/src/MooseEnumTest.C
Labels: PR: Failed but allowed

#15883 Improve flexibility and testing of new python parameter system
  python/parameters/InputParameters.py
  python/parameters/Parameter.py
  python/parameters/test/test_InputParameters.py
  python/parameters/test/test_Parameter.py
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15806 Kernel density estimation 1D #15789
  modules/stochastic_tools/doc/content/source/distributions/KernelDensity1D.md
  modules/stochastic_tools/include/distributions/KernelDensity1D.h
  modules/stochastic_tools/src/distributions/KernelDensity1D.C
  modules/stochastic_tools/test/tests/distributions/gold/kernel_density_1d_datvec_out.csv
  modules/stochastic_tools/test/tests/distributions/gold/kernel_density_1d_gaussian_out.csv
  modules/stochastic_tools/test/tests/distributions/gold/kernel_density_1d_sdbw_out.csv
  modules/stochastic_tools/test/tests/distributions/gold/kernel_density_1d_uniform_out.csv
  modules/stochastic_tools/test/tests/distributions/gold/kernel_density_1d_userbw_out.csv
  modules/stochastic_tools/test/tests/distributions/kernel_density_1D_input.csv
  modules/stochastic_tools/test/tests/distributions/kernel_density_1d_datvec.i
  modules/stochastic_tools/test/tests/distributions/kernel_density_1d_gaussian.i
  modules/stochastic_tools/test/tests/distributions/kernel_density_1d_sdbw.i
  modules/stochastic_tools/test/tests/distributions/kernel_density_1d_uniform.i
  modules/stochastic_tools/test/tests/distributions/kernel_density_1d_userbw.i
  modules/stochastic_tools/test/tests/distributions/tests
Labels: PR: Failed but allowed

#15862 Added saturation pressure material
  modules/fluid_properties/doc/content/source/materials/SaturationPressureMaterial.md
  modules/fluid_properties/include/materials/SaturationPressureMaterial.h
  modules/fluid_properties/src/materials/SaturationPressureMaterial.C
  modules/fluid_properties/test/tests/materials/saturation_pressure_material/gold/saturation_pressure_material_out.csv
  modules/fluid_properties/test/tests/materials/saturation_pressure_material/saturation_pressure_material.i
  modules/fluid_properties/test/tests/materials/saturation_pressure_material/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15687 Enable EigenProblem user set vector/matrix tag support
  framework/include/systems/AuxiliarySystem.h
  framework/include/systems/DisplacedSystem.h
  framework/include/systems/NonlinearEigenSystem.h
  framework/include/systems/NonlinearSystem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/include/systems/SystemBase.h
  framework/src/problems/EigenProblem.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/systems/NonlinearEigenSystem.C
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/SystemBase.C
  test/tests/tag/eigen_tag.i
  test/tests/tag/gold/eigen_tag_out.e
  test/tests/tag/tests
Labels: PR: Failed but allowed

#15701 Use proper matrix getters instead of public var access
  framework/src/preconditioners/PhysicsBasedPreconditioner.C
  framework/src/systems/NonlinearEigenSystem.C
  framework/src/systems/NonlinearSystem.C
  framework/src/timeintegrators/ActuallyExplicitEuler.C
  framework/src/timeintegrators/ExplicitSSPRungeKutta.C
  framework/src/transfers/MultiAppProjectionTransfer.C
Labels: PR: Failed but allowed

#15815 Adding scale_factor to CoupledVarNeumannBC
  framework/doc/content/source/bcs/CoupledVarNeumannBC.md
  framework/include/bcs/CoupledVarNeumannBC.h
  framework/src/bcs/CoupledVarNeumannBC.C
  test/tests/bcs/coupled_var_neumann/gold/on_off_out.e
  test/tests/bcs/coupled_var_neumann/on_off.i
  test/tests/bcs/coupled_var_neumann/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15909 Remove legacy const_cast for primary and secondary conversion
  modules/heat_conduction/src/materials/GapConductance.C
Labels: PR: Failed but allowed

#15765 Update PETSc Installation instructions
  modules/doc/content/getting_started/installation/hpc_install_moose.md
  modules/doc/content/getting_started/installation/install_moose.md
  modules/doc/content/getting_started/installation/manual_cleanup.md
  modules/doc/content/getting_started/installation/manual_installation_gcc.md
  modules/doc/content/getting_started/installation/manual_installation_llvm.md
  modules/doc/content/getting_started/installation/manual_petsc.md
  modules/doc/content/getting_started/installation/offline_installation.md
  scripts/update_and_rebuild_libmesh.sh
  scripts/update_and_rebuild_petsc.sh
Labels: PR: Failed but allowed

#15916 Combine BodyForce and ADBodyForce
  framework/include/kernels/ADBodyForce.h
  framework/include/kernels/BodyForce.h
  framework/include/kernels/GenericKernel.h
  framework/src/kernels/ADBodyForce.C
  framework/src/kernels/BodyForce.C
  test/include/kernels/GenericValueTest.h
  test/src/kernels/GenericValueTest.C
Labels: PR: Failed but allowed

#15919 Return unique_ptr from buildTypedMesh
  framework/include/mesh/MooseMesh.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/AnnularMeshGenerator.C
  framework/src/meshgenerators/CartesianMeshGenerator.C
  framework/src/meshgenerators/ConcentricCircleMeshGenerator.C
  framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C
  framework/src/meshgenerators/ElementGenerator.C
  framework/src/meshgenerators/FancyExtruderGenerator.C
  framework/src/meshgenerators/FileMeshGenerator.C
  framework/src/meshgenerators/GeneratedMeshGenerator.C
  framework/src/meshgenerators/ImageMeshGenerator.C
  framework/src/meshgenerators/MeshGenerator.C
  framework/src/meshgenerators/PatchMeshGenerator.C
  framework/src/meshgenerators/RinglebMeshGenerator.C
  framework/src/meshgenerators/SpiralAnnularMeshGenerator.C
  modules/heat_conduction/src/meshgenerators/PatchSidesetGenerator.C
  modules/peridynamics/src/meshgenerators/MeshGeneratorPD.C
  modules/phase_field/src/meshgenerators/SphereSurfaceMeshGenerator.C
  test/tests/mesh/nemesis/nemesis_repartitioning_test.i
  unit/include/BuildMeshTest.h
  unit/src/BuildMeshTest.C
Labels: PR: Failed but allowed

#15900 Optionally make x,y,z,t available in ParsedAux expressions
  framework/include/auxkernels/ParsedAux.h
  framework/src/auxkernels/ParsedAux.C
  test/tests/auxkernels/parsed_aux/gold/xyzt_out.e
  test/tests/auxkernels/parsed_aux/parsed_aux_test.i
  test/tests/auxkernels/parsed_aux/tests
  test/tests/auxkernels/parsed_aux/xyzt.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15907 PorousFlow small changes to JOSS paper
  modules/porous_flow/examples/co2_intercomparison/1Dradial/tests
  modules/porous_flow/paper.bib
  modules/porous_flow/paper.md
Labels: PR: Failed but allowed

#15925 thmc extension of the thm benchmark case added to PorousFlow
  modules/porous_flow/doc/content/media/porous_flow/2D_c_fig.png
  modules/porous_flow/doc/content/modules/porous_flow/index.md
  modules/porous_flow/doc/content/modules/porous_flow/thm_example.md
  modules/porous_flow/doc/content/modules/porous_flow/thmc_example.md
  modules/porous_flow/examples/thm_example/2D_c.i
  modules/porous_flow/examples/thm_example/2D_c.py
  modules/porous_flow/examples/thm_example/gold/2D_c_out.e
  modules/porous_flow/examples/thm_example/tests
Labels: PR: Failed but allowed

#15928 Handle HTML special characters
  python/MooseDocs/common/load_config.py
  python/MooseDocs/extensions/__init__.py
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/special.py
  python/MooseDocs/test/content/extensions/special.md
  python/MooseDocs/test/content/index.md
  python/MooseDocs/test/extensions/test_special.py
  python/MooseDocs/test/extensions/tests
  python/MooseDocs/test/gold/html/index.html
  python/MooseDocs/test/gold/latex/index.tex
  python/MooseDocs/test/gold/materialize/index.html
  python/MooseDocs/test/materialize.yml
Labels: PR: Failed but allowed

#15931 Update FAQs, Remove transitional instructions
  modules/doc/content/getting_started/installation/conda.md
  modules/doc/content/help/faq/conda_issues.md
  modules/doc/content/help/faq/faq_build_libmesh-vtk.md
  modules/doc/content/help/faq/faq_build_libmesh.md
  modules/doc/content/help/faq/faq_build_petsc.md
  modules/doc/content/help/faq/faq_conda_alternatives.md
  modules/doc/content/help/faq/index.md
Labels: PR: Failed but allowed

#15935 call meshChanged() earlier
  framework/src/problems/FEProblemBase.C
  test/tests/constraints/equal_value_boundary_constraint/adaptivity.i
  test/tests/constraints/equal_value_boundary_constraint/gold/adaptivity_out.e
  test/tests/constraints/equal_value_boundary_constraint/gold/adaptivity_out.e-s002
  test/tests/constraints/equal_value_boundary_constraint/gold/adaptivity_out.e-s003
  test/tests/constraints/equal_value_boundary_constraint/tests
Labels: PR: Failed but allowed

#15930 Add API to add generate_outputs to TMA
  modules/tensor_mechanics/include/actions/TensorMechanicsActionBase.h
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
Labels: PR: Failed but allowed

#15947 Improve chigger exodus filename sorting
  python/chigger/utils/__init__.py
Labels: PR: Ready for Review/Merge

#15948 Remove deprecated syntax
  modules/combined/test/tests/gap_heat_transfer_convex/gap_heat_transfer_convex_gap_offsets.i
  modules/contact/test/tests/mechanical_constraint/frictionless_kinematic_gap_offsets.i
  modules/stochastic_tools/examples/batch/full_solve.i
  test/tests/vectorpostprocessors/element_id_counters/interface_element_counter.i
  test/tests/vectorpostprocessors/element_id_counters/side_element_counter.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15964 Update deprecated method
  python/TestHarness/XMLDiffer.py
Labels: PR: Failed but allowed

#15959 Fixup API to add generate_outputs to TMA
  modules/tensor_mechanics/include/actions/TensorMechanicsActionBase.h
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
Labels: PR: Failed but allowed

#15957 Automatic name resolution in declareProperty
  framework/include/materials/InterfaceMaterial.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialBase.h
  modules/tensor_mechanics/include/materials/ScalarDamageBase.h
  modules/tensor_mechanics/src/materials/ScalarDamageBase.C
  modules/tensor_mechanics/src/materials/ScalarMaterialDamage.C
  test/include/TemplateStateful.h
  test/include/materials/ADStateful.h
  test/include/materials/Stateful.h
  test/src/materials/ADStateful.C
  test/src/materials/Stateful.C
  test/src/materials/TemplateStateful.C
  test/tests/materials/stateful_prop/gold/stateful_ad_out.e
  test/tests/materials/stateful_prop/gold/stateful_ad_template_out.e
  test/tests/materials/stateful_prop/gold/stateful_reg_out.e
  test/tests/materials/stateful_prop/gold/stateful_reg_template_out.e
  test/tests/materials/stateful_prop/stateful_ad.i
  test/tests/materials/stateful_prop/stateful_ad_template.i
  test/tests/materials/stateful_prop/stateful_reg.i
  test/tests/materials/stateful_prop/stateful_reg_template.i
  test/tests/materials/stateful_prop/tests
Labels: PR: Failed but allowed

#15940 Change references to sidesets to boundary
  modules/heat_conduction/doc/content/syntax/GrayDiffuseRadiation/index.md
  modules/heat_conduction/src/actions/RadiationTransferAction.C
Labels: PR: Failed but allowed

#15896 Block restricted BreakMeshByBlock
  framework/doc/content/source/meshgenerators/BreakMeshByBlockGenerator.md
  framework/include/meshgenerators/BreakMeshByBlockGenerator.h
  framework/include/meshgenerators/BreakMeshByBlockGeneratorBase.h
  framework/src/meshgenerators/BreakMeshByBlockGenerator.C
  test/tests/meshgenerators/break_mesh_by_block_generator/break_mesh_block_restricted.i
  test/tests/meshgenerators/break_mesh_by_block_generator/gold/block_restricted_no_transition_in.e
  test/tests/meshgenerators/break_mesh_by_block_generator/gold/block_restricted_no_transition_split_in.e
  test/tests/meshgenerators/break_mesh_by_block_generator/gold/block_restricted_split_all_in.e
  test/tests/meshgenerators/break_mesh_by_block_generator/gold/block_restricted_split_interface_only_in.e
  test/tests/meshgenerators/break_mesh_by_block_generator/gold/block_restricted_split_transition_only_in.e
  test/tests/meshgenerators/break_mesh_by_block_generator/gold/break_mesh_block_restricted_in.e
  test/tests/meshgenerators/break_mesh_by_block_generator/tests
Labels: PR: Failed but allowed

#15988 add a function to check the existence of mesh meta data and add mesh meta data
  framework/include/base/MooseApp.h
  framework/include/interfaces/MeshMetaDataInterface.h
  framework/include/meshgenerators/AllSideSetsByNormalsGenerator.h
  framework/include/meshgenerators/SideSetsFromNormalsGenerator.h
  framework/src/actions/SetupDebugAction.C
  framework/src/base/MooseApp.C
  framework/src/interfaces/MeshMetaDataInterface.C
  framework/src/meshgenerators/AllSideSetsByNormalsGenerator.C
  framework/src/meshgenerators/SideSetsFromNormalsGenerator.C
  test/include/actions/CheckMeshMetaDataAction.h
  test/src/actions/CheckMeshMetaDataAction.C
  test/src/base/MooseTestApp.C
  test/tests/misc/check_mesh_meta_data/check_mesh_meta_data_test.i
  test/tests/misc/check_mesh_meta_data/tests
Labels: PR: Failed but allowed

#15999 "Fix misc. issues with MOOSE tools"
  modules/stochastic_tools/examples/batch/execute.py
  python/MooseDocs/commands/check.py
  python/MooseDocs/common/check_filenames.py
  python/MooseDocs/test/common/test_check_filenames.py
  python/MooseDocs/test/common/test_project_find.py
  python/MooseDocs/test/common/tests
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/test_Timeout.py
  python/mms/runner.py
  python/moosesqa/SQAMooseAppReport.py
  python/mooseutils/MooseDataFrame.py
  python/mooseutils/VectorPostprocessorReader.py
  python/mooseutils/mooseutils.py
  python/mooseutils/tests/test_VectorPostprocessorReader.py
  python/mooseutils/tests/test_run_executable.py
  python/mooseutils/tests/tests
  scripts/sqa_check.py
  test/tests/samplers/distribute/execute.py
  test/tests/test_harness/timeout
Labels: PR: Ready for Review/Merge

#15950 Properly handle block restriction in INS
  modules/navier_stokes/include/materials/INSAD3Eqn.h
  modules/navier_stokes/include/materials/INSADMaterial.h
  modules/navier_stokes/include/userobjects/INSADObjectTracker.h
  modules/navier_stokes/src/bcs/INSADMomentumNoBCBC.C
  modules/navier_stokes/src/kernels/INSADBoussinesqBodyForce.C
  modules/navier_stokes/src/kernels/INSADEnergyAmbientConvection.C
  modules/navier_stokes/src/kernels/INSADEnergySource.C
  modules/navier_stokes/src/kernels/INSADGravityForce.C
  modules/navier_stokes/src/kernels/INSADMomentumCoupledForce.C
  modules/navier_stokes/src/kernels/INSADMomentumPressure.C
  modules/navier_stokes/src/kernels/INSADMomentumTimeDerivative.C
  modules/navier_stokes/src/kernels/INSADMomentumViscous.C
  modules/navier_stokes/src/materials/INSAD3Eqn.C
  modules/navier_stokes/src/materials/INSADMaterial.C
  modules/navier_stokes/src/userobjects/INSADObjectTracker.C
  modules/navier_stokes/test/tests/ins/block-restriction/gold/one-mat-two-eqn-sets_out.e
  modules/navier_stokes/test/tests/ins/block-restriction/gold/two-mats-one-eqn-set_out.e
  modules/navier_stokes/test/tests/ins/block-restriction/gold/two-mats-two-eqn-sets_out.e
  modules/navier_stokes/test/tests/ins/block-restriction/one-mat-two-eqn-sets.i
  modules/navier_stokes/test/tests/ins/block-restriction/tests
  modules/navier_stokes/test/tests/ins/block-restriction/two-mats-one-eqn-set.i
  modules/navier_stokes/test/tests/ins/block-restriction/two-mats-two-eqn-sets.i
Labels: PR: Failed but allowed

#15986 Flexible choice of MathUtils::poly coefficient containers
  framework/include/utils/MathUtils.h
  framework/src/utils/MathUtils.C
  test/src/functions/PolyTestFunction.C
  unit/src/MathUtilsTest.C
Labels: PR: Failed but allowed

#15960 Read block material properties
  modules/tensor_mechanics/doc/content/source/userobjects/ElementPropertyReadFile.md
  modules/tensor_mechanics/include/userobjects/ElementPropertyReadFile.h
  modules/tensor_mechanics/src/userobjects/ElementPropertyReadFile.C
  modules/tensor_mechanics/test/tests/cp_user_object/gold/prop_block_read_out.e
  modules/tensor_mechanics/test/tests/cp_user_object/prop_block_read.i
  modules/tensor_mechanics/test/tests/cp_user_object/tests
Labels: PR: Failed but allowed

#15792 Fix piecewise linear derivatives
  framework/include/functions/PiecewiseLinearBase.h
  framework/src/functions/PiecewiseLinearBase.C
  test/include/auxkernels/FunctionGradAux.h
  test/src/auxkernels/FunctionDerivativeAux.C
  test/src/auxkernels/FunctionGradAux.C
  test/tests/functions/linear_combination_function/lcf_grad.i
  test/tests/functions/solution_function/solution_function_grad_p2.i
  test/tests/utils/spline_interpolation/bicubic_spline_interpolation.i
  test/tests/utils/spline_interpolation/bicubic_spline_interpolation_x_normal.i
  test/tests/utils/spline_interpolation/bicubic_spline_interpolation_y_normal.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16010 Update build status badge domain
  README.md
Labels: PR: Failed but allowed

#16012 Please do gather periodic boundaries when we need ghosted boundaries
  framework/src/mesh/MooseMesh.C
  test/tests/meshgenerators/distributed_rectilinear_mesh_generator/tests
  test/tests/meshgenerators/dmg_displaced_mesh/tests
  test/tests/mortar/convergence-studies/solution-continuity/tests
Labels: PR: Failed but allowed

#16015 Allow steady energy and transient momentum in stabilized INS
  modules/navier_stokes/include/materials/INSAD3Eqn.h
  modules/navier_stokes/include/materials/INSADMaterial.h
  modules/navier_stokes/include/materials/INSADStabilized3Eqn.h
  modules/navier_stokes/src/kernels/INSADHeatConductionTimeDerivative.C
  modules/navier_stokes/src/materials/INSAD3Eqn.C
  modules/navier_stokes/src/materials/INSADStabilized3Eqn.C
  modules/navier_stokes/src/userobjects/INSADObjectTracker.C
  modules/navier_stokes/test/tests/ins/lid_driven/mixed-transient-steady/gold/mixed_out.e
  modules/navier_stokes/test/tests/ins/lid_driven/mixed-transient-steady/mixed.i
  modules/navier_stokes/test/tests/ins/lid_driven/mixed-transient-steady/tests
Labels: PR: Failed but allowed

#16025 Fix filenames for distributed JSON output of reporters
  test/tests/outputs/json/distributed/tests
Labels: PR: Failed but allowed

#16023 Add natural convection benchmark tests
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/benchmark.i
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e3.e
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e4.e
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e5.e
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/gold/1e6.e
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/tests
Labels: PR: Failed but allowed

#16031 Disable convergence reason printing when Outputs/console=false
  framework/src/actions/CommonOutputAction.C
  framework/src/outputs/Console.C
  test/tests/outputs/console/tests
Labels: PR: Failed but allowed

#16027 Add general addObject() to FEProblemBase
  framework/include/problems/FEProblemBase.h
  framework/src/problems/FEProblemBase.C
  modules/stochastic_tools/src/actions/AddCovarianceAction.C
  modules/stochastic_tools/src/actions/AddSurrogateAction.C
  modules/stochastic_tools/src/actions/LoadCovarianceDataAction.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15810 Auxiliary array variable
  framework/doc/content/source/auxkernels/FunctionArrayAux.md
  framework/doc/content/syntax/AuxKernels/index.md
  framework/include/auxkernels/AuxKernel.h
  framework/include/auxkernels/FunctionArrayAux.h
  framework/include/systems/AuxiliarySystem.h
  framework/src/auxkernels/AuxKernel.C
  framework/src/auxkernels/FunctionArrayAux.C
  framework/src/base/Moose.C
  framework/src/loops/ComputeElemAuxBcsThread.C
  framework/src/loops/ComputeElemAuxVarsThread.C
  framework/src/loops/ComputeNodalAuxBcsThread.C
  framework/src/loops/ComputeNodalAuxVarsThread.C
  framework/src/systems/AuxiliarySystem.C
  test/tests/auxkernels/array_aux_kernels/function_array_aux.i
  test/tests/auxkernels/array_aux_kernels/gold/function_array_aux_out.e
  test/tests/auxkernels/array_aux_kernels/tests
  test/tests/ics/array_function_ic/array_function_ic_test.i
  test/tests/ics/array_function_ic/gold/array_function_ic_test_out.e
  test/tests/ics/array_function_ic/tests
Labels: PR: Failed but allowed

#15772 Properly adjust target time when sub-cycling with negative times
  framework/src/base/MooseApp.C
  framework/src/executioners/Transient.C
  framework/src/multiapps/TransientMultiApp.C
  test/tests/multiapps/sub_cycling/gold/main_negative_out.e
  test/tests/multiapps/sub_cycling/gold/main_negative_out_sub0.e
  test/tests/multiapps/sub_cycling/main_negative.i
  test/tests/multiapps/sub_cycling/sub_negative.i
  test/tests/multiapps/sub_cycling/tests
  test/tests/multiapps/transient_multiapp/gold/main_negative.e
  test/tests/multiapps/transient_multiapp/gold/main_negative_sub_app0.e
  test/tests/multiapps/transient_multiapp/gold/main_negative_sub_app1.e
  test/tests/multiapps/transient_multiapp/gold/main_negative_sub_app2.e
  test/tests/multiapps/transient_multiapp/gold/main_negative_sub_app3.e
  test/tests/multiapps/transient_multiapp/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16036 Removing non-const get() method in RestartableData
  framework/include/restart/RestartableData.h
  modules/stochastic_tools/include/surrogates/SurrogateTrainer.h
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16000 Rework zero material property API
  framework/include/materials/DerivativeMaterialInterface.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialPropertyInterface.h
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16042 Disable valgrind for boussinesq benchmarks
  modules/navier_stokes/test/tests/ins/boussinesq/benchmark/tests
Labels: PR: Failed but allowed

#15942 add initialSetup for ComputeIsotropicElasticityTensor
  modules/tensor_mechanics/include/materials/ComputeIsotropicElasticityTensor.h
Labels: PR: Failed but allowed

#15892 Create method to obtain eigenstrain names within MasterAction
  framework/doc/content/source/materials/MaterialConverter.md
  framework/src/base/Moose.C
  modules/tensor_mechanics/doc/content/source/materials/CompositeEigenstrain.md
  modules/tensor_mechanics/doc/content/source/materials/ComputeReducedOrderEigenstrain.md
  modules/tensor_mechanics/doc/content/syntax/Modules/TensorMechanics/Master/index.md
  modules/tensor_mechanics/include/actions/TensorMechanicsAction.h
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/test/tests/action/action_eigenstrain.i
  modules/tensor_mechanics/test/tests/action/action_multi_eigenstrain.i
  modules/tensor_mechanics/test/tests/action/action_multi_eigenstrain_same_conditions.i
  modules/tensor_mechanics/test/tests/action/ad_converter_action_multi_eigenstrain.i
  modules/tensor_mechanics/test/tests/action/blocks.e
  modules/tensor_mechanics/test/tests/action/composite_eigenstrain.i
  modules/tensor_mechanics/test/tests/action/gold/action_eigenstrain_out.e
  modules/tensor_mechanics/test/tests/action/gold/action_multi_eigenstrain_out.csv
  modules/tensor_mechanics/test/tests/action/gold/ad_converter_action_multi_eigenstrain_out.csv
  modules/tensor_mechanics/test/tests/action/gold/composite_eigenstrain_out.e
  modules/tensor_mechanics/test/tests/action/gold/reduced_eigenstrain_action_out_hydro_0001.csv
  modules/tensor_mechanics/test/tests/action/reduced_eigenstrain_action.i
  modules/tensor_mechanics/test/tests/action/tests
Labels: PR: Failed but allowed

#15983 Initial implementation of substepping in radial return mapping
  modules/tensor_mechanics/doc/content/source/materials/ADRadialReturnStressUpdate.md
  modules/tensor_mechanics/include/materials/ADPowerLawCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/ADRadialReturnStressUpdate.h
  modules/tensor_mechanics/include/materials/ADStressUpdateBase.h
  modules/tensor_mechanics/include/materials/PowerLawCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/RadialReturnStressUpdate.h
  modules/tensor_mechanics/include/materials/StressUpdateBase.h
  modules/tensor_mechanics/src/materials/ADComputeMultipleInelasticStress.C
  modules/tensor_mechanics/src/materials/ADPowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/ADRadialReturnStressUpdate.C
  modules/tensor_mechanics/src/materials/ADStressUpdateBase.C
  modules/tensor_mechanics/src/materials/ComputeMultipleInelasticStress.C
  modules/tensor_mechanics/src/materials/PowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C
  modules/tensor_mechanics/src/materials/StressUpdateBase.C
  modules/tensor_mechanics/test/tests/substepping/ad_power_law_creep.i
  modules/tensor_mechanics/test/tests/substepping/gold/ad_power_law_substepping_out.e
  modules/tensor_mechanics/test/tests/substepping/gold/power_law_substepping_out.e
  modules/tensor_mechanics/test/tests/substepping/power_law_creep.i
  modules/tensor_mechanics/test/tests/substepping/tests
Labels: PR: Failed but allowed

#15979 Add Porosity material property
  modules/tensor_mechanics/doc/content/source/materials/ADPorosityFromStrain.md
  modules/tensor_mechanics/doc/content/source/materials/PorosityFromStrain.md
  modules/tensor_mechanics/include/materials/PorosityFromStrain.h
  modules/tensor_mechanics/src/materials/ADComputeMultiplePorousInelasticStress.C
  modules/tensor_mechanics/src/materials/PorosityFromStrain.C
  modules/tensor_mechanics/test/tests/ad_viscoplasticity_stress_update/creep.i
  modules/tensor_mechanics/test/tests/ad_viscoplasticity_stress_update/exact.i
  modules/tensor_mechanics/test/tests/ad_viscoplasticity_stress_update/gtn_single.i
  modules/tensor_mechanics/test/tests/ad_viscoplasticity_stress_update/lps_dual.i
  modules/tensor_mechanics/test/tests/ad_viscoplasticity_stress_update/lps_single.i
  modules/tensor_mechanics/test/tests/ad_viscoplasticity_stress_update/lps_single_split.i
  modules/tensor_mechanics/test/tests/ad_viscoplasticity_stress_update/tests
  modules/tensor_mechanics/test/tests/porosity/ad.i
  modules/tensor_mechanics/test/tests/porosity/gold/ad_out.csv
  modules/tensor_mechanics/test/tests/porosity/gold/reg_out.csv
  modules/tensor_mechanics/test/tests/porosity/reg.i
  modules/tensor_mechanics/test/tests/porosity/tests
Labels: C: Modules, PR: Failed but allowed
