Repository idaholab/moose, pull requests merged in 2020-07, with the labels that each got.

#15255 Allow a do_last test target
  python/TestHarness/JobDAG.py
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/test_DoLast.py
  python/TestHarness/tests/tests
  test/tests/test_harness/cyclic_do_last
  test/tests/test_harness/cyclic_do_last_depends
  test/tests/test_harness/do_last
  test/tests/test_harness/do_last_name
  test/tests/test_harness/do_last_skipped
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15522 Revert "Merge pull request #15118 from austinltam/fragment_cut"
  modules/xfem/include/efa/EFAElement.h
  modules/xfem/include/efa/EFAElement2D.h
  modules/xfem/include/efa/EFAElement3D.h
  modules/xfem/src/efa/EFAElement2D.C
  modules/xfem/src/efa/EFAElement3D.C
  modules/xfem/src/efa/EFAFragment2D.C
  modules/xfem/test/tests/corner_nodes_cut/gold/corner_edge_cut_out.e
  modules/xfem/test/tests/corner_nodes_cut/gold/corner_node_cut_out.e
  modules/xfem/test/tests/corner_nodes_cut/gold/corner_node_cut_twice_out.e
  modules/xfem/test/tests/second_order_elements/gold/square_branch_tri6_2d_out.e
  modules/xfem/test/tests/second_order_elements/gold/square_branch_tri6_2d_out.e-s002
  modules/xfem/test/tests/second_order_elements/gold/square_branch_tri6_2d_out.e-s003
  modules/xfem/test/tests/solid_mechanics_basic/gold/square_branch_tri_2d_out.e
  modules/xfem/test/tests/solid_mechanics_basic/gold/square_branch_tri_2d_out.e-s002
  modules/xfem/test/tests/solid_mechanics_basic/gold/square_branch_tri_2d_out.e-s003
  modules/xfem/test/tests/solid_mechanics_basic/tests
  unit/src/ElementFragmentAlgorithmTest.C
Labels: PR: Failed but allowed

#15528 Add support for specifying line_base parameter to PorousFlowPolyLineSink
  modules/porous_flow/src/dirackernels/PorousFlowLineGeometry.C
  modules/porous_flow/test/tests/dirackernels/gold/pls01_line_base.csv
  modules/porous_flow/test/tests/dirackernels/tests
Labels: PR: Failed but allowed

#15390 Improve DisplacementAboutAxis
  modules/tensor_mechanics/doc/content/source/bcs/DisplacementAboutAxis.md
  modules/tensor_mechanics/include/bcs/DisplacementAboutAxis.h
  modules/tensor_mechanics/src/bcs/DisplacementAboutAxis.C
  modules/tensor_mechanics/test/tests/torque_reaction/disp_about_axis_axial_motion_delayed.i
  modules/tensor_mechanics/test/tests/torque_reaction/gold/disp_about_axis_axial_motion_delayed_out.csv
  modules/tensor_mechanics/test/tests/torque_reaction/gold/disp_about_axis_axial_motion_incremental_out.csv
  modules/tensor_mechanics/test/tests/torque_reaction/tests
Labels: PR: Failed but allowed

#15471 Create 'tip' subcommand for alert extension
  framework/doc/content/css/alert_moose.css
  modules/doc/content/python/MooseDocs/extensions/alert.md
  modules/doc/content/python/MooseDocs/extensions/core.md
  python/MooseDocs/extensions/alert.py
  python/MooseDocs/test/content/extensions/alert.md
  python/MooseDocs/test/extensions/test_alert.py
  python/MooseDocs/test/extensions/tests
  python/MooseDocs/test/gold/html/extensions/alert.html
  python/MooseDocs/test/gold/latex/extensions/alert.tex
  python/MooseDocs/test/gold/materialize/extensions/alert.html
  python/MooseDocs/test/integrity/test_spec_files.py
Labels: PR: Failed but allowed

#15531 Refactor automatic scaling implementation for NonlinearEigenSystem
  framework/include/systems/DumpObjectsNonlinearSystem.h
  framework/include/systems/NonlinearEigenSystem.h
  framework/include/systems/NonlinearSystem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/systems/NonlinearEigenSystem.C
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/SlepcSupport.C
  test/tests/problems/eigen_problem/eigensolvers/gold/ne-coupled-resid-scaling_out_eigenvalues_0001.csv
  test/tests/problems/eigen_problem/eigensolvers/gold/ne-coupled-scaling_out_eigenvalues_0001.csv
  test/tests/problems/eigen_problem/eigensolvers/ne-coupled-resid-scaling.i
  test/tests/problems/eigen_problem/eigensolvers/ne-coupled-scaling.i
  test/tests/problems/eigen_problem/eigensolvers/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15551 Revert "Add --enable-nodeconstraint in update_and_rebuild_libmesh.sh"
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed

#15543 Adds geometry postprocessor tests
  test/tests/postprocessors/geometry/2d.e
  test/tests/postprocessors/geometry/2d_geometry.i
  test/tests/postprocessors/geometry/2d_mesh.jou
  test/tests/postprocessors/geometry/3d.e
  test/tests/postprocessors/geometry/3d_geometry.i
  test/tests/postprocessors/geometry/3d_mesh.jou
  test/tests/postprocessors/geometry/gold/2d_geometry_out.csv
  test/tests/postprocessors/geometry/gold/3d_geometry_out.csv
  test/tests/postprocessors/geometry/tests
Labels: PR: Failed but allowed

#15186 Copy boundary info from other meshes
  framework/doc/content/source/meshgenerators/GeneratedMeshGenerator.md
  framework/include/meshgenerators/GeneratedMeshGenerator.h
  framework/include/postprocessors/MemoryUsageReporter.h
  framework/src/meshgenerators/GeneratedMeshGenerator.C
  framework/src/meshgenerators/MeshCollectionGenerator.C
  modules/contact/test/tests/mortar_tm/2d/ad_frictionless_fir/finite.i
  modules/contact/test/tests/mortar_tm/2d/ad_frictionless_fir/finite_rr.i
  modules/contact/test/tests/mortar_tm/2d/ad_frictionless_fir/small.i
  modules/contact/test/tests/mortar_tm/2d/ad_frictionless_sec/finite.i
  modules/contact/test/tests/mortar_tm/2d/ad_frictionless_sec/finite_rr.i
  modules/contact/test/tests/mortar_tm/2d/ad_frictionless_sec/small.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_first/finite.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_first/finite_noaction.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_first/finite_rr.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_first/small.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_second/finite.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_second/finite_noaction.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_second/finite_rr.i
  modules/contact/test/tests/mortar_tm/2d/frictionless_second/small.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_first/finite.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_first/finite_rr.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_first/small.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_second/finite.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_second/finite_rr.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_second/small.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_first/finite.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_first/finite_noaction.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_first/finite_rr.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_first/small.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/finite.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/finite_noaction.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/finite_rr.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/small.i
  modules/contact/test/tests/mortar_tm/horizontal_blocks_mortar_TM.i
  test/tests/meshgenerators/generated_mesh_generator/both.i
  test/tests/meshgenerators/generated_mesh_generator/gold/both_in.e
  test/tests/meshgenerators/generated_mesh_generator/gold/offset_in.e
  test/tests/meshgenerators/generated_mesh_generator/gold/prefix_in.e
  test/tests/meshgenerators/generated_mesh_generator/offset.i
  test/tests/meshgenerators/generated_mesh_generator/prefix.i
  test/tests/meshgenerators/generated_mesh_generator/tests
  test/tests/meshgenerators/mesh_collection_generator/gold/image_mesh_generator_in.e
  test/tests/meshgenerators/mesh_collection_generator/gold/mesh_collection_generator_in.e
  test/tests/meshgenerators/mesh_collection_generator/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15537 Enhance element id interface
  framework/doc/content/source/interfaces/ElementIDInterface.md
  framework/include/base/Assembly.h
  framework/include/interfaces/ElementIDInterface.h
  framework/include/mesh/MooseMesh.h
  framework/include/userobject/InterfaceUserObject.h
  framework/include/userobject/InternalSideUserObject.h
  framework/include/userobject/SideUserObject.h
  framework/include/vectorpostprocessors/InterfaceVectorPostprocessor.h
  framework/src/actions/SetupMeshCompleteAction.C
  framework/src/base/Assembly.C
  framework/src/interfaces/ElementIDInterface.C
  framework/src/mesh/MooseMesh.C
  framework/src/userobject/InterfaceUserObject.C
  framework/src/userobject/InternalSideUserObject.C
  framework/src/userobject/SideUserObject.C
  framework/src/vectorpostprocessors/InterfaceVectorPostprocessor.C
  test/include/vectorpostprocessors/ElementCounterWithID.h
  test/include/vectorpostprocessors/InterfaceElementCounterWithID.h
  test/include/vectorpostprocessors/InternalSideElementCounterWithID.h
  test/include/vectorpostprocessors/SideElementCounterWithID.h
  test/src/vectorpostprocessors/ElementCounterWithID.C
  test/src/vectorpostprocessors/InterfaceElementCounterWithID.C
  test/src/vectorpostprocessors/InternalSideElementCounterWithID.C
  test/src/vectorpostprocessors/SideElementCounterWithID.C
  test/tests/vectorpostprocessors/element_id_counters/element_counter.i
  test/tests/vectorpostprocessors/element_id_counters/element_counter_block_restricted.i
  test/tests/vectorpostprocessors/element_id_counters/gold/element_counter_block_restricted_out_elem_counter0_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/gold/element_counter_block_restricted_out_elem_counter1_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/gold/element_counter_block_restricted_out_elem_counter_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/gold/element_counter_out_elem_counter_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/gold/interface_element_counter_out_elem_counter_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/gold/internal_side_element_counter_out_elem_counter_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/gold/side_element_counter_out_elem_counter_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/interface_element_counter.i
  test/tests/vectorpostprocessors/element_id_counters/internal_side_element_counter.i
  test/tests/vectorpostprocessors/element_id_counters/side_element_counter.i
  test/tests/vectorpostprocessors/element_id_counters/tests
Labels: PR: Failed but allowed

#15563 Adding initial condition for specific enthalpy
  modules/fluid_properties/doc/content/source/ics/SpecificEnthalpyFromPressureTemperatureIC.md
  modules/fluid_properties/include/ics/SpecificEnthalpyFromPressureTemperatureIC.h
  modules/fluid_properties/src/ics/SpecificEnthalpyFromPressureTemperatureIC.C
  modules/fluid_properties/test/tests/ics/specific_enthalpy_from_pressure_temperature/gold/test_out.csv
  modules/fluid_properties/test/tests/ics/specific_enthalpy_from_pressure_temperature/test.i
  modules/fluid_properties/test/tests/ics/specific_enthalpy_from_pressure_temperature/tests
Labels: PR: Failed but allowed

#15568 Fix spelling error in generate_output
  modules/tensor_mechanics/include/materials/ComputeMultiPlasticityStress.h
  modules/tensor_mechanics/include/materials/FiniteStrainPlasticMaterial.h
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
Labels: PR: Failed but allowed

#15369 Fix CZMInterfaceKernel Jacobian
  modules/tensor_mechanics/include/interfacekernels/CZMInterfaceKernel.h
  modules/tensor_mechanics/src/interfacekernels/CZMInterfaceKernel.C
  modules/tensor_mechanics/test/tests/czm/czm_patch_test.i
  modules/tensor_mechanics/test/tests/czm/gold/czm_patch_test_3DC_out.csv
  modules/tensor_mechanics/test/tests/czm/patch_mesh.e
  modules/tensor_mechanics/test/tests/czm/tests
Labels: PR: Failed but allowed

#15562 Ensure block-restricted save-in consistent for different proc counts
  framework/include/loops/AllLocalDofIndicesThread.h
  framework/src/executioners/PicardSolve.C
  framework/src/loops/AllLocalDofIndicesThread.C
  framework/src/multiapps/TransientMultiApp.C
  framework/src/postprocessors/GreaterThanLessThanPostprocessor.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  modules/contact/src/postprocessors/ContactDOFSetSize.C
  test/tests/misc/save_in/block-restricted-save-in.i
  test/tests/misc/save_in/gold/block-restricted-save-in_out.e
  test/tests/misc/save_in/tests
Labels: PR: Failed but allowed

#15548 Add ADJouleHeatingSource and ADElectricalConductivity
  modules/heat_conduction/doc/content/source/kernels/ADJouleHeatingSource.md
  modules/heat_conduction/doc/content/source/materials/ADElectricalConductivity.md
  modules/heat_conduction/include/kernels/ADJouleHeatingSource.h
  modules/heat_conduction/include/kernels/JouleHeatingSource.h
  modules/heat_conduction/include/materials/ElectricalConductivity.h
  modules/heat_conduction/src/kernels/ADJouleHeatingSource.C
  modules/heat_conduction/src/materials/ElectricalConductivity.C
  modules/heat_conduction/test/tests/joule_heating/gold/transient_ad_jouleheating_out.e
  modules/heat_conduction/test/tests/joule_heating/tests
  modules/heat_conduction/test/tests/joule_heating/transient_ad_jouleheating.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15578 Few loose ends of previous improvements on element ID interface
  framework/include/dgkernels/DGKernelBase.h
  framework/include/interfacekernels/InterfaceKernelBase.h
  framework/include/interfaces/ElementIDInterface.h
  framework/src/dgkernels/DGKernelBase.C
  framework/src/interfacekernels/InterfaceKernelBase.C
  test/src/vectorpostprocessors/ElementCounterWithID.C
  test/tests/vectorpostprocessors/element_id_counters/element_counter.i
  test/tests/vectorpostprocessors/element_id_counters/gold/element_counter_out_elem_counter_subdomain_0001.csv
  test/tests/vectorpostprocessors/element_id_counters/tests
Labels: PR: Failed but allowed

#15581 Allow user to continue
  scripts/verify_conda_libmesh.py
Labels: PR: Failed but allowed

#15553 Generic kernel
  framework/doc/content/source/kernels/GenericKernel.md
  framework/include/kernels/GenericKernel.h
  test/include/kernels/GenericValueTest.h
  test/src/kernels/GenericValueTest.C
  test/tests/kernels/ad_value/generic_value.i
  test/tests/kernels/ad_value/gold/generic_value_out.e
  test/tests/kernels/ad_value/tests
Labels: PR: Failed but allowed

#15557 Create virtually translated points during MultiApp transfers
  framework/include/transfers/MultiAppInterpolationTransfer.h
  framework/include/variables/MooseVariableBase.h
  framework/src/transfers/MultiAppInterpolationTransfer.C
  test/tests/transfers/multiapp_transfer_transformation/gold/transfer_transformation_out.e
  test/tests/transfers/multiapp_transfer_transformation/gold/transfer_transformation_out_sub0.e
  test/tests/transfers/multiapp_transfer_transformation/tests
  test/tests/transfers/multiapp_transfer_transformation/transfer_transformation.i
  test/tests/transfers/multiapp_transfer_transformation/transfer_transformation_sub.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15590 We did not support std::make_unique yet
  framework/src/transfers/MultiAppInterpolationTransfer.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15588 When restarting from exodus all processors need to keep the mesh file open
  framework/src/meshgenerators/FileMeshGenerator.C
  test/tests/ics/from_exodus_solution/tests
Labels: PR: Failed but allowed

#15570 Add mean-zero pressure approach for INS
  framework/doc/content/source/kernels/AverageValueConstraint.md
  framework/doc/content/source/kernels/ScalarLagrangeMultiplier.md
  framework/include/kernels/AverageValueConstraint.h
  framework/include/kernels/ScalarLagrangeMultiplier.h
  framework/src/kernels/AverageValueConstraint.C
  framework/src/kernels/ScalarLagrangeMultiplier.C
  modules/navier_stokes/test/tests/ins/lid_driven/ad_lid_driven_mean_zero_pressure.i
  modules/navier_stokes/test/tests/ins/lid_driven/gold/ad_lid_driven_mean_zero_pressure_out.e
  modules/navier_stokes/test/tests/ins/lid_driven/tests
  test/tests/kernels/scalar_constraint/scalar_constraint_kernel.i
  test/tests/kernels/scalar_constraint/scalar_constraint_kernel_disp.i
Labels: PR: Failed but allowed

#15574 Improve documentation for ReferenceResidualProblem
  framework/doc/content/source/problems/ReferenceResidualProblem.md
Labels: PR: Failed but allowed

#15560 Fixed make side set from node set error message
  framework/src/interfaces/BoundaryRestrictable.C
Labels: PR: Failed but allowed

#15592 PorousFlow JOSS paper minor mods
  modules/porous_flow/paper.bib
  modules/porous_flow/paper.md
Labels: PR: Failed but allowed

#15583 Adding pyhit as a conda package
  conda/pyhit/build.sh
  conda/pyhit/conda_build_config.yaml
  conda/pyhit/meta.yaml
Labels: PR: Ready for Review/Merge

#14090 Providing contact gap offset
  framework/doc/content/source/auxkernels/PenetrationAux.md
  framework/include/auxkernels/PenetrationAux.h
  framework/src/auxkernels/PenetrationAux.C
  modules/combined/test/tests/gap_heat_transfer_convex/gap_heat_transfer_convex_gap_offsets.e
  modules/combined/test/tests/gap_heat_transfer_convex/gap_heat_transfer_convex_gap_offsets.i
  modules/combined/test/tests/gap_heat_transfer_convex/gold/gap_heat_transfer_convex_gap_offsets_out.e
  modules/combined/test/tests/gap_heat_transfer_convex/tests
  modules/contact/doc/content/source/constraints/MechanicalContactConstraint.md
  modules/contact/doc/content/syntax/Contact/index.md
  modules/contact/include/constraints/MechanicalContactConstraint.h
  modules/contact/src/actions/ContactAction.C
  modules/contact/src/constraints/MechanicalContactConstraint.C
  modules/contact/test/tests/mechanical_constraint/blocks_2d_gap_offset.e
  modules/contact/test/tests/mechanical_constraint/frictionless_kinematic_gap_offsets.i
  modules/contact/test/tests/mechanical_constraint/gold/frictionless_kinematic_gap_offsets_out.e
  modules/contact/test/tests/mechanical_constraint/tests
  modules/heat_conduction/doc/content/source/actions/ThermalContactAction.md
  modules/heat_conduction/src/actions/ThermalContactAction.C
Labels: PR: Failed but allowed

#15605 Make getNodalValue const
  framework/include/variables/MooseVariableFE.h
  framework/src/variables/MooseVariableFE.C
  modules/contact/include/constraints/MechanicalContactConstraint.h
Labels: PR: Failed but allowed

#15609 Use proper hashbang
  scripts/verify_conda_libmesh.py
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#15597 Bug fixes for restarting transient multiapp solves from steady multiapp solves
  framework/src/multiapps/TransientMultiApp.C
  framework/src/systems/SystemBase.C
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/gold/master_ss_out.e
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/gold/master_ss_out_bison0.e
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/gold/master_tr_out.e
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/gold/master_tr_out_bison0.e
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/master_ss.i
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/master_tr.i
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/sub_ss.i
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/sub_tr.i
  modules/combined/test/tests/restart-transient-from-ss-with-stateful/tests
Labels: PR: Ready for Review/Merge

#15566 Snesmf reuse base sanity check forward compatability
  framework/include/utils/PetscSupport.h
  framework/src/actions/CommonOutputAction.C
  framework/src/outputs/Console.C
  framework/src/utils/PetscSupport.C
  modules/combined/test/tests/cavity_pressure/additional_volume.i
  modules/contact/src/actions/ContactAction.C
  modules/contact/test/tests/bouncing-block-contact/frictional-mortar-fb-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictional-mortar-min-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictional-nodal-min-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictional-nodal-min-normal-lm-mortar-fb-tangential-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-mortar-fb-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-mortar-min-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-nodal-fb-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-nodal-fb-lm-nodal-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-nodal-min-lm-mortar-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-nodal-min-lm-nodal-disp.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-nodal-reduced-active-set.i
  modules/contact/test/tests/bouncing-block-contact/grid-sequencing/grid-sequencing.i
  modules/contact/test/tests/bouncing-block-contact/ping-ponging/ranfs-ping-pong.i
  modules/contact/test/tests/dual_mortar/dm_mechanical_contact.i
  modules/contact/test/tests/non-singular-frictional-mortar/frictional-mortar.i
  modules/contact/test/tests/ranfs-and-scaling/bouncing-block-ranfs.i
  modules/navier_stokes/test/tests/ins/lid_driven/lid_driven_stabilized.i
  modules/richards/test/tests/buckley_leverett/bl01.i
  modules/richards/test/tests/buckley_leverett/bl01_lumped.i
  modules/richards/test/tests/buckley_leverett/bl01_lumped_fu.i
  modules/richards/test/tests/newton_cooling/nc02.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/crysp_cutback.i
  test/tests/misc/exception/parallel_exception_jacobian_transient.i
  test/tests/misc/exception/parallel_exception_residual_transient.i
  test/tests/multiapps/picard_catch_up/sub.i
  test/tests/multiapps/picard_failure/picard_sub.i
  test/tests/nodalkernels/constraint_enforcement/gold/rsls-pjfnk.e
  test/tests/nodalkernels/constraint_enforcement/tests
  test/tests/outputs/console/tests
Labels: PR: Failed but allowed

#15559 Add Jun/Jul 2020 news
  modules/doc/content/newsletter/2020_06.md
  modules/doc/content/newsletter/2020_07.md
  modules/doc/content/newsletter/2020_08.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#15610 Add option to INS action to not add temperature variable
  modules/navier_stokes/src/actions/INSAction.C
  modules/navier_stokes/test/tests/ins/wall_convection/gold/steady-action-no-temp-var.e
  modules/navier_stokes/test/tests/ins/wall_convection/steady-action.i
  modules/navier_stokes/test/tests/ins/wall_convection/tests
Labels: PR: Ready for Review/Merge

#15636 Moving SurrogateTester to EvaluateSurrogate
  modules/combined/examples/stochastic/poly_chaos_uniform.i
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/poly_chaos_surrogate.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/surrogate_creation.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/surrogate_evaluate.md
  modules/stochastic_tools/doc/content/source/surrogates/PolynomialRegressionSurrogate.md
  modules/stochastic_tools/doc/content/source/vectorpostprocessors/EvaluateSurrogate.md
  modules/stochastic_tools/examples/surrogates/nearest_point_normal.i
  modules/stochastic_tools/examples/surrogates/nearest_point_uniform.i
  modules/stochastic_tools/examples/surrogates/poly_chaos_normal.i
  modules/stochastic_tools/examples/surrogates/poly_chaos_uniform.i
  modules/stochastic_tools/examples/surrogates/polynomial_regression/normal_surr.i
  modules/stochastic_tools/examples/surrogates/polynomial_regression/uniform_surr.i
  modules/stochastic_tools/include/vectorpostprocessors/EvaluateSurrogate.h
  modules/stochastic_tools/src/vectorpostprocessors/EvaluateSurrogate.C
  modules/stochastic_tools/test/include/vectorpostprocessors/GaussianProcessTester.h
  modules/stochastic_tools/test/src/vectorpostprocessors/GaussianProcessTester.C
  modules/stochastic_tools/test/tests/surrogates/nearest_point/cartesian.i
  modules/stochastic_tools/test/tests/surrogates/nearest_point/evaluate.i
  modules/stochastic_tools/test/tests/surrogates/poly_chaos/master_2d_mc.i
  modules/stochastic_tools/test/tests/surrogates/poly_chaos/master_2d_quad.i
  modules/stochastic_tools/test/tests/surrogates/poly_chaos/master_2dnorm_quad.i
  modules/stochastic_tools/test/tests/surrogates/polynomial_regression/evaluate.i
  modules/stochastic_tools/test/tests/surrogates/polynomial_regression/train_and_evaluate.i
Labels: C: Modules

#15572 Add missing is_ad parameters
  framework/include/interfaces/BlockRestrictable.h
  framework/include/interfaces/BoundaryRestrictable.h
  framework/include/materials/DerivativeMaterialInterface.h
  framework/include/materials/DerivativeParsedMaterial.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/src/materials/DerivativeFunctionMaterialBase.C
  modules/phase_field/include/materials/DerivativeMultiPhaseBase.h
  test/include/kernels/DefaultMatPropConsumerKernel.h
  test/include/materials/DefaultMatPropConsumerMaterial.h
  test/include/materials/DerivativeMaterialInterfaceTestClient.h
  test/include/materials/DerivativeMaterialInterfaceTestProvider.h
  test/src/kernels/DefaultMatPropConsumerKernel.C
  test/src/materials/DefaultMatPropConsumerMaterial.C
  test/src/materials/DerivativeMaterialInterfaceTestClient.C
  test/src/materials/DerivativeMaterialInterfaceTestProvider.C
  test/tests/materials/derivative_material_interface/ad_bad_evaluation.i
  test/tests/materials/derivative_material_interface/ad_const.i
  test/tests/materials/derivative_material_interface/ad_execution_order.i
  test/tests/materials/derivative_material_interface/ad_material_chaining.i
  test/tests/materials/derivative_material_interface/ad_multiblock.i
  test/tests/materials/derivative_material_interface/ad_test.i
  test/tests/materials/derivative_material_interface/ad_warn.i
  test/tests/materials/derivative_material_interface/gold/ad_const_out.e
  test/tests/materials/derivative_material_interface/gold/ad_material_chaining_out.csv
  test/tests/materials/derivative_material_interface/tests
Labels: PR: Ready for Review/Merge

#15632 Documenting several executioner and preconditioning classes
  framework/doc/content/source/executioners/InversePowerMethod.md
  framework/doc/content/source/executioners/NonlinearEigen.md
  framework/doc/content/source/executioners/Steady.md
  framework/doc/content/source/preconditioners/FiniteDifferencePreconditioner.md
  framework/doc/content/source/preconditioners/PhysicsBasedPreconditioner.md
  framework/doc/content/source/preconditioners/SingleMatrixPreconditioner.md
  framework/doc/content/syntax/Preconditioning/index.md
  framework/doc/hidden.yml
  framework/src/preconditioners/FiniteDifferencePreconditioner.C
  framework/src/preconditioners/PhysicsBasedPreconditioner.C
  framework/src/preconditioners/SingleMatrixPreconditioner.C
Labels: C: Documentation

#15648 Enhance ExternalPetscSolverTestApp to take both petsc and moose input files
  modules/external_petsc_solver/include/base/ExternalPetscSolverApp.h
  modules/external_petsc_solver/src/base/ExternalPetscSolverApp.C
  modules/external_petsc_solver/src/main.C
  modules/external_petsc_solver/src/mesh/PETScDMDAMesh.C
  modules/external_petsc_solver/test/include/base/ExternalPetscSolverTestApp.h
  modules/external_petsc_solver/test/src/base/ExternalPetscSolverTestApp.C
  modules/external_petsc_solver/test/tests/external_petsc_problem/tests
Labels: PR: Ready for Review/Merge

#15614 Add auto_advance parameter to PicardSolve
  framework/doc/content/source/multiapps/TransientMultiApp.md
  framework/doc/content/source/postprocessors/TimePostprocessor.md
  framework/include/executioners/PicardSolve.h
  framework/include/multiapps/MultiApp.h
  framework/include/multiapps/TransientMultiApp.h
  framework/include/postprocessors/TimePostprocessor.h
  framework/include/problems/FEProblemBase.h
  framework/src/executioners/PicardSolve.C
  framework/src/executioners/Transient.C
  framework/src/multiapps/TransientMultiApp.C
  framework/src/postprocessors/TimePostprocessor.C
  framework/src/problems/FEProblemBase.C
  test/tests/multiapps/picard_multilevel/multilevel_dt_rejection/master.i
  test/tests/multiapps/picard_multilevel/multilevel_dt_rejection/picard_sub.i
  test/tests/multiapps/picard_multilevel/multilevel_dt_rejection/picard_sub2.i
  test/tests/multiapps/picard_multilevel/multilevel_dt_rejection/test_multilevel.py
  test/tests/multiapps/picard_multilevel/multilevel_dt_rejection/tests
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#15615 Auto-generate dirac points in PorousFlowPolyLineSink
  modules/porous_flow/doc/content/modules/porous_flow/sinks.md
  modules/porous_flow/include/dirackernels/PorousFlowLineGeometry.h
  modules/porous_flow/include/dirackernels/PorousFlowPolyLineSink.h
  modules/porous_flow/src/dirackernels/PorousFlowLineGeometry.C
  modules/porous_flow/test/include/vectorpostprocessors/DiracPointsWriter.h
  modules/porous_flow/test/src/vectorpostprocessors/DiracPointsWriter.C
  modules/porous_flow/test/tests/dirackernels/gold/pls02_dirac_pts_0004.csv
  modules/porous_flow/test/tests/dirackernels/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge
