Repository idaholab/moose, pull requests merged in 2020-02, with the labels that each got.

#14657 Update package manager installs to Python 3.
  docker_ci/apt_installs.sh
  docker_ci/yum_installs.sh
Labels: PR: Failed but allowed

#14574 Enable multi-level Picard iterations to restart from the latest solution
  framework/include/multiapps/MultiApp.h
  framework/include/multiapps/TransientMultiApp.h
  framework/src/multiapps/MultiApp.C
  framework/src/multiapps/TransientMultiApp.C
  test/tests/multiapps/picard_multilevel/2level_picard/gold/mutilevel_app_out.e
  test/tests/multiapps/picard_multilevel/2level_picard/gold/mutilevel_app_out_level1-0.e
  test/tests/multiapps/picard_multilevel/2level_picard/gold/mutilevel_app_out_level1-0_level2-0.e
  test/tests/multiapps/picard_multilevel/2level_picard/mutilevel_app.i
  test/tests/multiapps/picard_multilevel/2level_picard/sub_level1.i
  test/tests/multiapps/picard_multilevel/2level_picard/sub_level2.i
  test/tests/multiapps/picard_multilevel/2level_picard/tests
Labels: PR: Ready for Review/Merge

#14685 Make contact dependent on tensor mechanics, add one test, address par…
  modules/contact/doc/config.yml
  modules/contact/doc/sqa_contact.yml
  modules/contact/include/base/ContactApp.h
  modules/contact/src/base/ContactApp.C
  modules/contact/test/tests/verification/overclosure_removal/gold/overclosure_exodus.e
  modules/contact/test/tests/verification/overclosure_removal/oc_mesh.e
  modules/contact/test/tests/verification/overclosure_removal/overclosure.i
  modules/contact/test/tests/verification/overclosure_removal/tests
  modules/modules.mk
  modules/peridynamics/Makefile
Labels: PR: Auto Merge

#14689 Full specialization before possible implicit instantiations
  framework/include/base/Assembly.h
  framework/include/interfaces/TaggingInterface.h
  framework/include/samplers/Sampler.h
  framework/include/utils/ColumnMajorMatrix.h
  framework/include/utils/MooseADWrapper.h
  framework/src/geomsearch/FindContactPoint.C
  framework/src/restart/DataIO.C
  framework/src/utils/DenseMatrixDualReal.C
  modules/phase_field/include/userobjects/PolycrystalUserObjectBase.h
  modules/phase_field/src/userobjects/PolycrystalUserObjectBase.C
  modules/solid_mechanics/include/materials/AnisotropicElasticityTensor.h
  modules/tensor_mechanics/include/materials/ADComputeFiniteShellStrain.h
  modules/tensor_mechanics/include/materials/ADComputeIncrementalShellStrain.h
  modules/tensor_mechanics/include/materials/ComputeReducedOrderEigenstrain.h
  test/include/materials/TypesMaterial.h
  test/src/materials/TypesMaterial.C
Labels: PR: Ready for Review/Merge

#14695 Allow font size to change in lists
  framework/doc/content/css/reveal_moose.css
Labels: PR: Ready for Review/Merge

#14675 Multi dimensional interpolator
  framework/include/utils/MultiDimensionalInterpolation.h
  framework/include/utils/MultiIndex.h
  framework/src/utils/MultiDimensionalInterpolation.C
  unit/src/MultiDimensionalInterpolationTest.C
  unit/src/MultiIndexTest.C
Labels: PR: Failed but allowed

#14703 Fix rtags compile commands target
  framework/moose.mk
  framework/scripts/compile_commands.py
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14699 Add RANFS to contact action
  modules/contact/include/actions/ContactAction.h
  modules/contact/src/actions/ContactAction.C
  modules/contact/test/tests/bouncing-block-contact/bouncing-block-ranfs.i
  modules/contact/test/tests/bouncing-block-contact/gold/bouncing-block-coarse.e
  modules/contact/test/tests/bouncing-block-contact/tests
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#14712 Allow ADKernel objects to be controlled
  framework/include/problems/FEProblemBase.h
  framework/include/utils/InputParameterWarehouse.h
  framework/src/actions/AddBCAction.C
  framework/src/actions/AddKernelAction.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/InputParameterWarehouse.C
  test/tests/controls/time_periods/bcs/adbcs.i
  test/tests/controls/time_periods/bcs/tests
  test/tests/controls/time_periods/kernels/adkernels.i
  test/tests/controls/time_periods/kernels/tests
Labels: PR: Failed but allowed

#14715 Make are_queued_jobs_finished Python3 Compatible
  scripts/are_queued_jobs_finished.py
Labels: PR: Failed but allowed

#14711 Correct links for inherited SQA documents
  framework/doc/sqa_framework.yml
  modules/contact/doc/sqa_contact.yml
  modules/fluid_properties/doc/sqa_fluid_properties.yml
  modules/heat_conduction/doc/sqa_heat_conduction.yml
  modules/misc/doc/sqa_misc.yml
  modules/phase_field/doc/sqa_phase_field.yml
  modules/stochastic_tools/doc/sqa_stochastic_tools.yml
  modules/tensor_mechanics/doc/sqa_tensor_mechanics.yml
  modules/xfem/doc/sqa_xfem.yml
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/test/extensions/test_sqa.py
Labels: PR: Ready for Review/Merge

#14709 Print up-to-date scaling factors
  framework/include/systems/NonlinearSystemBase.h
  framework/include/systems/SystemBase.h
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  test/tests/scaling/up-to-date-scale-factors/gold/up-to-date-scale-factors_out.e
  test/tests/scaling/up-to-date-scale-factors/tests
  test/tests/scaling/up-to-date-scale-factors/up-to-date-scale-factors.i
Labels: PR: Ready for Review/Merge

#14716 Give error message when running TestHarness with python 2
  python/MooseDocs/__init__.py
  python/TestHarness/__init__.py
  python/peacock/peacock
  python/pyhit/pyhit.py
Labels: PR: Failed but allowed

#14723 Fix test 'bouncing-block-contact.reduced_active_set/bouncing-block'
  modules/contact/test/tests/bouncing-block-contact/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#14705 expand InterfaceUO capabilities
  framework/doc/content/source/auxkernels/InterfaceValueUserObjectAux.md
  framework/doc/content/source/userobject/InterfaceQpMaterialPropertyRealUO.md
  framework/doc/content/source/userobject/InterfaceQpValueUserObject.md
  framework/include/auxkernels/InterfaceValueUserObjectAux.h
  framework/include/postprocessors/InterfaceAverageVariableValuePostprocessor.h
  framework/include/postprocessors/InterfaceIntegralPostprocessor.h
  framework/include/postprocessors/InterfaceIntegralVariableValuePostprocessor.h
  framework/include/postprocessors/InterfacePostprocessor.h
  framework/include/userobject/InterfaceQpMaterialPropertyBaseUserObject.h
  framework/include/userobject/InterfaceQpMaterialPropertyRealUO.h
  framework/include/userobject/InterfaceQpUserObjectBase.h
  framework/include/userobject/InterfaceQpValueUserObject.h
  framework/include/userobject/InterfaceUserObject.h
  framework/include/userobject/InterfaceValueUserObject.h
  framework/src/auxkernels/InterfaceValueUserObjectAux.C
  framework/src/loops/ComputeJacobianThread.C
  framework/src/loops/ComputeResidualThread.C
  framework/src/loops/ComputeUserObjectsThread.C
  framework/src/postprocessors/InterfaceAverageVariableValuePostprocessor.C
  framework/src/postprocessors/InterfaceIntegralPostprocessor.C
  framework/src/postprocessors/InterfaceIntegralVariableValuePostprocessor.C
  framework/src/postprocessors/InterfacePostprocessor.C
  framework/src/problems/FEProblemBase.C
  framework/src/userobject/InterfaceQpMaterialPropertyRealUO.C
  framework/src/userobject/InterfaceQpUserObjectBase.C
  framework/src/userobject/InterfaceQpValueUserObject.C
  framework/src/userobject/InterfaceUserObject.C
  framework/src/userobject/InterfaceValueUserObject.C
  test/include/auxkernels/StatefulAux.h
  test/include/materials/LinearNonLinearIterationInterfaceMaterial.h
  test/include/materials/LinearNonLinearIterationMaterial.h
  test/include/userobjects/InterfaceUserObjectTestGetMaterialProperty.h
  test/src/auxkernels/StatefulAux.C
  test/src/materials/LinearNonLinearIterationInterfaceMaterial.C
  test/src/materials/LinearNonLinearIterationMaterial.C
  test/src/userobjects/InterfaceUserObjectTestGetMaterialProperty.C
  test/tests/userobjects/interface_user_object/gold/interface_mp_real_user_object_QP_out.e
  test/tests/userobjects/interface_user_object/gold/interface_value_rate_increment_user_object_QP_out.e
  test/tests/userobjects/interface_user_object/gold/interface_value_user_object_QP_out.e
  test/tests/userobjects/interface_user_object/interface_mp_real_user_object_QP.i
  test/tests/userobjects/interface_user_object/interface_userobject_material_value.i
  test/tests/userobjects/interface_user_object/interface_value_rate_increment_user_object_QP.i
  test/tests/userobjects/interface_user_object/interface_value_user_object_QP.i
  test/tests/userobjects/interface_user_object/tests
Labels: PR: Failed but allowed

#14727 update CZM to new validParamsSyntax
  modules/tensor_mechanics/include/actions/CohesiveZoneMasterAction.h
  modules/tensor_mechanics/include/interfacekernels/CZMInterfaceKernel.h
  modules/tensor_mechanics/include/materials/czm/CZMMaterialBase.h
  modules/tensor_mechanics/include/materials/czm/SalehaniIrani3DCTraction.h
  modules/tensor_mechanics/src/actions/CohesiveZoneMasterAction.C
  modules/tensor_mechanics/src/interfacekernels/CZMInterfaceKernel.C
  modules/tensor_mechanics/src/materials/czm/CZMMaterialBase.C
  modules/tensor_mechanics/src/materials/czm/SalehaniIrani3DCTraction.C
Labels: PR: Failed but allowed

#14731 Avoiding race conditions
  modules/combined/test/tests/beam_eigenstrain_transfer/tests
  modules/contact/test/tests/bouncing-block-contact/tied-nodes.i
  modules/navier_stokes/test/tests/ins/lid_driven/ad_lid_driven_stabilized.i
  modules/navier_stokes/test/tests/ins/lid_driven/lid_driven_stabilized.i
  modules/tensor_mechanics/test/tests/jacobian/cto15.i
  modules/tensor_mechanics/test/tests/thermal_expansion/tests
  test/tests/kernels/simple_transient_diffusion/speedtests
  test/tests/postprocessors/relative_difference/tests
  test/tests/vectorpostprocessors/csv_reader/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14737 Don't snapshot unrelated test outputs
  python/TestHarness/FileChecker.py
  python/TestHarness/schedulers/Job.py
Labels: PR: Auto Merge, PR: Failed but allowed, PR: Ready for Review/Merge

#14743 Fix the minor typo in beam documentation
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/C0TimoshenkoBeam.md
Labels: PR: Ready for Review/Merge

#14722 Feb. News
  modules/doc/content/newsletter/2020_02.md
  modules/doc/content/newsletter/2020_03.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#14720 JOSS paper.md, paper.bib, README.md and LICENSE added. Fixes #14719
  modules/porous_flow/LICENSE
  modules/porous_flow/README.md
  modules/porous_flow/paper.bib
  modules/porous_flow/paper.md
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14756 Add saturation temperature and pressure functions
  modules/fluid_properties/doc/content/modules/fluid_properties/index.md
  modules/fluid_properties/doc/content/source/functions/SaturationPressureFunction.md
  modules/fluid_properties/doc/content/source/functions/SaturationTemperatureFunction.md
  modules/fluid_properties/include/functions/SaturationPressureFunction.h
  modules/fluid_properties/include/functions/SaturationTemperatureFunction.h
  modules/fluid_properties/src/functions/SaturationPressureFunction.C
  modules/fluid_properties/src/functions/SaturationTemperatureFunction.C
  modules/fluid_properties/test/tests/functions/saturation_pressure_function/gold/saturation_pressure_function_out.csv
  modules/fluid_properties/test/tests/functions/saturation_pressure_function/saturation_pressure_function.i
  modules/fluid_properties/test/tests/functions/saturation_pressure_function/tests
  modules/fluid_properties/test/tests/functions/saturation_temperature_function/gold/saturation_temperature_function_out.csv
  modules/fluid_properties/test/tests/functions/saturation_temperature_function/saturation_temperature_function.i
  modules/fluid_properties/test/tests/functions/saturation_temperature_function/tests
Labels: PR: Failed but allowed

#14764 Grammar fixes
  modules/doc/content/newsletter/2020_02.md
Labels: PR: Auto Merge, PR: Failed but allowed

#14747 Rename emissivity_i to emissivity_master,slave (#14746)
  modules/combined/test/tests/gap_heat_transfer_radiation/gap_heat_transfer_radiation_test.i
  modules/heat_conduction/src/materials/GapConductance.C
Labels: PR: Failed but allowed

#14672 Aux user object dependency resolving
  framework/doc/content/source/auxkernels/AuxKernel.md
  framework/include/auxkernels/AuxKernel.h
  framework/include/userobject/ElementUserObject.h
  framework/include/userobject/GeneralUserObject.h
  framework/include/userobject/InterfaceUserObject.h
  framework/include/userobject/InternalSideUserObject.h
  framework/include/userobject/NodalUserObject.h
  framework/include/userobject/SideUserObject.h
  framework/include/userobject/UserObject.h
  framework/include/userobject/UserObjectInterface.h
  framework/src/auxkernels/AuxKernel.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/userobject/ElementUserObject.C
  framework/src/userobject/GeneralUserObject.C
  framework/src/userobject/InterfaceUserObject.C
  framework/src/userobject/InternalSideUserObject.C
  framework/src/userobject/NodalUserObject.C
  framework/src/userobject/SideUserObject.C
  framework/src/userobject/UserObject.C
  framework/src/userobject/UserObjectInterface.C
  modules/phase_field/examples/rigidbodymotion/AC_CH_advection_constforce_rect.i
  modules/phase_field/src/auxkernels/EBSDReaderAvgDataAux.C
  modules/phase_field/src/auxkernels/EulerAngleProvider2RGBAux.C
  modules/phase_field/src/auxkernels/GrainAdvectionAux.C
  modules/tensor_mechanics/src/auxkernels/GlobalDisplacementAux.C
  test/tests/auxkernels/user_object_dependency/aux_uo_deps.i
  test/tests/auxkernels/user_object_dependency/gold/aux_uo_deps_out.e
  test/tests/auxkernels/user_object_dependency/tests
Labels: PR: [TODO] Please address comments

#14769 Use new website for contributing link in readme
  README.md
Labels: PR: Ready for Review/Merge

#14760 Move nonlinear solve out of viscoplasticity base class
  modules/tensor_mechanics/include/materials/ADViscoplasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/ADViscoplasticityStressUpdateBase.h
  modules/tensor_mechanics/src/materials/ADViscoplasticityStressUpdate.C
  modules/tensor_mechanics/src/materials/ADViscoplasticityStressUpdateBase.C
Labels: PR: Failed but allowed

#14767 updated inlhpcconnectivity url and Linux instructions
  modules/doc/content/help/inlhpcconnectivity.md
Labels: PR: Ready for Review/Merge

#14659 Add slave slide Jacobian contribution from displacements
  modules/combined/test/tests/gap_heat_transfer_jac/gold/two_blocks_out.e
  modules/combined/test/tests/gap_heat_transfer_jac/tests
  modules/combined/test/tests/gap_heat_transfer_jac/two_blocks.i
  modules/heat_conduction/include/bcs/GapHeatTransfer.h
  modules/heat_conduction/src/bcs/GapHeatTransfer.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14774 Initial implementation of BCa confidence level intervals
  modules/stochastic_tools/doc/content/source/vectorpostprocessors/Statistics.md
  modules/stochastic_tools/include/utils/BootstrapCalculators.h
  modules/stochastic_tools/include/utils/Calculators.h
  modules/stochastic_tools/src/utils/BootstrapCalculators.C
  modules/stochastic_tools/src/utils/Calculators.C
  modules/stochastic_tools/src/vectorpostprocessors/Statistics.C
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/bca/bca.i
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/bca/bca_distributed.i
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/bca/gold/bca_distributed_out_stats_0001.csv
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/bca/gold/bca_out_stats_0001.csv
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/bca/tests
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/errors/error.i
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/errors/gold/percentile_distributed_out_stats_0001.csv
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/errors/gold/percentile_out_stats_0001.csv
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/errors/tests
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/percentile/gold/percentile_distributed_out_stats_0001.csv
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/percentile/gold/percentile_out_stats_0001.csv
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/percentile/percentile.i
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/percentile/percentile_distributed.i
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/percentile/tests
  modules/stochastic_tools/test/tests/vectorpostprocessors/bootstrap_statistics/tests
  unit/Makefile
  unit/src/TestStochasticToolsCalculators.C
Labels: PR: Failed but allowed

#14771 Serialize All Tests
  framework/doc/content/source/parser/Parser.md
  modules/doc/content/python/TestHarness.md
  python/TestHarness/JobDAG.py
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/tests
  test/tests/geomsearch/2d_moving_penetration/tests
  test/tests/misc/check_error/tests
  test/tests/outputs/format/tests
  test/tests/test_harness/output_clobber_simple
Labels: PR: Failed but allowed

#14780 Fix stork module unit test build issue
  scripts/stork.sh
  stork/unit/Makefile.app
  stork/unit/Makefile.module
Labels: PR: Failed but allowed

#14677 XML Output for VPP data
  .gitignore
  framework/contrib/pugixml/include/pugiconfig.h
  framework/contrib/pugixml/include/pugixml.h
  framework/contrib/pugixml/readme.txt
  framework/contrib/pugixml/src/pugixml.C
  framework/doc/content/source/outputs/XMLOutput.md
  framework/include/outputs/PetscOutput.h
  framework/include/outputs/XMLOutput.h
  framework/moose.mk
  framework/src/actions/CommonOutputAction.C
  framework/src/outputs/XMLOutput.C
  framework/src/vectorpostprocessors/VectorPostprocessor.C
  python/TestHarness/testers/XMLDiff.py
  test/tests/outputs/iterative/tests
  test/tests/outputs/vtk/tests
  test/tests/outputs/xml/gold/gold/xml_distributed_out.xml
  test/tests/outputs/xml/gold/gold/xml_distributed_out.xml.1
  test/tests/outputs/xml/gold/gold/xml_distributed_out.xml.2
  test/tests/outputs/xml/gold/gold/xml_iterations_out.xml
  test/tests/outputs/xml/gold/gold/xml_out.xml
  test/tests/outputs/xml/gold/xml_distributed_out.xml
  test/tests/outputs/xml/gold/xml_distributed_out.xml.1
  test/tests/outputs/xml/gold/xml_distributed_out.xml.2
  test/tests/outputs/xml/gold/xml_iterations_out.xml
  test/tests/outputs/xml/gold/xml_out.xml
  test/tests/outputs/xml/tests
  test/tests/outputs/xml/xml.i
  test/tests/outputs/xml/xml_iterations.i
Labels: PR: Failed but allowed

#14782 Change default of emissivities to be consistent w/ BISON
  modules/combined/test/tests/exception/ad.i
  modules/combined/test/tests/exception/nonad.i
  modules/combined/test/tests/gap_heat_transfer_convex/gap_heat_transfer_convex.i
  modules/combined/test/tests/gap_heat_transfer_convex/gap_heat_transfer_convex_sm.i
  modules/combined/test/tests/gap_heat_transfer_htonly/cyl2D.i
  modules/combined/test/tests/gap_heat_transfer_htonly/cyl2D_xz.i
  modules/combined/test/tests/gap_heat_transfer_htonly/cyl2D_yz.i
  modules/combined/test/tests/gap_heat_transfer_htonly/cyl3D.i
  modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_it_plot_test.i
  modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_rspherical.i
  modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_rz_test.i
  modules/combined/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_test.i
  modules/combined/test/tests/gap_heat_transfer_htonly/planar_xy.i
  modules/combined/test/tests/gap_heat_transfer_htonly/planar_xz.i
  modules/combined/test/tests/gap_heat_transfer_htonly/planar_yz.i
  modules/combined/test/tests/gap_heat_transfer_htonly/sphere2DRZ.i
  modules/combined/test/tests/gap_heat_transfer_htonly/sphere3D.i
  modules/combined/test/tests/gap_heat_transfer_jac/two_blocks.i
  modules/combined/test/tests/gap_heat_transfer_radiation/gap_heat_transfer_radiation_test.i
  modules/combined/test/tests/generalized_plane_strain_tm_contact/generalized_plane_strain_tm_contact.i
  modules/heat_conduction/src/materials/GapConductance.C
  modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/gap_conductivity_property.i
  modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/moving.i
  modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/nonmatching.i
  modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/perfect.i
  modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/perfectQ8.i
  modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/perfectQ9.i
  modules/heat_conduction/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/second_order.i
  modules/heat_conduction/test/tests/heat_conduction/3d_quadrature_gap_heat_transfer/moving.i
  modules/heat_conduction/test/tests/heat_conduction/3d_quadrature_gap_heat_transfer/nonmatching.i
  modules/heat_conduction/test/tests/heat_conduction/3d_quadrature_gap_heat_transfer/second.i
  modules/heat_conduction/test/tests/heat_conduction/min_gap/min_gap.i
  modules/heat_conduction/test/tests/meshed_gap_thermal_contact/meshed_annulus_thermal_contact.i
  modules/heat_conduction/test/tests/meshed_gap_thermal_contact/meshed_gap_thermal_contact.i
  modules/heat_conduction/test/tests/meshed_gap_thermal_contact/meshed_gap_thermal_contact_constant_conductance.i
  modules/heat_conduction/test/tests/recover/ad_recover.i
  modules/heat_conduction/test/tests/recover/recover.i
Labels: PR: Failed but allowed

#14728 Remove singularity for frictional mortar contact
  modules/contact/src/actions/ContactAction.C
  modules/contact/src/constraints/TangentialMortarLMMechanicalContact.C
  modules/contact/test/tests/bouncing-block-contact/tests
  modules/contact/test/tests/non-singular-frictional-mortar/frictional-mortar.i
  modules/contact/test/tests/non-singular-frictional-mortar/gold/frictional-mortar_exodus.e
  modules/contact/test/tests/non-singular-frictional-mortar/long_short_blocks.e
  modules/contact/test/tests/non-singular-frictional-mortar/tests
  modules/contact/test/tests/non-singular-frictional-mortar/two_horizontal_blocks.jou
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#14788 Fixup stork module MooseDocs
  scripts/stork.sh
  stork/doc/config.yml.app
  stork/doc/config.yml.module
  stork/doc/moosedocs.py.app
  stork/doc/moosedocs.py.module
Labels: PR: Failed but allowed
