Repository idaholab/moose, pull requests merged in 2020-05, with the labels that each got.

#15191 Lower tolerence for ExodusViewer on mac
  python/peacock/tests/exodus_tab/test_ExodusViewer.py
Labels: C: Automatic Differentiation, PR: Auto Merge

#15189 Improve logic in mooseutils.find_moose_executable
  python/mooseutils/mooseutils.py
  python/mooseutils/tests/test_find_moose_executable.py
  python/mooseutils/tests/tests
Labels: PR: Failed but allowed

#15192 Use no-param c-tor to build an empty bounding box
  framework/src/meshgenerators/TiledMeshGenerator.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15199 Ignoring boost warnings with pragma system_header
  modules/stochastic_tools/include/distributions/BoostDistribution.h
  modules/stochastic_tools/include/distributions/BoostDistributionInclude.h
Labels: PR: Failed but allowed

#15200 Make PETScDMDAMesh unique_ids more unique
  modules/external_petsc_solver/src/mesh/PETScDMDAMesh.C
Labels: PR: Failed but allowed

#14740 Adding new classes that create material property for strain and stres…
  modules/tensor_mechanics/doc/content/source/auxkernels/RankTwoScalarAux.md
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoCartesianComponent.md
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoCylindricalComponent.md
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoDirectionalComponent.md
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoInvariant.md
  modules/tensor_mechanics/doc/content/source/materials/RankTwoCartesianComponent.md
  modules/tensor_mechanics/doc/content/source/materials/RankTwoCylindricalComponent.md
  modules/tensor_mechanics/doc/content/source/materials/RankTwoDirectionalComponent.md
  modules/tensor_mechanics/doc/content/source/materials/RankTwoInvariant.md
  modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md
  modules/tensor_mechanics/doc/content/syntax/Modules/TensorMechanics/Master/index.md
  modules/tensor_mechanics/include/actions/TensorMechanicsAction.h
  modules/tensor_mechanics/include/actions/TensorMechanicsActionBase.h
  modules/tensor_mechanics/include/materials/ADRankTwoCartesianComponent.h
  modules/tensor_mechanics/include/materials/ADRankTwoCylindricalComponent.h
  modules/tensor_mechanics/include/materials/ADRankTwoDirectionalComponent.h
  modules/tensor_mechanics/include/materials/ADRankTwoInvariant.h
  modules/tensor_mechanics/include/materials/RankTwoCartesianComponent.h
  modules/tensor_mechanics/include/materials/RankTwoCylindricalComponent.h
  modules/tensor_mechanics/include/materials/RankTwoDirectionalComponent.h
  modules/tensor_mechanics/include/materials/RankTwoInvariant.h
  modules/tensor_mechanics/include/utils/RankTwoScalarTools.h
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
  modules/tensor_mechanics/src/materials/ADRankTwoCartesianComponent.C
  modules/tensor_mechanics/src/materials/ADRankTwoCylindricalComponent.C
  modules/tensor_mechanics/src/materials/ADRankTwoDirectionalComponent.C
  modules/tensor_mechanics/src/materials/ADRankTwoInvariant.C
  modules/tensor_mechanics/src/materials/RankTwoCartesianComponent.C
  modules/tensor_mechanics/src/materials/RankTwoCylindricalComponent.C
  modules/tensor_mechanics/src/materials/RankTwoDirectionalComponent.C
  modules/tensor_mechanics/src/materials/RankTwoInvariant.C
  modules/tensor_mechanics/src/utils/RankTwoScalarTools.C
Labels: PR: Failed but allowed

#15206 speedup peridynamics slow tests
  modules/peridynamics/test/tests/mesh/2D_center_crack.i
  modules/peridynamics/test/tests/mesh/2D_double_edged_cracks.i
  modules/peridynamics/test/tests/mesh/gold/2D_center_crack_in.e
  modules/peridynamics/test/tests/mesh/gold/2D_double_edged_cracks_in.e
  modules/peridynamics/test/tests/plane_stress/conventional_planestress_HNOSPD.i
  modules/peridynamics/test/tests/plane_stress/conventional_planestress_OSPD.i
  modules/peridynamics/test/tests/plane_stress/gold/conventional_planestress_HNOSPD.e
  modules/peridynamics/test/tests/plane_stress/gold/conventional_planestress_OSPD.e
  modules/peridynamics/test/tests/plane_stress/tests
  modules/peridynamics/test/tests/plane_stress/weak_planestress_HNOSPD.i
  modules/peridynamics/test/tests/simple_tests/2D_finite_strain_HNOSPD.i
  modules/peridynamics/test/tests/simple_tests/gold/2D_finite_strain_HNOSPD.e
Labels: PR: Failed but allowed

#15010 Update scripts to python 3
  scripts/git_commit_history.py
  scripts/github_traffic.py
  scripts/tests/tests
Labels: PR: Failed but allowed

#15197 Add non-boost lognormal distribution
  modules/stochastic_tools/doc/content/source/distributions/LognormalDistribution.md
  modules/stochastic_tools/include/distributions/LognormalDistribution.h
  modules/stochastic_tools/src/distributions/LognormalDistribution.C
  modules/stochastic_tools/test/tests/distributions/gold/lognormal_out.csv
  modules/stochastic_tools/test/tests/distributions/lognormal.i
  modules/stochastic_tools/test/tests/distributions/tests
Labels: PR: Failed but allowed

#15211 Separate out general and moose specific installation instructions
  modules/doc/content/getting_started/installation/conda.md
  modules/doc/content/getting_started/installation/install_miniconda.md
  modules/doc/content/getting_started/installation/remove_moose_environment.md
  modules/doc/content/getting_started/installation/uninstall_conda.md
  modules/doc/content/getting_started/installation/windows10.md
  modules/doc/content/getting_started/installation/wsl.md
Labels: PR: Failed but allowed

#15210 Remove usage of deprecated options in modules tests
  modules/contact/test/tests/fieldsplit/frictional_mortar_FS.i
  modules/contact/test/tests/non-singular-frictional-mortar/frictional-mortar.i
  modules/contact/test/tests/normal-nodal-lm-tan-tolerance/normal-nodal-lm-tan-tolerance.i
  modules/tensor_mechanics/test/tests/plane_stress/ad_weak_plane_stress_finite.i
  modules/tensor_mechanics/test/tests/plane_stress/ad_weak_plane_stress_incremental.i
  modules/tensor_mechanics/test/tests/plane_stress/ad_weak_plane_stress_small.i
Labels: PR: Failed but allowed

#15187 Build bounding boxes properly
  framework/include/utils/MooseUtils.h
  framework/src/markers/BoxMarker.C
  framework/src/meshgenerators/BoundingBoxNodeSetGenerator.C
  framework/src/meshgenerators/SideSetsFromBoundingBoxGenerator.C
  framework/src/meshgenerators/SubdomainBoundingBoxGenerator.C
  framework/src/meshmodifiers/AddSideSetsFromBoundingBox.C
  framework/src/meshmodifiers/BoundingBoxNodeSet.C
  framework/src/meshmodifiers/SubdomainBoundingBox.C
  framework/src/utils/MooseUtils.C
Labels: PR: Failed but allowed

#15217 Add test for unknown parameter error in TestHarness
  python/FactorySystem/Parser.py
  python/TestHarness/tests/test_UnknownParam.py
  python/TestHarness/tests/tests
  test/tests/test_harness/unknown_param
Labels: PR: Failed but allowed

#15219 Add pseudo quadrature point to ADNodalBCTempl
  framework/include/bcs/ADNodalBC.h
Labels: PR: Failed but allowed

#14980 Changed double-execution check method in CSVReader
  framework/include/base/Attributes.h
  framework/include/loops/ComputeUserObjectsThread.h
  framework/src/base/Attributes.C
  framework/src/base/MooseApp.C
  framework/src/problems/FEProblemBase.C
  framework/src/vectorpostprocessors/CSVReader.C
  test/tests/vectorpostprocessors/csv_reader/gold/read_out_reader.csv
  test/tests/vectorpostprocessors/csv_reader/gold/read_preic_out_reader.csv
  test/tests/vectorpostprocessors/csv_reader/gold/read_preic_out_reader_0000.csv
  test/tests/vectorpostprocessors/csv_reader/multi_read_fail.i
  test/tests/vectorpostprocessors/csv_reader/read_multi_preic.i
  test/tests/vectorpostprocessors/csv_reader/tests
Labels: PR: Failed but allowed

#15220 Find exe 15017
  python/MooseDocs/extensions/appsyntax.py
  python/mooseutils/mooseutils.py
  python/mooseutils/tests/test_find_moose_executable.py
Labels: PR: Failed but allowed

#15223 More remote elem deletion changes
  framework/src/actions/SetupMeshCompleteAction.C
  framework/src/problems/FEProblemBase.C
  test/tests/auxkernels/ghosting_aux/gold/no_algebraic_ghosting_out.e
  test/tests/auxkernels/ghosting_aux/gold/no_ghosting_out.e
  test/tests/auxkernels/ghosting_aux/no_algebraic_ghosting.i
  test/tests/auxkernels/ghosting_aux/tests
  test/tests/relationship_managers/two_rm/gold/two_rm_out.e
Labels: PR: Failed but allowed

#15237 Plug some FV leaks
  framework/src/systems/NonlinearSystemBase.C
Labels: PR: Failed but allowed

#15176 more basic functionality added to Geochemistry module
  modules/geochemistry/include/utils/GeochemistryActivityCalculators.h
  modules/geochemistry/include/utils/GeochemistryActivityCoefficients.h
  modules/geochemistry/include/utils/GeochemistryActivityCoefficientsDebyeHuckel.h
  modules/geochemistry/include/utils/GeochemistryFormattedOutput.h
  modules/geochemistry/include/utils/GeochemistryIonicStrength.h
  modules/geochemistry/include/utils/PertinentGeochemicalSystem.h
  modules/geochemistry/src/outputs/GeochemicalModelInterrogator.C
  modules/geochemistry/src/userobjects/GeochemicalModelDefinition.C
  modules/geochemistry/src/utils/GeochemistryActivityCalculators.C
  modules/geochemistry/src/utils/GeochemistryActivityCoefficientsDebyeHuckel.C
  modules/geochemistry/src/utils/GeochemistryFormattedOutput.C
  modules/geochemistry/src/utils/GeochemistryIonicStrength.C
  modules/geochemistry/src/utils/GeochemistrySpeciesSwapper.C
  modules/geochemistry/src/utils/PertinentGeochemicalSystem.C
  modules/geochemistry/test/tests/interrogate_reactions/tests
  modules/geochemistry/unit/src/GeochemistryActivityCalculatorsTest.C
  modules/geochemistry/unit/src/GeochemistryActivityCoefficientsDebyeHuckelTest.C
  modules/geochemistry/unit/src/GeochemistryActivityTest.C
  modules/geochemistry/unit/src/GeochemistryFormattedOutputTest.C
  modules/geochemistry/unit/src/GeochemistryIonicStrengthTest.C
  modules/geochemistry/unit/src/GeochemistrySpeciesSwapperTest.C
  modules/geochemistry/unit/src/MinimalGeochemicalSystemTest.C
Labels: PR: Failed but allowed

#15233 Allow libmesh to condense all variables into one group if possible
  framework/src/systems/SystemBase.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15214 Initial AD GenericMaterialProperty problem
  framework/include/materials/InterfaceMaterial.h
  framework/include/materials/Material.h
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoCartesianComponent.md
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoCylindricalComponent.md
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoDirectionalComponent.md
  modules/tensor_mechanics/doc/content/source/materials/ADRankTwoInvariant.md
  modules/tensor_mechanics/doc/content/source/materials/RankTwoCylindricalComponent.md
  modules/tensor_mechanics/doc/content/source/utils/RankTwoScalarTools.md
  modules/tensor_mechanics/include/materials/ADRankTwoCartesianComponent.h
  modules/tensor_mechanics/include/materials/ADRankTwoCylindricalComponent.h
  modules/tensor_mechanics/include/materials/ADRankTwoDirectionalComponent.h
  modules/tensor_mechanics/include/materials/ADRankTwoInvariant.h
  modules/tensor_mechanics/include/materials/RankTwoCartesianComponent.h
  modules/tensor_mechanics/include/materials/RankTwoCylindricalComponent.h
  modules/tensor_mechanics/include/materials/RankTwoDirectionalComponent.h
  modules/tensor_mechanics/include/materials/RankTwoInvariant.h
  modules/tensor_mechanics/include/utils/RankTwoScalarTools.h
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
  modules/tensor_mechanics/src/materials/ADRankTwoCartesianComponent.C
  modules/tensor_mechanics/src/materials/ADRankTwoCylindricalComponent.C
  modules/tensor_mechanics/src/materials/ADRankTwoDirectionalComponent.C
  modules/tensor_mechanics/src/materials/ADRankTwoInvariant.C
  modules/tensor_mechanics/src/materials/RankTwoCartesianComponent.C
  modules/tensor_mechanics/src/materials/RankTwoCylindricalComponent.C
  modules/tensor_mechanics/src/materials/RankTwoDirectionalComponent.C
  modules/tensor_mechanics/src/materials/RankTwoInvariant.C
Labels: PR: Failed but allowed

#15252 fix arg to be pass by ref
  framework/include/base/Attributes.h
  framework/src/loops/ComputeFullJacobianThread.C
  framework/src/loops/ComputeJacobianThread.C
  framework/src/loops/ComputeResidualThread.C
Labels: PR: Failed but allowed

#15254 Don't use LU in FV scalar advection test
  test/tests/fvkernels/fv_constant_scalar_advection/2D_constant_scalar_advection.i
Labels: PR: Failed but allowed

#15257 Ensure that FV works with uniform refinement
  framework/src/mesh/MooseMesh.C
  test/tests/fvkernels/fv_simple_diffusion/fv_only.i
  test/tests/fvkernels/fv_simple_diffusion/fv_only_refined.i
  test/tests/fvkernels/fv_simple_diffusion/gold/fv_only_out.e
  test/tests/fvkernels/fv_simple_diffusion/gold/fv_only_refined_out.e
  test/tests/fvkernels/fv_simple_diffusion/tests
Labels: PR: Failed but allowed

#15258 Pass by reference instead in AttribBoundaries
  framework/include/base/Attributes.h
Labels: PR: Failed but allowed

#15068 Implement inertial forces for shell element
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/ShellElements.md
  modules/tensor_mechanics/doc/content/source/kernels/ADInertialForceShell.md
  modules/tensor_mechanics/include/kernels/ADInertialForceShell.h
  modules/tensor_mechanics/include/materials/ADComputeIncrementalShellStrain.h
  modules/tensor_mechanics/src/kernels/ADInertialForceShell.C
  modules/tensor_mechanics/src/materials/ADComputeIncrementalShellStrain.C
  modules/tensor_mechanics/test/tests/shell/dynamics/gold/shell_dynamics_bending_moment_free_orientation_inclined_hht_out.csv
  modules/tensor_mechanics/test/tests/shell/dynamics/gold/shell_dynamics_bending_moment_free_orientation_inclined_out.csv
  modules/tensor_mechanics/test/tests/shell/dynamics/gold/shell_dynamics_bending_moment_free_out.csv
  modules/tensor_mechanics/test/tests/shell/dynamics/shell_dynamics_bending_moment.i
  modules/tensor_mechanics/test/tests/shell/dynamics/shell_dynamics_bending_moment_free.i
  modules/tensor_mechanics/test/tests/shell/dynamics/shell_dynamics_bending_moment_free_orientation_inclined.i
  modules/tensor_mechanics/test/tests/shell/dynamics/shell_dynamics_bending_moment_free_orientation_inclined_hht.i
  modules/tensor_mechanics/test/tests/shell/dynamics/shell_inclined.e
  modules/tensor_mechanics/test/tests/shell/dynamics/tests
Labels: PR: Failed but allowed

#15266 Tighten solve tolerance of FV advection test
  test/tests/fvkernels/fv_constant_scalar_advection/2D_constant_scalar_advection.i
  test/tests/fvkernels/fv_constant_scalar_advection/gold/2D_constant_scalar_advection_out.e
Labels: PR: Failed but allowed

#15264 fix deprecated warnings in input files
  modules/combined/test/tests/gap_heat_transfer_jac/two_blocks.i
  modules/combined/test/tests/heat_convection/heat_convection_function.i
  modules/stochastic_tools/test/tests/surrogates/poly_chaos/master_2d_quad_locs.i
  modules/stochastic_tools/test/tests/surrogates/poly_chaos/master_2dnorm_quad_locs.i
  modules/stochastic_tools/test/tests/surrogates/poly_chaos/tests
  modules/tensor_mechanics/test/tests/shell/static/beam_bending_moment_AD_2.i
Labels: PR: Failed but allowed

#15222 May 2020 News
  modules/doc/content/newsletter/2020_05.md
  modules/doc/content/newsletter/2020_06.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#15269 speed up jacobian test
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_second/finite.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_second/finite_rr.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_second/small.i
  modules/contact/test/tests/mortar_tm/2drz/ad_frictionless_second/tests
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/finite.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/finite_noaction.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/finite_rr.i
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/gold/small.csv
  modules/contact/test/tests/mortar_tm/2drz/frictionless_second/small.i
Labels: PR: Failed but allowed

#15272 Add traction form to INSAD implementation
  modules/navier_stokes/include/bcs/INSADMomentumNoBCBC.h
  modules/navier_stokes/include/kernels/INSADMomentumViscous.h
  modules/navier_stokes/include/materials/INSADMaterial.h
  modules/navier_stokes/include/userobjects/INSADObjectTracker.h
  modules/navier_stokes/src/bcs/INSADMomentumNoBCBC.C
  modules/navier_stokes/src/kernels/INSADMomentumViscous.C
  modules/navier_stokes/src/materials/INSADMaterial.C
  modules/navier_stokes/test/tests/ins/RZ_cone/ad_rz_cone_by_parts_traction_steady_stabilized.i
  modules/navier_stokes/test/tests/ins/RZ_cone/ad_rz_cone_no_parts.i
  modules/navier_stokes/test/tests/ins/RZ_cone/gold/ad_rz_cone_by_parts_traction_steady_stabilized_out.e
  modules/navier_stokes/test/tests/ins/RZ_cone/gold/ad_rz_cone_no_parts_out.e
  modules/navier_stokes/test/tests/ins/RZ_cone/gold/rz_cone_by_parts_traction_steady_stabilized_out.e
  modules/navier_stokes/test/tests/ins/RZ_cone/rz_cone_by_parts_traction_steady_stabilized.i
  modules/navier_stokes/test/tests/ins/RZ_cone/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15275 Small bug fixes and dual number output cleanup to LAROMANCE
  modules/tensor_mechanics/src/materials/ADLAROMANCEStressUpdateBase.C
Labels: PR: Failed but allowed

#15271 FV: speed things up a bit
  framework/include/base/Assembly.h
  framework/include/loops/ComputeFVFluxThread.h
  framework/src/base/Assembly.C
Labels: PR: Do Not Merge, PR: Failed but allowed

#15279 Make a couple of slow tests heavy
  modules/solid_mechanics/test/tests/interaction_integral_benchmark/tests
  modules/tensor_mechanics/test/tests/interaction_integral_benchmark/tests
Labels: PR: Failed but allowed

#15281 Make an SM test not give a deprecated error
  modules/combined/test/tests/solid_mechanics_deprecated/contact/tests
Labels: PR: Failed but allowed

#15286 Make tests of deprecated code not fail the deprecated tests
  modules/stochastic_tools/test/tests/distributions/tests
  python/TestHarness/testers/RunApp.py
  test/make
  test/tests/geomsearch/patch_update_strategy/tests
  test/tests/mesh/mesh_generation/tests
  test/tests/mesh_modifiers/add_all_side_sets/tests
  test/tests/mesh_modifiers/add_extra_nodeset/tests
  test/tests/mesh_modifiers/add_side_sets/tests
  test/tests/mesh_modifiers/add_side_sets_from_bounding_box/tests
  test/tests/mesh_modifiers/assign_element_subdomain_id/tests
  test/tests/mesh_modifiers/assign_subdomain_id/tests
  test/tests/mesh_modifiers/block_deleter/tests
  test/tests/mesh_modifiers/boundingbox_nodeset/tests
  test/tests/mesh_modifiers/break_boundary/tests
  test/tests/mesh_modifiers/break_mesh_by_blocks/2D/tests
  test/tests/mesh_modifiers/break_mesh_by_blocks/3D/tests
  test/tests/mesh_modifiers/image_subdomain/tests
  test/tests/mesh_modifiers/lower_d_block/tests
  test/tests/mesh_modifiers/mesh_extruder/tests
  test/tests/mesh_modifiers/mesh_side_set/tests
  test/tests/mesh_modifiers/modifier_depend_order/tests
  test/tests/mesh_modifiers/parsed_sideset/tests
  test/tests/mesh_modifiers/parsed_subdomain/tests
  test/tests/mesh_modifiers/rename_block/tests
  test/tests/mesh_modifiers/sidesets_around_subdomain/tests
  test/tests/mesh_modifiers/sidesets_between_subdomains/tests
  test/tests/mesh_modifiers/smooth_mesh/tests
  test/tests/mesh_modifiers/subdomain_bounding_box/tests
  test/tests/mesh_modifiers/transform/tests
  test/tests/meshgenerators/annular_mesh_generator/tests
Labels: PR: Failed but allowed

#15274 Add missing contact class descriptions
  modules/contact/src/constraints/NormalMortarLMMechanicalContact.C
  modules/contact/src/constraints/NormalNodalMechanicalContact.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15240 Executing multiapps on final with Steady executioner
  framework/src/executioners/EigenExecutionerBase.C
  framework/src/executioners/Steady.C
  test/tests/multiapps/full_solve_multiapp/gold/exec_final.e
  test/tests/multiapps/full_solve_multiapp/gold/exec_final_eigen.e
  test/tests/multiapps/full_solve_multiapp/gold/exec_final_eigen_full_solve0.e
  test/tests/multiapps/full_solve_multiapp/gold/exec_final_full_solve0.e
  test/tests/multiapps/full_solve_multiapp/gold/master_eigen_out.e
  test/tests/multiapps/full_solve_multiapp/gold/master_eigen_out_full_solve0.e
  test/tests/multiapps/full_solve_multiapp/master_eigen.i
  test/tests/multiapps/full_solve_multiapp/tests
Labels: PR: Failed but allowed

#15288 Moving StiffenedGasTwoPhaseFluidProperties into fluid_properties module
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/source/userobjects/StiffenedGasTwoPhaseFluidProperties.md
  modules/fluid_properties/include/userobjects/StiffenedGasTwoPhaseFluidProperties.h
  modules/fluid_properties/src/userobjects/StiffenedGasTwoPhaseFluidProperties.C
  modules/fluid_properties/unit/include/StiffenedGasTwoPhaseFluidPropertiesTest.h
  modules/fluid_properties/unit/src/StiffenedGasTwoPhaseFluidPropertiesTest.C
Labels: PR: Ready for Review/Merge

#15284 Enable type storage for vector tags
  framework/include/base/Assembly.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/SubProblem.h
  framework/include/utils/MooseTypes.h
  framework/include/utils/VectorTag.h
  framework/include/warehouses/MooseObjectTagWarehouse.h
  framework/src/base/Assembly.C
  framework/src/interfaces/Coupleable.C
  framework/src/interfaces/ScalarCoupleable.C
  framework/src/interfaces/TaggingInterface.C
  framework/src/loops/ComputeNodalKernelBcsThread.C
  framework/src/loops/ComputeNodalKernelsThread.C
  framework/src/loops/ComputeResidualThread.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/MooseTypes.C
  framework/src/utils/VectorTag.C
  framework/src/variables/MooseVariableData.C
  framework/src/variables/MooseVariableDataFV.C
  framework/src/variables/MooseVariableScalar.C
  test/src/problems/FixedPointProblem.C
  test/tests/kernels/tag_errors/tag_doesnt_exist/tests
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15289 Fix bug that creates empty directories when using abs path.
  framework/include/utils/MooseUtils.h
  framework/src/outputs/FileOutput.C
  framework/src/utils/MooseUtils.C
Labels: PR: Failed but allowed

#15278 Added AD versions of TwoPhaseFluidProperties interfaces
  modules/fluid_properties/include/userobjects/StiffenedGasTwoPhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/TwoPhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/TwoPhaseFluidPropertiesIndependent.h
  modules/fluid_properties/include/userobjects/TwoPhaseNCGFluidProperties.h
  modules/fluid_properties/src/userobjects/TwoPhaseFluidProperties.C
  modules/fluid_properties/test/include/userobjects/TestTwoPhaseFluidProperties.h
  modules/fluid_properties/test/include/userobjects/TestTwoPhaseNCGFluidProperties.h
  modules/fluid_properties/unit/include/ADFluidPropsTest.h
  modules/fluid_properties/unit/src/ADFluidPropsTest.C
Labels: PR: Failed but allowed

#15205 Add grad_zero for phi and test function
  framework/doc/content/source/variables/PhiZero.md
  framework/include/interfaces/Coupleable.h
  framework/include/problems/FEProblemBase.h
  framework/src/interfaces/Coupleable.C
  framework/src/problems/FEProblemBase.C
  test/include/kernels/PhiZeroKernel.h
  test/src/kernels/PhiZeroKernel.C
  test/tests/phi_zero/simple_transient_diffusion.i
  test/tests/phi_zero/tests
Labels: PR: Failed but allowed

#15312 Reference list
  framework/doc/content/bib/external_papers_citing_moose.bib
  framework/doc/content/bib/external_papers_using_moose.bib
  framework/doc/content/bib/inl_papers_citing_moose.bib
  framework/doc/content/bib/inl_papers_using_moose.bib
  modules/doc/content/citing.md
  modules/doc/content/documentation.menu.md
  modules/doc/content/publications.md
  python/MooseDocs/extensions/bibtex.py
  python/MooseDocs/test/content/extensions/bibtex.md
Labels: PR: Failed but allowed

#15306 Fix doco warnings
  framework/doc/hidden.yml
  framework/include/postprocessors/SideIntegralVariablePostprocessor.h
  framework/src/actions/AddMeshGeneratorAction.C
  framework/src/actions/AddPeriodicBCAction.C
  framework/src/dgkernels/ADDGDiffusion.C
  framework/src/fvbcs/FVMatAdvectionOutflowBC.C
  framework/src/fvkernels/FVReaction.C
  framework/src/mesh/MeshGeneratorMesh.C
  framework/src/outputs/png/PNGOutput.C
  framework/src/postprocessors/DifferencePostprocessor.C
  framework/src/postprocessors/ElementIntegralMaterialProperty.C
  framework/src/postprocessors/ElementIntegralVariablePostprocessor.C
  framework/src/postprocessors/ElementL2Error.C
  framework/src/postprocessors/LinearCombinationPostprocessor.C
  framework/src/postprocessors/PointValue.C
  framework/src/postprocessors/SideIntegralVariablePostprocessor.C
  framework/src/timeintegrators/ExplicitSSPRungeKutta.C
  framework/src/userobject/NearestPointLayeredAverage.C
  framework/src/userobject/NearestPointLayeredIntegral.C
  modules/chemical_reactions/doc/hidden.yml
  modules/chemical_reactions/include/kernels/DarcyFluxPressure.h
  modules/chemical_reactions/src/kernels/DarcyFluxPressure.C
  modules/contact/doc/hidden.yml
  modules/doc/config.yml
  modules/fluid_properties/doc/hidden.yml
  modules/heat_conduction/doc/hidden.yml
  modules/peridynamics/doc/config.yml
  modules/peridynamics/doc/hidden.yml
  modules/phase_field/doc/hidden.yml
  modules/stochastic_tools/doc/config.yml
  modules/stochastic_tools/doc/hidden.yml
  modules/tensor_mechanics/doc/hidden.yml
  modules/xfem/doc/hidden.yml
  python/MooseDocs/commands/build.py
  python/MooseDocs/commands/check.py
  test/Makefile
  test/src/vectorpostprocessors/TestFaceInfo.C
Labels: PR: Failed but allowed

#15309 Added AD saturation temperature and surface tension materials
  modules/fluid_properties/doc/content/source/materials/ADSaturationTemperatureMaterial.md
  modules/fluid_properties/doc/content/source/materials/ADSurfaceTensionMaterial.md
  modules/fluid_properties/include/materials/ADSaturationTemperatureMaterial.h
  modules/fluid_properties/include/materials/ADSurfaceTensionMaterial.h
  modules/fluid_properties/src/materials/ADSaturationTemperatureMaterial.C
  modules/fluid_properties/src/materials/ADSurfaceTensionMaterial.C
  modules/fluid_properties/test/tests/materials/ad_saturation_temperature_material/ad_saturation_temperature_material.i
  modules/fluid_properties/test/tests/materials/ad_saturation_temperature_material/gold/ad_saturation_temperature_material_out.csv
  modules/fluid_properties/test/tests/materials/ad_saturation_temperature_material/tests
  modules/fluid_properties/test/tests/materials/ad_surface_tension_material/ad_surface_tension_material.i
  modules/fluid_properties/test/tests/materials/ad_surface_tension_material/gold/ad_surface_tension_material_out.csv
  modules/fluid_properties/test/tests/materials/ad_surface_tension_material/tests
Labels: PR: Failed but allowed

#15317 Support residual output for elemental variables
  framework/src/actions/SetupResidualDebugAction.C
  framework/src/auxkernels/DebugResidualAux.C
  test/tests/outputs/residual/gold/out_elem.e
  test/tests/outputs/residual/output_residual_elem.i
  test/tests/outputs/residual/tests
Labels: PR: Failed but allowed

#15319 Reserve in Assembly::clearCachedResiduals()
  framework/include/base/Assembly.h
  framework/src/base/Assembly.C
Labels: PR: Auto Merge, PR: Failed but allowed

#14895 Expanding VectorPostprocessorFunction to interpolate within time domain
  framework/doc/content/source/functions/VectorPostprocessorFunction.md
  framework/include/functions/VectorPostprocessorFunction.h
  framework/src/functions/VectorPostprocessorFunction.C
  test/tests/functions/vector_postprocessor_function/gold/vpp_time_interpolation_out.csv
  test/tests/functions/vector_postprocessor_function/tests
  test/tests/functions/vector_postprocessor_function/time_data.csv
  test/tests/functions/vector_postprocessor_function/vector_postprocessor_function.i
  test/tests/functions/vector_postprocessor_function/vpp_time_interpolation.i
Labels: PR: Failed but allowed

#15277 add GenericRankNTensor
  framework/include/utils/MooseTypes.h
  unit/src/RankFourTensorTest.C
  unit/src/RankThreeTensorTest.C
  unit/src/RankTwoTensorTest.C
Labels: PR: Failed but allowed

#15326 Fixing doco
  modules/heat_conduction/src/kernels/ADMatHeatSource.C
  modules/tensor_mechanics/src/actions/CavityPressureAction.C
  modules/tensor_mechanics/src/actions/CavityPressureUOAction.C
  modules/tensor_mechanics/src/actions/CommonTensorMechanicsAction.C
Labels: PR: Auto Merge, PR: Failed but allowed

#15216 Enable usage of dual shape functions for the Lagrange multipliers
  framework/include/base/Assembly.h
  framework/include/constraints/MortarConstraintBase.h
  framework/include/variables/MooseVariableBase.h
  framework/include/variables/MooseVariableData.h
  framework/src/base/Assembly.C
  framework/src/constraints/MortarConstraintBase.C
  framework/src/variables/MooseVariableBase.C
  framework/src/variables/MooseVariableData.C
  test/tests/mortar/continuity-2d-conforming/gold/dual-conforming_out.e
  test/tests/mortar/continuity-2d-conforming/tests
  test/tests/mortar/continuity-2d-non-conforming/dual-soln-continuity.i
  test/tests/mortar/continuity-2d-non-conforming/gold/dual-soln-continuity-2nd-order_out.e
  test/tests/mortar/continuity-2d-non-conforming/gold/dual-soln-continuity_out.e
  test/tests/mortar/continuity-2d-non-conforming/tests
Labels: PR: Failed but allowed

#15324 Fixed "fall through" for PR "New PR: Eigen system supports shell matrices"
  framework/src/preconditioners/PhysicsBasedPreconditioner.C
  framework/src/utils/SlepcSupport.C
Labels: PR: Ready for Review/Merge

#15265 Enhancement to FindValueOnLine postprocessor
  framework/include/postprocessors/FindValueOnLine.h
  framework/src/postprocessors/FindValueOnLine.C
  test/tests/postprocessors/find_value_on_line/gold/findvalueonline_flag_above_out.csv
  test/tests/postprocessors/find_value_on_line/gold/findvalueonline_flag_above_user_out.csv
  test/tests/postprocessors/find_value_on_line/gold/findvalueonline_flag_below_out.csv
  test/tests/postprocessors/find_value_on_line/gold/findvalueonline_flag_below_user_out.csv
  test/tests/postprocessors/find_value_on_line/tests
Labels: PR: Failed but allowed

#15341 Fixing doco for ShellElements.md
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/ShellElements.md
Labels: PR: Ready for Review/Merge

#15297 Don't write master data when a master elem doesn't exist
  framework/src/constraints/ADMortarConstraint.C
  framework/src/constraints/MortarConstraint.C
  framework/src/constraints/MortarConstraintBase.C
  modules/contact/test/tests/normal-nodal-lm-tan-tolerance/gold/normal-nodal-lm-tan-tolerance_out.e
  test/tests/mortar/displaced-gap-conductance-2d-non-conforming/gold/gap-conductance_out.e
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15334 Dont execute stateful materials when doing mortar
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialData.h
  framework/include/problems/FEProblemBase.h
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/materials/MaterialBase.C
  framework/src/materials/MaterialData.C
  framework/src/problems/FEProblemBase.C
  test/src/materials/SpatialStatefulMaterial.C
  test/tests/mortar/gap-conductance-2d-non-conforming/gap-conductance.i
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#15346 Update velocity to AD in level set
  modules/level_set/examples/circle/circle_16.i
  modules/level_set/examples/rotating_circle/circle_rotate.i
  modules/level_set/examples/rotating_circle/circle_rotate_master.i
  modules/level_set/examples/rotating_circle/circle_rotate_supg.i
  modules/level_set/examples/vortex/vortex.i
  modules/level_set/examples/vortex/vortex_reinit.i
  modules/level_set/examples/vortex/vortex_supg.i
  modules/level_set/include/functions/LevelSetOlssonVortex.h
  modules/level_set/include/interfaces/LevelSetVelocityInterface.h
  modules/level_set/include/kernels/LevelSetAdvection.h
  modules/level_set/include/kernels/LevelSetAdvectionSUPG.h
  modules/level_set/include/kernels/LevelSetForcingFunctionSUPG.h
  modules/level_set/include/kernels/LevelSetTimeDerivativeSUPG.h
  modules/level_set/include/postprocessors/LevelSetCFLCondition.h
  modules/level_set/src/functions/LevelSetOlssonVortex.C
  modules/level_set/src/interfaces/LevelSetVelocityInterface.C
  modules/level_set/src/kernels/LevelSetAdvection.C
  modules/level_set/src/kernels/LevelSetAdvectionSUPG.C
  modules/level_set/src/kernels/LevelSetForcingFunctionSUPG.C
  modules/level_set/src/kernels/LevelSetTimeDerivativeSUPG.C
  modules/level_set/src/postprocessors/LevelSetCFLCondition.C
  modules/level_set/test/tests/functions/olsson_vortex/gold/olsson_vortex_cosine_out.e
  modules/level_set/test/tests/functions/olsson_vortex/gold/olsson_vortex_out.e
  modules/level_set/test/tests/functions/olsson_vortex/olsson_vortex.i
  modules/level_set/test/tests/functions/olsson_vortex/tests
  modules/level_set/test/tests/kernels/advection/advection_mms.i
  modules/level_set/test/tests/reinitialization/gold/master_modified.e
  modules/level_set/test/tests/reinitialization/gold/master_original.e
  modules/level_set/test/tests/reinitialization/master.i
  modules/level_set/test/tests/verification/1d_level_set_mms/level_set_mms.i
  modules/level_set/test/tests/verification/1d_level_set_supg_mms/1d_level_set_supg_mms.i
Labels: PR: Failed but allowed

#15345 New stress/strain combinations for TM Master Action
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
Labels: PR: Failed but allowed
