Repository idaholab/moose, pull requests merged in 2021-07, with the labels that each got.

#18223 Add ability to output the time the TimeExtremeValue occurred
  framework/doc/content/source/postprocessors/TimeExtremeValue.md
  framework/include/postprocessors/TimeExtremeValue.h
  framework/src/postprocessors/TimeExtremeValue.C
  test/tests/postprocessors/time_extreme_value/gold/time_of_time_extreme_value_out.csv
  test/tests/postprocessors/time_extreme_value/tests
  test/tests/postprocessors/time_extreme_value/time_extreme_value.i
Labels: PR: Auto Merge

#18231 Add missing FSI SQA pages
  modules/fsi/doc/config.yml
  modules/fsi/doc/content/modules/fsi/sqa/fsi_far.md
  modules/fsi/doc/content/modules/fsi/sqa/fsi_sll.md
Labels: PR: Failed but allowed

#18160 Do not construct solve objects in executioner base class
  framework/include/executioners/EigenExecutionerBase.h
  framework/include/executioners/Eigenvalue.h
  framework/include/executioners/Executioner.h
  framework/include/executioners/FEProblemSolve.h
  framework/include/executioners/Steady.h
  framework/include/executioners/Transient.h
  framework/src/actions/CreateExecutionerAction.C
  framework/src/executioners/EigenExecutionerBase.C
  framework/src/executioners/Eigenvalue.C
  framework/src/executioners/Executioner.C
  framework/src/executioners/FEProblemSolve.C
  framework/src/executioners/Steady.C
  framework/src/executioners/Transient.C
  framework/src/timesteppers/TimeStepper.C
  test/tests/geomsearch/patch_update_strategy/always-grid-sequence.i
  test/tests/multiapps/picard_multilevel/2level_picard/mutilevel_app.i
  test/tests/multiapps/steffensen/steady_main.i
Labels: PR: Failed but allowed

#18230 Optimize eigen decomposition for Hill tensor
  modules/tensor_mechanics/include/materials/ADGeneralizedRadialReturnStressUpdate.h
  modules/tensor_mechanics/src/materials/ADGeneralizedRadialReturnStressUpdate.C
  modules/tensor_mechanics/src/materials/ADHillElastoPlasticityStressUpdate.C
  modules/tensor_mechanics/src/materials/ADHillPlasticityStressUpdate.C
Labels: PR: Failed but allowed

#18119 Add template for accepting vector diffusivity in diffusive flux postprocessor
  framework/include/postprocessors/SideDiffusiveFluxAverage.h
  framework/include/postprocessors/SideDiffusiveFluxIntegral.h
  framework/src/postprocessors/SideDiffusiveFluxAverage.C
  framework/src/postprocessors/SideDiffusiveFluxIntegral.C
  test/tests/postprocessors/side_diffusive_flux_integral/gold/side_diffusive_flux_integral_fv_out.e
  test/tests/postprocessors/side_diffusive_flux_integral/gold/side_diffusive_flux_integral_fv_vector.e
  test/tests/postprocessors/side_diffusive_flux_integral/gold/side_diffusive_flux_integral_out.e
  test/tests/postprocessors/side_diffusive_flux_integral/gold/side_diffusive_flux_integral_vector.e
  test/tests/postprocessors/side_diffusive_flux_integral/side_diffusive_flux_integral.i
  test/tests/postprocessors/side_diffusive_flux_integral/side_diffusive_flux_integral_fv.i
  test/tests/postprocessors/side_diffusive_flux_integral/tests
Labels: PR: Failed but allowed

#18225 Protect against failed point inversions due to interface kernels
  framework/doc/content/syntax/InterfaceKernels/index.md
  framework/include/problems/FEProblemBase.h
  framework/src/problems/FEProblemBase.C
  test/tests/interfacekernels/1d_interface/gold/no-failed-point-inversions_out.e
  test/tests/interfacekernels/1d_interface/no-failed-point-inversions.i
  test/tests/interfacekernels/1d_interface/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#18306 Fix missing reinit introduced in #18225
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed

#18287 Minor updates to validation schema used by NEAMS Workbench
  framework/src/base/MooseApp.C
  framework/src/outputs/formatters/SONDefinitionFormatter.C
  test/tests/outputs/format/tests
Labels: PR: Failed but allowed

#18116 FancyExtruderGenerator Extra Element ID Fix and Adding Test Cases
  framework/include/meshgenerators/FancyExtruderGenerator.h
  framework/src/meshgenerators/FancyExtruderGenerator.C
  test/tests/meshgenerators/fancy_extruder_generator/fancy_extruder_with_element_extra_integer_swap.i
  test/tests/meshgenerators/fancy_extruder_generator/gold/fancy_extruder_with_element_extra_integer_swap_out.e
  test/tests/meshgenerators/fancy_extruder_generator/mesh_2d.e
  test/tests/meshgenerators/fancy_extruder_generator/tests
Labels: PR: Failed but allowed

#18316 Add derivative information to thermal expansion function objects
  framework/include/functions/ConstantFunction.h
  framework/src/functions/ConstantFunction.C
  modules/tensor_mechanics/src/materials/ADComputeInstantaneousThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ADComputeMeanThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/test/tests/ad_thermal_expansion_function/gold/instantaneous_complex_out.csv
  modules/tensor_mechanics/test/tests/ad_thermal_expansion_function/gold/mean_complex_out.csv
  modules/tensor_mechanics/test/tests/ad_thermal_expansion_function/instantaneous_complex.i
  modules/tensor_mechanics/test/tests/ad_thermal_expansion_function/mean_complex.i
  modules/tensor_mechanics/test/tests/ad_thermal_expansion_function/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#18235 PorousFlowElementNormal and ElementLength added
  modules/porous_flow/doc/content/media/porous_flow/PorousFlowElementLength.png
  modules/porous_flow/doc/content/source/auxkernels/PorousFlowElementLength.md
  modules/porous_flow/doc/content/source/auxkernels/PorousFlowElementNormal.md
  modules/porous_flow/include/auxkernels/PorousFlowElementLength.h
  modules/porous_flow/include/auxkernels/PorousFlowElementNormal.h
  modules/porous_flow/src/auxkernels/PorousFlowElementLength.C
  modules/porous_flow/src/auxkernels/PorousFlowElementNormal.C
  modules/porous_flow/test/tests/aux_kernels/element_length_2D.i
  modules/porous_flow/test/tests/aux_kernels/element_length_3D.i
  modules/porous_flow/test/tests/aux_kernels/element_length_except1.i
  modules/porous_flow/test/tests/aux_kernels/element_length_except2.i
  modules/porous_flow/test/tests/aux_kernels/element_normal_1D_2D.i
  modules/porous_flow/test/tests/aux_kernels/element_normal_2D_3D.i
  modules/porous_flow/test/tests/aux_kernels/element_normal_except1.i
  modules/porous_flow/test/tests/aux_kernels/element_normal_except2.i
  modules/porous_flow/test/tests/aux_kernels/element_normal_except3.i
  modules/porous_flow/test/tests/aux_kernels/gold/element_length_2D_out.csv
  modules/porous_flow/test/tests/aux_kernels/gold/element_length_3D_out.csv
  modules/porous_flow/test/tests/aux_kernels/gold/element_normal_1D_2D_out.csv
  modules/porous_flow/test/tests/aux_kernels/gold/element_normal_2D_3D_out.csv
  modules/porous_flow/test/tests/aux_kernels/tests
Labels: PR: Failed but allowed

#18062 Add option to consider off-diags in auto scaling
  framework/doc/content/source/systems/NonlinearSystemBase.md
  framework/include/loops/ComputeJacobianForScalingThread.h
  framework/include/systems/NonlinearSystemBase.h
  framework/include/utils/OffDiagonalScalingMatrix.h
  framework/src/executioners/FEProblemSolve.C
  framework/src/loops/ComputeJacobianForScalingThread.C
  framework/src/systems/NonlinearEigenSystem.C
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/NonlinearSystemBase.C
  test/tests/scaling/off-diag-scaling/gold/off_diag.e
  test/tests/scaling/off-diag-scaling/gold/test_out.e
  test/tests/scaling/off-diag-scaling/test.i
  test/tests/scaling/off-diag-scaling/tests
Labels: PR: Failed but allowed

#18234 Add inactive timesteps option to Newmark beta so that time derivative calcul…
  framework/doc/content/media/time_integrators/inactive_tsteps_u.png
  framework/doc/content/media/time_integrators/inactive_tsteps_udot.png
  framework/doc/content/media/time_integrators/inactive_tsteps_udotdot.png
  framework/doc/content/source/timeintegrators/NewmarkBeta.md
  framework/include/timeintegrators/NewmarkBeta.h
  framework/src/timeintegrators/NewmarkBeta.C
  test/tests/time_integrators/newmark-beta/gold/newmark_beta_inactive_steps_out.csv
  test/tests/time_integrators/newmark-beta/newmark_beta_inactive_steps.i
  test/tests/time_integrators/newmark-beta/tests
Labels: PR: Failed but allowed

#18383 Temperature-dependent Hill parameters
  modules/tensor_mechanics/include/materials/HillConstants.h
  modules/tensor_mechanics/src/materials/HillConstants.C
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_temperature_coefficients.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_temperature_coefficients_function.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_temperature_coefficients_function_variation.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/gold/ad_aniso_creep_temperature_coefficients_function_out.e
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/gold/ad_aniso_creep_temperature_coefficients_function_variation_out.e
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/gold/ad_aniso_creep_temperature_coefficients_out.e
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/temperature.exodiff
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/tests
Labels: PR: Failed but allowed

#18296 Install adreal monolithic header for jit in conda packages
  framework/moose.mk
Labels: PR: Failed but allowed

#18354 map to unordered_map for augmenting sparsity
  framework/include/systems/NonlinearSystemBase.h
  framework/src/systems/NonlinearSystemBase.C
Labels: PR: Failed but allowed

#18389 Only store a mat prop if we declare it
  framework/src/materials/MaterialBase.C
  framework/src/problems/SubProblem.C
  modules/tensor_mechanics/test/tests/strain_energy_density/tests
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed

#18401 Do not check the return code for MooseDocs check command
  python/MooseDocs/test/commands/test_check.py
Labels: PR: Failed but allowed

#18443 (AD/nonAD)-ified NeumannBC & MatNeumannBC
  framework/include/bcs/ADNeumannBC.h
  framework/include/bcs/MatNeumannBC.h
  framework/include/bcs/NeumannBC.h
  framework/src/bcs/ADNeumannBC.C
  framework/src/bcs/MatNeumannBC.C
  framework/src/bcs/NeumannBC.C
  test/tests/bcs/mat_neumann_bc/ad_mat_neumann.i
  test/tests/bcs/mat_neumann_bc/gold/ad_mat_neumann_out.e
  test/tests/bcs/mat_neumann_bc/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#18357 Improving performance of CIVET commit information
  python/MooseDocs/commands/build.py
  python/MooseDocs/extensions/civet.py
  python/mooseutils/__init__.py
  python/mooseutils/civet_results.py
  python/mooseutils/gitutils.py
  python/mooseutils/tests/test_civet_results.py
Labels: PR: Auto Merge, PR: Failed but allowed

#18448 Reset _prev_elem cache when mesh changes
  framework/include/variables/MooseVariableDataFV.h
  framework/src/variables/MooseVariableDataFV.C
Labels: PR: Failed but allowed
