Repository idaholab/moose, pull requests merged in 2021-12, with the labels that each got.

#19524 Added in citation to the JOSS article 'The MOOSE geochemistry module'
  modules/doc/content/citing.md
  modules/geochemistry/doc/content/bib/geochemistry.bib
Labels: PR: Auto Merge

#19218 Adding reporting ID capability in reactor module
  framework/doc/content/source/meshgenerators/PlaneIDMeshGenerator.md
  framework/include/meshgenerators/PlaneIDMeshGenerator.h
  framework/src/meshgenerators/PlaneIDMeshGenerator.C
  modules/reactor/doc/content/modules/reactor/index.md
  modules/reactor/doc/content/source/meshgenerators/CartesianIDPatternedMeshGenerator.md
  modules/reactor/doc/content/source/meshgenerators/HexIDPatternedMeshGenerator.md
  modules/reactor/include/meshgenerators/CartesianIDPatternedMeshGenerator.h
  modules/reactor/include/meshgenerators/HexIDPatternedMeshGenerator.h
  modules/reactor/include/utils/ReportingIDGeneratorUtils.h
  modules/reactor/src/meshgenerators/CartesianIDPatternedMeshGenerator.C
  modules/reactor/src/meshgenerators/HexIDPatternedMeshGenerator.C
  modules/reactor/src/utils/ReportingIDGeneratorUtils.C
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/assembly_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/core_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/core_zigzag_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/gold/assembly_reporting_id_cell_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/gold/assembly_reporting_id_manual_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/gold/assembly_reporting_id_pattern_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/gold/core_reporting_id_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/gold/core_zigzag_reporting_id_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/tests
  modules/reactor/test/tests/meshgenerators/reporting_id/gold/plane_reporting_id_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/assembly_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/core_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/core_reporting_id_exclude.i
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/gold/assembly_reporting_id_cell_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/gold/assembly_reporting_id_manual_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/gold/assembly_reporting_id_pattern_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/gold/core_reporting_id_exclude_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/gold/core_reporting_id_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/tests
  test/tests/meshgenerators/plane_id_mesh_generator/gold/plane_id_grid2d_x_dir_out.e
  test/tests/meshgenerators/plane_id_mesh_generator/gold/plane_id_grid2d_y_dir_out.e
  test/tests/meshgenerators/plane_id_mesh_generator/gold/plane_id_pin3d_out.e
  test/tests/meshgenerators/plane_id_mesh_generator/plane_id_grid2d.i
  test/tests/meshgenerators/plane_id_mesh_generator/plane_id_pin3d.i
  test/tests/meshgenerators/plane_id_mesh_generator/tests
Labels: PR: Failed but allowed

#19484 Bump up timestep tolerance on Transient Executioner
  framework/src/executioners/Transient.C
  modules/tensor_mechanics/test/tests/ad_smeared_cracking/gold/cracking_xyz_out.e
  modules/tensor_mechanics/test/tests/smeared_cracking/gold/cracking_xyz_out.e
Labels: PR: Failed but allowed

#19527 Add missing modules to stork makefile
  stork/Makefile.app
Labels: PR: Auto Merge

#19500 Register optional properties
  framework/doc/content/syntax/Materials/index.md
  framework/include/actions/ResolveOptionalMaterialPropertiesAction.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialProperty.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/include/postprocessors/SideIntegralMaterialProperty.h
  framework/include/utils/IndexableProperty.h
  framework/include/warehouses/MooseObjectWarehouseBase.h
  framework/src/actions/ResolveOptionalMaterialPropertiesAction.C
  framework/src/base/Moose.C
  framework/src/materials/Material.C
  framework/src/postprocessors/SideIntegralMaterialProperty.C
  modules/porous_flow/include/materials/PorousFlowPorosityLinear.h
  modules/porous_flow/src/materials/PorousFlowPorosityLinear.C
  modules/porous_flow/test/tests/poroperm/linear_except1.i
  modules/tensor_mechanics/include/materials/EshelbyTensor.h
  modules/tensor_mechanics/include/materials/StrainEnergyDensity.h
  modules/tensor_mechanics/src/materials/EshelbyTensor.C
  modules/tensor_mechanics/src/materials/StrainEnergyDensity.C
  modules/tensor_mechanics/test/tests/strain_energy_density/tests
  test/include/auxkernels/OptionalTestAux.h
  test/include/materials/OptionalTestMaterial.h
  test/include/materials/TypesMaterial.h
  test/src/auxkernels/OptionalTestAux.C
  test/src/materials/OptionalTestMaterial.C
  test/src/materials/TypesMaterial.C
  test/tests/materials/optional_properties/gold/material_after.e
  test/tests/materials/optional_properties/gold/material_before.e
  test/tests/materials/optional_properties/material.i
  test/tests/materials/optional_properties/tests
  test/tests/postprocessors/side_average_value/side_average_value_test.i
  test/tests/postprocessors/side_average_value/tests
  test/tests/postprocessors/side_integral/tests
  test/tests/postprocessors/side_material.i
Labels: PR: Ready for Review/Merge

#19421 Add FV skewness-correction to Navier-Stokes module
  framework/include/utils/MathFVUtils.h
  framework/src/fvkernels/FVAdvection.C
  framework/src/fvkernels/FVMatAdvection.C
  framework/src/variables/MooseVariableFV.C
  modules/navier_stokes/doc/content/modules/navier_stokes/insfv.md
  modules/navier_stokes/src/fvkernels/INSFVMomentumAdvection.C
  modules/navier_stokes/src/fvkernels/INSFVMomentumPressure.C
  modules/navier_stokes/src/variables/INSFVVelocityVariable.C
  modules/navier_stokes/test/tests/finite_volume/ins/mms/skew-correction/skewed-vortex.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/skew-correction/skewed.geo
  modules/navier_stokes/test/tests/finite_volume/ins/mms/skew-correction/skewed.msh
  modules/navier_stokes/test/tests/finite_volume/ins/mms/skew-correction/test.py
  modules/navier_stokes/test/tests/finite_volume/ins/mms/skew-correction/tests
  test/tests/fvkernels/mms/skewness-correction/adv-diff-react/test.py
  test/tests/fvkernels/mms/skewness-correction/adv-diff-react/tests
Labels: PR: Failed but allowed

#19530 A small followup PR for PR 19310
  modules/reactor/doc/content/source/meshgenerators/SubdomainExtraElementIDGenerator.md
  modules/reactor/test/tests/meshgenerators/subdomain_extra_element_id_generator/gold/subdomain_elem_ids_test_out.e
  modules/reactor/test/tests/meshgenerators/subdomain_extra_element_id_generator/subdomain_elem_ids_test.i
  modules/reactor/test/tests/meshgenerators/subdomain_extra_element_id_generator/tests
Labels: PR: Auto Merge

#19461 Update void distribution for PolycrystalVoronoiVoidIC
  modules/phase_field/src/ics/PolycrystalVoronoiVoidIC.C
  modules/phase_field/test/tests/initial_conditions/gold/PolycrystalVoronoiVoidIC_periodic_out.e
Labels: PR: Failed but allowed

#19546 Fix optional properties for pre-material systems
  framework/include/base/MooseApp.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialProperty.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/src/actions/ResolveOptionalMaterialPropertiesAction.C
  framework/src/base/Moose.C
  framework/src/materials/MaterialPropertyInterface.C
  test/include/userobjects/OptionalTestUserObject.h
  test/src/userobjects/OptionalTestUserObject.C
  test/tests/materials/optional_properties/auxkernel.i
  test/tests/materials/optional_properties/gold/auxkernel_out.e
  test/tests/materials/optional_properties/tests
  test/tests/materials/optional_properties/userobject.i
Labels: PR: Auto Merge

#19556 Add magnitude and function name interfaces. Refs #19555
  framework/include/ics/FunctionIC.h
  framework/include/ics/IntegralPreservingFunctionIC.h
  framework/src/ics/FunctionIC.C
  framework/src/ics/IntegralPreservingFunctionIC.C
Labels: PR: Failed but allowed

#19447 Documentation for UOs and some time schemes
  framework/doc/content/bib/moose.bib
  framework/doc/content/source/actions/AddNodalNormalsAction.md
  framework/doc/content/source/functions/MooseParsedFunction.md
  framework/doc/content/source/timeintegrators/AStableDirk4.md
  framework/doc/content/source/timeintegrators/BDF2.md
  framework/doc/content/source/timeintegrators/CrankNicolson.md
  framework/doc/content/source/timeintegrators/ExplicitEuler.md
  framework/doc/content/source/timeintegrators/ExplicitMidpoint.md
  framework/doc/content/source/timeintegrators/ExplicitTVDRK2.md
  framework/doc/content/source/timeintegrators/Heun.md
  framework/doc/content/source/timeintegrators/ImplicitEuler.md
  framework/doc/content/source/timeintegrators/ImplicitMidpoint.md
  framework/doc/content/source/timeintegrators/LStableDirk2.md
  framework/doc/content/source/timeintegrators/LStableDirk3.md
  framework/doc/content/source/timeintegrators/LStableDirk4.md
  framework/doc/content/source/timeintegrators/Ralston.md
  framework/doc/content/source/timesteppers/IterationAdaptiveDT.md
  framework/doc/content/source/userobject/ElementIntegralVariableUserObject.md
  framework/doc/content/source/userobject/LayeredAverage.md
  framework/doc/content/source/userobject/LayeredIntegral.md
  framework/doc/content/source/userobject/LayeredSideAverage.md
  framework/doc/content/source/userobject/LayeredSideDiffusiveFluxAverage.md
  framework/doc/content/source/userobject/LayeredSideFluxAverage.md
  framework/doc/content/source/userobject/LayeredSideIntegral.md
  framework/doc/content/source/userobject/NodalNormalsCorner.md
  framework/doc/content/source/userobject/NodalNormalsEvaluator.md
  framework/doc/content/source/userobject/NodalNormalsPreprocessor.md
  framework/doc/content/source/userobject/Terminator.md
  framework/doc/content/source/userobject/UserObject.md
  framework/doc/content/source/userobject/VerifyElementUniqueID.md
  framework/doc/content/source/userobject/VerifyNodalUniqueID.md
  framework/include/userobject/Terminator.h
  framework/src/userobject/ElementIntegralUserObject.C
  framework/src/userobject/LayeredAverage.C
  framework/src/userobject/LayeredIntegral.C
  framework/src/userobject/LayeredSideIntegral.C
  framework/src/userobject/NodalNormalsCorner.C
  framework/src/userobject/Terminator.C
  framework/src/userobject/VerifyNodalUniqueID.C
  test/tests/userobjects/Terminator/gold/terminator_pass_out.csv
  test/tests/userobjects/Terminator/terminator_pass.i
  test/tests/userobjects/Terminator/tests
Labels: PR: Failed but allowed

#19562 Fixing minor bugs in hfem diffusion kernel
  framework/src/dgkernels/ArrayDGKernel.C
  framework/src/dgkernels/DGKernel.C
Labels: PR: Failed but allowed

#19559 Consolidate setting METHODS for libmesh in configure_libmesh.sh
  conda/libmesh/build.sh
  conda/libmesh/meta.yaml
  conda/mpich/conda_build_config.yaml
  scripts/configure_libmesh.sh
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed

#19583 Elem::centroid() -> Elem::vertex_average()
  framework/src/meshgenerators/PlaneIDMeshGenerator.C
Labels: PR: Failed but allowed, PR: Auto Merge

#19582 Use .pvtu extension for VTKOutput, even on 1 core
  framework/src/outputs/VTKOutput.C
  test/tests/outputs/vtk/gold/vtk_diff_out_005.pvtu
  test/tests/outputs/vtk/gold/vtk_diff_serial_mesh_out_005.pvtu
  test/tests/outputs/vtk/tests
Labels: PR: Failed but allowed

#19592 Force ReferenceResidual to respect nl_force_its
  framework/src/problems/ReferenceResidualProblem.C
  test/tests/executioners/nl_forced_its/2d_diffusion_test.i
  test/tests/executioners/nl_forced_its/many_nl_forced_its.i
  test/tests/executioners/nl_forced_its/many_nl_forced_its_ref_res.i
  test/tests/executioners/nl_forced_its/nl_forced_its.i
  test/tests/executioners/nl_forced_its/tests
Labels: PR: Failed but allowed

#18721 Faster nodal patch recovery
  framework/include/problems/FEProblemBase.h
  framework/include/utils/MathUtils.h
  framework/src/actions/AddPeriodicBCAction.C
  framework/src/problems/FEProblemBase.C
  framework/src/userobject/ElemSideNeighborLayersTester.C
  framework/src/utils/MathUtils.C
  modules/geochemistry/src/userobjects/NodalVoidVolume.C
  modules/phase_field/src/userobjects/PolycrystalUserObjectBase.C
  modules/porous_flow/src/userobjects/AdvectiveFluxCalculatorBase.C
  modules/porous_flow/src/userobjects/PorousFlowAdvectiveFluxCalculatorBase.C
  modules/tensor_mechanics/doc/content/source/auxkernels/NodalPatchRecoveryAux.md
  modules/tensor_mechanics/doc/content/source/userobjects/NodalPatchRecoveryMaterialProperty.md
  modules/tensor_mechanics/include/auxkernels/NodalPatchRecoveryAux.h
  modules/tensor_mechanics/include/userobjects/NodalPatchRecoveryBase.h
  modules/tensor_mechanics/include/userobjects/NodalPatchRecoveryMaterialProperty.h
  modules/tensor_mechanics/src/auxkernels/NodalPatchRecoveryAux.C
  modules/tensor_mechanics/src/userobjects/NodalPatchRecoveryBase.C
  modules/tensor_mechanics/src/userobjects/NodalPatchRecoveryMaterialProperty.C
  modules/tensor_mechanics/test/tests/nodal_patch_recovery/gold/patch_recovery_out.e
  modules/tensor_mechanics/test/tests/nodal_patch_recovery/input_slip_sys.txt
  modules/tensor_mechanics/test/tests/nodal_patch_recovery/patch_recovery.i
  modules/tensor_mechanics/test/tests/nodal_patch_recovery/tests
  unit/src/MathUtilsTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#16816 Testing Eigen decomposition
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankFourTensorImplementation.h
  framework/include/utils/RankThreeTensor.h
  framework/include/utils/RankThreeTensorImplementation.h
  framework/include/utils/RankTwoTensor.h
  framework/include/utils/RankTwoTensorImplementation.h
  modules/contact/test/tests/simple_contact/two_block_compress/two_equal_blocks_compress_2d.i
  modules/tensor_mechanics/unit/src/RankTwoTensorTest.C
  unit/src/RankTwoEigenRoutinesTest.C
Labels: P: normal, PR: Failed but allowed, PR: Ready for Review/Merge

#19625 Deprecate ambiguous RankTwoTensor constructor
  framework/include/utils/RankTwoTensorImplementation.h
  modules/tensor_mechanics/src/materials/ADCompute1DFiniteStrain.C
  modules/tensor_mechanics/src/materials/ADCompute1DIncrementalStrain.C
  modules/tensor_mechanics/src/materials/ADCompute2DFiniteStrain.C
  modules/tensor_mechanics/src/materials/ADCompute2DIncrementalStrain.C
  modules/tensor_mechanics/src/materials/ADComputeFiniteStrain.C
  modules/tensor_mechanics/src/materials/ADComputeGreenLagrangeStrain.C
  modules/tensor_mechanics/src/materials/ADComputeIncrementalSmallStrain.C
  modules/tensor_mechanics/src/materials/ADComputeSmallStrain.C
  modules/tensor_mechanics/src/materials/Compute1DFiniteStrain.C
  modules/tensor_mechanics/src/materials/Compute1DIncrementalStrain.C
  modules/tensor_mechanics/src/materials/Compute2DFiniteStrain.C
  modules/tensor_mechanics/src/materials/Compute2DIncrementalStrain.C
  modules/tensor_mechanics/src/materials/ComputeCosseratIncrementalSmallStrain.C
  modules/tensor_mechanics/src/materials/ComputeCosseratSmallStrain.C
  modules/tensor_mechanics/src/materials/ComputeFiniteBeamStrain.C
  modules/tensor_mechanics/src/materials/ComputeFiniteStrain.C
  modules/tensor_mechanics/src/materials/ComputeIncrementalSmallStrain.C
  modules/tensor_mechanics/src/materials/ComputeSmallStrain.C
  modules/tensor_mechanics/src/materials/EshelbyTensor.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/CZMComputeDisplacementJumpTotalLagrangian.C
  modules/tensor_mechanics/src/vectorpostprocessors/InteractionIntegral.C
  modules/xfem/src/materials/ComputeCrackTipEnrichmentSmallStrain.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#19593 One based indexing in UMAT
  framework/plugin.mk
  modules/combined/test/tests/umat/gap_heat_transfer_umat.i
  modules/tensor_mechanics/doc/content/source/materials/abaqus/AbaqusUMATStress.md
  modules/tensor_mechanics/examples/umat_build/test.i
  modules/tensor_mechanics/include/materials/abaqus/AbaqusUMATStress.h
  modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C
  modules/tensor_mechanics/test/plugins/elastic_print_c.C
  modules/tensor_mechanics/test/plugins/elastic_print_eigen.C
  modules/tensor_mechanics/test/plugins/elastic_print_multiple_fields.f
  modules/tensor_mechanics/test/tests/umat/elastic_hardening/elastic.i
  modules/tensor_mechanics/test/tests/umat/elastic_hardening/linear_strain_hardening.i
  modules/tensor_mechanics/test/tests/umat/predef/dpredef.i
  modules/tensor_mechanics/test/tests/umat/predef/predef.i
  modules/tensor_mechanics/test/tests/umat/predef/predef_multiple.i
  modules/tensor_mechanics/test/tests/umat/predef/predef_multiple_mat.i
  modules/tensor_mechanics/test/tests/umat/print/print.i
  modules/tensor_mechanics/test/tests/umat/print/print_shear.i
  modules/tensor_mechanics/test/tests/umat/print/tests
  modules/tensor_mechanics/test/tests/umat/print_c/print_c.i
  modules/tensor_mechanics/test/tests/umat/print_c/print_compare_c.i
  modules/tensor_mechanics/test/tests/umat/print_c/tests
  modules/tensor_mechanics/test/tests/umat/temperature/elastic_dtemperature.i
  modules/tensor_mechanics/test/tests/umat/temperature/elastic_temperature.i
  modules/tensor_mechanics/test/tests/umat/time_step/elastic_timestep.i
Labels: PR: Ready for Review/Merge

#19663 Can distinguish between timing for different multiapps
  framework/include/multiapps/MultiApp.h
  framework/src/multiapps/FullSolveMultiApp.C
  framework/src/multiapps/MultiApp.C
  framework/src/multiapps/TransientMultiApp.C
  test/tests/multiapps/slow_sub/master.i
  test/tests/multiapps/slow_sub/sub.i
  test/tests/multiapps/slow_sub/tests
Labels: PR: Auto Merge

#19655 Add solve time section for ExternalProblem.
  framework/src/problems/ExternalProblem.C
Labels: PR: Failed but allowed

#19606 Use ElemSideBuilder to avoid extraneous element side construction
  framework/include/base/Assembly.h
  framework/include/geomsearch/PenetrationThread.h
  framework/src/base/Assembly.C
  framework/src/geomsearch/PenetrationThread.C
  framework/src/utils/PetscDMMoose.C
  framework/src/vectorpostprocessors/WorkBalance.C
  modules/ray_tracing/doc/content/source/utils/SidePtrHelper.md
  modules/ray_tracing/include/raytracing/TraceRay.h
  modules/ray_tracing/include/userobjects/RayTracingStudy.h
  modules/ray_tracing/include/utils/SidePtrHelper.h
  modules/ray_tracing/src/raytracing/ClaimRays.C
  modules/ray_tracing/src/raytracing/TraceRay.C
  modules/ray_tracing/src/userobjects/RayTracingStudy.C
  modules/ray_tracing/src/utils/SidePtrHelper.C
  modules/ray_tracing/test/src/userobjects/LotsOfRaysRayStudy.C
Labels: PR: Failed but allowed, PR: Requires libMesh update

#19462 3D mortar frictional contact
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/include/constraints/MortarConstraintBase.h
  framework/include/interfaces/MortarInterface.h
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/constraints/MortarData.C
  framework/src/interfaces/MortarInterface.C
  modules/contact/doc/content/source/auxkernels/MortarFrictionalPressureVectorAux.md
  modules/contact/include/auxkernels/MortarFrictionalPressureVectorAux.h
  modules/contact/include/constraints/ADMortarLagrangeConstraint.h
  modules/contact/include/constraints/ComputeFrictionalForceLMMechanicalContact.h
  modules/contact/include/constraints/ComputeWeightedGapLMMechanicalContact.h
  modules/contact/include/constraints/NormalMortarMechanicalContact.h
  modules/contact/include/constraints/TangentialMortarMechanicalContact.h
  modules/contact/src/actions/ContactAction.C
  modules/contact/src/auxkernels/MortarFrictionalPressureVectorAux.C
  modules/contact/src/constraints/ADMortarLagrangeConstraint.C
  modules/contact/src/constraints/ComputeFrictionalForceLMMechanicalContact.C
  modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C
  modules/contact/src/constraints/NormalMortarMechanicalContact.C
  modules/contact/src/constraints/TangentialMortarMechanicalContact.C
  modules/contact/test/tests/3d-mortar-contact/frictional-mortar-3d-action.i
  modules/contact/test/tests/3d-mortar-contact/frictional-mortar-3d-interp-geometry.i
  modules/contact/test/tests/3d-mortar-contact/frictional-mortar-3d.i
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d-action_out_frictional-pressure-3d_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d-action_out_frictional-pressure_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d-action_out_tangent_x_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d-action_out_tangent_y_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d-interp-geometry_out.e
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d_out.e
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d_out_frictional-pressure-3d_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d_out_frictional-pressure_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d_out_tangent_x_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d_out_tangent_y_0001.csv
  modules/contact/test/tests/3d-mortar-contact/gold/nodal_geometry_only.e
  modules/contact/test/tests/3d-mortar-contact/tests
Labels: PR: Failed but allowed

#19678 adding coupledArrayValues in Coupleable,
  framework/include/interfaces/Coupleable.h
  framework/src/interfaces/Coupleable.C
Labels: PR: Failed but allowed
