Repository idaholab/moose, pull requests merged in 2021-02, with the labels that each got.

#16844 Speed up ray verification and guard by verify_rays and add error testing
  modules/ray_tracing/include/userobjects/RepeatableRayStudyBase.h
  modules/ray_tracing/src/userobjects/RayTracingStudy.C
  modules/ray_tracing/src/userobjects/RepeatableRayStudyBase.C
  modules/ray_tracing/test/include/userobjects/RayTracingStudyTest.h
  modules/ray_tracing/test/include/userobjects/RepeatableRayStudyBaseTest.h
  modules/ray_tracing/test/src/userobjects/RayTracingStudyTest.C
  modules/ray_tracing/test/src/userobjects/RepeatableRayStudyBaseTest.C
  modules/ray_tracing/test/tests/userobjects/ray_tracing_study/errors/errors.i
  modules/ray_tracing/test/tests/userobjects/ray_tracing_study/errors/tests
  modules/ray_tracing/test/tests/userobjects/repeatable_ray_study_base/errors.i
  modules/ray_tracing/test/tests/userobjects/repeatable_ray_study_base/tests
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#16845 All props in stateful storage should be non-AD
  framework/include/materials/MaterialProperty.h
  framework/include/materials/MaterialPropertyStorage.h
  framework/include/utils/MooseADWrapper.h
  framework/src/materials/MaterialPropertyStorage.C
  framework/src/problems/FEProblemBase.C
Labels: PR: Ready for Review/Merge

#16856 Support Fully Developed Outlet Flow BC in INSFV
  framework/include/fvbcs/FVMatAdvectionOutflowBC.h
  framework/src/fvbcs/FVMatAdvectionOutflowBC.C
  modules/navier_stokes/doc/content/source/fvbcs/INSFVMassAdvectionOutflowBC.md
  modules/navier_stokes/doc/content/source/fvbcs/INSFVMomentumAdvectionOutflowBC.md
  modules/navier_stokes/include/fvbcs/INSFVMassAdvectionOutflowBC.h
  modules/navier_stokes/include/fvbcs/INSFVMomentumAdvectionOutflowBC.h
  modules/navier_stokes/src/fvbcs/INSFVMassAdvectionOutflowBC.C
  modules/navier_stokes/src/fvbcs/INSFVMomentumAdvectionOutflowBC.C
  modules/navier_stokes/src/fvkernels/INSFVMomentumAdvection.C
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-no-slip-extrapolated-outlet-pressure.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-no-slip-outflow-bcs.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-no-slip-extrapolated-outlet-pressure_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-no-slip-outflow-bcs_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Auto Merge

#16889 Some simple Coupleable extensions
  framework/include/interfaces/Coupleable.h
  framework/include/variables/MooseVariableFE.h
  framework/src/interfaces/Coupleable.C
  framework/src/variables/MooseVariableFE.C
Labels: PR: Auto Merge

#16893 Fix failures from #16856
  modules/navier_stokes/src/fvbcs/INSFVMassAdvectionOutflowBC.C
  modules/navier_stokes/src/fvbcs/INSFVMomentumAdvectionOutflowBC.C
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#16899 Fix failure from #16159 merge
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#16903 Added imports to pyhit init file
  python/pyhit/__init__.py
Labels: PR: Auto Merge

#16811 Add --args to MooseDocs build command for overriding config
  python/MooseDocs/base/executioners.py
  python/MooseDocs/commands/build.py
  python/MooseDocs/common/extract_content.py
  python/MooseDocs/common/load_config.py
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/autolink.py
  python/MooseDocs/extensions/core.py
  python/MooseDocs/extensions/floats.py
  python/MooseDocs/extensions/listing.py
  python/MooseDocs/extensions/modal.py
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/extensions/template.py
  python/MooseDocs/test/commands/test_build.py
  python/MooseDocs/test/commands/tests
  python/MooseDocs/test/common/test_load_config.py
  python/MooseDocs/test/content/extensions/example.template.md
  python/MooseDocs/test/content/extensions/listing.md
  python/MooseDocs/test/extensions/test_appsyntax.py
  python/MooseDocs/test/extensions/test_autolink.py
  python/MooseDocs/test/extensions/test_ifelse.py
  python/MooseDocs/test/extensions/test_listing.py
  python/MooseDocs/test/extensions/test_modal.py
  python/MooseDocs/test/extensions/test_sqa.py
  python/MooseDocs/test/extensions/test_template.py
  python/MooseDocs/test/extensions/tests
  python/MooseDocs/test/html.yml
  python/MooseDocs/test/latex.yml
  python/MooseDocs/test/materialize.yml
  python/moosesqa/check_requirements.py
  tutorials/darcy_thermo_mech/doc/config.yml
Labels: PR: Auto Merge

#16906 Forward compatibility with libmesh #2850
  framework/include/restart/DataIO.h
  test/tests/mesh/node_list_from_side_list/node_list_from_side_list.i
Labels: PR: Auto Merge

#16911 Fix failures from #16767 merge
  modules/navier_stokes/test/tests/postprocessors/conservation_INSFV.i
Labels: PR: Auto Merge

#16917 Use RC interpolation over average in INSFV conservation tests
  framework/include/variables/MooseVariableFV.h
  framework/src/variables/MooseVariableFV.C
  modules/navier_stokes/src/postprocessors/InternalVolumetricFlowRate.C
  modules/navier_stokes/test/tests/postprocessors/conservation_INSFV.i
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_xy.csv
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_xy_noslip.csv
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_xy_upwind.csv
  modules/navier_stokes/test/tests/postprocessors/tests
  test/tests/postprocessors/side_flux_average/tests
  test/tests/userobjects/layered_side_integral/tests
Labels: PR: Auto Merge

#16928 Add TRANSLATE_CENTER_ORIGIN and TRANSLATE_MIN_ORIGIN to TransformGenerator
  framework/doc/content/source/meshgenerators/TransformGenerator.md
  framework/include/meshgenerators/TransformGenerator.h
  framework/src/meshgenerators/TransformGenerator.C
  test/tests/meshgenerators/transform_generator/gold/rotate_and_scale_out.e
  test/tests/meshgenerators/transform_generator/gold/translate_center_origin_in.e
  test/tests/meshgenerators/transform_generator/gold/translate_in.e
  test/tests/meshgenerators/transform_generator/gold/translate_min_origin_in.e
  test/tests/meshgenerators/transform_generator/tests
  test/tests/meshgenerators/transform_generator/translate.i
  test/tests/meshgenerators/transform_generator/translate_center_origin.i
  test/tests/meshgenerators/transform_generator/translate_min_origin.i
Labels: PR: Ready for Review/Merge

#16733 Squarish partition for distributed generated mesh
  framework/include/meshgenerators/DistributedRectilinearMeshGenerator.h
  framework/include/transfers/MultiAppMeshFunctionTransfer.h
  framework/src/meshgenerators/DistributedRectilinearMeshGenerator.C
  framework/src/transfers/MultiAppMeshFunctionTransfer.C
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out.e
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out_3.e
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out_3_sub_app0.e
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out_4.e
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out_4_sub_app0.e
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out_6.e
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out_6_sub_app0.e
  modules/external_petsc_solver/test/tests/partition/gold/moose_as_master_out_sub_app0.e
  modules/external_petsc_solver/test/tests/partition/moose_as_master.i
  modules/external_petsc_solver/test/tests/partition/petsc_transient_as_sub.i
  modules/external_petsc_solver/test/tests/partition/tests
  modules/phase_field/test/tests/grain_growth/voronoi_adaptivity_ghost.i
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/tests
  test/tests/meshgenerators/distributed_rectilinear/ghosting_elements/num_layers.i
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out.e
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out_1D_3.e
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out_1D_4.e
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out_3D_3.e
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out_3D_4.e
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out_3D_8.e
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out_4.e
  test/tests/meshgenerators/distributed_rectilinear/partition/gold/squarish_partition_out_6.e
  test/tests/meshgenerators/distributed_rectilinear/partition/squarish_partition.i
  test/tests/meshgenerators/distributed_rectilinear/partition/tests
Labels: PR: Ready for Review/Merge

#16864 Add object information to MooseObject::moose[Error/Warning]()
  framework/include/base/MooseObject.h
  framework/src/base/MooseObject.C
Labels: PR: Ready for Review/Merge

#16943 Silence codecov comments until we get it all ironed out
  .codecov.yml
Labels: PR: Ready for Review/Merge

#16898 Feb. 2021 News
  modules/doc/content/newsletter/2021_02.md
  modules/doc/content/newsletter/2021_03.md
  modules/doc/content/newsletter/index.md
Labels: PR: Auto Merge

#16956 AD props alone don't mean we have AD residual objects
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/include/problems/FEProblemBase.h
Labels: PR: Auto Merge

#16929 Allow applications to automatically disable syntax of inherited documentation
  framework/doc/content/templates/sqa/app_index.md.template
  modules/contact/doc/config.yml
  modules/contact/doc/content/modules/contact/sqa/index.md
  modules/doc/sqa_reports.yml
  modules/fluid_properties/doc/config.yml
  modules/fluid_properties/doc/content/modules/fluid_properties/sqa/index.md
  modules/heat_conduction/doc/config.yml
  modules/heat_conduction/doc/content/modules/heat_conduction/sqa/index.md
  modules/misc/doc/config.yml
  modules/misc/doc/content/modules/misc/sqa/index.md
  modules/navier_stokes/doc/content/modules/navier_stokes/sqa/index.md
  modules/phase_field/doc/config.yml
  modules/phase_field/doc/content/modules/phase_field/sqa/index.md
  modules/stochastic_tools/doc/config.yml
  modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/index.md
  modules/tensor_mechanics/doc/config.yml
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/sqa/index.md
  modules/xfem/doc/config.yml
  modules/xfem/doc/content/modules/xfem/sqa/index.md
  python/MooseDocs/commands/build.py
  python/MooseDocs/commands/init.py
  python/MooseDocs/commands/sqa_app.yml.template
  python/MooseDocs/commands/sqa_reports.yml.template
  python/MooseDocs/common/get_content.py
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/core.py
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/main.py
  python/MooseDocs/test/commands/test_init.py
  python/MooseDocs/test/commands/tests
  python/MooseDocs/test/content/extensions/external.md
  python/MooseDocs/test/extensions/test_appsyntax.py
  python/MooseDocs/test/extensions/test_ifelse.py
  python/MooseDocs/test/html.yml
  python/MooseDocs/test/latex.yml
  python/MooseDocs/test/materialize.yml
  python/MooseDocs/tree/pages.py
  python/moosesqa/check_documents.py
  python/moosesqa/check_syntax.py
  python/moosesqa/get_documents.py
  python/mooseutils/__init__.py
  python/mooseutils/gitutils.py
  python/mooseutils/tests/test_gitutils.py
  python/mooseutils/tests/test_yaml_load.py
  python/mooseutils/yaml_load.py
  test/doc/config.yml
Labels: PR: Auto Merge

#16896 Make aux kernel work properly for high-order boundary restriction
  framework/doc/content/syntax/AuxKernels/index.md
  framework/include/auxkernels/AuxKernel.h
  framework/src/auxkernels/AuxKernel.C
  test/tests/auxkernels/element_aux_boundary/gold/high_order_boundary_aux_out.e
  test/tests/auxkernels/element_aux_boundary/high_order_boundary_aux.i
  test/tests/auxkernels/element_aux_boundary/tests
Labels: PR: Auto Merge

#16969 Fix sign error in heat conduction documentation
  modules/heat_conduction/doc/content/modules/heat_conduction/index.md
Labels: PR: Auto Merge

#16955 Use solve_type Newton in PorousFlow nc01.i test
  modules/porous_flow/test/tests/buckley_leverett/bl01.i
  modules/porous_flow/test/tests/buckley_leverett/tests
  modules/porous_flow/test/tests/newton_cooling/nc01.i
  modules/porous_flow/test/tests/newton_cooling/tests
Labels: PR: Failed but allowed

#16936 More FV postprocessors changes
  framework/src/postprocessors/InterfaceIntegralVariableValuePostprocessor.C
  modules/navier_stokes/src/fvkernels/INSFVMomentumAdvection.C
  modules/navier_stokes/test/tests/finite_volume/ins/block_restriction/2d-rc.i
  modules/navier_stokes/test/tests/finite_volume/ins/block_restriction/gold/2d-rc_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/block_restriction/tests
  modules/navier_stokes/test/tests/postprocessors/conservation_INSFV.i
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_rz.csv
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_xy.csv
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_xy_noslip.csv
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_xy_rc.csv
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_quad_xy_upwind.csv
  modules/navier_stokes/test/tests/postprocessors/gold/diverging_INSFV_tri_xy.csv
  modules/navier_stokes/test/tests/postprocessors/tests
  test/tests/postprocessors/interface_value/gold/InterfaceAverageVariableValuePostprocessor_fe.e
  test/tests/postprocessors/interface_value/gold/InterfaceAverageVariableValuePostprocessor_fv.e
  test/tests/postprocessors/interface_value/gold/InterfaceIntegralVariableValuePostprocessor_fe.e
  test/tests/postprocessors/interface_value/gold/InterfaceIntegralVariableValuePostprocessor_fv.e
  test/tests/postprocessors/interface_value/interface_fe_variable_value_postprocessor.i
  test/tests/postprocessors/interface_value/interface_fv_variable_value_postprocessor.i
  test/tests/postprocessors/interface_value/tests
Labels: PR: Ready for Review/Merge

#16967 Mesh generator tests should not be run in recover
  modules/heat_conduction/test/tests/generate_radiation_patch/tests
Labels: PR: Failed but allowed

#17002 Various ray_tracing enhancements
  modules/ray_tracing/include/userobjects/RepeatableRayStudy.h
  modules/ray_tracing/src/base/RayTracingObject.C
  modules/ray_tracing/src/userobjects/RayTracingStudy.C
  modules/ray_tracing/src/userobjects/RepeatableRayStudy.C
  modules/ray_tracing/test/tests/actions/add_raybc_action/add_raybc_action.i
  modules/ray_tracing/test/tests/actions/add_raykernel_action/add_raykernel_action.i
  modules/ray_tracing/test/tests/coord_type/rspherical_line_integral.i
  modules/ray_tracing/test/tests/coord_type/rz_line_integral.i
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.2
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.3
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/no_segments_nemesis_rays.e.2.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/no_segments_nemesis_rays.e.2.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/no_segments_rays.e
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays.e
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays.e.2.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays.e.2.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays_nodal.e.2.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays_nodal.e.2.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/ray_mesh_output_data.i
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/tests
  modules/ray_tracing/test/tests/postprocessors/ray_data_value/gold/ray_data_value_out.csv
  modules/ray_tracing/test/tests/postprocessors/ray_data_value/ray_data_value.i
  modules/ray_tracing/test/tests/postprocessors/ray_data_value/ray_data_value_errors.i
  modules/ray_tracing/test/tests/postprocessors/ray_integral_value/ray_integral_value_errors.i
  modules/ray_tracing/test/tests/raybcs/dependencies/ray_bc_dependencies.i
  modules/ray_tracing/test/tests/raykernels/coupled_line_source_ray_kernel/coupled_line_source_ray_kernel.i
  modules/ray_tracing/test/tests/raykernels/dependencies/ray_kernel_dependencies.i
  modules/ray_tracing/test/tests/raykernels/line_source_ray_kernel/fv_simple_diffusion_line_source.i
  modules/ray_tracing/test/tests/raykernels/line_source_ray_kernel/line_source_ray_kernel.i
  modules/ray_tracing/test/tests/raykernels/line_source_ray_kernel/simple_diffusion_line_source.i
  modules/ray_tracing/test/tests/raykernels/material_integral_ray_kernel/material_integral_ray_kernel.i
  modules/ray_tracing/test/tests/raykernels/variable_integral_ray_kernel/fv_simple_diffusion_line_integral.i
  modules/ray_tracing/test/tests/raykernels/variable_integral_ray_kernel/simple_diffusion_line_integral.i
  modules/ray_tracing/test/tests/raykernels/variable_integral_ray_kernel/variable_integral_ray_kernel.i
  modules/ray_tracing/test/tests/traceray/internal_sidesets/internal_sidesets_1d.i
  modules/ray_tracing/test/tests/traceray/internal_sidesets/internal_sidesets_2d.i
  modules/ray_tracing/test/tests/traceray/internal_sidesets/internal_sidesets_3d.i
  modules/ray_tracing/test/tests/traceray/raybc_check/raybc_check.i
  modules/ray_tracing/test/tests/userobjects/repeatable_ray_study/max_distance.i
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#16952 MUMPS not needed to run PorousFlow examples
  modules/porous_flow/examples/thm_example/2D.i
  modules/porous_flow/examples/thm_example/tests
  modules/porous_flow/examples/tutorial/tests
Labels: PR: Auto Merge

#16950 Reinstating two PorousFlow tests
  modules/porous_flow/test/tests/gravity/fully_saturated_grav01c.i
  modules/porous_flow/test/tests/gravity/tests
  modules/porous_flow/test/tests/jacobian/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#17010 Add call-back functions for DGKernel
  framework/include/dgkernels/DGKernel.h
  framework/src/dgkernels/DGKernel.C
  framework/src/dgkernels/DGKernelBase.C
Labels: PR: Auto Merge

#17011 Support std::map in InputParameters
  framework/include/actions/GlobalParamsAction.h
  framework/include/parser/Parser.h
  framework/src/parser/Parser.C
  test/include/kernels/MapMultiplyCoupledVars.h
  test/src/kernels/MapMultiplyCoupledVars.C
  test/tests/parser/map_param/gold/test_out.e
  test/tests/parser/map_param/test.i
  test/tests/parser/map_param/tests
Labels: PR: Ready for Review/Merge

#17043 Changes in support of SQA for applications
  modules/doc/config.yml
  modules/rdg/doc/config.yml
  modules/rdg/doc/content/sqa/index.md
  modules/rdg/doc/content/sqa/rdg_far.md
  modules/rdg/doc/content/sqa/rdg_rtm.md
  modules/rdg/doc/content/sqa/rdg_sdd.md
  modules/rdg/doc/content/sqa/rdg_srs.md
  modules/rdg/doc/content/sqa/rdg_stp.md
  modules/rdg/doc/content/sqa/rdg_vvr.md
  modules/rdg/doc/sqa_rdg.yml
  modules/rdg/doc/sqa_reports.yml
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/test/extensions/test_sqa.py
Labels: PR: Auto Merge

#16892 Add the ability to output mesh info after mesh generator execution
  framework/doc/content/source/meshgenerators/MeshGenerator.md
  framework/include/mesh/MooseMesh.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/src/actions/MeshOnlyAction.C
  framework/src/base/MooseApp.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/MeshGenerator.C
  framework/src/meshgenerators/PatternedMeshGenerator.C
  test/tests/meshgenerators/show_info/show_info.i
  test/tests/meshgenerators/show_info/tests
Labels: PR: Ready for Review/Merge

#17066 always use growth factor to increase timestep if it is provided
  framework/doc/content/source/timesteppers/FunctionDT.md
  framework/include/timesteppers/FunctionDT.h
  framework/src/timesteppers/FunctionDT.C
Labels: PR: Auto Merge

#16875 Add volumetric friction and convection terms to NSFV
  modules/navier_stokes/doc/content/source/fvkernels/NSFVEnergyAmbientConvection.md
  modules/navier_stokes/doc/content/source/fvkernels/NSFVMomentumFriction.md
  modules/navier_stokes/include/fvkernels/NSFVEnergyAmbientConvection.h
  modules/navier_stokes/include/fvkernels/NSFVMomentumFriction.h
  modules/navier_stokes/src/fvkernels/NSFVEnergyAmbientConvection.C
  modules/navier_stokes/src/fvkernels/NSFVMomentumFriction.C
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-ambient-convection.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-friction.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-ambient-convection_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-friction-quad.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-friction-quad_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-friction_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Ready for Review/Merge

#17075 Fix "Fixed a bug in Eigenvalue executioner when free_power_iterations=0 #17029"
  test/tests/problems/eigen_problem/initial_condition/gold/ne_ic_no_free_out_eigenvalues_0001.csv
  test/tests/problems/eigen_problem/initial_condition/gold/ne_ic_out.e
  test/tests/problems/eigen_problem/initial_condition/ne_ic_no_free.i
  test/tests/problems/eigen_problem/initial_condition/tests
Labels: PR: Auto Merge

#17086 Add more ray_tracing coverage
  modules/ray_tracing/include/userobjects/RayTracingStudy.h
  modules/ray_tracing/include/utils/ParallelStudy.h
  modules/ray_tracing/src/userobjects/ConeRayStudy.C
  modules/ray_tracing/src/userobjects/RayTracingStudy.C
  modules/ray_tracing/test/include/userobjects/RayTracingStudyTest.h
  modules/ray_tracing/test/src/userobjects/RayTracingStudyTest.C
  modules/ray_tracing/test/tests/traceray/internal_sidesets/tests
  modules/ray_tracing/test/tests/userobjects/ray_tracing_study/errors/errors.i
  modules/ray_tracing/test/tests/userobjects/ray_tracing_study/errors/tests
  modules/ray_tracing/unit/src/TraceRayToolsTest.C
Labels: PR: Ready for Review/Merge

#17096 Add SQA docs to ray tracing
  modules/doc/config.yml
  modules/heat_conduction/doc/config.yml
  modules/heat_conduction/doc/sqa_heat_conduction.yml
  modules/ray_tracing/doc/content/sqa/index.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_far.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_rtm.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_sdd.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_srs.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_stp.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_vvr.md
  modules/ray_tracing/doc/sqa_ray_tracing.yml
  modules/ray_tracing/doc/sqa_reports.yml
Labels: PR: Auto Merge

#17119 Fix incorrect coefficients in CO2FluidProperties
  modules/fluid_properties/include/userobjects/CO2FluidProperties.h
  modules/porous_flow/examples/co2_intercomparison/1Dradial/gold/properties_brine_co2_vpp_0001.csv
  modules/porous_flow/examples/co2_intercomparison/1Dradial/gold/properties_water_co2_vpp_0001.csv
  modules/porous_flow/test/tests/fluidstate/gold/brineco2.csv
  modules/porous_flow/test/tests/fluidstate/gold/brineco2_2.csv
  modules/porous_flow/test/tests/fluidstate/gold/theis_brineco2_nonisothermal_out.csv
  modules/porous_flow/unit/src/PorousFlowBrineCO2Test.C
  modules/porous_flow/unit/src/PorousFlowWaterNCGTest.C
Labels: PR: Auto Merge

#17123 Geochemistry: link to code coverage added to doco
  modules/geochemistry/doc/content/modules/geochemistry/tests_and_examples/index.md
Labels: PR: Auto Merge

#17126 Fix "serial" test spec that isn't serial introduced in #16838
  test/tests/utils/shuffle/tests
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#17129 Avoid ill-posed point value sample in FV test.
  test/tests/vectorpostprocessors/point_value_sampler/gold/point_value_sampler_fv_out_point_sample_0001.csv
  test/tests/vectorpostprocessors/point_value_sampler/point_value_sampler_fv.i
Labels: PR: Auto Merge

#17133 Output only when action is in action
  framework/src/actions/MaterialOutputAction.C
Labels: PR: Auto Merge

#17148 rdg: fix rdgP0 test
  modules/rdg/test/tests/advection_1d/gold/rdgP0_out_tracer_0011.csv
  modules/rdg/test/tests/advection_1d/rdgP0.i
Labels: PR: Auto Merge
