Repository idaholab/moose, pull requests merged in 2021-08, with the labels that each got.

#18335 Allow timestepper to control step tolerance. Refs #18334
  framework/include/executioners/Transient.h
Labels: PR: Failed but allowed

#18503 Minor documentation improvements
  framework/doc/content/source/meshgenerators/SpiralAnnularMeshGenerator.md
  framework/doc/content/source/variables/AuxVariable.md
  framework/doc/content/source/variables/MooseVariableBase.md
  modules/doc/content/ncrc/gen_ondemand.md
Labels: PR: Failed but allowed

#18473 Update links to slides
  modules/doc/content/getting_started.menu.md
  modules/doc/content/getting_started/examples_and_tutorials/index.md
  modules/doc/content/getting_started/examples_and_tutorials/tutorial02_multiapps/index.md
  modules/doc/content/getting_started/examples_and_tutorials/tutorial03_verification/index.md
  modules/doc/content/getting_started/examples_and_tutorials/tutorial03_verification/step03_analytical_solution.md
  modules/doc/content/getting_started/examples_and_tutorials/tutorial03_verification/step04_mms.md
  modules/doc/content/python/mms.md
  tutorials/tutorial03_verification/app/test/tests/1d_analytical.i
  tutorials/tutorial03_verification/app/test/tests/2d_main.i
  tutorials/tutorial03_verification/app/test/tests/2d_mms_spatial.i
  tutorials/tutorial03_verification/app/test/tests/2d_mms_temporal.i
  tutorials/tutorial03_verification/app/test/tests/step03_analytical/1d_analytical.i
  tutorials/tutorial03_verification/app/test/tests/step03_analytical/gold/1d_analytical_out.e
  tutorials/tutorial03_verification/app/test/tests/step03_analytical/step03_results.py
  tutorials/tutorial03_verification/app/test/tests/step03_analytical/step03_study.py
  tutorials/tutorial03_verification/app/test/tests/step03_analytical/tests
  tutorials/tutorial03_verification/app/test/tests/step03_results.py
  tutorials/tutorial03_verification/app/test/tests/step03_study.py
  tutorials/tutorial03_verification/app/test/tests/step04_function.py
  tutorials/tutorial03_verification/app/test/tests/step04_mms/2d_main.i
  tutorials/tutorial03_verification/app/test/tests/step04_mms/2d_mms_spatial.i
  tutorials/tutorial03_verification/app/test/tests/step04_mms/2d_mms_temporal.i
  tutorials/tutorial03_verification/app/test/tests/step04_mms/gold/2d_main_out.e
  tutorials/tutorial03_verification/app/test/tests/step04_mms/gold/2d_mms_spatial_out.e
  tutorials/tutorial03_verification/app/test/tests/step04_mms/gold/2d_mms_temporal_out.csv
  tutorials/tutorial03_verification/app/test/tests/step04_mms/gold/2d_mms_temporal_out.e
  tutorials/tutorial03_verification/app/test/tests/step04_mms/step04_function.py
  tutorials/tutorial03_verification/app/test/tests/step04_mms/step04_results.py
  tutorials/tutorial03_verification/app/test/tests/step04_mms/step04_study.py
  tutorials/tutorial03_verification/app/test/tests/step04_mms/tests
  tutorials/tutorial03_verification/app/test/tests/step04_results.py
  tutorials/tutorial03_verification/app/test/tests/step04_study.py
  tutorials/tutorial03_verification/doc/content/index.md
  tutorials/tutorial03_verification/doc/content/tutorial03_analytical.md
  tutorials/tutorial03_verification/doc/content/tutorial03_convergence.md
  tutorials/tutorial03_verification/doc/content/tutorial03_heat.md
  tutorials/tutorial03_verification/doc/content/tutorial03_mms.md
  tutorials/tutorial03_verification/step03_analytical
  tutorials/tutorial03_verification/step04_mms
Labels: PR: Failed but allowed

#18431 Add note to coupled force kernels that they do not overlap with reaction kernels
  framework/doc/content/source/kernels/CoefReaction.md
  framework/doc/content/source/kernels/CoupledForce.md
  framework/doc/content/source/kernels/Reaction.md
  framework/src/kernels/ADCoupledForce.C
  framework/src/kernels/CoupledForce.C
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed

#18517 Fix current Fbar
  modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C
Labels: PR: Failed but allowed

#18522 Fix phase field unit test
  modules/phase_field/unit/include/EBSDMeshErrorTest.h
  modules/phase_field/unit/src/EBSDMeshErrorTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#18462 Add utility function to create vector of pairs from two input parameters
  framework/include/base/MooseObject.h
Labels: PR: Failed but allowed

#18470 Improve handling of dependencies in HistogramVectorPostprocessor
  framework/include/vectorpostprocessors/HistogramVectorPostprocessor.h
  framework/src/vectorpostprocessors/HistogramVectorPostprocessor.C
  test/include/vectorpostprocessors/EmptyVectorPostprocessor.h
  test/src/vectorpostprocessors/EmptyVectorPostprocessor.C
  test/tests/vectorpostprocessors/histogram_vector_postprocessor/tests
Labels: PR: Failed but allowed

#18487 Allow prescribing radial positions in AnnularMeshGenerator
  framework/doc/content/source/meshgenerators/AnnularMeshGenerator.md
  framework/include/meshgenerators/AnnularMeshGenerator.h
  framework/src/meshgenerators/AnnularMeshGenerator.C
  test/tests/mesh/mesh_generation/annular_mesh_generator_radial_positions.i
  test/tests/mesh/mesh_generation/tests
  test/tests/meshgenerators/annular_mesh_generator/annular_mesh_generator_radial_positions.i
  test/tests/meshgenerators/annular_mesh_generator/gold/annular_mesh_generator_radial_positions_in.e
  test/tests/meshgenerators/annular_mesh_generator/tests
Labels: PR: Failed but allowed

#18505 Move nearest node number capability from geochemistry module to MOOSE…
  framework/doc/content/source/postprocessors/NearestNodeNumber.md
  framework/doc/content/source/userobject/NearestNodeNumberUO.md
  framework/include/postprocessors/NearestNodeNumber.h
  framework/include/userobject/NearestNodeNumberUO.h
  framework/src/postprocessors/NearestNodeNumber.C
  framework/src/userobject/NearestNodeNumberUO.C
  modules/geochemistry/test/tests/postprocessors/tests
  test/tests/postprocessors/nearest_node_number/gold/nearest_node_number_1_out.csv
  test/tests/postprocessors/nearest_node_number/gold/nearest_node_number_2_out.csv
  test/tests/postprocessors/nearest_node_number/gold/nearest_node_number_3_out.csv
  test/tests/postprocessors/nearest_node_number/nearest_node_number_1.i
  test/tests/postprocessors/nearest_node_number/nearest_node_number_2.i
  test/tests/postprocessors/nearest_node_number/nearest_node_number_3.i
  test/tests/postprocessors/nearest_node_number/tests
Labels: PR: Failed but allowed

#18496 Output more information about local numbers on console
  framework/include/interfaces/ElementIDInterface.h
  framework/include/multiapps/FullSolveMultiApp.h
  framework/src/executioners/Eigenvalue.C
  framework/src/executioners/Steady.C
  framework/src/interfaces/ElementIDInterface.C
  framework/src/outputs/ConsoleUtils.C
Labels: PR: Failed but allowed

#18539 Correct typo in cutback_factor_at_failure docstring.
  framework/src/timesteppers/TimeStepper.C
Labels: PR: Failed but allowed

#18273 Wall functions bc
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/modules/navier_stokes/rans_theory.md
  modules/navier_stokes/doc/content/source/auxkernels/WallFunctionWallShearStressAux.md
  modules/navier_stokes/doc/content/source/auxkernels/WallFunctionYPlusAux.md
  modules/navier_stokes/doc/content/source/fvbcs/INSFVWallFunctionBC.md
  modules/navier_stokes/include/auxkernels/WallFunctionWallShearStressAux.h
  modules/navier_stokes/include/auxkernels/WallFunctionYPlusAux.h
  modules/navier_stokes/include/base/INSFVMethods.h
  modules/navier_stokes/include/fvbcs/INSFVWallFunctionBC.h
  modules/navier_stokes/src/auxkernels/WallDistanceMixingLengthAux.C
  modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
  modules/navier_stokes/src/auxkernels/WallFunctionYPlusAux.C
  modules/navier_stokes/src/base/INSFVMethods.C
  modules/navier_stokes/src/fvbcs/INSFVWallFunctionBC.C
  modules/navier_stokes/test/tests/finite_volume/fvbcs/wall_function/Re_t395.i
  modules/navier_stokes/test/tests/finite_volume/fvbcs/wall_function/gold/Re_t395_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/wall_function/tests
Labels: PR: Failed but allowed

#18434 Add a FV version of heat flux BC in the Navier Stokes module
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/source/fvbcs/NSFVHeatFluxBC.md
  modules/navier_stokes/include/base/NSEnums.h
  modules/navier_stokes/include/fvbcs/NSFVHeatFluxBC.h
  modules/navier_stokes/src/base/NSEnums.C
  modules/navier_stokes/src/fvbcs/NSFVHeatFluxBC.C
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/gold/global_k_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/gold/global_kappa_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/gold/global_porosity_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/gold/local_k_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/gold/local_kappa_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/gold/local_porosity_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/gold/wall_heat_transfer_out.e
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/tests
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/wall_heat_transfer.i
Labels: PR: Ready for Review/Merge

#18578 Refactored ParallelPipe() to prevent race conditions.
  python/MooseDocs/base/executioners.py
Labels: PR: Auto Merge

#18597 Add post-aux ordering of UOs, allow ordering of UOs not just generalUOs
  framework/doc/content/source/meshgenerators/BoundaryDeletionGenerator.md
  framework/doc/content/syntax/Mesh/index.md
  framework/include/loops/ComputeUserObjectsThread.h
  framework/src/userobject/GeneralUserObject.C
  framework/src/userobject/UserObject.C
  test/tests/userobjects/force_aux_ordering/force_postaux.i
  test/tests/userobjects/force_aux_ordering/force_preaux.i
  test/tests/userobjects/force_aux_ordering/gold/force_postaux_out.csv
  test/tests/userobjects/force_aux_ordering/gold/force_preaux_out.csv
  test/tests/userobjects/force_aux_ordering/tests
  test/tests/userobjects/force_preaux/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#18589 Update Conda instructions
  conda/README.md
  modules/doc/content/getting_started/installation/install_miniconda.md
  python/peacock/CheckRequirements.py
Labels: PR: Failed but allowed

#18543 Add piston example for tensor_mechanics module
  modules/tensor_mechanics/examples/piston/piston_coarse.e
  modules/tensor_mechanics/examples/piston/piston_params.i
  modules/tensor_mechanics/examples/piston/tests
Labels: PR: Failed but allowed

#18630 Fix conda channel instruction mistake
  modules/doc/content/getting_started/installation/install_miniconda.md
Labels: PR: Failed but allowed

#18618 Get submodule hashes with git ls-files
  docker_ci/Jenkinsfile
  docker_ci/apt_installs.sh
  docker_ci/yum_installs.sh
Labels: PR: Failed but allowed

#18617 Fix getPairs input parameters helper and add tests
  framework/include/actions/Action.h
  framework/include/base/MooseObject.h
  framework/include/utils/Conversion.h
  framework/include/utils/InputParameters.h
  framework/include/utils/MooseUtils.h
  framework/src/base/MooseObject.C
  framework/src/utils/InputParameters.C
  unit/src/InputParametersTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#18576 Optionally allow uniform refinements when using a pre-split mesh
  framework/include/mesh/MooseMesh.h
  framework/src/actions/SetupMeshCompleteAction.C
  framework/src/mesh/MooseMesh.C
  test/tests/mesh/split_uniform_refine/3d_diffusion.i
  test/tests/mesh/split_uniform_refine/gold/3d_diffusion_out.e
  test/tests/mesh/split_uniform_refine/square.cpr/3/header.cpr
  test/tests/mesh/split_uniform_refine/square.cpr/3/split-3-0.cpr
  test/tests/mesh/split_uniform_refine/square.cpr/3/split-3-1.cpr
  test/tests/mesh/split_uniform_refine/square.cpr/3/split-3-2.cpr
  test/tests/mesh/split_uniform_refine/square.cpr/meta_data_mesh.rd
  test/tests/mesh/split_uniform_refine/tests
Labels: PR: Failed but allowed

#18647 Fixed some bugs in ExplicitSSPRungeKutta
  framework/src/timeintegrators/ExplicitSSPRungeKutta.C
  framework/src/timeintegrators/ExplicitTimeIntegrator.C
  modules/doc/content/newsletter/2021_08.md
  test/tests/time_integrators/explicit_ssp_runge_kutta/tests
Labels: PR: Failed but allowed

#18573 Optionally avoid repartitioning the mesh and deleting remote elements after uniform refinements
  framework/include/mesh/MooseMesh.h
  framework/src/actions/SetupMeshAction.C
  framework/src/base/Adaptivity.C
  framework/src/mesh/MooseMesh.C
  test/tests/mesh/uniform_refine/3d_diffusion.i
  test/tests/mesh/uniform_refine/gold/3d_diffusion_out.e.3.0
  test/tests/mesh/uniform_refine/gold/3d_diffusion_out.e.3.1
  test/tests/mesh/uniform_refine/gold/3d_diffusion_out.e.3.2
  test/tests/mesh/uniform_refine/tests
Labels: PR: Failed but allowed

#18660 Add missing copyrights to scripts
  conda/get_filename.py
  scripts/authors.py
  scripts/delete_trailing_whitespace.sh
  scripts/git_news.py
  scripts/install_format_hook.sh
  scripts/petsc_msys2_config.py
  scripts/petsc_msys2_fixup.py
  scripts/stork.sh
  scripts/update_and_rebuild_hit.sh
  scripts/update_and_rebuild_libmesh.sh
  scripts/update_and_rebuild_petsc.sh
  scripts/update_and_rebuild_petsc_alt.sh
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#18293 Pre aux UO grouping update
  framework/include/base/Attributes.h
  framework/include/loops/ComputeUserObjectsThread.h
  framework/include/utils/MooseHashing.h
  framework/src/base/Attributes.C
  framework/src/problems/FEProblemBase.C
  test/include/userobjects/RandomElementalUserObject.h
  test/tests/userobjects/pre_aux_based_on_exec_flag/gold/pre_post_aux_test_out.csv
  test/tests/userobjects/pre_aux_based_on_exec_flag/pre_post_aux_test.i
  test/tests/userobjects/pre_aux_based_on_exec_flag/tests
Labels: PR: Failed but allowed

#18612 Implement bilinear mixed modes traction separation law for cohesive zone model
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/source/materials/cohesive_zone_model/BiLinearMixedModeTraction.md
  modules/tensor_mechanics/include/materials/cohesive_zone_model/BiLinearMixedModeTraction.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/SalehaniIrani3DCTraction.h
  modules/tensor_mechanics/src/materials/cohesive_zone_model/BiLinearMixedModeTraction.C
  modules/tensor_mechanics/test/tests/cohesive_zone_model/bilinear_mixed.i
  modules/tensor_mechanics/test/tests/cohesive_zone_model/bilinear_mixed_scale_strength.i
  modules/tensor_mechanics/test/tests/cohesive_zone_model/gold/bilinear_mixed_normal_out.e
  modules/tensor_mechanics/test/tests/cohesive_zone_model/gold/bilinear_mixed_scale_strength_out.e
  modules/tensor_mechanics/test/tests/cohesive_zone_model/gold/bilinear_mixed_shear_out.e
  modules/tensor_mechanics/test/tests/cohesive_zone_model/tests
Labels: PR: Failed but allowed

#18672 Fix centroid output in FeatureVolumeVectorPostprocessor
  modules/phase_field/include/vectorpostprocessors/FeatureVolumeVectorPostprocessor.h
  modules/phase_field/src/vectorpostprocessors/FeatureVolumeVectorPostprocessor.C
  modules/phase_field/test/tests/feature_volume_vpp_test/centroid.i
  modules/phase_field/test/tests/feature_volume_vpp_test/gold/centroid_out_grain_volumes_0004.csv
  modules/phase_field/test/tests/feature_volume_vpp_test/tests
Labels: PR: Failed but allowed

#18634 Various Dockerfile improvements
  CODEOWNERS
  docker_ci/Dockerfile
  docker_ci/Jenkinsfile
  docker_ci/apt_installs.sh
  docker_ci/build_moose.sh
  docker_ci/install_packages.sh
  docker_ci/yum_installs.sh
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#18667 Treat invalid_id of element integers differently when converting it to a real number
  framework/doc/content/source/auxkernels/ElemExtraIDAux.md
  framework/src/auxkernels/ElemExtraIDAux.C
  test/tests/auxkernels/elem_extra_id_aux/elem_extra_integer_aux.i
  test/tests/auxkernels/elem_extra_id_aux/gold/elem_extra_integer_aux_out.e
  test/tests/auxkernels/elem_extra_id_aux/tests
  test/tests/meshgenerators/subdomain_bounding_box_generator/bounding_box_integers.i
  test/tests/meshgenerators/subdomain_bounding_box_generator/gold/bounding_box_integers_out.e
  test/tests/meshgenerators/subdomain_bounding_box_generator/tests
Labels: PR: Failed but allowed

#18693 Update hpc_remote.md
  modules/doc/content/help/inl/hpc_remote.md
Labels: PR: Failed but allowed

#18734 Changes to correct build of SQA pages
  modules/navier_stokes/test/tests/finite_volume/fvbcs/FVHeatFluxBC/tests
  python/MooseDocs/extensions/civet.py
Labels: PR: Auto Merge

#18731 Check a boundary node against its communicator in MultiAppNearestNodeTransfer
  framework/src/transfers/MultiAppNearestNodeTransfer.C
  framework/src/transfers/MultiAppTransfer.C
  test/tests/transfers/multiapp_nearest_node_transfer/gold/source_boundary_master_out.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/source_boundary_master_out_sub0.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/source_boundary_master_out_sub1.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/source_target_boundary.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/source_target_boundary_sub0.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/source_target_boundary_sub1.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/target_boundary_master_out.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/target_boundary_master_out_sub0.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/target_boundary_master_out_sub1.e
  test/tests/transfers/multiapp_nearest_node_transfer/source_boundary_master.i
  test/tests/transfers/multiapp_nearest_node_transfer/source_boundary_sub.i
  test/tests/transfers/multiapp_nearest_node_transfer/target_boundary_master.i
  test/tests/transfers/multiapp_nearest_node_transfer/target_boundary_sub.i
  test/tests/transfers/multiapp_nearest_node_transfer/tests
Labels: PR: Ready for Review/Merge

#18640 Update SONDefinitionFormatter for NEAMS input validation
  framework/src/outputs/formatters/SONDefinitionFormatter.C
  test/tests/outputs/format/tests
Labels: PR: Failed but allowed

#18598 Read command-line arguments from files for multiapp
  framework/include/multiapps/MultiApp.h
  framework/src/multiapps/MultiApp.C
  test/tests/multiapps/cliargs_from_file/cliargs.txt
  test/tests/multiapps/cliargs_from_file/cliargs_1.txt
  test/tests/multiapps/cliargs_from_file/cliargs_2.txt
  test/tests/multiapps/cliargs_from_file/cliargs_empty.txt
  test/tests/multiapps/cliargs_from_file/cliargs_many.txt
  test/tests/multiapps/cliargs_from_file/cliargs_master.i
  test/tests/multiapps/cliargs_from_file/cliargs_master_inline.i
  test/tests/multiapps/cliargs_from_file/cliargs_oneline.txt
  test/tests/multiapps/cliargs_from_file/cliargs_semicolon.txt
  test/tests/multiapps/cliargs_from_file/cliargs_sub.i
  test/tests/multiapps/cliargs_from_file/cliargs_sub_1.i
  test/tests/multiapps/cliargs_from_file/cliargs_sub_2.i
  test/tests/multiapps/cliargs_from_file/gold/cliargs_master_out.e
  test/tests/multiapps/cliargs_from_file/gold/cliargs_master_out_sub_app0.e
  test/tests/multiapps/cliargs_from_file/gold/cliargs_master_out_sub_app1.e
  test/tests/multiapps/cliargs_from_file/gold/cliargs_master_out_sub_app2.e
  test/tests/multiapps/cliargs_from_file/gold/cliargs_master_out_sub_app3.e
  test/tests/multiapps/cliargs_from_file/positions.txt
  test/tests/multiapps/cliargs_from_file/positions_1.txt
  test/tests/multiapps/cliargs_from_file/positions_2.txt
  test/tests/multiapps/cliargs_from_file/tests
Labels: PR: Ready for Review/Merge
