Repository idaholab/moose, pull requests merged in 2021-06, with the labels that each got.

#17977 MOOSE papers added to publications and citing.md
  framework/doc/content/bib/external_papers_using_moose.bib
  framework/doc/content/bib/inl_papers_using_moose.bib
  modules/doc/content/citing.md
Labels: PR: Failed but allowed

#17805 Add Hill Tensor Material
  modules/tensor_mechanics/doc/content/source/materials/HillConstants.md
  modules/tensor_mechanics/include/materials/ADGeneralizedRadialReturnStressUpdate.h
  modules/tensor_mechanics/include/materials/ADHillCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/ADHillElastoPlasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/ADHillPlasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/HillConstants.h
  modules/tensor_mechanics/src/materials/ADGeneralizedRadialReturnStressUpdate.C
  modules/tensor_mechanics/src/materials/ADHillCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/ADHillElastoPlasticityStressUpdate.C
  modules/tensor_mechanics/src/materials/ADHillPlasticityStressUpdate.C
  modules/tensor_mechanics/src/materials/HillConstants.C
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_integration_error.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_x_3d.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_y_3d.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_z_3d.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_iso_creep_x_3d.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/anis_mech_hill_tensor_creep.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/anis_mech_hill_tensor_creep_small_tiny_step_ts_limit_test.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_elastoplasticity/ad_aniso_plasticity_x_one.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_elastoplasticity/ad_aniso_plasticity_x_one_ref.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_plasticity/ad_aniso_plasticity_x.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_plasticity/ad_aniso_plasticity_x_rotate.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_plasticity/ad_aniso_plasticity_y.i
  modules/tensor_mechanics/test/tests/ad_anisotropic_plasticity/anis_plasticity_test.i
Labels: PR: Ready for Review/Merge

#18029 new Biot coefficient added to PorousFlowPorosity
  modules/porous_flow/doc/content/modules/porous_flow/nomenclature.md
  modules/porous_flow/doc/content/modules/porous_flow/porosity.md
  modules/porous_flow/doc/content/source/materials/PorousFlowPorosity.md
  modules/porous_flow/src/materials/PorousFlowPorosity.C
  modules/porous_flow/test/tests/poroperm/gold/poro_hm_out.csv
  modules/porous_flow/test/tests/poroperm/poro_hm.i
Labels: PR: Auto Merge

#18039 Fix segmentation fault with ElementValueSampler and FV variables
  framework/src/vectorpostprocessors/ElementValueSampler.C
  test/tests/vectorpostprocessors/element_value_sampler/fv_element_value_sampler.i
  test/tests/vectorpostprocessors/element_value_sampler/tests
Labels: PR: Auto Merge

#18043 Fix doxygen and code coverage links on framework development page
  modules/doc/content/framework_development/index.md
Labels: PR: Auto Merge

#17547 Move FluidDensityAux from Pronghorn to fluid property module.
  modules/fluid_properties/doc/content/source/auxkernels/FluidDensityAux.md
  modules/fluid_properties/include/auxkernels/FluidDensityAux.h
  modules/fluid_properties/src/auxkernels/FluidDensityAux.C
  modules/fluid_properties/test/tests/auxkernels/fluid_density_aux.i
  modules/fluid_properties/test/tests/auxkernels/gold/fluid_density_aux_out.e
  modules/fluid_properties/test/tests/auxkernels/tests
Labels: P: normal

#18052 Added an additional function call insertion point in ParallelStudy and parameter range change
  modules/ray_tracing/include/utils/ParallelStudy.h
Labels: PR: Failed but allowed

#18063 Add get crack front points ellipse cut user object
  modules/xfem/src/userobjects/EllipseCutUserObject.C
  modules/xfem/test/tests/solid_mechanics_basic/elliptical_crack.i
  modules/xfem/test/tests/solid_mechanics_basic/gold/elliptical_crack_out.e
Labels: PR: Failed but allowed

#18071 Remove non *.hpc.inl.gov domains from INL HPC proxy
  scripts/hpc_proxy.pac
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#18055 Fix CIVET result links for master branch documentation
  python/MooseDocs/__init__.py
  python/MooseDocs/common/get_content.py
  python/MooseDocs/extensions/civet.py
  python/MooseDocs/extensions/gitutils.py
  python/MooseDocs/test/extensions/test_gitutils.py
  python/moosesqa/SQADocumentReport.py
  python/moosesqa/check_documents.py
  python/moosesqa/check_requirements.py
  python/mooseutils/__init__.py
  python/mooseutils/gitutils.py
  python/mooseutils/tests/test_gitutils.py
  python/pyhit/__init__.py
Labels: PR: Failed but allowed

#16930 Remove order parameter from mechanical contact
  modules/contact/src/actions/ContactAction.C
  modules/contact/test/tests/hertz_spherical/hertz_contact_hex27.i
  modules/contact/test/tests/hertz_spherical/hertz_contact_rz_quad8.i
  modules/contact/test/tests/ring_contact/ring_contact.i
Labels: P: normal

#17509 Arbitrary test root path
  python/TestHarness/TestHarness.py
Labels: P: normal

#18114 Add ability to output JSON file per timestep
  framework/include/outputs/JSONOutput.h
  framework/src/outputs/JSONOutput.C
  test/tests/outputs/json/one_file_per_timestep/gold/json_out_0000.json
  test/tests/outputs/json/one_file_per_timestep/gold/json_out_0001.json
  test/tests/outputs/json/one_file_per_timestep/gold/json_out_0002.json
  test/tests/outputs/json/one_file_per_timestep/gold/json_out_0003.json
  test/tests/outputs/json/one_file_per_timestep/json.i
  test/tests/outputs/json/one_file_per_timestep/tests
Labels: PR: Failed but allowed

#17963 Get fsi compile/test standalone
  modules/modules.mk
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#18172 Remove overzealous TIME_SECTION in stochastic tools
  framework/include/distributions/Distribution.h
  framework/include/samplers/Sampler.h
  framework/src/distributions/Distribution.C
  framework/src/samplers/Sampler.C
  modules/stochastic_tools/include/multiapps/SamplerFullSolveMultiApp.h
  modules/stochastic_tools/src/distributions/JohnsonSB.C
  modules/stochastic_tools/src/distributions/KernelDensity1D.C
  modules/stochastic_tools/src/distributions/Logistic.C
  modules/stochastic_tools/src/distributions/Lognormal.C
  modules/stochastic_tools/src/distributions/Normal.C
  modules/stochastic_tools/src/distributions/TruncatedNormal.C
  modules/stochastic_tools/src/distributions/Uniform.C
  modules/stochastic_tools/src/distributions/Weibull.C
  modules/stochastic_tools/src/multiapps/SamplerFullSolveMultiApp.C
  modules/stochastic_tools/src/samplers/CartesianProductSampler.C
  modules/stochastic_tools/src/samplers/MonteCarloSampler.C
Labels: PR: Auto Merge

#17581 Require c++14
  conda/libmesh/build.sh
  conda/libmesh/meta.yaml
  framework/doc/content/sqa/framework_srs.md
  modules/doc/content/getting_started/installation/cluster.md
  modules/doc/content/getting_started/installation/hpc_install_moose.md
  modules/doc/content/getting_started/installation/manual_gcc.md
  modules/doc/content/getting_started/installation/manual_installation_llvm.md
  modules/doc/content/getting_started/petsc_default.md
  scripts/update_and_rebuild_libmesh.sh
Labels: P: normal, PR: Auto Merge

#18206 Account for moosetools in Docker image. Fixes #17406.
  docker_ci/Dockerfile
  docker_ci/Jenkinsfile
Labels: PR: Auto Merge

#18197 Add linear porosity to PorousFlow
  modules/porous_flow/doc/content/modules/porous_flow/permeability.md
  modules/porous_flow/doc/content/modules/porous_flow/porosity.md
  modules/porous_flow/doc/content/source/materials/PorousFlowPorosityLinear.md
  modules/porous_flow/include/materials/PorousFlowPorosityLinear.h
  modules/porous_flow/src/materials/PorousFlowPorosityLinear.C
  modules/porous_flow/test/tests/jacobian/linear_por.i
  modules/porous_flow/test/tests/jacobian/tests
  modules/porous_flow/test/tests/poroperm/gold/linear_test_vals_min.csv
  modules/porous_flow/test/tests/poroperm/gold/linear_test_vals_out.csv
  modules/porous_flow/test/tests/poroperm/linear_except1.i
  modules/porous_flow/test/tests/poroperm/linear_test_vals.i
  modules/porous_flow/test/tests/poroperm/tests
Labels: PR: Auto Merge
