Repository idaholab/moose, pull requests merged in 2021-05, with the labels that each got.

#17682 Refinement near a boundary
  framework/doc/content/source/markers/BoundaryMarker.md
  framework/include/markers/BoundaryMarker.h
  framework/src/markers/BoundaryMarker.C
  framework/src/markers/BoxMarker.C
  test/tests/markers/boundary_marker/adjacent.i
  test/tests/markers/boundary_marker/distance.i
  test/tests/markers/boundary_marker/gold/adjacent_out.e
  test/tests/markers/boundary_marker/gold/distance_out.e
  test/tests/markers/boundary_marker/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#17567 Add documentation for the integral variable pp
  framework/doc/content/source/postprocessors/ElementIntegralVariablePostprocessor.md
Labels: P: normal, PR: Auto Merge, PR: Ready for Review/Merge

#17728 Various ray_tracing enhancements
  modules/ray_tracing/include/raytracing/ClaimRays.h
  modules/ray_tracing/include/raytracing/ElemExtrema.h
  modules/ray_tracing/include/userobjects/RayTracingStudy.h
  modules/ray_tracing/src/raytracing/ClaimRays.C
  modules/ray_tracing/src/raytracing/ElemExtrema.C
  modules/ray_tracing/src/raytracing/TraceRay.C
  modules/ray_tracing/src/userobjects/RepeatableRayStudyBase.C
  modules/ray_tracing/unit/src/ElemExtremaTest.C
Labels: PR: Failed but allowed

#17562 Block-restricted DiracKernel
  framework/include/dirackernels/DiracKernel.h
  framework/include/dirackernels/DiracKernelInfo.h
  framework/include/interfaces/BlockRestrictable.h
  framework/src/dirackernels/DiracKernel.C
  framework/src/dirackernels/DiracKernelInfo.C
  test/tests/dirackernels/block_restriction/gold/skip_out.e
  test/tests/dirackernels/block_restriction/point_value_file.csv
  test/tests/dirackernels/block_restriction/skip.i
  test/tests/dirackernels/block_restriction/tests
Labels: P: normal, PR: Failed but allowed

#17421 Compute strain energy rate density in a parent class
  modules/tensor_mechanics/include/materials/ADAnisotropicReturnCreepStressUpdateBase.h
  modules/tensor_mechanics/include/materials/ADAnisotropicReturnPlasticityStressUpdateBase.h
  modules/tensor_mechanics/include/materials/ADHillCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/ADHillPlasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/ADPowerLawCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/RadialReturnCreepStressUpdateBase.h
  modules/tensor_mechanics/include/materials/StrainEnergyRateDensity.h
  modules/tensor_mechanics/include/materials/StressUpdateBase.h
  modules/tensor_mechanics/src/materials/ADHillCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/ADHillPlasticityStressUpdate.C
  modules/tensor_mechanics/src/materials/ADPowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/StrainEnergyRateDensity.C
Labels: P: normal

#17742 Abaqus UMAT revival
  framework/app.mk
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankFourTensorImplementation.h
  modules/tensor_mechanics/doc/content/source/materials/abaqus/AbaqusUMATStress.md
  modules/tensor_mechanics/include/materials/abaqus/AbaqusUMATStress.h
  modules/tensor_mechanics/plugins/README
  modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C
  modules/tensor_mechanics/test/include/materials/abaqus/utility/DROTCalc.f
  modules/tensor_mechanics/test/include/materials/abaqus/utility/ROTSIGInterface.f
  modules/tensor_mechanics/test/include/materials/abaqus/utility/SINVInterface.f
  modules/tensor_mechanics/test/include/materials/abaqus/utility/SPRINCInterface.f
  modules/tensor_mechanics/test/include/materials/abaqus/utility/SPRINDInterface.f
  modules/tensor_mechanics/test/plugins/creep.f
  modules/tensor_mechanics/test/plugins/creep_usr_creep.f
  modules/tensor_mechanics/test/plugins/elastic.f
  modules/tensor_mechanics/test/plugins/linear_strain_hardening.f
  modules/tensor_mechanics/test/plugins/swelling.f
  modules/tensor_mechanics/test/tests/umat/elastic.i
  modules/tensor_mechanics/test/tests/umat/gold/elastic_out.e
  modules/tensor_mechanics/test/tests/umat/gold/linear_strain_hardening_out.e
  modules/tensor_mechanics/test/tests/umat/linear_strain_hardening.i
  modules/tensor_mechanics/test/tests/umat/tests
Labels: PR: Failed but allowed

#17684 Winding order fix
  framework/src/meshgenerators/ConcentricCircleMeshGenerator.C
  modules/tensor_mechanics/include/bcs/DisplacementAboutAxis.h
  test/include/auxkernels/WindingOrder.h
  test/src/auxkernels/WindingOrder.C
  test/tests/meshgenerators/concentric_circle_mesh_generator/concentric_circle_mesh2.i
  test/tests/meshgenerators/concentric_circle_mesh_generator/gold/concentric_circle_mesh2_out.csv
  test/tests/meshgenerators/concentric_circle_mesh_generator/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#17767 Fix fortran warning, clean up indentation
  modules/tensor_mechanics/test/plugins/creep_usr_creep.f
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#17746 Add postprocessor value coupling to parsed materials
  framework/doc/content/source/materials/DerivativeParsedMaterial.md
  framework/doc/content/source/materials/ParsedMaterial.md
  framework/include/materials/ParsedMaterialHelper.h
  framework/src/materials/DerivativeParsedMaterial.C
  framework/src/materials/DerivativeParsedMaterialHelper.C
  framework/src/materials/ParsedMaterial.C
  framework/src/materials/ParsedMaterialBase.C
  framework/src/materials/ParsedMaterialHelper.C
  test/tests/materials/derivative_material_interface/gold/postprocessors_out.e
  test/tests/materials/derivative_material_interface/postprocessors.i
  test/tests/materials/derivative_material_interface/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#17770 fix myriad typos refs #17769
  framework/doc/content/source/executioners/InversePowerMethod.md
  framework/doc/content/sqa/framework_scs.md
  framework/doc/content/syntax/Executioner/index.md
  framework/doc/content/syntax/Materials/index.md
  framework/doc/content/syntax/MultiApps/index.md
  framework/include/problems/EigenProblem.h
  framework/src/executioners/EigenExecutionerBase.C
  framework/src/executioners/Eigenvalue.C
  framework/src/executioners/InversePowerMethod.C
  framework/src/problems/EigenProblem.C
  modules/doc/content/framework_development/warehouses.md
  modules/doc/content/getting_started/installation/conda.md
  modules/doc/content/getting_started/new_users.md
  modules/level_set/doc/content/modules/level_set/index.md
  modules/navier_stokes/doc/content/source/kernels/INSADSmagorinskyEddyViscosity.md
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/index.md
  test/tests/problems/eigen_problem/initial_condition/tests
Labels: PR: Failed but allowed

#17772 Fix poor logic in ParallelStudy work buffer resize
  modules/ray_tracing/include/utils/ParallelStudy.h
Labels: PR: Auto Merge, PR: Failed but allowed, PR: Ready for Review/Merge

#17763 Protect against zero size dof dependence before libMesh constraints
  framework/include/base/Assembly.h
  test/tests/kernels/diffusion_with_hanging_node/ad_simple_diffusion.i
  test/tests/kernels/diffusion_with_hanging_node/tests
Labels: PR: Failed but allowed

#17235 PorousFlow: Enthalpy injection BC + Action
  modules/porous_flow/doc/content/source/actions/PorousFlowAddBCAction.md
  modules/porous_flow/doc/content/source/bcs/PorousFlowEnthalpySink.md
  modules/porous_flow/doc/content/source/bcs/PorousFlowSinkBC.md
  modules/porous_flow/doc/content/syntax/Modules/PorousFlow/BCs/index.md
  modules/porous_flow/doc/content/syntax/Modules/PorousFlow/index.md
  modules/porous_flow/doc/content/syntax/Modules/index.md
  modules/porous_flow/include/actions/PorousFlowAddBCAction.h
  modules/porous_flow/include/bcs/PorousFlowEnthalpySink.h
  modules/porous_flow/include/bcs/PorousFlowSinkBC.h
  modules/porous_flow/src/actions/PorousFlowAddBCAction.C
  modules/porous_flow/src/base/PorousFlowApp.C
  modules/porous_flow/src/bcs/PorousFlowEnthalpySink.C
  modules/porous_flow/src/bcs/PorousFlowSinkBC.C
  modules/porous_flow/test/tests/jacobian/esbc01.i
  modules/porous_flow/test/tests/jacobian/esbc02.i
  modules/porous_flow/test/tests/jacobian/tests
  modules/porous_flow/test/tests/sinks/gold/s11.e
  modules/porous_flow/test/tests/sinks/gold/s12.csv
  modules/porous_flow/test/tests/sinks/s11.i
  modules/porous_flow/test/tests/sinks/s11_act.i
  modules/porous_flow/test/tests/sinks/s12.i
  modules/porous_flow/test/tests/sinks/tests
Labels: P: normal

#17752 Ability to specify reporter type in MultiAppCloneReporterTransfer
  framework/include/transfers/ReporterTransferInterface.h
  framework/src/transfers/MultiAppCloneReporterTransfer.C
  framework/src/transfers/ReporterTransferInterface.C
  test/tests/transfers/reporter_transfer/clone_type.i
  test/tests/transfers/reporter_transfer/gold/clone_type_out.json
  test/tests/transfers/reporter_transfer/gold/clone_type_out.json.1
  test/tests/transfers/reporter_transfer/gold/clone_type_out.json.2
  test/tests/transfers/reporter_transfer/gold/clone_type_out.json.3
  test/tests/transfers/reporter_transfer/gold/clone_type_out.json.4
  test/tests/transfers/reporter_transfer/gold/clone_type_out.json.5
  test/tests/transfers/reporter_transfer/tests
Labels: PR: Failed but allowed

#17826 Fix/test joining of urls in git submodule-hash command
  framework/doc/sqa_reports.yml
  python/MooseDocs/extensions/gitutils.py
  python/MooseDocs/test/extensions/test_gitutils.py
  python/moosesqa/SQARequirementReport.py
Labels: PR: Auto Merge

#17756 Fix tensor mechanics action material output
  modules/tensor_mechanics/include/actions/TensorMechanicsAction.h
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
  modules/tensor_mechanics/test/tests/action/tests
Labels: PR: Ready for Review/Merge

#17839 ADDerivativeParsedMaterial should create material properties even if …
  framework/src/materials/DerivativeParsedMaterialHelper.C
  test/tests/materials/derivative_material_interface/ad_derivative_parsed_material_zero.i
  test/tests/materials/derivative_material_interface/gold/ad_derivative_parsed_material_zero_out.e
  test/tests/materials/derivative_material_interface/tests
Labels: PR: Auto Merge

#17862 Improve support for offline results
  python/MooseDocs/extensions/civet.py
  python/mooseutils/civet_results.py
  python/mooseutils/tests/test_civet_results.py
Labels: PR: Auto Merge

#17550 Make normals consistent
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/include/constraints/MortarConstraintBase.h
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/constraints/MortarConstraintBase.C
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/relationshipmanagers/AugmentSparsityOnInterface.C
  modules/combined/test/tests/gap_heat_transfer_mortar/finite-2d-rz/gold/second_high_k.csv
  modules/combined/test/tests/gap_heat_transfer_mortar/finite-2d-rz/gold/second_low_k.csv
  modules/combined/test/tests/gap_heat_transfer_mortar/small-2d-rz/gold/second_high_k.csv
  modules/combined/test/tests/gap_heat_transfer_mortar/small-2d-rz/gold/second_low_k.csv
  modules/contact/include/constraints/ComputeWeightedGapLMMechanicalContact.h
  modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C
  modules/contact/test/tests/bouncing-block-contact/gold/frictional-mortar-fb-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictional-mortar-min-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictional-nodal-min-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictional-nodal-min-normal-lm-mortar-fb-tangential-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-mortar-fb-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-mortar-min-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-nodal-fb-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-nodal-min-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-weighted-gap-mixed-basis_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-weighted-gap_out.e
  modules/contact/test/tests/bouncing-block-contact/grid-sequencing/gold/grid-sequencing_exo.e
  modules/contact/test/tests/bouncing-block-contact/ping-ponging/gold/mortar-no-ping-pong_exo.e
  modules/contact/test/tests/fieldsplit/gold/frictional_mortar_FS_out.e
  modules/contact/test/tests/non-singular-frictional-mortar/gold/frictional-mortar_exodus.e
  modules/contact/test/tests/sliding_block/in_and_out/gold/frictional_lm_out.e
  modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_lm_out.e
Labels: P: normal

#17861 Fix typo in LevelSetBimaterial classes
  modules/xfem/src/materials/LevelSetBiMaterialRankFour.C
  modules/xfem/src/materials/LevelSetBiMaterialRankTwo.C
  modules/xfem/src/materials/LevelSetBiMaterialReal.C
Labels: PR: Auto Merge

#17542 Fixed indexing in ACBarrierFunction.C to prevent indexing outisde of …
  modules/phase_field/include/kernels/ACBarrierFunction.h
  modules/phase_field/src/kernels/ACBarrierFunction.C
Labels: P: normal, PR: Failed but allowed

#17887 Always render system headers when listing complete app syntax
  python/MooseDocs/extensions/appsyntax.py
  python/moosesyntax/nodes.py
Labels: PR: Failed but allowed

#17902 Build redistributable monolithic header for JIT
  framework/moose.mk
  framework/src/utils/ADFParser.C
  modules/phase_field/doc/content/modules/phase_field/FunctionMaterials/JITCompilation.md
Labels: PR: Failed but allowed

#17891 Output more digits for postprocessor values used for monitoring Picard convergence
  framework/include/outputs/Console.h
  framework/src/executioners/PicardSolve.C
  framework/src/outputs/Console.C
Labels: PR: Failed but allowed

#17915 Add CODEOWNERS for a few modules to test capability
  CODEOWNERS
Labels: PR: Failed but allowed

#17374 Allow and check for arbitrary coupled variables to generate complete Jacobians
  framework/include/utils/JvarMapInterface.h
  framework/src/executioners/FEProblemSolve.C
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_change.i
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_change_restart1.i
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_change_restart2.i
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_force_step.i
  modules/combined/test/tests/fdp_geometric_coupling/fdp_geometric_coupling.i
  modules/combined/test/tests/reference_residual/reference_residual.i
  modules/combined/test/tests/reference_residual/reference_residual_perfgraph.i
  modules/combined/test/tests/thermal_strain/thermal_strain.i
  modules/tensor_mechanics/include/kernels/StressDivergenceTensors.h
  modules/tensor_mechanics/src/kernels/ADDynamicStressDivergenceTensors.C
  modules/tensor_mechanics/src/kernels/DynamicStressDivergenceTensors.C
  modules/tensor_mechanics/src/kernels/StressDivergenceRSphericalTensors.C
  modules/tensor_mechanics/src/kernels/StressDivergenceRZTensors.C
  modules/tensor_mechanics/src/kernels/StressDivergenceTensors.C
  modules/tensor_mechanics/test/tests/test_jacobian/jacobian_test_3D.i
Labels: P: normal, PR: Ready for Review/Merge

#17497 Variationally consistent mortar friction
  framework/include/interfaces/NeighborCoupleable.h
  framework/src/interfaces/NeighborCoupleable.C
  modules/contact/doc/content/bib/contact.bib
  modules/contact/doc/content/source/constraints/ComputeFrictionalForceLMMechanicalContact.md
  modules/contact/include/constraints/ComputeFrictionalForceLMMechanicalContact.h
  modules/contact/include/constraints/ComputeWeightedGapLMMechanicalContact.h
  modules/contact/src/constraints/ComputeFrictionalForceLMMechanicalContact.C
  modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C
  modules/contact/test/tests/pdass_problems/cylinder.e
  modules/contact/test/tests/pdass_problems/cylinder_friction.i
  modules/contact/test/tests/pdass_problems/frictional_bouncing_block.i
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_chkfile_cont_press_0003.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_chkfile_friction_0003.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_chkfile_x_disp_0003.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_chkfile_y_disp_0003.csv
  modules/contact/test/tests/pdass_problems/gold/frictional_bouncing_block_checkfile_cont_press_0029.csv
  modules/contact/test/tests/pdass_problems/gold/frictional_bouncing_block_checkfile_friction_0029.csv
  modules/contact/test/tests/pdass_problems/gold/ironing_chkfile_cont_press_0009.csv
  modules/contact/test/tests/pdass_problems/gold/ironing_chkfile_friction_0009.csv
  modules/contact/test/tests/pdass_problems/hertz_27.jou
  modules/contact/test/tests/pdass_problems/iron.e
  modules/contact/test/tests/pdass_problems/ironing.i
  modules/contact/test/tests/pdass_problems/ironing_mesh.jou
  modules/contact/test/tests/pdass_problems/long-bottom-block-1elem-blocks.e
  modules/contact/test/tests/pdass_problems/tests
Labels: P: normal, PR: Auto Merge

#17944 Add non-const getter to TraceRay and make neighbor methods public
  modules/ray_tracing/include/base/RayTracingObject.h
  modules/ray_tracing/include/raytracing/TraceRay.h
  modules/ray_tracing/include/userobjects/RayTracingStudy.h
  modules/ray_tracing/src/base/RayTracingObject.C
  modules/ray_tracing/src/raybcs/RayBoundaryConditionBase.C
  modules/ray_tracing/src/raykernels/RayKernelBase.C
  modules/ray_tracing/src/raytracing/TraceRay.C
  modules/ray_tracing/test/src/userobjects/BackfaceCullingStudyTest.C
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#17950 Correct UserObjectInterface::hasUserObject<T> and add tests
  framework/include/userobject/UserObjectInterface.h
  test/include/userobjects/UserObjectInterfaceTest.h
  test/src/userobjects/UserObjectInterfaceTest.C
  test/tests/interfaces/userobjectinterface/tests
  test/tests/interfaces/userobjectinterface/uoi.i
Labels: PR: Ready for Review/Merge

#17930 Use a separate control parameter to print out action dependencies
  framework/include/actions/ActionWarehouse.h
  framework/src/actions/ActionWarehouse.C
  framework/src/actions/SetupDebugAction.C
  test/tests/actions/debug_block/debug_print_actions_test.i
Labels: PR: Auto Merge

#17959 Fix uninitialized value
  framework/src/actions/ActionWarehouse.C
Labels: PR: Failed but allowed

#17829 Add test for vector periodic BC
  test/tests/bcs/periodic/gold/vector_out.e
  test/tests/bcs/periodic/periodic_vector_bc_test.i
  test/tests/bcs/periodic/tests
Labels: PR: Auto Merge

#17972 Make TraceRay public in RayTracingStudy
  modules/ray_tracing/include/userobjects/RayTracingStudy.h
Labels: PR: Failed but allowed, PR: Ready for Review/Merge
