Repository idaholab/moose, pull requests merged in 2021-04, with the labels that each got.

#15794 Fix orphan nodes on 3D meshes for BreakMeshByBlockGenerator
  framework/src/meshgenerators/BreakMeshByBlockGenerator.C
  test/tests/meshgenerators/break_mesh_by_block_generator/gold/hanging_nodes_parallel_out.e
  test/tests/meshgenerators/break_mesh_by_block_generator/hanging_nodes_parallel.i
  test/tests/meshgenerators/break_mesh_by_block_generator/tests
Labels: PR: Auto Merge

#17189 Weighted gap mortar mechanical contact implementation
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/systems/NonlinearSystemBase.C
  modules/contact/doc/content/bib/contact.bib
  modules/contact/doc/content/source/constraints/ApplyPenetrationConstraintLMMechanicalContact.md
  modules/contact/doc/content/source/constraints/ComputeWeightedGapLMMechanicalContact.md
  modules/contact/include/constraints/ApplyPenetrationConstraintLMMechanicalContact.h
  modules/contact/include/constraints/ComputeWeightedGapLMMechanicalContact.h
  modules/contact/src/constraints/ApplyPenetrationConstraintLMMechanicalContact.C
  modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C
  modules/contact/test/tests/bouncing-block-contact/frictionless-weighted-gap-mixed-basis.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-weighted-gap.i
  modules/contact/test/tests/bouncing-block-contact/gold/frictional-nodal-min-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictional-nodal-min-normal-lm-mortar-fb-tangential-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-nodal-fb-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-nodal-min-lm-mortar-disp_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-weighted-gap-mixed-basis_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-weighted-gap_out.e
  modules/contact/test/tests/bouncing-block-contact/ping-ponging/gold/mortar-no-ping-pong_exo.e
  modules/contact/test/tests/bouncing-block-contact/tests
  modules/contact/test/tests/sliding_block/in_and_out/gold/frictional_lm_out.e
  modules/contact/test/tests/sliding_block/in_and_out/gold/frictionless_lm_out.e
Labels: PR: Ready for Review/Merge

#17494 Clean up executioner blocks for eigen problems
  framework/src/problems/EigenProblem.C
  test/tests/problems/eigen_problem/arraykernels/ne_array_kernels.i
  test/tests/problems/eigen_problem/arraykernels/ne_two_variables.i
  test/tests/problems/eigen_problem/eigensolvers/ane.i
  test/tests/problems/eigen_problem/eigensolvers/ne-coupled-resid-scaling.i
  test/tests/problems/eigen_problem/eigensolvers/ne-coupled-scaling.i
  test/tests/problems/eigen_problem/eigensolvers/ne.i
  test/tests/problems/eigen_problem/eigensolvers/ne_coupled.i
  test/tests/problems/eigen_problem/eigensolvers/ne_coupled_scaled.i
  test/tests/problems/eigen_problem/eigensolvers/ne_deficient_b.i
  test/tests/problems/eigen_problem/eigensolvers/ne_hmg.i
  test/tests/problems/eigen_problem/eigensolvers/tests
Labels: PR: Ready for Review/Merge

#17491 Only link to gperftools in profiling and opt modes
  framework/build.mk
  modules/doc/content/application_development/profiling.md
Labels: PR: Auto Merge, PR: Ready for Review/Merge

#17380 Remove _u_old from ScalarKernel/AuxScalarKernel and const-ify scalar vars
  framework/include/auxkernels/AuxScalarKernel.h
  framework/include/auxkernels/QuotientScalarAux.h
  framework/include/bcs/OneDEqualValueConstraintBC.h
  framework/include/functions/MooseParsedFunctionWrapper.h
  framework/include/interfaces/ScalarCoupleable.h
  framework/include/kernels/CoupledODETimeDerivative.h
  framework/include/kernels/ParsedODEKernel.h
  framework/include/kernels/ScalarKernel.h
  framework/include/kernels/ScalarLagrangeMultiplier.h
  framework/include/variables/MooseVariableScalar.h
  framework/src/auxkernels/AuxScalarKernel.C
  framework/src/functions/MooseParsedFunctionWrapper.C
  framework/src/interfaces/ScalarCoupleable.C
  framework/src/kernels/ParsedODEKernel.C
  framework/src/kernels/ScalarKernel.C
  framework/src/variables/MooseVariableScalar.C
  modules/tensor_mechanics/include/materials/ADComputePlaneFiniteStrain.h
  modules/tensor_mechanics/include/materials/ADComputePlaneIncrementalStrain.h
  modules/tensor_mechanics/include/materials/ADComputePlaneSmallStrain.h
  modules/tensor_mechanics/include/materials/ComputeAxisymmetric1DIncrementalStrain.h
  modules/tensor_mechanics/include/materials/ComputeAxisymmetric1DSmallStrain.h
  modules/tensor_mechanics/include/materials/ComputePlaneFiniteStrain.h
  modules/tensor_mechanics/include/materials/ComputePlaneIncrementalStrain.h
  modules/tensor_mechanics/include/materials/ComputePlaneSmallStrain.h
  modules/tensor_mechanics/src/materials/ADComputePlaneFiniteStrain.C
  modules/tensor_mechanics/src/materials/ADComputePlaneIncrementalStrain.C
  modules/tensor_mechanics/src/materials/ADComputePlaneSmallStrain.C
  modules/tensor_mechanics/src/materials/ComputeAxisymmetric1DFiniteStrain.C
  modules/tensor_mechanics/src/materials/ComputeAxisymmetric1DIncrementalStrain.C
  modules/tensor_mechanics/src/materials/ComputeAxisymmetric1DSmallStrain.C
  modules/tensor_mechanics/src/materials/ComputePlaneFiniteStrain.C
  modules/tensor_mechanics/src/materials/ComputePlaneIncrementalStrain.C
  modules/tensor_mechanics/src/materials/ComputePlaneSmallStrain.C
  test/include/auxkernels/CoupledScalarAux.h
  test/include/auxkernels/ExplicitODE.h
  test/include/bcs/ScalarVarBC.h
  test/include/dirackernels/ReportingConstantSource.h
  test/include/scalarkernels/ImplicitODEx.h
  test/include/scalarkernels/ImplicitODEy.h
  test/src/auxkernels/ExplicitODE.C
Labels: PR: Failed but allowed

#17518 Fix a bug in PR 17447
  framework/include/base/Assembly.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/src/base/Assembly.C
  framework/src/bcs/ArrayLowerDIntegratedBC.C
  framework/src/loops/ComputeJacobianThread.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed

#17522 Use upstream capability to restart scalar variables
  framework/doc/content/source/meshgenerators/FileMeshGenerator.md
  framework/doc/content/source/variables/MooseVariableBase.md
  framework/src/systems/SystemBase.C
  test/tests/restart/scalar-var/gold/part1_out.e
  test/tests/restart/scalar-var/gold/part2_out.e
  test/tests/restart/scalar-var/part1.i
  test/tests/restart/scalar-var/part2.i
  test/tests/restart/scalar-var/tests
Labels: PR: Failed but allowed

#17399 Add scaling vector if we are doing automatic scaling in MooseVariableBase::initialSetup
  framework/src/variables/MooseVariableBase.C
  test/tests/multiapps/auto_diff_auto_scaling/gold/main_out.e
  test/tests/multiapps/auto_diff_auto_scaling/gold/main_out_sub_app0.e
  test/tests/multiapps/auto_diff_auto_scaling/main.i
  test/tests/multiapps/auto_diff_auto_scaling/sub.i
  test/tests/multiapps/auto_diff_auto_scaling/tests
Labels: PR: Failed but allowed, PR: Ready for Review/Merge

#17535 Fixup for #17522
  test/tests/restart/scalar-var/tests
Labels: PR: Auto Merge, PR: Failed but allowed

#17514 Create additional orders and families for material outputs
  modules/tensor_mechanics/include/actions/TensorMechanicsAction.h
  modules/tensor_mechanics/include/actions/TensorMechanicsActionBase.h
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
  modules/tensor_mechanics/test/tests/action/material_output_order.i
  modules/tensor_mechanics/test/tests/action/tests
Labels: PR: Failed but allowed

#17449 Add FVInterfaceKernels
  framework/doc/content/source/actions/AddFVInterfaceKernelAction.md
  framework/doc/content/source/fviks/FVOneVarDiffusionInterface.md
  framework/doc/content/syntax/FVInterfaceKernels/index.md
  framework/include/actions/AddFVInterfaceKernelAction.h
  framework/include/fvbcs/FVBoundaryCondition.h
  framework/include/fviks/FVInterfaceKernel.h
  framework/include/fviks/FVOneVarDiffusionInterface.h
  framework/include/fvkernels/FVFluxKernel.h
  framework/include/geomsearch/GeometricSearchInterface.h
  framework/include/interfaces/PostprocessorInterface.h
  framework/include/loops/ComputeFVFluxThread.h
  framework/include/materials/MaterialPropertyStorage.h
  framework/include/problems/FEProblemBase.h
  framework/include/systems/SystemBase.h
  framework/include/userobject/UserObjectInterface.h
  framework/include/variables/MooseVariableFE.h
  framework/include/variables/MooseVariableFV.h
  framework/include/variables/NeighborCoupleableMooseVariableDependencyIntermediateInterface.h
  framework/include/variables/VariableWarehouse.h
  framework/include/vectorpostprocessors/VectorPostprocessorInterface.h
  framework/src/actions/AddFVInterfaceKernelAction.C
  framework/src/base/Moose.C
  framework/src/fvbcs/FVBoundaryCondition.C
  framework/src/fviks/FVInterfaceKernel.C
  framework/src/fviks/FVOneVarDiffusionInterface.C
  framework/src/fvkernels/FVFluxKernel.C
  framework/src/geomsearch/GeometricSearchInterface.C
  framework/src/interfaces/PostprocessorInterface.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  framework/src/userobject/UserObjectInterface.C
  framework/src/variables/MooseVariableFV.C
  framework/src/vectorpostprocessors/VectorPostprocessorInterface.C
  modules/doc/config.yml
  test/tests/fviks/one-var-diffusion/no-ik.i
  test/tests/fviks/one-var-diffusion/test.i
  test/tests/fviks/one-var-diffusion/test.py
  test/tests/fviks/one-var-diffusion/tests
  test/tests/fvkernels/block-restriction/tests
Labels: PR: Failed but allowed

#17425 Allow multiple element sides on same sideset for elemental boundary auxkernel
  framework/include/auxkernels/AuxKernel.h
  framework/src/auxkernels/AuxKernel.C
  test/tests/auxkernels/element_aux_boundary/tests
Labels: PR: Auto Merge

#17554 Restrict HFEM tests to when we have mumps
  test/tests/kernels/hfem/tests
Labels: PR: Auto Merge

#17553 Verify ray_tracing node and point neighbor routines
  modules/ray_tracing/src/raytracing/TraceRayTools.C
Labels: PR: Ready for Review/Merge

#17582 Clean RayTracingPackingUtils and make c++11 compatible
  modules/ray_tracing/include/utils/RayTracingPackingUtils.h
  modules/ray_tracing/src/raytracing/Ray.C
Labels: P: normal

#17584 Add array body force kernel
  framework/doc/content/source/kernels/ArrayBodyForce.md
  framework/include/kernels/ArrayBodyForce.h
  framework/src/kernels/ArrayBodyForce.C
  test/tests/kernels/array_kernels/array_body_force.i
  test/tests/kernels/array_kernels/gold/array_body_force_out.e
  test/tests/kernels/array_kernels/tests
Labels: P: normal

#17559 Geochemistry: can use non-mole units for kinetic initial conditions
  modules/combined/examples/geochem-porous_flow/forge/aquifer_geochemistry.i
  modules/combined/examples/geochem-porous_flow/forge/kinetic.i
  modules/combined/examples/geochem-porous_flow/forge/natural_reservoir.i
  modules/combined/examples/geochem-porous_flow/forge/reservoir_and_water_3.i
  modules/combined/examples/geochem-porous_flow/geotes_2D/aquifer_geochemistry.i
  modules/combined/examples/geochem-porous_flow/geotes_2D/aquifer_un_quartz_geochemistry.i
  modules/geochemistry/doc/content/media/geochemistry/quartz_dissolution.png
  modules/geochemistry/doc/content/modules/geochemistry/tests_and_examples/kinetic_albite.md
  modules/geochemistry/doc/content/modules/geochemistry/theory/index.md
  modules/geochemistry/doc/content/source/userobjects/GeochemistryKineticRate.md
  modules/geochemistry/include/utils/GeochemicalSystem.h
  modules/geochemistry/src/actions/AddSpatialReactionSolverAction.C
  modules/geochemistry/src/actions/AddTimeDependentReactionSolverAction.C
  modules/geochemistry/src/userobjects/GeochemistrySpatialReactor.C
  modules/geochemistry/src/userobjects/GeochemistryTimeDependentReactor.C
  modules/geochemistry/src/userobjects/GeochemistryTimeIndependentReactor.C
  modules/geochemistry/src/utils/GeochemicalSystem.C
  modules/geochemistry/test/tests/geochemistry_console_output/console.i
  modules/geochemistry/test/tests/geochemistry_quantity_aux/except5.i
  modules/geochemistry/test/tests/geochemistry_quantity_aux/kinetic_moles.i
  modules/geochemistry/test/tests/geochemistry_quantity_aux/kinetic_rate.i
  modules/geochemistry/test/tests/kinetics/gold/kinetic_albite_out.csv
  modules/geochemistry/test/tests/kinetics/gold/quartz_deposition_out.csv
  modules/geochemistry/test/tests/kinetics/gold/quartz_dissolution_out.csv
  modules/geochemistry/test/tests/kinetics/kinetic_albite.i
  modules/geochemistry/test/tests/kinetics/quartz_deposition.i
  modules/geochemistry/test/tests/kinetics/quartz_dissolution.i
  modules/geochemistry/test/tests/time_dependent_reactions/flushing.i
  modules/geochemistry/test/tests/time_dependent_reactions/flushing_case1.i
  modules/geochemistry/test/tests/time_dependent_reactions/flushing_case2.i
  modules/geochemistry/test/tests/time_dependent_reactions/flushing_case3.i
  modules/geochemistry/unit/include/GeochemicalSystemTest.h
  modules/geochemistry/unit/src/GeochemicalSolverTest.C
  modules/geochemistry/unit/src/GeochemicalSystemTest.C
Labels: P: normal

#17563 Add fluid properties for sodium.
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/source/userobjects/SodiumSaturationFluidProperties.md
  modules/fluid_properties/include/userobjects/SodiumSaturationFluidProperties.h
  modules/fluid_properties/src/userobjects/SodiumSaturationFluidProperties.C
  modules/fluid_properties/unit/include/SodiumSaturationFluidPropertiesTest.h
  modules/fluid_properties/unit/src/SodiumSaturationFluidPropertiesTest.C
Labels: P: normal

#17420 Add a PID controller for basic tuning / search / optimization
  framework/doc/content/source/controls/PIDTransientControl.md
  framework/include/controls/PIDTransientControl.h
  framework/src/controls/PIDTransientControl.C
  test/src/timesteppers/TimeSequenceStepperFailTest.C
  test/tests/controls/pid_control/gold/out.csv
  test/tests/controls/pid_control/gold/picard_out.csv
  test/tests/controls/pid_control/gold/picard_resets_out.csv
  test/tests/controls/pid_control/gold/pp_out.csv
  test/tests/controls/pid_control/gold/windup_out.csv
  test/tests/controls/pid_control/pid_control.i
  test/tests/controls/pid_control/pid_pp_control.i
  test/tests/controls/pid_control/pid_pp_control_subapp.i
  test/tests/controls/pid_control/tests
Labels: P: normal

#17555 Update PR template to align with coming changes to SQA process
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: P: normal

#17248 Allow target_boundary for elemental nearest point transfers
  framework/include/transfers/MultiAppNearestNodeTransfer.h
  framework/src/transfers/MultiAppNearestNodeTransfer.C
  test/tests/transfers/multiapp_nearest_node_transfer/boundary_elemental_master.i
  test/tests/transfers/multiapp_nearest_node_transfer/boundary_elemental_sub.i
  test/tests/transfers/multiapp_nearest_node_transfer/gold/boundary_elemental_master_out.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/boundary_elemental_master_out_sub0.e
  test/tests/transfers/multiapp_nearest_node_transfer/tests
Labels: P: normal

#17653 Allow for multiple timestep limiting functions
  framework/include/timesteppers/IterationAdaptiveDT.h
  framework/src/timesteppers/IterationAdaptiveDT.C
  test/tests/time_steppers/iteration_adaptive/gold/multi_piecewise_linear_function_change.csv
  test/tests/time_steppers/iteration_adaptive/gold/multi_piecewise_linear_function_point.csv
  test/tests/time_steppers/iteration_adaptive/multi_piecewise_linear.i
  test/tests/time_steppers/iteration_adaptive/tests
Labels: PR: Failed but allowed

#17457 Add Parameter to Enable Final Jacobian Testing
  modules/tensor_mechanics/test/tests/ad_anisotropic_creep/tests
  python/TestHarness/testers/PetscJacobianTester.py
Labels: P: normal

#17679 Revert "Allow target_boundary for elemental nearest point transfers"
  framework/include/transfers/MultiAppNearestNodeTransfer.h
  framework/src/transfers/MultiAppNearestNodeTransfer.C
  test/tests/transfers/multiapp_nearest_node_transfer/boundary_elemental_master.i
  test/tests/transfers/multiapp_nearest_node_transfer/boundary_elemental_sub.i
  test/tests/transfers/multiapp_nearest_node_transfer/gold/boundary_elemental_master_out.e
  test/tests/transfers/multiapp_nearest_node_transfer/gold/boundary_elemental_master_out_sub0.e
  test/tests/transfers/multiapp_nearest_node_transfer/tests
Labels: PR: Failed but allowed

#17276 Mar. 2021 news
  modules/doc/content/citing.md
  modules/doc/content/newsletter/2021_03.md
  modules/doc/content/newsletter/2021_04.md
  modules/doc/content/newsletter/2021_05.md
  modules/doc/content/newsletter/index.md
Labels: P: normal

#17672 Fix array variable relaxation in Picard iteration
  framework/include/loops/AllLocalDofIndicesThread.h
  framework/src/executioners/PicardSolve.C
  framework/src/executioners/Transient.C
  framework/src/kernels/ArrayDiffusion.C
  framework/src/kernels/ArrayTimeDerivative.C
  framework/src/loops/AllLocalDofIndicesThread.C
  framework/src/multiapps/TransientMultiApp.C
  framework/src/postprocessors/GreaterThanLessThanPostprocessor.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  modules/contact/src/postprocessors/ContactDOFSetSize.C
  test/include/auxkernels/ArrayQuotientAux.h
  test/src/auxkernels/ArrayQuotientAux.C
  test/tests/multiapps/relaxation/gold/picard_relaxed_array_master_out.e
  test/tests/multiapps/relaxation/picard_relaxed_array_master.i
  test/tests/multiapps/relaxation/picard_relaxed_array_sub.i
  test/tests/multiapps/relaxation/picard_relaxed_master.i
  test/tests/multiapps/relaxation/tests
Labels: PR: Failed but allowed

#17694 Added PostprocessorInterface to InitialConditionBase
  framework/include/ics/InitialConditionBase.h
  framework/src/ics/InitialConditionBase.C
  modules/doc/content/newsletter/2021_05.md
  test/include/ics/PostprocessorIC.h
  test/src/ics/PostprocessorIC.C
  test/tests/ics/postprocessor_interface/gold/postprocessor_interface_out.csv
  test/tests/ics/postprocessor_interface/postprocessor_interface.i
  test/tests/ics/postprocessor_interface/tests
Labels: PR: Failed but allowed

#17697 Slight change to mortar segment generation
  framework/src/constraints/AutomaticMortarGeneration.C
Labels: PR: Auto Merge, PR: Failed but allowed

#17706 Fix a memory issue revealed by a test in #17672
  framework/include/interfaces/Coupleable.h
  framework/src/interfaces/Coupleable.C
Labels: PR: Auto Merge, PR: Failed but allowed

#17669 Fix comments in template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Failed but allowed

#17698 CONSTANT MONOMIAL support for MultiAppPostprocessorInterpolationTransfer
  framework/include/transfers/MultiAppPostprocessorInterpolationTransfer.h
  framework/src/transfers/MultiAppPostprocessorInterpolationTransfer.C
  test/tests/transfers/multiapp_postprocessor_interpolation_transfer/gold/constant_monomial.e
  test/tests/transfers/multiapp_postprocessor_interpolation_transfer/tests
Labels: PR: Failed but allowed

#17714 Fix typo introduced in previous commit
  modules/doc/content/help/inl/hpc_remote.md
Labels: PR: Failed but allowed

#17596 More nomenclature improvements
  modules/contact/test/tests/mechanical_constraint/tests
  test/tests/transfers/multiapp_userobject_transfer/restricted_elem_master.i
  test/tests/transfers/multiapp_userobject_transfer/restricted_elem_sub.i
  test/tests/transfers/multiapp_userobject_transfer/restricted_node_master.i
  test/tests/transfers/multiapp_userobject_transfer/restricted_node_sub.i
Labels: PR: Ready for Review/Merge

#17606 Additional material property output options
  framework/doc/content/source/kernels/ADMaterialPropertyValue.md
  framework/include/kernels/MaterialPropertyValue.h
  framework/src/kernels/MaterialPropertyValue.C
  modules/tensor_mechanics/include/actions/TensorMechanicsAction.h
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
  modules/tensor_mechanics/test/tests/action/gold/material_output_first_lagrange_automatic_out.e
  modules/tensor_mechanics/test/tests/action/gold/material_output_first_lagrange_manual_out.e
  modules/tensor_mechanics/test/tests/action/material_output_first_lagrange_automatic.i
  modules/tensor_mechanics/test/tests/action/material_output_first_lagrange_manual.i
  modules/tensor_mechanics/test/tests/action/tests
Labels: PR: Failed but allowed
