Repository idaholab/moose, pull requests merged in 2022-05, with the labels that each got.

#20927 Couple pressure from flux model
  modules/combined/test/tests/gap_heat_transfer_mortar/finite-2d/closed_gap_thermomechanical_mortar_contact.i
  modules/combined/test/tests/gap_heat_transfer_mortar/finite-2d/varied_pressure_thermomechanical_mortar.i
  modules/combined/test/tests/gap_heat_transfer_mortar/small-2d/closed_gap_pressure_dependent_thermal_contact.i
  modules/combined/test/tests/gap_heat_transfer_mortar/small-2d/multi_component_mortar_thermal_conduction.i
  modules/combined/test/tests/gap_heat_transfer_mortar/small-2d/open_gap_pressure_dependent.i
  modules/heat_conduction/include/constraints/ModularGapConductanceConstraint.h
  modules/heat_conduction/include/userobjects/GapFluxModelPressureDependentConduction.h
  modules/heat_conduction/src/constraints/ModularGapConductanceConstraint.C
  modules/heat_conduction/src/userobjects/GapFluxModelBase.C
  modules/heat_conduction/src/userobjects/GapFluxModelPressureDependentConduction.C
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/closed_gap_prescribed_pressure.i
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/error_check_missing_pressure.i
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/tests
Labels: PR: Failed but allowed

#20910 Output n_constrained_dofs
  framework/include/reporters/MeshInfo.h
  framework/src/outputs/ConsoleUtils.C
  framework/src/reporters/MeshInfo.C
  test/tests/reporters/mesh_info/gold/mesh_info_out.json
  test/tests/reporters/mesh_info/gold/mesh_info_out.json.1
Labels: C: Framework, T: task, PR: Failed but allowed

#20907 Fix up PerfGraph when creating sub-apps
  framework/src/multiapps/MultiApp.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20908 Make all cloned repos marked as safe for Git in Docker builds
  docker_ci/Dockerfile
Labels: PR: Failed but allowed

#20937 Navier-stokes test robustness fixups
  modules/navier_stokes/test/tests/finite_volume/ins/advection-schemes/gold/min_mod.e
  modules/navier_stokes/test/tests/finite_volume/ins/advection-schemes/gold/quick.e
  modules/navier_stokes/test/tests/finite_volume/ins/advection-schemes/gold/quick_test_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/advection-schemes/gold/sou.e
  modules/navier_stokes/test/tests/finite_volume/ins/advection-schemes/gold/vanLeer.e
  modules/navier_stokes/test/tests/finite_volume/ins/advection-schemes/test.i
  modules/navier_stokes/test/tests/finite_volume/ins/advection-schemes/tests
  modules/navier_stokes/test/tests/finite_volume/ins/mixing_length_total_viscosity_material/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20645 Add PatternedHexPeripheralModifier and TransitionLayerTools
  framework/doc/content/source/meshgenerators/FillBetweenPointVectorsGenerator.md
  framework/doc/content/source/meshgenerators/FillBetweenSidesetsGenerator.md
  framework/doc/content/source/utils/FillBetweenPointVectorsTools.md
  framework/include/meshgenerators/FillBetweenPointVectorsGenerator.h
  framework/include/meshgenerators/FillBetweenSidesetsGenerator.h
  framework/include/utils/FillBetweenPointVectorsTools.h
  framework/include/utils/MooseMeshUtils.h
  framework/src/meshgenerators/FillBetweenPointVectorsGenerator.C
  framework/src/meshgenerators/FillBetweenSidesetsGenerator.C
  framework/src/utils/FillBetweenPointVectorsTools.C
  framework/src/utils/MooseMeshUtils.C
  modules/reactor/doc/content/source/meshgenerators/PatternedHexPeripheralModifier.md
  modules/reactor/include/meshgenerators/PatternedHexMeshGenerator.h
  modules/reactor/include/meshgenerators/PatternedHexPeripheralModifier.h
  modules/reactor/include/meshgenerators/PeripheralRingMeshGenerator.h
  modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
  modules/reactor/src/meshgenerators/PatternedHexMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedHexPeripheralModifier.C
  modules/reactor/src/meshgenerators/PeripheralRingMeshGenerator.C
  modules/reactor/src/meshgenerators/PolygonMeshGeneratorBase.C
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/patterned_in.e
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/single_hex_in.e
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/single_hex_pin_id_exodus_1.e
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/single_hex_pin_id_exodus_2.e
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/patterned.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/single_hex.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/single_hex_pin_id.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/tests
  test/tests/meshgenerators/fill_between_point_vectors_generator/bow.i
  test/tests/meshgenerators/fill_between_point_vectors_generator/bow_quad.i
  test/tests/meshgenerators/fill_between_point_vectors_generator/gold/bow_auto_bias_in.e
  test/tests/meshgenerators/fill_between_point_vectors_generator/gold/bow_in.e
  test/tests/meshgenerators/fill_between_point_vectors_generator/gold/bow_man_bias_in.e
  test/tests/meshgenerators/fill_between_point_vectors_generator/gold/bow_quad_in.e
  test/tests/meshgenerators/fill_between_point_vectors_generator/tests
  test/tests/meshgenerators/fill_between_sidesets_generator/gold/squares_auto_bias_in.e
  test/tests/meshgenerators/fill_between_sidesets_generator/gold/squares_bias_in.e
  test/tests/meshgenerators/fill_between_sidesets_generator/gold/squares_in.e
  test/tests/meshgenerators/fill_between_sidesets_generator/gold/squares_squares_stitched_in.e
  test/tests/meshgenerators/fill_between_sidesets_generator/squares.i
  test/tests/meshgenerators/fill_between_sidesets_generator/tests
Labels: PR: Failed but allowed

#20774 Exposing the ability to read TetGen meshes in MOOSE.
  framework/src/meshgenerators/FileMeshGenerator.C
  test/tests/mesh/tetgen/example1.ele
  test/tests/mesh/tetgen/example1.node
  test/tests/mesh/tetgen/gold/tetgen_mesh_in.e
  test/tests/mesh/tetgen/tests
  test/tests/mesh/tetgen/tetgen_mesh.i
Labels: PR: Ready for review/merge

#20945 Unify `[AD]ComputeThermalExpansionEigenstrainBase`
  modules/tensor_mechanics/doc/content/source/materials/ADComputeDilatationThermalExpansionFunctionEigenstrain.md
  modules/tensor_mechanics/doc/content/source/materials/ADComputeInstantaneousThermalExpansionFunctionEigenstrain.md
  modules/tensor_mechanics/include/materials/ADComputeDilatationThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ADComputeDilatationThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ADComputeInstantaneousThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ADComputeMeanThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ADComputeMeanThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ADComputeThermalExpansionEigenstrain.h
  modules/tensor_mechanics/include/materials/ADComputeThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ComputeDilatationThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ComputeDilatationThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeInstantaneousThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeMeanThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ComputeMeanThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/src/materials/ADComputeDilatationThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ADComputeDilatationThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ADComputeInstantaneousThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ADComputeMeanThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ADComputeThermalExpansionEigenstrain.C
  modules/tensor_mechanics/src/materials/ADComputeThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ComputeDilatationThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ComputeDilatationThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeInstantaneousThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C
Labels: PR: Ready for review/merge

#20965 Construct the PerfGraph after the Action warehouse and factory
  framework/include/base/MooseApp.h
  framework/src/base/MooseApp.C
Labels: PR: Ready for review/merge

#20930 Reduce NEAMS Workbench schema size in SONDefinitionFormatter
  framework/src/outputs/formatters/SONDefinitionFormatter.C
  test/tests/outputs/format/tests
Labels: PR: Ready for review/merge

#20982 Improved API for thermal eigenstrains
  framework/include/functions/Function.h
  framework/include/utils/CastDualNumber.h
  framework/include/utils/LinearInterpolation.h
  framework/src/functions/Function.C
  framework/src/utils/LinearInterpolation.C
  modules/tensor_mechanics/doc/content/source/materials/ADComputeThermalExpansionEigenstrain.md
  modules/tensor_mechanics/doc/content/source/materials/ComputeThermalExpansionEigenstrain.md
  modules/tensor_mechanics/include/materials/ADComputeMeanThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ADComputeThermalExpansionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeDilatationThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ComputeDilatationThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeInstantaneousThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeMeanThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ComputeMeanThermalExpansionFunctionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrain.h
  modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrainBeam.h
  modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrainBeamBase.h
  modules/tensor_mechanics/src/materials/ADComputeMeanThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ADComputeThermalExpansionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeDilatationThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ComputeDilatationThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeInstantaneousThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrain.C
  modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBeam.C
  modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBeamBase.C
  modules/tensor_mechanics/test/tests/domain_integral_thermal/gold/j_integral_2d_ctefunc_out.csv
  modules/tensor_mechanics/test/tests/thermal_expansion/tests
  unit/src/LinearInterpolationTest.C
Labels: PR: Ready for review/merge

#21005 Add conda_recipe generator into moose repo
  conda/empty_shell/meta.yaml
  conda/generate_recipe.sh
  conda/mpich/conda_build_config.yaml
  conda/template/build.sh
  conda/template/conda_build_config.yaml
  conda/template/meta.yaml
Labels: PR: Failed but allowed

#21010 Add ADReaction, ADCoefReaction, and combine CoupledForce objects
  framework/doc/content/source/kernels/ADCoupledForce.md
  framework/doc/content/source/kernels/CoefReaction.md
  framework/doc/content/source/kernels/CoupledForce.md
  framework/doc/content/source/kernels/Reaction.md
  framework/include/kernels/ADCoupledForce.h
  framework/include/kernels/CoefReaction.h
  framework/include/kernels/CoupledForce.h
  framework/include/kernels/Reaction.h
  framework/src/kernels/ADCoupledForce.C
  framework/src/kernels/CoefReaction.C
  framework/src/kernels/CoupledForce.C
  framework/src/kernels/Reaction.C
  test/tests/kernels/ad_coupled_force/tests
  test/tests/kernels/ad_reaction/ad_reaction.i
  test/tests/kernels/ad_reaction/gold/ad_coef_reaction_out.e
  test/tests/kernels/ad_reaction/gold/ad_reaction_out.e
  test/tests/kernels/ad_reaction/tests
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#20954 Remove vertex-based stencil from FV.
  framework/doc/content/finite_volumes/fv_design.md
  framework/doc/content/source/variables/MooseVariableFV.md
  framework/include/mesh/FaceInfo.h
  framework/include/utils/MathFVUtils.h
  framework/include/variables/MooseVariableFV.h
  framework/src/mesh/FaceInfo.C
  framework/src/variables/MooseVariableFV.C
  test/tests/fvkernels/fv_adapt/gold/steady-adapt_out.e
  test/tests/fvkernels/fv_adapt/steady-adapt.i
  test/tests/fvkernels/fv_adapt/tests
  test/tests/fvkernels/mms/grad-reconstruction/extended-cartesian.i
  test/tests/fvkernels/mms/grad-reconstruction/gold/extended-cartesian_out.e
  test/tests/fvkernels/mms/grad-reconstruction/tests
Labels: PR: Failed but allowed

#21029 Remove parameter, improve error check
  framework/include/utils/FunctionParserUtils.h
  framework/src/utils/FunctionParserUtils.C
  test/tests/materials/derivative_material_interface/tests
Labels: PR: Failed but allowed

#21032 Call base class single-parameter version of set()
  framework/include/utils/InputParameters.h
Labels: PR: Failed but allowed

#21006 Data file info output
  framework/doc/content/source/base/MooseObject.md
  framework/include/base/MooseObject.h
  framework/src/base/MooseObject.C
  framework/src/base/Registry.C
  modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C
  test/src/userobjects/DataFileNameTest.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20993 Added component to couple 2D heat structures
  CODEOWNERS
  modules/doc/content/newsletter/2022_05.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/bcs/HeatStructure2DCouplerBC.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/bcs/HeatStructure2DCouplerRZBC.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/HeatStructure2DCoupler.md
  modules/thermal_hydraulics/include/bcs/HeatStructure2DCouplerBC.h
  modules/thermal_hydraulics/include/bcs/HeatStructure2DCouplerRZBC.h
  modules/thermal_hydraulics/include/components/HeatStructure2DCoupler.h
  modules/thermal_hydraulics/include/components/HeatStructureBase.h
  modules/thermal_hydraulics/include/utils/MeshAlignment2D2D.h
  modules/thermal_hydraulics/src/bcs/HeatStructure2DCouplerBC.C
  modules/thermal_hydraulics/src/bcs/HeatStructure2DCouplerRZBC.C
  modules/thermal_hydraulics/src/components/HeatStructure2DCoupler.C
  modules/thermal_hydraulics/src/components/HeatStructureBase.C
  modules/thermal_hydraulics/src/utils/MeshAlignment2D2D.C
  modules/thermal_hydraulics/test/tests/components/heat_structure_2d_coupler/gold/cylindrical.e
  modules/thermal_hydraulics/test/tests/components/heat_structure_2d_coupler/gold/plate.e
  modules/thermal_hydraulics/test/tests/components/heat_structure_2d_coupler/heat_structure_2d_coupler.i
  modules/thermal_hydraulics/test/tests/components/heat_structure_2d_coupler/tests
Labels: PR: Failed but allowed

#21052 Make data file interface and add it to Action
  framework/doc/content/source/base/MooseObject.md
  framework/doc/content/source/interfaces/DataFileInterface.md
  framework/include/actions/Action.h
  framework/include/base/MooseObject.h
  framework/include/interfaces/DataFileInterface.h
  framework/src/actions/Action.C
  framework/src/base/MooseObject.C
  framework/src/interfaces/DataFileInterface.C
Labels: PR: Failed but allowed

#20550 Allow flexibility in how cli_args for MultiApps are handled
  framework/include/multiapps/MultiApp.h
  framework/src/multiapps/MultiApp.C
  test/include/multiapps/OverrideCliArgs.h
  test/src/OverrideCliArgs.C
  test/tests/multiapps/override_cliargs/gold/primary_out_sub0.e
  test/tests/multiapps/override_cliargs/primary.i
  test/tests/multiapps/override_cliargs/sub.i
  test/tests/multiapps/override_cliargs/tests
Labels: PR: Failed but allowed

#21073 Check and Prepare Input Mesh in ElementDeletionGeneratorBase
  framework/src/meshgenerators/ElementDeletionGeneratorBase.C
  test/tests/meshgenerators/block_deletion_generator/block_deletion_not_prepared.i
  test/tests/meshgenerators/block_deletion_generator/gold/block_deletion_not_prepared_in.e
  test/tests/meshgenerators/block_deletion_generator/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#21106 Ensure node processor id consistency in `ExplodeMeshGenerator`
  framework/include/meshgenerators/ExplodeMeshGenerator.h
  framework/src/meshgenerators/ExplodeMeshGenerator.C
Labels: PR: Auto Merge

#21070 Fix hard-coded radial coordinate for INSAD
  modules/navier_stokes/include/materials/INSADMaterial.h
  modules/navier_stokes/src/materials/INSADMaterial.C
  modules/navier_stokes/test/tests/finite_element/ins/RZ_cone/ad-rz-displacements.i
  modules/navier_stokes/test/tests/finite_element/ins/RZ_cone/gold/ad-rz-displacements-laplace.e
  modules/navier_stokes/test/tests/finite_element/ins/RZ_cone/gold/ad-rz-displacements-traction.e
  modules/navier_stokes/test/tests/finite_element/ins/RZ_cone/tests
  modules/navier_stokes/test/tests/finite_element/ins/rz-x-axial-coord/gold/pipe-flow_out.e
  modules/navier_stokes/test/tests/finite_element/ins/rz-x-axial-coord/pipe-flow.i
  modules/navier_stokes/test/tests/finite_element/ins/rz-x-axial-coord/tests
Labels: PR: Failed but allowed

#21128 Detect installed AD header
  framework/src/utils/ADFParser.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21136 Remove dof maps from FaceInfo
  framework/include/mesh/FaceInfo.h
  framework/src/mesh/MooseMesh.C
  test/include/vectorpostprocessors/TestFaceInfo.h
  test/src/vectorpostprocessors/TestFaceInfo.C
  test/tests/mesh/face_info/gold/face_info_quads_out_face_info_0001.csv
  test/tests/mesh/face_info/gold/face_info_tri_out_face_info_0001.csv
  test/tests/mesh/face_info/gold/face_info_two_region_quads_out_face_info_1_0001.csv
  test/tests/mesh/face_info/gold/face_info_two_region_quads_out_face_info_2_0001.csv
  test/tests/mesh/face_info/gold/face_info_two_region_quads_out_face_info_3_0001.csv
Labels: PR: Auto Merge

#21142 Consistent Extrudability for FillBetweenPointVectorsTools
  framework/include/utils/FillBetweenPointVectorsTools.h
  framework/src/utils/FillBetweenPointVectorsTools.C
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/patterned_in.e
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/single_hex_in.e
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/single_hex_pin_id_exodus_1.e
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/gold/single_hex_pin_id_exodus_2.e
  test/tests/meshgenerators/fill_between_point_vectors_generator/gold/bow_quad_in.e
  test/tests/meshgenerators/fill_between_sidesets_generator/gold/squares_bias_in.e
Labels: PR: Failed but allowed

#20997 Changes to ViscoPlasticityStressUpdateBase and SingleVariableReturnMappingSolution to help downstream development
  modules/combined/test/include/materials/ADPowerLawCreepExceptionTest.h
  modules/combined/test/include/materials/PowerLawCreepExceptionTest.h
  modules/combined/test/src/materials/ADPowerLawCreepExceptionTest.C
  modules/combined/test/src/materials/PowerLawCreepExceptionTest.C
  modules/combined/test/tests/exception/ad.i
  modules/combined/test/tests/exception/mesh.e
  modules/combined/test/tests/exception/mesh.jou
  modules/combined/test/tests/exception/nonad.i
  modules/combined/test/tests/exception/tests
  modules/tensor_mechanics/include/materials/ADSingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/include/materials/RadialReturnStressUpdate.h
  modules/tensor_mechanics/include/materials/SingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/include/materials/ViscoplasticityStressUpdateBase.h
  modules/tensor_mechanics/src/materials/ADSingleVariableReturnMappingSolution.C
  modules/tensor_mechanics/src/materials/SingleVariableReturnMappingSolution.C
  modules/tensor_mechanics/test/include/materials/PowerLawCreepTest.h
  modules/tensor_mechanics/test/src/materials/PowerLawCreepTest.C
  modules/tensor_mechanics/test/tests/power_law_creep/ad_exception.i
  modules/tensor_mechanics/test/tests/power_law_creep/nonad_bounds.i
  modules/tensor_mechanics/test/tests/power_law_creep/nonad_exception.i
  modules/tensor_mechanics/test/tests/power_law_creep/tests
  modules/tensor_mechanics/test/tests/substepping/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#21160 Nodal constraint sparsity
  framework/src/constraints/NodalConstraint.C
  test/tests/constraints/equal_value_boundary_constraint/equal_value_boundary_constraint_test.i
Labels: PR: Failed but allowed

#21045 Implement variable check for some boundary restricted objects
  framework/include/auxkernels/AuxKernel.h
  framework/include/geomsearch/GeometricSearchInterface.h
  framework/include/interfaces/BoundaryRestrictable.h
  framework/include/loops/BoundaryElemIntegrityCheckThread.h
  framework/include/loops/BoundaryNodeIntegrityCheckThread.h
  framework/include/problems/FEProblemBase.h
  framework/include/systems/AuxiliarySystem.h
  framework/include/variables/MooseVariableDependencyInterface.h
  framework/include/variables/NeighborCoupleableMooseVariableDependencyIntermediateInterface.h
  framework/include/warehouses/ExecuteMooseObjectWarehouse.h
  framework/include/warehouses/MooseObjectWarehouseBase.h
  framework/src/auxkernels/AuxNodalScalarKernel.C
  framework/src/bcs/ADNodalBC.C
  framework/src/bcs/ArrayNodalBC.C
  framework/src/bcs/NodalBC.C
  framework/src/bcs/VectorNodalBC.C
  framework/src/fvbcs/FVBoundaryCondition.C
  framework/src/geomsearch/GeometricSearchInterface.C
  framework/src/indicators/Indicator.C
  framework/src/interfaces/BoundaryRestrictable.C
  framework/src/kernels/NodalScalarKernel.C
  framework/src/loops/BoundaryElemIntegrityCheckThread.C
  framework/src/loops/BoundaryNodeIntegrityCheckThread.C
  framework/src/markers/Marker.C
  framework/src/materials/MaterialBase.C
  framework/src/problems/FEProblemBase.C
  framework/src/userobject/ElementUserObject.C
  framework/src/userobject/InterfaceUserObjectBase.C
  framework/src/userobject/InternalSideUserObject.C
  framework/src/userobject/NodalUserObject.C
  framework/src/userobject/SideUserObject.C
  framework/src/variables/CoupleableMooseVariableDependencyIntermediateInterface.C
  framework/src/variables/MooseVariableDependencyInterface.C
  modules/doc/content/framework_development/sanity_checking.md
  modules/heat_conduction/include/userobjects/GrayLambertSurfaceRadiationBase.h
  modules/phase_field/src/postprocessors/AverageGrainVolume.C
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
  modules/phase_field/src/vectorpostprocessors/FeatureVolumeVectorPostprocessor.C
  modules/rdg/src/userobjects/ElementLoopUserObject.C
  modules/thermal_hydraulics/include/bcs/HeatFluxBaseBC.h
  test/tests/misc/boundary_variable_check/test.i
  test/tests/misc/boundary_variable_check/tests
  test/tests/misc/boundary_variable_check/three-domains/test.i
  test/tests/misc/boundary_variable_check/three-domains/tests
Labels: PR: Failed but allowed

#21145 Allow LinearNodalConstraint to be run with distributed mesh
  framework/src/constraints/LinearNodalConstraint.C
Labels: PR: Failed but allowed

#21168 Add Apple Silicon option to getting started instructions for mamba
  modules/doc/content/getting_started/installation/install_miniconda.md
Labels: PR: Failed but allowed, PR: Auto Merge

#21067 Add option to turn off flow equations to NSFV action
  modules/navier_stokes/include/actions/NSFVAction.h
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/test/tests/finite_volume/ins/action/errors/2d-rc-error-action.i
  modules/navier_stokes/test/tests/finite_volume/ins/action/errors/tests
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-mixing-length-action.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-scalar-transport-action.i
  modules/navier_stokes/test/tests/finite_volume/ins/multiapp-scalar-transport/scalar-transport_action.i
  modules/navier_stokes/test/tests/finite_volume/ins/multiapp-scalar-transport/tests
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_mdot-action.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity-action.i
Labels: PR: Ready for review/merge

#21163 Fix Faulty Elements On the Fly in FancyExtruderGenerator
  framework/include/meshgenerators/FancyExtruderGenerator.h
  framework/src/meshgenerators/FancyExtruderGenerator.C
  test/tests/meshgenerators/fancy_extruder_generator/elem_flip.i
  test/tests/meshgenerators/fancy_extruder_generator/gold/elem_flip_in.e
  test/tests/meshgenerators/fancy_extruder_generator/gold/gen_extrude_flip_in.e
  test/tests/meshgenerators/fancy_extruder_generator/tests
Labels: PR: Failed but allowed

#21169 Adds minimum changes to address the missing base name parameter issue…
  modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeElasticityTensorConstantRotationCP.C
  modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeMultipleCrystalPlasticityStress.C
  modules/tensor_mechanics/test/tests/crystal_plasticity/stress_update_material_based/bicrystal_test.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/stress_update_material_based/gold/bicrystal_test_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/stress_update_material_based/tests
Labels: PR: Failed but allowed
