Repository idaholab/moose, pull requests merged in 2022-03, with the labels that each got.

#20388 Improvements to mortar friction
  modules/contact/doc/content/source/auxkernels/MortarFrictionalStateAux.md
  modules/contact/include/auxkernels/MortarFrictionalStateAux.h
  modules/contact/src/auxkernels/MortarFrictionalStateAux.C
  modules/contact/src/constraints/ComputeDynamicFrictionalForceLMMechanicalContact.C
  modules/contact/src/constraints/ComputeFrictionalForceLMMechanicalContact.C
  modules/contact/test/tests/mortar_aux_kernels/frictional-mortar-3d-status.i
  modules/contact/test/tests/mortar_aux_kernels/gold/frictional-mortar-3d-status_out.e
  modules/contact/test/tests/mortar_aux_kernels/tests
Labels: PR: Failed but allowed

#20398 Add February 2022 news
  modules/doc/content/newsletter/2022_01.md
  modules/doc/content/newsletter/2022_02.md
  modules/doc/content/newsletter/2022_03.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#20418 Option to explicitly provide mardown file location for objects
  python/MooseDocs/extensions/appsyntax.py
  python/moosesyntax/get_moose_syntax_tree.py
  python/moosesyntax/test/test_get_moose_syntax_tree.py
Labels: PR: Failed but allowed

#20440 Remove duplicate tests in STM
  modules/stochastic_tools/test/tests/transfers/errors/master_missing_control.i
  modules/stochastic_tools/test/tests/transfers/errors/master_multiapp_type_error.i
  modules/stochastic_tools/test/tests/transfers/errors/master_num_parameters_wrong.i
  modules/stochastic_tools/test/tests/transfers/errors/master_wrong_control.i
  modules/stochastic_tools/test/tests/transfers/errors/sub.i
  modules/stochastic_tools/test/tests/transfers/errors/sub_missing_control.i
  modules/stochastic_tools/test/tests/transfers/errors/sub_wrong_control.i
  modules/stochastic_tools/test/tests/transfers/errors/tests
  modules/stochastic_tools/test/tests/transfers/sampler_transfer/errors/tests
Labels: PR: Failed but allowed

#20442 added dof_id
  framework/src/reporters/AccumulateReporter.C
Labels: PR: Failed but allowed

#20447 Temporary fixes in MOOSE for nodal normals threading failures
  framework/include/userobject/NodalNormalsPreprocessor.h
  framework/src/userobject/NodalNormalsCorner.C
  framework/src/userobject/NodalNormalsEvaluator.C
  framework/src/userobject/NodalNormalsPreprocessor.C
Labels: PR: Failed but allowed, PR: Auto Merge

#20444 Added tests for deprecated components in THM
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/FreeBoundary.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/GateValve.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/HeatGeneration.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/HeatSourceVolumetric.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/JunctionOneToOne.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/PrescribedReactorPower.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/SolidWall.md
  modules/thermal_hydraulics/src/components/GateValve.C
  modules/thermal_hydraulics/src/components/HeatGeneration.C
  modules/thermal_hydraulics/src/components/JunctionOneToOne.C
  modules/thermal_hydraulics/test/tests/components/deprecated/free_boundary.i
  modules/thermal_hydraulics/test/tests/components/deprecated/gate_valve.i
  modules/thermal_hydraulics/test/tests/components/deprecated/heat_generation.i
  modules/thermal_hydraulics/test/tests/components/deprecated/heat_source_volumetric.i
  modules/thermal_hydraulics/test/tests/components/deprecated/junction_one_to_one.i
  modules/thermal_hydraulics/test/tests/components/deprecated/prescribed_reactor_power.i
  modules/thermal_hydraulics/test/tests/components/deprecated/solid_wall.i
  modules/thermal_hydraulics/test/tests/components/deprecated/tests
  modules/thermal_hydraulics/test/tests/components/prescribed_reactor_power/tests
  modules/thermal_hydraulics/test/tests/components/supersonic_inlet/err.i
  modules/thermal_hydraulics/test/tests/components/supersonic_inlet/tests
Labels: PR: Failed but allowed

#20449 Patch Yum mirror and bad exits in Docker builds
  docker_ci/Dockerfile
  docker_ci/apt_installs.sh
  docker_ci/install_packages.sh
  docker_ci/yum_installs.sh
Labels: PR: Failed but allowed

#20456 Add a parameter to control the initial normalization
  framework/include/problems/EigenProblem.h
  framework/src/executioners/Eigenvalue.C
  framework/src/problems/EigenProblem.C
  test/tests/problems/eigen_problem/initial_condition/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#20445 Declared controllable THM component parameters
  modules/thermal_hydraulics/src/base/FlowModel.C
  modules/thermal_hydraulics/src/components/FlowChannel1Phase.C
  modules/thermal_hydraulics/src/components/FlowChannelBase.C
  modules/thermal_hydraulics/src/components/GateValve1Phase.C
  modules/thermal_hydraulics/src/components/HSBoundarySpecifiedTemperature.C
  modules/thermal_hydraulics/src/components/HeatSourceFromTotalPower.C
  modules/thermal_hydraulics/src/components/HeatTransfer1PhaseBase.C
  modules/thermal_hydraulics/src/components/HeatTransferBase.C
  modules/thermal_hydraulics/src/components/HeatTransferFromSpecifiedTemperature1Phase.C
  modules/thermal_hydraulics/src/components/InletDensityVelocity1Phase.C
  modules/thermal_hydraulics/src/components/InletMassFlowRateTemperature1Phase.C
  modules/thermal_hydraulics/src/components/InletStagnationPressureTemperature1Phase.C
  modules/thermal_hydraulics/src/components/InletVelocityTemperature1Phase.C
  modules/thermal_hydraulics/src/components/Outlet1Phase.C
  modules/thermal_hydraulics/src/components/Pump1Phase.C
  modules/thermal_hydraulics/src/components/ShaftConnectedMotor.C
  modules/thermal_hydraulics/src/components/SimpleTurbine1Phase.C
  modules/thermal_hydraulics/src/components/TotalPower.C
  modules/thermal_hydraulics/src/userobjects/SolidMaterialProperties.C
Labels: PR: Failed but allowed

#20463 More convenience for NS Rayleigh PP
  framework/doc/content/source/auxkernels/DiffusionFluxAux.md
  framework/doc/content/source/meshgenerators/SideSetsFromNormalsGenerator.md
  framework/src/auxkernels/DiffusionFluxAux.C
  framework/src/auxkernels/ExtraElementIDAux.C
  framework/src/postprocessors/ElementExtremeMaterialProperty.C
  modules/navier_stokes/doc/content/source/postprocessors/RayleighNumber.md
  modules/navier_stokes/include/materials/GeneralFunctorFluidProps.h
  modules/navier_stokes/src/materials/GeneralFunctorFluidProps.C
  modules/navier_stokes/src/postprocessors/RayleighNumber.C
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/2d-transient.i
  modules/navier_stokes/test/tests/postprocessors/rayleigh/gold/natural_convection_out.csv
  modules/navier_stokes/test/tests/postprocessors/rayleigh/natural_convection.i
Labels: PR: Failed but allowed

#20332 Add wear depth to weighted gap for contact dynamics
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/src/systems/AuxiliarySystem.C
  modules/contact/include/constraints/ComputeDynamicFrictionalForceLMMechanicalContact.h
  modules/contact/include/constraints/ComputeDynamicWeightedGapLMMechanicalContact.h
  modules/contact/src/auxkernels/MortarFrictionalPressureVectorAux.C
  modules/contact/src/constraints/ComputeDynamicFrictionalForceLMMechanicalContact.C
  modules/contact/src/constraints/ComputeDynamicWeightedGapLMMechanicalContact.C
  modules/contact/test/tests/mortar_aux_kernels/block-dynamics-aux-fretting-wear-test.i
  modules/contact/test/tests/mortar_aux_kernels/gold/block-dynamics-aux-fretting-wear-test-quick_out.e
  modules/contact/test/tests/mortar_aux_kernels/tests
  modules/contact/test/tests/mortar_dynamics/frictional-mortar-3d-dynamics-light-function.i
  modules/contact/test/tests/mortar_dynamics/gold/frictional-mortar-3d-dynamics-light-function_out.e
  modules/contact/test/tests/mortar_dynamics/tests
Labels: PR: Failed but allowed

#20457 Specializations of MooseADWrapper for std::array and MooseUtils::SemiDynamicVector
  framework/include/utils/MooseADWrapper.h
Labels: PR: Failed but allowed

#20423 Allow AnnularMeshGenerator to create constant-area elements.
  framework/doc/content/source/meshgenerators/AnnularMeshGenerator.md
  framework/include/meshgenerators/AnnularMeshGenerator.h
  framework/src/meshgenerators/AnnularMeshGenerator.C
  test/tests/meshgenerators/annular_mesh_generator/equal_area.i
  test/tests/meshgenerators/annular_mesh_generator/gold/equal_area_in.e
  test/tests/meshgenerators/annular_mesh_generator/tests
Labels: PR: Address comments, PR: Failed but allowed

#20492 Allow creation of magnitude functor property from vector functor
  framework/doc/content/source/auxkernels/FunctorElementalAux.md
  framework/doc/content/source/materials/VectorMagnitudeFunctorMaterial.md
  framework/include/auxkernels/FunctorElementalAux.h
  framework/include/materials/VectorMagnitudeFunctorMaterial.h
  framework/src/auxkernels/FunctorElementalAux.C
  framework/src/auxkernels/VectorVariableMagnitudeAux.C
  framework/src/materials/VectorMagnitudeFunctorMaterial.C
  modules/navier_stokes/src/auxkernels/PecletNumberFunctorAux.C
  modules/navier_stokes/src/auxkernels/ReynoldsNumberFunctorAux.C
  modules/navier_stokes/test/tests/auxkernels/peclet-number-functor-aux/fe-thermal.i
  modules/navier_stokes/test/tests/auxkernels/peclet-number-functor-aux/fv-thermal.i
  modules/navier_stokes/test/tests/auxkernels/reynolds-number-functor-aux/fe.i
  modules/navier_stokes/test/tests/auxkernels/reynolds-number-functor-aux/fv.i
  test/tests/materials/functor_properties/vector-magnitude/gold/vector-test_out.e
  test/tests/materials/functor_properties/vector-magnitude/test.i
  test/tests/materials/functor_properties/vector-magnitude/tests
  test/tests/materials/functor_properties/vector-magnitude/vector-test.i
Labels: PR: Failed but allowed

#20068 Doco fixes + INL cluster installation instructions
  framework/doc/content/source/actions/DisplayGhostingAction.md
  framework/doc/content/source/bcs/SinDirichletBC.md
  framework/doc/content/source/bcs/SinNeumannBC.md
  framework/doc/content/source/bcs/WeakGradientBC.md
  framework/doc/content/source/interfaces/SetupInterface.md
  framework/doc/content/source/markers/ComboMarker.md
  framework/doc/content/source/markers/ErrorToleranceMarker.md
  framework/doc/content/source/markers/OrientedBoxMarker.md
  framework/doc/content/source/markers/ValueRangeMarker.md
  framework/doc/content/source/markers/ValueThresholdMarker.md
  framework/doc/content/source/materials/ADDerivativeSumMaterial.md
  framework/doc/content/source/materials/DerivativeParsedMaterial.md
  framework/doc/content/source/materials/DerivativeSumMaterial.md
  modules/contact/doc/content/source/auxkernels/ContactPressureAux.md
  modules/contact/doc/content/source/auxkernels/MortarFrictionalPressureVectorAux.md
  modules/doc/content/getting_started/installation/hpc_install_moose.md
  modules/doc/content/getting_started/installation/index.md
  modules/doc/content/getting_started/installation/inl_hpc_install_moose.md
  modules/heat_conduction/doc/content/source/auxkernels/JouleHeatingHeatGeneratedAux.md
  modules/navier_stokes/doc/content/source/auxkernels/WallFunctionWallShearStressAux.md
  modules/navier_stokes/doc/content/source/auxkernels/WallFunctionYPlusAux.md
  modules/phase_field/doc/content/source/materials/ElasticEnergyMaterial.md
  modules/phase_field/doc/content/source/materials/GasFreeEnergyBase.md
  modules/phase_field/doc/content/source/materials/MixedSwitchingFunctionMaterial.md
  modules/phase_field/doc/content/source/materials/MultiBarrierFunctionMaterial.md
  modules/phase_field/doc/content/source/userobjects/SolutionRasterizer.md
  modules/xfem/doc/content/source/bcs/CrackTipEnrichmentCutOffBC.md
  modules/xfem/doc/content/source/kernels/CrackTipEnrichmentStressDivergenceTensors.md
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20518 Retain Subdomain Name Map in PeripheralRingMeshGenerator
  modules/reactor/src/meshgenerators/PeripheralRingMeshGenerator.C
  modules/reactor/test/tests/meshgenerators/peripheral_ring_mesh_generator/gold/core_ring_in.e
  modules/reactor/test/tests/meshgenerators/peripheral_ring_mesh_generator/gold/core_ring_preserved_in.e
Labels: PR: Failed but allowed

#20521 Adjust the PR label that new stalebot applies
  .github/workflows/stale.yml
Labels: PR: Auto Merge

#20348 Install examples
  framework/app.mk
  framework/include/base/MooseApp.h
  framework/include/utils/MooseUtils.h
  framework/moose.mk
  framework/src/base/MooseApp.C
  framework/src/utils/MooseUtils.C
  modules/doc/content/application_development/build_system.md
  python/TestHarness/TestHarness.py
  python/TestHarness/testers/RunApp.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/util.py
  test/tests/make_install/tests
  test/tests/parser/multiple_inputs/tests
  test/tests/usability/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20304 Add input parameter to force a new time step post function sync
  framework/doc/content/source/timesteppers/IterationAdaptiveDT.md
  framework/include/timesteppers/IterationAdaptiveDT.h
  framework/src/timesteppers/IterationAdaptiveDT.C
  test/tests/time_steppers/iteration_adaptive/adapt_tstep_grow_dtfunc.i
  test/tests/time_steppers/iteration_adaptive/adapt_tstep_grow_dtfunc_restart.i
  test/tests/time_steppers/iteration_adaptive/gold/adapt_tstep_grow_dtfunc_out.csv
  test/tests/time_steppers/iteration_adaptive/gold/adapt_tstep_grow_dtfunc_out.e
  test/tests/time_steppers/iteration_adaptive/gold/adapt_tstep_grow_dtfunc_restart_out.csv
  test/tests/time_steppers/iteration_adaptive/gold/adapt_tstep_grow_dtfunc_restart_out.e
  test/tests/time_steppers/iteration_adaptive/gold/multi_piecewise_sync_dt_out.csv
  test/tests/time_steppers/iteration_adaptive/multi_piecewise_sync_dt.i
  test/tests/time_steppers/iteration_adaptive/tests
Labels: PR: Auto Merge

#20408 _Actually_ AD single variable return mapping
  framework/include/utils/ChainedADReal.h
  framework/include/utils/ChainedReal.h
  framework/include/utils/MooseADWrapper.h
  framework/include/utils/MooseTypes.h
  modules/tensor_mechanics/include/materials/ADPowerLawCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/ADSingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/include/materials/PowerLawCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/SingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/src/materials/ADPowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/ADSingleVariableReturnMappingSolution.C
  modules/tensor_mechanics/src/materials/IsotropicPlasticityStressUpdate.C
  modules/tensor_mechanics/src/materials/PowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/SingleVariableReturnMappingSolution.C
  modules/tensor_mechanics/test/tests/ad_return_mapping/ad_return_mapping_derivative.i
  modules/tensor_mechanics/test/tests/ad_return_mapping/gold/reference.e
  modules/tensor_mechanics/test/tests/ad_return_mapping/tests
  unit/include/ADChainRuleTest.h
  unit/src/ADChainRuleTest.C
Labels: PR: Failed but allowed

#20502 Don't do nonlocal in regular Jacobian thread
  framework/src/loops/ComputeJacobianThread.C
  test/tests/userobjects/shape_element_user_object/jacobian.i
  test/tests/userobjects/shape_element_user_object/tests
Labels: PR: Ready for review/merge

#20592 Docker: Rely on cmake from PETSc and set revision default
  docker_ci/Dockerfile
  docker_ci/apt_installs.sh
  docker_ci/yum_installs.sh
Labels: PR: Ready for review/merge

#20596 Fix PETSC_REV and LIBMESH_REV for Docker
  docker_ci/Dockerfile
Labels: PR: Auto Merge

#20603 Use hub.docker.com/r/idaholab/moose for Docker documentation
  modules/doc/content/getting_started/installation/docker.md
Labels: PR: Auto Merge

#20609 Add post push hook to also tag Docker images by commit
  CODEOWNERS
  hooks/README.md
  hooks/post_push
Labels: PR: Auto Merge

#19399 Parallel Subset Simulation sampler for failure evaluation and optimization
  modules/stochastic_tools/doc/content/bib/stochastic_tools.bib
  modules/stochastic_tools/doc/content/source/reporters/AdaptiveMonteCarloDecision.md
  modules/stochastic_tools/doc/content/source/samplers/ParallelSubsetSimulation.md
  modules/stochastic_tools/include/reporters/AdaptiveMonteCarloDecision.h
  modules/stochastic_tools/include/samplers/AdaptiveImportanceSampler.h
  modules/stochastic_tools/include/samplers/ParallelSubsetSimulation.h
  modules/stochastic_tools/include/utils/AdaptiveMonteCarloUtils.h
  modules/stochastic_tools/src/reporters/AdaptiveMonteCarloDecision.C
  modules/stochastic_tools/src/samplers/AdaptiveImportanceSampler.C
  modules/stochastic_tools/src/samplers/ParallelSubsetSimulation.C
  modules/stochastic_tools/src/utils/AdaptiveMonteCarloUtils.C
  modules/stochastic_tools/test/tests/samplers/AdaptiveImportanceSampler/gold/ais_out.json
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/gold/pss_out.json
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/pss.i
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/pss_error1.i
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/sub.i
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/tests
Labels: PR: Failed but allowed

#20615 Fix Docker hooks, deinit submodules in Docker autobuild
  docker_ci/hooks/README.md
  docker_ci/hooks/post_checkout
  docker_ci/hooks/post_push
Labels: PR: Auto Merge

#20595 Continue Cleanup of install tests
  framework/app.mk
  framework/include/parser/CommandLine.h
  framework/include/utils/MooseUtils.h
  framework/src/base/MooseApp.C
  framework/src/parser/CommandLine.C
  framework/src/utils/MooseUtils.C
  modules/doc/content/application_development/build_system.md
  test/tests/make_install/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#20633 Add zlib-devel to Docker Yum installs for Rocky Linux
  docker_ci/yum_installs.sh
Labels: PR: Auto Merge

#20640 Move to repo root in post_checkout for Docker autobuild
  CODEOWNERS
  docker_ci/hooks/post_checkout
Labels: PR: Auto Merge

#20643 Allow creation of ADPiecewiseLinear
  framework/include/functions/Function.h
  framework/include/functions/PiecewiseBase.h
  framework/include/functions/PiecewiseLinear.h
  framework/include/functions/PiecewiseLinearBase.h
  framework/include/functions/PiecewiseTabularBase.h
  framework/src/functions/PiecewiseBase.C
  framework/src/functions/PiecewiseLinear.C
  framework/src/functions/PiecewiseLinearBase.C
  framework/src/functions/PiecewiseTabularBase.C
  test/tests/materials/boundary_material/fv_material_quadrature.i
  test/tests/materials/boundary_material/gold/ad_piecewise.e
  test/tests/materials/boundary_material/tests
Labels: PR: Auto Merge

#20552 Semidynamic vector improvements
  framework/include/utils/MooseADWrapper.h
  framework/include/utils/MooseUtils.h
  unit/src/MooseUtilsTest.C
Labels: PR: Ready for review/merge

#20649 Remove module cache in docker image
  docker_ci/hooks/post_checkout
Labels: PR: Ready for review/merge

#20529 Nearest sub app user object transfer
  framework/include/multiapps/MultiApp.h
  framework/include/transfers/MultiAppUserObjectTransfer.h
  framework/src/transfers/MultiAppUserObjectTransfer.C
  modules/doc/content/newsletter/2022_03.md
  test/tests/transfers/multiapp_userobject_transfer/gold/main_nearest_sub_app_out.e
  test/tests/transfers/multiapp_userobject_transfer/main_nearest_sub_app.i
  test/tests/transfers/multiapp_userobject_transfer/tests
Labels: PR: Ready for review/merge
