Repository idaholab/moose, pull requests merged in 2022-01, with the labels that each got.

#19952 Do not attach the same RM multiple times
  framework/include/base/MooseApp.h
  framework/src/base/MooseApp.C
Labels: PR: Auto Merge

#19934 Add more docs to problems and predictors
  framework/doc/content/source/predictors/AdamsPredictor.md
  framework/doc/content/source/predictors/SimplePredictor.md
  framework/doc/content/source/problems/DisplacedProblem.md
  framework/doc/content/source/problems/EigenProblem.md
  framework/doc/content/source/problems/ExternalProblem.md
  framework/doc/content/source/problems/FEProblemBase.md
  framework/doc/content/syntax/Executioner/Predictor/index.md
  framework/include/problems/EigenProblem.h
  framework/src/base/MooseApp.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/EigenProblem.C
  modules/doc/config.yml
Labels: PR: Auto Merge

#19937 Remove boundary conditions parameters from addBCAction,
  framework/src/actions/AddBCAction.C
Labels: PR: Auto Merge

#19917 Allow aux for convergence check
  framework/include/executioners/Transient.h
  framework/src/executioners/Transient.C
  test/include/problems/BasicExternalProblem.h
  test/src/problems/BasicExternalProblem.C
  test/tests/executioners/aux-ss-detection/gold/test_with_external_prob_out.e
  test/tests/executioners/aux-ss-detection/test_with_external_prob.i
  test/tests/executioners/aux-ss-detection/tests
Labels: PR: Auto Merge

#19954 geochemistry/paper.{md,bib} renamed.
  modules/geochemistry/joss_paper.bib
  modules/geochemistry/joss_paper.md
Labels: PR: Auto Merge

#19944 More functor aux and material utilities to support extracting fluxes
  framework/doc/content/source/materials/GenericFunctorGradientMaterial.md
  framework/include/auxkernels/FunctorElementalAux.h
  framework/include/auxkernels/FunctorVectorElementalAux.h
  framework/include/materials/GenericFunctorGradientMaterial.h
  framework/src/auxkernels/FunctorElementalAux.C
  framework/src/auxkernels/FunctorVectorElementalAux.C
  framework/src/materials/GenericFunctorGradientMaterial.C
  test/tests/materials/functor_properties/gradients/functor-gradients.i
  test/tests/materials/functor_properties/gradients/gold/functor-gradients_out.e
  test/tests/materials/functor_properties/gradients/tests
Labels: PR: Auto Merge

#19620 Use $(MAKE) instead of raw make for recursion
  framework/moose.mk
Labels: PR: Failed but allowed

#19957 Fix typo and compiler warning
  framework/include/utils/Units.h
  framework/src/utils/Units.C
Labels: PR: Failed but allowed, PR: Auto Merge

#19568 Add flux & dirichlet boundary conditions for mass/momentum/energy in NS
  framework/include/fvbcs/FVBoundaryCondition.h
  framework/include/fvbcs/FVFluxBC.h
  framework/src/fvbcs/FVBoundaryCondition.C
  framework/src/fvbcs/FVFluxBC.C
  modules/navier_stokes/doc/content/source/fvbcs/INSFVSymmetryScalarBC.md
  modules/navier_stokes/doc/content/source/fvbcs/WCNSFVEnergyFluxBC.md
  modules/navier_stokes/doc/content/source/fvbcs/WCNSFVInletTemperatureBC.md
  modules/navier_stokes/doc/content/source/fvbcs/WCNSFVInletVelocityBC.md
  modules/navier_stokes/doc/content/source/fvbcs/WCNSFVMassFluxBC.md
  modules/navier_stokes/doc/content/source/fvbcs/WCNSFVMomentumFluxBC.md
  modules/navier_stokes/doc/content/source/fvbcs/WCNSFVScalarFluxBC.md
  modules/navier_stokes/include/fvbcs/INSFVSymmetryPressureBC.h
  modules/navier_stokes/include/fvbcs/WCNSFVEnergyFluxBC.h
  modules/navier_stokes/include/fvbcs/WCNSFVInletTemperatureBC.h
  modules/navier_stokes/include/fvbcs/WCNSFVInletVelocityBC.h
  modules/navier_stokes/include/fvbcs/WCNSFVMassFluxBC.h
  modules/navier_stokes/include/fvbcs/WCNSFVMomentumFluxBC.h
  modules/navier_stokes/include/fvbcs/WCNSFVScalarFluxBC.h
  modules/navier_stokes/src/fvbcs/INSFVSymmetryPressureBC.C
  modules/navier_stokes/src/fvbcs/WCNSFVEnergyFluxBC.C
  modules/navier_stokes/src/fvbcs/WCNSFVInletTemperatureBC.C
  modules/navier_stokes/src/fvbcs/WCNSFVInletVelocityBC.C
  modules/navier_stokes/src/fvbcs/WCNSFVMassFluxBC.C
  modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C
  modules/navier_stokes/src/fvbcs/WCNSFVScalarFluxBC.C
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/dirichlet_bcs_mdot.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/dirichlet_bcs_velocity.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_direct.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_mdot.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/gold/dirichlet_bcs_mdot_out.e
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/gold/dirichlet_bcs_velocity_out.e
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/gold/flux_bcs_direct_out.e
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/gold/flux_bcs_mdot_out.e
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/gold/flux_bcs_velocity_out.e
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/tests
Labels: PR: Failed but allowed

#19918 Allow variables to be used when initing neighbor stateful props
  framework/include/loops/ProjectMaterialProperties.h
  framework/include/loops/ThreadedElementLoopBase.h
  framework/src/loops/ComputeIndicatorThread.C
  framework/src/loops/ComputeJacobianThread.C
  framework/src/loops/ComputeMaterialsObjectThread.C
  framework/src/loops/ComputeResidualThread.C
  framework/src/vectorpostprocessors/WorkBalance.C
  test/include/materials/VarCouplingMaterial.h
  test/src/materials/VarCouplingMaterial.C
  test/tests/dgkernels/stateful-coupled-var/test.i
  test/tests/dgkernels/stateful-coupled-var/tests
Labels: PR: Failed but allowed

#19628 Add calculation of Jacobian for Pressure with spherical coordinates
  modules/tensor_mechanics/include/bcs/Pressure.h
  modules/tensor_mechanics/src/bcs/Pressure.C
  modules/tensor_mechanics/test/tests/test_jacobian/jacobian_pressure_spherical.i
  modules/tensor_mechanics/test/tests/test_jacobian/tests
Labels: PR: Ready for review/merge

#19969 Use default arg `Communicator::get_unique_tag()` everywhere
  framework/src/meshgenerators/ElementDeletionGeneratorBase.C
  framework/src/meshgenerators/SideSetsAroundSubdomainGenerator.C
  framework/src/meshgenerators/SideSetsBetweenSubdomainsGenerator.C
  modules/ray_tracing/include/utils/ParallelStudy.h
Labels: PR: Auto Merge

#20000 Prepare for nanoflann update
  framework/include/utils/KDTree.h
  framework/include/utils/PointListAdaptor.h
  framework/src/mesh/MooseMesh.C
  framework/src/utils/KDTree.C
Labels: PR: Ready for review/merge

#20028 Add December 2021 newsletter
  modules/doc/content/newsletter/2021_12.md
  modules/doc/content/newsletter/2022_01.md
  modules/doc/content/newsletter/index.md
Labels: PR: Auto Merge

#20027 Added an option for PiecewiseLinear to extrapolate
  framework/doc/content/source/functions/PiecewiseLinear.md
  framework/include/functions/PiecewiseLinearBase.h
  framework/src/functions/PiecewiseLinear.C
  framework/src/functions/PiecewiseLinearBase.C
  modules/doc/content/newsletter/2022_01.md
  test/tests/functions/piecewise_linear/gold/extrap_function_vpp_0000.csv
  test/tests/functions/piecewise_linear/gold/no_extrap_function_vpp_0000.csv
  test/tests/functions/piecewise_linear/piecewise_linear.i
  test/tests/functions/piecewise_linear/tests
Labels: PR: Failed but allowed

#19456 Update MPICH to 3.4.2
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/meta.yaml
  conda/mpich/build.sh
  conda/mpich/conda_build_config.yaml
  conda/mpich/meta.yaml
  conda/petsc/meta.yaml
  modules/doc/content/newsletter/2022_01.md
Labels: PR: Ready for review/merge

#20042 Added consistant outputIterationStep
  modules/tensor_mechanics/include/materials/ADSingleVariableReturnMappingSolution.h
  modules/tensor_mechanics/include/materials/SingleVariableReturnMappingSolution.h
Labels: PR: Failed but allowed

#20059 Avoid allocating large dense matrix in EBSDReader
  modules/phase_field/src/userobjects/EBSDReader.C
  modules/tensor_mechanics/include/utils/EulerAngles.h
  modules/tensor_mechanics/src/utils/EulerAngles.C
Labels: PR: Ready for review/merge

#20074 Dont reuse base for noisy functions
  modules/contact/test/tests/mechanical-small-problem/frictionless-nodal-lm-mortar-disp.i
  modules/contact/test/tests/mechanical-small-problem/mortar-mech.i
Labels: PR: Auto Merge

#19089 Removed calls to ADMaterial
  framework/include/materials/ADPiecewiseLinearInterpolationMaterial.h
  framework/src/materials/ADPiecewiseLinearInterpolationMaterial.C
  modules/heat_conduction/test/include/materials/ADConvectiveHeatFluxTest.h
  modules/heat_conduction/test/include/materials/ADThermalConductivityTest.h
  modules/heat_conduction/test/src/materials/ADConvectiveHeatFluxTest.C
  modules/heat_conduction/test/src/materials/ADThermalConductivityTest.C
  modules/misc/include/materials/ADDensity.h
  modules/misc/src/materials/ADDensity.C
  modules/misc/test/include/materials/ADSoretCoeffTest.h
  modules/misc/test/src/materials/ADSoretCoeffTest.C
  modules/navier_stokes/include/materials/INSADMaterial.h
  modules/navier_stokes/src/materials/INSADMaterial.C
  modules/phase_field/include/materials/ADMathFreeEnergy.h
  modules/phase_field/src/materials/ADMathFreeEnergy.C
  modules/phase_field/test/include/materials/ADTestDerivativeFunction.h
  modules/phase_field/test/src/materials/ADTestDerivativeFunction.C
  modules/tensor_mechanics/include/materials/ADComputeIncrementalShellStrain.h
  modules/tensor_mechanics/include/materials/ADComputeIsotropicElasticityTensorShell.h
  modules/tensor_mechanics/include/materials/ADComputeShellStress.h
  modules/tensor_mechanics/include/materials/ADComputeStrainBase.h
  modules/tensor_mechanics/include/materials/ADComputeStressBase.h
  modules/tensor_mechanics/include/materials/ADSmearedCrackSofteningBase.h
  modules/tensor_mechanics/include/materials/HillConstants.h
  modules/tensor_mechanics/src/materials/ADComputeIncrementalShellStrain.C
  modules/tensor_mechanics/src/materials/ADComputeIsotropicElasticityTensorShell.C
  modules/tensor_mechanics/src/materials/ADComputeShellStress.C
  modules/tensor_mechanics/src/materials/ADComputeStrainBase.C
  modules/tensor_mechanics/src/materials/ADComputeStressBase.C
  modules/tensor_mechanics/src/materials/ADSmearedCrackSofteningBase.C
  modules/tensor_mechanics/src/materials/HillConstants.C
  modules/tensor_mechanics/test/tests/ad_elastic/finite_elastic.i
  test/include/materials/ADCheckGlobalToDerivativeMap.h
  test/include/materials/ADCoupledMaterial.h
  test/include/materials/ADStateful.h
  test/include/materials/ADStatefulMaterial.h
  test/src/materials/ADCoupledMaterial.C
  test/src/materials/ADStateful.C
  test/src/materials/ADStatefulMaterial.C
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/include/materials/PackedColumn.h
  tutorials/darcy_thermo_mech/step06_coupled_darcy_heat_conduction/src/materials/PackedColumn.C
  tutorials/darcy_thermo_mech/step09_mechanics/include/materials/PackedColumn.h
  tutorials/darcy_thermo_mech/step09_mechanics/src/materials/PackedColumn.C
  tutorials/darcy_thermo_mech/step10_multiapps/include/materials/PackedColumn.h
  tutorials/darcy_thermo_mech/step10_multiapps/src/materials/PackedColumn.C
  tutorials/tutorial01_app_development/step09_mat_props/include/materials/PackedColumn.h
  tutorials/tutorial01_app_development/step10_auxkernels/include/materials/PackedColumn.h
  unit/src/ADTypesTest.C
Labels: PR: Failed but allowed

#20088 Fix string->int conversion on M1
  framework/src/utils/MooseUtils.C
  unit/src/MooseUtilsTest.C
Labels: PR: Auto Merge

#20084 Use an ordered set based on ID for secondary to msm container
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/src/constraints/AutomaticMortarGeneration.C
  modules/contact/test/tests/bouncing-block-contact/frictionless-weighted-gap.i
  modules/contact/test/tests/bouncing-block-contact/ping-ponging/mortar-no-ping-pong_weighted.i
  modules/contact/test/tests/mechanical-small-problem/frictionless-nodal-lm-mortar-disp.i
  modules/contact/test/tests/mechanical-small-problem/mortar-mech.i
Labels: PR: Failed but allowed

#20103 Updates to allow manual build of conda packages on M1
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/meta.yaml
  conda/mpich/build.sh
  conda/mpich/conda_build_config.yaml
  conda/mpich/meta.yaml
  conda/petsc/build.sh
  conda/petsc/meta.yaml
  conda/petsc/no-cppflags-in-pkgconfig-cflags.patch
  modules/doc/content/getting_started/installation/m1_monterey.md
  scripts/configure_petsc.sh
Labels: PR: Failed but allowed, PR: Ready for review/merge

#18182 Add a suffix to the material output auxvariables if the same name is already in use
  framework/src/actions/MaterialOutputAction.C
  framework/src/outputs/AdvancedOutput.C
  modules/tensor_mechanics/test/tests/truss/truss_plastic.i
  test/tests/materials/output/gold/vector_output.e
  test/tests/materials/output/tests
Labels: PR: Ready for review/merge

#20117 Slightly loosen exodiff tolerance for fixed point, nonlinear test
  test/tests/executioners/fixed_point/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#20007 Added TriangulatedMeshGenerator generator
  modules/doc/content/newsletter/2022_01.md
  modules/reactor/doc/content/media/meshgenerators/triangle_abtr.png
  modules/reactor/doc/content/media/meshgenerators/triangle_abtr_steiner.png
  modules/reactor/doc/content/source/meshgenerators/PeripheralTriangleMeshGenerator.md
  modules/reactor/include/meshgenerators/PeripheralTriangleMeshGenerator.h
  modules/reactor/src/meshgenerators/PeripheralTriangleMeshGenerator.C
  modules/reactor/test/tests/meshgenerators/peripheral_triangle_mesh_generator/abtr_tri.i
  modules/reactor/test/tests/meshgenerators/peripheral_triangle_mesh_generator/abtr_tri_err.i
  modules/reactor/test/tests/meshgenerators/peripheral_triangle_mesh_generator/gold/abtr_mesh.e
  modules/reactor/test/tests/meshgenerators/peripheral_triangle_mesh_generator/gold/abtr_tri.e
  modules/reactor/test/tests/meshgenerators/peripheral_triangle_mesh_generator/gold/abtr_tri_steiner.e
  modules/reactor/test/tests/meshgenerators/peripheral_triangle_mesh_generator/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20118 Value cache
  framework/include/utils/KDTree.h
  framework/include/utils/ValueCache.h
  framework/src/mesh/MooseMesh.C
  unit/src/ValueCacheTest.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20140 Tighten solve tolerances for random failing NS test
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/dirichlet_bcs_velocity.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/gold/dirichlet_bcs_velocity_out.e
Labels: PR: Failed but allowed

#20104 Construct custom material container for mortar
  framework/include/auxkernels/MortarNodalAuxKernel.h
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/include/constraints/MortarConstraintBase.h
  framework/include/constraints/MortarData.h
  framework/include/interfaces/MortarConsumerInterface.h
  framework/include/interfaces/MortarExecutorInterface.h
  framework/include/loops/ComputeMortarFunctor.h
  framework/include/materials/MaterialData.h
  framework/include/problems/FEProblemBase.h
  framework/include/utils/MooseUtils.h
  framework/include/utils/MortarUtils.h
  framework/src/auxkernels/MortarNodalAuxKernel.C
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/constraints/MortarConstraintBase.C
  framework/src/constraints/MortarData.C
  framework/src/interfaces/MortarConsumerInterface.C
  framework/src/interfaces/MortarExecutorInterface.C
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/materials/MaterialData.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/MooseUtils.C
Labels: PR: Failed but allowed

#20144 Have cylinder_friction use Eisenstat-Walker
  modules/contact/test/tests/pdass_problems/cylinder_friction.i
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_check_cont_press_FINAL.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_check_friction_FINAL.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_check_x_disp_FINAL.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_check_y_disp_FINAL.csv
Labels: PR: Failed but allowed

#20112 Update UMAT interface vector order to typical use
  modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C
  modules/tensor_mechanics/test/plugins/elastic_incremental_anisotropic.f
  modules/tensor_mechanics/test/tests/umat/print/tests
  modules/tensor_mechanics/test/tests/umat/shear_order/gold/shear_order_moose_x_out.e
  modules/tensor_mechanics/test/tests/umat/shear_order/gold/shear_order_moose_z_out.e
  modules/tensor_mechanics/test/tests/umat/shear_order/gold/shear_order_umat_x_out.e
  modules/tensor_mechanics/test/tests/umat/shear_order/gold/shear_order_umat_z_out.e
  modules/tensor_mechanics/test/tests/umat/shear_order/shear_order_umat.i
  modules/tensor_mechanics/test/tests/umat/shear_order/tests
Labels: PR: Failed but allowed

#20146 Enable AD material properties in DiffusionFluxAux
  framework/doc/content/source/auxkernels/DiffusionFluxAux.md
  framework/include/auxkernels/DiffusionFluxAux.h
  framework/src/auxkernels/DiffusionFluxAux.C
  test/tests/auxkernels/diffusion_flux/diffusion_flux.i
  test/tests/auxkernels/diffusion_flux/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20120 Add ForcingFunctionAux AuxKernel
  framework/doc/content/source/auxkernels/ForcingFunctionAux.md
  framework/include/auxkernels/ForcingFunctionAux.h
  framework/src/auxkernels/ForcingFunctionAux.C
  test/tests/auxkernels/forcing_function_aux/forcing_function_aux.i
  test/tests/auxkernels/forcing_function_aux/gold/forcing_function_aux_out.e
  test/tests/auxkernels/forcing_function_aux/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20131 Adding nested MC sampling
  framework/include/samplers/Sampler.h
  framework/src/samplers/Sampler.C
  modules/stochastic_tools/doc/content/source/samplers/NestedMonteCarloSampler.md
  modules/stochastic_tools/include/samplers/NestedMonteCarloSampler.h
  modules/stochastic_tools/src/samplers/NestedMonteCarloSampler.C
  modules/stochastic_tools/test/tests/samplers/nested_monte_carlo/gold/nested_monte_carlo_out_data_0001.csv
  modules/stochastic_tools/test/tests/samplers/nested_monte_carlo/nested_monte_carlo.i
  modules/stochastic_tools/test/tests/samplers/nested_monte_carlo/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20152 Error Message for PatternedHexMeshGenerator with inputs containing bl…
  modules/reactor/src/meshgenerators/PatternedHexMeshGenerator.C
  modules/reactor/test/tests/meshgenerators/patterned_hex_mesh_generator/patterned_2d_block_name_conflict.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_mesh_generator/tests
Labels: PR: Failed but allowed

#20150 Add January 2022 news
  modules/doc/content/newsletter/2021_08.md
  modules/doc/content/newsletter/2022_01.md
  modules/doc/content/newsletter/2022_02.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed, PR: Ready for review/merge
