Repository idaholab/moose, pull requests merged in 2022-08, with the labels that each got.

#21713 Use mpich 4.0.2 for docker
  docker_ci/Dockerfile
Labels: PR: Failed but allowed

#21729 Remove 2022 summer workshop announcement from website homepage
  modules/doc/content/upcoming_training.md
Labels: PR: Failed but allowed

#21726 Changes to support AD for 2 phase flow
  modules/thermal_hydraulics/include/utils/Numerics.h
  modules/thermal_hydraulics/src/utils/Numerics.C
  modules/thermal_hydraulics/test/src/actions/ClosureTestAction.C
Labels: PR: Failed but allowed

#21744 Add clear cyclic graph error for mesh generators
  framework/src/base/MooseApp.C
  framework/src/parser/Syntax.C
  test/tests/meshgenerators/cyclic/cyclic.i
  test/tests/meshgenerators/cyclic/tests
Labels: PR: Failed but allowed

#21711 Add missing gold file
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gold/gap_heat_transfer_3D_mortar_out_NodalTemperature_0001.csv
Labels: PR: Failed but allowed

#21756 Add robustness for fixed meshes in NearestNodeTransfer
  framework/src/transfers/MultiAppNearestNodeTransfer.C
Labels: PR: Failed but allowed

#21762 Make July news public and add August template
  modules/doc/content/newsletter/2022_07.md
  modules/doc/content/newsletter/2022_08.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#21721 Lagrangian kernels can mix small strain models
  modules/tensor_mechanics/src/materials/ComputeLinearElasticStress.C
  modules/tensor_mechanics/test/tests/lagrangian/materials/kinematic_check/strain_check.i
  modules/tensor_mechanics/test/tests/lagrangian/materials/kinematic_check/tests
Labels: PR: Failed but allowed

#21717 Block restrict homogenization integral
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/test/tests/lagrangian/action/homogenization_block.i
  modules/tensor_mechanics/test/tests/lagrangian/action/tests
Labels: PR: Failed but allowed

#21775 Cache PrimarySecondary and SecondaryPrimary Jacobians in Mortar
  framework/doc/content/source/constraints/ADPenaltyEqualValueConstraint.md
  framework/include/constraints/PenaltyEqualValueConstraint.h
  framework/src/base/Assembly.C
  framework/src/constraints/MortarConstraint.C
  framework/src/constraints/PenaltyEqualValueConstraint.C
  test/tests/mortar/continuity-3d-non-conforming/tests
Labels: PR: Failed but allowed

#21758 HIT format multiline strings
  framework/contrib/hit/lex.cc
  framework/contrib/hit/lex.h
  framework/contrib/hit/main.cc
  framework/contrib/hit/parse.cc
  framework/contrib/hit/test/reflow.i
  framework/doc/content/hit.md
  modules/doc/content/application_usage/input_syntax.md
  modules/doc/content/newsletter/2022_08.md
  unit/src/HitTests.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21565 Generalizing cross validation for other data types and Trainers.
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/cross_validation.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/surrogate_creation.md
  modules/stochastic_tools/doc/content/syntax/Trainers/index.md
  modules/stochastic_tools/examples/surrogates/cross_validation/all_sub.i
  modules/stochastic_tools/examples/surrogates/cross_validation/all_trainers_uniform_cv.i
  modules/stochastic_tools/examples/surrogates/cross_validation/gold/all_trainers_no_libtorch.json
  modules/stochastic_tools/examples/surrogates/cross_validation/gold/all_trainers_uniform_cv_out.json
  modules/stochastic_tools/examples/surrogates/cross_validation/gold/normal_train_and_cv_out_cv_scores_0002.csv
  modules/stochastic_tools/examples/surrogates/cross_validation/gold/uniform_train_and_cv_out_cv_scores_0002.csv
  modules/stochastic_tools/examples/surrogates/cross_validation/tests
  modules/stochastic_tools/examples/surrogates/cross_validation/uniform_train_and_cv.i
  modules/stochastic_tools/include/surrogates/GaussianProcessTrainer.h
  modules/stochastic_tools/include/surrogates/LibtorchANNTrainer.h
  modules/stochastic_tools/include/surrogates/NearestPointSurrogate.h
  modules/stochastic_tools/include/surrogates/NearestPointTrainer.h
  modules/stochastic_tools/include/surrogates/PolynomialChaosTrainer.h
  modules/stochastic_tools/include/surrogates/PolynomialRegressionTrainer.h
  modules/stochastic_tools/include/surrogates/SurrogateTrainer.h
  modules/stochastic_tools/src/surrogates/GaussianProcessTrainer.C
  modules/stochastic_tools/src/surrogates/LibtorchANNSurrogate.C
  modules/stochastic_tools/src/surrogates/LibtorchANNTrainer.C
  modules/stochastic_tools/src/surrogates/NearestPointSurrogate.C
  modules/stochastic_tools/src/surrogates/NearestPointTrainer.C
  modules/stochastic_tools/src/surrogates/PolynomialChaosTrainer.C
  modules/stochastic_tools/src/surrogates/PolynomialRegressionTrainer.C
  modules/stochastic_tools/src/surrogates/SurrogateTrainer.C
  modules/stochastic_tools/test/include/reporters/CrossValidationScores.h
  modules/stochastic_tools/test/src/reporters/CrossValidationScores.C
  modules/stochastic_tools/test/tests/surrogates/cross_validation/gold/poly_reg_vec_out.json
  modules/stochastic_tools/test/tests/surrogates/cross_validation/gold/train_and_cv_out.json
  modules/stochastic_tools/test/tests/surrogates/cross_validation/gold/train_and_cv_out_cv_scores_0002.csv
  modules/stochastic_tools/test/tests/surrogates/cross_validation/poly_reg_vec.i
  modules/stochastic_tools/test/tests/surrogates/cross_validation/sub_vector.i
  modules/stochastic_tools/test/tests/surrogates/cross_validation/tests
  modules/stochastic_tools/test/tests/surrogates/cross_validation/train_and_cv.i
  modules/stochastic_tools/test/tests/surrogates/nearest_point/gold/np_vec_out.json
  modules/stochastic_tools/test/tests/surrogates/nearest_point/np_vec.i
  modules/stochastic_tools/test/tests/surrogates/nearest_point/sub_vector.i
  modules/stochastic_tools/test/tests/surrogates/nearest_point/tests
Labels: PR: Failed but allowed

#21699 Add GhostLowerDElems relationship manager for side user objects
  framework/include/auxkernels/MortarNodalAuxKernel.h
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/include/constraints/MortarData.h
  framework/include/interfaces/MortarExecutorInterface.h
  framework/include/loops/ComputeMortarFunctor.h
  framework/include/outputs/OutputWarehouse.h
  framework/include/postprocessors/NodalVariableValue.h
  framework/include/problems/FEProblemBase.h
  framework/include/relationshipmanagers/AugmentSparsityOnInterface.h
  framework/include/relationshipmanagers/GhostHigherDLowerDPointNeighbors.h
  framework/include/relationshipmanagers/GhostLowerDElems.h
  framework/include/systems/NonlinearSystemBase.h
  framework/include/utils/MortarUtils.h
  framework/src/actions/SetupMeshCompleteAction.C
  framework/src/auxkernels/MortarNodalAuxKernel.C
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/constraints/MortarConstraintBase.C
  framework/src/constraints/MortarData.C
  framework/src/interfaces/MortarExecutorInterface.C
  framework/src/loops/BoundaryElemIntegrityCheckThread.C
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/outputs/OutputWarehouse.C
  framework/src/postprocessors/NodalVariableValue.C
  framework/src/preconditioners/VariableCondensationPreconditioner.C
  framework/src/problems/FEProblemBase.C
  framework/src/relationshipmanagers/AugmentSparsityOnInterface.C
  framework/src/relationshipmanagers/GhostHigherDLowerDPointNeighbors.C
  framework/src/relationshipmanagers/GhostLowerDElems.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/userobject/SideUserObject.C
  test/include/userobjects/LowerDIntegralSideUserObject.h
  test/src/userobjects/LowerDIntegralSideUserObject.C
  test/tests/mortar/continuity-2d-non-conforming/tests
  test/tests/preconditioners/vcp/tests
  test/tests/userobjects/side_uo_with_lowerd_use/side-uo-with-lower-d-use.i
  test/tests/userobjects/side_uo_with_lowerd_use/tests
Labels: PR: Failed but allowed

#21760 Have SideIntegralVariablePostprocessor use Guillaume's new API
  framework/include/postprocessors/SideDiffusiveFluxIntegral.h
  framework/include/postprocessors/SideIntegralVariablePostprocessor.h
  framework/src/postprocessors/SideDiffusiveFluxIntegral.C
  framework/src/postprocessors/SideIntegralVariablePostprocessor.C
  test/include/postprocessors/NonFunctorSideDiffusiveFluxIntegral.h
  test/src/postprocessors/NonFunctorSideDiffusiveFluxIntegral.C
  test/tests/materials/piecewise_by_block_material/test.i
  test/tests/postprocessors/side_diffusive_flux_average/side_diffusive_flux_average_fv.i
  test/tests/postprocessors/side_diffusive_flux_integral/side_diffusive_flux_integral_fv.i
  test/tests/postprocessors/side_diffusive_flux_integral/tests
Labels: C: Framework

#21810 Update moose-pyhit
  conda/pyhit/build.sh
  conda/pyhit/meta.yaml
Labels: PR: Failed but allowed

#21385 Corrected the stress and strain output and added tests
  modules/tensor_mechanics/include/materials/ADComputeIncrementalShellStrain.h
  modules/tensor_mechanics/include/materials/ADComputeShellStress.h
  modules/tensor_mechanics/src/materials/ADComputeIncrementalShellStrain.C
  modules/tensor_mechanics/src/materials/ADComputeShellStress.C
  modules/tensor_mechanics/test/tests/shell/static/gold/inclined_straintest_out.e
  modules/tensor_mechanics/test/tests/shell/static/gold/straintest_out.e
  modules/tensor_mechanics/test/tests/shell/static/gold/straintest_shear_out.e
  modules/tensor_mechanics/test/tests/shell/static/gold/tapered_out.e
  modules/tensor_mechanics/test/tests/shell/static/inclined_straintest.i
  modules/tensor_mechanics/test/tests/shell/static/pressure_error.i
  modules/tensor_mechanics/test/tests/shell/static/shell_inclined.e
  modules/tensor_mechanics/test/tests/shell/static/straintest.i
  modules/tensor_mechanics/test/tests/shell/static/straintest_shear.i
  modules/tensor_mechanics/test/tests/shell/static/tapered.i
  modules/tensor_mechanics/test/tests/shell/static/taperedmesh.e
  modules/tensor_mechanics/test/tests/shell/static/tests
Labels: PR: Failed but allowed

#21813 The new constructor added in this commit is no longer needed
  framework/include/utils/GriddedData.h
  framework/src/utils/GriddedData.C
  unit/src/GriddedDataTest.C
Labels: PR: Failed but allowed

#21690 Working on distributed merge for PolyCrystalUserObjectBase
  modules/phase_field/include/postprocessors/FeatureFloodCount.h
  modules/phase_field/include/userobjects/PolycrystalUserObjectBase.h
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
  modules/phase_field/src/userobjects/PolycrystalUserObjectBase.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21823 Set next_unique_id based on extruded nodes and elements in FancyExtruderGenerator
  framework/src/meshgenerators/FancyExtruderGenerator.C
Labels: PR: Failed but allowed

#21821 Changed unused param check to default to Error instead of warning
  examples/ex09_stateful_materials/ex09.i
  examples/ex15_actions/ex15.i
  examples/ex19_dampers/ex19.i
  framework/src/base/MooseApp.C
  python/TestHarness/TestHarness.py
  python/TestHarness/testers/RunApp.py
  test/tests/fvkernels/mms/skewness-correction/adv-diff-react/skewed.i
  test/tests/fvkernels/mms/skewness-correction/two_term_extrapol/advection-outflow.i
  test/tests/misc/check_error/tests
  test/tests/misc/jacobian/simple.i
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21803 Allow to initialize NSFV action added vars from mesh
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/src/base/NavierStokesApp.C
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-action-nulltr.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-action-nulltr_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Failed but allowed

#20989 Use static registration for execute flags
  framework/doc/content/source/interfaces/SetupInterface.md
  framework/include/base/Attributes.h
  framework/include/base/ExecFlagRegistry.h
  framework/include/base/Factory.h
  framework/include/base/Moose.h
  framework/include/base/MooseApp.h
  framework/include/interfaces/SetupInterface.h
  framework/include/loops/ComputeUserObjectsThread.h
  framework/include/transfers/MultiAppTransfer.h
  framework/include/utils/ExecFlagEnum.h
  framework/include/utils/MooseEnumBase.h
  framework/include/warehouses/ExecuteMooseObjectWarehouse.h
  framework/src/base/Attributes.C
  framework/src/base/ExecFlagRegistry.C
  framework/src/base/Factory.C
  framework/src/base/Moose.C
  framework/src/base/MooseApp.C
  framework/src/executors/Executor.C
  framework/src/interfaces/SetupInterface.C
  framework/src/transfers/MultiAppTransfer.C
  framework/src/utils/ExecFlagEnum.C
  framework/src/utils/MooseEnumBase.C
  modules/chemical_reactions/src/base/ChemicalReactionsApp.C
  modules/chemical_reactions/test/src/base/ChemicalReactionsTestApp.C
  modules/electromagnetics/src/base/ElectromagneticsApp.C
  modules/fluid_properties/src/base/FluidPropertiesApp.C
  modules/heat_conduction/src/base/HeatConductionApp.C
  modules/level_set/src/base/LevelSetApp.C
  modules/level_set/src/base/LevelSetTypes.C
  modules/module_loader/src/ModulesApp.C
  modules/navier_stokes/src/base/NavierStokesApp.C
  modules/peridynamics/src/base/PeridynamicsApp.C
  modules/phase_field/src/base/PhaseFieldApp.C
  modules/porous_flow/src/base/PorousFlowApp.C
  modules/ray_tracing/src/base/RayTracingApp.C
  modules/rdg/src/base/RdgApp.C
  modules/reactor/src/base/ReactorApp.C
  modules/richards/src/base/RichardsApp.C
  modules/stochastic_tools/src/base/StochasticToolsApp.C
  modules/tensor_mechanics/src/base/TensorMechanicsApp.C
  modules/xfem/src/base/XFEMApp.C
  modules/xfem/src/base/XFEMAppTypes.C
  scripts/add_exec_flag_registration.py
  test/include/reporters/CurrentExecFlagReporter.h
  test/include/userobjects/ExecFlagRegistryErrorTest.h
  test/src/auxkernels/CheckCurrentExecAux.C
  test/src/base/MooseTestApp.C
  test/src/base/MooseTestAppTypes.C
  test/src/reporters/CurrentExecFlagReporter.C
  test/src/userobjects/ExecFlagRegistryErrorTest.C
  test/tests/misc/exec_flag_registry/exec_flag_registry_errors.i
  test/tests/misc/exec_flag_registry/tests
  test/tests/misc/execute_on/execute_on_test.i
  test/tests/misc/execute_on/gold/execute_on_test_out.e
  test/tests/misc/execute_on/gold/execute_on_test_out.json
  test/tests/misc/execute_on/tests
Labels: PR: Ready for review/merge

#21576 Remove DT2
  framework/doc/content/source/timesteppers/DT2.md
  framework/include/timesteppers/DT2.h
  framework/src/timesteppers/DT2.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21421 Add ring and sector reporting ID option in PCCM object of reactor module
  modules/reactor/doc/content/source/meshgenerators/PolygonConcentricCircleMeshGenerator.md
  modules/reactor/src/meshgenerators/PolygonConcentricCircleMeshGeneratorBase.C
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/gold/pin_hex_reporting_id_out.e
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/gold/pin_reporting_id_annular_block_out.e
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/gold/pin_reporting_id_annular_ring_out.e
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/gold/pin_reporting_id_sector_out.e
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/pin_hex_reporting_id.i
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/pin_reporting_id.i
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/tests
  modules/reactor/test/tests/meshgenerators/reporting_id/depletion_id/gold/sub_pin_depletion_id_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/depletion_id/sub_pin_depletion_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/depletion_id/tests
Labels: PR: Failed but allowed

#21444 Gather material data for batch evaluation
  framework/doc/content/source/userobject/BatchMaterial.md
  framework/include/userobject/BatchMaterial.h
  test/include/materials/BatchTestMaterial.h
  test/include/userobjects/BatchMaterialTest.h
  test/src/materials/BatchTestMaterial.C
  test/src/userobjects/BatchMaterialTest.C
  test/tests/batch_material/test.i
  test/tests/batch_material/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21851 Bug fixes for running RGMB Mesh Generators with Griffin
  modules/reactor/src/meshgenerators/AssemblyMeshGenerator.C
  modules/reactor/src/meshgenerators/CoreMeshGenerator.C
  modules/reactor/src/meshgenerators/PinMeshGenerator.C
Labels: PR: Failed but allowed

#21830 Codeowners update
  CODEOWNERS
Labels: PR: Failed but allowed

#21862 Avoid parse errors getting dropped
  framework/src/parser/Parser.C
Labels: PR: Failed but allowed

#21772 Improve bounding box algorithms
  modules/phase_field/include/postprocessors/FeatureFloodCount.h
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
  modules/phase_field/src/postprocessors/GrainTracker.C
  modules/phase_field/test/tests/grain_tracker_test/tests
Labels: PR: Failed but allowed

#21646 Block-restricted ReferenceElementJacobianDamper
  modules/tensor_mechanics/include/dampers/ReferenceElementJacobianDamper.h
  modules/tensor_mechanics/src/dampers/ReferenceElementJacobianDamper.C
  modules/tensor_mechanics/test/tests/jacobian_damper/block_restriction.i
  modules/tensor_mechanics/test/tests/jacobian_damper/gold/block_restriction_out.e
  modules/tensor_mechanics/test/tests/jacobian_damper/tests
Labels: PR: Failed but allowed

#21613 Use main branch for storking new apps
  scripts/stork.sh
Labels: PR: Failed but allowed

#21593 Remove derivative of specific heat from NS kernels
  modules/navier_stokes/doc/content/source/fvkernels/INSFVEnergyTimeDerivative.md
  modules/navier_stokes/doc/content/source/fvkernels/PINSFVEnergyTimeDerivative.md
  modules/navier_stokes/include/fvkernels/INSFVEnergyTimeDerivative.h
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/src/fvkernels/INSFVEnergyTimeDerivative.C
  modules/navier_stokes/src/fvkernels/PINSFVEnergyTimeDerivative.C
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-transient.i
  modules/navier_stokes/test/tests/finite_volume/ins/lid-driven/transient-lid-driven-with-energy.i
  modules/navier_stokes/test/tests/finite_volume/pwcns/channel-flow/2d-transient.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/dirichlet_bcs_mdot.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/dirichlet_bcs_velocity.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_direct.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_mdot-action.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_mdot.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity-action.i
  modules/navier_stokes/test/tests/finite_volume/wcns/boundary_conditions/flux_bcs_velocity.i
  modules/navier_stokes/test/tests/finite_volume/wcns/channel-flow/2d-transient-action.i
  modules/navier_stokes/test/tests/finite_volume/wcns/channel-flow/2d-transient.i
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/2d-transient.i
  modules/navier_stokes/test/tests/postprocessors/rayleigh/natural_convection.i
Labels: PR: Failed but allowed

#21884 Removing conda check while issues are worked out
  framework/moose.mk
Labels: PR: Failed but allowed

#21864 Prepare mesh when needed in SidesetsBetweenSubdomainsGenerator
  framework/src/meshgenerators/SideSetsBetweenSubdomainsGenerator.C
  test/tests/meshgenerators/sidesets_between_subdomains_generator/gold/sideset_between_subdomains_not_prepared_in.e
  test/tests/meshgenerators/sidesets_between_subdomains_generator/sideset_between_subdomains_not_prepared.i
  test/tests/meshgenerators/sidesets_between_subdomains_generator/tests
Labels: PR: Failed but allowed

#21874 Fix nonunity errors with conda stacks
  framework/src/vectorpostprocessors/VectorPostprocessor.C
Labels: PR: Failed but allowed

#21889 Check whether or not LIBMESH_DIR is a child of conda base in libmesh install
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21787 Nonlocal damage model system
  framework/doc/content/source/userobject/RadialAverage.md
  framework/include/userobject/RadialAverage.h
  framework/include/userobject/ThreadedRadialAverageLoop.h
  framework/src/userobject/RadialAverage.C
  framework/src/userobject/ThreadedRadialAverageLoop.C
  modules/tensor_mechanics/doc/content/source/materials/ADNonlocalDamage.md
  modules/tensor_mechanics/doc/content/source/materials/CombinedScalarDamage.md
  modules/tensor_mechanics/doc/content/source/materials/NonlocalDamage.md
  modules/tensor_mechanics/include/materials/NonlocalDamage.h
  modules/tensor_mechanics/src/materials/NonlocalDamage.C
  modules/tensor_mechanics/test/tests/scalar_material_damage/ad_nonlocal_scalar_damage.i
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/ad_nonlocal_scalar_damage_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/nonlocal_scalar_damage_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/nonlocal_scalar_damage.i
  modules/tensor_mechanics/test/tests/scalar_material_damage/tests
  test/include/auxkernels/RadialAverageAux.h
  test/src/auxkernels/RadialAverageAux.C
  test/tests/userobjects/radial_average/gold/time_changing_test_out.e
  test/tests/userobjects/radial_average/tests
  test/tests/userobjects/radial_average/time_changing_test.i
Labels: PR: Failed but allowed

#21316 Dg helem
  framework/src/bcs/DGFunctionDiffusionDirichletBC.C
  framework/src/dgkernels/ADDGDiffusion.C
  framework/src/dgkernels/ArrayDGDiffusion.C
  framework/src/dgkernels/DGDiffusion.C
  test/tests/dgkernels/2d_diffusion_dg/gold/constMonomial.e-s003
  test/tests/dgkernels/2d_diffusion_dg/tests
Labels: PR: Failed but allowed

#21917 Correct logic for from+to `MultiAppTransfer`
  framework/include/transfers/MultiAppTransfer.h
  framework/src/transfers/MultiAppPostprocessorInterpolationTransfer.C
  framework/src/transfers/MultiAppTransfer.C
  test/tests/transfers/multiapp_postprocessor_interpolation_transfer/tests
Labels: PR: Failed but allowed

#21839 Support CoupledVectorTag to Array Variable
  framework/doc/content/source/auxkernels/TagVectorArrayVariableValueAux.md
  framework/include/auxkernels/TagAuxBase.h
  framework/include/auxkernels/TagVectorArrayVariableValueAux.h
  framework/include/interfaces/Coupleable.h
  framework/src/auxkernels/TagMatrixAux.C
  framework/src/auxkernels/TagVectorArrayVariableAux.C
  framework/src/auxkernels/TagVectorArrayVariableValueAux.C
  framework/src/auxkernels/TagVectorAux.C
  framework/src/interfaces/Coupleable.C
  test/include/auxkernels/TagVectorArrayVariableGradientAux.h
  test/src/auxkernels/TagVectorArrayVariableGradientAux.C
  test/tests/tag/gold/tag-array-grad_out.e
  test/tests/tag/gold/tag-array-var_out.e
  test/tests/tag/tag-array-grad.i
  test/tests/tag/tests
Labels: PR: Failed but allowed

#21831 Flow over circle
  modules/navier_stokes/examples/flow-over-circle/executioner_postprocessor.i
  modules/navier_stokes/examples/flow-over-circle/flow_over_circle-action.i
  modules/navier_stokes/examples/flow-over-circle/flow_over_circle.i
  modules/navier_stokes/examples/flow-over-circle/gold/flow_over_circle-action_out.csv
  modules/navier_stokes/examples/flow-over-circle/gold/flow_over_circle_out.csv
  modules/navier_stokes/examples/flow-over-circle/header.i
  modules/navier_stokes/examples/flow-over-circle/mesh.i
  modules/navier_stokes/examples/flow-over-circle/tests
Labels: PR: Failed but allowed

#21933 Unify libmesh re-bootstrap for arm mac
  conda/libmesh/build.sh
  conda/libmesh/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/template/conda_build_config.yaml
  scripts/configure_libmesh.sh
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed

#21954 Update get_repo_revision.py to get rid of deprecation warning due to …
  framework/scripts/get_repo_revision.py
Labels: PR: Failed but allowed

#21944 Fix radial averaging system
  framework/include/userobject/RadialAverage.h
  framework/src/userobject/RadialAverage.C
  framework/src/userobject/ThreadedRadialAverageLoop.C
  modules/tensor_mechanics/test/tests/scalar_material_damage/ad_nonlocal_scalar_damage.i
  modules/tensor_mechanics/test/tests/scalar_material_damage/nonlocal_scalar_damage.i
  test/tests/userobjects/radial_average/gold/time_changing_test_out.e
  test/tests/userobjects/radial_average/tests
  test/tests/userobjects/radial_average/time_changing_test.i
Labels: PR: Failed but allowed
