Repository idaholab/moose, pull requests merged in 2022-02, with the labels that each got.

#20155 Thread-safe refinement and stateful material property projection
  framework/include/loops/FlagElementsThread.h
  framework/include/loops/ProjectMaterialProperties.h
  framework/src/loops/ProjectMaterialProperties.C
  framework/src/problems/FEProblemBase.C
Labels: PR: Auto Merge

#20195 Fix mirror spec for Yum in Docker CentOS
  docker_ci/yum_installs.sh
Labels: PR: Auto Merge

#20184 Added centering option to PiecewiseConstant
  framework/doc/content/source/functions/PiecewiseConstant.md
  framework/include/functions/PiecewiseConstant.h
  framework/src/functions/PiecewiseConstant.C
  test/tests/functions/piecewise_constant/gold/piecewise_constant_simple_out.csv
  test/tests/functions/piecewise_constant/piecewise_constant_simple.i
  test/tests/functions/piecewise_constant/tests
Labels: PR: Address comments, PR: Failed but allowed

#20218 Fixes tests too heavy for valgrind
  modules/tensor_mechanics/test/tests/lagrangian/total/convergence/L/tests
  modules/tensor_mechanics/test/tests/lagrangian/updated/convergence/L/tests
Labels: PR: Failed but allowed

#20215 Support mortar meshes without corresponding mortar constraints
  framework/include/constraints/ConstraintWarehouse.h
  framework/src/constraints/ConstraintWarehouse.C
  framework/src/systems/NonlinearSystemBase.C
  test/tests/mortar/aux-gap/tests
Labels: PR: Failed but allowed

#20226 Added newsletter for THM integration into MOOSE
  modules/doc/content/newsletter/2022_02.md
Labels: PR: Auto Merge

#20244 Fixup threading for ElementSubdomainModifier
  framework/include/userobject/ElementSubdomainModifier.h
  framework/src/userobject/ElementSubdomainModifier.C
Labels: PR: Ready for review/merge

#20257 Update Reactor Module Documentation
  modules/reactor/doc/content/modules/reactor/index.md
Labels: PR: Auto Merge

#20092 Support QUAD8 element in mortar
  framework/include/utils/MooseLagrangeHelpers.h
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/utils/MortarUtils.C
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gap_heat_transfer_sphere3D.i
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gap_heat_transfer_sphere3D_mortar.i
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gold/gap_heat_transfer_3D_hex20_out_NodalTemperature_0001.csv
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gold/gap_heat_transfer_3D_mortar_HEX20_out_NodalTemperature_0001.csv
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gold/gap_heat_transfer_sphere3D_mortar_out_NodalTemperature_0001.csv
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/gold/gap_heat_transfer_sphere3D_out_NodalTemperature_0001.csv
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/sphere3D.e
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/tests
  test/tests/mortar/continuity-3d-non-conforming/continuity_sphere_hex20.i
  test/tests/mortar/continuity-3d-non-conforming/gold/continuity_sphere_hex20_out.e
  test/tests/mortar/continuity-3d-non-conforming/spheres.jou
  test/tests/mortar/continuity-3d-non-conforming/spheres_hex20.e
  test/tests/mortar/continuity-3d-non-conforming/tests
Labels: PR: Failed but allowed

#20282 Fixes tensor_mechanics action + 2nd order elements
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/test/tests/lagrangian/action/second.exo
  modules/tensor_mechanics/test/tests/lagrangian/action/simple_test.i
  modules/tensor_mechanics/test/tests/lagrangian/action/tests
Labels: PR: Failed but allowed

#20321 Fixed issues with ShaftConnectedPump1Phase
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/source/components/ShaftConnectedPump1Phase.md
  modules/thermal_hydraulics/src/userobjects/ADShaftConnectedPump1PhaseUserObject.C
  modules/thermal_hydraulics/test/tests/components/shaft_connected_pump_1phase/gold/pump_coastdown_out.e
  modules/thermal_hydraulics/test/tests/components/shaft_connected_pump_1phase/gold/shaft_motor_pump_out.e
  modules/thermal_hydraulics/test/tests/components/shaft_connected_pump_1phase/pump_coastdown.i
  modules/thermal_hydraulics/test/tests/components/shaft_connected_pump_1phase/shaft_motor_pump.i
Labels: PR: Failed but allowed

#20153 Add postprocessor for Rayleigh number calcs
  framework/doc/content/source/postprocessors/ElementExtremeFunctorValue.md
  framework/doc/content/source/postprocessors/ElementExtremeValue.md
  framework/include/auxkernels/ElementUOAux.h
  framework/include/postprocessors/ElementExtremeFunctorValue.h
  framework/src/auxkernels/ElementLengthAux.C
  framework/src/auxkernels/FunctorElementalAux.C
  framework/src/auxkernels/FunctorVectorElementalAux.C
  framework/src/auxkernels/InterfaceValueUserObjectAux.C
  framework/src/fvbcs/FVFluxBC.C
  framework/src/postprocessors/ElementExtremeFunctorValue.C
  framework/src/problems/FEProblemBase.C
  modules/navier_stokes/doc/content/modules/navier_stokes/pinsfv.md
  modules/navier_stokes/doc/content/source/fvbcs/INSFVSymmetryScalarBC.md
  modules/navier_stokes/doc/content/source/postprocessors/RayleighNumber.md
  modules/navier_stokes/include/auxkernels/WallFunctionWallShearStressAux.h
  modules/navier_stokes/include/auxkernels/WallFunctionYPlusAux.h
  modules/navier_stokes/include/postprocessors/RayleighNumber.h
  modules/navier_stokes/src/auxkernels/Courant.C
  modules/navier_stokes/src/auxkernels/INSCourant.C
  modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
  modules/navier_stokes/src/auxkernels/WallFunctionYPlusAux.C
  modules/navier_stokes/src/postprocessors/RayleighNumber.C
  modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/functorfluidprops.i
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/gold/functorfluidprops_out.e
  modules/navier_stokes/test/tests/postprocessors/flow_rates/conservation_INSFE.i
  modules/navier_stokes/test/tests/postprocessors/flow_rates/conservation_INSFV.i
  modules/navier_stokes/test/tests/postprocessors/flow_rates/conservation_PINSFV.i
  modules/navier_stokes/test/tests/postprocessors/flow_rates/expansion_quad.e
  modules/navier_stokes/test/tests/postprocessors/flow_rates/expansion_tri.e
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_INSFE.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_INSFV_quad_rz.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_INSFV_quad_xy.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_INSFV_quad_xy_noslip.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_INSFV_quad_xy_upwind.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_INSFV_tri_xy.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_PINSFV_quad_rz.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_PINSFV_quad_xy.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_PINSFV_quad_xy_noslip.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_PINSFV_quad_xy_upwind.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/straight_INSFE.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/straight_INSFV.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/straight_PINSFV.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/tests
  modules/navier_stokes/test/tests/postprocessors/rayleigh/gold/natural_convection_out.csv
  modules/navier_stokes/test/tests/postprocessors/rayleigh/natural_convection.i
  modules/navier_stokes/test/tests/postprocessors/rayleigh/tests
  modules/peridynamics/src/auxkernels/BondStatusBasePD.C
  modules/peridynamics/src/auxkernels/RankTwoBasedFailureCriteriaNOSPD.C
  modules/phase_field/src/auxkernels/EBSDReaderPointDataAux.C
  modules/phase_field/test/src/auxkernels/VoronoiICAux.C
  modules/porous_flow/src/auxkernels/PorousFlowDarcyVelocityComponentLowerDimensional.C
  modules/stochastic_tools/test/tests/reporters/sobol/tests
  test/tests/auxkernels/element_length/element_length.i
  test/tests/auxkernels/element_length/gold/element_length_out.e
  test/tests/postprocessors/element_extreme_functor_value/extreme_proxy_value.i
  test/tests/postprocessors/element_extreme_functor_value/gold/extreme_proxy_value_out.csv
  test/tests/postprocessors/element_extreme_functor_value/gold/extreme_value.csv
  test/tests/postprocessors/element_extreme_functor_value/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20327 Skip threads for `finite_volume/ins/channel-flow.singular_two_term_expansion`
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Ready for review/merge

#20330 Avoid relying on to-be-deprecated MeshBase iterators
  framework/include/mesh/MooseMesh.h
  framework/src/mesh/MooseMesh.C
  framework/src/transfers/MultiAppNearestNodeTransfer.C
Labels: PR: Failed but allowed

#20323 Indicate whether parameters are controllable on their documentation
  framework/doc/content/css/moose.css
  framework/doc/content/css/reveal_moose.css
  framework/doc/content/syntax/Controls/index.md
  framework/src/utils/JsonSyntaxTree.C
  modules/doc/content/newsletter/2022_02.md
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/test/content/extensions/appsyntax.md
  python/MooseDocs/test/extensions/test_appsyntax.py
  python/MooseDocs/test/materialize.yml
Labels: PR: Failed but allowed

#19664 Docs for output formatters
  framework/doc/content/source/actions/AddOutputAction.md
  framework/doc/content/source/actions/ReadExecutorParamsAction.md
  framework/doc/content/source/executors/NullExecutor.md
  framework/doc/content/source/outputs/formatters/ExodusFormatter.md
  framework/doc/content/source/outputs/formatters/InputFileFormatter.md
  framework/doc/content/source/outputs/formatters/JsonInputFileFormatter.md
  framework/doc/content/source/outputs/formatters/SONDefinitionFormatter.md
  framework/doc/content/source/outputs/formatters/YAMLFormatter.md
  framework/include/outputs/formatters/ExodusFormatter.h
  framework/include/outputs/formatters/InputFileFormatter.h
  framework/include/outputs/formatters/JsonInputFileFormatter.h
  framework/include/outputs/formatters/SyntaxFormatterInterface.h
  framework/include/outputs/formatters/YAMLFormatter.h
Labels: PR: Failed but allowed

#20346 Reduce number of face gradient computations
  modules/navier_stokes/src/fvkernels/INSFVMixingLengthReynoldsStress.C
Labels: PR: Failed but allowed

#20374 Remove unused variable
  modules/ray_tracing/src/outputs/RayTracingMeshOutput.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#20361 Add ReynoldsNumberFunctorAux
  framework/doc/content/source/materials/VectorMagnitudeFunctorMaterial.md
  framework/include/materials/FunctorMaterial.h
  framework/include/materials/VectorMagnitudeFunctorMaterial.h
  framework/src/materials/VectorMagnitudeFunctorMaterial.C
  modules/navier_stokes/doc/content/source/auxkernels/ReynoldsNumberFunctorAux.md
  modules/navier_stokes/include/auxkernels/ReynoldsNumberFunctorAux.h
  modules/navier_stokes/src/auxkernels/ReynoldsNumberFunctorAux.C
  modules/navier_stokes/src/materials/GeneralFunctorFluidProps.C
  modules/navier_stokes/test/tests/auxkernels/reynolds-number-functor-aux/fe.i
  modules/navier_stokes/test/tests/auxkernels/reynolds-number-functor-aux/fv.i
  modules/navier_stokes/test/tests/auxkernels/reynolds-number-functor-aux/gold/fe_out.e
  modules/navier_stokes/test/tests/auxkernels/reynolds-number-functor-aux/gold/fv_out.e
  modules/navier_stokes/test/tests/auxkernels/reynolds-number-functor-aux/tests
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/gold/functorfluidprops_out.e
  test/tests/materials/functor_properties/vector-magnitude/gold/test_out.e
  test/tests/materials/functor_properties/vector-magnitude/test.i
  test/tests/materials/functor_properties/vector-magnitude/tests
Labels: PR: Failed but allowed

#20368 Fixing non-google search in MooseDocs
  framework/doc/content/js/navigation.js
  python/MooseDocs/extensions/navigation.py
  python/MooseDocs/test/gold/materialize/extensions/algorithm.html
  python/MooseDocs/test/gold/materialize/extensions/amendments.html
  python/MooseDocs/test/gold/materialize/extensions/bibtex.html
  python/MooseDocs/test/gold/materialize/extensions/common.html
  python/MooseDocs/test/gold/materialize/extensions/config.html
  python/MooseDocs/test/gold/materialize/extensions/core.html
  python/MooseDocs/test/gold/materialize/extensions/first.html
  python/MooseDocs/test/gold/materialize/extensions/folder/folder.html
  python/MooseDocs/test/gold/materialize/extensions/folder/index.html
  python/MooseDocs/test/gold/materialize/extensions/graph.html
  python/MooseDocs/test/gold/materialize/extensions/include.html
  python/MooseDocs/test/gold/materialize/extensions/layout.html
  python/MooseDocs/test/gold/materialize/extensions/materialicon.html
  python/MooseDocs/test/gold/materialize/extensions/navigation.html
  python/MooseDocs/test/gold/materialize/extensions/package.html
  python/MooseDocs/test/gold/materialize/extensions/plotly.html
  python/MooseDocs/test/gold/materialize/extensions/preamble.html
  python/MooseDocs/test/gold/materialize/extensions/second.html
  python/MooseDocs/test/gold/materialize/extensions/style.html
  python/MooseDocs/test/gold/materialize/extensions/table.html
  python/MooseDocs/test/gold/materialize/mega.menu.html
Labels: PR: Failed but allowed

#20377 Change C++ standard set by moose-mpich to C++17
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/meta.yaml
  conda/mpich/build.sh
  conda/mpich/conda_build_config.yaml
  conda/mpich/meta.yaml
  conda/petsc/meta.yaml
Labels: PR: Failed but allowed

#20384 Remove set but unsed variable
  modules/porous_flow/src/kernels/PorousFlowDispersiveFlux.C
Labels: PR: Auto Merge

#20395 Remove unused variable in `MultiAppProjectionTransfer`
  framework/src/transfers/MultiAppProjectionTransfer.C
Labels: PR: Auto Merge

#20289 1-numbering option for ElementPropertyFileRead
  modules/tensor_mechanics/doc/content/source/userobjects/ElementPropertyReadFile.md
  modules/tensor_mechanics/include/userobjects/ElementPropertyReadFile.h
  modules/tensor_mechanics/src/userobjects/ElementPropertyReadFile.C
Labels: PR: Failed but allowed

#20401 Rename perf_graph in tests to avoid Outputs/perf_graph=true clobbering
  modules/phase_field/examples/grain_growth/grain_growth_3D.i
  modules/phase_field/test/tests/grain_tracker_test/grain_tracker_remapping_test.i
Labels: PR: Auto Merge

#20404 Remove unused variable in PolycrystalRandomIC.C
  modules/phase_field/src/ics/PolycrystalRandomIC.C
Labels: PR: Failed but allowed
