Repository idaholab/moose, pull requests merged in 2022-09, with the labels that each got.

#21753 Distinguish High Angle and Low Angle GB and Assign different diffusivities or other grain parameters
  modules/phase_field/doc/content/source/auxkernels/SolutionAuxMisorientationBoundary.md
  modules/phase_field/doc/content/source/materials/ComputeGBMisorientationType.md
  modules/phase_field/include/auxkernels/SolutionAuxMisorientationBoundary.h
  modules/phase_field/include/materials/ComputeGBMisorientationType.h
  modules/phase_field/src/auxkernels/SolutionAuxMisorientationBoundary.C
  modules/phase_field/src/materials/ComputeGBMisorientationType.C
  modules/phase_field/test/tests/GBType/EBSD_ThreeGrains.txt
  modules/phase_field/test/tests/GBType/GB_Type_Phase1.i
  modules/phase_field/test/tests/GBType/GB_Type_Phase2.i
  modules/phase_field/test/tests/GBType/gold/GB_Type_Phase1_out.e
  modules/phase_field/test/tests/GBType/gold/GB_Type_Phase2_out.e
  modules/phase_field/test/tests/GBType/tests
Labels: PR: Failed but allowed

#21891 Restoring the ability to swap between underlying containers
  modules/phase_field/include/postprocessors/FeatureFloodCount.h
  modules/phase_field/src/postprocessors/FeatureFloodCount.C
Labels: PR: Failed but allowed

#21990 Added solid_properties module to module loader
  modules/module_loader/src/ModulesApp.C
Labels: PR: Failed but allowed

#21974 Error with better messages
  python/TestHarness/tests/test_FailedJSON.py
  python/TestHarness/tests/tests
  python/TestHarness/util.py
  python/peacock/CheckRequirements.py
Labels: PR: Failed but allowed, PR: Ready for review/merge, PR: Auto Merge

#21999 Fix unused test
  modules/tensor_mechanics/test/tests/jacobian/mc_update6.i
  modules/tensor_mechanics/test/tests/jacobian/tests
Labels: PR: Failed but allowed

#21993 Add heat transfer capablity for thin layer
  modules/heat_conduction/doc/content/media/heat_conduction/three_bl_mesh.png
  modules/heat_conduction/doc/content/media/heat_conduction/three_bl_temp.png
  modules/heat_conduction/doc/content/media/heat_conduction/two_bl_mesh.png
  modules/heat_conduction/doc/content/media/heat_conduction/two_bl_temp.png
  modules/heat_conduction/doc/content/source/interfacekernels/ThinLayerHeatTransfer.md
  modules/heat_conduction/include/interfacekernels/ThinLayerHeatTransfer.h
  modules/heat_conduction/src/interfacekernels/ThinLayerHeatTransfer.C
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/gold/steady_2d_out.e
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/gold/steady_3d_out.e
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/gold/transient_2d_out.e
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/gold/transient_3d_out.e
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/steady_2d.i
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/steady_3d.i
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/tests
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/transient_2d.i
  modules/heat_conduction/test/tests/thin_layer_heat_transfer/transient_3d.i
Labels: PR: Failed but allowed

#21982 Made solid properties module a dependency for THM
  CODEOWNERS
  framework/doc/content/source/functions/MooseParsedFunction.md
  framework/doc/content/syntax/Functions/index.md
  framework/src/functions/MooseParsedFunctionBase.C
  framework/src/utils/InputParameters.C
  modules/doc/config.yml
  modules/doc/content/help/inl/hpc_binary.md
  modules/modules.mk
  modules/solid_properties/doc/content/source/materials/ConstantDensityThermalSolidPropertiesMaterial.md
  modules/solid_properties/doc/content/source/materials/ThermalSolidPropertiesMaterial.md
  modules/solid_properties/include/materials/ConstantDensityThermalSolidPropertiesMaterial.h
  modules/solid_properties/src/materials/ConstantDensityThermalSolidPropertiesMaterial.C
  modules/solid_properties/test/tests/materials/constant_density_thermal_solid_properties/constant_density_thermal_solid_properties.i
  modules/solid_properties/test/tests/materials/constant_density_thermal_solid_properties/gold/constant_density_thermal_solid_properties_out.csv
  modules/solid_properties/test/tests/materials/constant_density_thermal_solid_properties/tests
  modules/thermal_hydraulics/doc/config.yml
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/templates/templates/tutorials/basics/execution.md.template
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/templates/templates/tutorials/basics/input_file.md.template
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/templates/templates/tutorials/basics/output.md.template
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/tutorials/basics/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/tutorials/single_phase_flow/index.md
  modules/thermal_hydraulics/doc/sqa_thermal_hydraulics.yml
  modules/thermal_hydraulics/src/base/ThermalHydraulicsApp.C
  modules/thermal_hydraulics/test/tests/components/heat_structure_cylindrical/phy.rz_mats.i
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed

#22001 Add September 2022 news template and make August 2022 news public
  modules/doc/content/newsletter/2022_08.md
  modules/doc/content/newsletter/2022_09.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#22003 Initialize neighbor variables during stateful prop onInterface
  framework/src/loops/ComputeMaterialsObjectThread.C
Labels: PR: Failed but allowed

#21984 Fix gather proxy extreme MPI issue
  framework/include/postprocessors/ElementExtremeFunctorValue.h
  framework/include/postprocessors/ElementExtremeValue.h
  framework/include/postprocessors/ExtremeValueBase.h
  framework/include/postprocessors/NodalExtremeValue.h
  framework/include/userobject/UserObject.h
  framework/src/postprocessors/ElementExtremeFunctorValue.C
  framework/src/postprocessors/ElementExtremeValue.C
  framework/src/postprocessors/ExtremeValueBase.C
  framework/src/postprocessors/NodalExtremeValue.C
  test/tests/postprocessors/element_extreme_functor_value/gold/extreme_proxy_value_out.csv
  test/tests/postprocessors/element_extreme_value/gold/element_proxy_extreme_value_out.csv
  test/tests/postprocessors/nodal_extreme_value/gold/nodal_proxy_extreme_value_out.csv
  test/tests/postprocessors/nodal_extreme_value/nodal_proxy_extreme_value.i
Labels: PR: Failed but allowed, PR: Ready for review/merge

#22039 Actually use free charge parameter in PerpendicularElectricFieldInterface
  modules/electromagnetics/include/interfacekernels/PerpendicularElectricFieldInterface.h
  modules/electromagnetics/src/interfacekernels/PerpendicularElectricFieldInterface.C
  modules/electromagnetics/test/tests/interfacekernels/electromagnetic_interfaces/combined_props.i
  modules/electromagnetics/test/tests/interfacekernels/electromagnetic_interfaces/gold/combined_props_out.e
  modules/electromagnetics/test/tests/interfacekernels/electromagnetic_interfaces/gold/combined_props_zero_free_charge_out.e
  modules/electromagnetics/test/tests/interfacekernels/electromagnetic_interfaces/tests
Labels: PR: Ready for review/merge

#22037 Some NSFV updates
  modules/navier_stokes/doc/content/source/fvbcs/PWCNSFVMomentumFluxBC.md
  modules/navier_stokes/doc/content/source/fvbcs/WCNSFVMomentumFluxBC.md
  modules/navier_stokes/include/actions/NSFVAction.h
  modules/navier_stokes/include/fvbcs/PWCNSFVMomentumFluxBC.h
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/src/fvbcs/PWCNSFVMomentumFluxBC.C
  modules/navier_stokes/src/fvbcs/WCNSFVMomentumFluxBC.C
  modules/navier_stokes/test/tests/finite_volume/pwcns/boundary_conditions/flux_bcs_mdot-action.i
  modules/navier_stokes/test/tests/finite_volume/pwcns/boundary_conditions/gold/flux_bcs_mdot-action_out.e
  modules/navier_stokes/test/tests/finite_volume/pwcns/boundary_conditions/tests
Labels: PR: Failed but allowed

#22021 Enable scaling grouping with scalar variables
  framework/doc/content/source/systems/DisplacedSystem.md
  framework/doc/content/source/systems/NonlinearEigenSystem.md
  framework/doc/content/syntax/Systems/index.md
  framework/include/fviks/FVScalarLagrangeMultiplierInterface.h
  framework/include/systems/NonlinearSystemBase.h
  framework/include/variables/VariableWarehouse.h
  framework/src/systems/NonlinearSystemBase.C
  modules/doc/config.yml
  modules/external_petsc_solver/doc/content/source/problems/ExternalPETScProblem.md
  test/tests/scaling/scalar-field-grouping/gold/test_out.e
  test/tests/scaling/scalar-field-grouping/test.i
  test/tests/scaling/scalar-field-grouping/tests
Labels: PR: Failed but allowed

#22059 Add `skip_coordinate_collapsing` param to all MultiAppTransfers
  framework/src/transfers/MultiAppMeshFunctionTransfer.C
  framework/src/transfers/MultiAppPostprocessorInterpolationTransfer.C
  framework/src/transfers/MultiAppTransfer.C
  framework/src/transfers/MultiAppUserObjectTransfer.C
Labels: PR: Failed but allowed

#21981 Various changes to support AD in 2 phase flow and NCG
  framework/include/auxkernels/MaterialAuxBase.h
  framework/include/auxkernels/MaterialStdVectorAux.h
  framework/include/auxkernels/MaterialStdVectorAuxBase.h
  framework/include/materials/MaterialData.h
  framework/src/auxkernels/MaterialStdVectorAux.C
  modules/fluid_properties/include/userobjects/IdealRealGasMixtureFluidProperties.h
  modules/fluid_properties/include/userobjects/VaporMixtureFluidProperties.h
  modules/fluid_properties/src/userobjects/IdealRealGasMixtureFluidProperties.C
  modules/fluid_properties/src/userobjects/VaporMixtureFluidProperties.C
  modules/fluid_properties/unit/src/IdealRealGasMixtureFluidPropertiesTest.C
Labels: PR: Failed but allowed

#21882 NodalConstraints should support different variables on primary and secondary node sets
  framework/include/constraints/NodalConstraint.h
  framework/src/constraints/NodalConstraint.C
  modules/tensor_mechanics/src/constraints/NodalFrictionalConstraint.C
  modules/tensor_mechanics/src/constraints/NodalStickConstraint.C
  test/tests/constraints/nodal_constraint/gold/linear_nodal_constraint_different_variables_out.e
  test/tests/constraints/nodal_constraint/linear_nodal_constraint_different_variables.i
  test/tests/constraints/nodal_constraint/tests
Labels: PR: Failed but allowed

#22034 Get error message for retrieving non-existent AD material property
  framework/include/materials/MaterialPropertyInterface.h
  test/tests/materials/material/material_block_bound_check.i
  test/tests/materials/material/tests
  test/tests/materials/material_property_interface/nonexistent_mat_prop.i
  test/tests/materials/material_property_interface/tests
Labels: PR: Failed but allowed

#22085 Remove unnecessary gpHandler access from GP surrogate
  modules/stochastic_tools/src/surrogates/GaussianProcess.C
Labels: PR: Failed but allowed

#22088 Restore MooseDocs functionality for Python 3.10 on Darwin
  python/MooseDocs/base/executioners.py
Labels: PR: Failed but allowed

#21928 Add harmonic interpolation for FV diffusion kernel.
  framework/doc/content/source/fvkernels/FVDiffusion.md
  framework/include/fviks/FVDiffusionInterface.h
  framework/include/fviks/FVOneVarDiffusionInterface.h
  framework/include/fvkernels/FVDiffusion.h
  framework/include/postprocessors/InterfaceDiffusiveFluxIntegral.h
  framework/include/utils/MathFVUtils.h
  framework/include/utils/MooseTypes.h
  framework/src/fviks/FVDiffusionInterface.C
  framework/src/fviks/FVOneVarDiffusionInterface.C
  framework/src/fvkernels/FVDiffusion.C
  framework/src/postprocessors/InterfaceDiffusiveFluxIntegral.C
  test/tests/fviks/diffusion/gold/harmonic.e
  test/tests/fviks/diffusion/gold/test_out.e
  test/tests/fviks/diffusion/test.i
  test/tests/fviks/diffusion/tests
  test/tests/fviks/one-var-diffusion/gold/test_out.e
  test/tests/fviks/one-var-diffusion/no-ik.i
  test/tests/fviks/one-var-diffusion/test.i
  test/tests/fviks/one-var-diffusion/test.py
  test/tests/fviks/one-var-diffusion/tests
  test/tests/fvkernels/block-restriction/1d.i
  test/tests/fvkernels/block-restriction/fv-and-fe-block-restriction.i
  test/tests/fvkernels/block-restriction/just-mat-blk-restriction.i
  test/tests/fvkernels/fv-to-fe-coupling/1d.i
  test/tests/fvkernels/mms/harmonic_interpolation/diffusion.i
  test/tests/fvkernels/mms/harmonic_interpolation/test.py
  test/tests/fvkernels/mms/harmonic_interpolation/tests
  test/tests/materials/boundary_material/fv_material_quadrature.i
  test/tests/materials/piecewise_by_block_material/test.i
  test/tests/materials/piecewise_by_block_material/test_functor.i
  test/tests/postprocessors/interface_diffusive_flux/gold/InterfaceDiffusiveFluxIntegral_fv-harmonic.csv
  test/tests/postprocessors/interface_diffusive_flux/interface_diffusive_flux_fv.i
  test/tests/postprocessors/interface_diffusive_flux/tests
Labels: PR: Failed but allowed

#22094 Renamed warn_unused to allow_unused #22052
  framework/src/base/MooseApp.C
  python/TestHarness/TestHarness.py
  python/TestHarness/testers/RunApp.py
  python/chigger/utils/Options.py
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed

#22078 Ghost RC coefficients near postprocessing boundaries
  framework/include/interfaces/Coupleable.h
  framework/include/mesh/MooseMesh.h
  framework/src/mesh/MooseMesh.C
  modules/navier_stokes/include/materials/RhoFromPTFunctorMaterial.h
  modules/navier_stokes/include/postprocessors/VolumetricFlowRate.h
  modules/navier_stokes/include/userobjects/INSFVRhieChowInterpolator.h
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/src/materials/RhoFromPTFunctorMaterial.C
  modules/navier_stokes/src/postprocessors/VolumetricFlowRate.C
  modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
  modules/navier_stokes/test/tests/postprocessors/flow_rates/tests
Labels: PR: Failed but allowed

#22150 Improve fluid properties module documentation
  modules/fluid_properties/doc/content/modules/fluid_properties/index.md
  modules/fluid_properties/doc/content/source/userobjects/SinglePhaseFluidProperties.md
  modules/fluid_properties/doc/content/syntax/FluidProperties/index.md
Labels: C: Modules/Fluid Properties

#21854 FancyExtruderGenerator Enhancement with Axial Biasing, Boundary Swap,…
  framework/doc/content/source/meshgenerators/AdvancedExtruderGenerator.md
  framework/doc/content/source/meshgenerators/FancyExtruderGenerator.md
  framework/include/meshgenerators/AdvancedExtruderGenerator.h
  framework/src/meshgenerators/AdvancedExtruderGenerator.C
  modules/doc/content/application_usage/input_syntax.md
  modules/doc/content/newsletter/2019_06.md
  modules/reactor/doc/content/source/meshgenerators/AssemblyMeshGenerator.md
  modules/reactor/doc/content/source/meshgenerators/CoreMeshGenerator.md
  modules/reactor/doc/content/source/meshgenerators/PinMeshGenerator.md
  modules/reactor/src/meshgenerators/AssemblyMeshGenerator.C
  modules/reactor/src/meshgenerators/CoreMeshGenerator.C
  modules/reactor/src/meshgenerators/PinMeshGenerator.C
  test/tests/mesh/splitting/extrude_from_split.i
  test/tests/meshgenerators/advanced_extruder_generator/advanced_extruder_then_parsed_gen_sideset.i
  test/tests/meshgenerators/advanced_extruder_generator/advanced_extruder_with_boundary_swap.i
  test/tests/meshgenerators/advanced_extruder_generator/advanced_extruder_with_element_extra_integer_swap.i
  test/tests/meshgenerators/advanced_extruder_generator/advanced_extruder_with_interface_boundaries.i
  test/tests/meshgenerators/advanced_extruder_generator/elem_flip.i
  test/tests/meshgenerators/advanced_extruder_generator/gen_extrude.i
  test/tests/meshgenerators/advanced_extruder_generator/gold/advanced_extruder_then_parsed_gen_sideset_in.e
  test/tests/meshgenerators/advanced_extruder_generator/gold/advanced_extruder_with_boundary_swap_in.e
  test/tests/meshgenerators/advanced_extruder_generator/gold/advanced_extruder_with_element_extra_integer_swap_out.e
  test/tests/meshgenerators/advanced_extruder_generator/gold/advanced_extruder_with_interface_boundaries_in.e
  test/tests/meshgenerators/advanced_extruder_generator/gold/elem_flip_in.e
  test/tests/meshgenerators/advanced_extruder_generator/gold/gen_extrude_bias_in.e
  test/tests/meshgenerators/advanced_extruder_generator/gold/gen_extrude_flip_in.e
  test/tests/meshgenerators/advanced_extruder_generator/gold/gen_extrude_in.e
  test/tests/meshgenerators/advanced_extruder_generator/mesh_2d.e
  test/tests/meshgenerators/advanced_extruder_generator/need-neighbors.i
  test/tests/meshgenerators/advanced_extruder_generator/tests
  test/tests/meshgenerators/block_deletion_generator/block_deletion_not_prepared.i
  test/tests/meshgenerators/plane_id_mesh_generator/plane_id_pin3d.i
Labels: PR: Failed but allowed

#21869 Enables libmesh preconditioner reuse capability
  framework/doc/content/source/systems/NonlinearSystem.md
  framework/src/executioners/FEProblemSolve.C
  modules/tensor_mechanics/test/tests/preconditioner_reuse/convergence.i
  modules/tensor_mechanics/test/tests/preconditioner_reuse/gold/base_case.csv
  modules/tensor_mechanics/test/tests/preconditioner_reuse/gold/reuse_case.csv
  modules/tensor_mechanics/test/tests/preconditioner_reuse/tests
  test/tests/preconditioners/reuse/convergence.i
  test/tests/preconditioners/reuse/gold/base_case.csv
  test/tests/preconditioners/reuse/gold/mesh_case.csv
  test/tests/preconditioners/reuse/gold/reuse_case.csv
  test/tests/preconditioners/reuse/tests
Labels: PR: Failed but allowed

#22115 Mortar constraint formulation of Interface Joule Heating
  modules/heat_conduction/doc/content/source/constraints/ADInterfaceJouleHeatingConstraint.md
  modules/heat_conduction/include/constraints/ADInterfaceJouleHeatingConstraint.h
  modules/heat_conduction/src/constraints/ADInterfaceJouleHeatingConstraint.C
  modules/heat_conduction/src/constraints/ModularGapConductanceConstraint.C
  modules/heat_conduction/test/tests/interface_heating_mortar/constraint_joule_heating_dual_material.i
  modules/heat_conduction/test/tests/interface_heating_mortar/constraint_joule_heating_dual_material_insulated.i
  modules/heat_conduction/test/tests/interface_heating_mortar/constraint_joule_heating_offset_single_material_insulated.i
  modules/heat_conduction/test/tests/interface_heating_mortar/constraint_joule_heating_single_material.i
  modules/heat_conduction/test/tests/interface_heating_mortar/constraint_joule_heating_single_material_insulated.i
  modules/heat_conduction/test/tests/interface_heating_mortar/gold/constraint_joule_heating_dual_material_insulated_out.csv
  modules/heat_conduction/test/tests/interface_heating_mortar/gold/constraint_joule_heating_dual_material_out.csv
  modules/heat_conduction/test/tests/interface_heating_mortar/gold/constraint_joule_heating_offset_single_material_insulated_out.csv
  modules/heat_conduction/test/tests/interface_heating_mortar/gold/constraint_joule_heating_single_material_insulated_out.csv
  modules/heat_conduction/test/tests/interface_heating_mortar/gold/constraint_joule_heating_single_material_out.csv
  modules/heat_conduction/test/tests/interface_heating_mortar/gold/transient_joule_heating_constraint_out.csv
  modules/heat_conduction/test/tests/interface_heating_mortar/tests
  modules/heat_conduction/test/tests/interface_heating_mortar/transient_joule_heating_constraint.i
Labels: PR: Failed but allowed

#22045 Add new generic setup function in SetupInterface
  framework/doc/content/source/interfaces/SetupInterface.md
  framework/include/base/MooseFunctor.h
  framework/include/interfaces/SetupInterface.h
  framework/include/linesearches/LineSearch.h
  framework/include/outputs/OutputWarehouse.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/include/systems/AuxiliarySystem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/include/systems/SystemBase.h
  framework/include/variables/VariableWarehouse.h
  framework/include/warehouses/MooseObjectWarehouse.h
  framework/src/outputs/OutputWarehouse.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  framework/src/variables/VariableWarehouse.C
  test/include/postprocessors/TestPostprocessor.h
  test/src/postprocessors/TestPostprocessor.C
Labels: PR: Failed but allowed

#22265 Made location=outside actually work in sidesets_bounding_box_generator.C
  framework/src/meshgenerators/SideSetsFromBoundingBoxGenerator.C
  test/tests/meshgenerators/sidesets_bounding_box_generator/generate_outside.i
  test/tests/meshgenerators/sidesets_bounding_box_generator/gold/generate_outside_in.e
  test/tests/meshgenerators/sidesets_bounding_box_generator/tests
Labels: PR: Failed but allowed

#22140 Added check for non-linear var inclusion in MooseParsedFunctionBase.C
  framework/src/functions/MooseParsedFunction.C
  test/tests/functions/parsed/tests
Labels: PR: Failed but allowed

#22269 Remove far-away replicated mesh ghosted elements from VFR boundary ghosting
  modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
Labels: PR: Failed but allowed
