Repository idaholab/moose, pull requests merged in 2022-11, with the labels that each got.

#22552 Fix AzimuthalBlockSplitGenerator Bug
  modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C
  modules/reactor/test/tests/meshgenerators/azimuthal_block_split_generator/non_replicated.i
Labels: PR: Failed but allowed

#21448 create a blocks to mesh converter to support the development of the S…
  framework/doc/content/source/meshgenerators/BlockToMeshConverterGenerator.md
  framework/include/meshgenerators/BlockToMeshConverterGenerator.h
  framework/src/meshgenerators/BlockToMeshConverterGenerator.C
  test/tests/meshgenerators/block_to_mesh_converter_generator/3dmultiblock.e
  test/tests/meshgenerators/block_to_mesh_converter_generator/conv_2dblock.i
  test/tests/meshgenerators/block_to_mesh_converter_generator/conv_lowerDblock.i
  test/tests/meshgenerators/block_to_mesh_converter_generator/conv_multiblock.i
  test/tests/meshgenerators/block_to_mesh_converter_generator/conv_simple_2dblock.i
  test/tests/meshgenerators/block_to_mesh_converter_generator/gold/conv_2dblock_in.e
  test/tests/meshgenerators/block_to_mesh_converter_generator/gold/conv_lowerDblock_in.e
  test/tests/meshgenerators/block_to_mesh_converter_generator/gold/conv_multiblock_in.e
  test/tests/meshgenerators/block_to_mesh_converter_generator/gold/conv_simple_2dblock_in.e
  test/tests/meshgenerators/block_to_mesh_converter_generator/mixedDimMesh.e
  test/tests/meshgenerators/block_to_mesh_converter_generator/multiblock.e
  test/tests/meshgenerators/block_to_mesh_converter_generator/tests
Labels: PR: Auto Merge

#22561 Fix missing member
  framework/src/variables/MooseVariableFV.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#22564 Add submodule init at tail end of Dockerfile
  docker_ci/Dockerfile
Labels: PR: Failed but allowed

#22566 Prevent gap heat transfer test from timing out
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar/tests
Labels: PR: Failed but allowed

#21573 Create sideset extrusion generator
  framework/doc/content/source/meshgenerators/MeshExtruderGenerator.md
  framework/doc/content/source/meshgenerators/SideSetExtruderGenerator.md
  framework/doc/content/source/meshgenerators/StitchedMeshGenerator.md
  framework/include/meshgenerators/SideSetExtruderGenerator.h
  framework/src/meshgenerators/SideSetExtruderGenerator.C
  test/tests/meshgenerators/sideset_extruder_generator/3d_serrated_multiblock.e
  test/tests/meshgenerators/sideset_extruder_generator/external_generators.i
  test/tests/meshgenerators/sideset_extruder_generator/extrude_cube.i
  test/tests/meshgenerators/sideset_extruder_generator/extrude_cube.i-e
  test/tests/meshgenerators/sideset_extruder_generator/extrude_multiblock.i
  test/tests/meshgenerators/sideset_extruder_generator/extrude_multiblock.i-e
  test/tests/meshgenerators/sideset_extruder_generator/extrude_square.i
  test/tests/meshgenerators/sideset_extruder_generator/extrude_square.i-e
  test/tests/meshgenerators/sideset_extruder_generator/gen_extrude.i
  test/tests/meshgenerators/sideset_extruder_generator/gold/external_generators_in.e
  test/tests/meshgenerators/sideset_extruder_generator/gold/extrude_cube_in.e
  test/tests/meshgenerators/sideset_extruder_generator/gold/extrude_multiblock_in.e
  test/tests/meshgenerators/sideset_extruder_generator/gold/extrude_square_in.e
  test/tests/meshgenerators/sideset_extruder_generator/tests
Labels: PR: Failed but allowed

#22562 Petsc 3.18 fixes
  framework/src/utils/PetscDMMoose.C
Labels: PR: Failed but allowed

#22575 Prevent race condition in clearing point locator
  framework/include/loops/UpdateDisplacedMeshThread.h
  framework/src/loops/UpdateDisplacedMeshThread.C
  framework/src/problems/DisplacedProblem.C
Labels: PR: Failed but allowed

#22607 Bug fix of UniqueExtraIDMeshGenerator in parallel execution
  framework/src/meshgenerators/UniqueExtraIDMeshGenerator.C
  framework/src/utils/MooseMeshUtils.C
  modules/reactor/src/meshgenerators/DepletionIDGenerator.C
  test/tests/meshgenerators/unique_extra_id_mesh_generator/gold/unique_id_cut_out.e
  test/tests/meshgenerators/unique_extra_id_mesh_generator/tests
  test/tests/meshgenerators/unique_extra_id_mesh_generator/unique_id_cut.i
  test/tests/meshgenerators/unique_extra_id_mesh_generator/unique_id_cut_in.e
Labels: PR: Failed but allowed

#22608 Improved stub determination logic
  python/moosesqa/check_syntax.py
Labels: PR: Failed but allowed, C: Python

#22580 GenericConstantRankTwoTensor.C instantiating the templated classes.
  framework/src/materials/GenericConstantRankTwoTensor.C
Labels: PR: Failed but allowed

#22624 Get valgrind working with python
  modules/heat_conduction/tutorials/introduction/tests
  modules/stochastic_tools/examples/paper/tests
  modules/stochastic_tools/test/tests/samplers/AdaptiveImportanceSampler/tests
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/tests
  modules/stochastic_tools/test/tests/samplers/latin_hypercube/tests
  test/tests/fvkernels/mms/harmonic_interpolation/tests
  test/tests/fvkernels/mms/skewness-correction/adv-diff-react/tests
  test/tests/fvkernels/mms/skewness-correction/diffusion/tests
  test/tests/fvkernels/mms/skewness-correction/two_term_extrapol/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#22629 Guard eigenproblem implementations
  framework/include/problems/EigenProblem.h
Labels: PR: Failed but allowed, PR: Auto Merge

#22568 Make the pressure action require displacements,
  modules/tensor_mechanics/examples/bridge/bridge.i
  modules/tensor_mechanics/examples/bridge/bridge_large_strain.i
  modules/tensor_mechanics/src/actions/PressureAction.C
Labels: PR: Failed but allowed

#22647 Adding thermal expansion derivatives in stiffened gas fluid properties
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
  modules/fluid_properties/unit/src/StiffenedGasFluidPropertiesTest.C
Labels: PR: Failed but allowed

#21592 Biologically-catalysed reactions in Geochemistry
  modules/geochemistry/database/moose_geochemdb.json
  modules/geochemistry/doc/content/modules/geochemistry/index.md
  modules/geochemistry/doc/content/modules/geochemistry/tests_and_examples/bio_arsenate.md
  modules/geochemistry/doc/content/modules/geochemistry/tests_and_examples/bio_death.md
  modules/geochemistry/doc/content/modules/geochemistry/tests_and_examples/bio_sulfate.md
  modules/geochemistry/doc/content/modules/geochemistry/tests_and_examples/bio_zoning.md
  modules/geochemistry/doc/content/modules/geochemistry/tests_and_examples/index.md
  modules/geochemistry/doc/content/modules/geochemistry/theory/biogeochemistry.md
  modules/geochemistry/doc/content/modules/geochemistry/theory/index.md
  modules/geochemistry/doc/content/source/userobjects/GeochemistryKineticRate.md
  modules/geochemistry/include/userobjects/GeochemistryKineticRate.h
  modules/geochemistry/include/utils/GeochemicalSolver.h
  modules/geochemistry/include/utils/GeochemicalSystem.h
  modules/geochemistry/include/utils/GeochemistryKineticRateCalculator.h
  modules/geochemistry/include/utils/PertinentGeochemicalSystem.h
  modules/geochemistry/src/userobjects/GeochemistryKineticRate.C
  modules/geochemistry/src/utils/GeochemicalSolver.C
  modules/geochemistry/src/utils/GeochemicalSystem.C
  modules/geochemistry/src/utils/GeochemistryKineticRateCalculator.C
  modules/geochemistry/src/utils/GeochemistrySpeciesSwapper.C
  modules/geochemistry/src/utils/PertinentGeochemicalSystem.C
  modules/geochemistry/test/tests/kinetics/bio_arsenate.py
  modules/geochemistry/test/tests/kinetics/bio_arsenate0.i
  modules/geochemistry/test/tests/kinetics/bio_arsenate1.i
  modules/geochemistry/test/tests/kinetics/bio_death.i
  modules/geochemistry/test/tests/kinetics/bio_death.py
  modules/geochemistry/test/tests/kinetics/bio_sulfate.py
  modules/geochemistry/test/tests/kinetics/bio_sulfate_0.i
  modules/geochemistry/test/tests/kinetics/bio_sulfate_1.i
  modules/geochemistry/test/tests/kinetics/bio_sulfate_2.i
  modules/geochemistry/test/tests/kinetics/bio_zoning.py
  modules/geochemistry/test/tests/kinetics/bio_zoning_conc.i
  modules/geochemistry/test/tests/kinetics/bio_zoning_flow.i
  modules/geochemistry/test/tests/kinetics/gold/bio_arsenate1_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_arsenate1_shortdt_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_death_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_death_small_dt_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_sulfate_1_21_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_sulfate_1_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_sulfate_2_21_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_sulfate_2_out.csv
  modules/geochemistry/test/tests/kinetics/gold/bio_zoning_flow_out_react0.e
  modules/geochemistry/test/tests/kinetics/kinetic_albite.i
  modules/geochemistry/test/tests/kinetics/tests
  modules/geochemistry/test/tests/time_dependent_reactions/flushing.i
  modules/geochemistry/test/tests/time_dependent_reactions/flushing_case1.i
  modules/geochemistry/test/tests/time_dependent_reactions/flushing_case2.i
  modules/geochemistry/test/tests/time_dependent_reactions/flushing_case3.i
  modules/geochemistry/unit/database/moose_testdb_e_strange.json
  modules/geochemistry/unit/src/GeochemicalSolverTest.C
  modules/geochemistry/unit/src/GeochemicalSystemTest.C
  modules/geochemistry/unit/src/GeochemistryKineticRateCalculatorTest.C
  modules/geochemistry/unit/src/GeochemistrySpeciesSwapperTest.C
  modules/geochemistry/unit/src/MinimalGeochemicalSystemTest.C
Labels: PR: Failed but allowed

#22663 Heavy valgrind for mortar thermomech tests
  modules/contact/test/tests/mortar_tm/2d/ad_frictionless_sec/tests
Labels: PR: Failed but allowed

#22670 Fix moose to be able to compile on Sawtooth
  framework/src/variables/MooseVariableFV.C
Labels: PR: Failed but allowed

#22657 Handle new PBS exit codes
  python/TestHarness/schedulers/RunPBS.py
  scripts/are_queued_jobs_finished.py
Labels: PR: Failed but allowed

#22672 Valgrind contact heavy
  modules/contact/test/tests/mortar_tm/2d/ad_frictional/tests
Labels: PR: Failed but allowed

#22677 Allow whitespace between logic operator and version in specs
  python/TestHarness/util.py
Labels: PR: Failed but allowed

#22675 Complement boundary
  framework/include/userobject/ElementSubdomainModifier.h
  framework/src/userobject/ElementSubdomainModifier.C
  test/tests/userobjects/element_subdomain_modifier/complement_boundary.i
  test/tests/userobjects/element_subdomain_modifier/gold/complement_boundary_out.e
  test/tests/userobjects/element_subdomain_modifier/gold/complement_boundary_out.e-s002
  test/tests/userobjects/element_subdomain_modifier/gold/complement_boundary_out.e-s003
  test/tests/userobjects/element_subdomain_modifier/gold/complement_boundary_out.e-s004
  test/tests/userobjects/element_subdomain_modifier/gold/complement_boundary_out.e-s005
  test/tests/userobjects/element_subdomain_modifier/gold/complement_boundary_out.e-s006
  test/tests/userobjects/element_subdomain_modifier/tests
Labels: PR: Failed but allowed

#22634 Fix initialization bug
  framework/contrib/hit/main.cc
Labels: PR: Failed but allowed

#22679 Adding name for wall temperature material
  modules/thermal_hydraulics/include/components/FlowChannelBase.h
  modules/thermal_hydraulics/include/components/HeatTransferBase.h
  modules/thermal_hydraulics/src/components/FlowChannelBase.C
  modules/thermal_hydraulics/src/components/HeatTransferBase.C
Labels: PR: Failed but allowed

#22556 Add a 'replay' feature
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/RunParallel.py
  python/TestHarness/tests/test_Replay.py
  python/TestHarness/tests/tests
Labels: PR: Failed but allowed

#22698 Add libMesh exception::what() to MooseExceptions
  framework/include/loops/ComputeFVFluxThread.h
  framework/include/loops/ThreadedElementLoopBase.h
  framework/src/loops/ComputeJacobianForScalingThread.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/AuxiliarySystem.C
Labels: PR: Failed but allowed

#22737 Add lower-D element map getter in MooseMesh
  framework/include/mesh/MooseMesh.h
Labels: PR: Failed but allowed, PR: Auto Merge

#22613 Declare Mean Thermal Expansion Coefficient
  modules/tensor_mechanics/include/materials/ComputeThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/src/materials/ComputeThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/test/tests/action/ad_converter_action_multi_eigenstrain.i
  modules/tensor_mechanics/test/tests/thermal_expansion/multiple_thermal_eigenstrains.i
Labels: PR: Failed but allowed

#22749 Change default values of three problem parameters
  modules/stochastic_tools/src/actions/StochasticToolsAction.C
Labels: PR: Failed but allowed

#22777 Adjust warning for sibling transfer execute on
  framework/src/transfers/MultiAppTransfer.C
  test/tests/transfers/multiapp_mesh_function_transfer/exec_on_mismatch.i
  test/tests/transfers/multiapp_mesh_function_transfer/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#22756 Fixing timed section name
  framework/src/systems/NonlinearSystemBase.C
Labels: PR: Failed but allowed

#22775 Fix error checks for passive scalar inlet in NSFVAction
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/test/tests/finite_volume/ins/action/errors/tests
Labels: PR: Failed but allowed

#22782 Remove deprecated call to getBoundariesToElems
  framework/src/markers/BoundaryMarker.C
  modules/navier_stokes/src/auxkernels/WallDistanceMixingLengthAux.C
Labels: PR: Failed but allowed

#22785 Don't reinit displaced when it's not needed
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed

#22770 Add VectorPostprocessorSum
  framework/doc/content/source/postprocessors/VectorPostprocessorReductionValue.md
  framework/include/postprocessors/VectorPostprocessorReductionValue.h
  framework/src/postprocessors/VectorPostprocessorReductionValue.C
  test/tests/postprocessors/vector_postprocessor_reduction/gold/vpp_reduction_out.csv
  test/tests/postprocessors/vector_postprocessor_reduction/test_data.csv
  test/tests/postprocessors/vector_postprocessor_reduction/tests
  test/tests/postprocessors/vector_postprocessor_reduction/vpp_reduction.i
Labels: PR: Failed but allowed

#22681 Made version check in util.py more pythonic
  python/TestHarness/util.py
Labels: PR: Failed but allowed

#22801 Trigger meshChanged on a mesh renumbering for exodus output
  framework/include/outputs/Exodus.h
  framework/src/outputs/Exodus.C
Labels: PR: Failed but allowed

#22790 More docs on VPPs and reporters
  framework/doc/content/source/auxkernels/FunctorVectorElementalAux.md
  framework/doc/content/source/auxkernels/NormalizationAux.md
  framework/doc/content/source/reporters/AccumulateReporter.md
  framework/doc/content/source/reporters/ConstantReporter.md
  framework/doc/content/source/reporters/ExtraIDIntegralReporter.md
  framework/doc/content/source/reporters/IterationInfo.md
  framework/doc/content/source/reporters/MeshInfo.md
  framework/doc/content/source/userobject/RadialAverage.md
  framework/doc/content/source/vectorpostprocessors/CSVReader.md
  framework/doc/content/source/vectorpostprocessors/ConstantVectorPostprocessor.md
  framework/doc/content/source/vectorpostprocessors/CylindricalAverage.md
  framework/doc/content/source/vectorpostprocessors/Eigenvalues.md
  framework/doc/content/source/vectorpostprocessors/ElementValueSampler.md
  framework/doc/content/source/vectorpostprocessors/ElementVariablesDifferenceMax.md
  framework/doc/content/source/vectorpostprocessors/ExtraIDIntegralVectorPostprocessor.md
  framework/doc/content/source/vectorpostprocessors/HistogramVectorPostprocessor.md
  framework/doc/content/source/vectorpostprocessors/IntersectionPointsAlongLine.md
  framework/doc/content/source/vectorpostprocessors/LeastSquaresFit.md
  framework/doc/content/source/vectorpostprocessors/LeastSquaresFitHistory.md
  framework/doc/content/source/vectorpostprocessors/LineFunctionSampler.md
  framework/doc/content/source/vectorpostprocessors/LineMaterialRealSampler.md
  framework/doc/content/source/vectorpostprocessors/LineValueSampler.md
  framework/doc/content/source/vectorpostprocessors/MaterialVectorPostprocessor.md
  framework/doc/content/source/vectorpostprocessors/NodalValueSampler.md
  framework/doc/content/source/vectorpostprocessors/PiecewiseFunctionTabulate.md
  framework/doc/content/source/vectorpostprocessors/PointValueSampler.md
  framework/doc/content/source/vectorpostprocessors/SideValueSampler.md
  framework/doc/content/source/vectorpostprocessors/SidesetInfoVectorPostprocessor.md
  framework/doc/content/source/vectorpostprocessors/SpatialUserObjectVectorPostprocessor.md
  framework/doc/content/source/vectorpostprocessors/SphericalAverage.md
  framework/doc/content/source/vectorpostprocessors/VariableValueVolumeHistogram.md
  framework/doc/content/source/vectorpostprocessors/VectorOfPostprocessors.md
  framework/doc/content/source/vectorpostprocessors/WorkBalance.md
  framework/src/vectorpostprocessors/ConstantVectorPostprocessor.C
  framework/src/vectorpostprocessors/ExtraIDIntegralVectorPostprocessor.C
  framework/src/vectorpostprocessors/WorkBalance.C
  test/include/vectorpostprocessors/PiecewiseFunctionTabulate.h
  test/src/vectorpostprocessors/PiecewiseFunctionTabulate.C
Labels: PR: Failed but allowed

#22810 Avoid stopping the calculation, even in devel mode, on harmonic interpolation issues
  framework/include/utils/MathFVUtils.h
Labels: PR: Failed but allowed

#22170 Enable AD interaction integral
  framework/include/materials/MaterialData.h
  modules/tensor_mechanics/include/vectorpostprocessors/InteractionIntegral.h
  modules/tensor_mechanics/src/actions/DomainIntegralAction.C
  modules/tensor_mechanics/src/vectorpostprocessors/InteractionIntegral.C
  modules/tensor_mechanics/test/tests/t_stress/ad_t_stress_ellip_crack_3d.i
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_II_KI_1_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_II_KI_2_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_II_KI_3_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_II_T_1_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_II_T_2_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_II_T_3_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_J_1_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_J_2_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/gold/ad_t_stress_ellip_crack_out_J_3_0001.csv
  modules/tensor_mechanics/test/tests/t_stress/tests
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/howto/thm_ad_migration_guide.md
Labels: PR: Failed but allowed

#22815 Update seacas to v2022-10-14
  conda/seacas/conda_build_config.yaml
  conda/seacas/meta.yaml
  conda/seacas/use-curl-instead-of-wget.patch
Labels: PR: Failed but allowed

#22821 Add valgrind heavy to ad integral tests
  modules/tensor_mechanics/test/tests/t_stress/tests
Labels: PR: Failed but allowed

#22739 Allow Water97FluidProperties to work with a conservative variable set
  framework/src/utils/PetscSupport.C
  modules/fluid_properties/include/userobjects/CaloricallyImperfectGas.h
  modules/fluid_properties/include/userobjects/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/userobjects/StiffenedGasFluidProperties.h
  modules/fluid_properties/include/userobjects/Water97FluidProperties.h
  modules/fluid_properties/include/utils/NewtonInversion.h
  modules/fluid_properties/src/userobjects/CaloricallyImperfectGas.C
  modules/fluid_properties/src/userobjects/SimpleFluidProperties.C
  modules/fluid_properties/src/userobjects/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/userobjects/StiffenedGasFluidProperties.C
  modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
  modules/fluid_properties/src/userobjects/Water97FluidProperties.C
  modules/fluid_properties/src/utils/NewtonInversion.C
  modules/fluid_properties/test/include/utils/FluidPropertiesTestUtils.h
  modules/fluid_properties/test/include/utils/SinglePhaseFluidPropertiesTestUtils.h
  modules/fluid_properties/unit/include/Water97FluidPropertiesTest.h
  modules/fluid_properties/unit/src/NewtonInversionTest.C
  modules/fluid_properties/unit/src/StiffenedGasFluidPropertiesTest.C
  modules/fluid_properties/unit/src/Water97FluidPropertiesTest.C
  modules/thermal_hydraulics/test/tests/components/inlet_mass_flow_rate_1phase/jac.massflowrate_3eqn_water97.i
  modules/thermal_hydraulics/test/tests/components/inlet_mass_flow_rate_1phase/tests
Labels: PR: Failed but allowed

#22644 Fix SolutionUserObjects attempting to import postprocessors with the same name as a field variable
  framework/src/userobject/SolutionUserObject.C
  test/tests/userobjects/solution_user_object/gold/testscalarrename.e
  test/tests/userobjects/solution_user_object/tests
Labels: PR: Failed but allowed
