Repository idaholab/moose, pull requests merged in 2022-07, with the labels that each got.

#21440 Various improvements of PINSFV
  modules/navier_stokes/doc/content/source/fvkernels/PINSFVEnergyAmbientConvection.md
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/src/fvkernels/PINSFVEnergyAmbientConvection.C
  modules/navier_stokes/src/fvkernels/PINSFVMomentumDiffusion.C
  modules/navier_stokes/test/tests/finite_volume/ins/action/errors/tests
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-scalar-transport-action.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Failed but allowed

#21470 Apply shift to move nodes in MoveNodeGenerator
  framework/doc/content/source/meshgenerators/MoveNodeGenerator.md
  framework/include/meshgenerators/MoveNodeGenerator.h
  framework/src/meshgenerators/MoveNodeGenerator.C
  test/tests/meshgenerators/move_node_generator/gold/test3_in.e
  test/tests/meshgenerators/move_node_generator/test3.i
  test/tests/meshgenerators/move_node_generator/tests
Labels: PR: Failed but allowed

#20376 A wrapper for second order tensors to reuse eigenvalue decomposition
  framework/include/utils/FactorizedRankTwoTensor.h
  framework/include/utils/RankTwoTensor.h
  framework/include/utils/RankTwoTensorImplementation.h
  framework/include/utils/SymmetricRankTwoTensor.h
  framework/include/utils/SymmetricRankTwoTensorImplementation.h
  framework/src/utils/FactorizedRankTwoTensor.C
  modules/tensor_mechanics/include/materials/ADComputeFiniteStrain.h
  modules/tensor_mechanics/include/materials/ComputeFiniteStrain.h
  modules/tensor_mechanics/src/materials/ADComputeFiniteStrain.C
  modules/tensor_mechanics/src/materials/ComputeFiniteStrain.C
  unit/src/FactorizedRankTwoTensorTest.C
Labels: PR: Failed but allowed

#21433 Update find hung process
  framework/scripts/find_hung_process.py
Labels: PR: Failed but allowed

#21398 Add an ElementJacobianDamper that runs on the undisplaced mesh
  modules/tensor_mechanics/doc/content/source/dampers/ElementJacobianDamper.md
  modules/tensor_mechanics/doc/content/source/dampers/ReferenceElementJacobianDamper.md
  modules/tensor_mechanics/include/dampers/ReferenceElementJacobianDamper.h
  modules/tensor_mechanics/src/dampers/ReferenceElementJacobianDamper.C
  modules/tensor_mechanics/test/tests/jacobian_damper/cube_load_undisplaced.i
  modules/tensor_mechanics/test/tests/jacobian_damper/gold/cube_load_undisplaced_out.e
  modules/tensor_mechanics/test/tests/jacobian_damper/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#21370 Document RankTwoTensor.h
  framework/doc/content/source/utils/Tensors.md
  framework/include/utils/FactorizedRankTwoTensor.h
  framework/include/utils/RankTwoTensor.h
  framework/include/utils/RankTwoTensorImplementation.h
Labels: PR: Failed but allowed

#21471 Add ability to print clean cyclic graph
  framework/include/interfaces/DependencyResolverInterface.h
  framework/include/utils/DependencyResolver.h
  framework/src/parser/Syntax.C
  unit/src/SyntaxTest.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21504 'constant' is deprecated in Pressure BC
  modules/tensor_mechanics/src/actions/PressureAction.C
Labels: PR: Failed but allowed

#21436 Add option to allow nodal-to-elemental coupling
  framework/include/interfaces/Coupleable.h
  framework/src/interfaces/Coupleable.C
Labels: PR: Failed but allowed

#21469 First stab at JSON dump for the TestHarness
  python/FactorySystem/Factory.py
  python/FactorySystem/InputParameters.py
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21419 Enable manual build of PETSc and libMesh on Apple Silicon
  conda/libmesh-vtk/build.sh
  conda/libmesh-vtk/conda_build_config.yaml
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/conda_build_config.yaml
  conda/libmesh/meta.yaml
  conda/mpich/meta.yaml
  conda/petsc/conda_build_config.yaml
  conda/petsc/meta.yaml
  scripts/apple-silicon-hdf5-autogen.patch
  scripts/configure_petsc.sh
  scripts/update_and_rebuild_libmesh.sh
Labels: PR: Failed but allowed

#21158 Implement compile time derivative framework
  framework/include/utils/CompileTimeDerivatives.h
  unit/src/CompileTimeDerivativesTest.C
Labels: PR: Failed but allowed

#21521 Replace std::enable_if
  framework/include/base/MooseError.h
  framework/include/materials/InterfaceMaterial.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialData.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/include/materials/ThreeMaterialPropertyInterface.h
  framework/include/materials/TwoMaterialPropertyInterface.h
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankTwoTensor.h
  framework/include/utils/SymmetricRankFourTensor.h
  framework/include/utils/SymmetricRankTwoTensor.h
  framework/include/utils/SymmetricRankTwoTensorImplementation.h
  framework/include/utils/VariadicTable.h
  unit/src/RankFourTensorTest.C
  unit/src/SymmetricRankFourTensorTest.C
  unit/src/SymmetricRankTwoTensorTest.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#21534 Remove deprecated para from cavity pressure action
  modules/tensor_mechanics/src/actions/CavityPressureAction.C
Labels: PR: Failed but allowed

#21513 Protect access to tester variable when looking at longest folder jobs
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed

#21511 Silence partially the main app perf graph during the multiapp executions
  framework/src/multiapps/MultiApp.C
Labels: PR: Failed but allowed

#21489 GCC-12 compatibility
  framework/include/userobject/ShapeUserObject.h
Labels: PR: Failed but allowed

#21518 Update SmootherStep for shortcuts to correct behavior
  framework/doc/content/source/utils/MathUtils.md
  framework/include/utils/MathUtils.h
  unit/src/MathUtilsTest.C
Labels: PR: Failed but allowed

#21490 Misc fixups for transfers
  framework/doc/content/source/transfers/MultiAppMeshFunctionTransfer.md
  framework/src/multiapps/MultiApp.C
  framework/src/transfers/MultiAppConservativeTransfer.C
  framework/src/transfers/MultiAppMeshFunctionTransfer.C
  framework/src/transfers/MultiAppNearestNodeTransfer.C
  framework/src/transfers/Transfer.C
  test/tests/transfers/multiapp_copy_transfer/aux_to_primary/from_sub.i
  test/tests/transfers/multiapp_copy_transfer/aux_to_primary/gold/from_sub_out.e
  test/tests/transfers/multiapp_copy_transfer/aux_to_primary/gold/to_sub_out_sub0.e
  test/tests/transfers/multiapp_copy_transfer/aux_to_primary/sub.i
  test/tests/transfers/multiapp_copy_transfer/aux_to_primary/tests
  test/tests/transfers/multiapp_copy_transfer/aux_to_primary/to_sub.i
Labels: PR: Failed but allowed

#21533 Expand isParamValid for Vectors of MooseEnum
  framework/src/utils/InputParameters.C
  unit/src/InputParametersTest.C
Labels: PR: Failed but allowed

#21405 Adding cross validations to SurrogateTrainer base class
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/cross_validation.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/stochastic_tools_examples.md
  modules/stochastic_tools/doc/content/syntax/Trainers/index.md
  modules/stochastic_tools/examples/surrogates/cross_validation/gold/normal_train_and_cv_out_cv_scores_0002.csv
  modules/stochastic_tools/examples/surrogates/cross_validation/gold/uniform_train_and_cv_out_cv_scores_0002.csv
  modules/stochastic_tools/examples/surrogates/cross_validation/normal_train_and_cv.i
  modules/stochastic_tools/examples/surrogates/cross_validation/sub.i
  modules/stochastic_tools/examples/surrogates/cross_validation/tests
  modules/stochastic_tools/examples/surrogates/cross_validation/uniform_train_and_cv.i
  modules/stochastic_tools/include/surrogates/PolynomialRegressionTrainer.h
  modules/stochastic_tools/include/surrogates/SurrogateTrainer.h
  modules/stochastic_tools/include/utils/MultiDimPolynomialGenerator.h
  modules/stochastic_tools/src/surrogates/PolynomialRegressionTrainer.C
  modules/stochastic_tools/src/surrogates/SurrogateTrainer.C
  modules/stochastic_tools/src/utils/MultiDimPolynomialGenerator.C
  modules/stochastic_tools/test/include/reporters/CrossValidationScores.h
  modules/stochastic_tools/test/src/reporters/CrossValidationScores.C
  modules/stochastic_tools/test/tests/surrogates/cross_validation/gold/train_and_cv_out_cv_scores_0002.csv
  modules/stochastic_tools/test/tests/surrogates/cross_validation/tests
  modules/stochastic_tools/test/tests/surrogates/cross_validation/train_and_cv.i
  modules/stochastic_tools/test/tests/surrogates/polynomial_regression/gold/poly_reg_vec_out.json
  modules/stochastic_tools/test/tests/surrogates/polynomial_regression/tests
Labels: PR: Failed but allowed

#21394 New GriddedData constructor and unit test
  framework/include/utils/GriddedData.h
  framework/src/utils/GriddedData.C
  unit/src/GriddedDataTest.C
Labels: PR: Failed but allowed

#21543 Document improvements and more flexibility of interface variable check
  framework/doc/content/syntax/UserObjects/index.md
  framework/include/loops/ComputeUserObjectsThread.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/include/materials/ThreeMaterialPropertyInterface.h
  framework/include/materials/TwoMaterialPropertyInterface.h
  framework/include/mesh/MooseMesh.h
  framework/include/userobject/DomainUserObject.h
  framework/include/utils/MooseMeshUtils.h
  framework/src/loops/ComputeUserObjectsThread.C
  framework/src/mesh/MooseMesh.C
  framework/src/userobject/DomainUserObject.C
  framework/src/utils/MooseMeshUtils.C
Labels: PR: Failed but allowed

#21544 Fix false positive cyclic dep error for block-restricted discrete materials
  framework/include/warehouses/MooseObjectWarehouseBase.h
  framework/src/materials/MaterialWarehouse.C
  test/tests/materials/discrete/block_restricted.i
  test/tests/materials/discrete/tests
  test/tests/mesh/adapt/tests
Labels: PR: Failed but allowed, PR: Auto Merge

#21406 Pressure inlet boundary condition in the Navier Stokes FV action
  modules/navier_stokes/include/actions/NSFVAction.h
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/test/tests/finite_volume/ins/action/errors/tests
  modules/navier_stokes/test/tests/finite_volume/ins/natural_convection/gold/natural_circulation_dogleg_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/natural_convection/natural_circulation_dogleg.i
  modules/navier_stokes/test/tests/finite_volume/ins/natural_convection/tests
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/pressure-interpolation-corrected-action.i
  modules/navier_stokes/test/tests/finite_volume/wcns/natural_convection/gold/natural_circulation_pipe_out.e
  modules/navier_stokes/test/tests/finite_volume/wcns/natural_convection/natural_circulation_pipe.i
  modules/navier_stokes/test/tests/finite_volume/wcns/natural_convection/reference_pipe_natural_convection.py
  modules/navier_stokes/test/tests/finite_volume/wcns/natural_convection/tests
Labels: PR: Failed but allowed

#21509 Remove duplicate volumes, restructure FaceInfo
  framework/include/mesh/ElemInfo.h
  framework/include/mesh/FaceInfo.h
  framework/include/mesh/MooseMesh.h
  framework/include/utils/GreenGaussGradient.h
  framework/include/utils/MathFVUtils.h
  framework/src/fvkernels/FVOrthogonalDiffusion.C
  framework/src/mesh/ElemInfo.C
  framework/src/mesh/FaceInfo.C
  framework/src/mesh/MooseMesh.C
  framework/src/outputs/Exodus.C
  framework/src/utils/MathFVUtils.C
  framework/src/variables/MooseVariableFV.C
  modules/navier_stokes/include/utils/CellCenteredMapFunctor.h
  modules/navier_stokes/unit/src/TestReconstruction.C
  test/tests/fvkernels/mms/mat-advection-diffusion.i
  unit/src/LimitersTest.C
  unit/src/MooseFunctorTest.C
Labels: PR: Failed but allowed

#21555 Bump conda package MPICH to 4.0.2
  conda/libmesh-vtk/conda_build_config.yaml
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/conda_build_config.yaml
  conda/libmesh/meta.yaml
  conda/mpich/conda_build_config.yaml
  conda/mpich/meta.yaml
  conda/petsc/conda_build_config.yaml
  conda/petsc/meta.yaml
Labels: PR: Failed but allowed

#21413 Thermal expansion scaling factor in ComputeMeanThermalExpansionEigenstrainBase
  modules/tensor_mechanics/include/materials/ComputeMeanThermalExpansionEigenstrainBase.h
  modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionEigenstrainBase.C
  modules/tensor_mechanics/src/materials/ComputeMeanThermalExpansionFunctionEigenstrain.C
  modules/tensor_mechanics/test/tests/thermal_expansion_function/gold/mean_scaling_out.csv
  modules/tensor_mechanics/test/tests/thermal_expansion_function/mean.i
  modules/tensor_mechanics/test/tests/thermal_expansion_function/tests
Labels: PR: Failed but allowed

#21483 Fixing documentation typo
  modules/heat_conduction/src/auxkernels/JouleHeatingHeatGeneratedAux.C
Labels: PR: Failed but allowed

#21582 made parse as static function
  framework/include/utils/GriddedData.h
Labels: PR: Failed but allowed

#21612 Add update-motd to apt installs
  docker_ci/apt_installs.sh
Labels: PR: Failed but allowed

#21615 Make some things cleaner for FV presentation
  framework/src/fvkernels/FVDiffusion.C
  framework/src/transfers/MultiAppPostprocessorToAuxScalarTransfer.C
  modules/navier_stokes/test/tests/finite_volume/ins/block_restriction/2d-rc.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/1d-rc.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-mixing-length.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-ambient-convection.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-friction.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-no-slip-extrapolated-outlet-pressure.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-no-slip-outflow-bcs.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-no-slip.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-transient.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-scalar-transport.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/3d-rc-no-slip.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/3d-rc.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/cylindrical/2d-average-no-slip.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/cylindrical/2d-rc-slip.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/cylindrical/diverging.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/cylindrical/no-slip-tris.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/discontinuous-body-forces.i
  modules/navier_stokes/test/tests/finite_volume/ins/exceptions/bad-restriction.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/2d-average-with-temp.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/2d-average.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/2d-rc.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/cylindrical/2d-average-with-temp.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/cylindrical/2d-average.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/cylindrical/2d-rc.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/plane-poiseuille-flow.i
  modules/navier_stokes/test/tests/finite_volume/ins/mms/channel-flow/rotated/rotated-pp-flow.i
  modules/navier_stokes/test/tests/finite_volume/pins/mms/2d-rc.i
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/2d-rc-continuous.i
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/pressure-interpolation-corrected.i
  test/tests/fvkernels/mms/non-orthogonal/advection-diffusion-reaction.i
  tutorials/darcy_thermo_mech/doc/content/workshop/intro/moose_multiphysics.md
  tutorials/darcy_thermo_mech/doc/content/workshop/modules/modules.md
Labels: PR: Failed but allowed, PR: Auto Merge

#21624 Remove libunwind from gperftools doc
  modules/doc/content/application_development/profiling.md
Labels: PR: Failed but allowed

#21575 Add back secondary-primary coupling for penalty mortar
  framework/include/constraints/AutomaticMortarGeneration.h
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/relationshipmanagers/AugmentSparsityOnInterface.C
  test/tests/mortar/continuity-3d-non-conforming/continuity_penalty_sphere_hex8.i
Labels: PR: Failed but allowed

#21639 Fix gh discussion link in contributing.md
  framework/doc/content/framework/contributing.md
Labels: PR: Auto Merge

#21633 Have prepareAux do same thing for FE and FV vars
  framework/include/variables/MooseVariableData.h
  framework/include/variables/MooseVariableDataBase.h
  framework/include/variables/MooseVariableFV.h
  framework/src/variables/MooseVariableData.C
  framework/src/variables/MooseVariableFE.C
  framework/src/variables/MooseVariableFV.C
Labels: PR: Failed but allowed

#21647 Error if user requests nonsense with MooseVariableConstMonomial
  framework/src/variables/MooseVariableConstMonomial.C
  test/tests/variables/fe_monomial_const/tests
Labels: PR: Failed but allowed

#21651 Safer rename-and-shift in GeneratedMeshGenerator
  framework/src/meshgenerators/GeneratedMeshGenerator.C
Labels: PR: Failed but allowed

#21358 Added a check in the makefile for the latest conda build.
  framework/moose.mk
Labels: PR: Failed but allowed

#21659 Fix out of memory issue for mms test in NS module
  modules/navier_stokes/test/tests/finite_volume/pins/mms/2d-rc.i
Labels: PR: Failed but allowed

#21661 Remove valgrind for ambient convection tests
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Failed but allowed

#21694 Fix various issues with new petsc/libmesh version checks in makefile.
  framework/moose.mk
Labels: PR: Failed but allowed

#21683 Allow coincident nodes on mortar boundaries
  framework/src/constraints/AutomaticMortarGeneration.C
  test/tests/mortar/coincident-nodes/test.i
  test/tests/mortar/coincident-nodes/tests
Labels: PR: Failed but allowed

#21667 Dont bypass threads during initial stateful computation
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed

#21696 Add python 3.10 to supported conda versions
  conda/libmesh-vtk/conda_build_config.yaml
  conda/peacock/conda_build_config.yaml
  conda/peacock/meta.yaml
  conda/pyhit/conda_build_config.yaml
  conda/pyhit/meta.yaml
  conda/tools/conda_build_config.yaml
  conda/tools/meta.yaml
Labels: PR: Failed but allowed

#21409 Finite volume Jeffery-Hamel test
  modules/navier_stokes/test/tests/finite_volume/ins/jeffery-hamel/f.csv
  modules/navier_stokes/test/tests/finite_volume/ins/jeffery-hamel/gold/wedge_dirichlet_fv_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/jeffery-hamel/tests
  modules/navier_stokes/test/tests/finite_volume/ins/jeffery-hamel/wedge_8x12.e
  modules/navier_stokes/test/tests/finite_volume/ins/jeffery-hamel/wedge_dirichlet_fv.i
Labels: PR: Failed but allowed, PR: Auto Merge

#21665 Create the moose-seacas package
  conda/seacas/LICENSE
  conda/seacas/build.sh
  conda/seacas/conda_build_config.yaml
  conda/seacas/meta.yaml
  conda/seacas/use-curl-instead-of-wget.patch
Labels: PR: Failed but allowed

#21712 Update the exodiff doc to the new working link
  modules/doc/content/python/testers/Exodiff.md
Labels: PR: Failed but allowed
