Repository idaholab/moose, pull requests merged in 2023-03, with the labels that each got.

#23562 Extend bounds system to finite volume
  framework/include/auxkernels/BoundsAuxBase.h
  framework/src/auxkernels/BoundsAuxBase.C
  framework/src/auxkernels/VariableOldValueBoundsAux.C
  test/tests/auxkernels/bounds/constant_bounds_fv.i
  test/tests/auxkernels/bounds/gold/constant_bounds_fv_out.e
  test/tests/auxkernels/bounds/tests
Labels: PR: Failed but allowed

#23559 Corrected FVM documentation typos.
  framework/doc/content/finite_volumes/fv_design.md
  framework/doc/content/syntax/FVBCs/index.md
Labels: PR: Failed but allowed

#23564 Fix deprecations in phase field module
  modules/phase_field/examples/multiphase/DerivativeMultiPhaseMaterial.i
  modules/phase_field/examples/multiphase/GrandPotential3Phase_masscons.i
  modules/phase_field/examples/nucleation/cahn_hilliard.i
  modules/phase_field/examples/nucleation/refine.i
  modules/phase_field/include/kernels/CHBulk.h
  modules/phase_field/include/kernels/CHInterfaceBase.h
  modules/phase_field/include/kernels/SplitCHWResBase.h
  modules/phase_field/src/action/CHPFCRFFSplitVariablesAction.C
  modules/phase_field/src/action/ConservedAction.C
  modules/phase_field/src/action/NonconservedAction.C
  modules/phase_field/src/action/PolycrystalKernelAction.C
  modules/phase_field/src/kernels/ADACInterface.C
  modules/phase_field/src/kernels/ADSplitCHParsed.C
  modules/phase_field/src/kernels/CoupledSwitchingTimeDerivative.C
  modules/phase_field/src/kernels/MaskedBodyForce.C
  modules/phase_field/src/kernels/MaskedExponential.C
  modules/phase_field/src/kernels/MatGradSquareCoupled.C
  modules/phase_field/src/kernels/SLKKSChemicalPotential.C
  modules/phase_field/src/kernels/SplitCHParsed.C
  modules/phase_field/src/kernels/SusceptibilityTimeDerivative.C
  modules/phase_field/src/kernels/SwitchingFunctionConstraintEta.C
  modules/phase_field/src/materials/DerivativeMultiPhaseBase.C
  modules/phase_field/src/materials/DerivativeTwoPhaseMaterial.C
  modules/phase_field/src/materials/ElasticEnergyMaterial.C
  modules/phase_field/test/tests/DeformedGrain/DeformedGrain.i
  modules/phase_field/test/tests/GBType/GB_Type_Phase1.i
  modules/phase_field/test/tests/KKS_system/kks_multiphase.i
  modules/phase_field/test/tests/KKS_system/kks_xevac.i
  modules/phase_field/test/tests/MultiPhase/acmultiinterface.i
  modules/phase_field/test/tests/MultiPhase/acmultiinterface_aux.i
  modules/phase_field/test/tests/MultiPhase/derivativetwophasematerial.i
  modules/phase_field/test/tests/MultiPhase/lagrangemult.i
  modules/phase_field/test/tests/MultiPhase/mixedswitchingfunctionmaterial.i
  modules/phase_field/test/tests/MultiPhase/penalty.i
  modules/phase_field/test/tests/MultiPhase/switchingfunction3phasematerial.i
  modules/phase_field/test/tests/MultiPhase/switchingfunctionmultiphasematerial.i
  modules/phase_field/test/tests/anisotropic_mobility/nonsplit.i
  modules/phase_field/test/tests/anisotropic_mobility/split.i
  modules/phase_field/test/tests/free_energy_material/IdealGasFreeEnergy.i
  modules/phase_field/test/tests/free_energy_material/MathEBFreeEnergy.i
  modules/phase_field/test/tests/free_energy_material/MathEBFreeEnergy_split.i
  modules/phase_field/test/tests/free_energy_material/MathEBFreeEnergy_split_name.i
  modules/phase_field/test/tests/free_energy_material/MathFreeEnergy.i
  modules/phase_field/test/tests/free_energy_material/MathFreeEnergy_split.i
  modules/phase_field/test/tests/free_energy_material/RegularSolutionFreeEnergy.i
  modules/phase_field/test/tests/free_energy_material/RegularSolutionFreeEnergy_const_T.i
  modules/phase_field/test/tests/free_energy_material/RegularSolutionFreeEnergy_plog.i
  modules/phase_field/test/tests/free_energy_material/VanDerWaalsFreeEnergy.i
  modules/phase_field/test/tests/mobility_derivative/mobility_derivative_direct_coupled_test.i
  modules/phase_field/test/tests/mobility_derivative/mobility_derivative_split_coupled_test.i
  modules/phase_field/test/tests/mobility_derivative/mobility_derivative_test.i
  modules/phase_field/test/tests/phase_field_kernels/ADAllenCahnVariableL.i
Labels: PR: Failed but allowed

#23546 Improve testing resilience for signal_handler
  test/tests/misc/signal_handler/tests
Labels: PR: Failed but allowed

#23547 Make Feb 2023 news public, add March template
  modules/doc/content/newsletter/2023/2023_02.md
  modules/doc/content/newsletter/2023/2023_03.md
  modules/doc/content/newsletter/index.md
Labels: PR: Ready for review/merge

#23574 Try to be more of a framework lead
  CODEOWNERS
Labels: PR: Failed but allowed

#23442 Refactor DiracKernel for LAGRANGE_VEC
  framework/doc/content/source/dirackernels/VectorConstantPointSource.md
  framework/include/dirackernels/DiracKernel.h
  framework/include/dirackernels/DiracKernelBase.h
  framework/include/dirackernels/VectorConstantPointSource.h
  framework/include/loops/ComputeDiracThread.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/base/Moose.C
  framework/src/dirackernels/DiracKernel.C
  framework/src/dirackernels/DiracKernelBase.C
  framework/src/dirackernels/VectorConstantPointSource.C
  framework/src/systems/NonlinearSystemBase.C
  test/tests/dirackernels/constant_point_source/gold/vector_2d_out.e
  test/tests/dirackernels/constant_point_source/gold/vector_3d_out.e
  test/tests/dirackernels/constant_point_source/tests
  test/tests/dirackernels/constant_point_source/vector_2d_point_source.i
  test/tests/dirackernels/constant_point_source/vector_3d_point_source.i
Labels: PR: Failed but allowed

#23588 Make VectorPostprocessorFunction request parallel synchronized VPPs
  framework/src/functions/VectorPostprocessorFunction.C
  modules/doc/content/newsletter/2023/2023_03.md
  test/tests/functions/vector_postprocessor_function/gold/out.e
  test/tests/functions/vector_postprocessor_function/vector_postprocessor_function.i
Labels: PR: Failed but allowed

#23597 Valid blocks
  framework/doc/content/source/mesh/MooseMesh.md
  framework/src/mesh/MooseMesh.C
  test/tests/mesh/add_subdomain_ids/add_subdomain_ids.i
  test/tests/mesh/add_subdomain_ids/gold/add_subdomain_ids_out.e
  test/tests/mesh/add_subdomain_ids/tests
Labels: PR: Failed but allowed

#23604 Add myself to CODEOWNERS
  CODEOWNERS
Labels: PR: Failed but allowed

#23024 Make PiecewiseBilinear::parse a static function
  framework/include/functions/PiecewiseBilinear.h
  framework/src/functions/PiecewiseBilinear.C
Labels: PR: Failed but allowed

#23314 Add term to interaction integral for graded materials
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/FractureIntegrals.md
  modules/tensor_mechanics/include/actions/DomainIntegralAction.h
  modules/tensor_mechanics/include/vectorpostprocessors/InteractionIntegral.h
  modules/tensor_mechanics/src/actions/DomainIntegralAction.C
  modules/tensor_mechanics/src/vectorpostprocessors/InteractionIntegral.C
  modules/tensor_mechanics/test/tests/j_integral_vtest/2d_benchmark.jou
  modules/tensor_mechanics/test/tests/j_integral_vtest/2d_paulino.e
  modules/tensor_mechanics/test/tests/j_integral_vtest/fgm_5.i
  modules/tensor_mechanics/test/tests/j_integral_vtest/gold/fgm_5_out.csv
  modules/tensor_mechanics/test/tests/j_integral_vtest/gold/j_int_fgm_sif_out.csv
  modules/tensor_mechanics/test/tests/j_integral_vtest/j_int_fgm_sif.i
  modules/tensor_mechanics/test/tests/j_integral_vtest/j_int_multiple_blocks_bimaterial.jou
  modules/tensor_mechanics/test/tests/j_integral_vtest/multiple_blocks_bimaterial.e
  modules/tensor_mechanics/test/tests/j_integral_vtest/tests
Labels: PR: Failed but allowed

#23628 Remove deprecated FluidState objects
  modules/porous_flow/doc/content/source/ics/PorousFlowFluidStateBrineCO2IC.md
  modules/porous_flow/doc/content/source/ics/PorousFlowFluidStateWaterNCGIC.md
  modules/porous_flow/doc/content/source/materials/PorousFlowFluidStateBrineCO2.md
  modules/porous_flow/doc/content/source/materials/PorousFlowFluidStateWaterNCG.md
  modules/porous_flow/include/ics/PorousFlowFluidStateBrineCO2IC.h
  modules/porous_flow/include/ics/PorousFlowFluidStateWaterNCGIC.h
  modules/porous_flow/include/materials/PorousFlowFluidStateBrineCO2.h
  modules/porous_flow/include/materials/PorousFlowFluidStateWaterNCG.h
  modules/porous_flow/src/ics/PorousFlowFluidStateBrineCO2IC.C
  modules/porous_flow/src/ics/PorousFlowFluidStateWaterNCGIC.C
  modules/porous_flow/src/materials/PorousFlowFluidStateBrineCO2.C
  modules/porous_flow/src/materials/PorousFlowFluidStateWaterNCG.C
  modules/porous_flow/test/tests/fluidstate/tests
Labels: PR: Failed but allowed

#23473 Add execution order groups
  framework/doc/content/syntax/UserObjects/index.md
  framework/include/base/Attributes.h
  framework/src/base/Attributes.C
  framework/src/base/MooseApp.C
  framework/src/problems/FEProblemBase.C
  framework/src/userobjects/UserObject.C
  modules/doc/content/newsletter/2023/2023_03.md
  test/include/postprocessors/ExecutionGroupTestPostprocessor.h
  test/src/postprocessors/ExecutionGroupTestPostprocessor.C
  test/tests/userobjects/execution_order_groups/test.i
  test/tests/userobjects/execution_order_groups/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23652 Fix segmentation fault as PCCMG only has a single quad background lay…
  modules/reactor/src/meshgenerators/PolygonConcentricCircleMeshGeneratorBase.C
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/gold/poly_2d_back_only_one_layer_quad.e
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/tests
Labels: PR: Failed but allowed

#23660 Use proper cutback factor on failures
  framework/src/timesteppers/IterationAdaptiveDT.C
Labels: PR: Failed but allowed

#23644 Do not allow checking of mesh properties without a type
  framework/src/actions/SetupMeshAction.C
  modules/reactor/include/meshgenerators/ReactorGeometryMeshBuilderBase.h
  modules/reactor/src/meshgenerators/AssemblyMeshGenerator.C
  modules/reactor/src/meshgenerators/CartesianMeshTrimmer.C
  modules/reactor/src/meshgenerators/CoreMeshGenerator.C
  modules/reactor/src/meshgenerators/HexagonMeshTrimmer.C
  modules/reactor/src/meshgenerators/PatternedCartesianMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedCartesianPeripheralModifier.C
  modules/reactor/src/meshgenerators/PatternedHexMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedHexPeripheralModifier.C
  modules/reactor/src/meshgenerators/PeripheralRingMeshGenerator.C
  modules/reactor/src/meshgenerators/PinMeshGenerator.C
  modules/reactor/src/meshgenerators/PolygonMeshTrimmerBase.C
  modules/reactor/src/meshgenerators/ReactorGeometryMeshBuilderBase.C
Labels: PR: Ready for review/merge

#23669 Catch mispelled parameters for multiapp directions in transfers
  framework/include/transfers/MultiAppTransfer.h
  framework/src/transfers/MultiAppTransfer.C
  test/tests/transfers/errors/tests
Labels: PR: Failed but allowed

#23691 Suppress nonlinear parameters for `ExternalProblem`
  framework/src/problems/ExternalProblem.C
Labels: PR: Failed but allowed

#23700 UMAT interface with displaced mesh
  modules/tensor_mechanics/include/materials/ComputeGeneralStressBase.h
  modules/tensor_mechanics/include/materials/ComputeStressBase.h
  modules/tensor_mechanics/include/materials/abaqus/AbaqusUMATStress.h
  modules/tensor_mechanics/src/interfacekernels/StepUOInterface.C
  modules/tensor_mechanics/src/materials/ComputeGeneralStressBase.C
  modules/tensor_mechanics/src/materials/ComputeStressBase.C
  modules/tensor_mechanics/src/materials/abaqus/AbaqusUMATStress.C
  modules/tensor_mechanics/test/tests/umat/print/tests
Labels: PR: Failed but allowed

#23486 Add output intermediate mesh option to MeshGenerator
  framework/doc/content/source/meshgenerators/MeshGenerator.md
  framework/src/meshgenerators/MeshGenerator.C
  test/tests/meshgenerators/output_intermediate_mesh/gold/left_in.e
  test/tests/meshgenerators/output_intermediate_mesh/output_intermediate_mesh.i
  test/tests/meshgenerators/output_intermediate_mesh/tests
Labels: PR: Failed but allowed

#23704 Predictor timestep tolerance
  framework/include/predictors/Predictor.h
  framework/src/predictors/Predictor.C
  test/tests/predictors/simple/tests
Labels: PR: Failed but allowed

#23684 Add time integration scheme to the default console header output
  framework/include/executioners/Executioner.h
  framework/include/executioners/Transient.h
  framework/include/utils/MooseTypes.h
  framework/src/executioners/Transient.C
  framework/src/outputs/ConsoleUtils.C
Labels: PR: Failed but allowed

#23720 Improved Reporter documentation
  framework/doc/content/syntax/Reporters/index.md
  framework/include/reporters/MeshInfo.h
  framework/include/reporters/Reporter.h
  framework/src/reporters/MeshInfo.C
  test/include/reporters/TestReporter.h
  test/src/reporters/TestReporter.C
Labels: PR: Failed but allowed

#23710 Adding material to compute the heat transfer coefficient
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/bib/thm.bib
  modules/thermal_hydraulics/doc/content/source/materials/ADWallHeatTransferCoefficientWolfMcCarthyMaterial.md
  modules/thermal_hydraulics/include/materials/ADWallHeatTransferCoefficientWolfMcCarthyMaterial.h
  modules/thermal_hydraulics/src/materials/ADWallHeatTransferCoefficientWolfMcCarthyMaterial.C
  modules/thermal_hydraulics/test/tests/materials/ad_wall_heat_transfer_coefficient_wolf_mccarthy/gold/test_out.csv
  modules/thermal_hydraulics/test/tests/materials/ad_wall_heat_transfer_coefficient_wolf_mccarthy/test.i
  modules/thermal_hydraulics/test/tests/materials/ad_wall_heat_transfer_coefficient_wolf_mccarthy/tests
Labels: PR: Failed but allowed

#23672 Guard against sizing non-existant old material properties
  modules/porous_flow/src/materials/PorousFlowMaterial.C
Labels: PR: Failed but allowed

#23725 Make PCCMG Side-Specific Sidesets Generation Optional
  modules/reactor/doc/content/source/meshgenerators/PolygonConcentricCircleMeshGenerator.md
  modules/reactor/include/meshgenerators/PolygonConcentricCircleMeshGeneratorBase.h
  modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
  modules/reactor/src/meshgenerators/PolygonConcentricCircleMeshGeneratorBase.C
  modules/reactor/src/meshgenerators/PolygonMeshGeneratorBase.C
  modules/reactor/src/meshgenerators/TriPinHexAssemblyGenerator.C
  modules/reactor/test/tests/meshgenerators/patterned_cartesian_mesh_generator/patterned_2d.i
  modules/reactor/test/tests/meshgenerators/patterned_cartesian_peripheral_modifier/patterned.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_mesh_generator/patterned_2d.i
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/gold/poly_2d_back_only_nssb.e
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/poly_2d.i
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/tests
Labels: PR: Failed but allowed

#23723 Add MessageFromInput UserObject to print a message from the input file
  framework/doc/content/source/userobjects/MessageFromInput.md
  framework/include/userobjects/MessageFromInput.h
  framework/src/userobjects/MessageFromInput.C
  test/tests/userobjects/message_from_input/message_from_input.i
  test/tests/userobjects/message_from_input/tests
Labels: PR: Failed but allowed

#23633 Add block restriction to phase field actions that define variables
  framework/src/interfaces/BlockRestrictable.C
  modules/phase_field/include/actions/CHPFCRFFSplitKernelAction.h
  modules/phase_field/include/actions/CHPFCRFFSplitVariablesAction.h
  modules/phase_field/include/actions/ConservedAction.h
  modules/phase_field/include/actions/GrainGrowthAction.h
  modules/phase_field/include/actions/HHPFCRFFSplitKernelAction.h
  modules/phase_field/include/actions/HHPFCRFFSplitVariablesAction.h
  modules/phase_field/include/actions/NonconservedAction.h
  modules/phase_field/include/actions/PFCRFFKernelAction.h
  modules/phase_field/include/actions/PFCRFFVariablesAction.h
  modules/phase_field/include/actions/PolycrystalElasticDrivingForceAction.h
  modules/phase_field/include/actions/PolycrystalVariablesAction.h
  modules/phase_field/src/actions/BicrystalBoundingBoxICAction.C
  modules/phase_field/src/actions/BicrystalCircleGrainICAction.C
  modules/phase_field/src/actions/ConservedAction.C
  modules/phase_field/src/actions/DisplacementGradientsAction.C
  modules/phase_field/src/actions/EulerAngle2RGBAction.C
  modules/phase_field/src/actions/GrainGrowthAction.C
  modules/phase_field/src/actions/HHPFCRFFSplitVariablesAction.C
  modules/phase_field/src/actions/KKSAction.C
  modules/phase_field/src/actions/MultiAuxVariablesAction.C
  modules/phase_field/src/actions/NonconservedAction.C
  modules/phase_field/src/actions/PFCRFFVariablesAction.C
  modules/phase_field/src/actions/PolycrystalColoringICAction.C
  modules/phase_field/src/actions/PolycrystalElasticDrivingForceAction.C
  modules/phase_field/src/actions/PolycrystalRandomICAction.C
  modules/phase_field/src/actions/PolycrystalVariablesAction.C
  modules/phase_field/src/actions/PolycrystalVoronoiVoidICAction.C
  modules/phase_field/src/actions/Tricrystal2CircleGrainsICAction.C
Labels: PR: Failed but allowed

#23331 Update Grand Potential Sintering model with strict mass conservation
  modules/phase_field/doc/content/source/actions/GrandPotentialKernelAction.md
  modules/phase_field/doc/content/source/materials/GrandPotentialSinteringMaterial.md
  modules/phase_field/include/materials/GrandPotentialSinteringMaterial.h
  modules/phase_field/src/actions/GrandPotentialKernelAction.C
  modules/phase_field/src/materials/GrandPotentialSinteringMaterial.C
  modules/phase_field/test/tests/GrandPotentialPFM/GrandPotentialStrictMassConservation.i
  modules/phase_field/test/tests/GrandPotentialPFM/gold/GrandPotentialStrictMassConservation_out.e
  modules/phase_field/test/tests/GrandPotentialPFM/gold/SinteringDilute_out.e
  modules/phase_field/test/tests/GrandPotentialPFM/gold/SinteringIdeal_out.e
  modules/phase_field/test/tests/GrandPotentialPFM/gold/SinteringParabolic_out.e
  modules/phase_field/test/tests/GrandPotentialPFM/tests
Labels: PR: Failed but allowed

#23387 Automatically add mesh EEID's through the input file and modify command line options to output mesh with EEID's
  framework/doc/content/source/actions/ElementIDOutputAction.md
  framework/doc/content/syntax/Mesh/index.md
  framework/include/actions/ElementIDOutputAction.h
  framework/src/actions/ElementIDOutputAction.C
  framework/src/actions/MeshOnlyAction.C
  framework/src/base/Moose.C
  framework/src/outputs/AdvancedOutput.C
  modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/assembly_only.i
  modules/reactor/test/tests/meshgenerators/cartesian_mesh_trimmer/assembly_trim.i
  modules/reactor/test/tests/meshgenerators/cartesian_mesh_trimmer/patterned_trimmed.i
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/core.i
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/core_periphery_prmg.i
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/tests
  modules/reactor/test/tests/meshgenerators/hexagon_mesh_trimmer/assembly_trim.i
  modules/reactor/test/tests/meshgenerators/hexagon_mesh_trimmer/patterned_trimmed.i
  modules/reactor/test/tests/meshgenerators/patterned_cartesian_mesh_generator/patterned_pattern.i
  modules/reactor/test/tests/meshgenerators/patterned_cartesian_mesh_generator/patterned_pattern_cd.i
  modules/reactor/test/tests/meshgenerators/patterned_cartesian_peripheral_modifier/patterned.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_mesh_generator/patterned_pattern.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_mesh_generator/patterned_pattern_cd.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/patterned.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/single_hex_pin_id.i
  modules/reactor/test/tests/meshgenerators/patterned_hex_peripheral_modifier/tests
  modules/reactor/test/tests/meshgenerators/pin_mesh_generator/pin_only.i
  modules/reactor/test/tests/meshgenerators/pin_mesh_generator/tests
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/pin_hex_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/core_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/core_zigzag_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/depletion_id/depletion_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/depletion_id/sub_pin_depletion_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/assembly_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/core_reporting_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/core_reporting_id_exclude.i
  modules/reactor/test/tests/meshgenerators/tri_pin_hex_assemby_generator/dummy_core.i
  modules/reactor/test/tests/meshgenerators/tri_pin_hex_assemby_generator/tri_pin_id.i
  test/tests/mesh/mesh_only/gold/mesh_only_with_elem_ids_in.e
  test/tests/mesh/mesh_only/mesh_only.i
  test/tests/mesh/mesh_only/mesh_only_with_elem_ids.i
  test/tests/mesh/mesh_only/output_dimension_override.i
  test/tests/mesh/mesh_only/tests
  test/tests/outputs/exodus/exodus_elem_id.i
  test/tests/outputs/exodus/gold/exodus_elem_id_out.e
  test/tests/outputs/exodus/tests
Labels: PR: Failed but allowed

#23719 Forbid block restriction of UO transfers if we re planning on extrapolating
  framework/src/transfers/MultiAppGeneralFieldUserObjectTransfer.C
  test/tests/transfers/general_field/user_object/subdomain/tests
Labels: PR: Failed but allowed

#23399 add absolute value tagging option
  framework/include/interfaces/TaggingInterface.h
  framework/include/kernels/ADKernelValue.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/ReferenceResidualProblem.h
  framework/src/interfaces/TaggingInterface.C
  framework/src/kernels/KernelValue.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/ReferenceResidualProblem.C
  modules/scalar_transport/test/tests/multiple-species/multiple-species.i
  python/MooseDocs/test/extensions/test_appsyntax.py
  test/tests/geomsearch/patch_update_strategy/gold/always-grid-sequence_out.e-s002
  test/tests/geomsearch/patch_update_strategy/gold/always-grid-sequence_out.e-s003
  test/tests/geomsearch/patch_update_strategy/gold/always-grid-sequence_out.e-s004
  test/tests/mortar/1d/1d.i
  test/tests/mortar/continuity-2d-conforming/conforming_two_var.i
  test/tests/problems/reference_residual_problem/abs_ref.i
  test/tests/problems/reference_residual_problem/abs_ref_acceptable.i
  test/tests/problems/reference_residual_problem/ad_abs_ref.i
  test/tests/problems/reference_residual_problem/gold/abs_ref_Linf_out.csv
  test/tests/problems/reference_residual_problem/gold/abs_ref_acceptable_out.csv
  test/tests/problems/reference_residual_problem/gold/abs_ref_local_Linf_out.csv
  test/tests/problems/reference_residual_problem/gold/abs_ref_local_out.csv
  test/tests/problems/reference_residual_problem/gold/abs_ref_out.csv
  test/tests/problems/reference_residual_problem/gold/ad_abs_ref_out.csv
  test/tests/problems/reference_residual_problem/gold/no_ref_out.csv
  test/tests/problems/reference_residual_problem/no_ref.i
  test/tests/problems/reference_residual_problem/tests
Labels: PR: Failed but allowed

#23760 Add subdomain name duplication check
  framework/include/mesh/MooseMesh.h
  framework/src/mesh/MooseMesh.C
  test/tests/meshgenerators/check_duplicate_subdomain_names/check_duplicate_subdomain_names.i
  test/tests/meshgenerators/check_duplicate_subdomain_names/tests
Labels: PR: Failed but allowed

#23774 Fix acceptable tolerance check
  test/tests/problems/reference_residual_problem/abs_ref_acceptable.i
  test/tests/problems/reference_residual_problem/tests
Labels: PR: Failed but allowed

#23771 Add a 2nd time derivative auxkernel
  framework/doc/content/source/auxkernels/SecondTimeDerivativeAux.md
  framework/include/auxkernels/SecondTimeDerivativeAux.h
  framework/src/auxkernels/SecondTimeDerivativeAux.C
  test/tests/auxkernels/time_derivative_aux/test.i
  test/tests/auxkernels/time_derivative_second_aux/gold/test_out.e
  test/tests/auxkernels/time_derivative_second_aux/test.i
  test/tests/auxkernels/time_derivative_second_aux/tests
Labels: PR: Failed but allowed

#23752 Five fixes for the perf graph live prints, and two bonus outputs improvements
  framework/doc/content/source/utils/PerfGraphLivePrint.md
  framework/include/base/MooseApp.h
  framework/include/utils/PerfGraphLivePrint.h
  framework/src/outputs/Checkpoint.C
  framework/src/outputs/Console.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/FormattedTable.C
  framework/src/utils/PerfGraphLivePrint.C
  test/include/problems/SlowProblem.h
  test/src/problems/SlowProblem.C
  test/tests/utils/perf_graph_live_print/perf_graph_live_print.i
  test/tests/utils/perf_graph_live_print/tests
Labels: PR: Failed but allowed

#23810 Loosen perf graph live formatting testing
  test/tests/utils/perf_graph_live_print/tests
Labels: PR: Failed but allowed

#23816 Loosen perf graph live formatting testing
  test/tests/utils/perf_graph_live_print/tests
Labels: PR: Failed but allowed

#23618 Save-in capability in mesh generator which provides access to any saved moose meshes beside the final one
  framework/include/base/MeshGeneratorSystem.h
  framework/include/base/MooseApp.h
  framework/include/mesh/MooseMesh.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/src/actions/MeshOnlyAction.C
  framework/src/actions/SetupMeshAction.C
  framework/src/base/MeshGeneratorSystem.C
  framework/src/mesh/MeshGeneratorMesh.C
  framework/src/meshgenerators/MeshGenerator.C
  modules/peridynamics/src/mesh/PeridynamicsMesh.C
  test/include/userobjects/TestSaveInMesh.h
  test/src/userobjects/TestSaveInMesh.C
  test/tests/userobjects/save_in_meshes/gold/left_block_in.e
  test/tests/userobjects/save_in_meshes/save_in_meshes.i
  test/tests/userobjects/save_in_meshes/save_in_meshes_with_D.i
  test/tests/userobjects/save_in_meshes/tests
Labels: PR: Failed but allowed

#23820 Expand Google Analytics capability in MooseDocs
  framework/doc/content/js/google_analytics.js
  modules/doc/config.yml
  python/MooseDocs/base/renderers.py
  python/MooseDocs/extensions/__init__.py
  python/MooseDocs/extensions/analytics.py
  python/MooseDocs/test/gold/materialize/contrib/reveal/notes.html
  python/MooseDocs/test/gold/materialize/extensions/algorithm.html
  python/MooseDocs/test/gold/materialize/extensions/amendments.html
  python/MooseDocs/test/gold/materialize/extensions/bibtex.html
  python/MooseDocs/test/gold/materialize/extensions/common.html
  python/MooseDocs/test/gold/materialize/extensions/config.html
  python/MooseDocs/test/gold/materialize/extensions/core.html
  python/MooseDocs/test/gold/materialize/extensions/first.html
  python/MooseDocs/test/gold/materialize/extensions/folder/folder.html
  python/MooseDocs/test/gold/materialize/extensions/folder/index.html
  python/MooseDocs/test/gold/materialize/extensions/graph.html
  python/MooseDocs/test/gold/materialize/extensions/include.html
  python/MooseDocs/test/gold/materialize/extensions/layout.html
  python/MooseDocs/test/gold/materialize/extensions/materialicon.html
  python/MooseDocs/test/gold/materialize/extensions/navigation.html
  python/MooseDocs/test/gold/materialize/extensions/package.html
  python/MooseDocs/test/gold/materialize/extensions/plotly.html
  python/MooseDocs/test/gold/materialize/extensions/preamble.html
  python/MooseDocs/test/gold/materialize/extensions/second.html
  python/MooseDocs/test/gold/materialize/extensions/style.html
  python/MooseDocs/test/gold/materialize/extensions/table.html
  python/MooseDocs/test/gold/materialize/mega.menu.html
  python/MooseDocs/test/materialize.yml
  python/doc/content/python/MooseDocs/extensions/analytics.md
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23726 Add a pressure drop postprocessor to NS module
  framework/include/base/MooseFunctorArguments.h
  framework/src/mesh/MooseMesh.C
  modules/navier_stokes/doc/content/source/materials/NSFVFrictionFlowDiodeMaterial.md
  modules/navier_stokes/doc/content/source/postprocessors/PressureDrop.md
  modules/navier_stokes/include/postprocessors/PressureDrop.h
  modules/navier_stokes/include/utils/NSFVUtils.h
  modules/navier_stokes/src/postprocessors/PressureDrop.C
  modules/navier_stokes/src/postprocessors/VolumetricFlowRate.C
  modules/navier_stokes/src/utils/NSFVUtils.C
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/gold/flow_based.csv
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/gold/pdrop_based.csv
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/gold/time_based.csv
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/tests
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/transient_operation.i
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/drop_insad.i
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/drop_insfv.i
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/expansion_quad.e
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insad.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insad_weighted.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insfv_quad_rz.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insfv_quad_xy.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/drop_insad_out.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/straight_insad.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/straight_insfv.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/straight_insfv_weighted.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/tests
Labels: PR: Failed but allowed

#23792 Miscellaneous user improvements
  framework/include/mesh/MooseMesh.h
  framework/include/utils/Conversion.h
  framework/src/actions/SetupMeshAction.C
  framework/src/executioners/Transient.C
  framework/src/mesh/MooseMesh.C
  framework/src/splits/Split.C
  framework/src/systems/NonlinearSystemBase.C
  modules/navier_stokes/src/actions/NSFVAction.C
  modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
  modules/navier_stokes/test/tests/finite_volume/ins/action/restart-block-restriction/tests
  modules/tensor_mechanics/test/tests/action/tests
  modules/tensor_mechanics/test/tests/ad_smeared_cracking/tests
  modules/tensor_mechanics/test/tests/smeared_cracking/tests
  test/tests/misc/solution_invalid/tests
  test/tests/postprocessors/table_tolerance/table_tolerance_test.i
  unit/src/ConversionTest.C
  unit/src/MooseEnumTest.C
Labels: PR: Failed but allowed

#23829 Fix LowerDBlockFromSidesetGenerator functor signatures
  framework/src/meshgenerators/LowerDBlockFromSidesetGenerator.C
Labels: PR: Failed but allowed

#23832 Parallel sync fix
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/AuxiliarySystem.C
  framework/src/systems/ComputeResidualFunctor.C
  framework/src/systems/NonlinearSystemBase.C
  modules/contact/src/constraints/ComputeWeightedGapLMMechanicalContact.C
  modules/contact/src/utils/MortarContactUtils.C
Labels: PR: Failed but allowed

#23793 Allowed `JunctionOneToOne1Phase` to connect non-parallel channels
  modules/thermal_hydraulics/doc/content/source/components/JunctionOneToOne1Phase.md
  modules/thermal_hydraulics/src/userobjects/ADJunctionOneToOne1PhaseUserObject.C
  modules/thermal_hydraulics/test/tests/components/junction_one_to_one_1phase/tests
  modules/thermal_hydraulics/test/tests/problems/natural_circulation/gold/natural_circulation_out.xml
  modules/thermal_hydraulics/test/tests/problems/natural_circulation/natural_circulation.i
  modules/thermal_hydraulics/test/tests/problems/natural_circulation/plot.py
  modules/thermal_hydraulics/test/tests/problems/natural_circulation/tests
Labels: PR: Failed but allowed

#23687 Add axisymmetry capability to interaction integral for SIF
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/FractureIntegrals.md
  modules/tensor_mechanics/include/vectorpostprocessors/InteractionIntegral.h
  modules/tensor_mechanics/src/vectorpostprocessors/InteractionIntegral.C
  modules/tensor_mechanics/test/tests/j_integral_vtest/2drz_tran.e
  modules/tensor_mechanics/test/tests/j_integral_vtest/axisymmetric_solution_tran.i
  modules/tensor_mechanics/test/tests/j_integral_vtest/axisymmetric_solution_tran.jou
  modules/tensor_mechanics/test/tests/j_integral_vtest/gold/axisymmetric_solution_tran_out.csv
  modules/tensor_mechanics/test/tests/j_integral_vtest/tests
Labels: PR: Failed but allowed

#23848 Remove zealous assert in general field transfers
  framework/include/transfers/MultiAppGeneralFieldTransfer.h
Labels: PR: Failed but allowed

#23834 Allow sub/boundary names with digits and then non-digits
  framework/include/utils/MooseMeshUtils.h
  framework/include/utils/MooseUtils.h
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/RenameBlockGenerator.C
  framework/src/meshgenerators/RenameBoundaryGenerator.C
  framework/src/utils/MooseMeshUtils.C
  test/tests/mesh/mesh-names-with-numbers-then-letters/gold/test_out.e
  test/tests/mesh/mesh-names-with-numbers-then-letters/test.i
  test/tests/mesh/mesh-names-with-numbers-then-letters/tests
Labels: PR: Failed but allowed

#23870 Fix object numeration issue in mortar thermal action
  modules/heat_conduction/src/actions/MortarGapHeatTransferAction.C
Labels: PR: Failed but allowed

#23804 Allow duplicate exec flag registration
  framework/src/base/ExecFlagRegistry.C
  test/include/userobjects/ExecFlagRegistryErrorTest.h
  test/src/userobjects/ExecFlagRegistryErrorTest.C
  test/tests/misc/exec_flag_registry/exec_flag_registry_errors.i
  test/tests/misc/exec_flag_registry/tests
Labels: PR: Ready for review/merge

#23873 Skip matrix evaluation during linear iterations for PJFNKMO
  framework/src/utils/SlepcSupport.C
Labels: PR: Failed but allowed

#23876 Use just short name for naming objects in mortar heat transfer action…
  modules/heat_conduction/src/actions/MortarGapHeatTransferAction.C
  modules/heat_conduction/test/tests/gap_heat_transfer_mortar_action/tests
Labels: PR: Failed but allowed

#23866 Update separator for thermochimica variables
  modules/chemical_reactions/src/userobjects/ThermochimicaNodalData.C
  modules/chemical_reactions/test/tests/thermochimica/MoRu.i
  modules/chemical_reactions/test/tests/thermochimica/gold/MoRu_out.e
  modules/chemical_reactions/test/tests/thermochimica/gold/csv_ic_out.e
  modules/chemical_reactions/test/tests/thermochimica/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23878 Fixed segmentation fault from reinitting material faces
  framework/src/problems/FEProblemBase.C
  modules/combined/test/tests/misc/re_init_face.i
  modules/combined/test/tests/misc/tests
Labels: PR: Failed but allowed

#23877 Fix Dynamic Loading Random Segfaults
  framework/include/base/AppFactory.h
  framework/include/base/ExecFlagRegistry.h
  framework/include/base/MooseApp.h
  framework/include/base/Registry.h
  framework/src/base/AppFactory.C
  framework/src/base/ExecFlagRegistry.C
  framework/src/base/MooseApp.C
  framework/src/utils/JsonSyntaxTree.C
  framework/src/utils/MooseUtils.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23788 Enhancing tagging interface
  framework/include/base/Assembly.h
  framework/include/interfaces/Coupleable.h
  framework/include/loops/ComputeMortarFunctor.h
  framework/include/loops/ComputeNodalUserObjectsThread.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/base/Assembly.C
  framework/src/interfaces/Coupleable.C
  framework/src/kernels/EigenKernel.C
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/loops/ComputeNodalUserObjectsThread.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/timeintegrators/CrankNicolson.C
  test/include/userobjects/CallTaggedResidualsTest.h
  test/src/userobjects/CallTaggedResidualsTest.C
  test/tests/tag/gold/old_eigen_tag_out.e
  test/tests/tag/old_eigen_tag.i
  test/tests/tag/tag_residual_call.i
  test/tests/tag/tests
Labels: PR: Failed but allowed

#23855 AD cohesive zone method
  framework/include/interfaces/Coupleable.h
  framework/include/interfaces/NeighborCoupleable.h
  framework/include/materials/InterfaceMaterial.h
  modules/tensor_mechanics/doc/content/source/interfacekernels/ADCZMInterfaceKernelSmallStrain.md
  modules/tensor_mechanics/doc/content/source/interfacekernels/ADCZMInterfaceKernelTotalLagrangian.md
  modules/tensor_mechanics/doc/content/source/materials/cohesive_zone_model/ADCZMComputeGlobalTractionSmallStrain.md
  modules/tensor_mechanics/doc/content/source/materials/cohesive_zone_model/ADCZMComputeGlobalTractionTotalLagrangian.md
  modules/tensor_mechanics/doc/content/source/materials/cohesive_zone_model/ADPureElasticTractionSeparation.md
  modules/tensor_mechanics/include/actions/CohesiveZoneAction.h
  modules/tensor_mechanics/include/interfacekernels/ADCZMInterfaceKernelBase.h
  modules/tensor_mechanics/include/interfacekernels/ADCZMInterfaceKernelSmallStrain.h
  modules/tensor_mechanics/include/interfacekernels/ADCZMInterfaceKernelTotalLagrangian.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/ADCZMComputeGlobalTractionBase.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/ADCZMComputeGlobalTractionSmallStrain.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/ADCZMComputeGlobalTractionTotalLagrangian.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/ADCZMComputeLocalTractionBase.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/ADCZMComputeLocalTractionIncrementalBase.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/ADCZMComputeLocalTractionTotalBase.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/ADPureElasticTractionSeparation.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/CZMComputeDisplacementJumpBase.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/CZMComputeDisplacementJumpSmallStrain.h
  modules/tensor_mechanics/include/materials/cohesive_zone_model/CZMComputeDisplacementJumpTotalLagrangian.h
  modules/tensor_mechanics/src/actions/CohesiveZoneAction.C
  modules/tensor_mechanics/src/actions/CohesiveZoneActionBase.C
  modules/tensor_mechanics/src/interfacekernels/ADCZMInterfaceKernelBase.C
  modules/tensor_mechanics/src/interfacekernels/ADCZMInterfaceKernelSmallStrain.C
  modules/tensor_mechanics/src/interfacekernels/ADCZMInterfaceKernelTotalLagrangian.C
  modules/tensor_mechanics/src/interfacekernels/CZMInterfaceKernelBase.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/ADCZMComputeGlobalTractionBase.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/ADCZMComputeGlobalTractionSmallStrain.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/ADCZMComputeGlobalTractionTotalLagrangian.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/ADCZMComputeLocalTractionBase.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/ADCZMComputeLocalTractionIncrementalBase.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/ADCZMComputeLocalTractionTotalBase.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/ADPureElasticTractionSeparation.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/CZMComputeDisplacementJumpBase.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/CZMComputeDisplacementJumpSmallStrain.C
  modules/tensor_mechanics/src/materials/cohesive_zone_model/CZMComputeDisplacementJumpTotalLagrangian.C
  modules/tensor_mechanics/test/tests/cohesive_zone_model/ad_czm.i
  modules/tensor_mechanics/test/tests/cohesive_zone_model/gold/ad_czm_small_strain.e
  modules/tensor_mechanics/test/tests/cohesive_zone_model/gold/ad_czm_total_lagrangian.e
  modules/tensor_mechanics/test/tests/cohesive_zone_model/tests
Labels: PR: Failed but allowed

#23895 Skip ComputeResidualThread when there is no kernel object
  framework/include/loops/NonlinearThread.h
  framework/src/loops/NonlinearThread.C
Labels: PR: Failed but allowed
