Repository idaholab/moose, pull requests merged in 2023-09, with the labels that each got.

#25371 Fixed sync_times_object in Output
  framework/src/outputs/Output.C
  modules/doc/content/newsletter/2023/2023_08.md
  test/tests/outputs/sync_times_object/gold/sync_times_object_out.csv
  test/tests/outputs/sync_times_object/sync_times_object.i
  test/tests/outputs/sync_times_object/tests
Labels: PR: Failed but allowed

#25170 Switch to const Postprocessor::getValue() method
  framework/src/postprocessors/Postprocessor.C
  framework/src/problems/FEProblemBase.C
  framework/src/userobjects/NearestPointAverage.C
  framework/src/userobjects/NearestPointIntegralVariablePostprocessor.C
Labels: PR: Failed but allowed

#25409 Update stalebot to version 8
  .github/workflows/stale.yml
Labels: PR: Failed but allowed, PR: Auto Merge

#25399 Ability to delete small volume elements
  framework/doc/content/source/meshgenerators/ParsedElementDeletionGenerator.md
  framework/doc/content/source/meshgenerators/ParsedNodeTransformGenerator.md
  framework/include/meshgenerators/MeshRepairGenerator.h
  framework/include/meshgenerators/ParsedElementDeletionGenerator.h
  framework/src/meshgenerators/MeshRepairGenerator.C
  framework/src/meshgenerators/ParsedElementDeletionGenerator.C
  test/tests/meshgenerators/parsed_element_deletion_generator/cut_in_half.i
  test/tests/meshgenerators/parsed_element_deletion_generator/cut_the_small.i
  test/tests/meshgenerators/parsed_element_deletion_generator/gold/cut_in_half_json.json
  test/tests/meshgenerators/parsed_element_deletion_generator/gold/cut_the_small_json.json
  test/tests/meshgenerators/parsed_element_deletion_generator/tests
Labels: PR: Failed but allowed

#25415 Enable loading of restarted postprocessor values into a receiver
  framework/doc/content/source/postprocessors/Receiver.md
  framework/include/reporters/ReporterState.h
  test/tests/restart/receiver/gold/receiver_initial_out.csv
  test/tests/restart/receiver/gold/receiver_restart_out.csv
  test/tests/restart/receiver/receiver_initial.i
  test/tests/restart/receiver/receiver_restart.i
  test/tests/restart/receiver/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#25420 Make test valgrind heavy
  modules/phase_field/test/tests/grain_tracker_test/tests
Labels: PR: Ready for review/merge

#24540 Navier-stokes finite element pieces for AMMT
  configure
  configure.ac
  framework/include/base/MooseDefaultConfig.h
  framework/src/problems/FEProblemBase.C
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/modules/navier_stokes/cgfe.md
  modules/navier_stokes/doc/content/modules/navier_stokes/laser_welding.md
  modules/navier_stokes/doc/content/source/bcs/INSADDisplaceBoundaryBC.md
  modules/navier_stokes/doc/content/source/bcs/INSADDummyDisplaceBoundaryIntegratedBC.md
  modules/navier_stokes/doc/content/source/bcs/INSADVaporRecoilPressureMomentumFluxBC.md
  modules/navier_stokes/doc/content/source/kernels/INSADMeshConvection.md
  modules/navier_stokes/examples/laser-welding/3d.i
  modules/navier_stokes/examples/laser-welding/gold/3d_exodus.e
  modules/navier_stokes/examples/laser-welding/gold/3d_exodus.e-s002
  modules/navier_stokes/examples/laser-welding/gold/3d_exodus.e-s003
  modules/navier_stokes/examples/laser-welding/gold/3d_exodus.e-s004
  modules/navier_stokes/examples/laser-welding/tests
  modules/navier_stokes/include/base/NSEnums.h
  modules/navier_stokes/include/bcs/INSADDisplaceBoundaryBC.h
  modules/navier_stokes/include/bcs/INSADDummyDisplaceBoundaryIntegratedBC.h
  modules/navier_stokes/include/bcs/INSADVaporRecoilPressureMomentumFluxBC.h
  modules/navier_stokes/include/kernels/INSADMeshConvection.h
  modules/navier_stokes/include/materials/INSADMaterial.h
  modules/navier_stokes/include/materials/INSADTauMaterial.h
  modules/navier_stokes/src/bcs/INSADDisplaceBoundaryBC.C
  modules/navier_stokes/src/bcs/INSADDummyDisplaceBoundaryIntegratedBC.C
  modules/navier_stokes/src/bcs/INSADVaporRecoilPressureMomentumFluxBC.C
  modules/navier_stokes/src/kernels/INSADBoussinesqBodyForce.C
  modules/navier_stokes/src/kernels/INSADMeshConvection.C
  modules/navier_stokes/src/materials/INSADMaterial.C
  modules/navier_stokes/src/userobjects/INSADObjectTracker.C
  modules/navier_stokes/test/include/materials/AriaLaserWeld304LStainlessSteel.h
  modules/navier_stokes/test/include/materials/AriaLaserWeld304LStainlessSteelBoundary.h
  modules/navier_stokes/test/src/materials/AriaLaserWeld304LStainlessSteel.C
  modules/navier_stokes/test/src/materials/AriaLaserWeld304LStainlessSteelBoundary.C
  modules/navier_stokes/test/tests/finite_element/ins/RZ_cone/gold/ad_rz_cone_by_parts_steady_stabilized_second_order_out.e
  modules/navier_stokes/test/tests/finite_element/ins/RZ_cone/gold/ad_rz_cone_no_parts_steady_stabilized_second_order_out.e
  modules/navier_stokes/test/tests/finite_element/ins/RZ_cone/tests
  modules/navier_stokes/test/tests/finite_element/ins/energy-conservation/gold/q2q1_out.csv
  modules/navier_stokes/test/tests/finite_element/ins/energy-conservation/q1q1.i
  modules/navier_stokes/test/tests/finite_element/ins/energy-conservation/q2q1.i
Labels: PR: Ready for review/merge

#25427 Make my fresh laptop build 25% faster
  framework/include/utils_nonunity/ADRankFourTensorForward.h
  framework/include/utils_nonunity/ADRankThreeTensorForward.h
  framework/include/utils_nonunity/ADRankTwoTensorForward.h
  framework/include/utils_nonunity/ADSymmetricRankFourTensorForward.h
  framework/include/utils_nonunity/ADSymmetricRankTwoTensorForward.h
  framework/include/utils_nonunity/FactorizedRankTwoTensor.h
  framework/include/utils_nonunity/PerfGraph.h
  framework/include/utils_nonunity/PerfGraphLivePrint.h
  framework/include/utils_nonunity/PerfGraphRegistry.h
  framework/include/utils_nonunity/PermutationTensor.h
  framework/include/utils_nonunity/RankFourTensor.h
  framework/include/utils_nonunity/RankFourTensorForward.h
  framework/include/utils_nonunity/RankFourTensorImplementation.h
  framework/include/utils_nonunity/RankThreeTensor.h
  framework/include/utils_nonunity/RankThreeTensorForward.h
  framework/include/utils_nonunity/RankThreeTensorImplementation.h
  framework/include/utils_nonunity/RankTwoTensor.h
  framework/include/utils_nonunity/RankTwoTensorForward.h
  framework/include/utils_nonunity/RankTwoTensorImplementation.h
  framework/include/utils_nonunity/SymmetricRankFourTensor.h
  framework/include/utils_nonunity/SymmetricRankFourTensorForward.h
  framework/include/utils_nonunity/SymmetricRankFourTensorImplementation.h
  framework/include/utils_nonunity/SymmetricRankTwoTensor.h
  framework/include/utils_nonunity/SymmetricRankTwoTensorForward.h
  framework/include/utils_nonunity/SymmetricRankTwoTensorImplementation.h
  framework/include/utils_nonunity/VectorTag.h
  framework/moose.mk
  framework/src/utils_nonunity/FactorizedRankTwoTensor.C
  framework/src/utils_nonunity/PerfGraph.C
  framework/src/utils_nonunity/PerfGraphLivePrint.C
  framework/src/utils_nonunity/PerfGraphRegistry.C
  framework/src/utils_nonunity/PermutationTensor.C
  framework/src/utils_nonunity/RankFourTensor.C
  framework/src/utils_nonunity/RankThreeTensor.C
  framework/src/utils_nonunity/RankTwoTensor.C
  framework/src/utils_nonunity/SymmetricRankFourTensor.C
  framework/src/utils_nonunity/SymmetricRankTwoTensor.C
  framework/src/utils_nonunity/VectorTag.C
Labels: PR: Failed but allowed

#25134 Support absolute_value_vector_tags in more actions
  modules/combined/test/tests/cavity_pressure/gold/rz_abs_ref_out.e
  modules/combined/test/tests/cavity_pressure/rz_abs_ref.i
  modules/contact/src/actions/ContactAction.C
  modules/tensor_mechanics/src/actions/CavityPressureAction.C
  modules/tensor_mechanics/src/actions/PressureAction.C
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#25428 Avoid potentially unnecessary work in getting block dims
  framework/src/mesh/MooseMesh.C
Labels: PR: Failed but allowed

#25386 Speed up getBoundaryIDs when distributed
  framework/src/utils/MooseMeshUtils.C
Labels: PR: Failed but allowed

#25383 Make combined creep and plasticity solver more robust
  modules/tensor_mechanics/include/materials/ComputeCreepPlasticityStress.h
  modules/tensor_mechanics/src/materials/ComputeCreepPlasticityStress.C
  modules/tensor_mechanics/test/tests/combined_creep_plasticity/creepWithPlasticity.i
  modules/tensor_mechanics/test/tests/combined_creep_plasticity/tests
Labels: PR: Failed but allowed

#25461 Re-enable our Nemesis tests with fixed num_dim
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.2
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/nemesis_rays.e.4.3
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/no_segments_nemesis_rays.e.2.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/no_segments_nemesis_rays.e.2.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays.e.2.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays.e.2.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays_nodal.e.2.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_data_rays_nodal.e.2.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/tests
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0002.4.0
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0002.4.1
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0002.4.2
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0002.4.3
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0003.4.0
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0003.4.1
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0003.4.2
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0003.4.3
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0004.4.0
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0004.4.1
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0004.4.2
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0004.4.3
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0005.4.0
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0005.4.1
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0005.4.2
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e-s0005.4.3
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e.4.0
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e.4.1
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e.4.2
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/gold/pbc_adaptivity_out.e.4.3
  test/tests/meshgenerators/distributed_rectilinear/dmg_displaced_mesh/tests
  test/tests/meshgenerators/output_intermediate_mesh/gold/left_in.e.2.0
  test/tests/meshgenerators/output_intermediate_mesh/gold/left_in.e.2.1
  test/tests/meshgenerators/output_intermediate_mesh/tests
  test/tests/outputs/nemesis/gold/nemesis_elemental_distributed.e.4.0
  test/tests/outputs/nemesis/gold/nemesis_elemental_distributed.e.4.1
  test/tests/outputs/nemesis/gold/nemesis_elemental_distributed.e.4.2
  test/tests/outputs/nemesis/gold/nemesis_elemental_distributed.e.4.3
  test/tests/outputs/nemesis/gold/nemesis_elemental_replicated.e.4.0
  test/tests/outputs/nemesis/gold/nemesis_elemental_replicated.e.4.1
  test/tests/outputs/nemesis/gold/nemesis_elemental_replicated.e.4.2
  test/tests/outputs/nemesis/gold/nemesis_elemental_replicated.e.4.3
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.0
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.1
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.2
  test/tests/outputs/nemesis/gold/nemesis_scalar_distributed.e.4.3
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.0
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.1
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.2
  test/tests/outputs/nemesis/gold/nemesis_scalar_replicated.e.4.3
  test/tests/outputs/nemesis/tests
  test/tests/outputs/variables/gold/nemesis_hide_out.e.2.0
  test/tests/outputs/variables/gold/nemesis_hide_out.e.2.1
  test/tests/outputs/variables/tests
Labels: PR: Failed but allowed

#25388 Initial tagging system for MooseDocs
  modules/doc/config.yml
  modules/electromagnetics/doc/config.yml
  modules/electromagnetics/doc/content/modules/electromagnetics/benchmarks/DipoleAntenna.md
  modules/electromagnetics/doc/content/modules/electromagnetics/benchmarks/EvanescentWave.md
  modules/electromagnetics/doc/content/modules/electromagnetics/benchmarks/OneDReflection.md
  modules/electromagnetics/doc/content/modules/electromagnetics/benchmarks/WaveguideEigenvalue.md
  modules/electromagnetics/doc/content/modules/electromagnetics/benchmarks/WaveguideTransmission.md
  modules/electromagnetics/doc/content/modules/electromagnetics/filter/assets/index-93b559a6.js
  modules/electromagnetics/doc/content/modules/electromagnetics/filter/assets/index-d526a0c5.css
  modules/electromagnetics/doc/content/modules/electromagnetics/filter/index.html
  modules/electromagnetics/doc/content/modules/electromagnetics/verification/electrostatic_contact_three_block.md
  modules/electromagnetics/doc/content/modules/electromagnetics/verification/electrostatic_contact_two_block.md
  python/MooseDocs/base/Extension.py
  python/MooseDocs/extensions/__init__.py
  python/MooseDocs/extensions/tagging.py
  python/MooseDocs/test/content/extensions/tag.md
  python/MooseDocs/test/content/index.md
  python/MooseDocs/test/content/js/tagging.js
  python/MooseDocs/test/extensions/test_tagging.py
  python/MooseDocs/test/extensions/tests
  python/MooseDocs/test/html.yml
  python/MooseDocs/test/latex.yml
  python/MooseDocs/test/materialize.yml
  python/MooseDocs/test/moosedocs.py
  python/doc/content/python/MooseDocs/extensions/tag.md
  python/doc/content/python/MooseDocs/specification.md
Labels: PR: Failed but allowed

#25457 Modify bootstrap at libMesh level for macOS ARM64
  conda/libmesh/meta.yaml
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/template/conda_build_config.yaml
  scripts/configure_libmesh.sh
  scripts/tests/versioner_hashes.yaml
Labels: PR: Failed but allowed

#25478 Add Casey as codeowner for MooseDocs and SQA utilities
  CODEOWNERS
Labels: PR: Ready for review/merge

#25477 Added error message for failed plot script in MooseDocs
  python/MooseDocs/extensions/media.py
Labels: PR: Failed but allowed

#25470 Mark the following tests as skipped
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/tests
  modules/navier_stokes/test/tests/finite_volume/pins/mms/tests
Labels: PR: Failed but allowed

#24620 Remove MooseGhostPointNeighbors src and header
  framework/include/relationshipmanagers/MooseGhostPointNeighbors.h
  framework/src/actions/AdaptivityAction.C
  framework/src/actions/SetAdaptivityOptionsAction.C
  framework/src/outputs/Exodus.C
  framework/src/outputs/GMVOutput.C
  framework/src/outputs/Tecplot.C
  framework/src/relationshipmanagers/MooseGhostPointNeighbors.C
Labels: PR: Failed but allowed, stale

#25513 Apply matplotlib 3.8 API change fix
  python/mms/ConvergencePlot.py
Labels: PR: Failed but allowed

#25514 Add check on side normal orientation flip internally
  framework/include/meshgenerators/MeshDiagnosticsGenerator.h
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/MeshDiagnosticsGenerator.C
  test/tests/meshgenerators/mesh_diagnostics_generator/tests
Labels: PR: Failed but allowed

#25502 Add Transient support to RayTracingExodus + various cleanup
  modules/ray_tracing/include/outputs/RayTracingExodus.h
  modules/ray_tracing/src/outputs/RayTracingExodus.C
  modules/ray_tracing/src/outputs/RayTracingMeshOutput.C
  modules/ray_tracing/src/outputs/RayTracingNemesis.C
  modules/ray_tracing/test/include/userobjects/TestTransientRaysStudy.h
  modules/ray_tracing/test/src/userobjects/TestTransientRaysStudy.C
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0001.4.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0001.4.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0002.4.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0002.4.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0002.4.3
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0003.4.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0003.4.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0003.4.2
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e-s0003.4.3
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e.4.0
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_nemesis_rays.e.4.1
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_rays.e
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_rays.e-s0001
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_rays.e-s0002
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/ray_mesh_output_transient_rays.e-s0003
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/ray_mesh_output_transient.i
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#25522 Add simple test for particle-in-cell ray tracing capability
  modules/ray_tracing/test/include/userobjects/TestPICRayStudy.h
  modules/ray_tracing/test/src/userobjects/TestPICRayStudy.C
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0001
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0002
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0003
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0004
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0005
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0006
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0007
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0008
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/gold/pic_ray_study_rays.e-s0009
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/pic_ray_study.i
  modules/ray_tracing/test/tests/userobjects/test_pic_ray_study/tests
Labels: PR: Failed but allowed

#25551 Document Chorin predictor-corrector scheme
  modules/navier_stokes/doc/content/modules/navier_stokes/cgfe.md
  modules/navier_stokes/doc/content/modules/navier_stokes/index.md
  modules/navier_stokes/doc/content/modules/navier_stokes/inschorin.md
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/lid_driven_chorin.i
Labels: PR: Failed but allowed

#25549 Let block restrictable objects always return valid mesh block ids
  framework/include/interfaces/BlockRestrictable.h
  framework/include/utils/MooseMeshUtils.h
  framework/include/utils/PiecewiseByBlockLambdaFunctor.h
  framework/src/dirackernels/DiracKernelInfo.C
  framework/src/fvkernels/FVPointValueConstraint.C
  framework/src/interfaces/BlockRestrictable.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/UniqueExtraIDMeshGenerator.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/transfers/MultiAppConservativeTransfer.C
  framework/src/transfers/MultiAppDofCopyTransfer.C
  framework/src/utils/MooseMeshUtils.C
  modules/navier_stokes/include/userobjects/INSADObjectTracker.h
  modules/navier_stokes/src/userobjects/INSADObjectTracker.C
  modules/reactor/src/meshgenerators/DepletionIDGenerator.C
  test/include/userobjects/MooseMeshUtilsTest.h
  test/src/userobjects/MooseMeshUtilsTest.C
  test/tests/materials/get_material_property_names/get_material_property_any_block_id.i
  test/tests/utils/moose_mesh_utils/get_subdomain_id.i
  test/tests/utils/moose_mesh_utils/moose_mesh_utils.i
  test/tests/utils/moose_mesh_utils/tests
Labels: PR: Failed but allowed

#25455 Functor smoothing
  framework/doc/content/source/functormaterials/FunctorSmoother.md
  framework/include/functormaterials/FunctorSmoother.h
  framework/src/functormaterials/FunctorSmoother.C
  test/tests/functormaterials/smoother/gold/checker_line_0001.csv
  test/tests/functormaterials/smoother/gold/face_smooth_line_0001.csv
  test/tests/functormaterials/smoother/gold/layer_elem_line_0001.csv
  test/tests/functormaterials/smoother/gold/test_out_line_0001.csv
  test/tests/functormaterials/smoother/test.i
  test/tests/functormaterials/smoother/tests
Labels: PR: Failed but allowed

#25575 HOTFIX Perform the conflict search outside of the value acceptance condition
  framework/src/transfers/MultiAppGeneralFieldTransfer.C
  test/tests/transfers/general_field/nearest_node/regular/main.i
  test/tests/transfers/general_field/nearest_node/regular/main_array.i
  test/tests/transfers/general_field/nearest_node/subdomain/main.i
Labels: PR: Failed but allowed

#25583 Added NearestPointLayeredSideIntegralFunctor
  framework/doc/content/source/userobjects/NearestPointLayeredSideIntegralFunctor.md
  framework/include/userobjects/NearestPointLayeredSideIntegralFunctor.h
  framework/src/userobjects/NearestPointLayeredSideIntegralFunctor.C
  modules/doc/content/newsletter/2023/2023_09.md
  test/tests/userobjects/nearest_point_layered_side_integral_functor/gold/nearest_point_layered_side_integral_functor_out_test_vpp_0000.csv
  test/tests/userobjects/nearest_point_layered_side_integral_functor/nearest_point_layered_side_integral_functor.i
  test/tests/userobjects/nearest_point_layered_side_integral_functor/tests
Labels: PR: Failed but allowed

#25568 Add JSON UO reader for interaction with json data files from input
  framework/contrib/json/include/nlohmann/json.h
  framework/doc/content/source/userobjects/JSONFileReader.md
  framework/include/functions/CoarsenedPiecewiseLinear.h
  framework/include/functions/PiecewiseLinear.h
  framework/include/functions/PiecewiseLinearBase.h
  framework/include/functions/PiecewiseTabularBase.h
  framework/include/userobjects/JSONFileReader.h
  framework/include/userobjects/MessageFromInput.h
  framework/src/functions/CoarsenedPiecewiseLinear.C
  framework/src/functions/PiecewiseLinear.C
  framework/src/functions/PiecewiseLinearBase.C
  framework/src/functions/PiecewiseTabularBase.C
  framework/src/userobjects/JSONFileReader.C
  modules/geochemistry/include/utils/GeochemicalDatabaseReader.h
  test/tests/functions/piecewise_constant/function_values.json
  test/tests/functions/piecewise_constant/gold/piecewise_constant_json_out.csv
  test/tests/functions/piecewise_constant/piecewise_constant.i
  test/tests/functions/piecewise_constant/piecewise_constant_json.i
  test/tests/functions/piecewise_constant/piecewise_constant_simple.i
  test/tests/functions/piecewise_constant/tests
  test/tests/misc/check_error/tests
  unit/data/json/function_values.json
  unit/src/JSONReaderTest.C
Labels: PR: Failed but allowed

#25363 Debug output for unit conversions
  framework/src/parser/Parser.C
  test/tests/parser/param_substitution/tests
  test/tests/parser/param_substitution/unit_conversion.i
Labels: PR: Failed but allowed

#25323 Enable auxvariable collection for PODMapping
  framework/include/loops/AllLocalDofIndicesThread.h
  framework/include/systems/NonlinearSystemBase.h
  framework/include/systems/SystemBase.h
  framework/src/loops/AllLocalDofIndicesThread.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  modules/stochastic_tools/include/reporters/SolutionContainer.h
  modules/stochastic_tools/include/transfers/SerializedSolutionTransfer.h
  modules/stochastic_tools/include/userobjects/InverseMapping.h
  modules/stochastic_tools/src/reporters/SolutionContainer.C
  modules/stochastic_tools/src/transfers/SerializedSolutionTransfer.C
  modules/stochastic_tools/src/userobjects/InverseMapping.C
  modules/stochastic_tools/test/tests/reporters/parallel_storage/gold/parallel_storage_main_out.json
  modules/stochastic_tools/test/tests/reporters/parallel_storage/gold/parallel_storage_main_out.json.1
  modules/stochastic_tools/test/tests/reporters/parallel_storage/parallel_storage_main.i
  modules/stochastic_tools/test/tests/reporters/parallel_storage/sub.i
  modules/stochastic_tools/test/tests/userobjects/inverse_mapping/create_mapping_main.i
  modules/stochastic_tools/test/tests/userobjects/inverse_mapping/gold/with_manual.e
  modules/stochastic_tools/test/tests/userobjects/inverse_mapping/gold/with_surrogate.csv
  modules/stochastic_tools/test/tests/userobjects/inverse_mapping/gold/with_surrogate.e
  modules/stochastic_tools/test/tests/userobjects/inverse_mapping/inverse_map.i
  modules/stochastic_tools/test/tests/userobjects/inverse_mapping/sub.i
  modules/stochastic_tools/test/tests/userobjects/inverse_mapping/tests
Labels: PR: Failed but allowed

#25607 Add links to moosedocs tagging
  framework/doc/content/source/meshgenerators/CombinerGenerator.md
  framework/doc/content/source/outputs/formatters/InputFileFormatter.md
  modules/electromagnetics/doc/config.yml
  modules/electromagnetics/doc/content/modules/electromagnetics/filter/assets/index-6fae072b.js
  modules/electromagnetics/doc/content/modules/electromagnetics/filter/assets/index-93b559a6.js
  modules/electromagnetics/doc/content/modules/electromagnetics/filter/index.html
  python/MooseDocs/extensions/tagging.py
Labels: PR: Failed but allowed
