Repository idaholab/moose, pull requests merged in 2023-01, with the labels that each got.

#22908 Check that generation of MooseRevision.h is successful before continuing compilation.
  framework/moose.mk
Labels: PR: Failed but allowed

#22949 Add a state check capability for auxkernel/uo evaluations
  framework/doc/content/source/problems/FEProblemBase.md
  framework/include/postprocessors/PerfGraphData.h
  framework/include/problems/FEProblemBase.h
  framework/include/reporters/ReporterData.h
  framework/src/postprocessors/MemoryUsage.C
  framework/src/postprocessors/PerfGraphData.C
  framework/src/problems/FEProblemBase.C
  framework/src/reporters/ReporterData.C
  framework/src/vectorpostprocessors/VectorMemoryUsage.C
  test/tests/auxkernels/pp_depend/gold/pp_depend_indirect_wrong_out.csv
  test/tests/auxkernels/pp_depend/tests
  test/tests/postprocessors/memory_usage/tests
  test/tests/userobjects/pre_aux_based_on_exec_flag/gold/pre_post_aux_test_out.csv
  test/tests/userobjects/pre_aux_based_on_exec_flag/pre_post_aux_test.i
  test/tests/userobjects/pre_aux_based_on_exec_flag/tests
Labels: PR: Failed but allowed

#23011 Bail out of solve quicker on exception
  framework/include/problems/FEProblemBase.h
  framework/src/problems/FEProblemBase.C
  framework/src/systems/ComputeResidualFunctor.C
  test/include/kernels/ExceptionKernel.h
  test/src/kernels/ExceptionKernel.C
  test/tests/misc/exception/exception_transient.i
  test/tests/misc/exception/gold/exception_transient_out.csv
  test/tests/misc/exception/tests
Labels: PR: Failed but allowed

#22998 Initial stab at mass scaling for explicit dynamics
  modules/tensor_mechanics/doc/content/source/materials/DensityScaling.md
  modules/tensor_mechanics/include/kernels/InertialForce.h
  modules/tensor_mechanics/include/materials/DensityScaling.h
  modules/tensor_mechanics/include/postprocessors/CriticalTimeStep.h
  modules/tensor_mechanics/src/kernels/InertialForce.C
  modules/tensor_mechanics/src/materials/DensityScaling.C
  modules/tensor_mechanics/src/postprocessors/CriticalTimeStep.C
  modules/tensor_mechanics/test/tests/central_difference/consistent/3D/3d_consistent_explicit_mass_scaling.i
  modules/tensor_mechanics/test/tests/central_difference/consistent/3D/gold/3d_consistent_explicit_mass_scaling_out.e
  modules/tensor_mechanics/test/tests/central_difference/consistent/3D/tests
Labels: PR: Failed but allowed

#23056 add optimization module to registerAll and stork
  modules/module_loader/src/ModulesApp.C
  stork/Makefile.app
Labels: PR: Failed but allowed

#22583 Multiapp reset for multiple specification of times
  framework/include/multiapps/MultiApp.h
  framework/src/multiapps/MultiApp.C
  framework/src/multiapps/TransientMultiApp.C
  modules/level_set/src/multiapps/LevelSetReinitializationMultiApp.C
  test/tests/multiapps/reset/gold/multiple_times_sub0.e-s002
  test/tests/multiapps/reset/gold/multiple_times_sub0.e-s003
  test/tests/multiapps/reset/tests
Labels: PR: Failed but allowed

#23046 Shield MMS testing from MPI issues, point users to their mpirun
  test/tests/fvkernels/mms/harmonic_interpolation/test.py
  test/tests/fvkernels/mms/skewness-correction/adv-diff-react/test.py
  test/tests/fvkernels/mms/skewness-correction/diffusion/test.py
  test/tests/fvkernels/mms/skewness-correction/two_term_extrapol/test.py
  test/tests/misc/mpi_setup/tests
Labels: PR: Failed but allowed

#23062 Make a mortar restart valgrind test that timed out part of valgrind heavy
  modules/contact/test/tests/mortar_restart/tests
Labels: PR: Failed but allowed

#23073 Make test conditional on submodule
  modules/chemical_reactions/test/tests/thermochimica/tests
Labels: PR: Failed but allowed

#23081 Fixup a couple SQA template typos
  framework/doc/content/templates/sqa/app_scs.md.template
  framework/doc/content/templates/sqa/module_srs.md.template
Labels: PR: Failed but allowed

#23038 Renaming variable names in Simulation to avoid ambiguity
  modules/thermal_hydraulics/include/base/Simulation.h
  modules/thermal_hydraulics/src/base/Simulation.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23087 Switch git completion instructions to point to git repo
  modules/doc/content/framework_development/git.md
Labels: PR: Failed but allowed, PR: Auto Merge

#23080 Preformance improvements
  framework/doc/content/source/interfaces/SetupInterface.md
  framework/include/actions/CheckOutputAction.h
  framework/include/outputs/AdvancedOutput.h
  framework/include/outputs/MaterialPropertyDebugOutput.h
  framework/include/outputs/Output.h
  framework/include/reporters/ReporterData.h
  framework/include/utils/Shuffle.h
  framework/src/multiapps/TransientMultiApp.C
  framework/src/transfers/MultiAppTransfer.C
  framework/src/vectorpostprocessors/VectorPostprocessor.C
  modules/stochastic_tools/doc/content/modules/stochastic_tools/batch_mode.md
  python/peacock/ExodusViewer/plugins/VTKWindowPlugin.py
  test/tests/preconditioners/auto_smp/tests
  test/tests/transfers/multiapp_mesh_function_transfer/tests
Labels: PR: Failed but allowed

#22573 Made --failed-tests actually import only failed tests
  python/TestHarness/JobDAG.py
Labels: PR: Failed but allowed

#23075 Add regression test for AMR w/ high-order SCALARs
  test/tests/adaptivity/scalar/gold/scalar_adaptivity_out.e-s002
  test/tests/adaptivity/scalar/scalar_adaptivity.i
  test/tests/adaptivity/scalar/tests
Labels: PR: Failed but allowed

#23083 Add maximum_damage parameter to ScalarDamageBase
  modules/tensor_mechanics/include/materials/ScalarDamageBase.h
  modules/tensor_mechanics/src/materials/ScalarDamageBase.C
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/ad_combined_scalar_damage_limit_combined_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/ad_combined_scalar_damage_limit_sub_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/combined_scalar_damage_limit_combined_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/gold/combined_scalar_damage_limit_sub_out.csv
  modules/tensor_mechanics/test/tests/scalar_material_damage/tests
Labels: PR: Failed but allowed

#23064 Pbs errors
  python/TestHarness/StatusSystem.py
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/schedulers/PBScodes.py
  python/TestHarness/schedulers/QueueManager.py
  python/TestHarness/schedulers/RunPBS.py
  python/TestHarness/schedulers/Scheduler.py
  python/TestHarness/util.py
  scripts/are_queued_jobs_finished.py
Labels: PR: Failed but allowed

#23111 Update stalebot action to version 7
  .github/stale.yml
  .github/workflows/stale.yml
Labels: PR: Failed but allowed

#23054 Templating Hill Plasticity Models
  framework/include/utils/MooseTypes.h
  modules/tensor_mechanics/doc/content/source/materials/ADHillElastoPlasticityStressUpdate.md
  modules/tensor_mechanics/doc/content/source/materials/ADHillPlasticityStressUpdate.md
  modules/tensor_mechanics/doc/content/source/materials/GeneralizedRadialReturnStressUpdate.md
  modules/tensor_mechanics/doc/content/source/materials/HillConstants.md
  modules/tensor_mechanics/doc/content/source/materials/HillCreepStressUpdate.md
  modules/tensor_mechanics/doc/content/source/materials/HillElastoPlasticityStressUpdate.md
  modules/tensor_mechanics/doc/content/source/materials/HillPlasticityStressUpdate.md
  modules/tensor_mechanics/include/materials/ADAnisotropicReturnPlasticityStressUpdateBase.h
  modules/tensor_mechanics/include/materials/ADHillElastoPlasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/ADHillPlasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/AnisotropicReturnPlasticityStressUpdateBase.h
  modules/tensor_mechanics/include/materials/GeneralizedRadialReturnStressUpdate.h
  modules/tensor_mechanics/include/materials/HillElastoPlasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/HillPlasticityStressUpdate.h
  modules/tensor_mechanics/src/materials/ADAnisotropicReturnPlasticityStressUpdateBase.C
  modules/tensor_mechanics/src/materials/AnisotropicReturnPlasticityStressUpdateBase.C
  modules/tensor_mechanics/src/materials/HillElastoPlasticityStressUpdate.C
  modules/tensor_mechanics/src/materials/HillPlasticityStressUpdate.C
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/ad_aniso_plasticity_x_one.i
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/ad_aniso_plasticity_x_one_ref.i
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/ad_uniaxial_x.i
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/ad_uniaxial_x_non_linear.i
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/ad_uniaxial_y.i
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/gold/ad_aniso_plasticity_x_one_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/gold/ad_aniso_plasticity_x_one_ref_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/gold/ad_uniaxial_x_non_linear_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/gold/ad_uniaxial_x_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/gold/ad_uniaxial_y_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_elastoplasticity/tests
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/ad_aniso_plasticity_x.i
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/ad_aniso_plasticity_x_rotate.i
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/ad_aniso_plasticity_y.i
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/anis_elasticity_test.i
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/anis_plasticity_test.i
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/gold/ad_aniso_plasticity_x_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/gold/ad_aniso_plasticity_x_rotate_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/gold/ad_aniso_plasticity_y_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/gold/anis_elasticity_test_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/gold/anis_plasticity_test_out.csv
  modules/tensor_mechanics/test/tests/anisotropic_plasticity/tests
Labels: PR: Failed but allowed

#22953 Update WSL instructions
  modules/doc/content/getting_started/installation/conda.md
  modules/doc/content/getting_started/installation/index.md
  modules/doc/content/getting_started/installation/windows.md
  modules/doc/content/getting_started/installation/windows10.md
  modules/doc/content/getting_started/installation/wsl.md
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23127 Newsletter changes for Dec 2022/Jan 2023
  modules/doc/content/newsletter/2018/2018_05.md
  modules/doc/content/newsletter/2018/2018_06.md
  modules/doc/content/newsletter/2018/2018_07.md
  modules/doc/content/newsletter/2018/2018_08.md
  modules/doc/content/newsletter/2018/2018_09.md
  modules/doc/content/newsletter/2018/2018_10.md
  modules/doc/content/newsletter/2018/2018_11.md
  modules/doc/content/newsletter/2018/2018_12.md
  modules/doc/content/newsletter/2019/2019_01.md
  modules/doc/content/newsletter/2019/2019_02.md
  modules/doc/content/newsletter/2019/2019_03.md
  modules/doc/content/newsletter/2019/2019_04.md
  modules/doc/content/newsletter/2019/2019_05.md
  modules/doc/content/newsletter/2019/2019_06.md
  modules/doc/content/newsletter/2019/2019_07.md
  modules/doc/content/newsletter/2019/2019_08.md
  modules/doc/content/newsletter/2019/2019_09.md
  modules/doc/content/newsletter/2019/2019_10.md
  modules/doc/content/newsletter/2019/2019_11.md
  modules/doc/content/newsletter/2019/2019_12.md
  modules/doc/content/newsletter/2020/2020_01.md
  modules/doc/content/newsletter/2020/2020_02.md
  modules/doc/content/newsletter/2020/2020_03.md
  modules/doc/content/newsletter/2020/2020_04.md
  modules/doc/content/newsletter/2020/2020_05.md
  modules/doc/content/newsletter/2020/2020_06.md
  modules/doc/content/newsletter/2020/2020_07.md
  modules/doc/content/newsletter/2020/2020_08.md
  modules/doc/content/newsletter/2020/2020_09.md
  modules/doc/content/newsletter/2020/2020_10.md
  modules/doc/content/newsletter/2020/2020_11.md
  modules/doc/content/newsletter/2020/2020_12.md
  modules/doc/content/newsletter/2021/2021_01.md
  modules/doc/content/newsletter/2021/2021_02.md
  modules/doc/content/newsletter/2021/2021_03.md
  modules/doc/content/newsletter/2021/2021_04.md
  modules/doc/content/newsletter/2021/2021_05.md
  modules/doc/content/newsletter/2021/2021_06.md
  modules/doc/content/newsletter/2021/2021_07.md
  modules/doc/content/newsletter/2021/2021_08.md
  modules/doc/content/newsletter/2021/2021_09.md
  modules/doc/content/newsletter/2021/2021_10.md
  modules/doc/content/newsletter/2021/2021_11.md
  modules/doc/content/newsletter/2021/2021_12.md
  modules/doc/content/newsletter/2022/2022_01.md
  modules/doc/content/newsletter/2022/2022_02.md
  modules/doc/content/newsletter/2022/2022_03.md
  modules/doc/content/newsletter/2022/2022_04.md
  modules/doc/content/newsletter/2022/2022_05.md
  modules/doc/content/newsletter/2022/2022_06.md
  modules/doc/content/newsletter/2022/2022_07.md
  modules/doc/content/newsletter/2022/2022_08.md
  modules/doc/content/newsletter/2022/2022_09.md
  modules/doc/content/newsletter/2022/2022_10.md
  modules/doc/content/newsletter/2022/2022_11.md
  modules/doc/content/newsletter/2022/2022_12.md
  modules/doc/content/newsletter/2023/2023_01.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#23126 Ensure PATH gets set in /etc/environment for Docker images
  docker_ci/Dockerfile
Labels: PR: Failed but allowed

#23001 Add a functor which can describe a face-centered field
  framework/include/mesh/FaceInfo.h
  framework/include/mesh/MooseMesh.h
  framework/src/mesh/FaceInfo.C
  framework/src/mesh/MooseMesh.C
  framework/src/systems/NonlinearSystemBase.C
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/modules/navier_stokes/insfv.md
  modules/navier_stokes/include/fvkernels/PCNSFVKTDC.h
  modules/navier_stokes/include/utils/FaceCenteredMapFunctor.h
  modules/navier_stokes/src/fvkernels/PCNSFVKTDC.C
  modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
  modules/navier_stokes/src/utils/FaceCenteredMapFunctor.C
  modules/navier_stokes/test/include/postprocessors/TestFaceToCellReconstruction.h
  modules/navier_stokes/test/src/postprocessors/TestFaceToCellReconstruction.C
  modules/navier_stokes/test/tests/finite_volume/cell_value_reconst/test.py
  modules/navier_stokes/test/tests/finite_volume/cell_value_reconst/tests
  modules/navier_stokes/test/tests/finite_volume/cell_value_reconst/velocity_reconst.i
  modules/navier_stokes/unit/src/TestFaceCenteredMapFunctor.C
  unit/src/LimitersTest.C
  unit/src/MooseFunctorTest.C
Labels: PR: Failed but allowed

#21791 Replace XMLDiff and JSONDiff with new universal differ
  conda/test-tools/meta.yaml
  conda/tools/meta.yaml
  modules/stochastic_tools/examples/parameter_study/tests
  python/TestHarness/XMLDiffer.py
  python/TestHarness/testers/JSONDiff.py
  python/TestHarness/testers/SchemaDiff.py
  python/TestHarness/testers/XMLDiff.py
  python/TestHarness/tests/test_JSONDiff.py
  python/TestHarness/tests/test_SchemaDiff.py
  python/TestHarness/tests/tests
  python/mooseutils/jsondiff.py
  python/mooseutils/tests/test_jsondiff.py
  python/mooseutils/tests/tests
  scripts/tests/versioner_hashes.yaml
  test/tests/outputs/iterative/gold/iterative_vtk_out_003_0.vtu
  test/tests/outputs/vtk/gold/vtk_diff_out_005_0.vtu
  test/tests/outputs/vtk/gold/vtk_diff_serial_mesh_parallel_out_005_0.vtu
  test/tests/outputs/vtk/gold/vtk_diff_serial_mesh_parallel_out_005_1.vtu
  test/tests/outputs/xml/gold/gold/xml_distributed_out.xml
  test/tests/outputs/xml/gold/gold/xml_distributed_out.xml.1
  test/tests/outputs/xml/gold/gold/xml_distributed_out.xml.2
  test/tests/outputs/xml/gold/gold/xml_iterations_out.xml
  test/tests/outputs/xml/gold/gold/xml_out.xml
  test/tests/test_harness/gold/invalid.json
  test/tests/test_harness/gold/invalid.xml
  test/tests/test_harness/gold/schema_out.xml
  test/tests/test_harness/gold/schemadiff_out.json
  test/tests/test_harness/jsondiff
  test/tests/test_harness/schema.i
  test/tests/test_harness/schemadiff
  test/tests/test_harness/schemadiff.i
Labels: PR: Ready for review/merge, PR: Requires app patch(es)

#23005 Improved Features for 'Add an interface to mark the solution as invalid / out-of-bounds'
  framework/doc/content/source/problems/SolutionInvalidity.md
  framework/include/base/MooseApp.h
  framework/include/interfaces/SolutionInvalidInterface.h
  framework/include/problems/FEProblemBase.h
  framework/include/systems/SystemBase.h
  framework/include/utils/GeneralRegistry.h
  framework/include/utils/MooseTypes.h
  framework/include/utils/PerfGraph.h
  framework/include/utils/PerfGraphRegistry.h
  framework/include/utils/SolutionInvalidity.h
  framework/include/utils/SolutionInvalidityRegistry.h
  framework/src/base/MooseApp.C
  framework/src/interfaces/SolutionInvalidInterface.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  framework/src/utils/PerfGraph.C
  framework/src/utils/PerfGraphRegistry.C
  framework/src/utils/SolutionInvalidity.C
  framework/src/utils/SolutionInvalidityRegistry.C
  test/include/materials/NonsafeMaterial.h
  test/src/materials/NonsafeMaterial.C
  test/tests/materials/solution_invalid/solution_invalid.i
  test/tests/materials/solution_invalid/tests
  test/tests/utils/perf_graph/tests
Labels: PR: Failed but allowed

#23049 Add SRS, SDD, and RTM docs for scalar transport, FSI, heat conduction modules
  modules/fsi/doc/content/modules/fsi/sqa/fsi_rtm.md
  modules/fsi/doc/content/modules/fsi/sqa/fsi_sdd.md
  modules/fsi/doc/content/modules/fsi/sqa/fsi_srs.md
  modules/heat_conduction/doc/content/modules/heat_conduction/sqa/heat_conduction_rtm.md
  modules/heat_conduction/doc/content/modules/heat_conduction/sqa/heat_conduction_sdd.md
  modules/heat_conduction/doc/content/modules/heat_conduction/sqa/heat_conduction_srs.md
  modules/scalar_transport/doc/content/sqa/scalar_transport_rtm.md
  modules/scalar_transport/doc/content/sqa/scalar_transport_sdd.md
  modules/scalar_transport/doc/content/sqa/scalar_transport_srs.md
Labels: PR: Failed but allowed

#21503 Adding Lead and LeadBismuth Fluid properties
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/source/userobjects/LeadBismuthFluidProperties.md
  modules/fluid_properties/doc/content/source/userobjects/LeadFluidProperties.md
  modules/fluid_properties/include/userobjects/LeadBismuthFluidProperties.h
  modules/fluid_properties/include/userobjects/LeadFluidProperties.h
  modules/fluid_properties/src/userobjects/LeadBismuthFluidProperties.C
  modules/fluid_properties/src/userobjects/LeadFluidProperties.C
  modules/fluid_properties/unit/include/LeadBismuthFluidPropertiesTest.h
  modules/fluid_properties/unit/include/LeadFluidPropertiesTest.h
  modules/fluid_properties/unit/src/FlinakFluidPropertiesTest.C
  modules/fluid_properties/unit/src/LeadBismuthFluidPropertiesTest.C
  modules/fluid_properties/unit/src/LeadFluidPropertiesTest.C
Labels: PR: Failed but allowed

#23124 Fix the two bugs in assembly with array variables
  framework/include/base/Assembly.h
  framework/src/base/Assembly.C
  framework/src/preconditioners/PhysicsBasedPreconditioner.C
  framework/src/preconditioners/SingleMatrixPreconditioner.C
  test/tests/kernels/array_kernels/array_custom_coupling_test.i
  test/tests/kernels/array_kernels/tests
Labels: PR: Failed but allowed

#23134 outputMeshInformation: print skip_partitioning
  framework/src/outputs/ConsoleUtils.C
Labels: T: task, PR: Failed but allowed

#23147 Fix gradient population for FV kernels through FunctorElementalAux
  framework/include/variables/MooseVariableFV.h
  framework/include/variables/MooseVariableField.h
  framework/src/auxkernels/FunctorElementalGradientAux.C
  test/tests/auxkernels/functor_elemental_gradient/gold/functor_gradient_out_results_0001.csv
Labels: PR: Failed but allowed

#23122 Adaptive substepping
  framework/include/userobject/BatchMaterial.h
  modules/tensor_mechanics/doc/content/source/materials/RadialReturnStressUpdate.md
  modules/tensor_mechanics/include/materials/RadialReturnStressUpdate.h
  modules/tensor_mechanics/src/materials/ADMultiplePowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/LAROMANCEStressUpdateBase.C
  modules/tensor_mechanics/src/materials/PowerLawCreepStressUpdate.C
  modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C
  modules/tensor_mechanics/test/tests/ad_return_mapping/ad_return_mapping_derivative.i
  modules/tensor_mechanics/test/tests/rom_stress_update/creep_ramp_sub_false.i
  modules/tensor_mechanics/test/tests/rom_stress_update/creep_ramp_sub_false_more_steps.i
  modules/tensor_mechanics/test/tests/rom_stress_update/creep_ramp_sub_true.i
  modules/tensor_mechanics/test/tests/substepping/ad_power_law_creep.i
  modules/tensor_mechanics/test/tests/substepping/power_law_creep.i
  modules/tensor_mechanics/test/tests/substepping/tests
Labels: PR: Ready for review/merge

#23160 Fix TM action for new kernels
  framework/src/auxkernels/ParsedAux.C
  modules/tensor_mechanics/src/actions/TensorMechanicsAction.C
  modules/tensor_mechanics/src/actions/TensorMechanicsActionBase.C
  modules/tensor_mechanics/test/tests/action/gold/two_block_lagrangian_out.e
  modules/tensor_mechanics/test/tests/action/tests
  modules/tensor_mechanics/test/tests/action/two_block_lagrangian.i
  modules/tensor_mechanics/test/tests/jacobian_damper/block_restriction.i
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23149 `MaterialRateAuxKernel` code, tests, and documentation.
  framework/doc/content/source/auxkernels/MaterialRateRealAux.md
  framework/include/auxkernels/MaterialRateAuxBase.h
  framework/include/auxkernels/MaterialRateRealAux.h
  framework/src/auxkernels/MaterialRateRealAux.C
  framework/src/auxkernels/MaterialRealAux.C
  test/tests/auxkernels/material_rate_real/gold/material_rate_real_out.csv
  test/tests/auxkernels/material_rate_real/material_rate_real.i
  test/tests/auxkernels/material_rate_real/tests
Labels: PR: Failed but allowed

#23175 Fix FV loops to work with multiple NL systems
  framework/include/loops/ComputeFVFluxThread.h
  framework/src/systems/NonlinearSystemBase.C
  modules/navier_stokes/include/loops/GatherRCDataElementThread.h
  modules/navier_stokes/include/loops/GatherRCDataFaceThread.h
  modules/navier_stokes/include/userobjects/INSFVRhieChowInterpolator.h
  modules/navier_stokes/src/loops/GatherRCDataElementThread.C
  modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
  test/tests/misc/multiple-nl-systems/gold/test-fv_out.e
  test/tests/misc/multiple-nl-systems/test-fv.i
  test/tests/misc/multiple-nl-systems/tests
Labels: PR: Failed but allowed

#23136 Add Mesh Metadata to Existing Meshes
  framework/doc/content/source/meshgenerators/AddMetaDataGenerator.md
  framework/include/meshgenerators/AddMetaDataGenerator.h
  framework/include/parser/Parser.h
  framework/src/meshgenerators/AddMetaDataGenerator.C
  framework/src/parser/Parser.C
  test/include/meshgenerators/TestMeshMetaData.h
  test/src/meshgenerators/TestMeshMetaData.C
  test/tests/meshgenerators/add_meta_data_generator/meshmetadata_assign.i
  test/tests/meshgenerators/add_meta_data_generator/tests
Labels: PR: Failed but allowed

#23185 Fix store timestep
  modules/tensor_mechanics/include/materials/RadialReturnStressUpdate.h
  modules/tensor_mechanics/src/materials/RadialReturnStressUpdate.C
Labels: PR: Failed but allowed

#23007 Test named blocks/sidesets/nodesets with Nemesis mesh
  test/tests/mesh/nemesis/cylinder/cylinder.e.4.0
  test/tests/mesh/nemesis/cylinder/cylinder.e.4.1
  test/tests/mesh/nemesis/cylinder/cylinder.e.4.2
  test/tests/mesh/nemesis/cylinder/cylinder.e.4.3
  test/tests/mesh/nemesis/nemesis_test.i
  test/tests/mesh/nemesis/tests
Labels: PR: Failed but allowed

#23199 Added post-processors in the compressor component:
  modules/thermal_hydraulics/doc/content/source/components/ShaftConnectedCompressor1Phase.md
  modules/thermal_hydraulics/include/postprocessors/ShaftConnectedCompressor1PhasePostprocessor.h
  modules/thermal_hydraulics/include/userobjects/ADShaftConnectedCompressor1PhaseUserObject.h
  modules/thermal_hydraulics/src/components/ShaftConnectedCompressor1Phase.C
  modules/thermal_hydraulics/src/postprocessors/ShaftConnectedCompressor1PhasePostprocessor.C
  modules/thermal_hydraulics/src/userobjects/ADShaftConnectedCompressor1PhaseUserObject.C
  modules/thermal_hydraulics/test/tests/components/shaft_connected_compressor_1phase/gold/shaft_motor_compressor_out.e
  modules/thermal_hydraulics/test/tests/problems/brayton_cycle/gold/closed_brayton_cycle.csv
  modules/thermal_hydraulics/test/tests/problems/brayton_cycle/gold/closed_brayton_cycle_light.csv
  modules/thermal_hydraulics/test/tests/problems/brayton_cycle/gold/open_brayton_cycle.csv
  modules/thermal_hydraulics/test/tests/problems/brayton_cycle/gold/open_brayton_cycle_light.csv
Labels: PR: Failed but allowed

#23178 SQA documentation for stochastic tools and optimization module
  modules/modules.mk
  modules/optimization/doc/config.yml
  modules/optimization/doc/content/modules/optimization/sqa/index.md
  modules/optimization/doc/content/modules/optimization/sqa/optimization_rtm.md
  modules/optimization/doc/content/modules/optimization/sqa/optimization_sdd.md
  modules/optimization/doc/content/modules/optimization/sqa/optimization_srs.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/index.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_rtm.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_sdd.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_srs.md
Labels: PR: Failed but allowed, PR: Ready for review/merge

#23183 Add SideExtremeValue
  framework/doc/content/source/postprocessors/ElementExtremeValue.md
  framework/doc/content/source/postprocessors/NodalExtremeValue.md
  framework/doc/content/source/postprocessors/SideExtremeValue.md
  framework/include/postprocessors/SideExtremeValue.h
  framework/include/postprocessors/SideVariablePostprocessor.h
  framework/src/postprocessors/ExtremeValueBase.C
  framework/src/postprocessors/SideExtremeValue.C
  framework/src/postprocessors/SideVariablePostprocessor.C
  test/tests/postprocessors/side_extreme_value/aux_nodal.i
  test/tests/postprocessors/side_extreme_value/gold/aux_elemental_out.csv
  test/tests/postprocessors/side_extreme_value/gold/aux_nodal_out.csv
  test/tests/postprocessors/side_extreme_value/gold/nonlinear_variable_out.csv
  test/tests/postprocessors/side_extreme_value/gold/nonlinear_variable_proxy_out.csv
  test/tests/postprocessors/side_extreme_value/nonlinear_variable.i
  test/tests/postprocessors/side_extreme_value/nonlinear_variable_proxy.i
  test/tests/postprocessors/side_extreme_value/tests
Labels: PR: Failed but allowed

#23077 Give more explanatory error for bad 'Mesh/block' specification
  framework/include/mesh/MooseMesh.h
  framework/include/utils/MooseUtils.h
  framework/src/mesh/MooseMesh.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/MooseAppCoordTransform.C
  framework/src/utils/MooseUtils.C
  test/tests/misc/mismatch-coord-params/tests
Labels: PR: Failed but allowed

#23205 Add PeriodicFunction
  framework/doc/content/source/functions/PeriodicFunction.md
  framework/include/functions/PeriodicFunction.h
  framework/src/functions/PeriodicFunction.C
  test/tests/functions/periodic_function/gold/periodic_function_out.e
  test/tests/functions/periodic_function/periodic_function.i
  test/tests/functions/periodic_function/tests
Labels: PR: Failed but allowed

#23206 Include MetaPhysicL parallelism headers before use
  modules/contact/include/utils/MortarContactUtils.h
Labels: PR: Failed but allowed

#23131 Fixed periods breaking path in testharness
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed

#22985 Enhancement and Typos Fixing for ParsedCurveGenerator
  framework/doc/content/source/meshgenerators/ParsedCurveGenerator.md
  framework/include/meshgenerators/ParsedCurveGenerator.h
  framework/src/meshgenerators/ParsedCurveGenerator.C
  test/tests/meshgenerators/fill_between_curves_generator/fill_between_curves.i
  test/tests/meshgenerators/parsed_curve_generator/err_cross.i
  test/tests/meshgenerators/parsed_curve_generator/gold/parsed_curve_closed_forced_ms_in.e
  test/tests/meshgenerators/parsed_curve_generator/parsed_curve_3d.i
  test/tests/meshgenerators/parsed_curve_generator/parsed_curve_closed.i
  test/tests/meshgenerators/parsed_curve_generator/parsed_curve_open.i
  test/tests/meshgenerators/parsed_curve_generator/tests
  test/tests/meshgenerators/parsed_curve_generator/xy_curve.i
Labels: PR: Failed but allowed

#23228 Revert "Fixed periods breaking path in testharness"
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed

#23003 Define relevant RGMB metadata in generate instead of in constructor, …
  framework/include/base/MooseApp.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/src/base/MooseApp.C
  modules/reactor/include/meshgenerators/AzimuthalBlockSplitGenerator.h
  modules/reactor/include/meshgenerators/PatternedCartesianMeshGenerator.h
  modules/reactor/include/meshgenerators/PatternedCartesianPeripheralModifier.h
  modules/reactor/include/meshgenerators/PatternedHexMeshGenerator.h
  modules/reactor/include/meshgenerators/PatternedHexPeripheralModifier.h
  modules/reactor/include/meshgenerators/PatternedPolygonPeripheralModifierBase.h
  modules/reactor/include/meshgenerators/PeripheralRingMeshGenerator.h
  modules/reactor/include/meshgenerators/PolygonConcentricCircleMeshGeneratorBase.h
  modules/reactor/include/meshgenerators/PolygonMeshTrimmerBase.h
  modules/reactor/include/meshgenerators/SimpleHexagonGenerator.h
  modules/reactor/include/meshgenerators/TriPinHexAssemblyGenerator.h
  modules/reactor/src/meshgenerators/AssemblyMeshGenerator.C
  modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C
  modules/reactor/src/meshgenerators/PatternedCartesianMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedCartesianPeripheralModifier.C
  modules/reactor/src/meshgenerators/PatternedHexMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedHexPeripheralModifier.C
  modules/reactor/src/meshgenerators/PatternedPolygonPeripheralModifierBase.C
  modules/reactor/src/meshgenerators/PeripheralRingMeshGenerator.C
  modules/reactor/src/meshgenerators/PinMeshGenerator.C
  modules/reactor/src/meshgenerators/PolygonConcentricCircleMeshGeneratorBase.C
  modules/reactor/src/meshgenerators/PolygonMeshTrimmerBase.C
  modules/reactor/src/meshgenerators/SimpleHexagonGenerator.C
  modules/reactor/src/meshgenerators/TriPinHexAssemblyGenerator.C
  modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/gold/assembly_metadata_transfer.e
  modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/tests
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/gold/core_metadata_transfer.e
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/tests
Labels: PR: Failed but allowed

#23239 remove non existant methods from ViscoPlasticityStressUpdate
  modules/tensor_mechanics/include/materials/ViscoplasticityStressUpdateBase.h
Labels: PR: Failed but allowed

#23232 Added additional methods to DiscreteLineSegmentInterface
  modules/thermal_hydraulics/include/interfaces/DiscreteLineSegmentInterface.h
  modules/thermal_hydraulics/src/interfaces/DiscreteLineSegmentInterface.C
  modules/thermal_hydraulics/test/include/auxkernels/DiscreteLineSegmentInterfaceTestAux.h
  modules/thermal_hydraulics/test/src/auxkernels/DiscreteLineSegmentInterfaceTestAux.C
  modules/thermal_hydraulics/test/tests/interfaces/discrete_line_segment_interface/discrete_line_segment_interface.i
  modules/thermal_hydraulics/test/tests/interfaces/discrete_line_segment_interface/gold/axial_coord.e
  modules/thermal_hydraulics/test/tests/interfaces/discrete_line_segment_interface/gold/axial_index.e
  modules/thermal_hydraulics/test/tests/interfaces/discrete_line_segment_interface/gold/discrete_line_segment_interface_out.e
  modules/thermal_hydraulics/test/tests/interfaces/discrete_line_segment_interface/gold/radial_coord.e
  modules/thermal_hydraulics/test/tests/interfaces/discrete_line_segment_interface/tests
Labels: PR: Failed but allowed

#22282 Parallel active learning in Monte Carlo simulations with Gaussian Process
  modules/stochastic_tools/doc/content/bib/stochastic_tools.bib
  modules/stochastic_tools/doc/content/source/reporters/ActiveLearningGPDecision.md
  modules/stochastic_tools/doc/content/source/samplers/ActiveLearningMonteCarloSampler.md
  modules/stochastic_tools/doc/content/source/surrogates/ActiveLearningGaussianProcess.md
  modules/stochastic_tools/doc/content/source/utils/GaussianProcessHandler.md
  modules/stochastic_tools/include/reporters/ActiveLearningGPDecision.h
  modules/stochastic_tools/include/reporters/ActiveLearningReporterBase.h
  modules/stochastic_tools/include/samplers/ActiveLearningMonteCarloSampler.h
  modules/stochastic_tools/include/surrogates/ActiveLearningGaussianProcess.h
  modules/stochastic_tools/src/reporters/ActiveLearningGPDecision.C
  modules/stochastic_tools/src/samplers/ActiveLearningMonteCarloSampler.C
  modules/stochastic_tools/src/surrogates/ActiveLearningGaussianProcess.C
  modules/stochastic_tools/src/utils/GaussianProcessHandler.C
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/gold/cov_squared_exp.json
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/gold/multiple_proc_multiple_row_ufunction.json
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/gold/single_proc_single_row_ufunction.json
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/gold/ufunction_tao.json
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/main_adam.i
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/main_tao.i
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/sub.i
  modules/stochastic_tools/test/tests/reporters/ActiveLearningGP/tests
Labels: PR: Failed but allowed

#23213 Add minimum time between successive outputs
  framework/contrib/hit/hit.cpp
  framework/doc/content/syntax/Outputs/index.md
  framework/include/outputs/Output.h
  framework/src/actions/CommonOutputAction.C
  framework/src/functions/PeriodicFunction.C
  framework/src/outputs/Output.C
  modules/fluid_properties/src/userobjects/TabulatedFluidProperties.C
  modules/navier_stokes/src/postprocessors/VolumetricFlowRate.C
  modules/stochastic_tools/src/surrogates/GaussianProcessTrainer.C
  modules/stochastic_tools/src/utils/GaussianProcessHandler.C
  modules/tensor_mechanics/src/userobjects/TensorMechanicsHardeningConstant.C
  test/tests/outputs/intervals/gold/minimum_time_interval_out.csv
  test/tests/outputs/intervals/minimum_time_interval.i
  test/tests/outputs/intervals/tests
Labels: PR: Failed but allowed

#23217 Fill in Python SQA Documentation
  framework/doc/acronyms.yml
  framework/doc/content/sqa/framework_far.md
  framework/doc/content/sqa/framework_rtm.md
  framework/doc/content/sqa/framework_scs.md
  framework/doc/content/sqa/framework_sdd.md
  framework/doc/content/sqa/framework_srs.md
  framework/doc/content/sqa/framework_stp.md
  framework/doc/content/sqa/minimum_requirements.md
  framework/doc/content/templates/sqa/app_srs.md.template
  framework/doc/content/templates/sqa/module_srs.md.template
  framework/doc/packages_config.yml
  python/MooseDocs/test/base/tests
  python/MooseDocs/test/common/tests
  python/MooseDocs/test/integrity/tests
  python/MooseDocs/test/subconfig/tests
  python/MooseDocs/test/tests
  python/MooseDocs/test/tree/tests
  python/TestHarness/tests/tests
  python/doc/content/python/index.md
  python/doc/content/python/sqa/index.md
  python/doc/content/python/sqa/python_assumptions_and_dependencies.md
  python/doc/content/python/sqa/python_far.md
  python/doc/content/python/sqa/python_rtm.md
  python/doc/content/python/sqa/python_sdd.md
  python/doc/content/python/sqa/python_sll.md
  python/doc/content/python/sqa/python_srs.md
  python/doc/content/python/sqa/python_stp.md
  python/doc/content/python/sqa/python_system_purpose.md
  python/doc/content/python/sqa/python_system_scope.md
  python/doc/content/python/sqa/python_vvr.md
  python/doc/sqa_reports.yml
Labels: PR: Failed but allowed

#23195 Add SQA design documents for NS and ray tracing
  modules/fsi/doc/content/modules/fsi/sqa/fsi_srs.md
  modules/navier_stokes/doc/content/modules/navier_stokes/sqa/navier_stokes_rtm.md
  modules/navier_stokes/doc/content/modules/navier_stokes/sqa/navier_stokes_sdd.md
  modules/navier_stokes/doc/content/modules/navier_stokes/sqa/navier_stokes_srs.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_rtm.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_sdd.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_srs.md
Labels: PR: Failed but allowed

#23272 Add reactor module SQA documents
  framework/doc/acronyms.yml
  modules/reactor/doc/content/modules/reactor/sqa/reactor_rtm.md
  modules/reactor/doc/content/modules/reactor/sqa/reactor_sdd.md
  modules/reactor/doc/content/modules/reactor/sqa/reactor_srs.md
Labels: PR: Failed but allowed

#23268 Make January 2023 news public, add February template
  modules/doc/content/newsletter/2023/2023_01.md
  modules/doc/content/newsletter/2023/2023_02.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#23284 Capture nonzero test harness exit codes in %test section
  apptainer/app.def
Labels: PR: Failed but allowed, PR: Ready for review/merge

#22974 Reorganize examples and tutorials page
  modules/combined/doc/content/modules/combined/index.md
  modules/combined/doc/content/modules/combined/tutorials/index.md
  modules/contact/doc/content/modules/contact/tutorials/index.md
  modules/doc/config.yml
  modules/doc/content/getting_started/examples_and_tutorials/index.md
  modules/level_set/doc/content/modules/level_set/index.md
  modules/level_set/doc/content/modules/level_set/level_set_examples.md
  modules/optimization/doc/content/modules/optimization/examples/forceInv_BodyLoad.md
  modules/optimization/doc/content/modules/optimization/examples/forceInv_NeumannBC.md
  modules/optimization/doc/content/modules/optimization/examples/forceInv_pointLoads.md
  modules/optimization/doc/content/modules/optimization/examples/materialInv_ConstK.md
  modules/optimization/doc/content/modules/optimization/examples/materialInv_ConvectiveBC.md
  modules/optimization/doc/content/modules/optimization/theory/InvOptTheory.md
  modules/porous_flow/doc/content/modules/porous_flow/index.md
  modules/porous_flow/doc/content/modules/porous_flow/porous_flow_examples.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/index.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/index.md
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/examples_index.md
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/index.md
Labels: PR: Failed but allowed, PR: Ready for review/merge
