Repository idaholab/moose, pull requests merged in 2023-11, with the labels that each got.

#25915 No dlopen fix
  framework/src/base/MooseApp.C
Labels: PR: Failed but allowed

#25950 Generalize torch conditional jump suppression rule
  python/TestHarness/suppressions/errors.supp
Labels: PR: Failed but allowed

#25962 Support old Nanoflann API *and* new Nanoflann API
  framework/include/utils/KDTree.h
  framework/src/constraints/AutomaticMortarGeneration.C
  framework/src/mesh/MooseMesh.C
  framework/src/userobjects/RadialAverage.C
  framework/src/userobjects/ThreadedRadialAverageLoop.C
  framework/src/utils/KDTree.C
  modules/contact/src/actions/ContactAction.C
Labels: PR: Failed but allowed

#25975 Only error w/o WASP when building, not cleaning
  framework/moose.mk
Labels: PR: Failed but allowed

#25905 Patch for new and old Nanoflann API
  framework/src/constraints/AutomaticMortarGeneration.C
Labels: PR: Failed but allowed

#25980 Add general field coord transform to newsletter
  framework/doc/content/source/transfers/MultiAppGeneralFieldTransfer.md
  modules/doc/content/newsletter/2023/2023_11.md
Labels: PR: Failed but allowed

#25982 Fix function symbols in the diffusion kernel docs
  framework/doc/content/source/kernels/Diffusion.md
Labels: PR: Failed but allowed

#25988 Another nanoflann API compatibility shim
  unit/src/KDTreeTest.C
Labels: PR: Failed but allowed

#25927 Miscellaneous items from the Physics PR
  framework/include/utils/InputParameters.h
  framework/include/utils/MultiMooseEnum.h
  framework/src/utils/InputParameters.C
  framework/src/utils/MultiMooseEnum.C
  framework/src/variables/MooseVariableFE.C
  unit/src/InputParametersTest.C
  unit/src/MooseEnumTest.C
Labels: PR: Failed but allowed

#26010 Missing argument when creating Conda env
  modules/doc/content/getting_started/installation/true_update_conda.md
Labels: PR: Failed but allowed

#25204 custom eigenvalue normalization for slepc
  framework/include/kernels/MassEigenKernel.h
  framework/include/problems/EigenProblem.h
  framework/src/kernels/MassEigenKernel.C
  framework/src/problems/EigenProblem.C
  framework/src/utils/SlepcSupport.C
  test/tests/executioners/eigen_convergence/a.i
  test/tests/executioners/eigen_convergence/b.i
  test/tests/executioners/eigen_convergence/gold/a_out_eigen_0001.csv
  test/tests/executioners/eigen_convergence/gold/b_out.csv
  test/tests/executioners/eigen_convergence/tests
Labels: PR: Ready for review/merge

#25910 Removed unnecessary warning for 'outputs' parameter
  framework/include/outputs/AdvancedOutput.h
  framework/src/outputs/AdvancedOutput.C
  test/tests/outputs/format/tests
Labels: PR: Failed but allowed

#26032 Avoid compiler warning due to uninitialized variable
  modules/stochastic_tools/src/utils/GaussianProcessHandler.C
Labels: PR: Failed but allowed

#26017 Improve links between syntax pages and folders for Trainers, Likelihood, FVICs.
  modules/doc/config.yml
  modules/stochastic_tools/doc/content/modules/stochastic_tools/enable_pytorch.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/examples/cross_validation.md
  modules/stochastic_tools/doc/content/source/libtorch/trainers/LibtorchANNTrainer.md
  modules/stochastic_tools/doc/content/source/libtorch/trainers/LibtorchDRLControlTrainer.md
  modules/stochastic_tools/doc/content/source/trainers/GaussianProcessTrainer.md
  modules/stochastic_tools/doc/content/source/trainers/NearestPointTrainer.md
  modules/stochastic_tools/doc/content/source/trainers/PODReducedBasisTrainer.md
  modules/stochastic_tools/doc/content/source/trainers/PolynomialChaosTrainer.md
  modules/stochastic_tools/doc/content/source/trainers/PolynomialRegressionTrainer.md
  modules/stochastic_tools/include/trainers/GaussianProcessTrainer.h
  modules/stochastic_tools/include/trainers/NearestPointTrainer.h
  modules/stochastic_tools/include/trainers/PODReducedBasisTrainer.h
  modules/stochastic_tools/include/trainers/PolynomialChaosTrainer.h
  modules/stochastic_tools/include/trainers/PolynomialRegressionTrainer.h
  modules/stochastic_tools/include/trainers/SurrogateTrainer.h
  modules/stochastic_tools/src/libtorch/trainers/LibtorchANNTrainer.C
  modules/stochastic_tools/src/libtorch/trainers/LibtorchDRLControlTrainer.C
  modules/stochastic_tools/src/trainers/GaussianProcessTrainer.C
  modules/stochastic_tools/src/trainers/NearestPointTrainer.C
  modules/stochastic_tools/src/trainers/PODReducedBasisTrainer.C
  modules/stochastic_tools/src/trainers/PolynomialChaosTrainer.C
  modules/stochastic_tools/src/trainers/PolynomialRegressionTrainer.C
  modules/stochastic_tools/src/trainers/SurrogateTrainer.C
Labels: PR: Failed but allowed

#26025 Increase robustness of tests from 25204
  test/tests/executioners/eigen_convergence/b.i
  test/tests/executioners/eigen_convergence/gold/b_out.csv
  test/tests/executioners/eigen_convergence/tests
Labels: PR: Failed but allowed

#25880 Add element UO for Thermochimica coupling
  modules/chemical_reactions/doc/content/source/actions/ChemicalCompositionAction.md
  modules/chemical_reactions/doc/content/source/userobjects/ThermochimicaData.md
  modules/chemical_reactions/doc/content/source/userobjects/ThermochimicaElementData.md
  modules/chemical_reactions/doc/content/source/userobjects/ThermochimicaNodalData.md
  modules/chemical_reactions/include/userobjects/ThermochimicaData.h
  modules/chemical_reactions/src/actions/ChemicalCompositionAction.C
  modules/chemical_reactions/src/userobjects/ThermochimicaData.C
  modules/chemical_reactions/test/tests/thermochimica/gold/MoRu_FV_out.e
  modules/chemical_reactions/test/tests/thermochimica/tests
Labels: PR: Failed but allowed

#25930 Add logic when creating symlink
  conda/template/build.sh
Labels: PR: Failed but allowed

#25867 Remove reference to 'trunk'
  modules/doc/content/getting_started/installation/wsl.md
  python/doc/content/python/peacock.md
Labels: PR: Failed but allowed

#25108 Allow selective exclusion of Lagrange from p-refinement
  framework/doc/content/syntax/Adaptivity/index.md
  framework/include/actions/SetAdaptivityOptionsAction.h
  framework/include/base/Adaptivity.h
  framework/include/base/Assembly.h
  framework/include/loops/ThreadedElementLoopBase.h
  framework/include/materials/MaterialPropertyStorage.h
  framework/include/mesh/MooseMesh.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/src/actions/AdaptivityAction.C
  framework/src/actions/SetAdaptivityOptionsAction.C
  framework/src/base/Adaptivity.C
  framework/src/base/Assembly.C
  framework/src/ics/InitialConditionTempl.C
  framework/src/loops/CacheChangedListsThread.C
  framework/src/loops/FlagElementsThread.C
  framework/src/loops/ProjectMaterialProperties.C
  framework/src/materials/MaterialPropertyStorage.C
  framework/src/mesh/MooseMesh.C
  framework/src/outputs/AdvancedOutput.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/variables/MooseVariableData.C
  test/tests/adaptivity/dont-p-refine/gold/test_out.csv
  test/tests/adaptivity/dont-p-refine/test.i
  test/tests/adaptivity/dont-p-refine/tests
  test/tests/materials/stateful_prop/gold/spatial_adaptivity_test_p.e-s004
  test/tests/materials/stateful_prop/gold/stateful_prop_adaptivity_test_p.e-s004
  test/tests/materials/stateful_prop/spatial_adaptivity_test.i
  test/tests/materials/stateful_prop/tests
Labels: PR: Ready for review/merge

#25838 Add support for TET14 geometric elements
  framework/include/mesh/MooseMesh.h
  modules/heat_transfer/test/tests/directional_flux_bc/gold/3d_tet14.csv
  modules/heat_transfer/test/tests/directional_flux_bc/tests
  modules/ray_tracing/src/raytracing/TraceRay.C
  modules/ray_tracing/src/raytracing/TraceRayTools.C
  modules/ray_tracing/test/tests/traceray/tet14/gold/centroid_aq_out.csv
  modules/ray_tracing/test/tests/traceray/tet14/gold/ctc_out.csv
  modules/ray_tracing/test/tests/traceray/tet14/gold/ctv_out.csv
  modules/ray_tracing/test/tests/traceray/tet14/gold/ete_out.csv
  modules/ray_tracing/test/tests/traceray/tet14/gold/side_aq_out.csv
  modules/ray_tracing/test/tests/traceray/tet14/gold/vtv_out.csv
  modules/ray_tracing/test/tests/traceray/tet14/tests
  modules/ray_tracing/unit/src/TraceRayToolsTest.C
  modules/xfem/src/efa/EFAElement3D.C
  modules/xfem/src/efa/ElementFragmentAlgorithm.C
  modules/xfem/test/tests/high_order_elements/gold/diffusion_3d_tet14_out.e
  modules/xfem/test/tests/high_order_elements/tests
  test/tests/mesh/high_order_elems/gold/high_order_elems_tet14_refine_out.e
  test/tests/mesh/high_order_elems/tests
  test/tests/meshgenerators/mesh_diagnostics_generator/tests
  test/tests/mortar/continuity-3d-non-conforming/gold/continuity_penalty_tet14_out.e
  test/tests/mortar/continuity-3d-non-conforming/gold/continuity_tet14_out.e
  test/tests/mortar/continuity-3d-non-conforming/tests
Labels: PR: Failed but allowed

#26058 Fix typos in the docs
  framework/doc/content/automatic_differentiation/index.md
  framework/doc/content/automatic_differentiation/templated_objects.md
  framework/doc/content/source/auxkernels/ConstantBoundsAux.md
  framework/doc/content/source/auxkernels/HardwareIDAux.md
  framework/doc/content/source/constraints/PeriodicSegmentalConstraint.md
  framework/doc/content/source/dirackernels/ReporterPointSource.md
  framework/doc/content/source/fvbcs/FVDirichletBC.md
  framework/doc/content/source/interfaces/SetupInterface.md
  framework/doc/content/source/kernels/AnisotropicDiffusion.md
  framework/doc/content/source/meshgenerators/MeshDiagnosticsGenerator.md
  framework/doc/content/source/postprocessors/AreaPostprocessor.md
  framework/doc/content/source/variables/MooseVariableFV.md
  framework/doc/content/syntax/Adaptivity/index.md
  framework/doc/content/syntax/ICs/index.md
  framework/doc/content/syntax/Limiters/index.md
  framework/doc/content/syntax/Mesh/Partitioner/index.md
Labels: PR: Failed but allowed

#26061 Don't ask to make a HEX20 second_order=true
  test/tests/mortar/continuity-3d-non-conforming/tests
Labels: PR: Failed but allowed

#26043 Adding the post trace and upating the documentation page for RayKernel
  modules/ray_tracing/doc/content/syntax/RayKernels/index.md
  modules/ray_tracing/include/raykernels/RayKernelBase.h
  modules/ray_tracing/src/raykernels/RayKernelBase.C
  modules/ray_tracing/src/raytracing/TraceRay.C
Labels: PR: Failed but allowed

#26075 Remove deprecated elasticity tensor class
  modules/tensor_mechanics/doc/content/source/materials/crystal_plasticity/ComputeElasticityTensorConstantRotationCP.md
  modules/tensor_mechanics/include/materials/crystal_plasticity/ComputeElasticityTensorConstantRotationCP.h
  modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeElasticityTensorConstantRotationCP.C
  modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainCPSlipRateRes.C
  modules/tensor_mechanics/src/materials/crystal_plasticity/FiniteStrainCrystalPlasticity.C
  modules/tensor_mechanics/test/tests/crystal_plasticity/monolithic_material_based/tests
  modules/tensor_mechanics/test/tests/crystal_plasticity/stress_update_material_based/tests
Labels: PR: Failed but allowed

#26023 Restore MUMPS_ARM_STR to configure_petsc.sh for manual Apple Silicon builds and elif clang-min definition changes
  apptainer/mpich.def
  conda/libmesh-vtk/conda_build_config.yaml
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/conda_build_config.yaml
  conda/libmesh/meta.yaml
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/mpich/meta.yaml
  conda/peacock/conda_build_config.yaml
  conda/peacock/meta.yaml
  conda/petsc/conda_build_config.yaml
  conda/petsc/meta.yaml
  conda/template/conda_build_config.yaml
  framework/doc/packages_config.yml
  scripts/configure_petsc.sh
  scripts/tests/versioner_hashes.yaml
Labels: PR: Failed but allowed

#26063 Fix module name
  modules/doc/content/ncrc/applications/ncrc_hpc_relap5.md
Labels: PR: Failed but allowed

#26097 Add capability to filter contribution since a certain date
  python/mooseutils/gitutils.py
  scripts/authors.py
Labels: PR: Failed but allowed

#26083 Allow MultiAppCopyTransfer to transfer vector variables
  framework/src/transfers/MultiAppDofCopyTransfer.C
  test/tests/transfers/multiapp_copy_transfer/vector-variable-transfer/gold/parent_L2_LagrangeVec_out_sub_app0.csv
  test/tests/transfers/multiapp_copy_transfer/vector-variable-transfer/parent_L2_LagrangeVec.i
  test/tests/transfers/multiapp_copy_transfer/vector-variable-transfer/sub_L2_LagrangeVec.i
  test/tests/transfers/multiapp_copy_transfer/vector-variable-transfer/tests
Labels: PR: Failed but allowed

#21230 Change the way we do Darcy/Forchheimer
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/modules/navier_stokes/pinsfv.md
  modules/navier_stokes/doc/content/source/functormaterials/FunctorErgunDragCoefficients.md
  modules/navier_stokes/doc/content/source/functormaterials/FunctorKappaFluid.md
  modules/navier_stokes/doc/content/source/fvkernels/PINSFVMomentumFriction.md
  modules/navier_stokes/include/base/NS.h
  modules/navier_stokes/include/base/NSFVBase.h
  modules/navier_stokes/include/functormaterials/FunctorDragCoefficients.h
  modules/navier_stokes/include/functormaterials/FunctorEffectiveFluidThermalConductivity.h
  modules/navier_stokes/include/functormaterials/FunctorErgunDragCoefficients.h
  modules/navier_stokes/include/functormaterials/FunctorIsotropicDragCoefficients.h
  modules/navier_stokes/include/functormaterials/FunctorIsotropicEffectiveFluidThermalConductivity.h
  modules/navier_stokes/include/functormaterials/FunctorKappaFluid.h
  modules/navier_stokes/include/functormaterials/FunctorPebbleBedDragCoefficients.h
  modules/navier_stokes/include/fvkernels/PINSFVMomentumFriction.h
  modules/navier_stokes/include/fvkernels/PINSFVMomentumFrictionCorrection.h
  modules/navier_stokes/src/functormaterials/FunctorDragCoefficients.C
  modules/navier_stokes/src/functormaterials/FunctorEffectiveFluidThermalConductivity.C
  modules/navier_stokes/src/functormaterials/FunctorErgunDragCoefficients.C
  modules/navier_stokes/src/functormaterials/FunctorKappaFluid.C
  modules/navier_stokes/src/functormaterials/PINSFVSpeedFunctorMaterial.C
  modules/navier_stokes/src/fvkernels/PINSFVMomentumFriction.C
  modules/navier_stokes/src/fvkernels/PINSFVMomentumFrictionCorrection.C
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/2d-rc-friction-action.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/2d-rc-friction.i
  modules/navier_stokes/test/tests/finite_volume/materials/ergun/ergun.i
  modules/navier_stokes/test/tests/finite_volume/materials/ergun/ergun_in.e
  modules/navier_stokes/test/tests/finite_volume/materials/ergun/gold/ergun_out.e
  modules/navier_stokes/test/tests/finite_volume/materials/ergun/tests
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/friction.i
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/transient_operation.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/2d-rc-friction.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/2d-rc-rz-by-parts.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/gold/2d-rc-rz-by-parts_out.e
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/gold/linear_friction_out.e
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/gold/rc-friction-block.e
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/gold/rc-friction-free-slip.e
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/gold/rc-friction.e
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/segregated/2d-momentum.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/segregated/gold/2d-momentum-slip-friction.e
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/pressure-corrected.py
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/pressure-interpolation-corrected-action.i
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/pressure-interpolation-corrected.i
  modules/navier_stokes/test/tests/finite_volume/pwcns/channel-flow/2d-transient-gas.i
  modules/navier_stokes/test/tests/finite_volume/wcns/natural_convection/natural_circulation_pipe.i
Labels: PR: Ready for review/merge

#26147 Investigation of valgrind of ergun friction test
  modules/navier_stokes/test/tests/finite_volume/materials/ergun/tests
Labels: PR: Failed but allowed

#26027 Duplicate points
  framework/doc/content/source/dirackernels/ReporterPointSource.md
  framework/include/dirackernels/ReporterPointSource.h
  framework/src/dirackernels/ReporterPointSource.C
  modules/optimization/src/dirackernels/ReporterTimePointSource.C
  modules/optimization/test/tests/dirackernels/reporter_time_point_source.i
  test/tests/dirackernels/reporter_point_source/2d_vpp.i
  test/tests/dirackernels/reporter_point_source/tests
Labels: PR: Failed but allowed

#26141 Fix readme for new apps
  modules/level_set/README.md
  stork/README.md
  tutorials/darcy_thermo_mech/step01_diffusion/README.md
  tutorials/tutorial02_multiapps/app/README.md
Labels: PR: Failed but allowed

#25398 Add Depletion ID Generation Capability into RGMB
  modules/reactor/doc/content/source/meshgenerators/AssemblyMeshGenerator.md
  modules/reactor/doc/content/source/meshgenerators/CoreMeshGenerator.md
  modules/reactor/include/meshgenerators/ReactorGeometryMeshBuilderBase.h
  modules/reactor/src/meshgenerators/AssemblyMeshGenerator.C
  modules/reactor/src/meshgenerators/CoreMeshGenerator.C
  modules/reactor/src/meshgenerators/ReactorGeometryMeshBuilderBase.C
  modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/gold/assembly_depl_id_pin.e
  modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/gold/assembly_depl_id_pin_type.e
  modules/reactor/test/tests/meshgenerators/assembly_mesh_generator/tests
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/gold/core_hex_depl_pin_in.e
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/gold/core_hex_depl_pin_type_in.e
  modules/reactor/test/tests/meshgenerators/core_mesh_generator/tests
Labels: PR: Failed but allowed

#26176 Have an empty default for source variable in conservative transfer
  framework/src/transfers/MultiAppConservativeTransfer.C
Labels: PR: Failed but allowed

#26169 Add myself to codeowners.
  CODEOWNERS
Labels: PR: Failed but allowed

#26186 mamba init on all console profiles
  modules/doc/content/getting_started/installation/install_miniconda.md
Labels: PR: Failed but allowed

#25943 Add volumetric eigenstrain to crystal plasticity capability
  modules/tensor_mechanics/doc/content/bib/tensor_mechanics.bib
  modules/tensor_mechanics/doc/content/source/materials/crystal_plasticity/ComputeCrystalPlasticityThermalEigenstrain.md
  modules/tensor_mechanics/doc/content/source/materials/crystal_plasticity/ComputeCrystalPlasticityVolumetricEigenstrain.md
  modules/tensor_mechanics/include/materials/crystal_plasticity/ComputeCrystalPlasticityVolumetricEigenstrain.h
  modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeCrystalPlasticityThermalEigenstrain.C
  modules/tensor_mechanics/src/materials/crystal_plasticity/ComputeCrystalPlasticityVolumetricEigenstrain.C
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/gold/hcp_thermal_eigenstrain_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/gold/hcp_volumetric_eigenstrain_decrease_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/gold/multiple_eigenstrains_test_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/gold/thermal_eigenstrain_test_011orientation_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/gold/thermal_eigenstrain_test_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/gold/volumetric_eigenstrain_increase_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/gold/volumetric_eigenstrain_parabolic_out.csv
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/hcp_aprismatic_capyramidal_slip_sys.txt
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/hcp_thermal_eigenstrain.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/hcp_volumetric_eigenstrain_decrease.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/input_slip_sys.txt
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/multiple_eigenstrains_test.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/tests
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/thermal_eigenstrain_test.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/volumetric_eigenstrain_increase.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/cp_eigenstrains/volumetric_eigenstrain_parabolic.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/hcp_single_crystal/hcp_volumetric_eigenstrain.i
  modules/tensor_mechanics/test/tests/crystal_plasticity/stress_update_material_based/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#26177 Move VectorFunctionReaction and other minor tweaks
  framework/doc/content/source/kernels/VectorFunctionReaction.md
  framework/doc/content/syntax/AuxKernels/index.md
  framework/include/bcs/ADVectorFunctionNeumannBC.h
  framework/include/bcs/VectorCurlPenaltyDirichletBC.h
  framework/include/bcs/VectorPenaltyDirichletBC.h
  framework/include/kernels/VectorFunctionReaction.h
  framework/src/kernels/VectorFunctionReaction.C
  framework/src/utils/Conversion.C
  modules/electromagnetics/doc/content/modules/electromagnetics/benchmarks/DipoleAntenna.md
  modules/electromagnetics/doc/content/modules/electromagnetics/benchmarks/EvanescentWave.md
Labels: PR: Failed but allowed
