Repository idaholab/moose, pull requests merged in 2023-07, with the labels that each got.

#24800 General block restriction for domain integral action
  modules/tensor_mechanics/src/actions/DomainIntegralAction.C
  modules/tensor_mechanics/test/tests/j_integral/gold/j_integral_2d_block_restrict_out.csv
  modules/tensor_mechanics/test/tests/j_integral/j_integral_2d_block_restrict.i
  modules/tensor_mechanics/test/tests/j_integral/tests
Labels: PR: Failed but allowed, C: Modules/Tensor Mechanics

#24852 Writing the dimensionless numbers as templates in THM
  modules/thermal_hydraulics/include/utils/Numerics.h
  modules/thermal_hydraulics/src/materials/WallFrictionChurchillMaterial.C
  modules/thermal_hydraulics/src/utils/Numerics.C
  modules/thermal_hydraulics/unit/src/NumericsTest.C
Labels: PR: Failed but allowed

#24908 Fix moose Conda package
  conda/moose/run_test.sh
Labels: PR: Ready for review/merge

#24892 Cleanup and add ChainedReal support
  framework/include/utils/BicubicInterpolation.h
  framework/include/utils/BidimensionalInterpolation.h
  framework/include/utils/BilinearInterpolation.h
  framework/src/utils/BicubicInterpolation.C
  framework/src/utils/BilinearInterpolation.C
  unit/src/BicubicInterpolationTest.C
  unit/src/BilinearInterpolationTest.C
Labels: PR: Auto Merge

#24981 Add WASP as a build dependency
  conda/moose/meta.yaml
Labels: PR: Ready for review/merge

#25001 Documentation and miscelaneous fixes
  framework/doc/content/source/meshgenerators/FileMeshGenerator.md
  framework/src/userobjects/SolutionUserObject.C
  modules/external_petsc_solver/doc/content/source/timesteppers/ExternalPetscTimeStepper.md
  modules/navier_stokes/src/fvkernels/WCNSFVMixingLengthEnergyDiffusion.C
Labels: PR: Failed but allowed

#25033 Correctly report safe access for vectors/matrices in displaced problem
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/SubProblem.h
  framework/src/problems/DisplacedProblem.C
Labels: PR: Failed but allowed
