Repository idaholab/moose, pull requests merged in 2023-04, with the labels that each got.

#23924 More division by zero protection in INSAD
  modules/navier_stokes/src/materials/INSADStabilized3Eqn.C
Labels: PR: Failed but allowed

#23932 Revert "Enhancing tagging interface"
  framework/include/base/Assembly.h
  framework/include/interfaces/Coupleable.h
  framework/include/loops/ComputeMortarFunctor.h
  framework/include/loops/ComputeNodalUserObjectsThread.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/base/Assembly.C
  framework/src/interfaces/Coupleable.C
  framework/src/kernels/EigenKernel.C
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/loops/ComputeNodalUserObjectsThread.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/timeintegrators/CrankNicolson.C
  test/include/userobjects/CallTaggedResidualsTest.h
  test/src/userobjects/CallTaggedResidualsTest.C
  test/tests/tag/gold/old_eigen_tag_out.e
  test/tests/tag/old_eigen_tag.i
  test/tests/tag/tag_residual_call.i
  test/tests/tag/tests
Labels: PR: Failed but allowed

#23962 Make AugmentSparsityOnInterface thread-safe
  framework/include/relationshipmanagers/AugmentSparsityOnInterface.h
  framework/src/relationshipmanagers/AugmentSparsityOnInterface.C
  test/tests/mortar/ad_periodic_segmental_constraint/penalty_periodic_checker2d.i
  test/tests/mortar/ad_periodic_segmental_constraint/penalty_periodic_simple3d.i
  test/tests/mortar/ad_periodic_segmental_constraint/periodic_simple2d.i
  test/tests/mortar/ad_periodic_segmental_constraint/periodic_simple3d.i
  test/tests/mortar/ad_periodic_segmental_constraint/testperiodicsole.i
  test/tests/mortar/convergence-studies/gap-conductance/gap-conductance.i
  test/tests/mortar/periodic_segmental_constraint/gold/periodic_checker2d_out.csv
  test/tests/mortar/periodic_segmental_constraint/penalty_periodic_checker2d.i
  test/tests/mortar/periodic_segmental_constraint/penalty_periodic_simple3d.i
  test/tests/mortar/periodic_segmental_constraint/periodic_aux2d.i
  test/tests/mortar/periodic_segmental_constraint/periodic_checker2d.i
  test/tests/mortar/periodic_segmental_constraint/periodic_simple2d.i
  test/tests/mortar/periodic_segmental_constraint/periodic_simple3d.i
  test/tests/mortar/periodic_segmental_constraint/testperiodicsole.i
Labels: PR: Failed but allowed

#23984 Catch `Job` exception in test harness, resolve `scikit-image` deprecation
  python/TestHarness/schedulers/RunParallel.py
  python/TestHarness/schedulers/Scheduler.py
  python/mooseutils/ImageDiffer.py
Labels: PR: Ready for review/merge

#23978 DepletionIDGenerator Optimization
  framework/src/utils/MooseMeshUtils.C
  modules/reactor/src/meshgenerators/DepletionIDGenerator.C
Labels: PR: Failed but allowed

#23987 Add phase field citation
  modules/doc/content/citing.md
Labels: PR: Failed but allowed

#23960 Add nemesis to output intermediate mesh
  framework/src/interfaces/OutputInterface.C
  framework/src/meshgenerators/MeshGenerator.C
  test/tests/meshgenerators/output_intermediate_mesh/gold/left_in.e
  test/tests/meshgenerators/output_intermediate_mesh/gold/left_in.e.2.0
  test/tests/meshgenerators/output_intermediate_mesh/gold/left_in.e.2.1
  test/tests/meshgenerators/output_intermediate_mesh/output_intermediate_mesh.i
  test/tests/meshgenerators/output_intermediate_mesh/tests
Labels: PR: Failed but allowed

#24023 Miscellaneous fixups
  CODEOWNERS
  framework/src/meshgenerators/ConcentricCircleMeshGenerator.C
  framework/src/meshgenerators/MeshGenerator.C
  framework/src/meshgenerators/PatternedMeshGenerator.C
  framework/src/problems/FEProblemBase.C
  modules/ray_tracing/src/raytracing/TraceRay.C
  test/tests/mesh/save_in_meshes/gold/left_block_in.e
  test/tests/mesh/save_in_meshes/save_in_meshes.i
  test/tests/mesh/save_in_meshes/save_in_meshes_with_D.i
  test/tests/mesh/save_in_meshes/tests
Labels: PR: Failed but allowed

#24022 Add enum for how to handle zero reference values
  framework/include/problems/ReferenceResidualProblem.h
  framework/src/problems/ReferenceResidualProblem.C
  test/tests/problems/reference_residual_problem/gold/zero_rel_tolerance_ref_out.csv
  test/tests/problems/reference_residual_problem/no_ref.i
  test/tests/problems/reference_residual_problem/tests
Labels: PR: Failed but allowed

#23999 Update materialize.min.js
  framework/doc/content/contrib/materialize/materialize.min.js
Labels: PR: Failed but allowed

#24057 Correct coverage reqs due to improper collection
  .coverage
Labels: PR: Failed but allowed

#24052 Do not send empty vectors with parallel sync
  framework/src/meshgenerators/LowerDBlockFromSidesetGenerator.C
  modules/ray_tracing/src/outputs/RayTracingMeshOutput.C
  modules/ray_tracing/src/raytracing/ClaimRays.C
  modules/ray_tracing/src/userobjects/RayTracingStudy.C
Labels: PR: Ready for review/merge

#24039 Clean up JSON output operations
  framework/include/outputs/JsonIO.h
  framework/include/reporters/ReporterContext.h
  framework/src/outputs/JSONOutput.C
  framework/src/outputs/JsonIO.C
  modules/stochastic_tools/include/surrogates/PolynomialChaos.h
Labels: PR: Ready for review/merge

#24033 Better enable split mesh for multiapp configurations
  framework/doc/content/sqa/framework_srs.md
  framework/doc/content/syntax/Mesh/splitting.md
  framework/include/actions/SetupMeshAction.h
  framework/include/base/MooseApp.h
  framework/include/mesh/MooseMesh.h
  framework/src/actions/AdaptivityAction.C
  framework/src/actions/ExecuteMeshGenerators.C
  framework/src/actions/SetupMeshAction.C
  framework/src/actions/SetupMeshCompleteAction.C
  framework/src/base/MooseApp.C
  framework/src/mesh/MooseMesh.C
  framework/src/outputs/ConsoleUtils.C
  test/tests/mesh/splitting/tests
Labels: PR: Ready for review/merge

#23954 Allow some tolerance in 3D qp projection
  framework/src/utils/MortarUtils.C
  modules/combined/test/tests/3d-mortar-projection-tolerancing/test.i
  modules/combined/test/tests/3d-mortar-projection-tolerancing/test.msh
  modules/combined/test/tests/3d-mortar-projection-tolerancing/tests
Labels: PR: Failed but allowed

#24063 Fixup regression in empty collection indicator message
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/test/extensions/test_sqa.py
Labels: PR: Failed but allowed

#23941 Allow ADNodalBC to process non-local dofs
  framework/include/base/Assembly.h
  framework/include/bcs/ADNodalBC.h
  framework/src/bcs/ADDirichletBCBase.C
  framework/src/bcs/ADNodalBC.C
  framework/src/bcs/NeumannBC.C
  framework/src/systems/NonlinearSystemBase.C
  test/include/bcs/ADAverageValuePin.h
  test/include/relationshipmanagers/GhostEverything.h
  test/src/bcs/ADAverageValuePin.C
  test/src/relationshipmanagers/GhostEverything.C
  test/tests/bcs/ad_nodal_bc_nonlocal_dependence/gold/test_out.e
  test/tests/bcs/ad_nodal_bc_nonlocal_dependence/test.i
  test/tests/bcs/ad_nodal_bc_nonlocal_dependence/tests
Labels: PR: Failed but allowed

#24053 Adjust petsc options to use settings for every nonlinear system.
  framework/src/utils/PetscSupport.C
Labels: PR: Failed but allowed

#24070 Fix boundary id offset code with distributed meshes
  framework/src/meshgenerators/GeneratedMeshGenerator.C
  test/tests/meshgenerators/generated_mesh_generator/tests
Labels: PR: Failed but allowed

#24077 Only initialize the diagonal of the coupling matrix for diagonal coupling
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed

#23603 Redistribute stateful material properties
  framework/include/materials/MaterialProperty.h
  framework/include/materials/MaterialPropertyStorage.h
  framework/include/problems/FEProblemBase.h
  framework/include/relationshipmanagers/RedistributeProperties.h
  framework/include/utils/HashMap.h
  framework/src/loops/CacheChangedListsThread.C
  framework/src/loops/ProjectMaterialProperties.C
  framework/src/materials/MaterialPropertyStorage.C
  framework/src/problems/FEProblemBase.C
  framework/src/relationshipmanagers/RedistributeProperties.C
  modules/doc/content/newsletter/2023/2023_04.md
  modules/porous_flow/test/src/vectorpostprocessors/DiracPointsWriter.C
  test/tests/materials/stateful_prop/spatial_adaptivity_test.i
  test/tests/materials/stateful_prop/stateful_prop_adaptivity_test.i
Labels: PR: Failed but allowed

#24080 Makefile improvements
  framework/app.mk
  framework/moose.mk
Labels: PR: Failed but allowed, PR: Ready for review/merge

#24104 PorousFlowHysteresisOrder.C changes to avoid sizing issue
  modules/porous_flow/src/materials/PorousFlowHysteresisOrder.C
  modules/porous_flow/test/tests/hysteresis/1phase_bc.i
  modules/porous_flow/test/tests/hysteresis/gold/1phase_bc_out.csv
  modules/porous_flow/test/tests/hysteresis/tests
Labels: PR: Failed but allowed

#24100 Clean-up augmented lagrange contact problem
  modules/contact/src/problems/AugmentedLagrangianContactProblem.C
Labels: PR: Failed but allowed

#24115 Add flexibility in INSFEFluidEnergyDirichletBC
  modules/navier_stokes/include/bcs/INSFEFluidEnergyDirichletBC.h
  modules/navier_stokes/src/bcs/INSFEFluidEnergyDirichletBC.C
  modules/navier_stokes/test/tests/finite_element/pins/channel-flow/pm_reverse_flow.i
Labels: PR: Failed but allowed

#24074 Made loss coefficient controllable in volume junctions
  modules/thermal_hydraulics/src/components/VolumeJunction1Phase.C
  modules/thermal_hydraulics/src/userobjects/ADVolumeJunction1PhaseUserObject.C
  modules/thermal_hydraulics/test/tests/components/volume_junction_1phase/gold/phy.form_loss_crtl.csv
  modules/thermal_hydraulics/test/tests/components/volume_junction_1phase/phy.form_loss.i
  modules/thermal_hydraulics/test/tests/components/volume_junction_1phase/tests
Labels: PR: Failed but allowed

#23860 Allowed `HeatStructure2DCoupler` to have a gap
  modules/thermal_hydraulics/doc/content/source/components/HeatStructure2DCoupler.md
  modules/thermal_hydraulics/doc/content/source/components/HeatStructure2DRadiationCouplerRZ.md
  modules/thermal_hydraulics/include/bcs/HeatStructure2DCouplerBC.h
  modules/thermal_hydraulics/include/bcs/HeatStructure2DRadiationCouplerRZBC.h
  modules/thermal_hydraulics/include/components/Component.h
  modules/thermal_hydraulics/include/components/Component2D.h
  modules/thermal_hydraulics/include/components/HeatStructure2DCouplerBase.h
  modules/thermal_hydraulics/include/components/HeatStructure2DRadiationCouplerRZ.h
  modules/thermal_hydraulics/include/components/HeatStructureBase.h
  modules/thermal_hydraulics/include/components/HeatStructureCylindricalBase.h
  modules/thermal_hydraulics/include/components/HeatStructurePlate.h
  modules/thermal_hydraulics/include/interfaces/HSBoundaryInterface.h
  modules/thermal_hydraulics/src/bcs/HeatStructure2DCouplerBC.C
  modules/thermal_hydraulics/src/bcs/HeatStructure2DRadiationCouplerRZBC.C
  modules/thermal_hydraulics/src/components/Component2D.C
  modules/thermal_hydraulics/src/components/HSBoundary.C
  modules/thermal_hydraulics/src/components/HeatSourceFromTotalPower.C
  modules/thermal_hydraulics/src/components/HeatStructure2DCoupler.C
  modules/thermal_hydraulics/src/components/HeatStructure2DCouplerBase.C
  modules/thermal_hydraulics/src/components/HeatStructure2DRadiationCouplerRZ.C
  modules/thermal_hydraulics/src/components/HeatStructureBase.C
  modules/thermal_hydraulics/src/components/HeatStructureCylindrical.C
  modules/thermal_hydraulics/src/components/HeatStructureCylindricalBase.C
  modules/thermal_hydraulics/src/components/HeatStructurePlate.C
  modules/thermal_hydraulics/src/interfaces/HSBoundaryInterface.C
  modules/thermal_hydraulics/test/tests/components/heat_structure_2d_coupler/gold/separated_out.csv
  modules/thermal_hydraulics/test/tests/components/heat_structure_2d_coupler/separated.i
  modules/thermal_hydraulics/test/tests/components/heat_structure_2d_coupler/tests
  modules/thermal_hydraulics/test/tests/components/heat_transfer_from_heat_structure_1phase/tests
Labels: PR: Failed but allowed

#22405 Some decently working field split options
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/2d-rc-no-slip.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/gold/2d-rc-no-slip-fsp.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/tests
Labels: PR: Failed but allowed

#24127 Fix excess material property storage entry creation
  framework/src/loops/ComputeMarkerThread.C
  framework/src/materials/MaterialPropertyStorage.C
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed

#24139 Initialize variable causing valgrind failure
  modules/stochastic_tools/include/samplers/ActiveLearningMonteCarloSampler.h
Labels: PR: Failed but allowed

#21904 Transfinite mesh generator
  framework/doc/content/media/meshgenerators/mesharc.png
  framework/doc/content/source/meshgenerators/TransfiniteMeshGenerator.md
  framework/include/meshgenerators/TransfiniteMeshGenerator.h
  framework/src/meshgenerators/TransfiniteMeshGenerator.C
  test/tests/meshgenerators/transfinite_generator/annular_transf_generator.i
  test/tests/meshgenerators/transfinite_generator/arccircle_generator.i
  test/tests/meshgenerators/transfinite_generator/arccircle_midpoint_generator.i
  test/tests/meshgenerators/transfinite_generator/discrete_generator.i
  test/tests/meshgenerators/transfinite_generator/gold/annular_transf_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/arccircle_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/arccircle_midpoint_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/discrete_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/parsed_annular_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/parsed_biased_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/parsed_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/quadrilater_generator_in.e
  test/tests/meshgenerators/transfinite_generator/parsed_annular_generator.i
  test/tests/meshgenerators/transfinite_generator/parsed_biased_generator.i
  test/tests/meshgenerators/transfinite_generator/parsed_generator.i
  test/tests/meshgenerators/transfinite_generator/quadrilater_generator.i
  test/tests/meshgenerators/transfinite_generator/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#24138 Change from PETSC_NULL to LIBMESH_PETSC_NULLPTR
  framework/src/outputs/PetscOutput.C
  framework/src/utils/PetscDMMoose.C
  framework/src/utils/PetscSupport.C
Labels: PR: Failed but allowed

#24147 Close vectors as necessary in CrankNicolson
  framework/src/timeintegrators/CrankNicolson.C
Labels: PR: Failed but allowed

#24078 Block restrict domain integral objects
  modules/tensor_mechanics/src/actions/DomainIntegralAction.C
Labels: PR: Failed but allowed

#24157 Fix missed PETSC_NULL
  framework/src/utils/PetscSupport.C
Labels: PR: Failed but allowed

#24126 Document and improve augmented Lagrange loop
  framework/include/geomsearch/GeometricSearchData.h
  framework/src/geomsearch/GeometricSearchData.C
  framework/src/systems/NonlinearSystemBase.C
  modules/contact/include/constraints/MechanicalContactConstraint.h
  modules/contact/include/problems/AugmentedLagrangianContactProblem.h
  modules/contact/src/actions/ContactAction.C
  modules/contact/src/constraints/MechanicalContactConstraint.C
  modules/contact/src/dampers/ContactSlipDamper.C
  modules/contact/src/problems/AugmentedLagrangianContactProblem.C
  modules/xfem/include/dirackernels/XFEMPressure.h
  modules/xfem/src/dirackernels/XFEMPressure.C
Labels: PR: Failed but allowed

#24166 Revert "Revert "Enhancing tagging interface""
  framework/include/base/Assembly.h
  framework/include/interfaces/Coupleable.h
  framework/include/loops/ComputeMortarFunctor.h
  framework/include/loops/ComputeNodalUserObjectsThread.h
  framework/include/meshgenerators/MeshGenerator.h
  framework/include/problems/DisplacedProblem.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/base/Assembly.C
  framework/src/interfaces/Coupleable.C
  framework/src/kernels/EigenKernel.C
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/loops/ComputeNodalUserObjectsThread.C
  framework/src/problems/DisplacedProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/timeintegrators/CrankNicolson.C
  test/include/userobjects/CallTaggedResidualsTest.h
  test/src/userobjects/CallTaggedResidualsTest.C
  test/tests/tag/gold/old_eigen_tag_out.e
  test/tests/tag/old_eigen_tag.i
  test/tests/tag/tag_residual_call.i
  test/tests/tag/tests
Labels: PR: Failed but allowed

#24163 Start using apptainer builds for civet testing
  .coverage
  modules/tensor_mechanics/examples/cframe_iga/tests
Labels: PR: Failed but allowed

#24075 Penalty frictional mortar contact
  modules/contact/doc/content/source/auxkernels/PenaltyMortarUserObjectAux.md
  modules/contact/doc/content/source/userobjects/LMWeightedGapUserObject.md
  modules/contact/doc/content/source/userobjects/LMWeightedVelocitiesUserObject.md
  modules/contact/doc/content/source/userobjects/PenaltyFrictionUserObject.md
  modules/contact/doc/content/source/userobjects/PenaltyWeightedGapUserObject.md
  modules/contact/include/actions/ContactAction.h
  modules/contact/include/auxkernels/PenaltyMortarUserObjectAux.h
  modules/contact/include/userobjects/PenaltyFrictionUserObject.h
  modules/contact/include/userobjects/PenaltyWeightedGapUserObject.h
  modules/contact/include/userobjects/WeightedGapUserObject.h
  modules/contact/include/utils/MortarContactUtils.h
  modules/contact/src/actions/ContactAction.C
  modules/contact/src/auxkernels/PenaltyMortarUserObjectAux.C
  modules/contact/src/userobjects/LMWeightedGapUserObject.C
  modules/contact/src/userobjects/LMWeightedVelocitiesUserObject.C
  modules/contact/src/userobjects/PenaltyFrictionUserObject.C
  modules/contact/src/userobjects/PenaltyWeightedGapUserObject.C
  modules/contact/src/userobjects/WeightedGapUserObject.C
  modules/contact/src/userobjects/WeightedVelocitiesUserObject.C
  modules/contact/test/tests/3d-mortar-contact/frictional-mortar-3d-penalty.i
  modules/contact/test/tests/3d-mortar-contact/frictionless-mortar-3d-penalty.i
  modules/contact/test/tests/3d-mortar-contact/gold/frictional-mortar-3d-penalty_out.e
  modules/contact/test/tests/3d-mortar-contact/gold/frictionless-mortar-3d-penalty_out.e
  modules/contact/test/tests/3d-mortar-contact/tests
  modules/contact/test/tests/bouncing-block-contact/frictional-penalty-weighted-vel.i
  modules/contact/test/tests/bouncing-block-contact/frictionless-penalty-weighted-gap-action.i
  modules/contact/test/tests/bouncing-block-contact/gold/frictionless-penalty-weighted-gap-action_out.e
  modules/contact/test/tests/bouncing-block-contact/gold/parallel-frictional-penalty-weighted-vel_out.e
  modules/contact/test/tests/bouncing-block-contact/tests
  modules/contact/test/tests/multiple_contact_pairs/tests
  modules/contact/test/tests/pdass_problems/cylinder_friction_penalty.i
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_penalty_check_cont_press_FINAL.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_penalty_check_friction_FINAL.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_penalty_check_x_disp_FINAL.csv
  modules/contact/test/tests/pdass_problems/gold/cylinder_friction_penalty_check_y_disp_FINAL.csv
  modules/contact/test/tests/pdass_problems/gold/ironing_penalty_action_out_penalty_normal_pressure_0012.csv
  modules/contact/test/tests/pdass_problems/gold/ironing_penalty_out_penalty_normal_pressure_0012.csv
  modules/contact/test/tests/pdass_problems/ironing_penalty.i
  modules/contact/test/tests/pdass_problems/ironing_penalty_action.i
  modules/contact/test/tests/pdass_problems/tests
Labels: PR: Failed but allowed

#23917 Initial look at transient material inverse optimization
  framework/src/userobjects/SolutionUserObject.C
  modules/optimization/doc/content/source/userobjects/AdjointSolutionUserObject.md
  modules/optimization/examples/materialTransient/forward.i
  modules/optimization/examples/materialTransient/gold/forward_out_data_0011.csv
  modules/optimization/examples/materialTransient/gold/optimize_grad_out_forward0.e
  modules/optimization/examples/materialTransient/gold/optimize_nograd_out_forward0.e
  modules/optimization/examples/materialTransient/gradient.i
  modules/optimization/examples/materialTransient/optimize_grad.i
  modules/optimization/examples/materialTransient/optimize_nograd.i
  modules/optimization/examples/materialTransient/tests
  modules/optimization/examples/simpleTransient/gold/grad.csv
  modules/optimization/examples/simpleTransient/gold/main_mesh_out_forward0.e
  modules/optimization/examples/simpleTransient/main_gradient.i
  modules/optimization/examples/simpleTransient/main_mesh.i
  modules/optimization/include/userobjects/AdjointSolutionUserObject.h
  modules/optimization/src/userobjects/AdjointSolutionUserObject.C
  modules/optimization/src/vectorpostprocessors/OptimizationFunctionInnerProductHelper.C
  modules/optimization/test/tests/userobjects/adjoint_solution/adjoint.i
  modules/optimization/test/tests/userobjects/adjoint_solution/forward.i
  modules/optimization/test/tests/userobjects/adjoint_solution/tests
  modules/optimization/test/tests/vectorpostprocessors/element_source_inner_product/gold/element_source_inner_product_out_inner_product_0011.csv
Labels: PR: Failed but allowed

#24148 Remove repeated pairs from contact action
  modules/contact/include/actions/ContactAction.h
  modules/contact/src/actions/ContactAction.C
  modules/contact/test/tests/multiple_contact_pairs/gold/multiple_pairs_cleanup_out.e
  modules/contact/test/tests/multiple_contact_pairs/tests
Labels: PR: Failed but allowed

#24191 Install all module tests with the combined install
  modules/Makefile
  modules/combined/Makefile
  modules/combined/combined_installable_dirs.mk
  modules/combined/test/include/base/CombinedTestApp.h
  modules/combined/test/src/base/CombinedTestApp.C
Labels: PR: Failed but allowed

#24207 Fixing valgrind timeout in optimization module tests
  modules/optimization/examples/materialTransient/tests
Labels: PR: Failed but allowed

#24220 Check for mesh existance before checking split status
  framework/src/actions/ExecuteMeshGenerators.C
Labels: PR: Failed but allowed

#24224 More apptainer things
  apptainer/app.def
  apptainer/moose.def
Labels: PR: Failed but allowed

#24221 Re-enable multiple mortar contact action blocks capability
  modules/contact/src/actions/ContactAction.C
  modules/contact/test/tests/multiple_contact_pairs/gold/multiple_pairs_mortar_friction_out.e
  modules/contact/test/tests/multiple_contact_pairs/gold/multiple_pairs_mortar_out.e
  modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar.i
  modules/contact/test/tests/multiple_contact_pairs/multiple_pairs_mortar_friction.i
  modules/contact/test/tests/multiple_contact_pairs/tests
  modules/contact/test/tests/pdass_problems/ironing_penalty_action.i
Labels: PR: Failed but allowed
