Repository idaholab/moose, pull requests merged in 2024-08, with the labels that each got.

#28256 July 2024 newsletter
  modules/doc/content/newsletter/2024/2024_07.md
  modules/doc/content/newsletter/2024/2024_08.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#28284 Update coreform cubit docs
  framework/doc/content/source/meshgenerators/XYMeshLineCutter.md
  framework/src/outputs/Exodus.C
  framework/src/utils/PetscDMMoose.C
  modules/doc/content/application_usage/mesh_block_type.md
  modules/doc/content/getting_started/examples_and_tutorials/examples/ex01_inputfile.md
  modules/doc/content/getting_started/examples_and_tutorials/examples/ex02_kernel.md
  modules/doc/content/getting_started/examples_and_tutorials/examples/ex03_coupling.md
  modules/doc/content/getting_started/examples_and_tutorials/examples/ex20_user_objects.md
  modules/doc/content/getting_started/examples_and_tutorials/tutorial04_meshing/step01_overview.md
  modules/heat_transfer/doc/content/modules/heat_transfer/tutorials/introduction/therm_step01.md
  modules/solid_mechanics/doc/content/modules/solid_mechanics/tutorials/introduction/step01.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/paraview_basics.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/thm_tutorial.md
  tutorials/tutorial04_meshing/doc/content/getting_started/examples_and_tutorials/tutorial04_meshing/presentation/tutorial04_step01_overview.md
Labels: PR: Failed but allowed

#27810 Ghosting boundaries
  framework/doc/content/syntax/Mesh/splitting.md
  modules/heat_transfer/include/actions/ThermalContactAction.h
  modules/heat_transfer/include/relationshipmanagers/GhostBoundary.h
  modules/heat_transfer/src/actions/ThermalContactAction.C
  modules/heat_transfer/src/bcs/GapHeatTransfer.C
  modules/heat_transfer/src/relationshipmanagers/GhostBoundary.C
  modules/heat_transfer/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/perfect_split.i
  modules/heat_transfer/test/tests/heat_conduction/2d_quadrature_gap_heat_transfer/tests
Labels: PR: Failed but allowed

#28271 Improving documentation for acquired software related to CA2024-1659
  framework/doc/content/sqa/framework_sll.md
Labels: PR: Failed but allowed

#28285 Update MooseServer formatting to not remove include directives
  framework/src/base/MooseServer.C
Labels: PR: Failed but allowed

#28353 Loosen partitioning tolerance
  test/tests/partitioners/petsc_partitioner/tests
Labels: PR: Failed but allowed

#28321 Automatically setup multiple preconditioners for Newton
  framework/include/problems/FEProblemBase.h
  framework/src/actions/CreateExecutionerAction.C
  framework/src/outputs/ConsoleUtils.C
  framework/src/preconditioners/MoosePreconditioner.C
  framework/src/problems/FEProblemBase.C
  test/tests/misc/multiple-nl-systems/different-vars-per-system.i
  test/tests/misc/multiple-nl-systems/gold/different-vars-per-system_out.e
  test/tests/misc/multiple-nl-systems/tests
Labels: PR: Failed but allowed

#28351 Don't add redundant GhostBoundary objects
  framework/include/relationshipmanagers/GhostBoundary.h
  framework/src/relationshipmanagers/GhostBoundary.C
  framework/src/relationshipmanagers/GhostEverything.C
  test/include/userobjects/TestGhostBoundarySideUserObject.h
  test/src/userobjects/TestGhostBoundarySideUserObject.C
  test/tests/relationship_managers/ghost_boundary/gold/test_out.csv
  test/tests/relationship_managers/ghost_boundary/test.i
  test/tests/relationship_managers/ghost_boundary/tests
Labels: C: Framework

#28267 Add MooseServer completion of parameters required in blocks
  framework/include/base/MooseServer.h
  framework/src/base/MooseServer.C
  unit/src/MooseServerTest.C
Labels: PR: Failed but allowed

#28346 Update MooseServer formatting to not edit input that is malformed
  framework/src/base/MooseServer.C
Labels: PR: Failed but allowed

#28221 Functor support for ParsedMaterial
  framework/doc/content/source/materials/ParsedMaterial.md
  framework/include/materials/ParsedMaterialBase.h
  framework/include/materials/ParsedMaterialHelper.h
  framework/src/materials/DerivativeParsedMaterial.C
  framework/src/materials/ParsedMaterial.C
  framework/src/materials/ParsedMaterialBase.C
  framework/src/materials/ParsedMaterialHelper.C
  test/tests/materials/parsed/gold/parsed_material_with_functors_out.e
  test/tests/materials/parsed/parsed_material_with_functors.i
  test/tests/materials/parsed/tests
Labels: PR: Failed but allowed

#28395 Respect part_package if set by user
  framework/src/partitioner/PetscExternalPartitioner.C
Labels: PR: Failed but allowed

#28269 ThermocoupleSensorPostprocessor changes
  modules/misc/doc/content/source/postprocessors/ThermocoupleSensorPostprocessor.md
  modules/misc/include/postprocessors/ThermocoupleSensorPostprocessor.h
  modules/misc/src/postprocessors/ThermocoupleSensorPostprocessor.C
  modules/misc/test/tests/sensor_postprocessor/gold/transient_thermocouple_sensor_out.csv
  modules/misc/test/tests/sensor_postprocessor/transient_thermocouple_sensor.i
Labels: PR: Failed but allowed

#28417 Make test valgrind heavy
  test/tests/outputs/format/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28405 better unique id approach for RevolveGenerator
  framework/src/meshgenerators/AdvancedExtruderGenerator.C
  modules/reactor/src/meshgenerators/RevolveGenerator.C
Labels: PR: Failed but allowed

#28384 Add prefactor to the HillCreepStressUpdate model
  modules/solid_mechanics/include/materials/HillCreepStressUpdate.h
  modules/solid_mechanics/src/materials/HillCreepStressUpdate.C
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_x_3d_anisoElasticity.i
Labels: PR: Failed but allowed

#28421 deprecate mob_name in MatReaction
  framework/src/kernels/ADMatReaction.C
  framework/src/kernels/MatReaction.C
  modules/combined/examples/publications/rapid_dev/fig6.i
  modules/fsi/test/tests/2d-small-strain-transient/ad-fsi-flat-channel.i
  modules/fsi/test/tests/2d-small-strain-transient/fsi_flat_channel.i
  modules/phase_field/examples/multiphase/GrandPotential3Phase_masscons.i
  modules/phase_field/test/tests/KKS_system/kks_multiphase.i
  modules/phase_field/test/tests/KKS_system/lagrange_multiplier.i
  modules/phase_field/test/tests/SimpleACInterface/SimpleCoupledACInterface.i
  modules/phase_field/test/tests/electrochem_sintering/ElectrochemicalSintering_test.i
  modules/phase_field/test/tests/mobility_derivative/coupledmatdiffusion.i
  modules/phase_field/test/tests/phase_field_kernels/CoupledAllenCahn.i
  modules/phase_field/test/tests/phase_field_kernels/CoupledCoefAllenCahn.i
  modules/phase_field/test/tests/phase_field_kernels/MatGradSquareCoupled.i
  modules/stochastic_tools/test/tests/actions/parameter_study_action/sub_eigen.i
  test/src/kernels/RenamedMatReaction.C
Labels: PR: Failed but allowed

#28115 Restore transient multiapps by default
  framework/include/multiapps/FullSolveMultiApp.h
  framework/include/multiapps/MultiApp.h
  framework/include/multiapps/TransientMultiApp.h
  framework/src/multiapps/FullSolveMultiApp.C
  framework/src/multiapps/MultiApp.C
  framework/src/multiapps/TransientMultiApp.C
  test/tests/multiapps/picard/picard_adaptive_parent.i
  test/tests/multiapps/picard_multilevel/picard_parent.i
  test/tests/multiapps/picard_postprocessor/transient_main.i
  test/tests/multiapps/relaxation/picard_parent.i
  test/tests/multiapps/relaxation/picard_relaxed_parent.i
  test/tests/multiapps/relaxation/sub_relaxed_parent.i
  test/tests/multiapps/secant/transient_main.i
  test/tests/multiapps/secant_postprocessor/transient_main.i
  test/tests/multiapps/steffensen/transient_main.i
  test/tests/multiapps/steffensen_postprocessor/transient_main.i
  test/tests/transfers/transfer_once_per_fixed_point/parent.i
Labels: PR: Failed but allowed

#28394 Added TwoPhaseNCGPartialPressureFluidProperties
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/source/fluidproperties/IdealRealGasMixtureFluidProperties.md
  modules/fluid_properties/doc/content/source/fluidproperties/TwoPhaseNCGPartialPressureFluidProperties.md
  modules/fluid_properties/doc/content/source/functions/TwoPhaseNCGPartialPressureFunction.md
  modules/fluid_properties/include/fluidproperties/TwoPhaseNCGPartialPressureFluidProperties.h
  modules/fluid_properties/include/fluidproperties/VaporMixtureFluidProperties.h
  modules/fluid_properties/include/functions/TwoPhaseNCGPartialPressureFunction.h
  modules/fluid_properties/include/userobjects/FluidPropertiesInterrogator.h
  modules/fluid_properties/src/fluidproperties/TwoPhaseNCGPartialPressureFluidProperties.C
  modules/fluid_properties/src/fluidproperties/VaporMixtureFluidProperties.C
  modules/fluid_properties/src/functions/TwoPhaseNCGPartialPressureFunction.C
  modules/fluid_properties/src/userobjects/FluidPropertiesInterrogator.C
  modules/fluid_properties/test/tests/fp_interrogator/2ph_ncg_p_T.i
  modules/fluid_properties/test/tests/fp_interrogator/tests
  modules/fluid_properties/test/tests/two_phase_ncg_partial_pressure/gold/test_out.csv
  modules/fluid_properties/test/tests/two_phase_ncg_partial_pressure/test.i
  modules/fluid_properties/test/tests/two_phase_ncg_partial_pressure/tests
Labels: PR: Failed but allowed

#28428 multiple experiments and wave inversion example
  modules/combined/test/tests/optimization/invOpt_multiExperiment/sampler_subapp.i
  modules/optimization/doc/content/source/reporters/ParsedVectorRealReductionReporter.md
  modules/optimization/doc/content/source/reporters/ParsedVectorVectorRealReductionReporter.md
  modules/optimization/examples/materialFrequency/wave1D/gold/inversion_out_OptimizationReporter_0001.csv
  modules/optimization/examples/materialFrequency/wave1D/inversion.i
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ui_1.csv
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ui_2.csv
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ui_3.csv
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ui_4.csv
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ur_1.csv
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ur_2.csv
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ur_3.csv
  modules/optimization/examples/materialFrequency/wave1D/measurement/frequency_ur_4.csv
  modules/optimization/examples/materialFrequency/wave1D/model_grad.i
  modules/optimization/examples/materialFrequency/wave1D/sampler.i
  modules/optimization/examples/materialFrequency/wave1D/tests
  modules/optimization/test/tests/executioners/steady_and_adjoint/tests
  modules/optimization/test/tests/executioners/transient_and_adjoint/tests
  modules/optimization/test/tests/optimizationreporter/nonlinear_material/tests
  modules/optimization/test/tests/reporters/multiExperiment/forward.i
  modules/optimization/test/tests/reporters/multiExperiment/gold/optimize_out.csv
  modules/optimization/test/tests/reporters/multiExperiment/optimize.i
  modules/optimization/test/tests/reporters/multiExperiment/sampler_subapp.i
  modules/optimization/test/tests/reporters/multiExperiment/tests
Labels: PR: Failed but allowed

#28442 Make --copy-inputs quiet, show summary, enable retries
  apptainer/app.def
  framework/src/base/MooseApp.C
Labels: PR: Ready for review/merge

#28327 shell lint, better printf, colors
  scripts/diagnostics.sh
  scripts/functions/diagnostic_application.sh
  scripts/functions/diagnostic_conda.sh
  scripts/functions/diagnostic_environment.sh
  scripts/functions/diagnostic_tests.sh
  scripts/functions/help_system
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28468 Formatted how wall time checkpoint interval is displayed in console output
  framework/src/outputs/Checkpoint.C
  test/tests/outputs/checkpoint/tests
Labels: PR: Failed but allowed

#28478 Skip tests requiring requests
  test/tests/controls/web_server_control/tests
Labels: PR: Failed but allowed

#28438 Fixed Peacock setup doc and added doc for THM plugins
  framework/doc/content/templates/sqa/app_sll.md.template
  modules/doc/content/application_usage/input_syntax.md
  modules/doc/content/getting_started/installation/optional_python_and_peacock.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/utilities.md
  modules/thermal_hydraulics/doc/content/source/components/HSCoupler2D3D.md
  python/doc/content/python/MooseDocs/extensions/bibtex.md
  python/doc/content/python/peacock.md
Labels: PR: Failed but allowed
