Repository idaholab/moose, pull requests merged in 2024-05, with the labels that each got.

#27541 Avoid Subgenerator Name Confliting When Using Multiple FlexPatternG
  modules/reactor/src/meshgenerators/FlexiblePatternGenerator.C
Labels: PR: Failed but allowed

#27055 Xfem crack nucleation in bulk
  modules/solid_mechanics/doc/content/source/actions/DomainIntegralAction.md
  modules/solid_mechanics/src/actions/DomainIntegralAction.C
  modules/xfem/doc/content/source/userobjects/MeshCut2DRankTwoTensorNucleation.md
  modules/xfem/include/userobjects/MeshCut2DRankTwoTensorNucleation.h
  modules/xfem/src/userobjects/MeshCut2DNucleationBase.C
  modules/xfem/src/userobjects/MeshCut2DRankTwoTensorNucleation.C
  modules/xfem/src/userobjects/MeshCut2DUserObjectBase.C
  modules/xfem/test/tests/nucleation_uo/gold/nucleate_AllEdgeCracks_out_II_KI_1_0003.csv
  modules/xfem/test/tests/nucleation_uo/gold/nucleate_AllEdgeCracks_out_II_KI_1_0005.csv
  modules/xfem/test/tests/nucleation_uo/gold/nucleate_bulkCrack_out_II_KI_1_0006.csv
  modules/xfem/test/tests/nucleation_uo/gold/nucleate_edge_bulk_crack_2d_out_II_KI_1_0011.csv
  modules/xfem/test/tests/nucleation_uo/gold/nucleate_edge_crack_2d_out_II_KI_1_0004.csv
  modules/xfem/test/tests/nucleation_uo/nucleate_2edge_cracks_2d.i
  modules/xfem/test/tests/nucleation_uo/nucleate_AllEdgeCracks.i
  modules/xfem/test/tests/nucleation_uo/nucleate_bulkCrack.i
  modules/xfem/test/tests/nucleation_uo/nucleate_edge_bulk_crack_2d.i
  modules/xfem/test/tests/nucleation_uo/tests
Labels: PR: Failed but allowed

#27539 Delete heat conduction module folder
  modules/heat_conduction/Makefile
  modules/heat_conduction/doc
  modules/heat_conduction/include
  modules/heat_conduction/src
Labels: PR: Failed but allowed

#27257 Delete INSFVMomentumFriction and combine with the PINSFVMomentumFriction
  modules/navier_stokes/doc/content/source/functormaterials/INSFVMushyPorousFrictionFunctorMaterial.md
  modules/navier_stokes/doc/content/source/fvkernels/INSFVMomentumFriction.md
  modules/navier_stokes/doc/content/source/fvkernels/PINSFVMomentumFriction.md
  modules/navier_stokes/examples/solidification/galium_melting.i
  modules/navier_stokes/include/base/NSFVBase.h
  modules/navier_stokes/include/fvkernels/INSFVMomentumFriction.h
  modules/navier_stokes/include/fvkernels/PINSFVMomentumFriction.h
  modules/navier_stokes/src/fvkernels/INSFVMomentumFriction.C
  modules/navier_stokes/src/fvkernels/PINSFVMomentumFriction.C
  modules/navier_stokes/src/physics/WCNSFVFlowPhysics.C
  modules/navier_stokes/test/tests/finite_volume/ins/action/errors/2d-rc-error-action.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/discontinuous-body-forces.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/2d-rc-friction-action.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/2d-rc-friction.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/gold/2d-rc-friction-exp-factor-action_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/gold/2d-rc-friction-exp-factor_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/gold/2d-rc-friction-quad_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/friction/tests
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/segregated/2d/2d-segregated-velocity-rz-slip.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/segregated/2d/tests
  modules/navier_stokes/test/tests/finite_volume/ins/natural_convection/natural_circulation_dogleg.i
  modules/navier_stokes/test/tests/finite_volume/ins/solidification/pipe_solidification.i
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/friction.i
  modules/navier_stokes/test/tests/finite_volume/materials/flow_diode/transient_operation.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/2d-rc-friction-action.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/linear_friction.i
  modules/navier_stokes/test/tests/finite_volume/wcns/natural_convection/natural_circulation_pipe.i
Labels: PR: Failed but allowed

#27487 Add ModifyElementSubdomainByVar UserObject
  framework/doc/content/source/userobjects/VariableValueElementSubdomainModifier.md
  framework/include/userobjects/VariableValueElementSubdomainModifier.h
  framework/src/userobjects/VariableValueElementSubdomainModifier.C
  test/tests/userobjects/element_subdomain_modifier/gold/var_block_id_out.e-s002
  test/tests/userobjects/element_subdomain_modifier/gold/var_block_id_out.e-s005
  test/tests/userobjects/element_subdomain_modifier/gold/var_block_id_warning.e-s002
  test/tests/userobjects/element_subdomain_modifier/tests
  test/tests/userobjects/element_subdomain_modifier/var_block_id.i
Labels: PR: Failed but allowed

#27372 Misc solid mechanics doco
  modules/solid_mechanics/doc/content/source/actions/CohesiveZoneAction.md
  modules/solid_mechanics/doc/content/source/actions/CommonCohesiveZoneAction.md
  modules/solid_mechanics/doc/content/source/actions/PoroMechanicsAction.md
  modules/solid_mechanics/doc/content/source/auxkernels/AccumulateAux.md
  modules/solid_mechanics/doc/content/source/auxkernels/ElasticEnergyAux.md
  modules/solid_mechanics/doc/content/source/bcs/DashpotBC.md
  modules/solid_mechanics/doc/content/source/bcs/PresetVelocity.md
  modules/solid_mechanics/doc/content/source/constraints/NodalFrictionalConstraint.md
  modules/solid_mechanics/doc/content/source/constraints/NodalStickConstraint.md
  modules/solid_mechanics/doc/content/source/kernels/ADInertialForceShell.md
  modules/solid_mechanics/doc/content/source/kernels/CosseratStressDivergenceTensors.md
  modules/solid_mechanics/doc/content/source/kernels/MomentBalancing.md
  modules/solid_mechanics/doc/content/source/kernels/PhaseFieldFractureMechanicsOffDiag.md
  modules/solid_mechanics/doc/content/source/kernels/PlasticHeatEnergy.md
  modules/solid_mechanics/doc/content/source/kernels/PoroMechanicsCoupling.md
  modules/solid_mechanics/doc/content/source/postprocessors/Mass.md
  modules/solid_mechanics/doc/theory/cosserat.tex
  modules/solid_mechanics/src/actions/PoroMechanicsAction.C
  modules/solid_mechanics/src/constraints/NodalFrictionalConstraint.C
  modules/solid_mechanics/src/kernels/CosseratStressDivergenceTensors.C
  modules/solid_mechanics/src/postprocessors/Mass.C
Labels: PR: Ready for review/merge

#27421 Add source documentation to some materials in solid mechanics module
  modules/solid_mechanics/doc/content/source/materials/ComputeConcentrationDependentElasticityTensor.md
  modules/solid_mechanics/doc/content/source/materials/ComputeCosseratElasticityTensor.md
  modules/solid_mechanics/doc/content/source/materials/ComputeCosseratIncrementalSmallStrain.md
  modules/solid_mechanics/doc/content/source/materials/ComputeCosseratLinearElasticStress.md
  modules/solid_mechanics/doc/content/source/materials/ComputeCosseratSmallStrain.md
  modules/solid_mechanics/doc/content/source/materials/ComputeLayeredCosseratElasticityTensor.md
  modules/solid_mechanics/doc/content/source/materials/ComputeMultipleInelasticCosseratStress.md
  modules/solid_mechanics/doc/content/source/materials/ComputePlasticHeatEnergy.md
  modules/solid_mechanics/doc/content/source/materials/FluxBasedStrainIncrement.md
  modules/solid_mechanics/doc/content/source/materials/GBRelaxationStrainIncrement.md
  modules/solid_mechanics/doc/content/source/materials/MultiPhaseStressMaterial.md
  modules/solid_mechanics/doc/content/source/materials/StressBasedChemicalPotential.md
  modules/solid_mechanics/doc/content/source/materials/TwoPhaseStressMaterial.md
  modules/solid_mechanics/src/materials/CappedWeakPlaneStressUpdate.C
  modules/solid_mechanics/src/materials/ComputeLayeredCosseratElasticityTensor.C
  modules/solid_mechanics/src/materials/ComputeMultipleInelasticCosseratStress.C
  modules/solid_mechanics/src/materials/GBRelaxationStrainIncrement.C
  modules/solid_mechanics/src/materials/MultiPhaseStressMaterial.C
Labels: PR: Ready for review/merge

#27565 Add templates to help with Discussions
  .github/DISCUSSION_TEMPLATE/q-a-general.yml
  .github/DISCUSSION_TEMPLATE/q-a-getting-started.yml
  .github/DISCUSSION_TEMPLATE/q-a-navier-stokes.yml
Labels: PR: Failed but allowed

#27570 Fix scaling of pressure mass matrix for preconditioning
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_vector_fsp_al.i
Labels: PR: Failed but allowed

#27579 Disallow addDeprecatedParam and deprecateParam on same param
  framework/include/utils/InputParameters.h
  framework/src/actions/CommonOutputAction.C
  framework/src/executioners/FEProblemSolve.C
  framework/src/executioners/PicardSolve.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/SideSetsFromBoundingBoxGenerator.C
  framework/src/meshgenerators/SideSetsFromNormalsGenerator.C
  framework/src/meshgenerators/SideSetsGeneratorBase.C
  framework/src/outputs/Output.C
  framework/src/transfers/MultiAppProjectionTransfer.C
  framework/src/utils/InputParameters.C
Labels: C: Framework, PR: Failed but allowed

#26520 WIP EIL conference information
  modules/doc/content/index.md
  modules/doc/content/training/index.md
Labels: C: Documentation

#27588 Adding link to form submission
  modules/doc/content/index.md
Labels: PR: Ready for review/merge

#27595 Fix Navier stokes q&a template
  .github/DISCUSSION_TEMPLATE/q-a-modules-navier-stokes.yml
Labels: PR: Failed but allowed

#27568 Initialize constant postprocessor value in constructor
  framework/include/reporters/ReporterData.h
  framework/src/postprocessors/ConstantPostprocessor.C
Labels: C: Framework, PR: Failed but allowed

#27603 Supress PETSc's unused options warning when not solving
  framework/src/problems/FEProblemBase.C
  test/tests/problems/no_solve/tests
Labels: PR: Failed but allowed

#27638 Register objects from FET module
  modules/module_loader/include/ModulesApp.h
  modules/module_loader/src/ModulesApp.C
Labels: PR: Failed but allowed

#26456 Add sideset updater
  framework/doc/content/source/userobjects/SidesetAroundSubdomainUpdater.md
  framework/include/loops/ComputeUserObjectsThread.h
  framework/include/loops/ThreadedElementLoopBase.h
  framework/include/userobjects/DomainUserObject.h
  framework/include/userobjects/SidesetAroundSubdomainUpdater.h
  framework/include/utils/MooseTypes.h
  framework/src/loops/ComputeUserObjectsThread.C
  framework/src/userobjects/SidesetAroundSubdomainUpdater.C
  test/tests/userobjects/sideset_around_subdomain_updater/gold/no_surface.e-s006
  test/tests/userobjects/sideset_around_subdomain_updater/gold/surface.e-s006
  test/tests/userobjects/sideset_around_subdomain_updater/test.i
  test/tests/userobjects/sideset_around_subdomain_updater/tests
Labels: PR: Failed but allowed

#27667 Simplify tests, correct prereqs, use same input
  test/tests/problems/eigen_problem/initial_condition/ne_ic.i
  test/tests/problems/eigen_problem/initial_condition/ne_restart.i
  test/tests/problems/eigen_problem/initial_condition/tests
Labels: PR: Failed but allowed

#27662 Add quad8 extrusion, fixed mixed order extrusion
  framework/src/meshgenerators/AdvancedExtruderGenerator.C
  test/tests/meshgenerators/advanced_extruder_generator/gold/elem_flip_second.e
  test/tests/meshgenerators/advanced_extruder_generator/tests
Labels: PR: Ready for review/merge

#26606 Add stationary ray output
  modules/ray_tracing/include/outputs/RayTracingMeshOutput.h
  modules/ray_tracing/include/raytracing/Ray.h
  modules/ray_tracing/include/raytracing/TraceData.h
  modules/ray_tracing/src/outputs/RayTracingMeshOutput.C
  modules/ray_tracing/src/raytracing/Ray.C
  modules/ray_tracing/src/raytracing/TraceRay.C
  modules/ray_tracing/test/include/userobjects/StationaryRayStudyTest.h
  modules/ray_tracing/test/src/userobjects/StationaryRayStudyTest.C
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/stationary_rays.e
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/stationary_rays.e-s0001
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/gold/stationary_rays.e-s0002
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/stationary.i
  modules/ray_tracing/test/tests/outputs/ray_tracing_mesh_output/tests
Labels: PR: Failed but allowed

#27682 Making `generateUniqueRayID` virtual so custom implementations can be added
  modules/ray_tracing/include/userobjects/RayTracingStudy.h
Labels: PR: Failed but allowed

#27679 Use the inexact LU with compression from strumpack
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_vector_fsp_al.i
Labels: PR: Failed but allowed

#27681 Add ! character to hit as it is used now in input file includes
  framework/contrib/hit/src/hit/lex.cc
Labels: PR: Failed but allowed, PR: Ready for review/merge

#27323 Eigen fixes
  framework/src/systems/NonlinearEigenSystem.C
  test/tests/problems/eigen_problem/eigensolvers/dg_krylovschur.i
  test/tests/problems/eigen_problem/eigensolvers/tests
Labels: PR: Failed but allowed

#27327 Add Modal beam example
  modules/solid_mechanics/doc/content/modules/solid_mechanics/1d_elastic_waves.md
  modules/solid_mechanics/test/tests/modal_analysis/gold/modal_out.e
  modules/solid_mechanics/test/tests/modal_analysis/modal.i
  modules/solid_mechanics/test/tests/modal_analysis/tests
Labels: PR: Failed but allowed

#27697 Make sure two maps connecting lower-d and higher-d elements are built in recovery mode
  framework/src/mesh/MooseMesh.C
  test/src/userobjects/LowerDIntegralSideUserObject.C
  test/tests/userobjects/side_uo_with_lowerd_use/side-uo-with-lower-d-use.i
Labels: PR: Failed but allowed

#27685 Added radiation coupling component between multiple 2D heat structures
  modules/doc/content/newsletter/2024/2024_05.md
  modules/heat_transfer/doc/content/modules/heat_transfer/index.md
  modules/thermal_hydraulics/doc/content/source/bcs/HSCoupler2D2DRadiationRZBC.md
  modules/thermal_hydraulics/doc/content/source/components/HSCoupler2D2DRadiation.md
  modules/thermal_hydraulics/doc/content/source/userobjects/HSCoupler2D2DRadiationUserObject.md
  modules/thermal_hydraulics/doc/content/source/utils/MeshAlignment2D2D.md
  modules/thermal_hydraulics/include/bcs/HSCoupler2D2DRadiationRZBC.h
  modules/thermal_hydraulics/include/components/HSCoupler2D2DRadiation.h
  modules/thermal_hydraulics/include/userobjects/HSCoupler2D2DRadiationUserObject.h
  modules/thermal_hydraulics/include/utils/MeshAlignment1D3D.h
  modules/thermal_hydraulics/include/utils/MeshAlignment2D2D.h
  modules/thermal_hydraulics/include/utils/MeshAlignment2D3D.h
  modules/thermal_hydraulics/include/utils/MeshAlignmentOneToMany.h
  modules/thermal_hydraulics/src/bcs/HSCoupler2D2DRadiationRZBC.C
  modules/thermal_hydraulics/src/components/HSCoupler2D2DRadiation.C
  modules/thermal_hydraulics/src/userobjects/HSCoupler2D2DRadiationUserObject.C
  modules/thermal_hydraulics/src/utils/MeshAlignment1D3D.C
  modules/thermal_hydraulics/src/utils/MeshAlignment2D2D.C
  modules/thermal_hydraulics/src/utils/MeshAlignment2D3D.C
  modules/thermal_hydraulics/src/utils/MeshAlignmentOneToMany.C
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d2d_radiation/adjacent_cylinders.i
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d2d_radiation/concentric_cylinders.i
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d2d_radiation/energy_conservation.i
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d2d_radiation/gold/adjacent_cylinders.e
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d2d_radiation/gold/concentric_cylinders.csv
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d2d_radiation/gold/energy_conservation.csv
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d2d_radiation/tests
Labels: PR: Failed but allowed

#27546 Enable Quadratic Elems in XYDelaunay and Related MGs
  framework/doc/content/source/meshgenerators/ElementOrderConversionGenerator.md
  framework/include/meshgenerators/ElementOrderConversionGenerator.h
  framework/include/meshgenerators/XYDelaunayGenerator.h
  framework/src/meshgenerators/ElementOrderConversionGenerator.C
  framework/src/meshgenerators/XYDelaunayGenerator.C
  modules/reactor/src/meshgenerators/FlexiblePatternGenerator.C
  modules/reactor/src/meshgenerators/PeripheralTriangleMeshGenerator.C
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/gold/quadratic_elems_in.e
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/quadratic_elems.i
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/tests
  test/tests/meshgenerators/elem_order_conversion_generator/gold/complete_order.e
  test/tests/meshgenerators/elem_order_conversion_generator/gold/firsrt_order.e
  test/tests/meshgenerators/elem_order_conversion_generator/gold/full_second_order.e
  test/tests/meshgenerators/elem_order_conversion_generator/gold/nonfull_second_order.e
  test/tests/meshgenerators/elem_order_conversion_generator/order_conversion.i
  test/tests/meshgenerators/elem_order_conversion_generator/tests
  test/tests/meshgenerators/xy_delaunay_generator/accg_one_layer_quadratic.e
  test/tests/meshgenerators/xy_delaunay_generator/gold/xydelaunay_quadratic_hole_tri3.e
  test/tests/meshgenerators/xy_delaunay_generator/gold/xydelaunay_quadratic_tri6.e
  test/tests/meshgenerators/xy_delaunay_generator/gold/xydelaunay_quadratic_tri7.e
  test/tests/meshgenerators/xy_delaunay_generator/gold/xydelaunay_stitching_tri6.e
  test/tests/meshgenerators/xy_delaunay_generator/gold/xydelaunay_stitching_tri7.e
  test/tests/meshgenerators/xy_delaunay_generator/tests
  test/tests/meshgenerators/xy_delaunay_generator/xydelaunay_quadratic.i
Labels: PR: Failed but allowed

#27647 Add no-merge capability to mesh combiner generator
  framework/include/meshgenerators/CombinerGenerator.h
  framework/src/meshgenerators/CombinerGenerator.C
  test/tests/meshgenerators/combiner_generator/gold/no_merge_blocks.e
  test/tests/meshgenerators/combiner_generator/gold/no_merge_boundaries.e
  test/tests/meshgenerators/combiner_generator/tests
Labels: PR: Ready for review/merge

#26870 General sensor postprocessor
  modules/misc/doc/content/source/postprocessors/GeneralSensorPostprocessor.md
  modules/misc/doc/content/source/postprocessors/ThermocoupleSensorPostprocessor.md
  modules/misc/include/postprocessors/GeneralSensorPostprocessor.h
  modules/misc/include/postprocessors/ThermocoupleSensorPostprocessor.h
  modules/misc/src/postprocessors/GeneralSensorPostprocessor.C
  modules/misc/src/postprocessors/ThermocoupleSensorPostprocessor.C
  modules/misc/test/tests/sensor_postprocessor/gold/steady_general_sensor_out.csv
  modules/misc/test/tests/sensor_postprocessor/gold/steady_thermocouple_sensor_out.csv
  modules/misc/test/tests/sensor_postprocessor/gold/transient_general_sensor_out.csv
  modules/misc/test/tests/sensor_postprocessor/gold/transient_thermocouple_sensor_out.csv
  modules/misc/test/tests/sensor_postprocessor/steady_general_sensor.i
  modules/misc/test/tests/sensor_postprocessor/steady_thermocouple_sensor.i
  modules/misc/test/tests/sensor_postprocessor/tests
  modules/misc/test/tests/sensor_postprocessor/transient_general_sensor.i
  modules/misc/test/tests/sensor_postprocessor/transient_thermocouple_sensor.i
Labels: PR: Failed but allowed

#27720 correcting wall functions for k epsilon
  modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C
  modules/navier_stokes/src/fvbcs/INSFVTurbulentViscosityWallFunction.C
Labels: PR: Failed but allowed

#27755 Added Physics interfaces for adding multiapps and transfers
  framework/include/physics/PhysicsBase.h
  framework/src/physics/PhysicsBase.C
Labels: PR: Failed but allowed

#27747 Initialize _delay_value
  modules/misc/src/postprocessors/GeneralSensorPostprocessor.C
Labels: PR: Failed but allowed
