Repository idaholab/moose, pull requests merged in 2024-09, with the labels that each got.

#28491 Wait for the process to be killed
  python/MooseControl/MooseControl.py
Labels: PR: Failed but allowed

#28557 Correct class description in PorousFlow1PhaseP
  modules/porous_flow/src/materials/PorousFlow1PhaseP.C
Labels: PR: Failed but allowed

#28559 Finish gathering utilities in unity build
  framework/include/utils/ADRankFourTensorForward.h
  framework/include/utils/ADRankThreeTensorForward.h
  framework/include/utils/ADRankTwoTensorForward.h
  framework/include/utils/ADSymmetricRankFourTensorForward.h
  framework/include/utils/ADSymmetricRankTwoTensorForward.h
  framework/include/utils/FactorizedRankTwoTensor.h
  framework/include/utils/InputParametersChecksUtils.h
  framework/include/utils/MeshCoarseningUtils.h
  framework/include/utils/PerfGraph.h
  framework/include/utils/PerfGraphLivePrint.h
  framework/include/utils/PerfGraphRegistry.h
  framework/include/utils/PermutationTensor.h
  framework/include/utils/RankFourTensor.h
  framework/include/utils/RankFourTensorForward.h
  framework/include/utils/RankFourTensorImplementation.h
  framework/include/utils/RankThreeTensor.h
  framework/include/utils/RankThreeTensorForward.h
  framework/include/utils/RankThreeTensorImplementation.h
  framework/include/utils/RankTwoTensor.h
  framework/include/utils/RankTwoTensorForward.h
  framework/include/utils/RankTwoTensorImplementation.h
  framework/include/utils/SymmetricRankFourTensor.h
  framework/include/utils/SymmetricRankFourTensorForward.h
  framework/include/utils/SymmetricRankFourTensorImplementation.h
  framework/include/utils/SymmetricRankTwoTensor.h
  framework/include/utils/SymmetricRankTwoTensorForward.h
  framework/include/utils/SymmetricRankTwoTensorImplementation.h
  framework/include/utils/VectorTag.h
  framework/src/utils/ADUtils.C
  framework/src/utils/FactorizedRankTwoTensor.C
  framework/src/utils/PerfGraph.C
  framework/src/utils/PerfGraphLivePrint.C
  framework/src/utils/PerfGraphRegistry.C
  framework/src/utils/PermutationTensor.C
  framework/src/utils/RankFourTensor.C
  framework/src/utils/RankThreeTensor.C
  framework/src/utils/RankTwoTensor.C
  framework/src/utils/RankTwoTensorImplementation.C
  framework/src/utils/SymmetricRankFourTensor.C
  framework/src/utils/SymmetricRankTwoTensor.C
  framework/src/utils/SymmetricRankTwoTensorImplementation.C
  framework/src/utils/VectorTag.C
Labels: PR: Failed but allowed

#28518 Enabled a consistent variable ordering in THM from components
  modules/thermal_hydraulics/doc/content/syntax/Components/index.md
  modules/thermal_hydraulics/include/base/Simulation.h
  modules/thermal_hydraulics/src/base/Simulation.C
  modules/thermal_hydraulics/src/base/ThermalHydraulicsApp.C
Labels: PR: Failed but allowed

#28572 Report a module name instead if we can
  scripts/premake.py
  scripts/tests/test_premake.py
Labels: PR: Ready for review/merge

#28574 Add `Versioner` extension to `MooseDocs`
  framework/doc/packages_config.yml
  modules/doc/content/getting_started/installation/install_conda_moose.md
  modules/doc/content/getting_started/installation/true_update_conda.md
  modules/doc/content/help/faq/build_issues.md
  modules/doc/content/help/faq/conda_issues.md
  modules/doc/content/ncrc/applications/ncrc_develop.md.template
  python/MooseDocs/common/load_config.py
  python/MooseDocs/extensions/__init__.py
  python/MooseDocs/extensions/versioner.py
  python/MooseDocs/test/extensions/test_versioner.py
  python/MooseDocs/test/extensions/tests
  python/doc/content/python/MooseDocs/setup.md
  scripts/tests/versioner_hashes.yaml
  scripts/versioner.py
  scripts/versioner.yaml
Labels: PR: Ready for review/merge

#28580 Allow non-recursive checks for hasSubmodule
  framework/doc/content/templates/sqa/app_sll.md.template
  python/MooseDocs/extensions/ifelse.py
Labels: PR: Failed but allowed

#28554 Add support for NS solves to saline
  modules/fluid_properties/include/fluidproperties/SalineMoltenSaltFluidProperties.h
  modules/fluid_properties/src/fluidproperties/SalineMoltenSaltFluidProperties.C
  modules/fluid_properties/unit/src/SalineMoltenSaltFluidPropertiesTest.C
  modules/navier_stokes/src/functormaterials/RhoFromPTFunctorMaterial.C
Labels: PR: Failed but allowed

#28548 Nemesis recover
  framework/include/outputs/Nemesis.h
  framework/src/outputs/Nemesis.C
  test/tests/outputs/recover/gold/recover_nemesis_out.e.2.0
  test/tests/outputs/recover/gold/recover_nemesis_out.e.2.1
  test/tests/outputs/recover/recover_nemesis.i
  test/tests/outputs/recover/tests
Labels: PR: Failed but allowed

#28473 Modifing base vectors of shell element and added test example
  modules/solid_mechanics/doc/content/modules/solid_mechanics/ShellElements.md
  modules/solid_mechanics/src/materials/ADComputeIncrementalShellStrain.C
  modules/solid_mechanics/test/tests/shell/static/gold/pinched_cylinder_symm_unstructured_out.e
  modules/solid_mechanics/test/tests/shell/static/gold/tapered_out.e
  modules/solid_mechanics/test/tests/shell/static/pinched_cyl_10_10_unstructured.msh
  modules/solid_mechanics/test/tests/shell/static/pinched_cylinder_symm_unstructured.i
  modules/solid_mechanics/test/tests/shell/static/tests
Labels: PR: Failed but allowed

#28514 Using field variables instead of scalar variables for THM junctions, part 1
  modules/thermal_hydraulics/doc/content/source/scalarkernels/VolumeJunctionAdvectionScalarKernel.md
  modules/thermal_hydraulics/include/base/THMMesh.h
  modules/thermal_hydraulics/include/bcs/ADVolumeJunction1PhaseBC.h
  modules/thermal_hydraulics/include/components/Component.h
  modules/thermal_hydraulics/include/components/Component1DJunction.h
  modules/thermal_hydraulics/include/components/GeometricalComponent.h
  modules/thermal_hydraulics/include/scalarkernels/VolumeJunctionAdvectionScalarKernel.h
  modules/thermal_hydraulics/include/userobjects/ADVolumeJunctionBaseUserObject.h
  modules/thermal_hydraulics/include/userobjects/FlowJunctionUserObject.h
  modules/thermal_hydraulics/include/userobjects/VolumeJunctionBaseUserObject.h
  modules/thermal_hydraulics/src/base/Simulation.C
  modules/thermal_hydraulics/src/base/THMMesh.C
  modules/thermal_hydraulics/src/bcs/ADVolumeJunction1PhaseBC.C
  modules/thermal_hydraulics/src/components/Component.C
  modules/thermal_hydraulics/src/components/GateValve1Phase.C
  modules/thermal_hydraulics/src/components/GeometricalComponent.C
  modules/thermal_hydraulics/src/components/JunctionOneToOne1Phase.C
  modules/thermal_hydraulics/src/components/JunctionParallelChannels1Phase.C
  modules/thermal_hydraulics/src/components/Pump1Phase.C
  modules/thermal_hydraulics/src/components/ShaftConnectedCompressor1Phase.C
  modules/thermal_hydraulics/src/components/ShaftConnectedPump1Phase.C
  modules/thermal_hydraulics/src/components/ShaftConnectedTurbine1Phase.C
  modules/thermal_hydraulics/src/components/SimpleTurbine1Phase.C
  modules/thermal_hydraulics/src/components/VolumeJunction1Phase.C
  modules/thermal_hydraulics/src/outputs/ParaviewComponentAnnotationMap.C
  modules/thermal_hydraulics/src/scalarkernels/VolumeJunctionAdvectionScalarKernel.C
  modules/thermal_hydraulics/src/userobjects/ADVolumeJunctionBaseUserObject.C
  modules/thermal_hydraulics/src/userobjects/FlowJunctionUserObject.C
  modules/thermal_hydraulics/src/userobjects/VolumeJunctionBaseUserObject.C
  modules/thermal_hydraulics/test/doc/content/source/components/ShaftConnectedTestComponent.md
  modules/thermal_hydraulics/test/doc/content/source/userobjects/ShaftConnectedTestComponentUserObject.md
  modules/thermal_hydraulics/test/include/components/ShaftConnectedTestComponent.h
  modules/thermal_hydraulics/test/include/userobjects/ADShaftConnectedTestComponentUserObject.h
  modules/thermal_hydraulics/test/include/userobjects/ShaftConnectedTestComponentUserObject.h
  modules/thermal_hydraulics/test/src/components/ShaftConnectedTestComponent.C
  modules/thermal_hydraulics/test/src/userobjects/ADShaftConnectedTestComponentUserObject.C
  modules/thermal_hydraulics/test/src/userobjects/ShaftConnectedTestComponentUserObject.C
  modules/thermal_hydraulics/test/tests/components/shaft_connected_test_component/jacobian.i
  modules/thermal_hydraulics/test/tests/components/shaft_connected_test_component/tests
  modules/thermal_hydraulics/test/tests/jacobians/userobjects/shaft_connected_test_component/shaft_connected_test_component.i
  modules/thermal_hydraulics/test/tests/jacobians/userobjects/shaft_connected_test_component/tests
Labels: PR: Failed but allowed

#28399 Remove flags. Default Python packages moose-mpi
  apptainer/files/mpi/.singularity.d/env/01-fix-exec.sh
  apptainer/mpi.def
  conda/libmesh-vtk/conda_build_config.yaml
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/conda_build_config.yaml
  conda/libmesh/meta.yaml
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/mpi/base_build.sh
  conda/mpi/build.sh
  conda/mpi/conda_build_config.yaml
  conda/mpi/meta.yaml
  conda/peacock/conda_build_config.yaml
  conda/peacock/meta.yaml
  conda/petsc/build.sh
  conda/petsc/conda_build_config.yaml
  conda/petsc/meta.yaml
  conda/tools/meta.yaml
  scripts/tests/versioner_hashes.yaml
  scripts/versioner.yaml
Labels: PR: Failed but allowed

#28488 Add support for vectors of MultiMooseEnums
  framework/include/utils/InputParameters.h
  framework/src/parser/Builder.C
  framework/src/utils/InputParameters.C
  framework/src/utils/JsonSyntaxTree.C
  test/include/materials/VecMultiMooseEnumMaterial.h
  test/src/materials/VecMultiMooseEnumMaterial.C
  test/tests/parser/vector_multimooseenum/tests
  test/tests/parser/vector_multimooseenum/vmme.i
Labels: PR: Failed but allowed

#17048 Wrap warning in a do-once statement to avoid overload. Refs #17047
  modules/heat_transfer/src/materials/HeatConductionMaterial.C
  modules/heat_transfer/test/tests/transient_heat/tests
Labels: P: normal

#28298 XYZDelaunayMeshGenerator
  framework/doc/content/source/meshgenerators/XYDelaunayGenerator.md
  framework/doc/content/source/meshgenerators/XYZDelaunayGenerator.md
  framework/include/meshgenerators/XYZDelaunayGenerator.h
  framework/src/meshgenerators/XYDelaunayGenerator.C
  framework/src/meshgenerators/XYZDelaunayGenerator.C
  test/tests/meshgenerators/xyz_delaunay_generator/gold/xyzdelaunay_mesh_generator_out.csv
  test/tests/meshgenerators/xyz_delaunay_generator/gold/xyzdelaunay_nested_out.csv
  test/tests/meshgenerators/xyz_delaunay_generator/gold/xyzdelaunay_smoothed_out.csv
  test/tests/meshgenerators/xyz_delaunay_generator/gold/xyzdelaunay_stitching_out.csv
  test/tests/meshgenerators/xyz_delaunay_generator/gold/xyzdelaunay_with_holes_out.csv
  test/tests/meshgenerators/xyz_delaunay_generator/tests
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_mesh_generator.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_nested.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_smoothed.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_stitching.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_with_holes.i
Labels: PR: Failed but allowed

#28631 Check block restriction for lower dimensional blocks in ProjectionAux
  framework/build.mk
  framework/doc/content/source/auxkernels/ProjectionAux.md
  framework/include/auxkernels/ProjectionAux.h
  framework/src/auxkernels/ProjectionAux.C
  test/tests/auxkernels/projection_aux/2d_and_lower_d.i
  test/tests/auxkernels/projection_aux/gold/2d_and_lower_d_out.e
  test/tests/auxkernels/projection_aux/gold/2d_restrict_source.e
  test/tests/auxkernels/projection_aux/mesh/cube.e
  test/tests/auxkernels/projection_aux/tests
Labels: PR: Failed but allowed

#28620 Added specific internal energy to ThermalSolidProperties
  modules/doc/content/newsletter/2024/2024_09.md
  modules/solid_properties/doc/content/modules/solid_properties/index.md
  modules/solid_properties/doc/content/source/functormaterials/ThermalSolidPropertiesFunctorMaterial.md
  modules/solid_properties/doc/content/source/solidproperties/ThermalSolidProperties.md
  modules/solid_properties/include/base/SolidPropertiesNames.h
  modules/solid_properties/include/solidproperties/ThermalCompositeSiCProperties.h
  modules/solid_properties/include/solidproperties/ThermalGraphiteProperties.h
  modules/solid_properties/include/solidproperties/ThermalMonolithicSiCProperties.h
  modules/solid_properties/include/solidproperties/ThermalSS316Properties.h
  modules/solid_properties/include/solidproperties/ThermalSolidProperties.h
  modules/solid_properties/include/solidproperties/ThermalUCProperties.h
  modules/solid_properties/src/functormaterials/ThermalSolidPropertiesFunctorMaterial.C
  modules/solid_properties/src/solidproperties/ThermalCompositeSiCProperties.C
  modules/solid_properties/src/solidproperties/ThermalGraphiteProperties.C
  modules/solid_properties/src/solidproperties/ThermalMonolithicSiCProperties.C
  modules/solid_properties/src/solidproperties/ThermalSS316Properties.C
  modules/solid_properties/src/solidproperties/ThermalSolidProperties.C
  modules/solid_properties/src/solidproperties/ThermalUCProperties.C
  modules/solid_properties/test/include/utils/SolidPropertiesTestUtils.h
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/base.i
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/constant_density.i
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/error_no_T_ref.i
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/error_provided_T_ref.i
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/gold/constant_density.csv
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/gold/test_out.csv
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/gold/variable_density.csv
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/tests
  modules/solid_properties/test/tests/materials/thermal_solid_functor_properties/variable_density.i
  modules/solid_properties/unit/src/ThermalCompositeSiCPropertiesTest.C
  modules/solid_properties/unit/src/ThermalGraphitePropertiesTest.C
  modules/solid_properties/unit/src/ThermalMonolithicSiCPropertiesTest.C
  modules/solid_properties/unit/src/ThermalSS316PropertiesTest.C
  modules/solid_properties/unit/src/ThermalUCPropertiesTest.C
Labels: PR: Failed but allowed

#28669 Added scale parameter to HeatTransferFromHeatStructure1Phase
  modules/thermal_hydraulics/doc/content/source/components/HSBoundaryAmbientConvection.md
  modules/thermal_hydraulics/doc/content/source/components/HeatTransferFromHeatStructure1Phase.md
  modules/thermal_hydraulics/include/userobjects/ADHeatFluxFromHeatStructure3EqnUserObject.h
  modules/thermal_hydraulics/include/userobjects/FlowChannelHeatStructureCouplerUserObject.h
  modules/thermal_hydraulics/src/components/HeatTransferFromHeatStructure1Phase.C
  modules/thermal_hydraulics/src/userobjects/ADHeatFluxFromHeatStructure3EqnUserObject.C
  modules/thermal_hydraulics/src/userobjects/FlowChannelHeatStructureCouplerUserObject.C
  modules/thermal_hydraulics/test/tests/components/heat_transfer_from_heat_structure_1phase/fin_enhancement.i
  modules/thermal_hydraulics/test/tests/components/heat_transfer_from_heat_structure_1phase/gold/fin_enhancement_out.csv
  modules/thermal_hydraulics/test/tests/components/heat_transfer_from_heat_structure_1phase/tests
Labels: PR: Failed but allowed

#28684 Allow submodules to run in test/tests
  python/TestHarness/TestHarness.py
Labels: PR: Failed but allowed

#28550 Add support for excluding boundary ids from sideset generation in a number of sideset-generating MGs
  framework/include/meshgenerators/SideSetsGeneratorBase.h
  framework/src/meshgenerators/AdvancedExtruderGenerator.C
  framework/src/meshgenerators/ElementsToTetrahedronsConverter.C
  framework/src/meshgenerators/LowerDBlockFromSidesetGenerator.C
  framework/src/meshgenerators/ParsedExtraElementIDGenerator.C
  framework/src/meshgenerators/SideSetsAroundSubdomainGenerator.C
  framework/src/meshgenerators/SideSetsFromBoundingBoxGenerator.C
  framework/src/meshgenerators/SideSetsGeneratorBase.C
  framework/src/meshgenerators/UniqueExtraIDMeshGenerator.C
  framework/src/meshgenerators/XYMeshLineCutter.C
  test/tests/meshgenerators/advanced_extruder_generator/tests
  test/tests/meshgenerators/lower_d_block_generator/tests
  test/tests/meshgenerators/parsed_generate_sideset/gold/parsed_generate_sideset_boundary_excluded_in.e
  test/tests/meshgenerators/parsed_generate_sideset/parsed_generate_sideset_boundary_excluded.i
  test/tests/meshgenerators/parsed_generate_sideset/tests
  test/tests/meshgenerators/xy_mesh_line_cutter/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28692 Update MooseServer formatting to not use wrong document text
  framework/include/base/MooseServer.h
  framework/src/base/MooseServer.C
Labels: PR: Failed but allowed

#28392 Remove execute_on from function parameters
  framework/include/functions/Function.h
  framework/src/functions/Function.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28647 Convert to relative path if needed
  scripts/tests/test_versioner.py
  scripts/versioner.py
Labels: PR: Failed but allowed

#28717 Bump moose-dev
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  scripts/tests/versioner_hashes.yaml
  test/tests/outputs/format/tests
Labels: PR: Failed but allowed

#28685 Improve error message for PolygonConcentricCircleMeshGenerator #27979
  modules/reactor/src/meshgenerators/PolygonConcentricCircleMeshGeneratorBase.C
  modules/reactor/test/tests/meshgenerators/polygon_concentric_circle_mesh_generator/tests
Labels: PR: Failed but allowed

#28609 Makefile fix for external FP submodule inclusion
  framework/app.mk
  modules/combined/Makefile
  modules/fluid_properties/fluid_properties.mk
Labels: PR: Ready for review/merge

#28681 Fix block restriction of adaptivity indicators
  framework/doc/content/source/kernels/ADMatBodyForce.md
  framework/include/loops/UpdateErrorVectorsThread.h
  framework/src/loops/UpdateErrorVectorsThread.C
  framework/src/markers/IndicatorMarker.C
  test/tests/adaptivity/block_restriction/gold/test_out.e-s002
  test/tests/adaptivity/block_restriction/test.i
  test/tests/adaptivity/block_restriction/tests
Labels: PR: Ready for review/merge
