Repository idaholab/moose, pull requests merged in 2024-06, with the labels that each got.

#27775 Minor changes for MOOSE training
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/timesteppers.md
  tutorials/darcy_thermo_mech/step05_heat_conduction/problems/step5b_transient.i
Labels: PR: Failed but allowed

#27726 P1 radiation
  modules/heat_transfer/doc/content/bib/heat_transfer.bib
  modules/heat_transfer/doc/content/source/functormaterials/RadiativeP1DiffusionCoefficientMaterial.md
  modules/heat_transfer/doc/content/source/fvbcs/FVMarshakRadiativeBC.md
  modules/heat_transfer/doc/content/source/fvkernels/FVThermalRadiationSourceSink.md
  modules/heat_transfer/include/functormaterials/RadiativeP1DiffusionCoefficientMaterial.h
  modules/heat_transfer/include/fvbcs/FVMarshakRadiativeBC.h
  modules/heat_transfer/include/fvkernels/FVThermalRadiationSourceSink.h
  modules/heat_transfer/src/functormaterials/RadiativeP1DiffusionCoefficientMaterial.C
  modules/heat_transfer/src/fvbcs/FVMarshakRadiativeBC.C
  modules/heat_transfer/src/fvkernels/FVThermalRadiationSourceSink.C
  modules/heat_transfer/test/tests/functormaterials/P1_radiation/P1_radiation_material_test.i
  modules/heat_transfer/test/tests/functormaterials/P1_radiation/gold/P1_radiation_material_test_out.csv
  modules/heat_transfer/test/tests/functormaterials/P1_radiation/tests
  modules/heat_transfer/test/tests/fvbcs/fv_marshak_bc/gold/rad_istothermal_medium_1d_out.csv
  modules/heat_transfer/test/tests/fvbcs/fv_marshak_bc/gold/rad_istothermal_medium_2d_out.csv
  modules/heat_transfer/test/tests/fvbcs/fv_marshak_bc/rad_istothermal_medium_1d.i
  modules/heat_transfer/test/tests/fvbcs/fv_marshak_bc/rad_istothermal_medium_2d.i
  modules/heat_transfer/test/tests/fvbcs/fv_marshak_bc/tests
  modules/heat_transfer/test/tests/fvkernels/gold/radiation_istothermal_medium_1d_out.csv
  modules/heat_transfer/test/tests/fvkernels/radiation_istothermal_medium_1d.i
  modules/heat_transfer/test/tests/fvkernels/tests
Labels: PR: Failed but allowed

#27773 Populate _exact_z with the correct function in VectorPenaltyDirichletBC
  framework/include/bcs/VectorPenaltyDirichletBC.h
  framework/src/bcs/VectorPenaltyDirichletBC.C
  test/tests/bcs/vector_penalty_dirichlet_bc/gold/test_out.e
  test/tests/bcs/vector_penalty_dirichlet_bc/test.i
  test/tests/bcs/vector_penalty_dirichlet_bc/tests
Labels: PR: Failed but allowed

#27777 fix turbulence channel test input
  modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/channel_ERCOFTAC.i
  modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/gold/channel_ERCOFTAC_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/turbulence/channel/gold/channel_ERCOFTAC_short.e
Labels: PR: Failed but allowed

#27806 Link banner to 2025 MOOSE Conference
  modules/doc/content/index.md
  modules/doc/content/training/index.md
  modules/doc/content/training/more_detail/MOOSE_2024_06_04-06_IF.md
Labels: PR: Auto Merge

#27788 Use libmesh_CXX instead of CXX for HIT
  framework/contrib/hit/Makefile
Labels: PR: Failed but allowed

#27808 Add mulit-variable optimization example
  modules/combined/test/tests/optimization/invOpt_mechanics/forward_and_adjoint.i
  modules/combined/test/tests/optimization/invOpt_mechanics/gold/main_auto_adjoint_out_OptimizationReporter_0001.csv
  modules/combined/test/tests/optimization/invOpt_mechanics/main_auto_adjoint.i
  modules/combined/test/tests/optimization/invOpt_mechanics/tests
  modules/optimization/doc/content/modules/optimization/examples/forceInv_NeumannBC.md
Labels: PR: Failed but allowed

#27853 Added convection to HSCoupler2D3D
  modules/thermal_hydraulics/doc/content/source/components/HSCoupler2D3D.md
  modules/thermal_hydraulics/include/userobjects/HSCoupler2D3DUserObject.h
  modules/thermal_hydraulics/src/components/HSCoupler2D3D.C
  modules/thermal_hydraulics/src/userobjects/HSCoupler2D3DUserObject.C
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d3d/gold/conduction_only.e
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d3d/gold/conduction_plus_radiation.e
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d3d/gold/convection_only.e
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d3d/hs_coupler_2d3d.i
  modules/thermal_hydraulics/test/tests/components/hs_coupler_2d3d/tests
Labels: PR: Failed but allowed

#26954 scatter/gather reporter transfer
  framework/doc/content/source/transfers/MultiAppReporterTransfer.md
  framework/include/reporters/ConstantReporter.h
  framework/include/reporters/ReporterContext.h
  framework/include/reporters/ReporterData.h
  framework/include/transfers/MultiAppReporterTransfer.h
  framework/include/transfers/ReporterTransferInterface.h
  framework/src/reporters/ConstantReporter.C
  framework/src/transfers/MultiAppReporterTransfer.C
  framework/src/transfers/ReporterTransferInterface.C
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/1_to_N_sub0_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/1_to_N_sub1_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/1_to_N_sub2_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/1_to_N_sub3_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/N_to_1.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_2_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_2_out_sub0_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_2_out_sub1_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_2_out_sub2_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_2_out_sub3_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_5_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_5_out_sub0_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_5_out_sub1_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_5_out_sub2_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_5_out_sub3_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_out_sub0_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_out_sub1_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_out_sub2_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/gold/main_out_sub3_out.json
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/main.i
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/main_dist.i
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/main_rec.i
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/main_send.i
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/sub.i
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/sub_dist.i
  test/tests/transfers/multiapp_reporter_transfer/dist_vector/tests
Labels: PR: Failed but allowed

#27092 TimedSubdomainModifier
  framework/doc/content/source/userobjects/TimedElementSubdomainModifier.md
  framework/doc/content/source/userobjects/TimedSubdomainModifier.md
  framework/include/interfaces/TransientInterface.h
  framework/include/mesh/MooseMesh.h
  framework/include/userobjects/TimedElementSubdomainModifier.h
  framework/include/userobjects/TimedSubdomainModifier.h
  framework/include/utils/DelimitedFileReader.h
  framework/src/interfaces/TransientInterface.C
  framework/src/mesh/MooseMesh.C
  framework/src/userobjects/TimedElementSubdomainModifier.C
  framework/src/userobjects/TimedSubdomainModifier.C
  framework/src/utils/DelimitedFileReader.C
  test/tests/userobjects/element_subdomain_modifier/gold/tsm_csv_out.e
  test/tests/userobjects/element_subdomain_modifier/gold/tsm_direct_out.e-s006
  test/tests/userobjects/element_subdomain_modifier/tests
  test/tests/userobjects/element_subdomain_modifier/tsm.csv
  test/tests/userobjects/element_subdomain_modifier/tsm_csv.i
  test/tests/userobjects/element_subdomain_modifier/tsm_direct.i
Labels: PR: Failed but allowed

#27910 Add file socket support to `WebServerControl`
  framework/contrib/tinyhttp/include/tinyhttp/http.h
  framework/contrib/tinyhttp/src/tinyhttp/http.C
  framework/doc/content/source/controls/WebServerControl.md
  framework/include/controls/WebServerControl.h
  framework/src/controls/WebServerControl.C
  python/MooseControl/MooseControl.py
  python/MooseControl/requests_unixsocket/README.md
  python/MooseControl/requests_unixsocket/__init__.py
  python/MooseControl/requests_unixsocket/adapters.py
  test/tests/controls/web_server_control/base_controller.py
  test/tests/controls/web_server_control/control_reporter.i
  test/tests/controls/web_server_control/errors.py
  test/tests/controls/web_server_control/get_postprocessor.i
  test/tests/controls/web_server_control/tests
  test/tests/controls/web_server_control/use_port.py
  test/tests/controls/web_server_control/wait_initial.i
Labels: PR: Ready for review/merge

#27923 Add `h5py` to `moose-tools`
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/tools/meta.yaml
  framework/doc/packages_config.yml
  scripts/tests/versioner_hashes.yaml
Labels: PR: Failed but allowed, PR: Ready for review/merge

#27856 Improvements to damped nested KKS model in MOOSE
  framework/include/materials/ParsedMaterialHelper.h
  framework/include/utils/FunctionParserUtils.h
  framework/src/materials/ParsedMaterialHelper.C
  framework/src/utils/FunctionParserUtils.C
  modules/phase_field/include/materials/KKSPhaseConcentrationMultiPhaseMaterial.h
  modules/phase_field/src/kernels/NestedKKSMultiACBulkC.C
  modules/phase_field/src/kernels/NestedKKSMultiACBulkF.C
  modules/phase_field/src/kernels/NestedKKSMultiSplitCHCRes.C
  modules/phase_field/src/kernels/NestedKKSSplitCHCRes.C
  modules/phase_field/src/materials/KKSPhaseConcentrationMultiPhaseMaterial.C
Labels: PR: Failed but allowed

#27943 TimedSubdomainModifier fails for multiple idential times (closes #27942)
  framework/include/userobjects/TimedElementSubdomainModifier.h
  framework/include/userobjects/TimedSubdomainModifier.h
  framework/src/userobjects/TimedElementSubdomainModifier.C
  framework/src/userobjects/TimedSubdomainModifier.C
  test/tests/userobjects/element_subdomain_modifier/gold/tsm_direct_out.e-s004
  test/tests/userobjects/element_subdomain_modifier/gold/tsm_direct_out.e-s006
  test/tests/userobjects/element_subdomain_modifier/tests
  test/tests/userobjects/element_subdomain_modifier/tsm_direct.i
Labels: PR: Failed but allowed

#27748 Fixed some typos in workshop slides.
  modules/doc/content/getting_started/examples_and_tutorials/tutorial01_app_development/problem_statement.md
  test/tests/outputs/checkpoint/checkpoint_interval.i
  tutorials/darcy_thermo_mech/doc/content/workshop/infrastructure/restart.md
  tutorials/darcy_thermo_mech/doc/content/workshop/infrastructure/testing.md
  tutorials/darcy_thermo_mech/doc/content/workshop/numerical/fem_solve.md
  tutorials/darcy_thermo_mech/doc/content/workshop/numerical/fvm_overview.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/overview.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step05.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step06.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/summary.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/actions.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/auxkernels.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/materials.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/outputs.md
  tutorials/darcy_thermo_mech/step03_darcy_material/include/kernels/DarcyPressure.h
  tutorials/darcy_thermo_mech/step11_action/src/actions/SetupDarcySimulation.C
  tutorials/darcy_thermo_mech/step11_action/src/base/DarcyThermoMechApp.C
Labels: PR: Failed but allowed

#27966 Store NEML2 stateful data in MOOSE-managed material properties
  modules/solid_mechanics/include/neml2/materials/NEML2ToMOOSEMaterialProperty.h
  modules/solid_mechanics/include/neml2/userobjects/ExecuteNEML2Model.h
  modules/solid_mechanics/include/neml2/userobjects/MOOSEMaterialPropertyToNEML2.h
  modules/solid_mechanics/include/neml2/userobjects/MOOSEToNEML2.h
  modules/solid_mechanics/include/neml2/userobjects/MOOSEVariableToNEML2.h
  modules/solid_mechanics/include/neml2/utils/NEML2Utils.h
  modules/solid_mechanics/src/neml2/materials/NEML2ToMOOSEMaterialProperty.C
  modules/solid_mechanics/src/neml2/userobjects/ExecuteNEML2Model.C
  modules/solid_mechanics/src/neml2/userobjects/MOOSEMaterialPropertyToNEML2.C
  modules/solid_mechanics/src/neml2/userobjects/MOOSEToNEML2.C
  modules/solid_mechanics/src/neml2/userobjects/MOOSEVariableToNEML2.C
  modules/solid_mechanics/src/neml2/utils/NEML2Utils.C
  modules/solid_mechanics/test/tests/neml2/fem_modular.i
  modules/solid_mechanics/test/tests/neml2/tests
Labels: PR: Failed but allowed

#27981 Execute porosity smoothing on `EXEC_INITIAL`
  modules/navier_stokes/include/userobjects/INSFVRhieChowInterpolator.h
  modules/navier_stokes/include/userobjects/PINSFVRhieChowInterpolator.h
  modules/navier_stokes/src/userobjects/PINSFVRhieChowInterpolator.C
  modules/navier_stokes/test/tests/finite_volume/pins/mms/porosity_change/pressure-interpolation-corrected-action.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/channel-drift-flux.i
Labels: PR: Failed but allowed

#27982 Minor fixups to allow matching gFHR results between regular & physics syntax
  modules/heat_transfer/src/physics/HeatConductionCG.C
  modules/heat_transfer/src/physics/HeatConductionFV.C
  modules/heat_transfer/src/physics/HeatConductionPhysics.C
  modules/heat_transfer/test/tests/physics/test_cg.i
  modules/heat_transfer/test/tests/physics/test_fv.i
  modules/navier_stokes/src/physics/PNSFVSolidHeatTransferPhysics.C
  modules/navier_stokes/src/physics/WCNSFVFluidHeatTransferPhysics.C
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/heated/2d-rc-heated-physics.i
  modules/navier_stokes/test/tests/finite_volume/pins/physics/heated_porous_medium.i
  modules/navier_stokes/test/tests/finite_volume/pwcns/channel-flow/2d-transient-physics.i
Labels: PR: Failed but allowed

#27967 Finish INSFE doco
  modules/navier_stokes/doc/content/source/kernels/INSFEFluidEnergyKernel.md
  modules/navier_stokes/doc/content/source/kernels/INSFEFluidMassKernel.md
  modules/navier_stokes/doc/content/source/kernels/INSFEFluidMomentumKernel.md
  modules/navier_stokes/doc/content/source/kernels/PINSFEFluidPressureTimeDerivative.md
  modules/navier_stokes/doc/content/source/kernels/PINSFEFluidTemperatureTimeDerivative.md
  modules/navier_stokes/doc/content/source/kernels/PINSFEFluidVelocityTimeDerivative.md
  modules/navier_stokes/doc/content/source/materials/INSFEMaterial.md
  modules/navier_stokes/doc/content/source/materials/PINSFEMaterial.md
  modules/navier_stokes/src/kernels/PINSFEFluidTemperatureTimeDerivative.C
  modules/navier_stokes/src/kernels/PINSFEFluidVelocityTimeDerivative.C
Labels: PR: Failed but allowed

#27987 Use non-shell elements in FV test input file
  modules/navier_stokes/test/tests/postprocessors/flow_rates/expansion_quad.e
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/diverging_INSFE.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insad.csv
  modules/navier_stokes/test/tests/postprocessors/pressure_drop/gold/diverging_insad_weighted.csv
Labels: PR: Failed but allowed

#27958 Alter discussions template
  .github/DISCUSSION_TEMPLATE/q-a-getting-started.yml
Labels: PR: Failed but allowed

#27998 Fix typo in tests
  test/tests/outputs/format/test_json.py
Labels: PR: Failed but allowed

#28003 Add support for FV variables for projection aux
  framework/include/auxkernels/ProjectionAux.h
  framework/src/auxkernels/ProjectionAux.C
  test/tests/auxkernels/projection_aux/tests
Labels: PR: Failed but allowed

#27996 Make ConsoleStream/GeneralRegistry thread-safe
  framework/include/interfaces/SolutionInvalidInterface.h
  framework/include/outputs/ConsoleStream.h
  framework/include/utils/GeneralRegistry.h
  framework/src/interfaces/SolutionInvalidInterface.C
  framework/src/outputs/ConsoleStream.C
  framework/src/utils_nonunity/PerfGraphRegistry.C
Labels: PR: Failed but allowed

#27959 Adding functor input capability to ParsedAux
  framework/doc/content/source/auxkernels/ParsedAux.md
  framework/include/auxkernels/ParsedAux.h
  framework/src/auxkernels/ParsedAux.C
  test/tests/auxkernels/parsed_aux/gold/parsed_aux_functors_test_out.e
  test/tests/auxkernels/parsed_aux/parsed_aux_functors_test.i
  test/tests/auxkernels/parsed_aux/tests
Labels: PR: Failed but allowed
