Repository idaholab/moose, pull requests merged in 2024-07, with the labels that each got.

#27933 Add a default to skip missing external modules during doco build
  python/MooseDocs/common/get_content.py
  python/MooseDocs/test/extensions/test_content.py
Labels: PR: Failed but allowed

#28009 Make June 2024 news public
  modules/doc/content/newsletter/2024/2024_06.md
  modules/doc/content/newsletter/2024/2024_07.md
  modules/doc/content/newsletter/index.md
Labels: PR: Ready for review/merge

#28088 Properly use --to-project-suffix in push action
  scripts/apptainer_generator.py
Labels: PR: Ready for review/merge

#28098 Add int and vector<int> support to WebServerControl
  framework/src/controls/WebServerControl.C
  python/MooseControl/MooseControl.py
  test/src/reporters/WebServerControlTestReporter.C
  test/tests/controls/web_server_control/control_reporter.py
  test/tests/controls/web_server_control/gold/control_reporter_int.json
  test/tests/controls/web_server_control/gold/control_reporter_vec_int.json
  test/tests/controls/web_server_control/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28102 Expose installed binaries in application containers
  apptainer/app.def
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28041 improved error messages for invalid subdomain names in QuasiStaticSolidMechanicsPhysics
  modules/solid_mechanics/src/physics/QuasiStaticSolidMechanicsPhysics.C
Labels: PR: Failed but allowed

#28070 allow block-restriction for the PorousFlow actions #28030
  modules/porous_flow/include/actions/PorousFlowActionBase.h
  modules/porous_flow/src/actions/PorousFlowActionBase.C
  modules/porous_flow/src/actions/PorousFlowBasicTHM.C
  modules/porous_flow/src/actions/PorousFlowFullySaturated.C
  modules/porous_flow/src/actions/PorousFlowSinglePhaseBase.C
  modules/porous_flow/src/actions/PorousFlowUnsaturated.C
  modules/porous_flow/test/tests/actions/block_restricted.i
  modules/porous_flow/test/tests/actions/gold/block_restricted_out.e
  modules/porous_flow/test/tests/actions/tests
Labels: PR: Failed but allowed

#28084 Assign correct boundary names in TransfiniteMG.
  framework/src/meshgenerators/TransfiniteMeshGenerator.C
  test/tests/meshgenerators/transfinite_generator/gold/annular_transf_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/arccircle_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/arccircle_midpoint_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/discrete_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/parsed_annular_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/parsed_biased_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/parsed_generator_in.e
  test/tests/meshgenerators/transfinite_generator/gold/quadrilater_generator_in.e
  test/tests/meshgenerators/transfinite_generator/tests
Labels: PR: Failed but allowed

#27236 Add capability to compute creep with anisotropic elasticity
  modules/solid_mechanics/doc/content/source/materials/HillCreepStressUpdate.md
  modules/solid_mechanics/include/materials/HillCreepStressUpdate.h
  modules/solid_mechanics/include/utils/ElasticityTensorTools.h
  modules/solid_mechanics/src/materials/HillCreepStressUpdate.C
  modules/solid_mechanics/src/utils/ElasticityTensorTools.C
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_x_3d_anisoElasticity.i
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_x_3d_shear.i
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_xy_3d_anisoElasticity.i
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/ad_aniso_creep_xy_3d_shear.i
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/anis_mech_hill_tensor_creep_small_tiny_step_ts_limit_test.i
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/gold/ad_aniso_creep_x_3d_anisoElasticity_out.csv
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/gold/ad_aniso_creep_x_3d_shear_out.csv
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/gold/ad_aniso_creep_xy_3d_anisoElasticity_out.csv
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/gold/ad_aniso_creep_xy_3d_shear_out.csv
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/gold/anis_mech_hill_tensor_creep_small_tiny_step_ts_limit_test_out.e
  modules/solid_mechanics/test/tests/ad_anisotropic_creep/tests
Labels: PR: Failed but allowed

#28150 Added test to show subapp checkpoint issue is resolved.
  test/tests/outputs/checkpoint/checkpoint_child_ss.i
  test/tests/outputs/checkpoint/checkpoint_parent_ss.i
  test/tests/outputs/checkpoint/tests
Labels: PR: Failed but allowed

#27445 Adding interface area to two phase
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/source/fvkernels/WCNSFV2PInterfaceAreaSourceSink.md
  modules/navier_stokes/include/fvkernels/WCNSFV2PInterfaceAreaSourceSink.h
  modules/navier_stokes/src/fvkernels/WCNSFV2PInterfaceAreaSourceSink.C
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_interface_area_model/gold/pressure_driven_growth_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_interface_area_model/gold/pressure_driven_growth_transient_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_interface_area_model/gold/turbulent_driven_growth_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_interface_area_model/pressure_driven_growth.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_interface_area_model/pressure_driven_growth_transient.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_interface_area_model/tests
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_interface_area_model/turbulent_driven_growth.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/channel-drift-flux-w-interface-area.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-advection-slip_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-drift-flux-w-interface-area_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-drift-flux_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/tests
Labels: PR: Failed but allowed

#28138 Add warnings to stitchers and options to merge boundaries.
  framework/doc/content/source/meshgenerators/MeshRepairGenerator.md
  framework/include/meshgenerators/MeshRepairGenerator.h
  framework/include/meshgenerators/StitchedMeshGenerator.h
  framework/include/utils/MooseMeshUtils.h
  framework/src/meshgenerators/MeshRepairGenerator.C
  framework/src/meshgenerators/StitchedMeshGenerator.C
  framework/src/utils/MooseMeshUtils.C
  modules/navier_stokes/examples/flow-over-circle/mesh.i
  modules/porous_flow/examples/ates/ates.i
  test/tests/mesh/preparedness/test.i
  test/tests/mesh/preparedness/tests
  test/tests/meshgenerators/mesh_repair_generator/gold/merge_boundaries_json.json
  test/tests/meshgenerators/mesh_repair_generator/merge_boundaries.i
  test/tests/meshgenerators/mesh_repair_generator/tests
  test/tests/meshgenerators/sidesets_from_points_generator/sidesets_ambiguity.i
  test/tests/meshgenerators/sidesets_from_points_generator/tests
  test/tests/meshgenerators/stitched_mesh_generator/stitched_mesh_generator.i
  test/tests/meshgenerators/stitched_mesh_generator/stitched_mesh_generator_sameid.i
  test/tests/meshgenerators/stitched_mesh_generator/tests
Labels: PR: Failed but allowed

#28085 Add more support for (v,e) TabulatedFP
  framework/include/utils/DelimitedFileReader.h
  modules/fluid_properties/doc/content/source/fluidproperties/TabulatedFluidProperties.md
  modules/fluid_properties/include/fluidproperties/LeadBismuthFluidProperties.h
  modules/fluid_properties/include/fluidproperties/LeadFluidProperties.h
  modules/fluid_properties/include/fluidproperties/SinglePhaseFluidProperties.h
  modules/fluid_properties/include/fluidproperties/TabulatedFluidProperties.h
  modules/fluid_properties/src/fluidproperties/SinglePhaseFluidProperties.C
  modules/fluid_properties/src/fluidproperties/TabulatedBicubicFluidProperties.C
  modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C
  modules/fluid_properties/test/tests/tabulated/gold/tabulated_direct_v_e_out.csv
  modules/fluid_properties/test/tests/tabulated/gold/tabulated_pT_out.csv
  modules/fluid_properties/test/tests/tabulated/gold/tabulated_v_e_loge_out.csv
  modules/fluid_properties/test/tests/tabulated/gold/tabulated_v_e_out.csv
  modules/fluid_properties/test/tests/tabulated/tabulated.i
  modules/fluid_properties/test/tests/tabulated/tabulated_v_e.i
  modules/fluid_properties/test/tests/tabulated/tests
  modules/fluid_properties/unit/include/TabulatedBicubicFluidPropertiesTest.h
  modules/fluid_properties/unit/src/TabulatedBicubicFluidPropertiesTest.C
Labels: PR: Failed but allowed

#28208 Add code server wrapper to apptainer containers
  apptainer/app.def
Labels: PR: Failed but allowed

#28226 Rename MAX_STACK_SIZE
  framework/doc/content/source/utils/PerfGraph.md
  framework/include/utils_nonunity/PerfGraph.h
  framework/include/utils_nonunity/PerfGraphLivePrint.h
  framework/src/utils_nonunity/PerfGraph.C
Labels: PR: Failed but allowed

#28195 Default MPICH instructions
  modules/doc/content/getting_started/installation/conda.md
  modules/doc/content/getting_started/installation/install_conda_moose.md
  modules/doc/content/getting_started/installation/manual_gcc.md
  modules/doc/content/getting_started/installation/manual_installation_gcc.md
  modules/doc/content/getting_started/installation/manual_installation_llvm.md
  modules/doc/content/getting_started/installation/manual_llvm.md
  modules/doc/content/getting_started/installation/true_update_conda.md
  modules/doc/content/help/faq/build_issues.md
  modules/doc/content/help/faq/conda_issues.md
  modules/doc/content/ncrc/applications/ncrc_develop.md.template
Labels: PR: Failed but allowed

#28255 Do not loop over boundary nodes when there is no NodalBC
  framework/src/systems/NonlinearSystemBase.C
Labels: PR: Failed but allowed

#28242 Add an inheritance layer shared by Action and MooseObject
  framework/include/actions/Action.h
  framework/include/base/MooseObject.h
  framework/include/base/ParallelParamObject.h
  framework/include/interfaces/DataFileInterface.h
  framework/src/actions/Action.C
  framework/src/base/MooseObject.C
  framework/src/base/ParallelParamObject.C
  framework/src/interfaces/DataFileInterface.C
Labels: PR: Failed but allowed

#28218 Add two function for coupling variables by name in Coupleable
  framework/doc/content/source/interfaces/Coupleable.md
  framework/include/userobjects/DomainUserObject.h
  framework/include/userobjects/ElementUserObject.h
  framework/include/userobjects/GeneralUserObject.h
  framework/include/userobjects/InterfaceUserObjectBase.h
  framework/include/userobjects/InternalSideUserObject.h
  framework/include/userobjects/MortarUserObject.h
  framework/include/userobjects/NodalUserObject.h
  framework/include/userobjects/SideUserObject.h
  framework/include/userobjects/UserObject.h
  framework/include/variables/CoupleableMooseVariableDependencyIntermediateInterface.h
  framework/src/userobjects/DomainUserObject.C
  framework/src/userobjects/ElementUserObject.C
  framework/src/userobjects/GeneralUserObject.C
  framework/src/userobjects/InterfaceUserObjectBase.C
  framework/src/userobjects/InternalSideUserObject.C
  framework/src/userobjects/MortarUserObject.C
  framework/src/userobjects/NodalUserObject.C
  framework/src/userobjects/SideUserObject.C
  framework/src/userobjects/UserObject.C
  framework/src/variables/CoupleableMooseVariableDependencyIntermediateInterface.C
  test/include/kernels/ArrayCoupledForceVar.h
  test/include/kernels/CoupledForceVar.h
  test/src/kernels/ArrayCoupledForceVar.C
  test/src/kernels/CoupledForceVar.C
  test/tests/interfaces/coupleable/array_coupling_by_name.i
  test/tests/interfaces/coupleable/coupling_by_name.i
  test/tests/interfaces/coupleable/gold/array_coupling_by_name_out.e
  test/tests/interfaces/coupleable/gold/coupling_by_name_out.e
  test/tests/interfaces/coupleable/tests
Labels: PR: Failed but allowed

#28262 Fixing IntegralDirectedSurfaceForce postprocessor.
  modules/navier_stokes/src/postprocessors/IntegralDirectedSurfaceForce.C
Labels: PR: Failed but allowed

#28191 Add support for file input of list of files to read in property read file
  framework/include/userobjects/PropertyReadFile.h
  framework/src/userobjects/PropertyReadFile.C
  test/tests/userobjects/property_read_file/data_element.csv
  test/tests/userobjects/property_read_file/data_element_t2.csv
  test/tests/userobjects/property_read_file/data_empty.csv
  test/tests/userobjects/property_read_file/data_files.csv
  test/tests/userobjects/property_read_file/gold/piecewise_constant_elem_multiple_out.e
  test/tests/userobjects/property_read_file/piecewise_constant_elem_multiple.i
  test/tests/userobjects/property_read_file/tests
Labels: PR: Failed but allowed

#28241 improvement of some error messages in MooseVariableBase
  framework/src/variables/MooseVariableBase.C
Labels: PR: Failed but allowed
