Repository idaholab/moose, pull requests merged in 2024-01, with the labels that each got.

#26454 Tweak EM module citation
  modules/doc/content/citing.md
  modules/electromagnetics/doc/content/modules/electromagnetics/index.md
Labels: PR: Auto Merge

#26464 Also install moose_test for apptainer moose, get installed framework tests working
  apptainer/app.def
  framework/app.mk
  framework/include/parser/CommandLine.h
  framework/moose.mk
  framework/scripts/get_repo_revision.py
  framework/src/base/MooseApp.C
  framework/src/parser/CommandLine.C
  test/tests/fviks/one-var-diffusion/tests
  test/tests/fvkernels/mms/advective-outflow/tests
  test/tests/fvkernels/mms/broken-domain/tests
  test/tests/fvkernels/mms/harmonic_interpolation/tests
  test/tests/fvkernels/mms/mass-mom-mat-advection-diffusion/tests
  test/tests/fvkernels/mms/skewness-correction/adv-diff-react/tests
  test/tests/fvkernels/mms/skewness-correction/diffusion/tests
  test/tests/fvkernels/mms/skewness-correction/two_term_extrapol/tests
  test/tests/meshdivisions/depletion_id_in.e
  test/tests/meshdivisions/extra_elem_id_division.i
  test/tests/meshdivisions/nested_division.i
  test/tests/misc/hit_cli/tests
  test/tests/mortar/convergence-studies/fv-gap-conductance/tests
  test/tests/outputs/format/tests
  test/tests/positions/depletion_id_in.e
  test/tests/positions/element_group_centroid_positions.i
  test/tests/samplers/distribute/tests
Labels: PR: Ready for review/merge

#26482 Allow contact tutorial to run to completion
  modules/contact/tutorials/introduction/step02.i
  modules/contact/tutorials/introduction/tests
Labels: PR: Ready for review/merge

#26394 Add L2, H(curl) and H(div) errors for vector variables
  framework/doc/content/source/functions/MooseParsedVectorFunction.md
  framework/doc/content/source/functormaterials/GenericVectorFunctorMaterial.md
  framework/doc/content/source/postprocessors/ElementHCurlError.md
  framework/doc/content/source/postprocessors/ElementHCurlSemiError.md
  framework/doc/content/source/postprocessors/ElementHDivError.md
  framework/doc/content/source/postprocessors/ElementHDivSemiError.md
  framework/doc/content/source/postprocessors/ElementVectorL2Error.md
  framework/doc/content/syntax/Functions/index.md
  framework/include/bcs/VectorIntegratedBC.h
  framework/include/bcs/VectorNodalBC.h
  framework/include/functions/Function.h
  framework/include/functions/MooseParsedVectorFunction.h
  framework/include/kernels/DivField.h
  framework/include/kernels/VectorKernel.h
  framework/include/postprocessors/ElementHCurlError.h
  framework/include/postprocessors/ElementHCurlSemiError.h
  framework/include/postprocessors/ElementHDivError.h
  framework/include/postprocessors/ElementHDivSemiError.h
  framework/include/postprocessors/ElementVectorL2Error.h
  framework/src/functions/Function.C
  framework/src/functions/MooseParsedVectorFunction.C
  framework/src/kernels/DivField.C
  framework/src/postprocessors/ElementHCurlError.C
  framework/src/postprocessors/ElementHCurlSemiError.C
  framework/src/postprocessors/ElementHDivError.C
  framework/src/postprocessors/ElementHDivSemiError.C
  framework/src/postprocessors/ElementVectorL2Error.C
  modules/electromagnetics/src/bcs/VectorEMRobinBC.C
  test/src/bcs/VectorCurlBC.C
  test/tests/kernels/vector_fe/coupled_electrostatics.i
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_hex27.csv
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_hex27.e
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_quad8.csv
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_quad8.e
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_quad9.csv
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_quad9.e
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_tet14.csv
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_tet14.e
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_tri6.csv
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_tri6.e
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_tri7.csv
  test/tests/kernels/vector_fe/gold/coupled_electrostatics_tri7.e
  test/tests/kernels/vector_fe/gold/vector_kernel_out.csv
  test/tests/kernels/vector_fe/tests
  test/tests/kernels/vector_fe/vector_kernel.i
Labels: PR: Failed but allowed

#26282 variable scaling for multiple nonlinear systems
  framework/include/problems/SubProblem.h
  framework/src/problems/SubProblem.C
  framework/src/systems/SystemBase.C
  framework/src/variables/MooseVariableBase.C
  modules/optimization/src/executioners/AdjointSolve.C
  modules/optimization/test/tests/misc/scaling_test/scaling_test.i
  modules/optimization/test/tests/misc/scaling_test/tests
Labels: PR: Failed but allowed

#26051 More unity
  framework/app.mk
  framework/moose.mk
Labels: PR: Failed but allowed, PR: Ready for review/merge

#26510 Update UIUC training
  modules/doc/content/training/more_detail/MOOSE_2024_10_15-17_UIUC.md
Labels: C: Documentation

#26516 Don't use deprecated transfers in THM
  framework/doc/content/source/transfers/MultiAppGeneralFieldTransfer.md
  modules/thermal_hydraulics/src/actions/CoupledHeatTransferAction.C
  modules/thermal_hydraulics/test/tests/actions/coupled_heat_transfer_action/master.i
  modules/thermal_hydraulics/test/tests/components/form_loss_from_external_app_1phase/phy.form_loss_1phase.parent.i
  modules/thermal_hydraulics/test/tests/components/heat_transfer_from_external_app_1phase/phy.T_wall_transfer_3eqn.parent.i
  modules/thermal_hydraulics/test/tests/components/heat_transfer_from_external_app_1phase/phy.T_wall_transfer_elem_3eqn.parent.i
  modules/thermal_hydraulics/test/tests/components/heat_transfer_from_external_app_1phase/phy.q_wall_transfer_3eqn.parent.i
  modules/thermal_hydraulics/test/tests/components/hs_boundary_external_app_convection/plate.parent.i
  modules/thermal_hydraulics/test/tests/components/hs_boundary_external_app_heat_flux/main.i
  modules/thermal_hydraulics/test/tests/components/hs_boundary_external_app_temperature/phy.parent.i
Labels: PR: Failed but allowed

#26528 Silence excessive log after reading unique file
  framework/src/userobjects/PropertyReadFile.C
Labels: PR: Failed but allowed

#26241 Add document for some porous flow tests.
  modules/porous_flow/doc/content/bib/porous_flow.bib
  modules/porous_flow/doc/content/media/porous_flow/brook_corey.png
  modules/porous_flow/doc/content/media/porous_flow/brook_corey1.png
  modules/porous_flow/doc/content/media/porous_flow/brook_corey2.png
  modules/porous_flow/doc/content/media/porous_flow/corey1.png
  modules/porous_flow/doc/content/media/porous_flow/corey2.png
  modules/porous_flow/doc/content/media/porous_flow/corey3.png
  modules/porous_flow/doc/content/media/porous_flow/corey4.png
  modules/porous_flow/doc/content/media/porous_flow/vangen.png
  modules/porous_flow/doc/content/media/porous_flow/vangen1.png
  modules/porous_flow/doc/content/media/porous_flow/vangen2.png
  modules/porous_flow/doc/content/modules/porous_flow/tests.md
  modules/porous_flow/doc/content/modules/porous_flow/tests/adv_diff_bcs/adv_diff_bcs_tests.md
  modules/porous_flow/doc/content/modules/porous_flow/tests/capillary_pressure/brook_corey.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/capillary_pressure/capillary_pressure.py
  modules/porous_flow/doc/content/modules/porous_flow/tests/capillary_pressure/capillary_pressure_tests.md
  modules/porous_flow/doc/content/modules/porous_flow/tests/capillary_pressure/vangen.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/fluids/brook_corey1.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/fluids/fluids.py
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/brook_corey1.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/brook_corey2.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/corey1.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/corey2.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/corey3.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/corey4.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/relperm.py
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/relperm_tests.md
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/unity.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/vangen1.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/relperm/vangen2.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/thm_rehbinder/displacement_fig.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/thm_rehbinder/porepressure_fig.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/thm_rehbinder/temperature_fig.png
  modules/porous_flow/doc/content/modules/porous_flow/tests/thm_rehbinder/thm_rehbinder_tests.md
  modules/porous_flow/test/tests/thm_rehbinder/thm_rehbinder.py
Labels: PR: Failed but allowed

#26526 Build moose_test-opt in the Conda MOOSE package
  conda/moose/build.sh
  test/tests/materials/derivative_material_interface/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#26531 Testing and fixing parallel issue with reporters that operate on data collected from samplers
  modules/combined/test/tests/optimization/invOpt_multiExperiment/sampler_subapp.i
  modules/combined/test/tests/optimization/invOpt_multiExperiment/tests
  modules/optimization/include/reporters/ParsedVectorVectorRealReductionReporter.h
  modules/optimization/src/reporters/ParsedScalarReporter.C
  modules/optimization/src/reporters/ParsedVectorRealReductionReporter.C
  modules/optimization/src/reporters/ParsedVectorReporter.C
  modules/optimization/src/reporters/ParsedVectorVectorRealReductionReporter.C
Labels: PR: Failed but allowed

#26562 Allow more complicated absolute paths in file_base
  framework/include/utils/MooseUtils.h
  framework/src/outputs/FileOutput.C
  framework/src/utils/MooseUtils.C
Labels: C: Framework, PR: Ready for review/merge

#26559 Consolidate equivalent hit binaries
  framework/contrib/hit/hit.cpp
  framework/contrib/hit/hit311.cpp
  framework/contrib/hit/hitpre311.cpp
Labels: PR: Failed but allowed

#26576 Resolve `DependencyResolver` issue with missing cyclic sub-graphs
  framework/include/base/TheWarehouse.h
  framework/include/interfaces/DependencyResolverInterface.h
  framework/include/utils/DependencyResolver.h
  framework/src/base/TheWarehouse.C
  test/tests/positions/creating_multiapps/tests
  unit/src/DependencyResolverTest.C
Labels: C: Framework, PR: Failed but allowed, PR: Ready for review/merge

#26594 Minor cosmetic changes
  framework/include/interfaces/TaggingInterface.h
  framework/src/bcs/VectorCurlPenaltyDirichletBC.C
  framework/src/bcs/VectorDivPenaltyDirichletBC.C
  framework/src/interfaces/TaggingInterface.C
  test/tests/kernels/vector_fe/tests
Labels: PR: Failed but allowed

#26540 Add Changelog Revision section to RTM
  framework/doc/content/sqa/framework_rtm.md
  framework/doc/content/templates/sqa/rtm.md.template
  modules/contact/doc/content/modules/contact/sqa/contact_rtm.md
  modules/doc/content/sqa/moose_rtm.md
  modules/electromagnetics/doc/content/modules/electromagnetics/sqa/electromagnetics_rtm.md
  modules/fluid_properties/doc/content/modules/fluid_properties/sqa/fluid_properties_rtm.md
  modules/fsi/doc/content/modules/fsi/sqa/fsi_rtm.md
  modules/heat_transfer/doc/content/modules/heat_transfer/sqa/heat_transfer_rtm.md
  modules/level_set/doc/content/modules/level_set/sqa/level_set_rtm.md
  modules/misc/doc/content/modules/misc/sqa/misc_rtm.md
  modules/navier_stokes/doc/content/modules/navier_stokes/sqa/navier_stokes_rtm.md
  modules/optimization/doc/content/modules/optimization/sqa/optimization_rtm.md
  modules/phase_field/doc/content/modules/phase_field/sqa/phase_field_rtm.md
  modules/porous_flow/doc/content/modules/porous_flow/sqa/porous_flow_rtm.md
  modules/ray_tracing/doc/content/sqa/ray_tracing_rtm.md
  modules/rdg/doc/content/sqa/rdg_rtm.md
  modules/reactor/doc/content/modules/reactor/sqa/reactor_rtm.md
  modules/scalar_transport/doc/content/sqa/scalar_transport_rtm.md
  modules/solid_properties/doc/content/modules/solid_properties/sqa/solid_properties_rtm.md
  modules/stochastic_tools/doc/content/modules/stochastic_tools/sqa/stochastic_tools_rtm.md
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/sqa/tensor_mechanics_rtm.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/sqa/thermal_hydraulics_rtm.md
  modules/xfem/doc/content/modules/xfem/sqa/xfem_rtm.md
  python/doc/content/python/sqa/python_rtm.md
Labels: PR: Failed but allowed

#26589 Allow INSAD kernels to take real constants for material property names
  framework/include/materials/Material.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/src/materials/Material.C
  framework/src/problems/FEProblemBase.C
  modules/navier_stokes/include/materials/INSADMaterial.h
  modules/navier_stokes/src/materials/INSADMaterial.C
  modules/navier_stokes/test/tests/finite_element/ins/boussinesq/boussinesq_square_constant_names.i
  modules/navier_stokes/test/tests/finite_element/ins/boussinesq/gold/boussinesq_square_constant_names_out.e
  modules/navier_stokes/test/tests/finite_element/ins/boussinesq/tests
  modules/optimization/src/executioners/OptimizeSolve.C
Labels: C: Framework, PR: Failed but allowed, C: Modules/Navier Stokes

#26597 Add stationary ray capability
  modules/ray_tracing/doc/content/source/raytracing/Ray.md
  modules/ray_tracing/include/raytracing/Ray.h
  modules/ray_tracing/include/raytracing/TraceRay.h
  modules/ray_tracing/src/raytracing/Ray.C
  modules/ray_tracing/src/raytracing/TraceRay.C
  modules/ray_tracing/test/include/userobjects/StationaryRayStudyTest.h
  modules/ray_tracing/test/src/userobjects/StationaryRayStudyTest.C
  modules/ray_tracing/test/src/userobjects/TestRay.C
  modules/ray_tracing/test/tests/raytracing/stationary/errors.i
  modules/ray_tracing/test/tests/raytracing/stationary/gold/stationary_out.e
  modules/ray_tracing/test/tests/raytracing/stationary/stationary.i
  modules/ray_tracing/test/tests/raytracing/stationary/tests
Labels: PR: Failed but allowed

#26483 Sub-block support for Thermochimica calculations
  modules/chemical_reactions/doc/content/source/actions/ChemicalCompositionAction.md
  modules/chemical_reactions/doc/content/source/actions/CommonChemicalCompositionAction.md
  modules/chemical_reactions/doc/content/syntax/ChemicalComposition/index.md
  modules/chemical_reactions/include/actions/ChemicalCompositionAction.h
  modules/chemical_reactions/include/actions/CommonChemicalCompositionAction.h
  modules/chemical_reactions/include/userobjects/ThermochimicaData.h
  modules/chemical_reactions/src/actions/ChemicalCompositionAction.C
  modules/chemical_reactions/src/actions/CommonChemicalCompositionAction.C
  modules/chemical_reactions/src/base/ChemicalReactionsApp.C
  modules/chemical_reactions/src/userobjects/ThermochimicaData.C
  modules/chemical_reactions/test/tests/thermochimica/FeTiVO.i
  modules/chemical_reactions/test/tests/thermochimica/MoRu.i
  modules/chemical_reactions/test/tests/thermochimica/MoRuPd.i
  modules/chemical_reactions/test/tests/thermochimica/MoRu_block-restrict.i
  modules/chemical_reactions/test/tests/thermochimica/MoRu_subblock.i
  modules/chemical_reactions/test/tests/thermochimica/csv_ic.i
  modules/chemical_reactions/test/tests/thermochimica/csv_ic_all.i
  modules/chemical_reactions/test/tests/thermochimica/gold/MoRu_block-restrict_out.e
  modules/chemical_reactions/test/tests/thermochimica/gold/MoRu_subblock_out.e
  modules/chemical_reactions/test/tests/thermochimica/gold/csv_ic_all_out.e
  modules/chemical_reactions/test/tests/thermochimica/tests
Labels: PR: Failed but allowed

#26593 Support aux kernel evaluation of lower-d vars
  framework/doc/content/syntax/AuxKernels/index.md
  framework/include/auxkernels/AuxKernel.h
  framework/include/base/Assembly.h
  framework/include/interfaces/BlockRestrictable.h
  framework/include/mesh/MooseMesh.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/include/variables/MooseVariableBase.h
  framework/include/variables/MooseVariableFE.h
  framework/include/variables/MooseVariableFV.h
  framework/include/variables/MooseVariableField.h
  framework/include/variables/MooseVariableFieldBase.h
  framework/src/auxkernels/AuxKernel.C
  framework/src/loops/ComputeElemAuxBcsThread.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/RefineSidesetGenerator.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  framework/src/variables/MooseVariableBase.C
  framework/src/variables/MooseVariableFE.C
  framework/src/variables/MooseVariableFV.C
  test/tests/auxkernels/lower_d_var/gold/lower-d-aux-var_out.csv
  test/tests/auxkernels/lower_d_var/lower-d-aux-var.i
  test/tests/auxkernels/lower_d_var/tests
Labels: C: Framework

#26613 Remove redundant solver default setting
  framework/include/problems/EigenProblem.h
  framework/include/problems/FEProblemBase.h
  framework/src/problems/EigenProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/timeintegrators/AStableDirk4.C
  framework/src/timeintegrators/ExplicitRK2.C
  framework/src/timeintegrators/ExplicitTVDRK2.C
  framework/src/timeintegrators/ImplicitMidpoint.C
  framework/src/timeintegrators/LStableDirk2.C
  framework/src/timeintegrators/LStableDirk3.C
  framework/src/timeintegrators/LStableDirk4.C
  framework/src/utils/SlepcEigenSolverConfiguration.C
  modules/navier_stokes/include/problems/NavierStokesProblem.h
  modules/navier_stokes/src/problems/NavierStokesProblem.C
Labels: C: Framework

#26611 LSC requires PETSc >= 3.20
  modules/navier_stokes/include/problems/NavierStokesProblem.h
  modules/navier_stokes/src/problems/NavierStokesProblem.C
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/tests
Labels: C: Modules/Navier Stokes

#26444 Add functor material property shortcut output
  framework/include/actions/MaterialOutputAction.h
  framework/include/functormaterials/FunctorMaterial.h
  framework/src/actions/MaterialOutputAction.C
  framework/src/functormaterials/FunctorMaterial.C
  framework/src/functormaterials/ParsedFunctorMaterial.C
  test/tests/functormaterials/output/gold/output_ad_out.e
  test/tests/functormaterials/output/gold/output_out.e
  test/tests/functormaterials/output/output.i
  test/tests/functormaterials/output/output_ad.i
  test/tests/functormaterials/output/tests
Labels: C: Framework

#26636 FSI acoustic structure interface document fix
  modules/fsi/doc/content/source/interfacekernels/StructureAcousticInterface.md
Labels: C: Modules/FSI

#26617 Fix automatic scaling for array variables
  framework/include/variables/MooseVariableBase.h
  framework/src/systems/NonlinearSystemBase.C
  framework/src/systems/SystemBase.C
  framework/src/variables/MooseVariableBase.C
  test/tests/scaling/array-variables/gold/test_out.e
  test/tests/scaling/array-variables/test.i
  test/tests/scaling/array-variables/tests
Labels: C: Framework

#26630 Improve the AD docs
  framework/doc/content/automatic_differentiation/index.md
  framework/doc/content/source/systems/NonlinearSystem.md
  framework/doc/content/source/utils/DualReal.md
  modules/doc/content/getting_started/examples_and_tutorials/tutorial01_app_development/step10_auxkernels.md
  modules/doc/content/getting_started/new_users.md.template
  python/TestHarness/util.py
Labels: C: Documentation

#26644 Need to be able to set the moose mesh for mesh generators
  framework/include/meshgenerators/MeshGenerator.h
  framework/include/utils/MooseMeshUtils.h
  framework/src/meshgenerators/MeshGenerator.C
  framework/src/utils/MooseMeshUtils.C
Labels: PR: Failed but allowed

#26656 Use CoupledName as an alias for std::vector<VariableName>
  framework/include/utils/MooseTypes.h
  modules/contact/include/actions/ContactAction.h
  modules/navier_stokes/include/actions/CNSAction.h
  modules/navier_stokes/include/actions/INSAction.h
  modules/navier_stokes/include/base/NSFVBase.h
  modules/tensor_mechanics/include/actions/DomainIntegralAction.h
Labels: C: Framework

#25977 Add Physics base class and a heat conduction example
  framework/doc/content/source/physics/DiffusionCG.md
  framework/doc/content/source/physics/DiffusionFV.md
  framework/doc/content/source/physics/DiffusionPhysicsBase.md
  framework/doc/content/syntax/Physics/Diffusion/ContinuousGalerkin/index.md
  framework/doc/content/syntax/Physics/Diffusion/FiniteVolume/index.md
  framework/doc/content/syntax/Physics/Diffusion/index.md
  framework/doc/content/syntax/Physics/index.md
  framework/doc/globals.yml
  framework/include/base/Factory.h
  framework/include/executioners/Executioner.h
  framework/include/physics/DiffusionCG.h
  framework/include/physics/DiffusionFV.h
  framework/include/physics/DiffusionPhysicsBase.h
  framework/include/physics/PhysicsBase.h
  framework/include/utils/InputParameters.h
  framework/include/utils/MooseTypes.h
  framework/src/actions/ActionWarehouse.C
  framework/src/base/Factory.C
  framework/src/base/Moose.C
  framework/src/parser/Builder.C
  framework/src/physics/DiffusionCG.C
  framework/src/physics/DiffusionFV.C
  framework/src/physics/DiffusionPhysicsBase.C
  framework/src/physics/PhysicsBase.C
  framework/src/utils/InputParameters.C
  modules/doc/config.yml
  modules/heat_transfer/doc/content/source/physics/HeatConductionFE.md
  modules/heat_transfer/doc/content/syntax/Physics/HeatConduction/FiniteElement/index.md
  modules/heat_transfer/doc/content/syntax/Physics/HeatConduction/index.md
  modules/heat_transfer/include/physics/HeatConductionFE.h
  modules/heat_transfer/include/physics/HeatConductionPhysics.h
  modules/heat_transfer/src/base/HeatTransferApp.C
  modules/heat_transfer/src/physics/HeatConductionFE.C
  modules/heat_transfer/src/physics/HeatConductionPhysics.C
  modules/heat_transfer/test/tests/physics/gold/test_fe_out.e
  modules/heat_transfer/test/tests/physics/test_fe.i
  modules/heat_transfer/test/tests/physics/tests
  test/tests/physics/diffusion_cg.i
  test/tests/physics/diffusion_fv.i
  test/tests/physics/gold/diffusion_cg_out_sample_0010.csv
  test/tests/physics/gold/diffusion_fv_out_sample_0010.csv
  test/tests/physics/tests
  unit/src/MooseServerTest.C
Labels: PR: Failed but allowed

#26658 Robustify Rayleigh Bernard two phase test
  modules/navier_stokes/doc/content/source/functormaterials/WCNSFV2PSlipVelocityFunctorMaterial.md
  modules/navier_stokes/include/functormaterials/WCNSFV2PSlipVelocityFunctorMaterial.h
  modules/navier_stokes/src/functormaterials/NSFVDispersePhaseDragFunctorMaterial.C
  modules/navier_stokes/src/functormaterials/WCNSFV2PSlipVelocityFunctorMaterial.C
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/rayleigh-bernard-two-phase_CSV.csv
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/rayleigh-bernard-two-phase.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/tests
Labels: C: Modules/Navier Stokes

#26677 Add MOOSE training at Duke
  modules/doc/content/training/index.md
  modules/doc/content/training/more_detail/MOOSE_2024_03_11-12_DUKE.md
Labels: PR: Failed but allowed

#26678 THM home page improvements
  modules/doc/content/newsletter/2022/2022_02.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/examples/brayton_cycle/brayton_cycle.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/examples/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/examples/recuperated_brayton_cycle/recuperated_brayton_cycle.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/getting_started.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/modeling_guide/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/syntax.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/test_problems/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/tutorials/single_phase_flow/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/tutorials/single_phase_flow/step01.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/tutorials/single_phase_flow/step06.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/adding_new_cases.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/index.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/cosine_nozzle.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/double_rarefaction.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/free_fall.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/hydrostatic_pressure.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/lax_shock_tube.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/sedov_blast_wave.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/sod_shock_tube.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/square_wave.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/stationary_fluid.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/super_sonic_tube.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/water_hammer.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/v_and_v/verification/woodward_colella_blast_wave.md
Labels: PR: Failed but allowed

#23513 Build a mesh generator which creates an overlaying mesh over the given mesh
  framework/doc/content/source/meshgenerators/OverlayMeshGenerator.md
  framework/include/mesh/MooseMesh.h
  framework/include/meshgenerators/OverlayMeshGenerator.h
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/OverlayMeshGenerator.C
  test/tests/meshgenerators/overlay_mesh_generator/gold/overlay_mesh_generator_in.e
  test/tests/meshgenerators/overlay_mesh_generator/overlay_mesh_generator.i
  test/tests/meshgenerators/overlay_mesh_generator/tests
Labels: PR: Failed but allowed

#26683 More robustification for mixture model tests
  modules/navier_stokes/doc/content/source/auxkernels/WCNSFV2PSlipVelocityAux.md
  modules/navier_stokes/doc/content/source/functormaterials/WCNSFV2PSlipVelocityFunctorMaterial.md
  modules/navier_stokes/doc/content/source/fvkernels/WCNSFV2PMomentumDriftFlux.md
  modules/navier_stokes/include/auxkernels/WCNSFV2PSlipVelocityAux.h
  modules/navier_stokes/include/fvkernels/INSFVMomentumAdvection.h
  modules/navier_stokes/include/fvkernels/WCNSFV2PMomentumAdvectionSlip.h
  modules/navier_stokes/src/auxkernels/WCNSFV2PSlipVelocityAux.C
  modules/navier_stokes/src/functormaterials/NSFVDispersePhaseDragFunctorMaterial.C
  modules/navier_stokes/src/functormaterials/WCNSFV2PSlipVelocityFunctorMaterial.C
  modules/navier_stokes/src/fvkernels/WCNSFV2PMomentumAdvectionSlip.C
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/channel-advection-slip.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/channel-drift-flux.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-advection-slip_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-drift-flux_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/lid-driven-two-phase_CSV.csv
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/lid-driven-two-phase.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/tests
Labels: C: Modules/Navier Stokes

#26614 Accurately retrieve the mesh dimension
  framework/src/meshgenerators/AdvancedExtruderGenerator.C
  framework/src/meshgenerators/SideSetsGeneratorBase.C
  test/tests/meshgenerators/ordering_of_execution/modifier_depend_order.i
Labels: PR: Failed but allowed
