Repository idaholab/moose, pull requests merged in 2024-04, with the labels that each got.

#27246 Skip system check in latest optimization module test
  modules/optimization/examples/diffusion_reaction/forward_and_adjoint.i
Labels: PR: Failed but allowed

#27261 Documentation improvements
  framework/doc/content/source/kernels/ADCoupledTimeDerivative.md
  framework/doc/content/source/kernels/ADKernelGrad.md
  framework/doc/content/source/kernels/ADKernelValue.md
  framework/doc/content/source/kernels/CoupledTimeDerivative.md
  framework/doc/content/source/kernels/GradField.md
  framework/doc/content/source/kernels/KernelGrad.md
  framework/doc/content/source/kernels/KernelValue.md
  framework/doc/content/source/kernels/MassLumpedTimeDerivative.md
  framework/doc/content/source/kernels/MaterialDerivativeTestKernel.md
  framework/doc/content/source/problems/FEProblemBase.md
  framework/src/kernels/ArrayCoupledTimeDerivative.C
  framework/src/kernels/DivField.C
  framework/src/kernels/GradField.C
  modules/doc/content/getting_started/examples_and_tutorials/examples/ex01_inputfile.md
  modules/doc/content/getting_started/examples_and_tutorials/examples/ex03_coupling.md
  modules/doc/content/getting_started/installation/install_peacock.md
  modules/doc/content/help/finite_element_concepts/fem_principles.md
  modules/heat_transfer/doc/content/source/auxkernels/JouleHeatingHeatGeneratedAux.md
  modules/heat_transfer/src/auxkernels/JouleHeatingHeatGeneratedAux.C
  modules/navier_stokes/doc/content/source/fvkernels/INSFVTKESourceSink.md
  modules/solid_mechanics/doc/content/modules/solid_mechanics/Stresses.md
  modules/solid_mechanics/doc/content/source/materials/ADComputeGreenLagrangeStrain.md
  modules/solid_mechanics/doc/content/source/userobjects/CrystalPlasticitySlipRateGSS.md
  python/doc/content/python/peacock.md
Labels: PR: Failed but allowed

#27172 Separate auxvariable norms for steady state detection
  framework/include/executioners/Transient.h
  framework/include/systems/AuxiliarySystem.h
  framework/src/executioners/Transient.C
  framework/src/systems/AuxiliarySystem.C
  test/tests/executioners/aux-ss-detection/gold/simple_transient_diffusion_out.e
  test/tests/executioners/aux-ss-detection/gold/test_with_external_prob_out.e
  test/tests/executioners/aux-ss-detection/simple_transient_diffusion.i
  test/tests/executioners/aux-ss-detection/test_with_external_prob.i
  test/tests/executioners/aux-ss-detection/tests
Labels: PR: Failed but allowed

#27256 Fix mac JIT compile
  framework/src/utils/ADFParser.C
  modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/tests
  modules/navier_stokes/test/tests/finite_volume/wcns/natural_convection/tests
  modules/phase_field/test/tests/GrandPotentialPFM/tests
  modules/phase_field/test/tests/phase_field_kernels/tests
Labels: PR: Failed but allowed

#27221 Fix shared pointer factory create
  framework/include/base/MooseObject.h
  framework/src/base/MooseObject.C
  unit/src/MooseObjectTest.C
Labels: PR: Failed but allowed

#26750 Elasticity inversion using NEML2
  framework/doc/content/source/userobjects/BatchPropertyDerivative.md
  framework/include/userobjects/BatchMaterial.h
  framework/include/userobjects/BatchPropertyDerivative.h
  framework/src/userobjects/BatchPropertyDerivative.C
  modules/combined/test/tests/optimization/invOpt_elasticity/elasticity.i
  modules/combined/test/tests/optimization/invOpt_elasticity/forward.i
  modules/combined/test/tests/optimization/invOpt_elasticity/gold/main_out_OptimizationReporter_0001.csv
  modules/combined/test/tests/optimization/invOpt_elasticity/grad.i
  modules/combined/test/tests/optimization/invOpt_elasticity/main.i
  modules/combined/test/tests/optimization/invOpt_elasticity/tests
  modules/optimization/doc/content/source/vectorpostprocessors/AdjointStrainBatchStressGradInnerProduct.md
  modules/optimization/include/vectorpostprocessors/AdjointStrainBatchStressGradInnerProduct.h
  modules/optimization/src/vectorpostprocessors/AdjointStrainBatchStressGradInnerProduct.C
  modules/optimization/test/include/vectorpostprocessors/OptimizationBatchPropertyDerivativeTest.h
  modules/optimization/test/src/vectorpostprocessors/OptimizationBatchPropertyDerivativeTest.C
  modules/optimization/test/tests/vectorpostprocessors/adjoint_strain_batch_stress_grad_inner_product/gold/strain_stress_grad_inner_product_out_inner_product_0011.csv
  modules/optimization/test/tests/vectorpostprocessors/adjoint_strain_batch_stress_grad_inner_product/strain_stress_grad_inner_product.i
  modules/optimization/test/tests/vectorpostprocessors/adjoint_strain_batch_stress_grad_inner_product/tests
  modules/solid_mechanics/include/neml2/userobjects/CauchyStressFromNEML2UO.h
  modules/solid_mechanics/src/neml2/userobjects/CauchyStressFromNEML2UO.C
  test/include/materials/BatchTestPropertyDerivative.h
  test/include/userobjects/BatchPropertyDerivativeTest.h
  test/src/materials/BatchTestPropertyDerivative.C
  test/src/userobjects/BatchPropertyDerivativeTest.C
  test/tests/batch_property_derivative/test.i
  test/tests/batch_property_derivative/tests
Labels: PR: Failed but allowed

#27275 Add `const` version for `getSharedPtr()`
  framework/include/base/MooseObject.h
  framework/src/base/MooseObject.C
  unit/src/MooseObjectTest.C
Labels: PR: Failed but allowed

#27272 Fix petsc_alt next
  modules/optimization/examples/diffusion_reaction/forward_and_adjoint.i
  modules/optimization/examples/diffusion_reaction/tests
Labels: PR: Failed but allowed

#27274 Fix PiecewiseByBlockMaterial for continuous variable
  framework/src/materials/PiecewiseConstantByBlockMaterial.C
  test/tests/materials/piecewise_by_block_material/continuous.i
  test/tests/materials/piecewise_by_block_material/discontinuous.i
  test/tests/materials/piecewise_by_block_material/discontinuous_functor.i
  test/tests/materials/piecewise_by_block_material/gold/continuous_out.e
  test/tests/materials/piecewise_by_block_material/gold/discontinuous_functor_out.e
  test/tests/materials/piecewise_by_block_material/gold/discontinuous_out.e
  test/tests/materials/piecewise_by_block_material/tests
Labels: PR: Failed but allowed

#27287 Check whether `_eigen_sys` was cast successfully
  framework/src/kernels/EigenKernel.C
Labels: PR: Failed but allowed

#27290 Limit _stage variable to prevent OOB access
  framework/src/timeintegrators/ExplicitSSPRungeKutta.C
Labels: PR: Failed but allowed

#27302 Make FixedPointSolve respect fixed_point_min_its with custom_pp
  framework/src/executioners/FixedPointSolve.C
Labels: PR: Failed but allowed

#27304 Must compute time derivatives ahead of Jacobian for coloring
  framework/include/systems/NonlinearSystem.h
  framework/include/systems/SolverSystem.h
  framework/src/systems/NonlinearSystem.C
  framework/src/systems/SolverSystem.C
Labels: C: Framework, PR: Failed but allowed

#27312 Add ignore_solve_not_converge parameter in ParameterStudy
  modules/stochastic_tools/src/actions/ParameterStudyAction.C
Labels: PR: Failed but allowed

#27194 Output at FORWARD for optimization
  modules/optimization/include/executioners/OptimizeSolve.h
  modules/optimization/src/executioners/OptimizeSolve.C
  modules/optimization/test/tests/optimizationreporter/general_opt/function_optimization/gold/main_json.json
  modules/optimization/test/tests/optimizationreporter/general_opt/function_optimization/gold/main_json_forward.json
  modules/optimization/test/tests/optimizationreporter/general_opt/function_optimization/main.i
  modules/optimization/test/tests/optimizationreporter/general_opt/function_optimization/tests
Labels: PR: Failed but allowed

#27248 Added convection heat flux functor material
  modules/doc/content/newsletter/2024/2024_04.md
  modules/heat_transfer/doc/content/modules/heat_transfer/index.md
  modules/heat_transfer/doc/content/source/functormaterials/ConvectionHeatFluxFunctorMaterial.md
  modules/heat_transfer/include/functormaterials/ConvectionHeatFluxFunctorMaterial.h
  modules/heat_transfer/src/functormaterials/ConvectionHeatFluxFunctorMaterial.C
  modules/heat_transfer/test/tests/functormaterials/convection_heat_flux/convection_heat_flux.i
  modules/heat_transfer/test/tests/functormaterials/convection_heat_flux/gold/convection_heat_flux_out.csv
  modules/heat_transfer/test/tests/functormaterials/convection_heat_flux/tests
Labels: PR: Failed but allowed

#27351 27349 add gfortran
  conda/libmesh-vtk/conda_build_config.yaml
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/conda_build_config.yaml
  conda/libmesh/meta.yaml
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/mpich/conda_build_config.yaml
  conda/mpich/meta.yaml
  conda/peacock/conda_build_config.yaml
  conda/peacock/meta.yaml
  conda/petsc/conda_build_config.yaml
  conda/petsc/meta.yaml
  framework/doc/packages_config.yml
  scripts/tests/versioner_hashes.yaml
Labels: PR: Failed but allowed

#27341 Update FunctionSideAverage.md
  framework/doc/content/source/postprocessors/FunctionSideAverage.md
Labels: PR: Failed but allowed

#27344 More detailed error messages for inconsistent pitch metadata
  framework/src/utils/FormattedTable.C
  modules/reactor/include/meshgenerators/PolygonMeshGeneratorBase.h
  modules/reactor/src/meshgenerators/PatternedCartesianMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedHexMeshGenerator.C
  modules/reactor/src/meshgenerators/PolygonMeshGeneratorBase.C
Labels: PR: Failed but allowed

#27367 Colored fixed point iterations based on previous residual
  framework/src/executioners/PicardSolve.C
  framework/src/executioners/SecantSolve.C
  framework/src/executioners/SteffensenSolve.C
Labels: PR: Failed but allowed

#27330 Patch for MultiAppVectorPostprocessorTransfer for distributed subapps.
  framework/src/transfers/MultiAppVectorPostprocessorTransfer.C
  test/tests/transfers/multiapp_vector_pp_transfer/parent.i
  test/tests/transfers/multiapp_vector_pp_transfer/tests
Labels: PR: Failed but allowed

#27354 Mat body force
  framework/doc/content/source/kernels/ADMatBodyForce.md
  framework/doc/content/source/kernels/MatBodyForce.md
  framework/include/kernels/MatBodyForce.h
  framework/src/kernels/MatBodyForce.C
  test/tests/kernels/body_force/ad_mat_forcing_function_test.i
  test/tests/kernels/body_force/forcing_function_error_check.i
  test/tests/kernels/body_force/forcing_function_test.i
  test/tests/kernels/body_force/gold/ad_mat_forcing_function_test_out.e
  test/tests/kernels/body_force/gold/forcing_function_test_out.e
  test/tests/kernels/body_force/gold/mat_forcing_function_test_out.e
  test/tests/kernels/body_force/mat_forcing_function_test.i
  test/tests/kernels/body_force/tests
  test/tests/kernels/forcing_function/forcing_function_test.i
  test/tests/kernels/forcing_function/tests
Labels: PR: Failed but allowed

#27249 Improved the requested non-AD functor error message
  framework/doc/content/syntax/Functors/index.md
  framework/include/problems/SubProblem.h
  test/tests/materials/functor_properties/tests
Labels: PR: Failed but allowed

#27283 Training fixes
  modules/doc/content/getting_started/examples_and_tutorials/examples_tutorials.md
  modules/doc/content/training/index.md
  modules/doc/content/training/more_detail/MOOSE_2024_03_11-12_DUKE.md
  modules/doc/content/training/more_detail/MOOSE_2024_04_02-04_OSU.md
  tutorials/darcy_thermo_mech/doc/content/workshop/cpp/01_basics.md
  tutorials/darcy_thermo_mech/doc/content/workshop/cpp/02_scope.md
  tutorials/darcy_thermo_mech/doc/content/workshop/cpp/03_types.md
  tutorials/darcy_thermo_mech/doc/content/workshop/cpp/04_classes.md
  tutorials/darcy_thermo_mech/doc/content/workshop/cpp/standards.md
  tutorials/darcy_thermo_mech/doc/content/workshop/infrastructure/debugging.md
  tutorials/darcy_thermo_mech/doc/content/workshop/modules/modules.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step01.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step02.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step03.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step04.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step05.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step06.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step07.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step08.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step09.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step10.md
  tutorials/darcy_thermo_mech/doc/content/workshop/problem/step11.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/auxkernels.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/inputparameters.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/mesh.md
  tutorials/darcy_thermo_mech/doc/content/workshop/systems/transfers.md
Labels: PR: Failed but allowed

#27242 Part 1 of finishing modules object & syntax documentation
  modules/chemical_reactions/doc/content/modules/chemical_reactions/index.md
  modules/chemical_reactions/doc/content/source/actions/AddCoupledEqSpeciesAction.md
  modules/chemical_reactions/doc/content/source/actions/AddCoupledSolidKinSpeciesAction.md
  modules/chemical_reactions/doc/content/source/actions/AddPrimarySpeciesAction.md
  modules/chemical_reactions/doc/content/source/actions/AddSecondarySpeciesAction.md
  modules/chemical_reactions/doc/content/source/kernels/DesorptionFromMatrix.md
  modules/chemical_reactions/doc/content/source/kernels/DesorptionToPorespace.md
  modules/chemical_reactions/doc/content/source/materials/LangmuirMaterial.md
  modules/chemical_reactions/doc/content/source/materials/MollifiedLangmuirMaterial.md
  modules/chemical_reactions/doc/content/syntax/ReactionNetwork/AqueousEquilibriumReactions/index.md
  modules/chemical_reactions/doc/content/syntax/ReactionNetwork/SolidKineticReactions/index.md
  modules/chemical_reactions/doc/content/syntax/ReactionNetwork/index.md
  modules/contact/doc/content/source/postprocessors/NumAugmentedLagrangeIterations.md
  modules/navier_stokes/doc/content/source/bcs/INSFEFluidEnergyBC.md
  modules/navier_stokes/doc/content/source/bcs/INSFEFluidEnergyDirichletBC.md
  modules/navier_stokes/doc/content/source/bcs/INSFEFluidMassBC.md
  modules/navier_stokes/doc/content/source/bcs/INSFEFluidMomentumBC.md
  modules/navier_stokes/doc/content/source/bcs/INSFEFluidWallMomentumBC.md
  modules/navier_stokes/doc/content/source/bcs/INSFEMomentumFreeSlipBC.md
  modules/peridynamics/doc/content/syntax/Modules/Peridynamics/index.md
  modules/porous_flow/doc/content/source/functions/MovingPlanarFront.md
  modules/porous_flow/doc/content/syntax/Modules/PorousFlow/BCs/index.md
  modules/porous_flow/doc/content/syntax/Modules/PorousFlow/index.md
  modules/porous_flow/doc/content/syntax/Modules/index.md
  modules/porous_flow/doc/content/syntax/PorousFlowBasicTHM/index.md
  modules/porous_flow/doc/content/syntax/PorousFlowFullySaturated/index.md
  modules/porous_flow/doc/content/syntax/PorousFlowUnsaturated/index.md
Labels: PR: Failed but allowed, PR: Ready for review/merge

#27050 Fixup CSV data reading, when data is organized in Voronoi partittions, to make it clearer
  framework/doc/content/source/functions/PiecewiseConstantFromCSV.md
  framework/doc/content/source/userobjects/PropertyReadFile.md
  framework/src/userobjects/PropertyReadFile.C
  test/tests/functions/piecewise_constant_from_csv/data_nearest.csv
  test/tests/functions/piecewise_constant_from_csv/piecewise_constant.i
Labels: PR: Failed but allowed, PR: Ready for review/merge

#27081 Let users use variables as coordinates to a function in an auxkernel
  framework/doc/content/source/auxkernels/FunctorCoordinatesFunctionAux.md
  framework/include/auxkernels/FunctorCoordinatesFunctionAux.h
  framework/src/auxkernels/FunctorCoordinatesFunctionAux.C
  test/tests/auxkernels/functor_coordinates_function_aux/gold/test_out.e
  test/tests/auxkernels/functor_coordinates_function_aux/test.i
  test/tests/auxkernels/functor_coordinates_function_aux/tests
Labels: PR: Ready for review/merge

#27224 Replace no_backup_and_restore with no_restore
  framework/include/multiapps/FullSolveMultiApp.h
  framework/src/multiapps/FullSolveMultiApp.C
  modules/stochastic_tools/src/actions/ParameterStudyAction.C
  modules/stochastic_tools/test/tests/actions/parameter_study_action/tests
  modules/stochastic_tools/test/tests/auxkernels/surrogate_aux/surrogate.i
  test/tests/multiapps/picard/picard_custom_postprocessor.i
  test/tests/multiapps/picard/pseudo_transient_picard_parent.i
  test/tests/multiapps/picard/steady_custom_picard_parent.i
  test/tests/multiapps/picard/steady_picard_parent.i
  test/tests/multiapps/picard_multilevel/fullsolve_multilevel/parent.i
Labels: PR: Failed but allowed, PR: Ready for review/merge

#27386 Changed default value of 'normal_tol' in SideSetsFromNormalsGenerator
  framework/src/meshgenerators/SideSetsFromNormalsGenerator.C
  modules/porous_flow/examples/groundwater/ex02_steady_state.i
Labels: PR: Failed but allowed

#27332 Rbg surface num
  framework/include/utils/MooseMeshUtils.h
  framework/src/meshgenerators/RenameBoundaryGenerator.C
  framework/src/utils/MooseMeshUtils.C
  test/tests/meshgenerators/polyline_mesh_generator/tests
  test/tests/meshgenerators/rename_boundary_generator/tests
  test/tests/mortar/convergence-studies/gap-conductance/gap-conductance.i
  test/tests/mortar/convergence-studies/solution-continuity/continuity.i
Labels: PR: Failed but allowed

#27448 Adding functors to NSFVAction
  modules/navier_stokes/include/base/NSFVBase.h
Labels: PR: Failed but allowed

#27454 Update and improve minimum system requirements
  framework/doc/content/sqa/minimum_requirements.md
  framework/doc/packages_config.yml
  modules/doc/content/getting_started/installation/index_content.md
Labels: PR: Failed but allowed

#27067 Add pre-make helper for checking dependencies
  framework/app.mk
  framework/build.mk
  framework/moose.mk
  scripts/premake.py
  scripts/tests/test_premake.py
  scripts/tests/tests
Labels: PR: Ready for review/merge

#27371 Supply Euler angles from aux-variables for CP
  modules/solid_mechanics/include/materials/crystal_plasticity/ComputeElasticityTensorCP.h
  modules/solid_mechanics/src/materials/crystal_plasticity/ComputeElasticityTensorCP.C
  modules/solid_mechanics/test/tests/crystal_plasticity/euler_angles/euler_ang_file.txt
  modules/solid_mechanics/test/tests/crystal_plasticity/euler_angles/euler_angle_auxvar.i
  modules/solid_mechanics/test/tests/crystal_plasticity/euler_angles/euler_angle_conflict.i
  modules/solid_mechanics/test/tests/crystal_plasticity/euler_angles/gold/euler_angle_auxvar_out.csv
  modules/solid_mechanics/test/tests/crystal_plasticity/euler_angles/input_slip_sys.txt
  modules/solid_mechanics/test/tests/crystal_plasticity/euler_angles/tests
Labels: PR: Failed but allowed

#27472 FlexiblePatternGenerator: add options to delete external boundaries f…
  modules/reactor/include/meshgenerators/FlexiblePatternGenerator.h
  modules/reactor/src/meshgenerators/FlexiblePatternGenerator.C
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/double_ext_boundary.i
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/gold/double_ext_boundary_in.e
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/tests
Labels: PR: Failed but allowed

#27420 add_subdomain_names
  framework/doc/content/source/mesh/MooseMesh.md
  framework/src/mesh/MooseMesh.C
  test/tests/mesh/add_subdomain_ids/tests
  unit/src/MooseServerTest.C
Labels: PR: Failed but allowed

#27481 Allow use of FDP with DIRK time integration
  framework/include/systems/NonlinearSystem.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/systems/NonlinearSystem.C
  framework/src/timeintegrators/LStableDirk2.C
  framework/src/timeintegrators/LStableDirk3.C
  framework/src/timeintegrators/LStableDirk4.C
  test/tests/time_integrators/dirk/tests
Labels: PR: Failed but allowed

#27366 Disallow all plane formulations with new lagrangian kernels in SM physics
  modules/solid_mechanics/src/physics/QuasiStaticSolidMechanicsPhysics.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#27442 Material suffix
  framework/include/functormaterials/FunctorMaterial.h
  test/tests/functormaterials/with_suffix/functor_material.i
  test/tests/functormaterials/with_suffix/gold/functor_material_out.csv
  test/tests/functormaterials/with_suffix/tests
Labels: PR: Failed but allowed

#27173 Add example input file for isothermal version of Echebarria solidification model
  modules/phase_field/examples/anisotropic_interfaces/echebarria_iso.i
  modules/phase_field/examples/anisotropic_interfaces/tests
Labels: PR: Failed but allowed
