Repository idaholab/moose, pull requests merged in 2024-02, with the labels that each got.

#26679 Make January 2024 news public
  modules/doc/content/newsletter/2024/2024_01.md
  modules/doc/content/newsletter/2024/2024_02.md
  modules/doc/content/newsletter/index.md
Labels: PR: Failed but allowed

#26720 Stage 1 of active material property refactor
  framework/include/loops/ComputeFVFluxThread.h
  framework/include/materials/InterfaceMaterial.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/include/problems/FEProblemBase.h
  framework/include/problems/SubProblem.h
  framework/include/utils/MortarUtils.h
  framework/include/vectorpostprocessors/LineMaterialSamplerBase.h
  framework/include/warehouses/MooseObjectWarehouseBase.h
  framework/src/auxkernels/NodalPatchRecovery.C
  framework/src/loops/ComputeDiracThread.C
  framework/src/loops/ComputeElemAuxBcsThread.C
  framework/src/loops/ComputeElemAuxVarsThread.C
  framework/src/loops/ComputeIndicatorThread.C
  framework/src/loops/ComputeUserObjectsThread.C
  framework/src/loops/NonlinearThread.C
  framework/src/problems/FEProblemBase.C
  framework/src/problems/SubProblem.C
  modules/ray_tracing/src/userobjects/RayTracingStudy.C
  modules/thermal_hydraulics/include/vectorpostprocessors/Sampler1DBase.h
  modules/thermal_hydraulics/src/vectorpostprocessors/Sampler1DReal.C
Labels: C: Framework, PR: Failed but allowed

#26731 Test fixes for two phase mixture model round two
  modules/contact/test/tests/pdass_problems/tests
  modules/navier_stokes/examples/laser-welding/tests
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/segregated/3d/tests
  modules/navier_stokes/test/tests/finite_volume/ins/lid-driven/segregated/tests
  modules/navier_stokes/test/tests/finite_volume/materials/ergun/tests
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/segregated/tests
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/tests
  modules/stochastic_tools/examples/paper/tests
  modules/tensor_mechanics/test/tests/t_stress/tests
Labels: PR: Failed but allowed

#26749 Create NonlinearSolveObject
  framework/include/executioners/FEProblemSolve.h
  framework/include/executioners/NonlinearSolveObject.h
  framework/src/executioners/FEProblemSolve.C
  framework/src/executioners/NonlinearSolveObject.C
Labels: PR: Failed but allowed

#26474 Add application block
  framework/doc/content/source/actions/CreateApplicationBlockAction.md
  framework/doc/content/syntax/Application/index.md
  framework/include/actions/CreateApplicationBlockAction.h
  framework/include/base/MooseApp.h
  framework/include/base/MooseMain.h
  framework/include/parser/Parser.h
  framework/src/actions/CreateApplicationBlockAction.C
  framework/src/base/AppFactory.C
  framework/src/base/Moose.C
  framework/src/base/MooseApp.C
  framework/src/base/MooseMain.C
  framework/src/multiapps/MultiApp.C
  framework/src/parser/Parser.C
  modules/combined/test/src/base/CombinedTestApp.C
  modules/combined/test/tests/application_block_check/application_block.i
  modules/combined/test/tests/application_block_check/tests
  modules/doc/config.yml
  test/tests/multiapps/application_block_multiapps/application_block_parent.i
  test/tests/multiapps/application_block_multiapps/application_block_sub.i
  test/tests/multiapps/application_block_multiapps/application_block_unregistered_sub.i
  test/tests/multiapps/application_block_multiapps/tests
Labels: PR: Failed but allowed

#26696 Add a function in material base class to check whether a property is active
  framework/doc/content/syntax/Materials/index.md
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialWarehouse.h
  framework/include/problems/FEProblemBase.h
  framework/src/loops/ComputeElemAuxVarsThread.C
  framework/src/loops/ComputeIndicatorThread.C
  framework/src/loops/ComputeMarkerThread.C
  framework/src/loops/ComputeUserObjectsThread.C
  framework/src/loops/NonlinearThread.C
  framework/src/materials/Material.C
  framework/src/materials/MaterialBase.C
  framework/src/materials/MaterialWarehouse.C
  framework/src/problems/FEProblemBase.C
  modules/ray_tracing/src/userobjects/RayTracingStudy.C
  test/include/auxkernels/CheckActiveMatProp.h
  test/include/materials/ActiveGenericConstantMaterial.h
  test/include/problems/CheckActiveMatPropProblem.h
  test/src/auxkernels/CheckActiveMatProp.C
  test/src/materials/ActiveGenericConstantMaterial.C
  test/src/problems/CheckActiveMatPropProblem.C
  test/tests/materials/active_material_props/check_active_props.i
  test/tests/materials/active_material_props/gold/check_active_props_out.e
  test/tests/materials/active_material_props/tests
Labels: PR: Failed but allowed

#26723 Old older properties and `x`,`y`,`z`,`t`,`dt` in parsed materials
  framework/doc/content/source/materials/DerivativeParsedMaterial.md
  framework/include/base/MooseBase.h
  framework/include/base/MooseBaseParameterInterface.h
  framework/include/base/MooseObject.h
  framework/include/bcs/ADDirichletBCBaseTempl.h
  framework/include/bcs/GenericIntegratedBC.h
  framework/include/bcs/GenericNodalBC.h
  framework/include/interfacekernels/GenericInterfaceKernel.h
  framework/include/kernels/GenericKernel.h
  framework/include/kernels/GenericKernelScalar.h
  framework/include/materials/FunctionMaterialBase.h
  framework/include/materials/Material.h
  framework/include/materials/MaterialBase.h
  framework/include/materials/MaterialPropertyInterface.h
  framework/include/materials/ParsedMaterialHelper.h
  framework/include/userobjects/NearestPointBase.h
  framework/include/utils/FunctionMaterialPropertyDescriptor.h
  framework/include/utils/MultiMooseEnum.h
  framework/src/materials/DerivativeFunctionMaterialBase.C
  framework/src/materials/DerivativeParsedMaterialHelper.C
  framework/src/materials/ParsedMaterialHelper.C
  framework/src/utils/FunctionMaterialPropertyDescriptor.C
  modules/navier_stokes/include/fvbcs/INSFVOutletPressureBC.h
  modules/ray_tracing/include/raykernels/GenericRayKernel.h
  modules/tensor_mechanics/include/bcs/Pressure.h
  modules/tensor_mechanics/include/bcs/Torque.h
  modules/tensor_mechanics/include/kernels/Gravity.h
  modules/tensor_mechanics/include/materials/HillCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/HillElastoPlasticityStressUpdate.h
  modules/tensor_mechanics/include/materials/LAROMANCEStressUpdateBase.h
  modules/tensor_mechanics/include/materials/PowerLawCreepStressUpdate.h
  modules/tensor_mechanics/include/materials/ViscoplasticityStressUpdateBase.h
  test/tests/materials/derivative_material_interface/construction_order.i
  test/tests/materials/derivative_material_interface/extra_symbols.i
  test/tests/materials/derivative_material_interface/gold/extra_symbols_out.e
  test/tests/materials/derivative_material_interface/gold/old.csv
  test/tests/materials/derivative_material_interface/gold/older.csv
  test/tests/materials/derivative_material_interface/old_older.i
  test/tests/materials/derivative_material_interface/tests
Labels: PR: Failed but allowed

#26725 Assorted fixes and improvements
  framework/app.mk
  framework/doc/content/source/base/Assembly.md
  framework/doc/content/source/mesh/FileMesh.md
  framework/doc/content/source/mesh/MooseMesh.md
  framework/doc/content/source/meshgenerators/FileMeshGenerator.md
  framework/doc/content/source/meshgenerators/RefineBlockGenerator.md
  framework/doc/content/source/meshgenerators/RefineSidesetGenerator.md
  framework/doc/content/source/partitioner/LibmeshPartitioner.md
  framework/doc/content/source/systems/NonlinearSystem.md
  framework/doc/content/source/userobjects/ElementQualityChecker.md
  framework/doc/content/syntax/Executioner/Quadrature/index.md
  framework/moose.mk
  framework/src/mesh/GeneratedMesh.C
  framework/src/meshgenerators/GeneratedMeshGenerator.C
  modules/doc/content/getting_started/installation/install_libtorch.md
  modules/doc/content/getting_started/installation/msys2.md
  modules/doc/content/help/faq/libmesh_issues.md
  modules/doc/content/newsletter/2018/2018_08.md
  modules/electromagnetics/doc/content/source/auxkernels/CurrentDensity.md
  modules/heat_transfer/doc/content/source/meshgenerators/PatchSidesetGenerator.md
  modules/tensor_mechanics/doc/content/modules/tensor_mechanics/examples/cframe_iga.md
  tutorials/darcy_thermo_mech/doc/content/workshop/infrastructure/troubleshooting.md
Labels: PR: Failed but allowed

#26743 Small PIDTransientControl enhancement
  framework/include/controls/PIDTransientControl.h
  framework/include/executioners/Executioner.h
  framework/src/controls/PIDTransientControl.C
  test/tests/controls/pid_control/gold/min_max_limits.csv
  test/tests/controls/pid_control/pid_control.i
  test/tests/controls/pid_control/tests
Labels: PR: Failed but allowed

#26754 Added standard functor description to functor parameters
  framework/include/utils/InputParameters.h
  framework/src/utils/InputParameters.C
Labels: PR: Failed but allowed

#26764 Add MooseEnum support to CLI params, improve CLI params
  framework/include/parser/CommandLine.h
  framework/include/utils/InputParameters.h
  framework/src/base/MooseApp.C
  framework/src/parser/CommandLine.C
  framework/src/utils/InputParameters.C
  unit/src/CommandLine.C
Labels: PR: Failed but allowed

#26781 Fix makefile for downstream apps with additional dependencies
  framework/app.mk
Labels: PR: Failed but allowed

#26777 Improve Background Block ID Name for FlexiblePatternGenerator
  framework/src/meshgenerators/XYDelaunayGenerator.C
  modules/reactor/doc/content/source/meshgenerators/FlexiblePatternGenerator.md
  modules/reactor/include/meshgenerators/FlexiblePatternGenerator.h
  modules/reactor/src/meshgenerators/FlexiblePatternGenerator.C
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/single_hex_pattern.i
  modules/reactor/test/tests/meshgenerators/flexible_pattern_generator/tests
  test/tests/meshgenerators/xy_delaunay_generator/tests
  test/tests/meshgenerators/xy_delaunay_generator/xydelaunay_stitching.i
Labels: PR: Failed but allowed

#26786 Revert more makefile change
  framework/app.mk
  framework/moose.mk
Labels: PR: Failed but allowed

#26774 extending MooseVariableFV to face and qp for transient two-phase flow…
  framework/include/base/MooseFunctor.h
  framework/include/utils/MathFVUtils.h
  framework/include/utils/PiecewiseByBlockLambdaFunctor.h
  framework/include/variables/MooseVariableFE.h
  framework/include/variables/MooseVariableFV.h
  framework/src/variables/MooseVariableFV.C
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/channel-drift-flux-transient.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-advection-slip_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-drift-flux-transient_CSV.csv
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/gold/channel-drift-flux_out.e
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/tests
Labels: C: Framework, C: Modules/Navier Stokes

#26793 Fix broken residual link
  framework/doc/content/source/postprocessors/Residual.md
Labels: C: Framework, PR: Failed but allowed

#26445 Mesh coarsening generator
  framework/doc/content/source/meshgenerators/CoarsenBlockGenerator.md
  framework/include/meshgenerators/CoarsenBlockGenerator.h
  framework/include/meshgenerators/MeshDiagnosticsGenerator.h
  framework/include/utils/MeshBaseDiagnosticsUtils.h
  framework/include/utils/MeshCoarseningUtils.h
  framework/src/meshgenerators/CoarsenBlockGenerator.C
  framework/src/meshgenerators/MeshDiagnosticsGenerator.C
  framework/src/utils/MeshBaseDiagnosticsUtils.C
  framework/src/utils/MeshCoarseningUtils.C
  test/tests/meshgenerators/coarsen_block_generator/coarsen_hex.i
  test/tests/meshgenerators/coarsen_block_generator/coarsen_hex_multi.i
  test/tests/meshgenerators/coarsen_block_generator/coarsen_quad.i
  test/tests/meshgenerators/coarsen_block_generator/coarsen_quad_multi.i
  test/tests/meshgenerators/coarsen_block_generator/gold/coarsen_hex_in.e
  test/tests/meshgenerators/coarsen_block_generator/gold/coarsen_hex_multi_in.e
  test/tests/meshgenerators/coarsen_block_generator/gold/coarsen_quad_in.e
  test/tests/meshgenerators/coarsen_block_generator/gold/coarsen_quad_multi_in.e
  test/tests/meshgenerators/coarsen_block_generator/tests
Labels: PR: Failed but allowed

#26811 Added citation info for new THM paper
  modules/doc/content/citing.md
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/index.md
Labels: PR: Failed but allowed

#26817 Add option to avoid reading the file on construction
  framework/include/userobjects/PropertyReadFile.h
  framework/src/userobjects/PropertyReadFile.C
Labels: PR: Failed but allowed

#26861 Restrict tests that cant compile their AD parsed function currently
  modules/phase_field/test/tests/GrandPotentialPFM/tests
  modules/phase_field/test/tests/phase_field_kernels/tests
Labels: PR: Failed but allowed

#26850 Expanding radiative heat flux BC for FV
  modules/heat_transfer/include/fvbcs/FVRadiativeHeatFluxBCBase.h
  modules/heat_transfer/src/fvbcs/FVRadiativeHeatFluxBCBase.C
Labels: PR: Failed but allowed

#26859 Refactoring reporting ID capability in patterned mesh generators to support multiple ID assignment
  modules/reactor/doc/content/source/meshgenerators/PatternedCartesianMeshGenerator.md
  modules/reactor/doc/content/source/meshgenerators/PatternedHexMeshGenerator.md
  modules/reactor/include/meshgenerators/PatternedCartesianMeshGenerator.h
  modules/reactor/include/meshgenerators/PatternedHexMeshGenerator.h
  modules/reactor/src/meshgenerators/AssemblyMeshGenerator.C
  modules/reactor/src/meshgenerators/CoreMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedCartesianMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedHexMeshGenerator.C
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/gold/patterned_cartesian_assembly_reporting_multi_id_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/patterned_cartesian_assembly_reporting_multi_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/cartesian_id/tests
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/assembly_reporting_multi_id.i
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/gold/assembly_reporting_multi_id_out.e
  modules/reactor/test/tests/meshgenerators/reporting_id/hexagonal_id/tests
Labels: PR: Failed but allowed

#26873 Fix indexing issue in `ThermochimicaData` UO
  modules/chemical_reactions/src/userobjects/ThermochimicaData.C
Labels: PR: Failed but allowed, PR: Auto Merge

#23222 Adding UC thermal properties in solid_properties module
  modules/solid_properties/doc/content/bib/solid_properties.bib
  modules/solid_properties/doc/content/source/solidproperties/ThermalUCProperties.md
  modules/solid_properties/include/solidproperties/SolidProperties.h
  modules/solid_properties/include/solidproperties/ThermalUCProperties.h
  modules/solid_properties/src/solidproperties/SolidProperties.C
  modules/solid_properties/src/solidproperties/ThermalUCProperties.C
  modules/solid_properties/unit/include/ThermalUCPropertiesTest.h
  modules/solid_properties/unit/src/ThermalUCPropertiesTest.C
Labels: PR: Failed but allowed

#26648 Add spheat and density deriv to heat conduction
  modules/heat_transfer/include/kernels/HeatConductionTimeDerivative.h
  modules/heat_transfer/include/materials/HeatConductionMaterial.h
  modules/heat_transfer/src/kernels/HeatConductionTimeDerivative.C
  modules/heat_transfer/src/materials/HeatConductionMaterial.C
  modules/heat_transfer/test/tests/transient_heat/gold/transient_heat_derivatives_out.csv
  modules/heat_transfer/test/tests/transient_heat/tests
  modules/heat_transfer/test/tests/transient_heat/transient_heat_derivatives.i
Labels: PR: Failed but allowed

#26903 Fix missing cut plane in CutMeshByPlaneGenerator
  framework/src/meshgenerators/CutMeshByPlaneGenerator.C
  test/tests/meshgenerators/cut_mesh_by_plane_generator/gold/simple_hex_cut_aligned_in.e
  test/tests/meshgenerators/cut_mesh_by_plane_generator/tests
Labels: C: Framework, C: Meshing

#26906 Get variable dependencies of discrete materials for stateful init
  framework/src/loops/ComputeMaterialsObjectThread.C
Labels: C: Framework

#26927 Remove unused VCP contact tests
  modules/contact/test/tests/mortar_cartesian_lms/cylinder_friction_cartesian_pg_vcp.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_1st_order_constraint_lm_xy_friction_pg_vcp.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_1st_order_constraint_lm_xy_pg.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_1st_order_constraint_lm_xy_pg_vcp.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_1st_order_constraint_lm_xy_vcp.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD8_constraint_lm_xy.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD8_constraint_lm_xy_pg.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD8_constraint_lm_xy_pg_vcp.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD8_constraint_lm_xy_vcp.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD9_constraint_lm_xy.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD9_constraint_lm_xy_pg.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD9_constraint_lm_xy_pg_vcp.i
  modules/contact/test/tests/mortar_cartesian_lms/two_block_QUAD9_constraint_lm_xy_vcp.i
Labels: C: Modules/Contact
