Repository idaholab/moose, pull requests merged in 2024-10, with the labels that each got.

#28744 Fix block restricted adaptivity inconsistency
  framework/src/indicators/GradientJumpIndicator.C
  framework/src/indicators/InternalSideIndicator.C
  test/tests/adaptivity/block_restriction/gold/test_out.e-s002
  test/tests/adaptivity/block_restriction/test.i
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28708 Add some checks in reactor module for bad subdomain / boundaries inputs
  modules/reactor/src/meshgenerators/AzimuthalBlockSplitGenerator.C
  modules/reactor/src/meshgenerators/DepletionIDGenerator.C
  modules/reactor/src/meshgenerators/PatternedPolygonPeripheralModifierBase.C
  modules/reactor/src/meshgenerators/PeripheralRingMeshGenerator.C
  modules/reactor/src/meshgenerators/RevolveGenerator.C
  modules/reactor/src/meshgenerators/SubdomainExtraElementIDGenerator.C
  modules/reactor/test/tests/meshgenerators/peripheral_ring_mesh_generator/tests
  modules/reactor/test/tests/meshgenerators/revolve_generator/tests
  modules/reactor/test/tests/meshgenerators/subdomain_extra_element_id_generator/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28738 Add pressure skewness correction in RC interpolation
  modules/navier_stokes/include/userobjects/INSFVRhieChowInterpolator.h
  modules/navier_stokes/src/userobjects/INSFVRhieChowInterpolator.C
Labels: PR: Ready for review/merge

#28511 Make MOOSE folder resistent to folder-wide whitespace trimming
  scripts/delete_trailing_whitespace.sh
Labels: PR: Ready for review/merge

#28747 Update seacas to 2024-08-15
  conda/seacas/arm-kern-return.patch
  conda/seacas/conda_build_config.yaml
  conda/seacas/meta.yaml
Labels: PR: Failed but allowed

#28786 Add `--project-suffix` to exists, def, pull, build, uri
  scripts/apptainer_generator.py
Labels: PR: Failed but allowed, PR: Ready for review/merge

#27352 Add method for setting input parameter unit for purposes of documentation
  framework/doc/content/css/moose.css
  framework/include/utils/InputParameters.h
  framework/src/outputs/formatters/JsonInputFileFormatter.C
  framework/src/outputs/formatters/YAMLFormatter.C
  framework/src/utils/InputParameters.C
  framework/src/utils/JsonSyntaxTree.C
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/test/extensions/test_appsyntax.py
  scripts/stork.sh
Labels: T: task, C: Documentation, PR: Failed but allowed

#28713 Fix distributed threaded NS issues
  framework/src/systems/SystemBase.C
  framework/src/variables/MooseVariableFV.C
  modules/navier_stokes/src/base/NavierStokesMethods.C
Labels: PR: Ready for review/merge

#28732 Added `Function::timeIntegral(t1, t2, p)`
  framework/doc/content/syntax/Functions/index.md
  framework/include/functions/ConstantFunction.h
  framework/include/functions/Function.h
  framework/include/functions/PiecewiseLinearBase.h
  framework/include/utils/LinearInterpolation.h
  framework/src/functions/ConstantFunction.C
  framework/src/functions/Function.C
  framework/src/functions/PiecewiseLinearBase.C
  framework/src/utils/LinearInterpolation.C
  modules/solid_properties/include/solidproperties/ThermalFunctionSolidProperties.h
  modules/solid_properties/src/solidproperties/ThermalFunctionSolidProperties.C
  modules/solid_properties/unit/include/ThermalFunctionSolidPropertiesTest.h
  modules/solid_properties/unit/src/ThermalFunctionSolidPropertiesTest.C
  unit/include/ConstantFunctionTest.h
  unit/include/FunctionTestUtils.h
  unit/include/PiecewiseLinearTest.h
  unit/src/ConstantFunctionTest.C
  unit/src/FunctionTestUtils.C
  unit/src/PiecewiseLinearTest.C
Labels: PR: Failed but allowed

#28780 Additional items to heat conduction & diffusion physics
  framework/include/actioncomponents/PhysicsComponentBase.h
  framework/include/actions/ActionWarehouse.h
  framework/include/physics/DiffusionPhysicsBase.h
  framework/src/physics/DiffusionCG.C
  framework/src/physics/DiffusionPhysicsBase.C
  modules/heat_transfer/doc/content/source/physics/HeatConductionPhysicsBase.md
  modules/heat_transfer/include/bcs/ADConvectiveHeatFluxBC.h
  modules/heat_transfer/include/physics/HeatConductionCG.h
  modules/heat_transfer/include/physics/HeatConductionFV.h
  modules/heat_transfer/include/physics/HeatConductionPhysicsBase.h
  modules/heat_transfer/src/bcs/ADConvectiveHeatFluxBC.C
  modules/heat_transfer/src/physics/HeatConductionCG.C
  modules/heat_transfer/src/physics/HeatConductionFV.C
  modules/heat_transfer/src/physics/HeatConductionPhysicsBase.C
  modules/heat_transfer/test/tests/physics/gold/test_cg_convective_bc_out.e
  modules/heat_transfer/test/tests/physics/gold/test_cg_functor_hs_out.e
  modules/heat_transfer/test/tests/physics/gold/test_fv_convective_bc_out.e
  modules/heat_transfer/test/tests/physics/gold/test_fv_functor_hs_out.e
  modules/heat_transfer/test/tests/physics/test_cg_convective_bc.i
  modules/heat_transfer/test/tests/physics/test_fv_convective_bc.i
  modules/heat_transfer/test/tests/physics/tests
  modules/navier_stokes/include/physics/PNSFVSolidHeatTransferPhysics.h
  modules/navier_stokes/src/physics/PNSFVSolidHeatTransferPhysics.C
  modules/scalar_transport/include/physics/MultiSpeciesDiffusionPhysicsBase.h
  modules/scalar_transport/src/physics/MultiSpeciesDiffusionCG.C
  modules/scalar_transport/src/physics/MultiSpeciesDiffusionPhysicsBase.C
  modules/scalar_transport/test/tests/physics/restart/gold/from_file.csv
  modules/scalar_transport/test/tests/physics/restart/gold/restart_user_ics.csv
  modules/scalar_transport/test/tests/physics/restart/gold/user_ics.csv
  modules/scalar_transport/test/tests/physics/restart/test_cg.i
  modules/scalar_transport/test/tests/physics/restart/tests
  modules/scalar_transport/test/tests/physics/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28673 Material property support for ParsedAux
  framework/doc/content/source/auxkernels/ParsedAux.md
  framework/include/auxkernels/ParsedAux.h
  framework/src/auxkernels/ParsedAux.C
  test/tests/auxkernels/parsed_aux/gold/parsed_aux_mat_test_out.e
  test/tests/auxkernels/parsed_aux/parsed_aux_mat_test.i
  test/tests/auxkernels/parsed_aux/tests
Labels: PR: Ready for review/merge

#28770 Registered new `ExecFlagType`: `NONLINEAR_CONVERGENCE`
  framework/doc/content/source/interfaces/SetupInterface.md
  framework/doc/content/source/postprocessors/Residual.md
  framework/include/base/Moose.h
  framework/src/base/Moose.C
  framework/src/postprocessors/Residual.C
  framework/src/utils/ExecFlagEnum.C
  framework/src/utils/PetscSupport.C
  test/tests/postprocessors/residual/current_residual.i
  test/tests/postprocessors/residual/gold/current_residual_out.csv
  test/tests/postprocessors/residual/tests
  unit/src/MooseEnumTest.C
Labels: PR: Failed but allowed

#28381 Couple changes to support GPUs
  framework/include/problems/FEProblemBase.h
  framework/include/utils/PetscSupport.h
  framework/src/problems/FEProblemBase.C
  framework/src/utils/PetscSupport.C
  framework/src/utils/SlepcSupport.C
  test/tests/misc/respect_petsc_options/gold/test_out.csv
  test/tests/misc/respect_petsc_options/test.i
  test/tests/misc/respect_petsc_options/tests
Labels: PR: Failed but allowed

#28810 Fix bounds and initial conditions input parameter
  modules/optimization/doc/content/source/optimizationreporters/ParameterMeshOptimization.md
  modules/optimization/examples/diffusion_reaction/optimize.i
  modules/optimization/include/optimizationreporters/OptimizationReporterBase.h
  modules/optimization/include/optimizationreporters/ParameterMeshOptimization.h
  modules/optimization/src/optimizationreporters/GeneralOptimization.C
  modules/optimization/src/optimizationreporters/OptimizationReporter.C
  modules/optimization/src/optimizationreporters/OptimizationReporterBase.C
  modules/optimization/src/optimizationreporters/ParameterMeshOptimization.C
  modules/optimization/test/tests/optimizationreporter/mesh_source/main_linearRestart.i
  modules/optimization/test/tests/optimizationreporter/mesh_source/tests
  modules/optimization/test/tests/optimizationreporter/parameter_mesh_base/tests
Labels: PR: Failed but allowed

#28802 Update CrFe.i
  modules/phase_field/examples/slkks/CrFe.i
  modules/phase_field/examples/slkks/CrFe_sigma.i
  modules/phase_field/examples/slkks/tests
Labels: PR: Failed but allowed

#28840 Add option to throw an exception in nan interface
  modules/fluid_properties/doc/content/source/interfaces/NaNInterface.md
  modules/fluid_properties/include/interfaces/NaNInterface.h
  modules/fluid_properties/src/interfaces/NaNInterface.C
  modules/fluid_properties/test/tests/interfaces/nan_interface/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28866 Turn off legacy initial residual evaluation behavior for darcy flow tutorial
  tutorials/darcy_thermo_mech/step01_diffusion/src/base/DarcyThermoMechApp.C
  tutorials/darcy_thermo_mech/step11_action/src/base/DarcyThermoMechApp.C
Labels: PR: Auto Merge

#28864 Patched THM DG kernel for upcoming normal vector changes
  modules/thermal_hydraulics/src/bcs/ADBoundaryFlux3EqnBC.C
  modules/thermal_hydraulics/src/bcs/BoundaryFlux3EqnBC.C
  modules/thermal_hydraulics/src/dgkernels/ADNumericalFlux3EqnDGKernel.C
  modules/thermal_hydraulics/src/dgkernels/NumericalFlux3EqnDGKernel.C
  modules/thermal_hydraulics/src/materials/DirectionMaterial.C
  modules/thermal_hydraulics/src/userobjects/ADBoundaryFlux3EqnGhostBase.C
Labels: PR: Failed but allowed

#28773 Add capabilities to report the integrals of FVFluxBCs.
  framework/doc/content/source/postprocessors/SideFVFluxBCIntegral.md
  framework/include/fvbcs/FVFluxBC.h
  framework/include/postprocessors/SideFVFluxBCIntegral.h
  framework/src/fvbcs/FVFluxBC.C
  framework/src/postprocessors/SideFVFluxBCIntegral.C
  test/tests/postprocessors/fvfluxbc_integral/fvfluxbc_integral.i
  test/tests/postprocessors/fvfluxbc_integral/gold/fvfluxbc_integral_out.csv
  test/tests/postprocessors/fvfluxbc_integral/tests
Labels: PR: Failed but allowed

#28853 Add a few parameter groups
  framework/src/executioners/FEProblemSolve.C
  framework/src/problems/EigenProblem.C
  framework/src/problems/FEProblemBase.C
  framework/src/utils/SlepcSupport.C
  modules/heat_transfer/src/actions/MortarGapHeatTransferAction.C
  modules/heat_transfer/src/actions/ThermalContactAction.C
  modules/heat_transfer/src/constraints/ModularGapConductanceConstraint.C
  modules/heat_transfer/src/materials/GapConductance.C
  modules/heat_transfer/src/materials/GapConductanceConstant.C
  modules/heat_transfer/src/userobjects/GapFluxModelConduction.C
  modules/heat_transfer/src/userobjects/GapFluxModelConductionBase.C
  modules/heat_transfer/src/userobjects/GapFluxModelRadiationBase.C
Labels: PR: Ready for review/merge

#28688 Add code, tests and documentation for combined hardening model
  modules/solid_mechanics/doc/content/bib/solid_mechanics.bib
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/1d_ratcheting_non_linear_kinematic_load_controlled.png
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/linear_kin_nonsymmetric_load_controlled.png
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/linear_kin_nonsymmetric_strain_controlled.png
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/linear_kin_symmetric_strain_controlled.png
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/non_linear_combined_symmetric_strain_controlled.png
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/non_linear_isotropic_symmetric_strain_controlled.png
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/non_linear_kinematic_nonsymmetric_strain_controlled.png
  modules/solid_mechanics/doc/content/media/solid_mechanics/rate_independent_cyclic_hardening/non_linear_kinematic_symmetric_strain_controlled.png
  modules/solid_mechanics/doc/content/source/materials/CombinedNonlinearHardeningPlasticity.md
  modules/solid_mechanics/include/materials/CombinedNonlinearHardeningPlasticity.h
  modules/solid_mechanics/include/materials/RadialReturnBackstressStressUpdateBase.h
  modules/solid_mechanics/src/materials/CombinedNonlinearHardeningPlasticity.C
  modules/solid_mechanics/src/materials/RadialReturnBackstressStressUpdateBase.C
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/1D_ratcheting_nonlin_kinharden_stress_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/1x1x1cube.e
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/1D_ratcheting_nonlin_kinharden_stress_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/linear_kinharden_nonsymmetric_strain_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/linear_kinharden_nonsymmetric_stress_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/linear_kinharden_symmetric_strain_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/nonlin_isoharden_symmetric_strain_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/nonlin_isokinharden_symmetric_strain_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/nonlin_kinharden_nonsymmetric_strain_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/gold/nonlin_kinharden_symmetric_strain_controlled_out.csv
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/linear_kinharden_nonsymmetric_strain_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/linear_kinharden_nonsymmetric_stress_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/linear_kinharden_symmetric_strain_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/nonlin_isoharden_symmetric_strain_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/nonlin_isokinharden_symmetric_strain_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/nonlin_kinharden_nonsymmetric_strain_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/nonlin_kinharden_symmetric_strain_controlled.i
  modules/solid_mechanics/test/tests/rate_independent_cyclic_hardening/tests
Labels: PR: Failed but allowed, C: Modules/Solid Mechanics

#28804 Add ability to compute relative sensitivities directly in STM.
  modules/stochastic_tools/doc/content/source/samplers/DirectPerturbationSampler.md
  modules/stochastic_tools/include/reporters/DirectPerturbationReporter.h
  modules/stochastic_tools/include/samplers/DirectPerturbationSampler.h
  modules/stochastic_tools/src/reporters/DirectPerturbationReporter.C
  modules/stochastic_tools/src/samplers/DirectPerturbationSampler.C
  modules/stochastic_tools/test/tests/reporters/directperturbation/gold/relative_sens.json
  modules/stochastic_tools/test/tests/reporters/directperturbation/tests
  modules/stochastic_tools/test/tests/samplers/directperturbation/gold/directperturbation_out_data_0001.csv
  modules/stochastic_tools/test/tests/samplers/directperturbation/gold/dp_cd_3_data_0001.csv.0
Labels: PR: Failed but allowed
