Repository idaholab/moose, pull requests merged in 2025-06, with the labels that each got.

#30613 Remove `required_objects`, add capabilities verbosity, add scoped timers
  modules/fluid_properties/test/tests/saline/tests
  python/TestHarness/TestHarness.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/test_FailedJSON.py
  python/TestHarness/tests/test_RequiredObjects.py
  python/TestHarness/tests/tests
  python/TestHarness/util.py
  test/tests/test_harness/required_objects
Labels: PR: Ready for review/merge

#30597 Turn off search value diagnostics by default, turn on missed-value check by default in field transfers
  framework/src/transfers/MultiAppGeneralFieldTransfer.C
  test/tests/fvkernels/fv_simple_diffusion/neumann.i
  test/tests/transfers/general_field/nearest_node/mesh_division/main_match_division.i
  test/tests/transfers/general_field/shape_evaluation/between_siblings/main_between_multiapp.i
  test/tests/transfers/general_field/shape_evaluation/boundary/main.i
  test/tests/transfers/general_field/shape_evaluation/displaced/parent.i
  test/tests/transfers/general_field/shape_evaluation/duplicated_shape_evaluation_tests/fromsub.i
  test/tests/transfers/general_field/shape_evaluation/duplicated_shape_evaluation_tests/fromsub_source_displaced.i
  test/tests/transfers/general_field/shape_evaluation/duplicated_shape_evaluation_tests/fromsub_target_displaced.i
  test/tests/transfers/general_field/shape_evaluation/duplicated_shape_evaluation_tests/tests
  test/tests/transfers/general_field/shape_evaluation/mesh_division/main.i
  test/tests/transfers/general_field/shape_evaluation/mesh_division/main_match_subapps.i
  test/tests/transfers/general_field/shape_evaluation/regular/main.i
  test/tests/transfers/general_field/shape_evaluation/regular/main_array.i
  test/tests/transfers/general_field/shape_evaluation/subdomain/main.i
  test/tests/transfers/general_field/user_object/between_siblings/main_between_multiapp.i
  test/tests/transfers/general_field/user_object/boundary/main.i
  test/tests/transfers/general_field/user_object/duplicated_user_object_tests/3d_1d_parent.i
  test/tests/transfers/general_field/user_object/duplicated_user_object_tests/parent.i
  test/tests/transfers/general_field/user_object/duplicated_user_object_tests/tests
  test/tests/transfers/general_field/user_object/nearest_position/main_between_multiapp.i
  test/tests/transfers/general_field/user_object/regular/main.i
  test/tests/transfers/general_field/user_object/subdomain/main.i
  test/tests/transfers/multiapp_conservative_transfer/parent_conservative_transfer.i
  test/tests/transfers/multiapp_conservative_transfer/parent_nearest_point.i
  test/tests/transfers/multiapp_conservative_transfer/parent_power_density.i
  test/tests/transfers/multiapp_conservative_transfer/parent_userobject.i
  test/tests/transfers/multiapp_mesh_function_transfer/exec_on_mismatch.i
  test/tests/transfers/multiapp_mesh_function_transfer/fromsub.i
  test/tests/transfers/multiapp_mesh_function_transfer/fromsub_source_displaced.i
  test/tests/transfers/multiapp_mesh_function_transfer/fromsub_target_displaced.i
  test/tests/transfers/multiapp_mesh_function_transfer/tests
Labels: PR: Ready for review/merge

#30594 Make May 2025 news public, add June template
  modules/doc/content/newsletter/2025/2025_05.md
  modules/doc/content/newsletter/2025/2025_06.md
  modules/doc/content/newsletter/index.md
Labels: PR: Ready for review/merge

#30592 Add support for correlation-based convective BC to linear FV physics
  modules/navier_stokes/include/userobjects/RhieChowFaceFluxProvider.h
  modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
  modules/navier_stokes/src/base/NSFVBase.C
  modules/navier_stokes/src/functormaterials/LinearFVEnthalpyFunctorMaterial.C
  modules/navier_stokes/src/physics/WCNSLinearFVFluidHeatTransferPhysics.C
  modules/navier_stokes/src/postprocessors/VolumetricFlowRate.C
  modules/navier_stokes/test/tests/finite_volume/ins/cht/flow-around-square-linear-fluidonly-physics.i
  modules/navier_stokes/test/tests/finite_volume/ins/cht/gold/flow-around-square-linear-fluidonly-physics_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/cht/tests
Labels: PR: Ready for review/merge

#30679 Remove capabilities from tests that don't need it
  python/TestHarness/tests/TestHarnessTestCase.py
  python/TestHarness/tests/test_ExtraInfo.py
  python/TestHarness/tests/test_MinADSize.py
Labels: PR: Ready for review/merge

#30693 Do not use subprocess in test harness unit tests
  python/TestHarness/TestHarness.py
  python/TestHarness/tests/TestHarnessTestCase.py
  python/TestHarness/tests/test_Allocations.py
  python/TestHarness/tests/test_ArbitrarySpecFile.py
  python/TestHarness/tests/test_CSVDiffs.py
  python/TestHarness/tests/test_CSVValidationTester.py
  python/TestHarness/tests/test_CapturePerfGraph.py
  python/TestHarness/tests/test_CustomEval.py
  python/TestHarness/tests/test_Cyclic.py
  python/TestHarness/tests/test_Deleted.py
  python/TestHarness/tests/test_DependencySkip.py
  python/TestHarness/tests/test_Diff.py
  python/TestHarness/tests/test_DiffGold.py
  python/TestHarness/tests/test_DisplayRequired.py
  python/TestHarness/tests/test_DistributedMesh.py
  python/TestHarness/tests/test_DoLast.py
  python/TestHarness/tests/test_DryRun.py
  python/TestHarness/tests/test_Duplicate.py
  python/TestHarness/tests/test_Expect.py
  python/TestHarness/tests/test_ExtraInfo.py
  python/TestHarness/tests/test_FailedTests.py
  python/TestHarness/tests/test_Ignore.py
  python/TestHarness/tests/test_InstallType.py
  python/TestHarness/tests/test_LongRunning.py
  python/TestHarness/tests/test_LongestJobs.py
  python/TestHarness/tests/test_MachineType.py
  python/TestHarness/tests/test_MinADSize.py
  python/TestHarness/tests/test_MissingGold.py
  python/TestHarness/tests/test_ParserErrors.py
  python/TestHarness/tests/test_PythonVersion.py
  python/TestHarness/tests/test_RaceConditions.py
  python/TestHarness/tests/test_Recover.py
  python/TestHarness/tests/test_Replay.py
  python/TestHarness/tests/test_ReportSkipped.py
  python/TestHarness/tests/test_RequiredApps.py
  python/TestHarness/tests/test_SchemaDiff.py
  python/TestHarness/tests/test_ShouldExecute.py
  python/TestHarness/tests/test_SoftHeavyDependency.py
  python/TestHarness/tests/test_Syntax.py
  python/TestHarness/tests/test_Timeout.py
  python/TestHarness/tests/test_TrimOutput.py
  python/TestHarness/tests/test_UnknownParam.py
  python/TestHarness/tests/test_UnknownPrereq.py
  python/TestHarness/tests/test_UnreadableOutput.py
  python/TestHarness/tests/test_WorkingDirectory.py
  python/TestHarness/tests/test_WriteResults.py
Labels: PR: Ready for review/merge

#30534 Add routines to prevent adding ICs/time derivatives twice in Physics
  framework/include/interfaces/BlockRestrictable.h
  framework/include/materials/MaterialPropertyStorage.h
  framework/include/mesh/MooseMesh.h
  framework/include/physics/PhysicsBase.h
  framework/include/problems/FEProblemBase.h
  framework/include/utils/MooseMeshUtils.h
  framework/include/warehouses/MooseObjectWarehouseBase.h
  framework/src/auxkernels/AuxKernel.C
  framework/src/bcs/BoundaryCondition.C
  framework/src/constraints/Constraint.C
  framework/src/dampers/Damper.C
  framework/src/dgkernels/DGKernelBase.C
  framework/src/dirackernels/DiracKernelBase.C
  framework/src/functions/PiecewiseTabularBase.C
  framework/src/interfacekernels/InterfaceKernelBase.C
  framework/src/interfaces/BlockRestrictable.C
  framework/src/kernels/KernelBase.C
  framework/src/materials/MaterialPropertyStorage.C
  framework/src/mesh/MooseMesh.C
  framework/src/nodalkernels/NodalKernelBase.C
  framework/src/physics/DiffusionCG.C
  framework/src/physics/DiffusionFV.C
  framework/src/physics/DiffusionPhysicsBase.C
  framework/src/physics/PhysicsBase.C
  framework/src/problems/FEProblemBase.C
  framework/src/scalarkernels/ScalarKernelBase.C
  framework/src/splits/Split.C
  framework/src/systems/NonlinearSystemBase.C
  framework/src/utils/MooseMeshUtils.C
  modules/heat_transfer/src/physics/HeatConductionCG.C
  modules/heat_transfer/src/physics/HeatConductionFV.C
  modules/heat_transfer/src/physics/HeatConductionPhysicsBase.C
  modules/navier_stokes/src/physics/WCNSFVFlowPhysics.C
  modules/navier_stokes/src/physics/WCNSFVFlowPhysicsBase.C
  modules/navier_stokes/src/physics/WCNSFVFluidHeatTransferPhysics.C
  modules/navier_stokes/src/physics/WCNSFVFluidHeatTransferPhysicsBase.C
  modules/navier_stokes/src/physics/WCNSFVScalarTransportPhysics.C
  modules/navier_stokes/src/physics/WCNSFVTurbulencePhysics.C
  modules/navier_stokes/src/physics/WCNSLinearFVFlowPhysics.C
  modules/navier_stokes/src/physics/WCNSLinearFVFluidHeatTransferPhysics.C
  modules/navier_stokes/src/physics/WCNSLinearFVScalarTransportPhysics.C
  modules/navier_stokes/test/tests/finite_volume/ins/action/restart-block-restriction/tests
  modules/navier_stokes/test/tests/finite_volume/physics/restart/tests
  modules/scalar_transport/src/physics/MultiSpeciesDiffusionCG.C
  modules/scalar_transport/src/physics/MultiSpeciesDiffusionPhysicsBase.C
  modules/scalar_transport/test/tests/physics/restart/tests
  test/tests/physics/block_restriction/diffusion_cg.i
  test/tests/physics/block_restriction/gold/diffusion_cg_out_sample_0010.csv
  test/tests/physics/block_restriction/tests
Labels: PR: Ready for review/merge

#30719 Remove redundant build_side_ptr() proxy parameter
  framework/src/geomsearch/PenetrationInfo.C
  framework/src/geomsearch/PenetrationThread.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshgenerators/LowerDBlockFromSidesetGenerator.C
Labels: PR: Ready for review/merge

#30709 Re-enable \deprecated etc. Doxygen commands
  framework/doc/doxygen/Doxyfile
  framework/doc/doxygen/Doxyfile_libmesh
  framework/doc/doxygen/Doxyfile_timpi
Labels: PR: Ready for review/merge

#30318 Add block-restricted exodus output
  framework/include/outputs/Exodus.h
  framework/include/outputs/GMVOutput.h
  framework/include/outputs/SampledOutput.h
  framework/include/outputs/Tecplot.h
  framework/include/outputs/VTKOutput.h
  framework/include/outputs/XDA.h
  framework/src/actions/SetupDebugAction.C
  framework/src/outputs/Exodus.C
  framework/src/outputs/GMVOutput.C
  framework/src/outputs/OversampleOutput.C
  framework/src/outputs/SampledOutput.C
  framework/src/outputs/Tecplot.C
  framework/src/outputs/VTKOutput.C
  framework/src/outputs/XDA.C
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_change.i
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_change_restart1.i
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_change_restart2.i
  modules/combined/test/tests/adaptive_timestepping/adapt_tstep_function_force_step.i
  modules/phase_field/test/tests/KKS_system/kks_example.i
  modules/solid_mechanics/test/tests/anisotropic_patch/anisotropic_patch_test.i
  test/tests/meshgenerators/break_mesh_by_block_generator/hanging_nodes_parallel.i
  test/tests/misc/debug_pid_aux/debug_pid_aux.i
  test/tests/outputs/block_restricted/block.i
  test/tests/outputs/block_restricted/gold/block_elem_out.e
  test/tests/outputs/block_restricted/gold/block_out.e
  test/tests/outputs/block_restricted/tests
  test/tests/outputs/sampled_output/adapt.i
  test/tests/outputs/sampled_output/ex02_adapt.i
  test/tests/outputs/sampled_output/ex02_oversample.i
  test/tests/outputs/sampled_output/gold/adapt_out.e-s003
  test/tests/outputs/sampled_output/gold/adapt_out_oversample.e
  test/tests/outputs/sampled_output/gold/ex02_adapt_os2.e
  test/tests/outputs/sampled_output/gold/ex02_adapt_os4.e
  test/tests/outputs/sampled_output/gold/ex02_adapt_out.e
  test/tests/outputs/sampled_output/gold/ex02_oversample_os2.e
  test/tests/outputs/sampled_output/gold/ex02_oversample_os4.e
  test/tests/outputs/sampled_output/gold/ex02_oversample_out.e
  test/tests/outputs/sampled_output/gold/exodus_oversample_custom_name.e
  test/tests/outputs/sampled_output/gold/out_file.e
  test/tests/outputs/sampled_output/gold/out_file_oversample.e
  test/tests/outputs/sampled_output/gold/out_gen.e
  test/tests/outputs/sampled_output/gold/out_gen_oversample.e
  test/tests/outputs/sampled_output/gold/out_wedge_oversample.e
  test/tests/outputs/sampled_output/gold/oversample_out.e
  test/tests/outputs/sampled_output/over_sampling_second_file.i
  test/tests/outputs/sampled_output/over_sampling_test_file.i
  test/tests/outputs/sampled_output/over_sampling_test_gen.i
  test/tests/outputs/sampled_output/oversample.i
  test/tests/outputs/sampled_output/oversample_file.i
  test/tests/outputs/sampled_output/square.e
  test/tests/outputs/sampled_output/square_3x3.e
  test/tests/outputs/sampled_output/tests
  test/tests/outputs/sampled_output/wedge18_mesh.e
  test/tests/outputs/sampled_output/wedge6_mesh.e
  test/tests/partitioners/single_rank_partitioner/single_rank_partitioner.i
Labels: PR: Ready for review/merge

#30771 Add test spec path to job header
  python/FactorySystem/Parser.py
  python/TestHarness/schedulers/Job.py
Labels: PR: Ready for review/merge

#30756 Fix longest tests/folders, unify result output, cleanup result summary
  python/TestHarness/OutputInterface.py
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/schedulers/RunParallel.py
  python/TestHarness/tests/test_FormatResult.py
  python/TestHarness/tests/test_LongestJobs.py
  python/TestHarness/tests/tests
  python/TestHarness/util.py
Labels: PR: Ready for review/merge

#30694 Make exec_transfer a valid option for an up-to-date execution before sending data to sub apps
  framework/include/transfers/MultiAppGeneralFieldUserObjectTransfer.h
  framework/include/transfers/MultiAppTransfer.h
  framework/include/userobjects/SpatialUserObjectFunctor.h
  framework/src/transfers/MultiAppGeneralFieldUserObjectTransfer.C
  framework/src/transfers/MultiAppPostprocessorInterpolationTransfer.C
  framework/src/transfers/MultiAppPostprocessorToAuxScalarTransfer.C
  framework/src/transfers/MultiAppPostprocessorTransfer.C
  framework/src/transfers/MultiAppTransfer.C
  framework/src/transfers/MultiAppUserObjectTransfer.C
  framework/src/transfers/MultiAppVectorPostprocessorTransfer.C
  test/tests/transfers/general_field/user_object/regular/gold/main_out_sub0_out.e
  test/tests/transfers/general_field/user_object/regular/gold/main_out_sub1_out.e
  test/tests/transfers/general_field/user_object/regular/gold/main_out_sub2_out.e
  test/tests/transfers/general_field/user_object/regular/gold/projection_receive_sub0_out.e
  test/tests/transfers/general_field/user_object/regular/gold/projection_receive_sub1_out.e
  test/tests/transfers/general_field/user_object/regular/gold/projection_receive_sub2_out.e
  test/tests/transfers/general_field/user_object/regular/main.i
  test/tests/transfers/multiapp_postprocessor_interpolation_transfer/parent.i
  test/tests/transfers/multiapp_postprocessor_interpolation_transfer/radial_parent.i
  test/tests/transfers/multiapp_postprocessor_to_scalar/parent.i
  test/tests/transfers/multiapp_postprocessor_transfer/parent.i
  test/tests/transfers/multiapp_userobject_transfer/3d_1d_parent.i
  test/tests/transfers/multiapp_vector_pp_transfer/tests
Labels: PR: Ready for review/merge

#30760 Fix for divergence crtieria in parsed Convergence when no convergence objects are used
  framework/src/convergence/ParsedConvergence.C
  test/tests/convergence/parsed_convergence/tests
Labels: PR: Ready for review/merge

#30750 Added functor material to compute non-dimensional numbers for conjugate heat transfer
  modules/fluid_properties/include/fluidproperties/IdealGasFluidProperties.h
  modules/fluid_properties/src/fluidproperties/IdealGasFluidProperties.C
  modules/fluid_properties/unit/src/IdealGasFluidPropertiesTest.C
  modules/misc/include/utils/PhysicalConstants.h
  modules/thermal_hydraulics/doc/content/source/functormaterials/ConjugateHTNumbersFunctorMaterial.md
  modules/thermal_hydraulics/include/functormaterials/ConjugateHTNumbersFunctorMaterial.h
  modules/thermal_hydraulics/src/functormaterials/ConjugateHTNumbersFunctorMaterial.C
  modules/thermal_hydraulics/test/tests/functormaterials/conjugate_ht_numbers/conjugate_ht_numbers.i
  modules/thermal_hydraulics/test/tests/functormaterials/conjugate_ht_numbers/gold/conjugate_ht_numbers_out.csv
  modules/thermal_hydraulics/test/tests/functormaterials/conjugate_ht_numbers/tests
Labels: PR: Failed but allowed

#30653 Add support for linear system convergence
  framework/doc/content/source/timesteppers/IterationAdaptiveDT.md
  framework/include/base/Moose.h
  framework/include/problems/FEProblemBase.h
  framework/include/timesteppers/IterationAdaptiveDT.h
  framework/src/base/Moose.C
  framework/src/executioners/FEProblemSolve.C
  framework/src/physics/PhysicsBase.C
  framework/src/problems/FEProblemBase.C
  framework/src/timesteppers/IterationAdaptiveDT.C
  framework/src/utils/PetscSupport.C
  test/tests/time_steppers/iteration_adaptive/adapt_linear_systems.i
  test/tests/time_steppers/iteration_adaptive/gold/adapt_linear_systems_out.csv
  test/tests/time_steppers/iteration_adaptive/tests
  unit/src/MooseEnumTest.C
Labels: PR: Ready for review/merge

#30884 Fix uninitialized memory error introduced in #30653
  framework/include/problems/FEProblemBase.h
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed, PR: Ready for review/merge
