Repository idaholab/moose, pull requests merged in 2025-04, with the labels that each got.

#29775 Laromance model in NEML2
  modules/solid_mechanics/doc/content/bib/solid_mechanics.bib
  modules/solid_mechanics/doc/content/modules/solid_mechanics/NEML2.md
  modules/solid_mechanics/doc/content/modules/solid_mechanics/common/LAROMANCE6DInterpolation.md
  modules/solid_mechanics/neml2/include/LAROMANCE6DInterpolation.h
  modules/solid_mechanics/neml2/src/LAROMANCE6DInterpolation.cxx
  modules/solid_mechanics/solid_mechanics.mk
  modules/solid_mechanics/src/neml2/userobjects/NEML2ModelExecutor.C
  modules/solid_mechanics/test/neml2/src/NEML2TestModel.cxx
  modules/solid_mechanics/test/tests/neml2/laromance/gold/laromance_interpolate_out.csv
  modules/solid_mechanics/test/tests/neml2/laromance/gold/laromance_return_mapping_out.csv
  modules/solid_mechanics/test/tests/neml2/laromance/laromance_interpolate.i
  modules/solid_mechanics/test/tests/neml2/laromance/laromance_return_mapping.i
  modules/solid_mechanics/test/tests/neml2/laromance/models/create_6D_dummy_grid_json.py
  modules/solid_mechanics/test/tests/neml2/laromance/models/laromance_matl_interp.i
  modules/solid_mechanics/test/tests/neml2/laromance/models/laromance_matl_interp_bad.i
  modules/solid_mechanics/test/tests/neml2/laromance/models/laromance_matl_radial_return.i
  modules/solid_mechanics/test/tests/neml2/laromance/models/random_value_6d_grid.json
  modules/solid_mechanics/test/tests/neml2/laromance/models/random_value_6d_grid_bad.json
  modules/solid_mechanics/test/tests/neml2/laromance/models/sampled_combinations.csv
  modules/solid_mechanics/test/tests/neml2/laromance/tests
Labels: PR: Failed but allowed

#30247 Updated SlepscSupport to support dont_add_these_options
  framework/include/utils/PetscSupport.h
  framework/include/utils/SlepcSupport.h
  framework/src/executioners/Eigenvalue.C
  framework/src/utils/SlepcSupport.C
Labels: PR: Failed but allowed

#30306 Slow down PID transient control test wiith a lower max rate and a time derivate to make it slowly get to the target value
  framework/src/partitioner/HierarchicalGridPartitioner.C
  test/tests/controls/pid_control/gold/abs_max_rate_change.csv
  test/tests/controls/pid_control/tests
Labels: PR: Failed but allowed

#30005 Fix for internal side indicator on displaced mesh
  framework/include/indicators/Indicator.h
  framework/include/variables/MooseVariableFieldBase.h
  framework/src/indicators/Indicator.C
  framework/src/indicators/InternalSideIndicator.C
  test/tests/adaptivity/block_restriction/test.i
  test/tests/adaptivity/displaced_mesh/cycles_per_step.i
  test/tests/adaptivity/displaced_mesh/gold/cycles_per_step_out.e-s002
  test/tests/adaptivity/displaced_mesh/gold/cycles_per_step_out.e-s004
  test/tests/adaptivity/displaced_mesh/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#30222 Add capability for separator sidesets in NS.
  framework/include/variables/MooseVariableFV.h
  framework/src/fvkernels/FVFluxKernel.C
  framework/src/variables/MooseVariableFV.C
  modules/navier_stokes/doc/content/source/fvbcs/INSFVScalarFieldSeparatorBC.md
  modules/navier_stokes/doc/content/source/fvbcs/INSFVVelocityHydraulicSeparatorBC.md
  modules/navier_stokes/include/fvbcs/INSFVHydraulicSeparatorInterface.h
  modules/navier_stokes/include/fvbcs/INSFVScalarFieldSeparatorBC.h
  modules/navier_stokes/include/fvbcs/INSFVVelocityHydraulicSeparatorBC.h
  modules/navier_stokes/include/physics/WCNSFVFlowPhysics.h
  modules/navier_stokes/include/physics/WCNSFVFlowPhysicsBase.h
  modules/navier_stokes/include/physics/WCNSFVFluidHeatTransferPhysics.h
  modules/navier_stokes/include/physics/WCNSFVFluidHeatTransferPhysicsBase.h
  modules/navier_stokes/include/physics/WCNSFVScalarTransportPhysics.h
  modules/navier_stokes/include/physics/WCNSLinearFVFlowPhysics.h
  modules/navier_stokes/include/physics/WCNSLinearFVFluidHeatTransferPhysics.h
  modules/navier_stokes/include/variables/INSFVVariable.h
  modules/navier_stokes/src/base/NSFVBase.C
  modules/navier_stokes/src/fvbcs/INSFVHydraulicSeparatorInterface.C
  modules/navier_stokes/src/fvbcs/INSFVScalarFieldSeparatorBC.C
  modules/navier_stokes/src/fvbcs/INSFVVelocityHydraulicSeparatorBC.C
  modules/navier_stokes/src/fvkernels/INSFVAdvectionKernel.C
  modules/navier_stokes/src/fvkernels/INSFVMassAdvection.C
  modules/navier_stokes/src/physics/WCNSFVFlowPhysics.C
  modules/navier_stokes/src/physics/WCNSFVFlowPhysicsBase.C
  modules/navier_stokes/src/physics/WCNSFVFluidHeatTransferPhysics.C
  modules/navier_stokes/src/physics/WCNSFVFluidHeatTransferPhysicsBase.C
  modules/navier_stokes/src/physics/WCNSLinearFVFlowPhysics.C
  modules/navier_stokes/src/variables/BernoulliPressureVariable.C
  modules/navier_stokes/src/variables/INSFVVariable.C
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/diverging.msh
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/gold/separator-energy-nonorthogonal_out.csv
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/gold/separator-energy_out.csv
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/gold/separator-jump_out.csv
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/gold/separator-mixing-physics_out.csv
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/gold/separator-mixing_out.csv
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/gold/separator-no-jump_out.csv
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/gold/separator-scalar_out.csv
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/separator-energy-nonorthogonal.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/separator-energy.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/separator-jump.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/separator-mixing-physics.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/separator-mixing.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/separator-no-jump.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/separator-scalar.i
  modules/navier_stokes/test/tests/finite_volume/pins/channel-flow/hydraulic-separators/tests
Labels: PR: Failed but allowed

#30325 Revert "Make Transient APIs more atomic"
  framework/include/executioners/TransientBase.h
  framework/src/executioners/TransientBase.C
Labels: PR: Failed but allowed

#30355 Add default phrase when empty validation and verification sections exist in the VVR
  python/MooseDocs/extensions/sqa.py
  python/MooseDocs/test/extensions/test_sqa.py
Labels: T: task, C: Documentation, PR: Ready for review/merge, C: Python

#30376 Leaner build for capabilities without MOOSE dependency
  framework/contrib/capabilities/capabilities.C
  framework/include/utils/CapabilityUtils.h
  framework/include/utils/MooseStringUtils.h
  framework/include/utils/MooseUtils.h
  framework/include/utils/StreamArguments.h
  framework/moose.mk
  framework/src/base/MooseApp.C
  framework/src/utils/CapabilityUtils.C
  framework/src/utils/MooseUtils.C
  modules/solid_mechanics/test/tests/neml2/laromance/tests
  modules/subchannel/validation/areva_FCTF/tests
  python/TestHarness/TestHarness.py
  python/pycapabilities/__init__.py
  scripts/convert_to_capabilities.py
Labels: PR: Failed but allowed

#30393 Remove now unnecessary patches to installed capability lib
  framework/moose.mk
Labels: PR: Failed but allowed

#30399 Prepare meshes for stitching
  modules/reactor/src/meshgenerators/PatternedCartesianMeshGenerator.C
  modules/reactor/src/meshgenerators/PatternedHexMeshGenerator.C
Labels: PR: Failed but allowed

#30250 Add derivatives to GrandPotentialSinteringMaterial
  modules/phase_field/include/materials/GrandPotentialSinteringMaterial.h
  modules/phase_field/src/materials/GrandPotentialSinteringMaterial.C
  modules/phase_field/test/tests/GrandPotentialPFM/gold/SinteringDilute_out.e
  modules/phase_field/test/tests/GrandPotentialPFM/gold/SinteringIdeal_out.e
  modules/phase_field/test/tests/GrandPotentialPFM/gold/SinteringParabolic_out.e
Labels: PR: Failed but allowed

#30414 Nodal constraints now work with threads
  test/tests/constraints/nodal_constraint/tests
Labels: PR: Failed but allowed

#30249 Turn on recover testing for the phase field module
  framework/include/utils/MooseRandom.h
  framework/src/outputs/Exodus.C
  modules/phase_field/include/materials/GrandPotentialSinteringMaterial.h
  modules/phase_field/include/userobjects/DiscreteNucleationFromFile.h
  modules/phase_field/include/userobjects/EulerAngleUpdater.h
  modules/phase_field/include/userobjects/RandomEulerAngleProvider.h
  modules/phase_field/src/ics/PFCFreezingIC.C
  modules/phase_field/src/userobjects/DiscreteNucleationFromFile.C
  modules/phase_field/src/userobjects/EulerAngleUpdater.C
  modules/phase_field/src/userobjects/RandomEulerAngleProvider.C
  modules/phase_field/test/tests/GBType/tests
  modules/phase_field/test/tests/GrandPotentialPFM/tests
  modules/phase_field/test/tests/KKS_system/tests
  modules/phase_field/test/tests/actions/tests
  modules/phase_field/test/tests/free_energy_material/tests
  modules/phase_field/test/tests/initial_conditions/HexPolycrystalIC_3D_columnar.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiIC_periodic.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_moregrains.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_notperiodic.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_periodic.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoiVoidIC_periodic_fromfile.i
  modules/phase_field/test/tests/initial_conditions/PolycrystalVoronoi_fromfile.i
  modules/phase_field/test/tests/initial_conditions/circles_from_file_ic.i
  modules/phase_field/test/tests/initial_conditions/polycrystalcircles_clipped.i
  modules/phase_field/test/tests/initial_conditions/polycrystalcircles_fromfile.i
  modules/phase_field/test/tests/initial_conditions/tests
  modules/phase_field/test/tests/mobility_derivative/tests
  modules/phase_field/test/tests/new_initial_conditions/GrainGrowth_initial_from_file.i
  modules/phase_field/test/tests/new_initial_conditions/tests
  modules/phase_field/test/tests/phase_field_crystal/PFC_IC/PFC_IC_FCC_test.i
  modules/phase_field/test/tests/phase_field_crystal/PFC_IC/tests
  modules/phase_field/test/tests/phase_field_kernels/tests
  modules/phase_field/test/tests/reconstruction/tests
Labels: PR: Failed but allowed
