Repository idaholab/moose, pull requests merged in 2025-07, with the labels that each got.

#30893 Write Console output header to Exodus info
  framework/src/outputs/formatters/ExodusFormatter.C
Labels: PR: Ready for review/merge

#30155 Enable External and Hole Boundaries Assignment in XYZDelaunay
  framework/doc/content/source/meshgenerators/XYZDelaunayGenerator.md
  framework/include/meshgenerators/XYZDelaunayGenerator.h
  framework/src/meshgenerators/ElementGenerator.C
  framework/src/meshgenerators/XYZDelaunayGenerator.C
  test/tests/meshgenerators/xyz_delaunay_generator/err_xyzdelaunay_with_holes_mix.i
  test/tests/meshgenerators/xyz_delaunay_generator/gold/2d_cube.e
  test/tests/meshgenerators/xyz_delaunay_generator/gold/xyzdelaunay_bcid_csv.csv
  test/tests/meshgenerators/xyz_delaunay_generator/tests
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_bcid.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_mesh_generator_2d.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_mesh_generator_3d.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_with_holes_1d.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_with_holes_2d.i
  test/tests/meshgenerators/xyz_delaunay_generator/xyzdelaunay_with_holes_3d.i
Labels: PR: Failed but allowed

#30936 Correct `ResultsReader` getting PR results
  python/TestHarness/resultsreader/reader.py
  python/TestHarness/tests/gold/resultsreader/prod_get_test_results.json
  python/TestHarness/tests/test_resultsreader_reader.py
Labels: PR: Ready for review/merge

#30967 Two minor improves to ElementGroupCentroidPositions
  framework/src/positions/ElementGroupCentroidPositions.C
Labels: PR: Failed but allowed

#30990 Add IP-HDG to newsletter
  modules/doc/content/newsletter/2025/2025_06.md
Labels: PR: Failed but allowed

#30981 Re-init displaced assembly for domain user objects acting on the displaced mesh
  framework/src/problems/FEProblemBase.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#30984 Update terminology for multi-species diffusion Physics preconditioning option
  modules/scalar_transport/src/physics/MultiSpeciesDiffusionPhysicsBase.C
Labels: PR: Ready for review/merge

#30982 Add a capability of prolongating values in ExtraIDIntegralVectorPostprocessor
  framework/doc/content/source/vectorpostprocessors/ExtraIDIntegralVectorPostprocessor.md
  framework/include/userobjects/SpatialUserObjectFunctor.h
  framework/include/vectorpostprocessors/ExtraIDIntegralVectorPostprocessor.h
  framework/src/auxkernels/FunctorAux.C
  framework/src/vectorpostprocessors/ExtraIDIntegralVectorPostprocessor.C
  test/tests/vectorpostprocessors/extra_id_integral/functor_test.i
  test/tests/vectorpostprocessors/extra_id_integral/gold/functor_test_out.e
  test/tests/vectorpostprocessors/extra_id_integral/tests
Labels: PR: Failed but allowed

#31071 turn error to exception for out of bounds behavior on temperature
  modules/fluid_properties/src/fluidproperties/TabulatedFluidProperties.C
Labels: PR: Failed but allowed

#30953 Revert "Build the FP apps even when using the relevant FP submodule"
  modules/fluid_properties/fluid_properties.mk
Labels: PR: Failed but allowed, PR: Ready for review/merge

#30906 Add `CSVValidationCase` for testing validation with golded CSVs
  python/TestHarness/JobDAG.py
  python/TestHarness/TestHarness.py
  python/TestHarness/resultsreader/results.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/schedulers/RunHPC.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/gold/validation/csvvalidationcase_testaddscalarcsvdata.json
  python/TestHarness/tests/gold/validation/csvvalidationcase_testaddscalarcsvdataabszerofail.json
  python/TestHarness/tests/gold/validation/csvvalidationcase_testaddscalarcsvdataabszeropass.json
  python/TestHarness/tests/gold/validation/csvvalidationcase_testaddscalarcsvdatafailrelerr.json
  python/TestHarness/tests/gold/validation/csvvalidationcase_testaddscalarcsvdatafailrelerrunchecked.json
  python/TestHarness/tests/gold/validation/csvvalidationcase_testaddscalarcsvdatastorekey.json
  python/TestHarness/tests/gold/validation/validation_testcsv.json
  python/TestHarness/tests/test_CSVValidationCase.py
  python/TestHarness/tests/test_Duplicate.py
  python/TestHarness/tests/test_Validation.py
  python/TestHarness/tests/test_WriteResults.py
  python/TestHarness/validation/__init__.py
  python/TestHarness/validation/cases/csvvalidationcase.py
  python/TestHarness/validation/cases/validationcase.py
  test/tests/test_harness/gold/validation_csv.csv
  test/tests/test_harness/gold/validation_ok.csv
  test/tests/test_harness/validation
  test/tests/test_harness/validation_csv.py
  test/tests/test_harness/validation_init_exception
  test/tests/test_harness/validation_init_exception.py
Labels: PR: Ready for review/merge

#31099 Avoid redundant add/remove of GhostingFunctors
  framework/src/base/MooseApp.C
  framework/src/problems/SubProblem.C
  framework/src/transfers/MultiAppProjectionTransfer.C
Labels: PR: Failed but allowed

#31104 Add kokkos+libceed to all petsc builds, update container mpi, update containers, fix conda zsh on linux
  apptainer/mpi.def
  apptainer/petsc.def
  conda/libmesh-vtk/conda_build_config.yaml
  conda/libmesh-vtk/meta.yaml
  conda/libmesh/conda_build_config.yaml
  conda/libmesh/meta.yaml
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/mpi/base_build.sh
  conda/mpi/meta.yaml
  conda/petsc/conda_build_config.yaml
  conda/petsc/meta.yaml
  scripts/configure_petsc.sh
  scripts/tests/versioner_hashes.yaml
  scripts/update_and_rebuild_mfem.sh
  scripts/versioner.yaml
Labels: PR: Ready for review/merge, PR: Updates packages

#31115 Fix sampled output of variables with larger block restriction
  framework/src/outputs/SampledOutput.C
  test/tests/outputs/block_restricted/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge
