Repository idaholab/moose, pull requests merged in 2025-08, with the labels that each got.

#31174 Update terminology in diffusion physics for preconditioning options
  framework/src/physics/DiffusionPhysicsBase.C
  modules/heat_transfer/src/physics/HeatConductionCG.C
Labels: PR: Ready for review/merge

#31151 Add ceed-* devices to test harness
  python/TestHarness/TestHarness.py
  python/TestHarness/testers/RunApp.py
Labels: PR: Ready for review/merge

#31194 Skip restep in linear k-epsilon + non-equilibrium wall function
  modules/navier_stokes/include/auxkernels/kEpsilonViscosityAux.h
  modules/navier_stokes/src/auxkernels/kEpsilonViscosityAux.C
  modules/navier_stokes/test/tests/finite_volume/ins/turbulence/bfs/linear-segregated-transient/tests
Labels: PR: Failed but allowed

#31159 Support further / mismatched block-restricted variables in block-restricted sampled output
  framework/include/outputs/AdvancedOutput.h
  framework/src/outputs/SampledOutput.C
  test/tests/outputs/block_restricted/block.i
Labels: PR: Ready for review/merge

#31226 Add `--with-dap` option to MooseDocs build for enabling the Digital Analytics Program
  python/MooseDocs/base/renderers.py
  python/MooseDocs/commands/build.py
  python/MooseDocs/test/commands/test_build.py
  python/MooseDocs/test/tree/test_html.py
  python/MooseDocs/tree/html.py
Labels: PR: Ready for review/merge

#31253 Updates papers to cite
  modules/doc/content/citing.md
Labels: PR: Failed but allowed, PR: Ready for review/merge

#31247 Fix SQA doco of heat transfer module
  modules/doc/sqa_reports.yml
  modules/heat_transfer/doc/config.yml
  modules/heat_transfer/doc/content/source/bcs/CoupledConvectiveFlux.md
  modules/heat_transfer/doc/content/source/bcs/HeatConductionBC.md
  modules/heat_transfer/doc/content/source/dirackernels/GapHeatPointSourceMaster.md
  modules/heat_transfer/doc/content/source/materials/GapConductance.md
  modules/heat_transfer/doc/content/source/postprocessors/ThermalConductivity.md
  modules/heat_transfer/doc/content/syntax/Modules/HeatTransfer/ThermalContact/BC/index.md
  modules/heat_transfer/doc/content/syntax/Modules/HeatTransfer/ThermalContact/index.md
  modules/heat_transfer/doc/content/syntax/Modules/HeatTransfer/index.md
  modules/heat_transfer/doc/content/syntax/Modules/index.md
  modules/heat_transfer/doc/sqa_reports.yml
  modules/heat_transfer/src/base/HeatTransferApp.C
  modules/heat_transfer/src/bcs/CoupledConvectiveFlux.C
  modules/heat_transfer/src/bcs/HeatConductionBC.C
  modules/heat_transfer/src/dirackernels/GapHeatPointSourceMaster.C
  modules/heat_transfer/src/materials/GapConductance.C
  modules/heat_transfer/src/postprocessors/ThermalConductivity.C
  modules/heat_transfer/test/tests/gap_heat_transfer_htonly/gap_heat_transfer_htonly_syntax.i
  modules/heat_transfer/test/tests/gap_heat_transfer_htonly/tests
Labels: PR: Ready for review/merge

#31196 Move NS auxkernels away from AD
  modules/navier_stokes/include/auxkernels/HasPorosityJumpFace.h
  modules/navier_stokes/include/auxkernels/NSLiquidFractionAux.h
  modules/navier_stokes/include/auxkernels/PecletNumberFunctorAux.h
  modules/navier_stokes/include/auxkernels/ReynoldsNumberFunctorAux.h
  modules/navier_stokes/include/auxkernels/TurbulentConductivityAux.h
  modules/navier_stokes/include/auxkernels/WallFunctionWallShearStressAux.h
  modules/navier_stokes/include/auxkernels/WallFunctionYPlusAux.h
  modules/navier_stokes/include/utils/NSFVUtils.h
  modules/navier_stokes/src/auxkernels/HasPorosityJumpFace.C
  modules/navier_stokes/src/auxkernels/INSFVMixingLengthTurbulentViscosityAux.C
  modules/navier_stokes/src/auxkernels/NSLiquidFractionAux.C
  modules/navier_stokes/src/auxkernels/PecletNumberFunctorAux.C
  modules/navier_stokes/src/auxkernels/ReynoldsNumberFunctorAux.C
  modules/navier_stokes/src/auxkernels/TurbulentConductivityAux.C
  modules/navier_stokes/src/auxkernels/WallFunctionWallShearStressAux.C
  modules/navier_stokes/src/auxkernels/WallFunctionYPlusAux.C
  modules/navier_stokes/src/utils/NSFVUtils.C
Labels: PR: Ready for review/merge

#31274 Limit number of threads for libtorch via --num-threads
  framework/include/neml2/interfaces/NEML2ModelInterface.h
  framework/src/base/MooseInit.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#31015 compile_commands.json defaults MOOSE_UNITY and MOOSE_HEADER_SYMLINKS to false
  framework/build.mk
  framework/moose.mk
Labels: PR: Failed but allowed

#31230 Enhancements to web server control
  framework/doc/content/source/controls/WebServerControl.md
  framework/include/controls/Control.h
  framework/include/controls/WebServerControl.h
  framework/include/controls/WebServerControlTypeRegistry.h
  framework/include/outputs/JsonIO.h
  framework/include/reporters/ConstantReporter.h
  framework/include/reporters/ReporterInterface.h
  framework/include/reporters/ReporterName.h
  framework/src/controls/Control.C
  framework/src/controls/WebServerControl.C
  framework/src/reporters/ConstantReporter.C
  framework/src/reporters/ReporterInterface.C
  framework/src/reporters/ReporterName.C
  python/MooseControl/MooseControl.py
  test/src/reporters/WebServerControlTestReporter.C
  test/tests/controls/web_server_control/control_reporter.py
  test/tests/controls/web_server_control/errors.py
  test/tests/controls/web_server_control/get_reporter.i
  test/tests/controls/web_server_control/get_reporter.py
  test/tests/controls/web_server_control/gold/control_reporter_matrix.json
  test/tests/controls/web_server_control/gold/get_reporter_out.json
  test/tests/controls/web_server_control/terminate.py
  test/tests/controls/web_server_control/tests
  test/tests/reporters/constant_reporter/constant_eigen_reporter.i
  test/tests/reporters/constant_reporter/gold/constant_eigen_reporter_out.json
  test/tests/reporters/constant_reporter/tests
  unit/src/WebServerControlTest.C
Labels: PR: Failed but allowed

#31105 Mesh modification and displacements improvements for UOs and mortar
  framework/include/loops/ComputeMortarFunctor.h
  framework/include/systems/NonlinearSystemBase.h
  framework/src/auxkernels/NearestNodeValueAux.C
  framework/src/loops/ComputeMortarFunctor.C
  framework/src/mesh/MooseMesh.C
  framework/src/meshmodifiers/SidesetAroundSubdomainUpdater.C
  framework/src/problems/FEProblemBase.C
  framework/src/systems/NonlinearSystemBase.C
  test/tests/mortar/mesh_modification/displaced_and_modifying_meshes.i
  test/tests/mortar/mesh_modification/gold/displaced_and_modifying_meshes_out.csv
  test/tests/mortar/mesh_modification/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#31221 Minor code refactoring and makefile fix
  framework/doc/content/source/mfem/mesh/MFEMMesh.md
  framework/include/mfem/outputs/MFEMConduitDataCollection.h
  framework/include/mfem/outputs/MFEMDataCollection.h
  framework/include/mfem/problem_operators/TimeDomainProblemOperator.h
  framework/moose.mk
  framework/src/base/MooseApp.C
  framework/src/executioners/SteadyBase.C
  framework/src/mfem/executioners/MFEMSteady.C
  framework/src/mfem/ics/MFEMVectorIC.C
  framework/src/mfem/outputs/MFEMDataCollection.C
  framework/src/mfem/problem_operators/TimeDomainProblemOperator.C
  framework/src/multiapps/MultiApp.C
  test/tests/mfem/ics/vector_ic.i
  test/tests/mfem/kernels/diffusion.i
  test/tests/mfem/timesteppers/tests
Labels: PR: Failed but allowed

#31318 Remove milljm from codeowners
  CODEOWNERS
Labels: PR: Ready for review/merge

#31347 Avoid creating gridfunctions for the time derivatives of MFEM AuxVariables
  framework/doc/content/source/mfem/kernels/MFEMKernel.md
  framework/include/mfem/mesh/MFEMMesh.h
  framework/src/mfem/mesh/MFEMMesh.C
  framework/src/mfem/problem/MFEMProblem.C
  test/tests/mfem/ics/gold/OutputData/TransientScalarIC/Run0/Cycle000000/data.pvtu
  test/tests/mfem/ics/gold/OutputData/TransientScalarIC/Run0/Cycle000000/proc000000.vtu
  test/tests/mfem/ics/gold/OutputData/TransientScalarIC/Run0/Cycle000001/data.pvtu
  test/tests/mfem/ics/gold/OutputData/TransientScalarIC/Run0/Cycle000001/proc000000.vtu
  test/tests/mfem/variables/gold/OutputData/VariableSetupTest/Run0/Cycle000000/data.pvtu
  test/tests/mfem/variables/gold/OutputData/VariableSetupTest/Run0/Cycle000001/data.pvtu
  test/tests/mfem/variables/gold/OutputData/VariableSetupTest/Run0/Run0.pvd
Labels: PR: Failed but allowed

#31335 Improve CI consistency of SolutionTimeAdaptiveDT
  framework/doc/content/source/timesteppers/SolutionTimeAdaptiveDT.md
  framework/include/timesteppers/SolutionTimeAdaptiveDT.h
  framework/src/timesteppers/SolutionTimeAdaptiveDT.C
  modules/phase_field/test/tests/GrandPotentialPFM/GrandPotentialMultiphase.i
  modules/phase_field/test/tests/GrandPotentialPFM/GrandPotentialMultiphase_AD.i
  modules/richards/test/tests/buckley_leverett/bl02.i
  test/include/timesteppers/SolutionTimeAdaptiveDTTest.h
  test/src/timesteppers/SolutionTimeAdaptiveDTTest.C
  test/tests/executioners/executioner/sln-time-adapt.i
  test/tests/time_steppers/time_adaptive/gold/time-adaptive_out.csv
  test/tests/time_steppers/time_adaptive/tests
  test/tests/time_steppers/time_adaptive/time-adaptive.i
  test/tests/time_steppers/time_stepper_system/testRejectStep.i
  test/tests/time_steppers/time_stepper_system/tests
  test/tests/time_steppers/time_stepper_system/time_stepper_system_restart.i
Labels: PR: Failed but allowed

#30934 Add some support for multi-system for porous flow actions
  framework/include/problems/FEProblemBase.h
  framework/include/userobjects/UserObject.h
  framework/src/problems/FEProblemBase.C
  framework/src/userobjects/UserObject.C
  modules/navier_stokes/include/correctors/NSPressurePin.h
  modules/navier_stokes/include/userobjects/RhieChowInterpolatorBase.h
  modules/navier_stokes/src/correctors/NSPressurePin.C
  modules/navier_stokes/src/userobjects/RhieChowInterpolatorBase.C
  modules/porous_flow/src/actions/PorousFlowSinglePhaseBase.C
  modules/porous_flow/src/userobjects/PorousFlowDictator.C
  modules/porous_flow/test/tests/multi_system/flow_and_mecha.i
  modules/porous_flow/test/tests/multi_system/gold/flow_and_mecha_out.csv
  modules/porous_flow/test/tests/multi_system/tests
  modules/porous_flow/unit/src/PorousFlowBrineCO2Test.C
  modules/porous_flow/unit/src/PorousFlowDictatorTest.C
  modules/porous_flow/unit/src/PorousFlowWaterVaporTest.C
Labels: PR: Ready for review/merge

#31183 Extend 2D Delaunay to Curved Surfaces
  framework/doc/content/source/meshgenerators/Boundary2DDelaunayGenerator.md
  framework/include/meshgenerators/Boundary2DDelaunayGenerator.h
  framework/include/meshgenerators/SurfaceDelaunayGeneratorBase.h
  framework/include/meshgenerators/XYDelaunayGenerator.h
  framework/include/utils/MooseMeshUtils.h
  framework/src/meshgenerators/BlockToMeshConverterGenerator.C
  framework/src/meshgenerators/Boundary2DDelaunayGenerator.C
  framework/src/meshgenerators/LowerDBlockFromSidesetGenerator.C
  framework/src/meshgenerators/SurfaceDelaunayGeneratorBase.C
  framework/src/meshgenerators/XYDelaunayGenerator.C
  framework/src/utils/MooseMeshUtils.C
  test/tests/meshgenerators/boundary_2d_delaunay_generator/cube.i
  test/tests/meshgenerators/boundary_2d_delaunay_generator/cylinder.i
  test/tests/meshgenerators/boundary_2d_delaunay_generator/gold/cube_nrf.csv
  test/tests/meshgenerators/boundary_2d_delaunay_generator/gold/cube_rf.csv
  test/tests/meshgenerators/boundary_2d_delaunay_generator/gold/curved_surf.csv
  test/tests/meshgenerators/boundary_2d_delaunay_generator/gold/curved_surf_ls.csv
  test/tests/meshgenerators/boundary_2d_delaunay_generator/gold/cylinder.csv
  test/tests/meshgenerators/boundary_2d_delaunay_generator/gold/sphere_surf.csv
  test/tests/meshgenerators/boundary_2d_delaunay_generator/sphere.i
  test/tests/meshgenerators/boundary_2d_delaunay_generator/tests
Labels: PR: Failed but allowed

#31383 Update lowerD elements before moving the parent elements
  test/tests/mortar/mesh_modification/mortar_esm_displaced.i
Labels: PR: Ready for review/merge
