Repository idaholab/moose, pull requests merged in 2025-05, with the labels that each got.

#29920 Added error to prevent segfault in DebugResidualAux
  framework/src/auxkernels/DebugResidualAux.C
  test/tests/auxkernels/debug_residual_aux/mismatch_residual_test.i
  test/tests/auxkernels/debug_residual_aux/tests
Labels: PR: Failed but allowed

#30441 Fixup lead lithium properties documentation and speed of sound
  modules/fluid_properties/doc/content/bib/fluid_properties.bib
  modules/fluid_properties/doc/content/source/fluidproperties/LeadLithiumFluidProperties.md
  modules/fluid_properties/include/fluidproperties/LeadLithiumFluidProperties.h
  modules/fluid_properties/src/fluidproperties/LeadLithiumFluidProperties.C
  modules/fluid_properties/unit/src/LeadLithiumFluidPropertiesTest.C
Labels: PR: Failed but allowed

#30443 Handle moving boundary inside a shared top parent of refined elements
  framework/src/meshmodifiers/ElementSubdomainModifierBase.C
  test/tests/meshmodifiers/element_subdomain_modifier/gold/moving_boundary_h_refinement_out.csv
  test/tests/meshmodifiers/element_subdomain_modifier/moving_boundary_h_refinement.i
  test/tests/meshmodifiers/element_subdomain_modifier/tests
Labels: PR: Failed but allowed

#30298 Create ICs to model a marvel-type core #30295
  modules/subchannel/doc/content/modules/subchannel/examples/quad_thermo_mech.md
  modules/subchannel/doc/content/source/ics/MarvelTriFlowAreaIC.md
  modules/subchannel/doc/content/source/ics/MarvelTriWettedPerimIC.md
  modules/subchannel/include/ics/MarvelTriFlowAreaIC.h
  modules/subchannel/include/ics/MarvelTriWettedPerimIC.h
  modules/subchannel/src/ics/MarvelTriFlowAreaIC.C
  modules/subchannel/src/ics/MarvelTriWettedPerimIC.C
  modules/subchannel/test/tests/ics/marvel/gold/test_out.e
  modules/subchannel/test/tests/ics/marvel/test.i
  modules/subchannel/test/tests/ics/marvel/tests
Labels: PR: Failed but allowed

#30125 Preliminaries for gas mixture model in THM
  modules/fluid_properties/include/fluidproperties/IdealGasMixtureFluidProperties.h
  modules/fluid_properties/include/fluidproperties/IdealRealGasMixtureFluidProperties.h
  modules/fluid_properties/src/fluidproperties/IdealGasMixtureFluidProperties.C
  modules/fluid_properties/unit/src/IdealGasMixtureFluidPropertiesTest.C
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/bib/thm.bib
  modules/thermal_hydraulics/doc/content/source/userobjects/ADNumericalFlux3EqnHLLC.md
  modules/thermal_hydraulics/include/base/FlowModel.h
  modules/thermal_hydraulics/include/base/FlowModel1PhaseBase.h
  modules/thermal_hydraulics/include/base/FlowModelSinglePhase.h
  modules/thermal_hydraulics/include/base/THMNames.h
  modules/thermal_hydraulics/include/bcs/ADBoundaryFlux3EqnBC.h
  modules/thermal_hydraulics/include/components/FlowBoundary1Phase.h
  modules/thermal_hydraulics/include/components/FlowChannel1Phase.h
  modules/thermal_hydraulics/include/components/FlowChannel1PhaseBase.h
  modules/thermal_hydraulics/include/userobjects/ADNumericalFlux3EqnBase.h
  modules/thermal_hydraulics/include/userobjects/ADNumericalFlux3EqnHLLC.h
  modules/thermal_hydraulics/include/userobjects/NumericalFlux1D.h
  modules/thermal_hydraulics/include/utils/FlowModel1PhaseUtils.h
  modules/thermal_hydraulics/src/base/FlowModel.C
  modules/thermal_hydraulics/src/base/FlowModel1PhaseBase.C
  modules/thermal_hydraulics/src/base/FlowModelSinglePhase.C
  modules/thermal_hydraulics/src/bcs/ADBoundaryFlux3EqnBC.C
  modules/thermal_hydraulics/src/components/FlowBoundary1Phase.C
  modules/thermal_hydraulics/src/components/FlowChannel1Phase.C
  modules/thermal_hydraulics/src/components/FlowChannel1PhaseBase.C
  modules/thermal_hydraulics/src/components/FlowChannelBase.C
  modules/thermal_hydraulics/src/components/FreeBoundary1Phase.C
  modules/thermal_hydraulics/src/components/HeatTransfer1PhaseBase.C
  modules/thermal_hydraulics/src/components/HeatTransferFromHeatStructure1Phase.C
  modules/thermal_hydraulics/src/components/InletDensityVelocity1Phase.C
  modules/thermal_hydraulics/src/components/InletMassFlowRateTemperature1Phase.C
  modules/thermal_hydraulics/src/components/InletStagnationPressureTemperature1Phase.C
  modules/thermal_hydraulics/src/components/InletVelocityTemperature1Phase.C
  modules/thermal_hydraulics/src/components/Outlet1Phase.C
  modules/thermal_hydraulics/src/components/SolidWall1Phase.C
  modules/thermal_hydraulics/src/userobjects/ADNumericalFlux3EqnBase.C
  modules/thermal_hydraulics/src/userobjects/ADNumericalFlux3EqnHLLC.C
  modules/thermal_hydraulics/src/userobjects/ADVolumeJunction1PhaseUserObject.C
  modules/thermal_hydraulics/src/userobjects/NumericalFlux1D.C
  modules/thermal_hydraulics/test/src/components/InletFunction1Phase.C
  modules/thermal_hydraulics/test/tests/problems/brayton_cycle/tests
  modules/thermal_hydraulics/test/tests/problems/sod_shock_tube/davis_wave_speed.i
  modules/thermal_hydraulics/test/tests/problems/sod_shock_tube/gold/davis_wave_speed_vpp_FINAL.csv
  modules/thermal_hydraulics/test/tests/problems/sod_shock_tube/sod_shock_tube.i
  modules/thermal_hydraulics/test/tests/problems/sod_shock_tube/tests
  modules/thermal_hydraulics/unit/include/TestNumericalFlux1D.h
  modules/thermal_hydraulics/unit/include/TestNumericalFlux3EqnBase.h
  modules/thermal_hydraulics/unit/include/TestNumericalFlux3EqnCentered.h
  modules/thermal_hydraulics/unit/include/TestNumericalFlux3EqnHLLC.h
  modules/thermal_hydraulics/unit/src/TestNumericalFlux1D.C
  modules/thermal_hydraulics/unit/src/TestNumericalFlux3EqnBase.C
  modules/thermal_hydraulics/unit/src/TestNumericalFlux3EqnCentered.C
  modules/thermal_hydraulics/unit/src/TestNumericalFlux3EqnHLLC.C
Labels: PR: Failed but allowed

#30481 Make libtorch controller recoverable.
  framework/include/libtorch/controls/LibtorchNeuralNetControl.h
  framework/src/libtorch/controls/LibtorchNeuralNetControl.C
  modules/stochastic_tools/src/libtorch/controls/LibtorchDRLControl.C
  test/tests/controls/libtorch_nn_control/gold/torch_parameter_read.json
  test/tests/controls/libtorch_nn_control/gold/torch_script_read_T_reporter_0026.csv
  test/tests/controls/libtorch_nn_control/read_control.i
Labels: PR: Failed but allowed

#30491 Add influential file change to versioner verify
  scripts/versioner.py
Labels: PR: Failed but allowed

#30123 Moose Syntax Highlighting
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/wasp/meta.yaml
  framework/doc/content/contrib/prism/prism.min.js
  framework/doc/content/css/moose.css
  framework/doc/content/js/moose_input_parser.js
  python/MooseDocs/common/read.py
  python/MooseDocs/extensions/appsyntax.py
  python/MooseDocs/extensions/listing.py
  python/MooseDocs/test/content/extensions/listing.md
  python/MooseDocs/test/extensions/test_listing.py
  python/MooseDocs/test/gold/html/extensions/listing.html
  python/pyhit/pyhit.py
  scripts/versioner.yaml
Labels: PR: Updates packages

#30504 Add a positions object for gathering functor extremas
  framework/doc/content/source/positions/FunctorExtremaPositions.md
  framework/include/positions/ElementCentroidPositions.h
  framework/include/positions/FunctorExtremaPositions.h
  framework/src/functions/PiecewiseMulticonstant.C
  framework/src/materials/MaterialFunctorConverter.C
  framework/src/positions/FunctorExtremaPositions.C
  framework/src/positions/FunctorPositions.C
  framework/src/positions/Positions.C
  modules/doc/content/citing.md
  modules/fluid_properties/src/fluidproperties/SalineMoltenSaltFluidProperties.C
  test/tests/positions/functor_extrema_positions.i
  test/tests/positions/gold/functor_extrema_positions_out.json
  test/tests/positions/tests
Labels: PR: Ready for review/merge

#30544 Fix logic for forcing MPI
  python/TestHarness/util.py
Labels: PR: Ready for review/merge

#30550 Add more FV functor heat conduction capability
  framework/include/utils/InputParametersChecksUtils.h
  modules/heat_transfer/doc/content/source/fvkernels/FVFunctorHeatConductionTimeDerivative.md
  modules/heat_transfer/doc/content/source/fvkernels/FVHeatConductionTimeDerivative.md
  modules/heat_transfer/include/fvkernels/FVFunctorHeatConductionTimeDerivative.h
  modules/heat_transfer/include/fvkernels/FVHeatConductionTimeDerivative.h
  modules/heat_transfer/src/fvkernels/FVFunctorHeatConductionTimeDerivative.C
  modules/heat_transfer/src/physics/HeatConductionFV.C
  modules/heat_transfer/test/tests/physics/gold/test_fv_functor_all_out.e
  modules/heat_transfer/test/tests/physics/test_fv_functor.i
  modules/heat_transfer/test/tests/physics/tests
  modules/navier_stokes/include/functormaterials/GeneralFunctorFluidProps.h
  modules/navier_stokes/src/functormaterials/GeneralFunctorFluidProps.C
Labels: PR: Ready for review/merge

#30445 Add recover testing to the contact module
  framework/src/problems/FEProblemBase.C
  modules/contact/include/constraints/ComputeWeightedGapLMMechanicalContact.h
  modules/contact/src/constraints/ComputeDynamicWeightedGapLMMechanicalContact.C
  modules/contact/test/tests/3d-mortar-contact/tests
  modules/contact/test/tests/dual_mortar/tests
  modules/contact/test/tests/explicit_dynamics/tests
  modules/contact/test/tests/mortar_aux_kernels/gold/mortar_segment_mesh.e
  modules/contact/test/tests/mortar_aux_kernels/tests
  modules/contact/test/tests/mortar_dynamics/tests
  modules/contact/test/tests/multiple_contact_pairs/tests
  modules/contact/test/tests/pdass_problems/cylinder_friction_penalty_frictional_al_action_amg_tight_vectorpp_output_surface_FINAL.csv
Labels: PR: Ready for review/merge

#29855 Add a mesh generator for creating boundary layers in meshes
  framework/doc/content/source/meshgenerators/BoundaryLayerSubdomainGenerator.md
  framework/include/meshgenerators/BoundaryLayerSubdomainGenerator.h
  framework/src/meshgenerators/BoundaryLayerSubdomainGenerator.C
  test/tests/meshgenerators/boundary_layer_generator/external.i
  test/tests/meshgenerators/boundary_layer_generator/gold/external_in.e
  test/tests/meshgenerators/boundary_layer_generator/gold/internal_in.e
  test/tests/meshgenerators/boundary_layer_generator/internal.i
  test/tests/meshgenerators/boundary_layer_generator/tests
Labels: PR: Ready for review/merge

#30563 Error on passing coordinate transformation parameters in a standalone simulation
  framework/src/base/MooseApp.C
  framework/src/problems/FEProblemBase.C
  test/tests/transfers/coord_transform/tests
Labels: PR: Ready for review/merge

#30476 Update training list
  modules/doc/content/training/index.md
Labels: PR: Ready for review/merge

#30566 Only get status if a value was found
  python/TestHarness/testers/Tester.py
Labels: PR: Ready for review/merge

#30561 Honor `FindValueOnLine` error logic, improve errors
  framework/src/postprocessors/FindValueOnLine.C
Labels: PR: Ready for review/merge

#30471 Add a partitioner that can match the partitioning of another mesh
  framework/doc/content/source/partitioner/CopyMeshPartitioner.md
  framework/include/base/MooseApp.h
  framework/include/partitioner/CopyMeshPartitioner.h
  framework/src/actions/ExecuteMeshGenerators.C
  framework/src/actions/SetupMeshAction.C
  framework/src/actions/SetupMeshCompleteAction.C
  framework/src/base/MooseApp.C
  framework/src/multiapps/MultiApp.C
  framework/src/partitioner/CopyMeshPartitioner.C
  test/tests/partitioners/copy_mesh_partitioner/gold/parent_out_full_solve0.e
  test/tests/partitioners/copy_mesh_partitioner/gold/small_full_solve0.e
  test/tests/partitioners/copy_mesh_partitioner/parent.i
  test/tests/partitioners/copy_mesh_partitioner/sub.i
  test/tests/partitioners/copy_mesh_partitioner/tests
Labels: PR: Ready for review/merge

#30549 Add an option to skip some tasks in the Physics
  framework/src/physics/PhysicsBase.C
Labels: PR: Ready for review/merge

#30581 Add unique_test_id to job output
  python/TestHarness/TestHarness.py
  python/TestHarness/schedulers/Job.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/test_WriteResults.py
  test/tests/test_harness/always_ok
Labels: PR: Ready for review/merge

#30489 Move the introduction more towards regression instead of fitting.
  tutorials/darcy_thermo_mech/doc/config.yml
  tutorials/darcy_thermo_mech/doc/content/workshop/numerical/fem_overview.md
Labels: PR: Failed but allowed

#30288 Add correlation-based conjugate heat transfer capability to the linear segregated solver.
  framework/src/linearfvkernels/LinearFVDiffusion.C
  framework/src/loops/ComputeLinearFVGreenGaussGradientFaceThread.C
  framework/src/loops/ComputeLinearFVGreenGaussGradientVolumeThread.C
  framework/src/systems/LinearSystem.C
  modules/navier_stokes/doc/content/source/linearfvbcs/LinearFVConvectiveHeatTransferBC.md
  modules/navier_stokes/include/executioners/LinearAssemblySegregatedSolve.h
  modules/navier_stokes/include/executioners/SIMPLESolveBase.h
  modules/navier_stokes/include/executioners/SIMPLESolveNonlinearAssembly.h
  modules/navier_stokes/include/linearfvbcs/LinearFVConvectiveHeatTransferBC.h
  modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
  modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C
  modules/navier_stokes/src/executioners/SIMPLESolveBase.C
  modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C
  modules/navier_stokes/src/linearfvbcs/LinearFVConvectiveHeatTransferBC.C
  modules/navier_stokes/src/linearfvkernels/LinearWCNSFVMomentumFlux.C
  modules/navier_stokes/src/userobjects/RhieChowMassFlux.C
  modules/navier_stokes/test/tests/finite_volume/ins/cht/flow-around-square-linear-fluidonly.i
  modules/navier_stokes/test/tests/finite_volume/ins/cht/flow-around-square-linear.i
  modules/navier_stokes/test/tests/finite_volume/ins/cht/gold/flow-around-square-linear-fluidonly_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/cht/gold/flow-around-square-linear_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/cht/gold/tri.e
  modules/navier_stokes/test/tests/finite_volume/ins/cht/tests
Labels: PR: Failed but allowed

#30608 Don't use deprecated UserObjects syntax pressure corrector
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_fsp.i
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_fsp_diagonal_of_a_for_scaling.i
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_vector_fsp.i
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_vector_fsp_al.i
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_vector_fsp_elman.i
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/steady_vector_fsp_stokes.i
  modules/navier_stokes/test/tests/finite_element/ins/lid_driven/transient_fsp.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/lid-driven-two-phase.i
  modules/navier_stokes/test/tests/finite_volume/two_phase/mixture_model/rayleigh-bernard-two-phase.i
Labels: PR: Ready for review/merge
