Repository idaholab/moose, pull requests merged in 2025-01, with the labels that each got.

#29648 Fixing typos in MooseDocs documentation.
  python/MooseDocs/base/components.py
  python/doc/content/python/MooseDocs/extensions/acronym.md
  python/doc/content/python/MooseDocs/extensions/alert.md
  python/doc/content/python/MooseDocs/extensions/appsyntax.md
  python/doc/content/python/MooseDocs/extensions/core.md
  python/doc/content/python/MooseDocs/extensions/datetime.md
  python/doc/content/python/MooseDocs/extensions/gallery.md
  python/doc/content/python/MooseDocs/extensions/graph.md
  python/doc/content/python/MooseDocs/extensions/ifelse.md
  python/doc/content/python/MooseDocs/extensions/include.md
  python/doc/content/python/MooseDocs/extensions/katex.md
  python/doc/content/python/MooseDocs/extensions/listing.md
  python/doc/content/python/MooseDocs/extensions/media.md
  python/doc/content/python/MooseDocs/extensions/sqa.md
  python/doc/content/python/MooseDocs/extensions/table.md
  python/doc/content/python/MooseDocs/extensions/tag.md
  python/doc/content/python/MooseDocs/extensions/template.md
  python/doc/content/python/MooseDocs/index.md
  python/doc/content/python/MooseDocs/specification.md
Labels: PR: Failed but allowed

#29605 Add a debug option for controls
  framework/src/actions/SetupDebugAction.C
  test/tests/controls/output/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#29586 Enable VolumetricFlowRate for LinearFV
  modules/navier_stokes/include/postprocessors/VolumetricFlowRate.h
  modules/navier_stokes/include/userobjects/RhieChowFaceFluxProvider.h
  modules/navier_stokes/include/userobjects/RhieChowInterpolatorBase.h
  modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
  modules/navier_stokes/src/postprocessors/MassFluxWeightedFlowRate.C
  modules/navier_stokes/src/postprocessors/VolumetricFlowRate.C
  modules/navier_stokes/src/userobjects/RhieChowFaceFluxProvider.C
  modules/navier_stokes/src/userobjects/RhieChowInterpolatorBase.C
  modules/navier_stokes/src/userobjects/RhieChowMassFlux.C
  modules/navier_stokes/test/tests/postprocessors/flow_rates/conservation_LinearFV.i
  modules/navier_stokes/test/tests/postprocessors/flow_rates/gold/conservation_LinearFV_out.csv
  modules/navier_stokes/test/tests/postprocessors/flow_rates/tests
Labels: PR: Failed but allowed

#29001 Rename the Geometry-UOs to MoveNodes meshmodifier
  framework/doc/content/source/meshmodifiers/MoveNodesToSphere.md
  framework/doc/content/source/userobjects/GeometrySphere.md
  framework/include/meshmodifiers/MoveNodesToGeometryModifierBase.h
  framework/include/meshmodifiers/MoveNodesToSphere.h
  framework/src/meshmodifiers/MoveNodesToGeometryModifierBase.C
  framework/src/meshmodifiers/MoveNodesToSphere.C
  framework/src/userobjects/GeometrySphere.C
  test/tests/meshmodifiers/move_nodes_to_sphere/block.i
  test/tests/meshmodifiers/move_nodes_to_sphere/geometrysphere.i
  test/tests/meshmodifiers/move_nodes_to_sphere/gold/block_out.e-s004
  test/tests/meshmodifiers/move_nodes_to_sphere/gold/geometrysphere_out.e-s004
  test/tests/meshmodifiers/move_nodes_to_sphere/tests
Labels: PR: Ready for review/merge

#29640 Add time transformation
  framework/include/auxkernels/SolutionAux.h
  framework/include/auxkernels/SolutionScalarAux.h
  framework/include/functions/Axisymmetric2D3DSolutionFunction.h
  framework/include/functions/SolutionFunction.h
  framework/include/ics/ScalarSolutionIC.h
  framework/include/ics/SolutionIC.h
  framework/include/userobjects/SolutionUserObject.h
  framework/include/userobjects/SolutionUserObjectBase.h
  framework/src/auxkernels/SolutionAux.C
  framework/src/auxkernels/SolutionScalarAux.C
  framework/src/functions/Axisymmetric2D3DSolutionFunction.C
  framework/src/functions/SolutionFunction.C
  framework/src/ics/ScalarSolutionIC.C
  framework/src/ics/SolutionIC.C
  framework/src/postprocessors/ParsedPostprocessor.C
  framework/src/userobjects/SolutionUserObject.C
  framework/src/userobjects/SolutionUserObjectBase.C
  modules/optimization/include/userobjects/AdjointSolutionUserObject.h
  modules/optimization/src/userobjects/AdjointSolutionUserObject.C
  modules/phase_field/src/userobjects/SolutionRasterizer.C
  test/include/postprocessors/TestDiscontinuousValuePP.h
  test/src/postprocessors/TestDiscontinuousValuePP.C
  test/tests/auxkernels/solution_aux/gold/solution_aux_exodus_interp_out2.e
  test/tests/auxkernels/solution_aux/tests
Labels: PR: Failed but allowed

#29671 Removed redeclaration of _name attribute from MooseApp
  framework/include/base/MooseApp.h
Labels: PR: Failed but allowed

#29674 Add more information to restart error message which can be hit by users with a wrong setup
  framework/src/restart/RestartableEquationSystems.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#29668 Add a clean error on adding components with a regular / mesh generated mesh
  modules/thermal_hydraulics/src/actions/AddComponentAction.C
  modules/thermal_hydraulics/test/tests/misc/mesh_block_interaction/test.i
  modules/thermal_hydraulics/test/tests/misc/mesh_block_interaction/tests
Labels: PR: Ready for review/merge

#29686 Add test for checking global cli parameters across subapps
  unit/src/CommandLineTest.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#28388 Add Composite Power Law Creepfor multiphases
  modules/solid_mechanics/doc/content/source/materials/CompositePowerLawCreepStressUpdate.md
  modules/solid_mechanics/include/materials/CompositePowerLawCreepStressUpdate.h
  modules/solid_mechanics/src/materials/CompositePowerLawCreepStressUpdate.C
  modules/solid_mechanics/test/tests/power_law_creep/composite_power_law_creep.i
  modules/solid_mechanics/test/tests/power_law_creep/composite_power_law_creep_onePhaseMulti.i
  modules/solid_mechanics/test/tests/power_law_creep/composite_power_law_creep_plasticity.i
  modules/solid_mechanics/test/tests/power_law_creep/composite_power_law_creep_single_material.i
  modules/solid_mechanics/test/tests/power_law_creep/composite_power_law_creep_small_strain.i
  modules/solid_mechanics/test/tests/power_law_creep/gold/composite_power_law_creep_onePhaseMulti_tests_soln_0011.csv
  modules/solid_mechanics/test/tests/power_law_creep/gold/composite_power_law_creep_plasticity_tests_soln_0011.csv
  modules/solid_mechanics/test/tests/power_law_creep/gold/composite_power_law_creep_single_material_tests_soln_0011.csv
  modules/solid_mechanics/test/tests/power_law_creep/gold/composite_power_law_creep_small_strain_tests_soln_0011.csv
  modules/solid_mechanics/test/tests/power_law_creep/gold/composite_power_law_creep_tests_soln_0011.csv
  modules/solid_mechanics/test/tests/power_law_creep/tests
Labels: PR: Failed but allowed

#29691 Fixup a couple of inconsistencies in EM module SQA
  modules/doc/sqa_reports.yml
  modules/electromagnetics/doc/content/modules/electromagnetics/sqa/index.md
Labels: PR: Ready for review/merge

#28785 Optimization of nearest location transfer for nearest-subapp
  framework/include/partitioner/HierarchicalGridPartitioner.h
  framework/include/positions/MultiAppPositions.h
  framework/include/positions/Positions.h
  framework/include/transfers/MultiAppGeneralFieldNearestLocationTransfer.h
  framework/include/utils/KDTree.h
  framework/src/partitioner/GridPartitioner.C
  framework/src/partitioner/HierarchicalGridPartitioner.C
  framework/src/positions/FilePositions.C
  framework/src/positions/InputPositions.C
  framework/src/positions/Positions.C
  framework/src/transfers/MultiAppGeneralFieldNearestLocationTransfer.C
  framework/src/transfers/MultiAppGeneralFieldShapeEvaluationTransfer.C
  framework/src/transfers/MultiAppGeneralFieldTransfer.C
  framework/src/transfers/MultiAppGeneralFieldUserObjectTransfer.C
  framework/src/utils/KDTree.C
  test/tests/bcs/periodic/tests
  test/tests/partitioners/custom_partition_generated_mesh/custom_partition_generated_mesh.i
  test/tests/partitioners/custom_partition_generated_mesh/tests
  test/tests/partitioners/grid_partitioner/tests
  test/tests/partitioners/hierarchical_grid_partitioner/hierarchical_grid_partitioner_errors.i
  test/tests/partitioners/hierarchical_grid_partitioner/tests
  test/tests/reporters/mesh_info/mesh_info.i
  test/tests/transfers/general_field/nearest_node/nearest_app/gold/main_between_multiapp_out_ma10.e
  test/tests/transfers/general_field/nearest_node/nearest_app/gold/main_between_multiapp_out_ma11.e
  test/tests/transfers/general_field/nearest_node/nearest_app/gold/main_between_multiapp_out_ma20.e
  test/tests/transfers/general_field/nearest_node/nearest_app/gold/main_between_multiapp_out_ma21.e
  test/tests/transfers/general_field/nearest_node/nearest_app/gold/main_out.e
  test/tests/transfers/general_field/nearest_node/nearest_app/main.i
  test/tests/transfers/general_field/nearest_node/nearest_app/main_between_multiapp.i
  test/tests/transfers/general_field/nearest_node/nearest_app/sub.i
  test/tests/transfers/general_field/nearest_node/nearest_app/sub_between_diffusion.i
  test/tests/transfers/general_field/nearest_node/nearest_app/tests
  test/tests/transfers/general_field/shape_evaluation/regular/tests
  test/tests/vectorpostprocessors/point_value_sampler/tests
  unit/src/PositionsTest.C
Labels: PR: Ready for review/merge

#29714 Add capability to define multiple test spec file names in MooseDocs configurations
  modules/doc/content/newsletter/2025/2025_01.md
  modules/doc/training/content/sqa/training/lead/sqa_moosedocs.md
  python/moosesqa/SQARequirementReport.py
  python/moosesqa/test/specs/spec_multiple
  python/moosesqa/test/test_SQARequirementReport.py
Labels: PR: Failed but allowed

#29736 Skip --dump tests for valgrind
  test/tests/misc/check_error/tests
Labels: PR: Failed but allowed

#29738 Remove extraneous apptainer instance list
  python/TestHarness/schedulers/hpc_template
Labels: PR: Failed but allowed

#29593 Removed deprecated Closures enumerations
  modules/thermal_hydraulics/include/base/ThermalHydraulicsApp.h
  modules/thermal_hydraulics/include/components/FlowChannelBase.h
  modules/thermal_hydraulics/src/base/ThermalHydraulicsApp.C
  modules/thermal_hydraulics/src/components/FlowChannelBase.C
  modules/thermal_hydraulics/test/tests/closures/none_1phase/tests
  modules/thermal_hydraulics/test/tests/closures/simple_1phase/tests
Labels: PR: Failed but allowed

#29569 Add option to advect enthalpy instead of cp T for non constant cp fluids
  modules/fluid_properties/include/fluidproperties/NaClFluidProperties.h
  modules/fluid_properties/src/fluidproperties/NaClFluidProperties.C
  modules/fluid_properties/unit/src/NaClFluidPropertiesTest.C
  modules/navier_stokes/include/functormaterials/INSFVEnthalpyFunctorMaterial.h
  modules/navier_stokes/src/functormaterials/INSFVEnthalpyFunctorMaterial.C
  modules/navier_stokes/test/tests/finite_volume/materials/ergun/tests
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/1d_test_cpT.i
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/2d-steady-wall-balance.i
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/enthalpy_computation.i
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/gold/1d_test_cpT_out.csv
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/gold/2d-steady-wall-balance_out.csv
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/gold/enthalpy_computation_non_constant_cp_out.csv
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/gold/enthalpy_computation_out.csv
  modules/navier_stokes/test/tests/finite_volume/wcns/materials/tests
Labels: PR: Ready for review/merge

#29751 Misc occasional test failures fixups
  modules/contact/test/tests/pdass_problems/tests
  modules/navier_stokes/examples/laser-welding/tests
  modules/navier_stokes/test/tests/finite_volume/ins/turbulence/lid-driven/lid-driven-turb-capped-physics.i
  modules/optimization/examples/diffusion_reaction_XYDelaunay/tests
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/gold/pss_reduced.json
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/pss.i
  modules/stochastic_tools/test/tests/samplers/ParallelSubsetSimulation/tests
Labels: PR: Failed but allowed, PR: Ready for review/merge

#29752 Allow multiple (or no) Closures on a flow channel
  modules/thermal_hydraulics/doc/content/modules/thermal_hydraulics/tutorials/single_phase_flow/step06.md
  modules/thermal_hydraulics/doc/content/source/closures/FunctorClosures.md
  modules/thermal_hydraulics/doc/content/source/closures/WallTemperature1PhaseClosures.md
  modules/thermal_hydraulics/include/closures/ClosuresBase.h
  modules/thermal_hydraulics/include/closures/FunctorClosures.h
  modules/thermal_hydraulics/include/closures/WallTemperature1PhaseClosures.h
  modules/thermal_hydraulics/include/components/FlowChannelBase.h
  modules/thermal_hydraulics/include/components/HeatTransferBase.h
  modules/thermal_hydraulics/include/materials/ADAverageWallTemperature3EqnMaterial.h
  modules/thermal_hydraulics/include/materials/AverageWallTemperature3EqnMaterial.h
  modules/thermal_hydraulics/src/closures/Closures1PhaseBase.C
  modules/thermal_hydraulics/src/closures/Closures1PhaseNone.C
  modules/thermal_hydraulics/src/closures/FunctorClosures.C
  modules/thermal_hydraulics/src/closures/WallTemperature1PhaseClosures.C
  modules/thermal_hydraulics/src/components/FlowChannelBase.C
  modules/thermal_hydraulics/src/components/HeatTransfer1PhaseBase.C
  modules/thermal_hydraulics/src/components/HeatTransferBase.C
  modules/thermal_hydraulics/src/components/HeatTransferFromHeatStructure3D1Phase.C
  modules/thermal_hydraulics/src/materials/ADAverageWallTemperature3EqnMaterial.C
  modules/thermal_hydraulics/src/materials/AverageWallTemperature3EqnMaterial.C
  modules/thermal_hydraulics/test/tests/closures/functor_closures/functor_closures.i
  modules/thermal_hydraulics/test/tests/closures/functor_closures/gold/functor_closures_out.csv
  modules/thermal_hydraulics/test/tests/closures/functor_closures/tests
  modules/thermal_hydraulics/test/tests/closures/wall_temperature_1phase/base.i
  modules/thermal_hydraulics/test/tests/closures/wall_temperature_1phase/gold/multiple_out.csv
  modules/thermal_hydraulics/test/tests/closures/wall_temperature_1phase/gold/single_out.csv
  modules/thermal_hydraulics/test/tests/closures/wall_temperature_1phase/multiple.i
  modules/thermal_hydraulics/test/tests/closures/wall_temperature_1phase/single.i
  modules/thermal_hydraulics/test/tests/closures/wall_temperature_1phase/tests
  modules/thermal_hydraulics/test/tests/components/flow_component_ns/flow_component_ns_pinc.i
  modules/thermal_hydraulics/test/tests/materials/ad_average_wall_temperature_3eqn/ad_average_wall_temperature_3eqn.i
  modules/thermal_hydraulics/test/tests/materials/average_wall_temperature_3eqn/average_wall_temperature_3eqn.i
  modules/thermal_hydraulics/tutorials/single_phase_flow/06_custom_closures.i
Labels: PR: Failed but allowed

#29603 Let us control the pressure action
  framework/src/base/MooseBaseParameterInterface.C
  modules/solid_mechanics/doc/content/source/actions/PressureAction.md
  modules/solid_mechanics/src/actions/PressureAction.C
  modules/solid_mechanics/test/tests/pressure/gold/pressure_control_test_out.e
  modules/solid_mechanics/test/tests/pressure/pressure_control_test.i
  modules/solid_mechanics/test/tests/pressure/tests
Labels: PR: Ready for review/merge

#29641 Add an option for a functionalized cp for TemperaturePressureFunctionFP
  modules/fluid_properties/doc/content/source/fluidproperties/TemperaturePressureFunctionFluidProperties.md
  modules/fluid_properties/include/fluidproperties/TemperaturePressureFunctionFluidProperties.h
  modules/fluid_properties/src/fluidproperties/SimpleFluidProperties.C
  modules/fluid_properties/src/fluidproperties/TemperaturePressureFunctionFluidProperties.C
  modules/fluid_properties/test/tests/temperature_pressure_function/gold/example_out.csv
  modules/fluid_properties/unit/include/TemperaturePressureFunctionFluidPropertiesTest.h
  modules/fluid_properties/unit/src/BrineFluidPropertiesTest.C
  modules/fluid_properties/unit/src/TemperaturePressureFunctionFluidPropertiesTest.C
Labels: PR: Ready for review/merge

#29516 Add PIMPLE transient solve for linearFV
  framework/include/multiapps/TransientMultiApp.h
  framework/include/outputs/ProgressOutput.h
  framework/include/postprocessors/RelativeSolutionDifferenceNorm.h
  framework/include/systems/LinearSystem.h
  framework/include/systems/SystemBase.h
  framework/include/timesteppers/TimeStepper.h
  framework/src/actions/AddTimeStepperAction.C
  framework/src/actions/ComposeTimeStepperAction.C
  framework/src/actions/SetupPredictorAction.C
  framework/src/actions/SetupTimeStepperAction.C
  framework/src/base/MooseObject.C
  framework/src/linearfvkernels/LinearFVFluxKernel.C
  framework/src/multiapps/FullSolveMultiApp.C
  framework/src/multiapps/MultiApp.C
  framework/src/multiapps/TransientMultiApp.C
  framework/src/outputs/ProgressOutput.C
  framework/src/postprocessors/NumFailedTimeSteps.C
  framework/src/postprocessors/PseudoTimestep.C
  framework/src/postprocessors/RelativeSolutionDifferenceNorm.C
  framework/src/predictors/Predictor.C
  framework/src/systems/LinearSystem.C
  framework/src/systems/SystemBase.C
  framework/src/times/TimeIntervalTimes.C
  framework/src/timesteppers/TimeStepper.C
  framework/src/variables/MooseLinearVariableFV.C
  modules/navier_stokes/doc/content/bib/navier_stokes.bib
  modules/navier_stokes/doc/content/source/executioners/PIMPLE.md
  modules/navier_stokes/examples/flow-over-circle/flow_over_circle_linearfv.i
  modules/navier_stokes/examples/flow-over-circle/gold/flow_over_circle_linearfv_out.csv
  modules/navier_stokes/examples/flow-over-circle/mesh.i
  modules/navier_stokes/examples/flow-over-circle/tests
  modules/navier_stokes/include/executioners/LinearAssemblySegregatedSolve.h
  modules/navier_stokes/include/executioners/PIMPLE.h
  modules/navier_stokes/include/executioners/PIMPLESolve.h
  modules/navier_stokes/include/executioners/SIMPLESolve.h
  modules/navier_stokes/include/executioners/SIMPLESolveBase.h
  modules/navier_stokes/include/executioners/SIMPLESolveNonlinearAssembly.h
  modules/navier_stokes/include/userobjects/RhieChowMassFlux.h
  modules/navier_stokes/include/utils/FaceCenteredMapFunctor.h
  modules/navier_stokes/src/executioners/LinearAssemblySegregatedSolve.C
  modules/navier_stokes/src/executioners/PIMPLE.C
  modules/navier_stokes/src/executioners/PIMPLESolve.C
  modules/navier_stokes/src/executioners/SIMPLE.C
  modules/navier_stokes/src/executioners/SIMPLESolve.C
  modules/navier_stokes/src/executioners/SIMPLESolveNonlinearAssembly.C
  modules/navier_stokes/src/userobjects/RhieChowMassFlux.C
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/2d/2d-boussinesq-transient.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/2d/gold/2d-boussinesq-transient-piso_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/2d/gold/2d-boussinesq-transient_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/2d/tests
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/common-blocks.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/compare.cmp
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/gold/pimple_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/gold/piso_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/gold/simple_out.e
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/pimple.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/simple.i
  modules/navier_stokes/test/tests/finite_volume/ins/channel-flow/linear-segregated/steady-transient-compare/tests
  modules/optimization/src/userobjects/DensityUpdateTwoConstraints.C
  modules/thermal_hydraulics/src/base/Simulation.C
Labels: PR: Failed but allowed
