Repository idaholab/moose, pull requests merged in 2025-09, with the labels that each got.

#31314 Made scalar variables functors
  framework/doc/content/syntax/Functors/index.md
  framework/include/variables/MooseVariableBase.h
  framework/include/variables/MooseVariableField.h
  framework/include/variables/MooseVariableScalar.h
  framework/src/systems/SystemBase.C
  framework/src/variables/MooseVariableBase.C
  framework/src/variables/MooseVariableField.C
  framework/src/variables/MooseVariableScalar.C
  test/tests/functors/scalar_variable/gold/test_out.csv
  test/tests/functors/scalar_variable/test.i
  test/tests/functors/scalar_variable/tests
Labels: PR: Failed but allowed

#31389 switch from absoluteFuzzyEqual to relative in the fillGeneralOrthotro…
  framework/include/utils/RankFourTensorImplementation.h
Labels: PR: Failed but allowed

#31396 Only print trace and abort from a single thread
  framework/include/base/MooseError.h
  framework/src/base/MooseError.C
Labels: PR: Ready for review/merge

#31430 Avoid empty sends in MeshInfo
  framework/src/reporters/MeshInfo.C
Labels: PR: Failed but allowed

#31395 Add parameter registration and optimize Builder
  framework/include/actions/GlobalParamsAction.h
  framework/include/base/Moose.h
  framework/include/parser/Builder.h
  framework/include/parser/ParameterRegistration.h
  framework/include/parser/ParameterRegistry.h
  framework/include/utils/InputParameters.h
  framework/include/utils/MooseStringUtils.h
  framework/include/utils/MooseTypes.h
  framework/include/utils/MooseUnitUtils.h
  framework/include/utils/MooseUtils.h
  framework/moose.mk
  framework/src/actions/GlobalParamsAction.C
  framework/src/base/Moose.C
  framework/src/base/MooseServer.C
  framework/src/interfaces/DataFileInterface.C
  framework/src/meshmodifiers/TimedSubdomainModifier.C
  framework/src/parser/Builder.C
  framework/src/parser/ParameterRegistration.C
  framework/src/parser/ParameterRegistry.C
  framework/src/utils/InputParameters.C
  framework/src/utils/MooseUtils.C
  modules/reactor/include/meshgenerators/SubdomainExtraElementIDGenerator.h
  modules/reactor/src/meshgenerators/SubdomainExtraElementIDGenerator.C
  modules/reactor/test/tests/meshgenerators/subdomain_extra_element_id_generator/gold/subdomain_elem_ids_test_out.e
  modules/reactor/test/tests/meshgenerators/subdomain_extra_element_id_generator/subdomain_elem_ids_test.i
  modules/reactor/test/tests/meshgenerators/subdomain_extra_element_id_generator/tests
  test/tests/misc/check_error/bad_number.i
  test/tests/misc/check_error/tests
  test/tests/parser/map_param/tests
  test/tests/parser/vector_range_checking/tests
  test/tests/reporters/base/tests
  unit/src/InputParametersTest.C
  unit/src/MinimalApp.C
  unit/src/ParameterRegistrationTest.C
  unit/src/ParameterRegistryTest.C
Labels: PR: Ready for review/merge

#31029 Add MooseServer plotting as NEAMS Workbench protocol extension
  conda/moose-dev/conda_build_config.yaml
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  conda/wasp/meta.yaml
  framework/contrib/hit/Makefile
  framework/include/base/MooseServer.h
  framework/moose.mk
  framework/src/base/MooseServer.C
  scripts/configure_wasp.sh
  scripts/tests/versioner_hashes.yaml
  scripts/versioner.yaml
  unit/src/MooseServerTest.C
Labels: PR: Failed but allowed

#31433 Fix a typo in DofCopyTransfer and address issue #30988 in MultiAppGeneralFieldTransfer
  framework/src/transfers/MultiAppDofCopyTransfer.C
  framework/src/transfers/MultiAppGeneralFieldTransfer.C
  test/tests/transfers/general_field/nearest_node/regular/tests
Labels: PR: Failed but allowed

#31449 Make executable name configurable
  python/TestHarness/tests/TestHarnessTestCase.py
Labels: PR: Failed but allowed

#31463 Support partial homogenization constraint in SolidMechanics physics
  modules/solid_mechanics/src/physics/QuasiStaticSolidMechanicsPhysics.C
  modules/solid_mechanics/test/tests/lagrangian/cartesian/total/homogenization/action/2d_pbc_symmetry.i
  modules/solid_mechanics/test/tests/lagrangian/cartesian/total/homogenization/action/gold/2d_pbc_symmetry_out.e
  modules/solid_mechanics/test/tests/lagrangian/cartesian/total/homogenization/action/tests
Labels: PR: Failed but allowed

#31460 Rework DG/HDG execution logic to limit warehouse and shoudlExecute calls
  framework/include/loops/NonlinearThread.h
  framework/src/loops/NonlinearThread.C
Labels: PR: Failed but allowed

#31278 Support Newmark-Beta time integration in FSI ALE simulation
  framework/src/auxkernels/VectorVariableComponentAux.C
  modules/fsi/doc/content/source/interfacekernels/ADPenaltyVelocityContinuityNewmarkBeta.md
  modules/fsi/include/interfacekernels/ADPenaltyVelocityContinuity.h
  modules/fsi/include/interfacekernels/ADPenaltyVelocityContinuityNewmarkBeta.h
  modules/fsi/src/interfacekernels/ADPenaltyVelocityContinuity.C
  modules/fsi/src/interfacekernels/ADPenaltyVelocityContinuityNewmarkBeta.C
  modules/fsi/test/tests/2d-small-strain-transient/fsi_flat_channel.i
  modules/fsi/test/tests/2d-small-strain-transient/tests
  modules/fsi/test/tests/newmark-beta/gold/test_ALE_csv.csv
  modules/fsi/test/tests/newmark-beta/test_ALE.i
  modules/fsi/test/tests/newmark-beta/tests
  modules/fsi/test/tests/newmark-beta/tmesh_HR.msh
  modules/solid_mechanics/doc/content/source/physics/DynamicSolidMechanicsPhysics.md
  modules/solid_mechanics/include/kernels/InertialForce.h
  modules/solid_mechanics/src/kernels/InertialForce.C
Labels: PR: Failed but allowed, PR: Ready for review/merge

#31536 Update code-server in apptainer moose-dev
  apptainer/files/moose-dev/opt/code-server/bin/code-server-start
  apptainer/moose-dev.def
  conda/moose-dev/meta.yaml
  conda/moose/conda_build_config.yaml
  scripts/tests/versioner_hashes.yaml
  scripts/versioner.yaml
Labels: PR: Failed but allowed, PR: Updates packages

#31538 Improve Kokkos initialization settings
  framework/src/kokkos/base/KokkosMooseInit.K
Labels: PR: Failed but allowed

#31546 Put libmesh libraries after capabilities sources
  framework/moose.mk
Labels: PR: Failed but allowed

#31311 Add `--only-tests-that-require` to TestHarness
  modules/doc/content/newsletter/2025/2025_09.md
  python/TestHarness/TestHarness.py
  python/TestHarness/testers/Tester.py
  python/TestHarness/tests/TestHarnessTestCase.py
  python/TestHarness/tests/test_GetExecutable.py
  python/TestHarness/tests/test_OnlyTestsThatRequire.py
  python/TestHarness/tests/test_Replay.py
  python/TestHarness/tests/tests
  python/pycapabilities/__init__.py
Labels: PR: Failed but allowed, PR: Ready for review/merge

#31557 Remove libmesh dependency for capabilities library and fix test
  framework/build.mk
  framework/include/utils/MooseStringUtils.h
  framework/moose.mk
  python/pycapabilities/tests/test_capabilities.py
Labels: PR: Ready for review/merge

#31574 Use a stronger preconditioner for more reproducible results at high MPI count
  test/tests/kernels/conservative_advection/no_upwinding_1D.i
Labels: PR: Ready for review/merge

#31623 Avoid neighbor side material property computations on all sidesets
  framework/include/problems/FEProblemBase.h
  framework/src/loops/NonlinearThread.C
  framework/src/problems/FEProblemBase.C
  test/src/materials/ErrorMaterial.C
Labels: PR: Ready for review/merge
